### ISSUE TITLE
Mention StreetComplete in manually created notes

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1012]
In https://github.com/westnordost/StreetComplete/issues/905#issuecomment-379839031 we discovered SC does not add some string to manually created notes. IMHO, this is a must-have.

One just needs to find out. That is a good thing both for the SC development and for OSM mappers, as they then know how one collected the data they want to add (e.g.) via a note. (so one can e.g. be quite assured it was no wheelchair mapping)

I consider this quite high-priority, as it prevents @ENT8R's [NotesReview](https://github.com/ENT8R/NotesReview) and any evaluation of the manually created notes by SC, which is e.g. necessary for https://github.com/westnordost/StreetComplete/issues/905.

**Comment by westnordost** [comment]
I don't. The feature is the same as leaving a note on the openstreetmap.org website and also uses similar wording. The feature on the website also does not add any string to the user's message.

Putting #StreetComplete into each and every "free text" note (not speaking of "leave a note instead"-Feature) might come across like an advertisement.
Instead, StreetComplete correctly sets the http user agent when posting the note.

**Comment by RubenKelevra** [comment]
Well, notes created a bit trouble and confusion, because I missed details. I think we might not need to add an "ad" but details the user creating have, but the reader don't.

Example:

I see a street, click on the task for surface, but the way is too long and in reality the surface change.

I leave a note: In the south it's different than in the north, this way needs to be split.

The reader of this ticket is maximal confused causing him to ask me. If the creator is a newbie he might be confused by the email he receives, too.

Sure, both might learn after such an instance, how to handle it the next time, but I think we can do better!

---

When we create a note which is the "last resort" of a not solveable quest, we should add the details about it. If the object got a name, we should add this too - as well as the id - helping in complex situations by adding more context which element is meant.

An example for the surface task:

> The surface information quest for street Brückenweg (id:12345) couldn't been easily solved by this user, he added the following comment on that:
> 
> In the south it's different than in the north, this way needs to be split. 

We should display this "introduction" with a ckeckbox to let the user remove it. 🙂

**Comment by westnordost** [comment]
> I see a street, click on the task for surface, but the way is too long and in reality the surface change.
> I leave a note: In the south it's different than in the north, this way needs to be split.

Why do you not click on "Can't answer" to leave a note in that case?

**Comment by RubenKelevra** [comment]
I did, but sometimes the note is added very near to a crossing, makes it hard to spot what the user creating it meant. That's why a ID/name would be nice.

The task I solved or tried to, as SC user isn't added by SC to the note. So as a user creating it I know what I'm talking about, but the user which needs to solve the task might be completely puzzled, because he might not know exactly why I add this note - since the information about the not solveable task isn't transfered.

BTW:
The situation in my case was even worse, the other user responded, that I'm a pretty veteran mapper and he doesn't get why I'm creating this note instead of solving it myself. I explained him, that I've created it by an App on the go which haven't the capability to edit this complex situations.

But it shows how much time the other user invested - instead of just splitting the way, adding both surface tags, he read my profile.

**Comment by rugk** [comment]
Just to be sure:
* actually the "can't answer" always adds StreetComplete to the note and even mentions the quest, AFAIK. So this is not what this issue is about.
* it's about the manually created more with the bottom left button

So my reason to still add sc name or some tag there (and even if it it's just "#createdbysc", which is unique but not directly an ad), is that we need that for evaluations and the one, who answers needs it so the note can be solved faster.

Sc is just very different from the osm website, where everyone can add a note.

E.g. say I add a note that a bench is missing there. The one who reads the note, now somehow has to check where the claim is right. Or at least it may be useful…
So when they see the note has been created by sc, they can at least now that the user very likely was there and did see the thing he made a note about. That's an important information!
The user could also made the note because of satellite images or whatever… in this case the note has to be treated complety different.

Of you want also just add a general " note created, while I was at `gps coordinates `"or something as general, so it does not directly advertise sc. (Although I personally had nothing against such an "advertisement").
But it also should be easy to find when searching all notes, so we know what notes have been created by SC. As explained e.g. for @ENT8R's review tool, which can only detect these answered by " can't answer " right now. And to measure the effectiveness of the notes and find out for what they are used. So this issue here is also blocking #905. There is no way to solve #905 without being able to look at the sc notes and find out how they are used.

**Comment by RubenKelevra** [comment]
Okay, then might I had used the left-down button feature in this case :)

**Comment by rugk** [comment]
>  might I had used the left-down button feature in this case

Sorry, but what?

**Comment by westnordost** [comment]
Ok the app will add

```

via StreetComplete 5.0-beta1
```

to the end of the message, then.

**Comment by rugk** [comment]
Yeah, mentioning the version number is, of course, also a good idea… :laughing: :+1:
