### ISSUE TITLE
Include relations in search for parking areas

### ISSUE THREAD

**Issue by BjornRasmussen** [westnordost/StreetComplete#1033]
After using StreetComplete, I have noticed that it does not edit Multipolygons.  In my town, many parking lots are added as multipolygons due to the presence of buildings in the center of them.  As far as I can tell, missing tagging in these parking lots is not noticed by StreetComplete.

**Comment by ENT8R** [comment]
This is because the query does not search for them. The current query for the parking type looks like this:
https://github.com/westnordost/StreetComplete/blob/00072402b52431e78e51df0165153dffa556f24d/app/src/main/java/de/westnordost/streetcomplete/quests/parking_type/AddParkingType.java#L24

Which means that it searches only for points and normal areas with the tag `amenity=parking` and without the tag `parking=*`. I'm not sure what the wiki article says about mapping parkings as realtions (multipolygons) as it says: "use on relations unspecified". But IMO they can be included and one just needs to add a single word to the query: `nodes, ways, relations with amenity=parking and !parking`
But it also does not make sense to add this to every quest.
Is there some reason that we didn't include relations or did we just forgot it? 😄

**Comment by matkoniecz** [comment]
> as it says: "use on relations unspecified"

It has "may be used on areas" (what includes multipolygons) at https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparkingm . 

and anyway, amenity=parking is widely used on multipolygons so if wiki claimed otherwise it should be changed

**Comment by westnordost** [comment]
Should also be checked for the other (parking) quests if also looking for releations (=multipolygons) makes sense.
