### ISSUE TITLE
Do not show own notes which were added through "Can't say" flow

### ISSUE THREAD

**Issue by jancborchardt** [westnordost/StreetComplete#1071]
When you follow the "Can't say" flow on an element you are prompted to optionally add a note.

Now when you later rescan and maybe on the next day go the same route, your own note will show up. That doesn't make a lot of sense since you of course can't add anything to it cause you already opened it.

Basically, notes you added yourself (especially through StreetComplete) which have no further comments should be filtered out and not shown.

**Comment by rugk** [comment]
First: Do you have the "Show all notes" option in the settings enabled? If not, would you accept it, if it shows these notes, if this setting is enabled or should it still filter them out?

Your suggestion is quite funny, because some other users (namely @blipp) [suggested actually the contrary](https://github.com/westnordost/StreetComplete/issues/962#issuecomment-383323490) and were disappointed, because the "can't say" notes did not pop-up immediately.

That said, I personally do not really care about the behaviour of "can't say" notes. When the "show notes" option is enabled this may be shown for completeness indeed.
I could however, in general, imagine, that your notes you created yourself may shown **with a different icon** (i.e. the `!` icon, which already exists for the button to create your own note).
These things are just important for me, because of https://github.com/westnordost/StreetComplete/issues/962, i.e. showing manually created notes. But I know, this issue is about something else.

**Comment by rugk** [comment]
> I think it was default?

Just FYI: It's not. :smiley: 
BTW about that NextCloud thing: Great to hear, I finally get rid of these notifications then, which I also just click away. :smile: 

But back to topic: I doubt that the situation can be compared with NextCloud. Anyway, well… actually I don't really care.

**Comment by westnordost** [comment]
Well then  disable that option and the problem is solved.

Am 15. Mai 2018 23:04:05 MESZ schrieb rugk <notifications@github.com>:
>> I think it was default?
>
>Just FYI: It's not. :smiley: 
>BTW about that NextCloud thing: Great to hear, I finally get rid of
>these notifications then, which I also just click away. :smile: 
>
>But back to topic: I doubt that the situation can be compared with
>NextCloud. Anyway, well… actually I don't really care.

**Comment by jancborchardt** [comment]
Sure, makes sense.
