### ISSUE TITLE
increase MIN_DIST_TO_CYCLEWAYS or exclude bicycle=use_sidepath ways from bikeway quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1084]
https://www.openstreetmap.org/way/244968825 is over 15m from https://www.openstreetmap.org/way/298887264 so it appears in the bikeway quest despite that it has cycleway tagged along it

present bicycle=use_sidepath hints that there is a separately mapped cycleway, and this tag appears to have some usage (about 60k usages according to https://taginfo.openstreetmap.org//search?q=bicycle%3Duse_sidepath ) so it may be worth supporting

There is also bicycle:forward=use_sidepath and bicycle:backward=use_sidepath with some small usage that may be also added for completeness

**Comment by matkoniecz** [comment]
I may make a PR but I want to check what is preferred

- increasing MIN_DIST_TO_CYCLEWAYS
- exclude bicycle=use_sidepath
- exclude bicycle=use_sidepath and bicycle:forward=use_sidepath and bicycle:backward=use_sidepath
- doing nothing and closing as not worth fixing
- some combinations of possible solutions

**Comment by westnordost** [comment]
Mh damn, a sad evidence that geospatial analysis for finding out what un-`relation`ed features belong to each other can never be precise. Your suggestions also only mitigate the underlying issue, but we have to work with what he have.
I think it makes sense to exclude roads with `bicycle=use_sidepath` and the forward/backward variants (if actually used). 
~~I would also definitely exclude roads tagged with [`cycleway=sidepath`](https://wiki.openstreetmap.org/wiki/Tag%3Acycleway%3Dsidepath) and variants, since this actually more precisely carries exactly the information we are after.~~ Nevermind, it is already excluded, naturally.

**Comment by matkoniecz** [comment]
> and the forward/backward variants (if actually used)

usage is not high, but it should not make code worse (it is one line more, without need for an additional explanation)

and these tags are really used - for example I used them in some cases and from taginfo I see that I am far from being main user of this tags.
