### ISSUE TITLE
Expand quest for building characteristics to all buildings

### ISSUE THREAD

**Issue by gsurrel** [westnordost/StreetComplete#109]
I feel like the quest asking for building height only consider the "building=yes". It would be nice to expand to "building=*".

**Comment by westnordost** [comment]
They specifically do not consider building=yes. They only consider 
house|residential|apartments|detached|terrace|farm|hotel|dormitory|houseboat|school|civic|college|university|public|hospital|kindergarten|transportation|train_station|retail|commercial|warehouse|industrial|manufacture

And this is intended.

It is not reasonable to ask for an "unspecified building" how many levels it has, because perhaps it does not have levels. How many levels does this church have, how many levels these garages etc? 
I want the least amount of "false positive" quests in the app as possible. 

However, a "what type of building" quest is planned, that replaces the building=yes bulidings with more specific buildings. From there on, the building level quest can be asked.

**Comment by gsurrel** [comment]
Fair explanation :)

Therefore, I do not understand why the buildings in EPFL are not suggested for the number for stories (geo:46.519276,6.5639663?z=17
http://osmand.net/go?lat=46.519276&lon=6.5639663&z=17)

I also have the same behavior near this train station: geo:46.53781,6.5832553?z=19
http://osmand.net/go?lat=46.53781&lon=6.5832553&z=19

I know there are many notes around but even when zooming to the maximum on the specific buildings, they do not show up. 

No matter what, thanks a lot for the app, I love it :)

**Comment by westnordost** [comment]
They are not considered because they are tagged with `building=yes`+`amenity=university`. This is wrong, it should be `building=university`.
As for the train station, the quest is not shown because the building levels were already added by use Xinfe 8 hours ago (with StreetComplete).
