### ISSUE TITLE
Download all new quest

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#1091]
Right now, when checking for new quest, streetcomplete only download 3 quests (from what I read in some issue discussion) every time we check for new quest. It would be great to have an option allowing to download all new quest at once and not only 3 quest. 
It's kind of a bother to download every available quest of an area right now as we have to check from time to time to relaunch the download, whereas we could just launch the new option and wait a bit then go for a walk and complete every available quest.

**Comment by matkoniecz** [comment]
Note that it was done to limit calls to overpass server that responds to querries.

Also, note that with less tha 12 quests for km2 futher should be downloaded automatically, beyond default limit - see https://github.com/westnordost/StreetComplete/blob/3f327ca1a70d2663c9363e4022bdfdad6d9ad5bc/app/src/main/java/de/westnordost/streetcomplete/data/download/WifiAutoDownloadStrategy.java#L36

**Comment by Dostoi** [comment]
So adding an option to download all available isn't something you'd like to do ?
I can totally understand, just want to be sure as you didn't say yes or no ^^

Yes it's a great feature but isn't exactly what I'm looking for. I'd like to be able to easily download all (and not some) available quest in an area to know that I don't have to pass several time in a street to complete all quest of the street (as other available quest would only be downloaded later on)

**Comment by matkoniecz** [comment]
> So adding an option to download all available isn't something you'd like to do ?

Note, I am not the author and I am not making decisions here. I just noticed it in my notification feed and I known at least part of reason for why it is like it is.

I wonder whatever I should start to include "not an an author or person who makes decisions here" in my comments.

>  I can totally understand, just want to be sure as you didn't say yes or no ^^

See above, I am not the person who makes decisions here.

**Comment by matkoniecz** [comment]
I would consider raising this limits, this limit was also irritating for me - especially in places with limited or no mobile internet access.

**Comment by Dostoi** [comment]
> Note, I am not the author and I am not making decisions here. I just noticed it in my notification feed and I known at least part of reason for why it is like it is.

No problem, I assumed as you were the first one to respond. 
I'll wait for others answer then :)

**Comment by westnordost** [comment]
You mean the "3 quests" limit?

**Comment by Dostoi** [comment]
Yes this one. Having an option to download all quest until there's no more new quest available.
Like looping on the already existing option.

**Comment by westnordost** [comment]
The reason why the app only retrieves the quests piece by piece currently is two-fold:
1. to not overwhelm the users with "things to do" (quests)
2. to not over-use the Overpass-API

Regarding 2, I asked the maintainer of the (main) overpass instance and there is a lot of room for more, so actually there would be no problem in downloading more quests and/or re-downloading them in more frequent intervals.

The real reason is that the app is designed to be casual, it should not feel like work, but rather be fun. (I know, it is rather frugal still on the fun part, but I do plan to add some more animations, pretty pictures, rewards, perhaps even small games/toys).
It's not supposed to be another QA tool that shows bazillions of issues on the map, but feeds things to do to the user one-by-one while trying to keep the balance between keeping him busy if he wants to be busy but not overwhelm him with work. The app is supposed to be going-for-a-walk compatible.
To my experience, a "full survey" _does_ feel like work and if the aim of this app was to provide a tool for that, one might just as well use Vespucci directly or resort to field papers.
I can understand the urge to solve everything completely, ticking off everything there is to do in a street/area, but in truth, mapping OpenStreetMap is never complete, because once one has recorded every possible information, some others may be outdated already.

**Comment by rugk** [comment]
Oh, that explanation actually surprised me. So the whole restriction is actually more one from a usability perspective than from a technical one.

IMHO, it is somewhat counterprodutive, because:
* at least heavy users of the app would really like to try out new quests, so they want to see many
* a big number of quests is too much, indeed, but it's even worse to only see **3 types of quests**. The app looks so "lame" then…
* A better idea may just be to limit the amount of quests per type, which are being downloaded/shown. This way, we can show the "diversity" of the quests/of the app and what users can all do.
* Maybe the limit in general is only useful for new users. When you get to use to the app, you know, IMHO; which quests you like to solve and which quests you can ignore…
    So, personally, I don't "solve everything completely, ticking off everything there", but just know which ones to pick out. Usually I just pick the ones out, which are quite rare, because stuff like opening hours (in a big cities) or just the building levels are not so 
* When users don't know this limit is there, it may all look like a bug or so. Or 

Personally this results in the fact that I **always** press the "download new quests" button 4-5 times when I am in a new area.

**Comment by westnordost** [comment]
> a big number of quests is too much, indeed, but it's even worse to only see 3 types of quests. The app looks so "lame" then…
> A better idea may just be to limit the amount of quests per type, which are being downloaded/shown. This way, we can show the "diversity" of the quests/of the app and what users can all do.

I agree with this. However, that may be a technical problem, because the quests are strictly ordered by their importance.

But all in all, we can maybe increase the number of quests downloaded in one go and/or increase the number of "minumum" quests until a new batch of quests is downloaded.

**Comment by matkoniecz** [comment]
>  To my experience, a "full survey" does feel like work and if the aim of this app was to provide a tool for that, one might just as well use Vespucci directly or resort to field papers.

Note that at least some (for example me) consider survey using SC far more efficient than using Vespucci (and so much better than field papers that it is amazing).

> Personally this results in the fact that I always press the "download new quests" button 4-5 times when I am in a new area. I accepted to do this, if this is a technical limit, but as a design decision, this is not good, IMHO.

And I modified the behavior to download (on wifi) always all available quest types in one go for a given area.

**Comment by Dostoi** [comment]
> to not overwhelm the users with "things to do" (quests)

Having an extra button in the menu bellow the existing one or allowing in the option menu to switch the default behavior of the existing menu would allow user to choose if they want to only have a few quest or really all available.
Putting it in the option menu with other parameter would only make it available to user who go to the trouble of looking in the option menu and testing the parameters (and I don't think a lot of users do that).

**Comment by mahdi1234** [comment]
I do totally agree with previous comment, nothing against surface, but when I'm in city, I don't expect anything else than asphalt (and I guess all nav apps do the same). I don't have internet on the go, so I make surface and make most as urban limit, then when I return "home" more appears ... it's exactly same with opening hours and whatever else reveals later on, probably not big deal in area I live in, but during one stop visit hmm probably miss lot of what could have been done, just my 2 cents anyway :) ... please add "advanced" download option for those who want more.

**Comment by Ekleog** [comment]
I am the new user @matkoniecz mentioned. (~1 week of contribution to OSM, even though I had installed and dismissed StreetComplete a few months ago -- see below for why and why I now get it was an error)

So basically my issues with StreetComplete have been in two categories:
 1. When zooming out with default config I see only road surface quests and a few speed limit tests
 2. Zooming in/out makes quests appear/vanish

Honestly, I don't get the point of zooming out making quests vanish. When I go for a walk, I can solve a quest every X meters. That doesn't depend on the zoom factor. Quite the contrary, before going to a walk I like to zoom out and have a look at where I'll have most quests, and maybe adapt my path to handle interesting ones. Having almost no quest visible when zoomed-out means I can't do that.

If the zoom-out-means-fewer-quests-displayed is for not overflowing the screen with quests, then I'd argue in favor of just not displaying any quest when too zoomed-out, and instead display a heatmap of how many quests / what importance of quests there are. Because anyway the quest display is un-usable to me in its current form.

Oh, and the “Quest selection” menu should be at the top of the “Settings” screen, not hidden behind the scary-sounding “Advanced” section. I discovered its existence only thanks to @matkoniecz telling me it existed on a Vespucci issue, as I usually don't look in the “Advanced” portion of the config until having gotten used to an application, and StreetComplete never went past “getting used to it”, as I felt like it was useless due to the kind of quests proposed.

For a newcomer (esp. urban) like me, road surface type is gadget. Opening hours, cycleways, parking metadata or wheelchair accessibility are all quests that sound much more useful. So changing the default ordering may bring in more users (well, it'd likely have brought at least one more a few months ago: me)

Hope this helps!

**Comment by rugk** [comment]
That heat map thing has been discussed in https://github.com/westnordost/StreetComplete/issues/869 and cannot currently be done.

Everything else is something I strongly support. Also making the config option more visible is a nice idea.

**Comment by Kjarrval** [comment]
Are the quests types downloaded for each area prioritised based on the "Quest selection" order?

Based on my experience it feels like it doesn't because I've been moving through areas without my priority quests displaying and then they suddenly appear on a later trip. Sometimes I've been travelling on buses for various purposes and have been checking the bus stops on StreetComplete while I do to fill in any missing information I can observe from my seat. Even though bus stop-related quests are on the top of the priority list, they are not always displayed. Not knowing about the 3 quest limit I assumed the information had already been gathered, only to find out in later trips through the same area they display as usual.

The case of not overloading the OverPass servers sounds reasonable so I'm not advocating that suggestion (at this time). Perhaps there is a solution to improve the balance of making it possible for the user to endeavour on a quest to exhaust a specific type of quest in their area versus the needs of users who want more variation. One idea is to have the default as it is now but add an option which would make the answer to the first question in my reply to be "yes".

**Comment by rugk** [comment]
> Are the quests types downloaded for each area prioritised based on the "Quest selection" order?

AFAIK, yes, they are.

**Comment by matkoniecz** [comment]
Yes, quests are downloaded in the same order as displayed.

**Comment by westnordost** [comment]
So I increased the number of quests that are downloaded in one go. Regarding mixing up the display of the different quest types to be displayed not strictly in the order in which they were downloaded (=in which they are specified in the options), I am totally not sure about that, because people might think this is a bug.

**Comment by rugk** [comment]
I guess no one would even notice it. At least if the display order follows the settings and only the "internal" download is changed, it would be hard to notice. Anyway, I think it's no argument to not implement something so subtle when some users could think it us a bug. We can always add it to the FAQ and this overloading prevention e.g. is already such a feature.
So if it us useful, do it. I just right now don't know, how you would change the order there. Why even do it differently?

**Comment by matkoniecz** [comment]
@rugk Main problem is that less important quest may block more important ones.

**Comment by westnordost** [comment]
@rugk It is not about the order of the download but the order of the display. I.e. which quest type obfuscates which
