### ISSUE TITLE
opening hours: add answer that the place does not really have opening hours

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#11]
There are some places that are basically not open, or open by appointment, or 3 times a year they announce they will be open.  I don't even know how to represent this in OSM, but it would be good to resolve them by tagging "no regular open hours; usually closed" or something.   I suppose this needs a whole new tagging scheme for erratic-almost-never erratic-1h-per-week erratic-frequent.   Right now the best I can do is say don't know and hide.

**Comment by westnordost** [comment]
Actually the opening hours scheme in OSM is hopelessly overspecified, meaning that probably all the cases you mentioned and more abstruse ones are somehow covered by the spec. But the more complex the spec, the more complex the implementation and of course the even more complex the actual form to input this data.

So this is why the user of this app will only be able to specify the "normal" opening hours with this app to keep the interface simple.

I do intend to add some more answer options in the near future that should cover more cases, namely the possibility to add a comment (this is part of the spec) to add something like "(and) by appointment" which I often see. Whether it covers the case of "no regular opening times", I am not sure, also not after reading https://wiki.openstreetmap.org/wiki/Key:opening_hours

**Comment by westnordost** [comment]
So, the tagging spec allows this:
1. to instead have a short comment, i.e. `"only by appointment"` or `"no regular opening hours"`
2. to have a fallback rule, i.e. `Mo-Fr 10:00-12:00 || "by appointment"`
3. to have a comment for a rule, i.e. `Tu-Fr 10-12:00; Mo 10:00-12:00 "if owner makes it out of bed"`

The language of the comment should be in the language of the country the quest is in.

So what it does not allow is just to specify that it has no regular opening hours and be done with it. There must always be a comment from the user.

I will likely implement an answer-option for the first point to cover the issue you describe. The rest I think would only needlessly make the form complex.

**Comment by gdt** [comment]
(Not sure why this is closed; there isn't a change yet.)

I would then say that the tagging spec is inadequate.  Certainly the notion that there aren't regular hours is one that could be captured with a machine-parseable token.   Strings with fixed content will have to do fo now. 

So I would suggest that you make something up for common cases, and allow the user to click a few presets, perhaps unioning them if multiple (appointment and chance go together pretty often).    I would suggest "by appointment", "by chance", and "on special occasions".   ("By chance" is common in en_US and I think normal in en_UK; it means that the shop is open at least some of the time, but not according to any posted schedule, so if you walk by and it's open, it's open.....)     My point here is not so much that it's really useful to capture this, but that  it allows someone to close quests in an area which feels like it would be a goal in the game sense, vs saying "I can't answer because while I know the reality the app won't let me express the answer", which feels very frustrating.

**Comment by westnordost** [comment]
> (Not sure why this is closed; there isn't a change yet.)
Did you pull the newest version from master?
You have to click "Other answers..." and then on "No regular opening hours". A dialog will open, asking you to concisely describe the non-regular opening hours, advising to best transcribe directly from the sign (if there is any). So you can specify "by appointment", "by chance", and "on special occasions" or whatever else, just as you like. See this changeset: https://github.com/westnordost/StreetComplete/commit/166533bb09fce06191025122c1eebfe4b54aea51

I also made many more changes on the opening hours quest, by the way. So if you see no changes, pull:
- to specify seasonal opening hours by month has been moved to the "Other answers..." option to not clutter the main view
- added ability to directly specify "24/7", also in "Other answers..."
- revised weekday selection dialog to be a multi-select dialog (instead of range-select) to make selection quicker and added a "Public holidays" option
- added an "open end" option for the time selection; fixed it to make it possible to specify opening hours ranging into the next day; the time selection is now the default for the device, so for newer devices, it is this clock
- revised the layout so that the added opening hours are more visible, also when you add a month/weekday, you are directly prompted to also specify the hours.

**Comment by gdt** [comment]
Sorry, I misparsed "I will" and for some reason aren't getting the commit notifications.  I will update and retry.
