### ISSUE TITLE
maxspeed in Poland - it is trickier than expected

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1101]
https://pl.wikipedia.org/wiki/Wzory_znak%C3%B3w_i_sygna%C5%82%C3%B3w_drogowych_w_Polsce#/media/File:Znak_D-39._Ograniczenia_pr%C4%99dko%C5%9Bci_w_Polsce_od_2011.svg

So initial step is distinguishing urban and rural (what is present already).

But for rural further checks are needed:

- is it a "droga ekspresowa"?
- is it a "autostrada" (motorway)?

If road is not a motorway it is additionally needed to ask whatever carriageways are separated.

**Comment by matkoniecz** [comment]
As bonus, all PL:rural need to be checked (should be doable without resurvey and it is less than 150 ways) - http://overpass-turbo.eu/s/zsZ (I plan on doing this part).

**Comment by westnordost** [comment]
But a motorway is already tagged as a highway=motorway

**Comment by westnordost** [comment]
Also, there are also autostraßen in DE which I guess are the same concept as autostradas and afaik these are tagged as trunk (because they are no real Autobahn but something alike)

**Comment by westnordost** [comment]
For reference:
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Znak_D-39._Ograniczenia_pr%C4%99dko%C5%9Bci_w_Polsce_od_2011.svg/281px-Znak_D-39._Ograniczenia_pr%C4%99dko%C5%9Bci_w_Polsce_od_2011.svg.png"/>

Okay, ignore my previous dabble, here is the plan:
1. What tags to use? The autostrada is a trunk, by the way, see [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk). Does `PL:rural`, `PL:rural_dual`, `PL:trunk`, `PL:trunk_dual` look like a reasonable tagging to you?
2. For Poland, it needs to be added that in case it is rural (asked per dialog) or a trunk (determined by tag set), it is asked whether it is a single or dual carriageway road - just like it is done for the UK. The logic needs to be broken up a bit there because the app currently assumes that the implicit speed limit of trunk roads is always `XX:trunk`
3. After the fix, we need to either create an update for v5 or release v6 soon. However, v6 will be probably be in beta for some time because of the building type quest. I am considering to move the building type quest to v7 instead and in its stead have some time invested in that the implicit maxspeed logic is definite for all countries.

I'd be surprised if Poland would be the only special case here. The only reason why this has been found is because _certain_ contributors to this app are from Poland, the implicit speed limit tagging documentation is somewhat incomplete and I would say written from a German perspective. This needs to be changed.
My vision is to have a parseable table in the wiki that contains all the rules with sources linked and ideally already a translation into OSM maxspeed syntax (that could be used by data consumer). A list has been started [here](https://wiki.openstreetmap.org/wiki/Speed_limits#Country_code.2Fcategory_conversion_table), however, there are no sources linked and I know it is incomplete - i.e. it only covers the "happy path".

I started a page here: https://wiki.openstreetmap.org/wiki/Default_speed_limits

**Comment by matkoniecz** [comment]
> The autostrada is a trunk, by the way, see wiki / motorroad=yes

"autostrada" is motorway, "droga ekspresowa" is currenty usually tagged as trunk (though there is long ongoing debate whatever some "droga ekspresowa" should be tagged as highway=motorway)

> whether it is a single or dual carriageway road - just like it is done for the UK

hmm, it reminds me about my idea for dual_carriageway=yes/no tag,

**Comment by westnordost** [comment]
I posted a question in the German forum regarding details in the German legislation https://forum.openstreetmap.org/viewtopic.php?pid=702887#p702887

**Comment by westnordost** [comment]
> "autostrada" is motorway, "droga ekspresowa" is currenty usually tagged as trunk (though there is long ongoing debate whatever some "droga ekspresowa" should be tagged as highway=motorway)

Well, I guess the killer-argument to *not* tag it as motorway is because different maxspeed rules apply to "droga ekspresowa" (plus in all neighbouring countries, it's also done this way).

**Comment by westnordost** [comment]
Okay, so I am a bit appalled from the attitude in the forum, so I lost motivation to continue the research on https://wiki.openstreetmap.org/wiki/Default_speed_limits

But in any case, I found out here that Germany has exactly the same problem in that regard as Poland and I gained the impression that the people are mostly indifferent but slightly leaning towards simply using the lanes+oneway tags and not inventing anything new. (Something I also slightly advocate for.)

If this is the thing we are going to go now, aka business as usual, no action is required here and this can be closed.

**Comment by matkoniecz** [comment]
> from the attitude in the forum

Which one? OSM wiki/tagging list/some other? (sorry if you prefer to do not answer)

**Comment by westnordost** [comment]
The osm forum (q&a section right now). Nothing bad, just a bit fed up by certain people. It seems the highest appraise you can get there is no comment/indifference, makes coming to an agreement very difficult and is somewhat demotivating.

**Comment by westnordost** [comment]
**Second part of the rant:**

Even more so when wiki-people come along and (perhaps understandably) [call out for that there hasn't been an agreement](https://wiki.openstreetmap.org/wiki/User_talk:Nop#Coach_revert_on_access_page) - well, how, if the forum (and mailing list) culture is to either be against or to be silent? The discussions regarding the advisory cycle lane were already unbelievably tiring, wore on for a year or so in various topics ([this](https://forum.openstreetmap.org/viewtopic.php?id=61427) was only the last of several) and in the end when I finally documented the "agreement", I wouldn't know if it was actually a broad consensus, perhaps I just wore everyone else out instead and they lost interest. So in case someone complains about [`lane:advisory`](https://wiki.openstreetmap.org/wiki/Key:cycleway:lane), the shit is still on me.

And I get the feeling, this is for any kind addition, change or innovation.

It seems the way to get along easiest in the OSM community as a mapper, the way with the least resistance, is to avoid the official communication channels altogether. Instead, just tag what you feel like sneakily, or agree to tag it like that in your local mapping group (see e.g. "Lübecker Methode", "Karlsruhe Schema", etc etc...), in the hope that at some point, "your" tag has reached significancy on taginfo, so that it can be documented as "status quo" / "in use".

Only, that it doesn't work for projects like this, or rather, it shouldn't. I understand that part of the resistance against StreetComplete comes from the fear that the author(s) of this app might avail themselves of those same practices.  It is not a secret that the described behavior is common practice somewhat.
I am well aware of the responsibility of a software / preset developer here, as you know and I always try to seek consensus in the official communication channels and without it, leave it be. 
But when I do try to reach a consensus, I always feel like a fucking solicitor. Rather than seeing the opportunity to collaborate together to define how thousands of OSM surveyors will tag things, thus helping to harmonize and standardize the tagging and making it actually useful for data consumers, I am met with an attitude like "well, **I** do it differently" or "do what you must, but don't touch my turf" all too often. 

Anyway, it's all not that bad and I might have exaggerated a little, but I talked myself in a rage here, that's what a good rant is about anyway, to let off some steam.

**Comment by matkoniecz** [comment]
Recently I started switching whenever possible from "maybe we should document X as Y" to "I documented X as Y, is there any problem with that? Please edit wiki if there is something really wrong."

This way "nitpicks unimportant detail at mailing list" group may be skipped and useful comments can be taken in account and I do not feel burdened by need to assess whatever there is a consensus or not.

It solves most of cases, though not all.

-----

I had similar experience and for example with man_made=carpet_hanger I seriously considering mapping enough of them and creating page based on tag usage to skip creating and voting on a proposal.

For example with street_vendor=yes I got some useful comments on tagging mailing list.

-----

BTW, very similar rant may be written about mechanical edit policy ignored by most people running mechanical edits that puts quite ridiculous burdens on people following it.

**Comment by westnordost** [comment]
Thanks for your view on things. I didn't know that there are people who ignore the mechanical editing policy - and don't know what is ridiculous about it, but I have also not read it and that's another topic anyway.

Back to the topic, I think this can be closed, right?

**Comment by matkoniecz** [comment]
Yeah, at this point changes are required outside repo.

BTW, can you respond to https://wiki.openstreetmap.org/wiki/Talk:Default_speed_limits#Potential_duplication ? It seems that a similar table was started already.

**Comment by matkoniecz** [comment]
I looked at speed limits in Poland and made some fixes.

I will look at it again, some things are quite murky.
