### ISSUE TITLE
Show arrows for the oneway quest?

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#1110]
Well done with the update to 6.0!

Just a suggestion. When answering the oneway quest I think it would be nice to show some arrows of the direction of the street, just so you know that you are answering the quest correct.

What do you think?

**Comment by westnordost** [comment]
Can you elaborate on the "why" and "where? / how?":

Is it just to reassure (more experienced) OSM users that StreetComplete does the correct thing or would there be also another reason for that? Where should it be shown (spoiler: on the map itself, it's difficult) and how would it then be communicated that this mysterious arrow is supposed to be the direction of the oneway?

**Comment by matkoniecz** [comment]
> Is it just to reassure (more experienced) OSM users that StreetComplete does the correct thing

For me - yes.

I so far solved this quest once and I checked later whatever oneway direction was correctly set.

**Comment by westnordost** [comment]
So there should just a an arrow / pictogram with an arrow displayed without further info?

**Comment by rindlerblabla** [comment]
Would be enough for me.

**Comment by rugk** [comment]
Or the best would be on the map, of course. But yeah, it's hard, I know. :smile:

**Comment by westnordost** [comment]
![device-2018-06-23-030133](https://user-images.githubusercontent.com/4661658/41804147-cfab13b6-7691-11e8-9713-7e56cb4ca591.png)

**Comment by westnordost** [comment]
Also, turns out there was a critical bug that led to the logic that decided in which direction the oneway goes to **always** assume that it would be the direction of the way itself. See https://github.com/ENT8R/oneway-data-api/pull/15

So, I will create a new update with a fix tomorrow. This fix will include that all oneway-quest data is purged on update (because the logic that determines whether it is forward or backward is executed on download and then stored in the local DB), even answered quests that haven't been uploaded yet.

The feature + fix is basically done, but I did not commit it yet because I want to review the changes at some other time than 3 o'clock in the morning. Good night.
