### ISSUE TITLE
Meta-Quest: Verify information 

### ISSUE THREAD

**Issue by derfasthirnlosenick** [westnordost/StreetComplete#112]
I think it might be cool if there was a verification/confirmation quest for 
A. Very recent entries, esp. ones made with street complete
B. Very old entries on parameters that tend to change over time (hours, names, construction sites)
C. Changes made by old StreetComplete versions that are known to produce faulty data (e.g. by users not knowing how to properly enter opening hours)

Rationale:
A. Gamification might incentivize undesirable behavior (e.g. tagging a major street as paved without actually checking) or quick-and-dirty entries (e.g. of opening hours) by novice OSM users.
B. + C. Obvious

StreetComplete is a great tool for data quantity and with verification quest could become the same for data quality.

Any verification that is positive could be a note on the element or on the changes etc that introduced the element/last changed an attribute. Amy verification that is negative could trigger either a change, or if the app is to be more conservative, a fixme tag. Elements with a fixme could either be added to the "verify" batch and trigger a change on the next verification/check (b.c. two people have the same opinion) or could be left to non-streetcomplete users.

**Comment by westnordost** [comment]
This is a really nice idea (A & B)! For C: StreetComplete versions that are known to produce faulty data will simply be blocked from my site. Also, it is not effective to correct systematically faulty data in a survey. 

Though, I will not add any tags to elements that (only) serve to help SC find quests, like adding a `note=` tag. If this cannot be implemented any other way, then this feature cannot be implemented.

So, moving on how to implement it, what is required is to selectively
* search through the changeset history in a certain bbox (for A)
* be able to make overpass queries that are like _"all ways with tags construction=* whose construction tag was changed at least X days ago"_ or any query that comes near this, leaving the rest of the filtering to the app itself. As long as this is not possible at all, finding this out "by hand" will involve too much data to be downloaded and analysed that makes the feature feasible.

I don't know if anything of the above is somehow already available. Since this feature is not amongst the high priority ones, I will defer further research about that until when I actually get around to (try to) do this - perhaps then the situation also changed anyway.

**Comment by derfasthirnlosenick** [comment]
With regards to C:  I was thinking of systemic errors that are due to user misunderstanding which are later fixd - the version might be blocked, but the changes are already in and would need to be checked/corrected manually (as hopefully most of the entries are correct). Given the high volume of data this app seems to be able to generate, this might be a tedious task.

I'll try to investigate the most sensible way to implement this without breaking/misusing OSM. Will report back.

**Comment by derfasthirnlosenick** [comment]
Did some thinking and wiki digging.

To implement this, we need a few things:
1. A way to document when an object/property was reviewed.
2. A way to handle disparities between existing data and review results.

For 2, the conservative approach (2a) would be to place a fixme tag and leave the final fix to a non-SC mapper. 2b could be to place the tag and and have a third SC mapper make a choice -> tiebreaker or if (s)he provides yet another set of data, revert to 2a. The simplest option (2c) would be to just overwrite.

For 1, there seems to be a large number of existing tags that do exactly that and are commonly used. (https://wiki.openstreetmap.org/wiki/Key:check_date provides a good overview) without a clear consensus. Check_date and survey:date seem good candidates).
If my understanding is right, check_date would be appropriate if a certain parameter is surveyed and regularly subject to change (opening hours come to mind). Survey:date is probably more for full surveys, I.e. every parameter of an object.

Probably the most reasonable candidate to start out with would be the opening hours. If I recall correctly there was some issues with how people enter those however.

Will think a bit more about this.

**Comment by Jibec** [comment]
This may be great to review shops of a street, it's one of the big challenge in cities. Maybe this quest should be on a special mode.

What a review may looks like:
* at nr 12: the shop still exist, tags are ok => you need to see tags
* at nr 16: the shop still exist, but the name changed => you need to edit tags or add a note
* at nr 18: a new shop was created => you need to add a note

**Comment by matkoniecz** [comment]
It is possible to combine retagging to stardard scheme with verification.

For example for [amenity=parking, access=public]* objects SC would ask "Is this parking available to general public?" and on yes it would be retagged to [amenity=parking, access=yes].

For [highway=footway; bicycle=designated, foot=designated]** SC would ask "Is this route for both cyclists and pedestrians?" and on yes it would retag way to [highway=path; bicycle=designated, foot=designated].

This way given object would not be verified too often.

*this tagging scheme got popular due to JOSM and iD preset bugs https://josm.openstreetmap.de/ticket/10007 https://github.com/openstreetmap/iD/issues/2280
**popular due to https://github.com/openstreetmap/iD/issues/2327, using footway instead the correct path breaks rendering in Default osm style. Appears quite often in edits by newbies.

**Comment by derfasthirnlosenick** [comment]
Sure, any valid reason to retag something provides an opportunity to indicate verification on osm - esp. if the original intent isn't 100% clear (in this case a bit just retagging might be the better solution), manual verification by SC could help.

**Comment by CloCkWeRX** [comment]
This overlaps a lot with the idea of osmose - there's a lot of well defined bugs, some are easily fixable (street type in street name, for example); and baked in "bug detected", "bug last status" concepts behind the scenes; as well as concepts for important.

Vespucci is a good example of it in action; perhaps the simplest way to implement it would be to hit their API (https://wiki.openstreetmap.org/wiki/Osmose/api/0.2) for specific bug types (https://wiki.openstreetmap.org/wiki/Osmose/issues)

Given there's an existing active community there; it could save a lot of work by simply asking for a feature request/new error detection if there are things StreetComplete users would be particularly adept at fixing.

**Comment by westnordost** [comment]
SC is not for error detection and solving. The overlap of SC and QA tools is very little.

**Comment by Jibec** [comment]
Le 18 juin 2017 10:07:40 UTC+02:00, Tobias Zwick <notifications@github.com> a écrit :
>SC is not for error detection and solving. The overlap of SC and QA
>tools is very little.

I understand it is for survey. The overlap is where the error can't be fixed without going there, no?
-- 
Jean-Baptiste Holcroft

**Comment by Jibec** [comment]
Le 18 juin 2017 05:30:34 UTC+02:00, CloCkWeRX <notifications@github.com> a écrit :
>This overlaps a lot with the idea of osmose - there's a lot of well
>defined bugs, some are easily fixable (street type in street name, for
>example); and baked in "bug detected", "bug last status" concepts
>behind the scenes; as well as concepts for important.
>
>Vespucci is a good example of it in action; perhaps the simplest way to
>implement it would be to hit their API
>(https://wiki.openstreetmap.org/wiki/Osmose/api/0.2) for specific bug
>types (https://wiki.openstreetmap.org/wiki/Osmose/issues)
>
>Given there's an existing active community there; it could save a lot
>of work by simply asking for a feature request/new error detection if
>there are things StreetComplete users would be particularly adept at
>fixing.

I really love the idea to link this with osmose which I used a lot in the past. Will have to say which error to take. Because some are not relevant for mobile correction.

In addition of errors detection, we have suggestions of opendata integration in France (yes, in osmose). The only thing is we need to be able to move+edit objects to make it really efficient, opendata doesn't mean perfect data.
-- 
Jean-Baptiste Holcroft

**Comment by westnordost** [comment]
@Jibec Well this deviates from the topic a bit. Generally: Yes, SC may (want to) use aggregate analytics data from QA tools to create quests, this is entirely possible to implement. Please simply create a new ticket here for each quest type that should be taken from Osmose. Note though that many of the Osmose issues you might have in mind are actually just as easily queryable through Overpass (i.e. streets with no names)
See #370 for a reasonable quest suggestion that involves also data from another source (improveOSM).

P.S: Sorry for the late reply, didn't see your message.

**Comment by westnordost** [comment]
I am closing this in favour of #314, which is a shorter/more accurate description of the actual thing that would make sense to implement.
