### ISSUE TITLE
Building quest and sport halls

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1124]
The building quest is really nice, but what should i select for a tennis sport building?

A normal school sports hall could be tagged as school, but the others?

The only sport tag "Stadium" (stadion in german) seems wrong...

**Comment by westnordost** [comment]
> A normal school sports hall could be tagged as school

Not sure about that.

But anyway, is there a tag for that?

**Comment by HolgerJeromin** [comment]
https://taginfo.openstreetmap.org/tags/building=sports_hall
is not the top most building=*sport* tag but the only one with a wiki page

**Comment by matkoniecz** [comment]
I created note and later [used](https://www.openstreetmap.org/way/233354992#map=19/50.07547/19.94151) building=sports_centre, but building=sports_hall seems equally fine for me (with balance tipped by wiki page for building=sports_hall).

**Comment by westnordost** [comment]
Hmm, actually I would prefer `sports_centre`, because it is much more generic. A building used for sports is not always a hall like it is often used in schools. Without a wiki definition, I can of course only assume, but it reads like that tag would also include:
- building built for fitness centres
- dojos, dance school buildings
- bowling centres
- big sports centres (offering a wide range of different sports)
- sport club buildings (de:Vereinsheim)

Perhaps someone could do some research on how sports_centre is used and document it?

**Comment by HolgerJeromin** [comment]
I used sports_centre in the past, too. So i was surprised about the sports_hall tag.

**Comment by westnordost** [comment]
Does the building type "sports centre" need a description? If yes, what should it be?

**Comment by matkoniecz** [comment]
I would expect it to be self-explanatory and I have no good idea for a short description.

**Comment by HolgerJeromin** [comment]
1. "All buildings forming a sport centre including showers, changing rooms and halls for pitches."
2. "All buildings defining a sport centre including showers, changing rooms and halls for pitches."
3. "All buildings supporting a sport centre including showers, changing rooms and halls for pitches."

**Comment by westnordost** [comment]
All three are too long

**Comment by HolgerJeromin** [comment]
Sports_centre should be tagged even for swimming buildings. I am not sure if the volleyball works in that case
