### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1142]
Just read https://t3n.de/news/kotlin-programmiersprache-1094268/ (German) and saw Kotlin is a new Java-like langauge, which is even compatible with Java, so you can integrate it into existing projects and replace stuff step by step.

https://kotlinlang.org/

Just thought of this project then, just as an idea. If you think it's not useful, just forget it. 😄

**Comment by rugk** [comment]
Issue trackers are for any issues, that may be considered. This here is clearly Android-related (and mayn you linked are also clearly GitHub-related), but as I know what you mean: No, they don't have to be related stricly to source code. They just have to be related to the application, of course. Ideas/whatever for it.
Of course, you can split that and some people make dedicated repos for that stuff... (particularly #928 would have made it possible) Or for general things forums, but we have no such thing here.

What wastes time is discussing this stuff. It's very easy to say "No, does not interest me." and close an issue.

**Comment by ENT8R** [comment]
I also read this article today because it was on the start page of Firefox :blush:
Kotlin might have some features which are useful, but IMO this is only a nice-to-have feature... And somebody would need to convert all Java files to Kotlin files which is at least in case of this project a massive work and I can imagine that nobody wants to do it. At least I can always think of issues which are far more important than converting this project to another language. Kotlin basically just makes sense if you use it from the beginning :grinning:
I actually converted a private Android project from Java to Kotlin because I thought I could learn Kotlin and all of its features by just trying it out. In the beginning everything was okay but after a while, as I wanted to implement some more advanced features, I rewrote all files back to normal Java code because the syntax was pretty unfamiliar to me :relaxed: Maybe I'm the only person with this opinion but I like Java more than Kotlin :smile:
Another thing which should be considered is the amount of contributors who feel comfortable with writing code using Kotlin and if there are persons who really feel like a Kotlin expert. I can imagine that just because Kotlin is such a young language, there are not a lot of contributors "speaking" Kotlin.

**Comment by rugk** [comment]
As far as I see the syntax is quite similar, but well... no need to argue about that. 😄 
As far as I read it is possible to just use one Kotlin file together with Java. So no one needs to convert the whole project. (maybe just some core stuff, if needed or so) At least not everything of it. 😄 

> Another thing which should be considered is the amount of contributors who feel comfortable with writing code using Kotlin and if there are persons who really feel like a Kotlin expert. 

Anyway actually a good point, so maybe someone would like to contribute something in Kotlin. And seeing it is (after Rust) the most "liked" language, I guess it has not a bad future.
But yes, currently there are likely not a lot. Though anyone could still contribute in Java to a Kotlin project as far as I seem.

**Comment by rugk** [comment]
BTW, let's get to a compromise. I'll close this and if there is any interest, it will be re-opened. 😃
