### ISSUE TITLE
building:flats where building=apartments

### ISSUE THREAD

**Issue by andrewharvey** [westnordost/StreetComplete#1152]
### General
Affected tag(s) to be modified/added: [building:flats](https://wiki.openstreetmap.org/wiki/Key:building:flats)
Question asked: How many units are there in this apartment building?

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
Yes has 1.6M usages already and is uselful in understanding the density of the apartment.

- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
Most apartment buildings have letterboxes for each unit at the entrance, a count of these will give the answer.

- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
Yes.

### Ideas for implementation
**Element selection:** `building=apartments AND building:flats IS NULL` (please excuse my SQL and not OverpassQL)

**Metadata needed:** I don't think so

**Proposed GUI:** A simple numeric input.

**Comment by andrewharvey** [comment]
> The tag is not approved and 97.49% of the currently tagged values seem to be (imported from) that Czech RUIAN register, moreover, most with the meaningless value of "1".

Okay, I'll get out and start mapping this more to increase other usage and try to get it approved status.

> I am also not convinced about the how much sense it makes to record this information. Do not forget that implementing a quest in SC to collect this information will sooner or later lead to that every apartment building will have this information.

I think that's the point of any SC quest that sooner or later every element that can be mapped, is mapped.

It's useful as a metric of how dense is this building, you can estimate how many people live in that apartment with is useful for all sorts of analysis planning activities.

> Moreover, and this is more important in context of StreetComplete, how many flats there are is sometimes not possible to determine by counting the number of bell button panels/letterboxes at the door, so it is not always answerable. But it must be in order to be appropriate for a quest. So, this is why I am closing this.

Yeah that is true, although sometimes you'll be able to see this without entering the property, other times you would need to enter the property. There are many other SC quests that are unanswerable or if you answer the question it would lead to less accurate OSM data compared to not answering, At least with this I think the likely hood of entering a wrong value is low.

**Comment by westnordost** [comment]
> There are many other SC quests that are unanswerable
Which, for example?

**Comment by andrewharvey** [comment]
> Which, for example?

sometimes

- buildings just don't have an address at all
- buildings have different addresses for different entrances to the building
- how many bikes can be parked here? depends squashed you make them, it's hard to tell from some bike parking exactly how many bikes it was designed for.
- what is the name of this pedestrian street? sometimes it's not a pedestrian street at all but has been tagged incorrectly as one.

I know some of these are addressed though "other answers", but I can't think of any scenario where a building=apartment doesn't have a value for building:flats. By definition an apartment is made up of multiple units. Maybe it can't easily be determined from the entrance but that's another matter.

Either way I can appreciate why you'd prefer only approved tags, so I'm going to try to get it approved, to sort out any lingering issues with the tag first.

**Comment by westnordost** [comment]
Not that the goal of StreetComplete is not to have any unanswerable quests, that is why I am asking.

> buildings just don't have an address at all

Since recently (version v6), it is possible to answer that the building has no housenumber.

> buildings have different addresses for different entrances to the building

It is possible to answer _"It has multiple house numbers"_ which makes the app inform the user that he is allowed to simply enter comma-separated house numbers or ranges, for instance 1,3 or 2-6.

> how many bikes can be parked here? depends squashed you make them, it's hard to tell from some bike parking exactly how many bikes it was designed for.

It is still answerable, though. Of course, depending on the information, there is more or less amount of subjectiveness around, this is natural (and the fuzzyness of the OSM tag definition is to "blame").

Specifically regarding the bike parkings, if it is a [stand](https://en.wikipedia.org/wiki/Bicycle_parking_rack#/media/File:Cycle_Rack,_Ferensway,_Hull_-_geograph.org.uk_-_947416.jpg), they are obviously intended for one bicycle on each side, while those wheelbender type racks are intended to have one bicycle (minus front wheel) stolen per slot. ;-)

> what is the name of this pedestrian street? sometimes it's not a pedestrian street at all but has been tagged incorrectly as one.

Any data currently in OSM may be incorrect and the correct way to answer it is to raise an issue (create a note) and describe the situation.

> Either way I can appreciate why you'd prefer only approved tags, so I'm going to try to get it approved, to sort out any lingering issues with the tag first.

Well, the main problem is that it is not always answerable.

> I can't think of any scenario where a building=apartment doesn't have a value for building:flats

I never said it cannot have a value for building:flats, I said that it is not always answerable by a surveyor walking down the street. In Australia (and in Germany, certainly) most/all? apartment buildings will have rows of doorbells with labels at the entrance, but it is not the case in all countries. I know it will be a problem at least in East Asia, probably even everywhere except in the Western world.

Anyway, in case I did not mention this yet, I also doubt the usefulness of this information vs. the effort to capture and maintain this data because they can be approximated already by building:levels + area of building outline. OSM/StreetComplete surveyors are a finite resource.

**Comment by matkoniecz** [comment]
> In Australia (and in Germany, certainly) most/all? apartment buildings will have rows of doorbells with labels at the entrance, but it is not the case in all countries.

And in Poland there is more and more popular version with electronic system that requires to enter only one flat code at once with no information about available code range (to block people triggering all doorbells at once[1] with hope that at least one person will let them in, without restricting invited people that know apartment number)

[1] people carrying spam leaflets, thieves, Jehovah's Witnesses etc

**Comment by rugk** [comment]
@matkoniecz Wow, really? That is an awkward (spam) system… (Also, if I understood you correctly, this means no single bells are there anymore, so you hardly can enter without ringing everywhere?? :open_mouth:)

**Comment by andrewharvey** [comment]
> I never said it cannot have a value for building:flats, I said that it is not always answerable by a surveyor walking down the street. In Australia (and in Germany, certainly) most/all? apartment buildings will have rows of doorbells with labels at the entrance, but it is not the case in all countries. I know it will be a problem at least in East Asia, probably even everywhere except in the Western world.

Easy, make the quest opt in for geographies where the OSM community want it, where it would usually be able to be answered (of course there's always going to be cases where it can't and that's okay).

**Comment by andrewharvey** [comment]
> Anyway, in case I did not mention this yet, I also doubt the usefulness of this information vs. the effort to capture and maintain this data because they can be approximated already by building:levels + area of building outline. OSM/StreetComplete surveyors are a finite resource.

I think that's an extremely poor approximation. For many kinds of analysis it's useful to understand how many housing units there are in an area, and if we only tag building=apartment given it could be anywhere from an apartment of 3 units to 3000 building:flats adds a lot of value. You might want to look at density, which you need to know both the footprint + levels + number of units.

> Well, the main problem is that it is not always answerable.

There is always some answer though. It's not like a street which may really have no name. An apartment building will always have a set number of units.

You're right about it not being easily answerable from the ground in every scenario, as @matkoniecz points out some newer apartments you might need to key in the number, or might have a separate postal delivery system and not have mailboxes publicly accessible.

Perhaps we could use building:flats:nosigned or something like that to indicate it was not surveyable. Or just accept it and let people answer can't say.

**Comment by westnordost** [comment]
I'll note down the most important point why this way rejected, nevermind the minor ones that may be solvable or would just lead to the quest being disabled by default:

> 🤷 Useful purpose: Especially for tags that are not that well established yet - they should have some application.

To measure population density, if having to choose whether to use `building:levels` or `building:flats`, the former is better suited because one can estimate the total m² of living space. With `building:flats`, you only know the number of flats, but each flat can vary greatly in size while the space used for each person is usually more homogenous. I don't deny that `building:flats` when looked at additionally to `building:levels` may make the population estimation more precise.

> 💵 Valuable Surveyors: Surveyor time is valuable

We should be wary of the usefulness of any quest that applies to any (apartment) building, as adding a quest here will add a really massive amount of quests everywhere. Why? Because this is then going to be an equally massive timesink for users of the app to collect this information. And the surveyor's times are limited.

**So, in my opinion, the massive spam of new quests appearing outweighs the useful purpose the collection of this data has by far.** After all, there is not even any application yet that does look at this data, it is all assumption how it **could be used** (not how it is used).

**Comment by andrewharvey** [comment]
> And the surveyor's times are limited.

That's why maybe opt-in is better. As an OSM surveyor it's completely up to me what I feel I want to map and where I should spend my time. I'm grateful I can disable quests I'm not interested in like `lit`. If I decide I want to add `building:flats` or if I don't care about possible uses for the data I just want to complete the data in the hope that maybe one day someone will find it useful then I should be able to opt-in.

Of course if you decide to allow `addr:flats` to be added #1862 then this quest is less important since you can derive the number of flats from `addr:flats` (though I'd still support having both quests because someone might want to take the easier mapping task of just counting rather than listing).

**Comment by westnordost** [comment]
Are you referring to #3064?

>> And the surveyor's times are limited.

> That's why maybe opt-in is better

Hm, this feature (disabled by default) has been used so far for quests that did not satisfy all conditions of the quest guidelines, almost exclusively the "visible from outside" rule.
