### ISSUE TITLE
Counter mismatch when not using auto-upload

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1165]
Hi again,

I don't use auto-upload, so I collect many answers and upload them all at once by tapping on the arrow. Yet again I noticed that the sum of the counters before and after the upload didn't match. Here is an example from today:

Before the upload:
![counter_before](https://user-images.githubusercontent.com/32601012/44312655-f659d000-a3fb-11e8-8de0-4e22309f7b57.png)

After the upload:
![counter_after](https://user-images.githubusercontent.com/32601012/44312657-f9ed5700-a3fb-11e8-8cc6-83e3547e92b1.png)

Of course, one would expect the counter to be 1335 instead of 1331. I haven't found a way yet to reproduce this behaviour though; as soon as I have more information I will post it here. (When I discovered this behaviour first some weeks ago I thought that it had something to do with notes not being counted correctly, but today I didn't leave a note somewhere.)

(StreetComplete 6.1 on a bq Aquaris M4.5 with Android 5.1)

The cycling cat

**Comment by westnordost** [comment]
No worries about the discrepancy. Notes left (instead of solving the quest) are not included in the star counter but are so in the to-be-uploaded counter.

It's included in the latter so that the user knows that there is something pending for upload. To explain why it's not in the former is a bit more complex - it has something to do with it being impossible by searching through the user's change history or similar to recover how many notes the user left (with StreetComplete).
It should be recoverable because StreetComplete should (one day) gain the ability to recover the star count for a user on a fresh installation and also it was originally planned or maybe still is to show this star count in some kind of leaderboard, thus requiring this count to be verifiable.

**Comment by westnordost** [comment]
(Also, when someone else already solved the quest before you upload your answer, your answer is dropped and you dont get a star)

**Comment by westnordost** [comment]
Though, showing a leaderboard decreased somewhat in priority because of the problems it might bring, so maybe I should just count notes as well and in the event that a previous star count needs to be recovered, the notes will then just be dropped.

**Comment by cyclingcat** [comment]
Okay, but today I didn't leave a note and nevertheless the counter showed an (at least) unexpected value (and I doubt that another user solved 4 of the same quests I did today in the same quarter of an hour...)

I will watch the counters carefully in the next time, perhaps I will be able to reproduce this behaviour.

The cycling cat

**Comment by westnordost** [comment]
Note that with "someone else answered the quest", I actually meant that someone else modified (or deleted) that element so that the quest is not applicable to it anymore - doesn't have to be made with StreetComplete.

Also, note that perhaps that quest was downloaded several weeks ago already. Then the timeframe in which some other user might have changed something becomes much larger.

**Comment by rugk** [comment]
Also this should really be documented in the FAQ.

**Comment by rugk** [comment]
Can you keep this issue open for an FAQ entry? Or just do it right now?

**Comment by westnordost** [comment]
Sure, you can do it whenever you want

**Comment by rugk** [comment]
done: https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#Why_does_not_the_star_counter_match_the_whole_count_of_previous_stars_and_upload_counter.3F
