### ISSUE TITLE
app asks for permission to upload GPS traces

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#12]
After completing a quest, I tried to upload it.   It sent me to osm OAuth which is fine, but it asked for not only permission to read profile, upload changesets, and change notes, but also to upload traces.   StreetComplete's documentation does not talk about recording GPS traces, and certainly it does not talk about uploading them.   Permissions should only be requested for things that are reasonably connected with the described functionality.

In addition, if one unchecks "upload GPS traces", the authorization is considered to fail, because not all requested permission were granted.   This is really a separate bug - even if there were a documented trace/upload function, it should be possible to do quests without authorizing upload.   I am happy to open a separate issue for that, but for now it doesn't seem useful.

**Comment by westnordost** [comment]
Yeah. I plan to offer the user the option to record the GPS trace and upload it automatically to OSM later since the GPS is on while the app is active anyway.

While the feature is not implemented, I can remove that from the list I think. Then later, I have to deal programmatically with incomplete permissions and rerequest oauth when the user checks that option. But that's okay.

The "read profile and preferences" permission is necessary to find out the users ID, oddly enough. I need the ID to find and hide all notes to which the user already contributed to from the map of quests. Perhaps I can explain that in the error msg when he unchecks that permission. I consider removing quests visually after the user answered them a core functionality of the app, so making that permission optional is out of the question as long as there is no other way to get the id of a user.

Am 24. Dezember 2016 18:06:33 MEZ, schrieb Greg Troxel <notifications@github.com>:
>After completing a quest, I tried to upload it.   It sent me to osm
>OAuth which is fine, but it asked for not only permission to read
>profile, upload changesets, and change notes, but also to upload
>traces.   StreetComplete's documentation does not talk about recording
>GPS traces, and certainly it does not talk about uploading them.  
>Permissions should only be requested for things that are reasonably
>connected with the described functionality.
>
>In addition, if one unchecks "upload GPS traces", the authorization is
>considered to fail, because not all requested permission were granted. 
>This is really a separate bug - even if there were a documented
>trace/upload function, it should be possible to do quests without
>authorizing upload.   I am happy to open a separate issue for that, but
>for now it doesn't seem useful.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/12

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gdt** [comment]
It's good that the OSM OAuth system served it's purpose then!   But seriously, I think uploading GPS traces is a bug, not a feature, in any program which does not present itself to the user as having that as a primary feature.   The privacy stance of the app is that you can download regions, and thsese queries are not expected to be logged/stored/published (fsvo logged, I know).   Answering a quest is the same as making an edit with an editor, so that's expected to be public.   But how one walks around, and where, should not be published.  I realize you said you'd make it opt-in, but still.

Separately from the tinfoil hattery, I am doubtful about the usefulness of pedestrian traces when using this app.   I find traces useful when driving, and when hiking on fairly long trails in the woods.  In the city, GPS tracks tend to be very noisy relative to how streets can be seen on imagery, even if the user doesn't run back and forth to read signs about opening hours :-)   So I would think that traces from StreetComplete users would not be useful to other mappers.

All in all, I suggest sticking to the core mission and maintaining the privacy stance that geolocation information is published solely by answering quests/notes and then only that the object was updated.

**Comment by gdt** [comment]
Interesting about the "read profile".  I noticed that, and wondered, but I didn't find that troubling.  Ideally there would be a manual that explains how the app behaves, and the reason for the permission can be explained there.  (I realize the Android way is to code apps to not need a manual, but I think manuals are still needed to define the expected behavior and explain the subtleties.)

**Comment by westnordost** [comment]
You might be right about the GPS traces of pedestrians being too noisy to be of use. Let's see, adding this feature (yes, opt-in of course) has very low priority.

**Comment by westnordost** [comment]
Removed. If you use version 0.2 and have not authenticated yourself yet, you probably won't be able to. No problems if you build from master though.
