### ISSUE TITLE
Add bollard type to bicycle_parking quest

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#1202]
Hi,

First of all, this might be related to https://github.com/westnordost/StreetComplete/issues/330 and https://github.com/westnordost/StreetComplete/issues/1038 where some arguments against having "bollard" type were mentionned.

**Use case**

There is no simple way to tag a "bollard"-type bicycle parking in StreetComplete at the moment. These are to be considered as stands. See https://wiki.openstreetmap.org/wiki/File:Bike_path_on_College_in_Toronto.jpeg for an example of bollard.

**Proposed Solution**

I suggest "bollard" type could be added to the bicycle parking type quest. My main arguments for it are:

* "bollard" value is relatively spread https://taginfo.openstreetmap.org/keys/bicycle_parking#values (given the fact that this type of stands is more rare than regular stands for instance).
* As a bike user, bollard offer a quite different experience from what could offer other stands. Typically, a bollard is always not very large, meaning there might be conflicts if you park one bike on each side (contrary to wide stands https://wiki.openstreetmap.org/wiki/File:Wide_stands_1.jpeg).
* Some cities are starting to turn bollard on the side of the sidewalk (for instance) into bike parking by fixing extra legs on them. These could be poor quality bike parking as the bollard was already there and not designed with bikes in mind.

Thanks!

P.S.: The same could actually be discussed for wide stands as well, which ensures your bike will lean on an horizontal metal part and which should be larger so that two bikes can be on each side without conflicts.

**Comment by westnordost** [comment]
You linked the right issues. In #1038 I explain why there is nothing beyond wheelbenders and stands. 
Arguments for adding bollard would be that
- it is visually very different and users might be confused what to choose. But IMO I solved this in #1038
- it is in effect something yet different from a stand. I am not convinced that this is the case. I do not understand what you mean with that there may be a conflict when two bikes are attached. Do you mean that oftentimes it is not possible to use a bollard for two bikes? How so? And even if, there is a quest that asks about the bike parking capacity. Then this capacity will simply be lower, no?

**Comment by matkoniecz** [comment]
> meaning the security might be lower than the one offered by a regular stand

Note that it is not distinguishing them from stands. There are also some poorly secured parkings among them.

![31808361-0fcf1572-b573-11e7-95d5-51e711a868e7](https://user-images.githubusercontent.com/899988/45823100-3824b180-bced-11e8-8559-b201f1db2ea8.jpg)

**Comment by westnordost** [comment]
Hm, you said it yourself: Bollards might negatively affect the capacity, but other stands as well, if they are too close to each other. Also, there are stands that are as narrow as bollards (the 50cm picture). So, I do not see a property here that generally distinguishes them from any other kind of stands.

In my opinion, the tagging scheme as it is documented in the wiki is a bit broken, because any kind of shape, even "bicycle trees" made it into the list there. 
* some values are ambiguous (racks vs stands, anchors vs wall_loops for example)
* some values are defined by appearance, some by quality/security
* there is not any categorization, it's almost a free-form value

This is why I reduced what StreetComplete users can tag directly to two things: unsafe and safe - front wheel only and frame.

Further subcategories of these in my opinion belong into subtags, if there was a scheme for that (a wide stand, a curly stand, a wavy stand, a narrow stand and bollards are a type of stand).
But question is if they should be tagged at all. What is the value or use case to define exactly what type of stand there is? I can only think of something halfway far-fetched. The most important thing is to map whether they are reasonably usable (safe) or not (unsafe), and that is done in StreetComplete's bicycle parking type quest. Adding any more details I consider a separate task whose effort to add and maintain this data vs gain is unclear to me.

**Comment by Phyks** [comment]
> So, I do not see a property here that generally distinguishes them from any other kind of stands.

What I was saying was rather that "stands" is a very generic (too generic actually) description. As it is well explained in SC, a "stand" is just something you can lean your frame on.

> Further subcategories of these in my opinion belong into subtags, if there was a scheme for that (a wide stand, a curly stand, a wavy stand, a narrow stand and bollards are a type of stand).

I tend to agree with this. However, I'm not really willing to try pushing a new tagging system for "bicycle_parking" based on security vs appearance at the moment :) I was trying to get the most from the existing tagging scheme with SC :)

My main argument here was that:

* a "stand" is too generic to give a real insight on the quality of the bike parking.
* a "wide stand" might be visually oriented, but it narrows down the quality of the "stand" as well. A "wide stand" will guarantee you you can use the bike parking at full capacity (they are large enough) and you can secure both front and rear wheel + frame.
* A "bollard" (even though this is visually oriented as well) on the contrary can be considered as a "not very good stand" as usually they are quite narrow and you cannot lock both frame, rear wheel and front wheel. There might be negative effects on capacity as well.

Of course, "stand" category will be very heterogeneous as not everything would look like a "wide stand" or a "bollard". At least, for everything that looks like a "wide stand" or a "bollard", it will be tagged as such and convey more infos for the end users.

Additionnally, in my area (Paris region, France), most pre-existing stands are poor quality stands (regular stands, bollards). New bike parking added are "wide stand", so making a clear distinction (still visual, I agree that's not perfect and should be based on quality and safeness rather than look) here would help keep track of which are the newest (and then the best) spots.

**Comment by westnordost** [comment]
Okay, so the definition of "wide stand" is, that both front and back wheel can be secured(?)

However, bollard is a definition by appearance, so it does not seem to fit in there, it is not consistent.
[This bike stand](http://belairsud.blogspirit.com/media/01/00/913280775.JPG) has similar properties as this [bollard](https://wiki.openstreetmap.org/wiki/File:Bike_path_on_College_in_Toronto.jpeg), they are both quite narrow. 

The problem with the missing proper categorization in the values currently documented on the wiki page for bicycle parking types is this:
If `stand` is implicitly a category of _"any kind of stand as long as you can lock your frame to it"_ but **_at the same time_** on the same level as its implicit children like `wide_stand`, it becomes impossible later to tell apart if one bicycle parking is just "a typical medium-sized stand" or "wasn't tagged more precisely because the user didn't care".

We have this problem at a number of different places, such as buildings (`building=residential` means that it can't be defined more precisely or the previous user didn't care to?) or surfaces (`surface=paved` means that it can't be defined more precisely because it is more or less a patchwork or the previous user thought that `paved `is enough "for now"?).
I want to avoid this with bicycle parking types, or at least not contribute to the problem, by clearly separating the category from the detailed (appearance-based) tags.

**Comment by brunnerpaul** [comment]
I'm commenting mainly because of the "feedback required tag".

Relevant note: https://www.openstreetmap.org/note/3519463
Image: https://westnordost.de/p/128498.jpg

I agree with two quotes from @Phyks:
> Typically, my (small) city only uses bollards but most users tagged them as stands through Street Complete.

> A "bollard" [...] can be considered as a "not very good stand" 

*Not* adding "bollard" was IMO a good decision as it's basically a sub-type of stands, so it would only take up more precious screen real estate. Adding "two-tier bike rack" on the other hand was important because that's an entirely different type regarding functionality and how it looks.

My distinction between "bollard" and "stands" is based on how far the two poles are apart (most "bollards" I see have two poles). I've also tagged "stands" in cases where I would now prefer to use "bollard". 

Previously, I was wondering if the distinction between the two is worth a) giving up the ease of StreetComplete on my side for that task or b) for StreetComplete to offer "bollard" additionally, only for other users to realize "wait, these were a different type?" :) 

My favorite answer to that would be a third option: to have more types offered in StreetComplete Expert Edition (I see there are already additional types for some other quests there). 

That way, StreetComplete would achieve this (quote from @westnordost)
> I want to avoid this with bicycle parking types, or at least not contribute to the problem, by clearly separating the category from the detailed (appearance-based) tags.

... while StreetComplete Expert Edition would give users more choices without confusing the general StreetComplete user base.

@Helium314, what's your take on this? Should I open an issue for that in your repo?

**Comment by Helium314** [comment]
My first impression is that `bollard` is not really worth a separate answer, but then I've never actually put my bicycle to one, and it's 5th place for `bicycle_parking` in taginfo.
It definitely could be included in EE.

**Comment by curbia** [comment]
I would like to see `bollard` included, at the very least in EE. It's the dominant form of parking here. `rack` would also be a necessary addition for me.

As it stands, I will have to edit every single bike parking node manually at a computer because of the lack of inclusion of these tags in StreetComplete. I think SC should be aiming to not add incorrect information to the map whenever possible. I think the average user can tell the difference between these types of parking based on photos.

**Comment by mnalis** [comment]
> I would like to see `bollard` included, at the very least in EE. It's the dominant form of parking here. `rack` would also be a necessary addition for me.

Can you post here a few typical pictures of each in EE @curbia  (preferably with bicycle nearby) to be sure what type exactly are you talking about?

Looking at the [wiki](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking) I do not see huge issue with missing `bollard` subtype: it seems to me that `wide_stands`, `bollard` and (some meanings of) `wave` are all just subtypes of `stands` (see both wiki description and a StreetComplete text `"supports bicycle frame"` which is very important part of the answer). 

So using `stands` for `bollard` is IMHO **not incorrect, just less precise**. (e.g. like some people might tag [building=house](https://wiki.openstreetmap.org/wiki/Tag:building%3Dhouse) instead of `building=detached` - it's not incorrect, just less precise; but in any way it is improvement over `building=yes`).

> I think SC should be aiming to not add incorrect information to the map whenever possible. 

Absolutely. If user is not sure, they should say `Other answers` / `Can't say`; and leave a note (preferably with a picture) -- and not selecting an random incorrect answer. Hopefully most of users would behave in that way, but there is no guarantee. 

> I think the average user can tell the difference between these types of parking based on photos.

Sure; but I still don't still what is fundamental difference from stands? There are many types of **stands**, and the one of more popular ones shown in the picture (called _"staple rack"_ in North America) is just one of them. What they all have in common is that they **support whole bicycle frame, and allow locking _both_ frame and wheel to it**. If you can do that with `bicycle_parking=bollard`, then it is a subtype of `bicycle_parking=stand`.  E.g. all parkings in picture below are `bicycle_parking=stand`, even if they are not staple-shaped:

![small_bicycle_stands](https://github.com/streetcomplete/StreetComplete/assets/156656/acdcabdf-3a81-41bc-bb89-4ddf89139922)

Would `bollard` also fit in that picture; or is it fundamentally different (and how?) 

I think main problem with adding subtypes of `stands` is that if you add one such exception, you really should add all of them; otherwise one risks creating more confusion than solving problems. And adding all bicycle parking type is impractical and creates stress for mappers who are then unable to decide which one to use.

> `rack` would also be a necessary addition for me.

Looking at the wiki, the `bicycle_parking=rack` tag seems ill-defined: it seems to be used both for wheelbenders and coathangers, as well as for stands sometimes (see North American usage of "staple rack" to mean `bicycle_parking=stand` instead). I would avoid using that value and use some [other](https://taginfo.openstreetmap.org/keys/bicycle_parking#values) more precisely defined tag.
