### ISSUE TITLE
Move "enable showing notes not formed as a question" to the same place where other quests can be enabled

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1205]
**Use case**
Add a clear and concise description of *your use case* and what you thus think is missing, and why. 

It should be easier to use settings after that change. At least I think that it would be more intuitive, I wanted to toggle this setting and went to quest selection menu.

**Proposed Solution**
There may be several different solutions for your idea or use case, add your deliberations about it here to help out sort out the best one.
Also, add screenshots or blueprints to visualize your idea, if applicable.

Remove toggle from settings menu, add new entry in quest selection list called "Can you contribute anything to this note? (notes that are not questions)".

**Comment by westnordost** [comment]
Though technically, these are two completely different things, perhaps from a user perspective it might be logical (to search for a setting like this there).

However, even from that point of view, I see some UI problems with this suggestion:
1. The "notes not phrased as questions" quest would need to be displayed right below the disabled "notes phrased as questions because priority-wise, it is always downloaded first, however the relative importance of notes not phrased as questions is much lower (which is why they are hidden by default)
2. That new quest would need to be displayed disabled because you cannot change its priority but at the same time, the checkbox would need to be displayed as checkable/uncheckable. This might be slightly confusing to users

All in all, I would not like to do this because it adds some technical hackery and still brings some (minor) UI problems while the improvement over the current solution is not really clear. The settings screen is not exactly crowded.

**Comment by matkoniecz** [comment]
In that case I will close it.

Inability to move it but ability to toggle would be tricky to display.

And implementing ability to change priority is probably not worth it.

> however the relative importance of notes not phrased as questions is much lower

So notes not phrased as question should be blocked by some of other quests? I think it is not happening now.

**Comment by westnordost** [comment]
> So notes not phrased as question should be blocked by some of other quests? I think it is not happening now.

No, other quests will always be blocked, but I perceive that notes not phrased as questions are less _important_ because most of the times, one will not be able to contribute anything to such notes.

**Comment by rugk** [comment]
Thinking about the UI and this thing here, I have an idea for a long-term solution: Basically, you would need to introduce "per quest" settings, as this is the thing, this setting actually is. For other quests, you could then adjust similar details a (n expert) user might want…

The UI could then be adjusted to just add a small gear wheel at the right, which opens the settings page for the specific quest. This is an UI pattern that is quite common in the Android world. :smiley:
