### ISSUE TITLE
Quest suggestion: Adding fuel types to fuel stations

### ISSUE THREAD

**Issue by Spanholz** [westnordost/StreetComplete#121]
There are a lot of fuel stations tagged without the types of gas they offer. Some only offer Diesel for trucks, some others only LPG or CNG.

**Comment by escoand** [comment]
Hard to decide if this quest is needed, could just be visible if no tag at all is set.
http://wiki.openstreetmap.org/wiki/Key:fuel

**Comment by escoand** [comment]
A list of checkboxes could be the right choice for that.

**Comment by matkoniecz** [comment]
@Spanholz Can you specify what kind of tags should appear in quest? http://wiki.openstreetmap.org/wiki/Key:fuel has a massive list.

**Comment by Spanholz** [comment]
Diesel and HGV-Diesel are interesting. Also LPG and CNG, which are often sold standalone. Ad-Blue as an additive is getting more important. And the 2-3 normal gas types with ROZ 91, 95 and 98. In Germany called Benzin, Super and Super Plus. 
Hydrogen could get more interesting in the future. 
Aviation fuels are not that interesting. Also some other gas types with low market share or only sold in some countries.

**Comment by westnordost** [comment]
The list from the wiki needs to be dumbed down before this is in a format eligible for a quest. As a reminder, in SC you have the following possibilities available:
* you can show/hide certain fuel types and/or sort them depending on the country the quest is displayed in
* you can have different names for fuel types in different countries. (So, it is possible to name fuel types according to the country the quest is displayed in, not the user's language of the user's phone.)

**Comment by HolgerJeromin** [comment]
Just for completeness: here is the link to [taginfo fuel list](https://taginfo.openstreetmap.org/search?q=fuel%3A).

**Comment by Carnildo** [comment]
"Normal gas types" vary not just from country to country, but from region to region as well.  For example, in the United States, the 2-3 normal gas types are AKI 87, AKI 89, and AKI 91, except in the Mountain West, where everything is shifted down by a point or two because you don't need as much anti-knock additive at higher elevations.  Additionally, what's available can be either pure gasoline or 10% ethanol blend, subject to change without notice.

**Comment by westnordost** [comment]
I'll close this because:
- quests should be solveable by anyone, but not everyone may know what actual fuel is behind a certain brand name
- there are lots and lots of different fuel types, see taginfo and wiki, and to make sense of it (and recognize which brands/fuels are the same/synonyms) is a huge task
- since there are so many variants/synonyms, it would be a huge effort to find country-specific defaults so that for any one country, only the relevant/actually used ones are shown
- in principle, this tagging scheme has the same problem as the `recycling:*` tagging scheme: Is a certain fuel not available or has it just not been tagged (yet)? This is problematic because as soon as there is **any** `fuel:*` tag, we have to assume that it **only** sells the given fuel(s). So, even asking "Does this fuel station sell LPG?", which would be an important thing to ask (if it wasn't spam) is not possible because then we'd have to tag the fuel station in a way that implicitly suggests that it only sells LPG.
