### ISSUE TITLE
Allow to use dot to Parking entrance max height quest 

### ISSUE THREAD

**Issue by Dostoi** [westnordost/StreetComplete#1212]
I've encountered several parking where the max height isn't a round number but 1.9 meters or something like that. Currently we can't enter it correctly with streetcomplete.

It would be helpful to be allowed to use the dot and not only number when answering this quest.

With streetcomplete 7.1

**Comment by westnordost** [comment]
Why can't you enter a dot?

Am 25. September 2018 12:32:22 MESZ schrieb Dostoi <notifications@github.com>:
>I've encountered several parking where the max height isn't a round
>number but 1.9 meters or something like that. Currently we can't enter
>it correctly with streetcomplete.
>
>It would be helpful to be allowed to use the dot and not only number
>when answering this quest.
>
>With streetcomplete 7.1

**Comment by ENT8R** [comment]
In some countries/languages a comma is used instead of a dot as a decimal seperator... (e.g. Germany) Do you live in a country where this is used?

**Comment by westnordost** [comment]
The input field accepts both `,` and `.`, you should know it, you (also) implemented it. I suspect there is a misunderstanding or something specific to Dostoi's device, like a custom keyboard app that fails to show buttons for these or something.

**Comment by ENT8R** [comment]
Oops yes, I think I mixed something up then... Either it didn't work on my emulator or I only remember an old implantation where I limited the input to have only the dot as a decimal seperator... Sorry for the noise.

**Comment by Dostoi** [comment]
The issue is that there's only number and no separator. But it might be specific to my device. I have a galaxy J1 with android 5.1.1

![screenshot_2018-10-01-09-15-21](https://user-images.githubusercontent.com/7694864/46275173-4cbe4080-c55c-11e8-8ed6-d788066f5a66.png)

**Comment by rugk** [comment]
So which Android version is that? (possibly also which device?)

**Comment by westnordost** [comment]
OKay, @Dostoi , this is definitely a bug in the default keyboard on your Samsung. You can solve this by yourself by installing a different keyboard. I am still researching whether this bug in Samsung can be worked around somehow by the app.

**Comment by rugk** [comment]
Ah sorry, overread that.

**Comment by westnordost** [comment]
I cannot reproduce this on a Samsung Galaxy S4 (2013) and also not on a Samsung Galaxy 8.0 WiFi (2013), both devices are known to have Samsung-related glitches. Without being able to reproduce it on *some* device, I can't look for if there are hacks to workaround this bug with your keyboard.

Try installing the newest Samsung keyboard here: https://play.google.com/store/apps/details?id=com.sec.android.inputmethod
 and set it as the default instead of the keyboard integrated in your system.

Otherwise, if you don't like it, **two popular ones that do neither have ads nor in-app-purchases** (but possibly are data leeches):
* [Google Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin), most will have this one
* [SwiftKey keyboard](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) 

**If you value privacy, try out:**
* [AnySoftKeyboard](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard), open source, also available on F-Droid
* [Multiling O Keyboard](https://play.google.com/store/apps/details?id=kl.ime.oh)

**Comment by Dostoi** [comment]
Yeah I taught that it might be specific of my device as no one reported it before. I'll just switch to another keyboard.
Thanks for your effort :)

**Comment by matkoniecz** [comment]
> Without being able to reproduce it on some device, I can't look for if there are hacks to workaround this bug with your keyboard.

I have access to a device with this specific glitch. But telling user in "can't say" menu to install a proper keyboard seems to be the best solution.

WONTFIXing with hint in "can't say" is based on https://github.com/bitpay/copay/issues/2384 https://stackoverflow.com/questions/14025340/how-can-i-ensure-a-numeric-decimal-keyboard-in-android https://stackoverflow.com/questions/19433745/missing-period-for-samsung-galaxy-s4-numeric-keypad
