### ISSUE TITLE
Rural or Urban? Tag is written incorrectly for the two regions in Belgium

### ISSUE THREAD

**Issue by hgcvm** [westnordost/StreetComplete#1216]
Concerning the maxspeed quest and the follow-up question "Urban or rural".

When answering whether a way is in an urban or rural area, the tags in Belgium are written incorrectly. 

The current tag StreetComplete writes is "maxspeed:type=BE:rural" and is not correct. There is no uniform maximum speed in rural areas of Belgium. Wallonia has 90 and Flanders has 70 as a maximum. We don't use BE:rural. Please see: https://wiki.openstreetmap.org/wiki/Key:source:maxspeed#Belgium

The correct way would be to use BE-VLG and BE-WAL in the corresponding areas.

**Comment by westnordost** [comment]
StreetComplete is currently not able to determine if a street is in Wallonia or Flanders, that is why it is tagging it as BE only. I consider this information better than nothing, because it still carries the information that there is no signed limit and finding out where a street is located is trivial to do later.

I'd have a lot to say about this topic, and I have been sinking a lot of time into this, and still am, so really short just FYI: The whole `maxspeed:type` scheme is actually insufficient for default speed limit tagging. Read/discuss i.e. [this recent tagging mailing list discussion](https://lists.openstreetmap.org/pipermail/tagging/2018-September/039195.html) (linking to the message later in the thread where I explain why the scheme is insufficient).

**Comment by hgcvm** [comment]
I disagree with the fact that "this information is better than nothing". I think not writing the speed limit is better than adding the wrong one.

**Comment by westnordost** [comment]
It is not wrong to state that "this is a rural road in Belgium".

**Comment by hgcvm** [comment]
OK, so you can't/won't fix the issue. I'll close this here.
