### ISSUE TITLE
[8.1] House number chellenge doesn't generate street / city name

### ISSUE THREAD

**Issue by woj-tek** [westnordost/StreetComplete#1231]
**How to Reproduce**
When presented with "building number" challenge only the number is submitted without city/street name

**Versions affected**
8.1

**Comment by matkoniecz** [comment]
Hello! This is a known problem, reported in #213 

It will be fixed once someone implements this missing quest. I have a prototype and plan to continue working on it, but I am unable to predict when I will have time for that.

**Comment by woj-tek** [comment]
I search for something (got a notification from Polish OSM editors) but did not find that issue. I'll take a closer look.

I assume it's still ok to solve houser number issue and then add street name manually via webpage?

**Comment by westnordost** [comment]
Yes, of course it is ok. It is correct that only the housenumber, without the street, is not immediately useful for data consumers because the address is incomplete. However, it is still useful, because the street name can always be added later and unlike the housenumber, usually does not require a survey.

The reasons why the quest only asks for the housenumber, and not the name are:
1. It can more efficiently be added later, also by someone else, via iD or JOSM. *
    1. On a mobile while on and about, it is always more awkward and slow to type than on a computer
    2. With a proper editor, one can select all the houses of one road and just set it for all at the same time
2. The street name is usually not on the housenumber plate as well, so the information is often not directly available to the surveyor, especially on long roads and in ambiguous cases where the house might belong to one road, or to another. It is easier and less prone to mistake to determine the street name if one had the overview over the enumeration and affiliation of the other houses as well as the big picture on the map. This is the case when using iD / JOSM.

* See also [quest guidelines](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete): <blockquote>💵 Valuable Surveyors: Surveyor time is valuable, they shouldn't be asked to complete data that does not require a survey and can more efficiently be done remotely.</blockquote>
