### ISSUE TITLE
Add shortcuts to last used values for the floor quest

### ISSUE THREAD

**Issue by lightonflux** [westnordost/StreetComplete#1237]
**Use case**
When adding the number of floors or levels to a house you can get exhausted and bored, because in most areas there are zoning laws so most if not all houses have the same height and number of floors. 
 This means you have to redo the same process over and over.

At the moment you have to

1)  tap the house
1) tap the first field so the keyboard shows up
1) enter the first number
1) tap the second field 
1) enter the second number 
1) confirm

Now repeat this 30 times. :(

**Proposed Solution**

1)  tap house
1) select shortcut
1) confirm

Illustration where the shortcuts could be:

![fr](https://user-images.githubusercontent.com/1377943/47270381-5dfed980-d56b-11e8-89b5-d3e2766379b9.png)

**Comment by westnordost** [comment]
Implemented this now, but only the last selection will be shown. Main reason for that is that there is not so much space in the layout: If I did it how you suggested, the answer form would always need to be scrolled.

**Comment by lightonflux** [comment]
Thank you. Looking forward to test it.

**Comment by pkoby** [comment]
I LOVE this update. However, I do find it limiting that there's only the last-used values, because around here, there are often two (or more) level types in an area, and they alternate randomly (some houses are 2+1roof, others are 1+1). (See [here](https://www.google.com/maps/@38.4092163,-82.433875,3a,75y,268.05h,81.13t/data=!3m6!1e1!3m4!1sKFhobkx39NLknKqjldPzgw!2e0!7i13312!8i6656) for an example.)

I understand that the UI doesn't have much space, but maybe you could consider another value to the left of the current one? I'm not sure if this is limited by some languages, but in English (and I see German), that space shouldn't be used by text.

I don't think scrolling would be good, though, so I'd say it should be horizontally aligned.

**Comment by westnordost** [comment]
@pkoby I checked, actually in quite a few languages the label text would be obscured by a second button
