### ISSUE TITLE
Housenumber quest still visible in Italy

### ISSUE THREAD

**Issue by NonnEmilia** [westnordost/StreetComplete#1243]
The house numbers quest is still visible in Italy. When I go to the quests list I see "never show in Italy", but the quest is still visible on the map.

<img src="https://user-images.githubusercontent.com/2818194/47613059-05a66b00-da88-11e8-889e-e0c20f22c1b1.png" alt="settings" width="300"/>
<img src="https://user-images.githubusercontent.com/2818194/47613077-48684300-da88-11e8-86d9-3577825429c2.png" alt="map" width="300"/>

**How to Reproduce**
Go to Italy (i.e.: the one in the screenshot at https://www.openstreetmap.org/#map=19/44.70461/10.65568) and find a building without housenumber.

**Versions affected**
Android v8.1.0 StreetComplete v8.3

**Comment by NonnEmilia** [comment]
I've did this:

1. Opened StreetComplete
2. Went to settings and used "Invalidate quest cache"
3. Returned to the map
4. Downloaded the quests

The house number quest is still there... :thinking:

I tried also to delete the app cache and then restarting from 1., but it did not help.

I have StreetComplete from the very early beta releases, maybe I have to uninstall and re-install it?
If your fresh download works maybe it's a specific issue of my install...

**Comment by westnordost** [comment]
> I tried also to delete the app cache

The downloaded quests are not in the app cache, but in the app data. (Technically it is not a cache but a full-blown database.) You'd have to clear the whole app data to also clear the quests.

What you have to do is to invalidate the quest cache and have the app download the housenumber quest again. I know, there is no visual feedback what quest type the app is currently downloading, so you can't see if the housenumber quest has been downloaded now or not. To make sure that the app does, just move the housenumber quest in the quest selection list to the top once, then hit "download here". And voila, the quest should be gone after the download.

> though, it would be still a bug - country filtering should apply also to downloaded ones

Country filtering does not apply to already downloaded ones. And I would not like to implement it because cases like this where it was wrong to download them in the first place should be very rare and a (second) check right when the quest is fetched from the local database would slow down things. I.e. in this case, it was most probably caused by the bug in v8.0.

For the next version it is planned to include #766 to mitigate the issue of stale quests.

**Comment by matkoniecz** [comment]
Maybe it would be a good idea to clear quest cache on update in rate case of app downloading wrong quests? Probably most editors in Italy will encounter this problem and not report it.

**Comment by NonnEmilia** [comment]
> To make sure that the app does, just move the housenumber quest in the quest selection list to the top once, then hit "download here". And voilà, the quest should be gone after the download.

I did this and nothing happened again, so I delete the app data.

Not only the house number quest is gone, but also some other quests not updated (edit made with other editors) have been updated!

Maybe I had very old corrupted quests that didn't update correctly with the normal workflow...

Thank you all for the support. 🎉
