### ISSUE TITLE
Reduce / disable animations

### ISSUE THREAD

**Issue by StyXman** [westnordost/StreetComplete#1260]
I find the animations cute and game-like, but after a while to me they become tiresome and battery-draining. Could you add an option to disable or reduce them?

**Comment by rugk** [comment]
FYI if you disable animation system-wide (e.g. usually done via the "battery saver" mode), they are also disabled in SC.

**Comment by westnordost** [comment]
So, is this concluded by @rugk's comment?

**Comment by westnordost** [comment]
By the way, the animations are not draining the battery more than the default animations would. The duration of animations are the determining factor (because parts of the screen are redrawn every frame while the animation is active). As @rugk said, you can disable animations system-wide to save battery.
