### ISSUE TITLE
access=yes on playgrounds

### ISSUE THREAD

**Issue by flohoff** [westnordost/StreetComplete#1262]
Hi,
the wiki states that only playgrounds unavailable to the public should be tagged with access tags. A playground by definition is public.

I understand that in this case you cant make a quest from this as its unclear whether a certain object has been tagged or not, but bending the current interpretation of wiki and usage to make it suitable for a quest may not be done without consensus shouldnt it?

Flo

**Comment by westnordost** [comment]
Did you read #1114?

**Comment by matkoniecz** [comment]
I believe that https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aleisure%3Dplayground&type=revision&diff=1696619&oldid=1560655 fixes this problem (I explicitly described explicit access=yes tagging).

If someone disgrees and thinks that discussion on https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dplayground or tagging mailing list I will participate in it.

**Comment by matkoniecz** [comment]
Additional note: if someone wants it is possible to disable quests in their copy of SC (in settings).

**Comment by westnordost** [comment]
Well, I'll close this now. 

It is a matter of fact that the general assumption is public if no `access` tag is present, probably for everything that is mapped in OSM. I do not think it is necessary to mention this on (every) wiki page. 

What is noteworthy is to document that something should not be mapped at all if it is private. If there is a consensus not to do that, that is. I am thinking of [gardens](https://www.openstreetmap.org/way/35803879) or [swimming pools](https://www.openstreetmap.org/#map=18/43.70886/7.30763)
Regardless of that, it may still happen that people map private playgrounds, pools etc. when tracing from satellite imagery. In that case, tagging these private places as `access=private` is preferable to deleting the place from OSM because in the latter case, the place may pop up again and again because mappers look at satellite imagery, think it is missing and add it again.
