### ISSUE TITLE
toilets:access for objects with toilets=yes

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1272]
### General
Affected tag(s) to be modified/added: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#Toilets_within_places https://taginfo.openstreetmap.org/keys/toilets%3Aaccess
Question asked: **Is toilet accessible to public?**

Answers: Yes/Only for customers

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

It would be disabled by default if accepted.

### Ideas for implementation

I will implement it (either for my private use or I will submit it as a PR after processing my current ones)

**Element selection:** trivial

**Metadata needed:** no

**Proposed GUI:** yes/no template

**Comment by westnordost** [comment]
I think this is reasonable. Perhaps there need to be more possible choices other than **yes** and **customers**.
Specifically, looking at taginfo, the value used most often is **permissive**. I do not really understand what this means, i.e. what kind of toilets would have this, so I think it is necessary to do a bit of research and see what toilet-places are understood by mappers as toilets with permissive access.

**Comment by matkoniecz** [comment]
permissive is pointless duplicate of yes

From what I remember in theory "permissive" is distinguished from "yes" that it can by withdrawn at any moment, but in practise this distinction is hard to survey and useless for data users

**Comment by matkoniecz** [comment]
> permissive | Open to general traffic until such time as the owner revokes the  permission which they are legally allowed to do at any time in the  future.
> yes | The public has an official, legally-enshrined right of access; i.e., it's a right of way.

https://wiki.openstreetmap.org/wiki/Key:access

So you are right about checking, toilets:access should be rather permissive/customers (I guess that there are places where owners are obligated to provide public toilets but...)

**Comment by westnordost** [comment]
By reading the wiki we know how the `access` tag was intended (for roads) but not how and for which places `toilets:access=permissive` in particular is used for toilets.

**Comment by westnordost** [comment]
I have doubts about this quest now. Any toilet within any kind of shop/restaurant is only for customers. It seems odd to ask about it. The question as such may confuse surveyors cause they don't know whether to answer "yes" or "for customers" and will choose based on what they feel like. 

I mean, we all know that **probably** the toilets within malls are for "customers" in the mall only, but everyone just uses them like public toilets because malls are a semi-public space. Toilets within a amusement park or a large camping grounds should probably be tagged as "for customers" only, but while (the surveyor) is in there, it might for him feel like "yes, they are public" because he might not get the connection that he is the customer of the amusement park right now. (Even more difficult to answer if there is a restaurant with connected toilets within the amusement park... etc)

I am concerned that this will lead to bad data quality as answer to the question is too subjective.
