### ISSUE TITLE
"this is a service street" for name quest

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1274]
https://www.openstreetmap.org/way/54515993
Is/was tagged as living_street without name.
For such streets it would be nice to have
"this is only a service street"
in the menu of the name quest.

**Comment by matkoniecz** [comment]
It is already available. Select first reason in the list available from  "it has no name" in "other answers" button.

**Comment by matkoniecz** [comment]
Though list is not too long, maybe it can be accessed directly from "other answers" menu.

**Comment by HolgerJeromin** [comment]
> It is already available. Select first reason in the list available from "it has no name" in "other answers" button.

Damn! :)
I even checked it, but thought "has no name" would only add `noname=yes` or something like that.

**Comment by westnordost** [comment]
Perhaps it helps if I add an ellipsis to menu items that lead to a second question?

**Comment by westnordost** [comment]
Hmm, I decided not to do this after all, because an ellipsis is hardly universally known to denote that there will be a follow-up question/menu. For example, I couldn't have answered your initial post with "_But, didn't you see the ... at the end of 'has no name'??_".

Also, it is hard to separate what would count as a follow-up question and what not - the "are you sure" dialog certainly not, but there are other dialogs which do not really present a list of options but still pose a question that is not entirely similar to the "are you sure", for example selecting "no housenumber" or selecting that there is no maxheight sign on a parking entrance.

I think, the user maybe has to simply faithfully answer the question the app asks. In this case, it asks for a name and the answer is that there is no name. Faithfully, because you need to trust that the app is smart enough to not simply tag `noname=yes` but further enquires for the reason for it having no name.

**Comment by goldfndr** [comment]
Desktop windowing systems tend to use an arrow or pointing triangle on the side (LTR/RTL sensitive) to indicate that a menu item leads to another menu. Might one work for "has no name"?

**Comment by rugk** [comment]
Actually common standard is:
* A button…
  – open a popup
* A button >
  ![image](https://user-images.githubusercontent.com/11966684/50287731-fb8b6200-0463-11e9-94ce-7fd78a3f9581.png)
  -> opens a submenu

i.e. that is something different.

And that **is** universally known and actually [how interfaces were design in Microsoft, Apple and KDE](https://stackoverflow.com/questions/637683/when-to-use-ellipsis-after-menu-items). The techical term is "ellipsis" BTW.
There are exact guidelines what counts as follow-up, i.e. "whether it needs *any* additional user input". Examples: Save As..., Open...

Quoting KDE again:
> A simple confirmation dialog is not considered a dialog that requires additional information.

But apart from that, 

> question that is not entirely similar to the "are you sure", for example selecting "no housenumber" or selecting that there is no maxheight sign on a parking entrance.

If the options you can do as the user still are only confirm or deny, I'd still say it is a confirmation dialog. 

I've looked at the other examples you've mentioned:
* may height (pops up question about 4,5m): It is not only confirmation, it is a completely new question, i.e., I'd say yes, use ellipsis. Users should know it does not tag "no-sign" instantly…
* no house number (asks for the building type): Obviously, yes, ellipsis. It is a completly new dialog, new question etc.

---

Generally you can see it like that:
* without an ellipsis: It is just another button from the main GUI that did not fit into it or is a rarely used one
* with an ellipsis: This opens a popup that may lead to further re-tagging/completely new quest/leaving a note etc. In any case the user is asked for something that is not just a "security-"confirmation.

**Comment by westnordost** [comment]
Well I'll reopen this then
