### ISSUE TITLE
Bike lane (piste cyclable) cannot be saved

### ISSUE THREAD

**Issue by smilearric** [westnordost/StreetComplete#1276]
Hello

Bike lane (piste cyclable) can not be saved. Lanes are selectable but OK button is not visible, only 'don't know'.

Latest version of the App. Android 8.1 with disabled GAPPS on a OnePlus 5T.

Thanx

**Comment by westnordost** [comment]
Did you select both sides?

**Comment by smilearric** [comment]
Hello,

Sorry, I didn't know that I had to select both side. That was not as obvious as when I had to choose the opening and closing hours.

What did I miss? Where was it written?

BTW, I already live that app! Fantastic job!

**Comment by rugk** [comment]
A small message at the bottom (a so-called [toast message](https://developer.android.com/guide/topics/ui/notifiers/toasts)) should have been shown when you tried to submit the quest with only one lane selected.

**Comment by smilearric** [comment]
Well, I tried some times but I could not notice any toast message, probably because I just could not submit.

**Comment by smilearric** [comment]
Alright! I see what you mean now!

Thanx for your patience. Maybe you could make a bit more clear somehow. Colorize? Add text?

I am not on the street now but I wonder how I will be able to differentiate each from the given pattern and identify them with the correct side.

I let you close the issue changing the tags since this is not a bug but more of a feature request.

**Comment by rugk** [comment]
> I am not on the street now but I wonder how I will be able to differentiate each side from the given pattern and identify them with the correct side of the street.

You don't, because this is done by SC magically… :wink: 

No, seriously, it uses the same way as it is on the map. You can even rotate it. I was also confused by that (see https://github.com/westnordost/StreetComplete/issues/723) when this has been first introduced in another quest type, but the little small compass icon in the corner of that area should give you a hint. :smile:

**Comment by westnordost** [comment]
> I am not on the street now but I wonder how I will be able to differentiate each side from the given pattern and identify them with the correct side of the street.

The street illustration that shows each side of the street is oriented the same way the map is. Also, there is a compass for orientation. Try rotating the map (the rotate gesture with two fingers) and you will see what I mean.

@rugk  There is no toast message anymore, because the OK button will only show when the form is complete.

**Comment by rugk** [comment]
Ah okay…
Then how can we make it more obvious again that you need to fill both sides?

**Comment by smilearric** [comment]
Maybe by making the question marks of the remaining side(s) 'glow'? This just an idea.
