### ISSUE TITLE
"OK" button is not consistently used

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#1282]
For some quests there is an orange "OK" bubble floating, sometimes it is just the old orange text "OK" at the bottom right.
I'd say, this should be consistent…

**Comment by matkoniecz** [comment]
> For some quests

which ones?

> sometimes it is just the old orange text

which ones?

**Comment by rugk** [comment]
E.g. the "notes quest": You have your comment entry at the bottom and the usual "OK" button.

Actually, that may be the only one. (I thought in the past it affacted more quests.)

**Comment by westnordost** [comment]
That is deliberate because the interface should be consistent with "create new note" form. The "OK" button is on the same level as the "Cancel"/"No, hide" button there as it is with other quests such as the wheelchair quest (Can't Answer / No / Limited / Yes).
An orange round OK button would pop up immediately after the user typed one letter because the form would be "complete". I found that behavior inadequate with a free text input like this.
