### ISSUE TITLE
Current performance is fun!

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1291]
Perhaps i did not used the app a while and updated to android 7 on my phone in the meantime.
Yesterday i solved many lit and others quests. 
The last time i remember it took 1-2 seconds to select the next.
Now I was able to click the next quest after a few hundred milliseconds. (new region with few downloaded quest on my phone?)

I did not found this improvement in the changelog, but it really rocks!

**Comment by westnordost** [comment]
Hmm I did not change anything there. Perhaps limiting the number of quests of one quest type to download to 1000 per area did the trick (and thus, less quests are displayed on the map). If it gets slow again, disable some quests in the settings so that not so many are displayed at the same time.

Anyway, thanks for the feedback!

Am 9. Dezember 2018 07:42:42 MEZ schrieb Holger Jeromin <notifications@github.com>:
>Perhaps i did not used the app a while and updated to android 7 on my
>phone in the meantime.
>Yesterday i solved many lit and others quests.
>The last time i remember it took 1-2 seconds to select the next.
>Now I was able to click the next quest after a few hundred
>milliseconds.
>
>I did not found this improvement in the changelog, but it really rocks!
