### ISSUE TITLE
Outdated quests and map features still appear after entering data via main website

### ISSUE THREAD

**Issue by welkie** [westnordost/StreetComplete#1293]
After adding details to OSM through the main website's editor, my StreetComplete app still shows quests related to the data. For example, I added business hours and address information to many local businesses, but the quests for adding their hours still appear.

The first thing I tried to do to solve this was clear the app's data in the apps section of my phone's settings. When I booted the app up again, I noticed it was still logged in, so I don't know if this actually cleared the data. I then tried uninstalling and reinstalling the app, and had the same outcome. I then explored the app's settings and found the option to "Invalidate quest cache". I tried this but it didn't do anything. The icons all disappeared but when I change the zoom level they all come back. Nothing outdated was removed.

It might be worth mentioning that the map data itself also is very out of date. I added heights to buildings a few months ago, but the buildings are still rendered as 2D shapes. I added paths a week ago but they do not appear in the map yet, and inaccurate paths I removed a week ago still appear.

**How to Reproduce**

- Note a quest displayed in the app.
- Log in to the main website and use its editor to add data that would solve the quest.
- Use "Invalidate quest cache" in the settings of the app.
- Note that the quest is still displayed in the app.

**Versions affected**
Android 8.10
StreetComplete 9.0

**Comment by HolgerJeromin** [comment]
> It might be worth mentioning that the map data itself also is very out of date.

This is a known issue and covered by #1011

**Comment by welkie** [comment]
@HolgerJeromin I read that issue before posting this one and I think I may have misunderstood this part:

> the map is no longer up-to-date with the OSM 

I interpreted that as meaning the tile data was in the background layer and the OSM data was layered over it in the foreground, and that the issue creator was just noticing the tiles being out of date. I take it tiles means all data in OSM? Both background shapes and nodes, etc? If so, that would explain why all of the data in my app is out of date, including nodes.

**Comment by westnordost** [comment]
**Short answer**: Don't worry, everything is fine.

**Longer answer**:
1. If you solve a quest that turns out to be outdated, the answer will be dropped automatically and the app also triggers the "Invalidate quest cache" for the area around where the conflict happened automatically.
2. the displayed background map comes from some vector tile server on a shoestring, the quests pins on the other hand come from the Overpass API. So, quests are always based on up-to-date data at the time of download, independent of the displayed map.
3. "Invalidate quest cache" does exactly what is explained in the dialog that pop up when you press that option. It does not delete the old quests but marks the quests (in the area) as to-be-downloaded next time the app downloads this quest type.
