### ISSUE TITLE
Help users anticipate consequences of "Can't Answer" by re-wording

### ISSUE THREAD

**Issue by georg-d** [westnordost/StreetComplete#1296]
When I began using StreetComplete and came across "Can't Answer" (e.g. because I do not understand the language on a sign) I did not know what will happen after pressing "Can't Answer", i.e. whether I tell noone or just me can't answer this quest, and whether I would be able to undo that action. Hence, I avoided clicking it for quite a while and I am still in doubt again and again - not a really desirable user experience.

Suggestion: Let's help users _anticipate consequences_ by
1. re-wording "Can't Answer" (DE: "Nicht beantwortbar") to "Can't Answer..." (DE:  "Nicht beantwortbar...") so the user sees the  common indication "..." that clicking that text is not the final action but will open some dialog. I suggested that indication as it's already used in SC, e.g. in "Other answers...", but I'm happy with other indications as well :-)
2. re-wording the dialog text so it becomes absolutely clear that one answer hides the quest for _all users_ (instead, the created note is shown) while the other answer only hides it for the _individual user_ (I am not yet sure whether this is the real behaviour). 
Current text in EN
`Leave a note instead? You can leave a public note at this location which other mappers can comment on and hopefully resolve: <no, just hide> <ok>`
New wording idea
`Only hide for you or for all users? The quest can be set to not appear again for you personally only, or you can replace this quest by a public note which other mappers can comment on and hopefully resolve: <Just hide for me> <Replace by note for all users>`
Current text in DE 
`Stattdessen eine Notiz hinterlassen? Du kannst hier eine öffentliche Notiz hinterlassen, welche von anderen kommentiert und hoffentlich gelöst werden kann: <Nein, verstecken> <OK>`
New wording idea
`Nur für Dich verstecken oder für alle Nutzer? Du kannst die Frage nur für Dich nicht mehr anzeigen lassen, oder diese Frage für alle Nutzer durch eine öffentliche Notiz ersetzen, welche von anderen kommentiert und hoffentlich gelöst werden kann: <Nur für mich verstecken> <Durch Noitz für alle ersetzen>`

**Comment by rugk** [comment]
BTW dev note for !1.": Preferably use `…` the Unicode character for three dots.

**Comment by matkoniecz** [comment]
> I did not find a language toggle in the app settings

SC simply follows system language, it is possible to temporarily change it in the settings (even reboot is not necessary).

**Comment by smichel17** [comment]
This is a good idea for all actions that will open a dialog with additional options. When I was learning the app (back before I trusted the undo button), I often wanted to try an option to see if there were any sub-options or a dialog that would give me more information about what it meant, but I was reluctant because I didn't know if I'd accidentally apply an incorrect option.

**Comment by georg-d** [comment]
> SC simply follows system language, it is possible to temporarily change it in the phone settings (even reboot is not necessary).

Thank you, @matkoniecz, that helped me to make a suggestion for EN and DE

**Comment by goldfndr** [comment]
Relevant to ... or … : #1274

**Comment by westnordost** [comment]
Hmm, I find the wording suggestion is too long to display in the dialog that also shows the input comment text. Also, the button texts are too long. Of course, it would be possible to first show a dialog that tells the user about the options - _Leave a public note or just hide for yourself?_ and only then show the view to input the note. I chose to deal with it in just one dialog because leaving a note should be the desireable thing to do and I did not want to nest the dialogs too deep. But the current behavior is not set in stone and the second reason is not valid anymore, as the note input field is not a dialog anymore but in the bottom sheet.

Alternatively, what do you think about

_You can leave a public note at this location which other mappers can comment on and hopefully resolve or alternatively just hide the quest for yourself only: <hide for myself> <ok>_

**Comment by rugk** [comment]
> You can leave a public note at this location which other mappers can comment on and hopefully resolve or alternatively just hide the quest for yourself only: 

Sounds good, IMHO. :+1: 

So shall we discuss that "…" (ellipsis) thing in https://github.com/westnordost/StreetComplete/issues/1274 and keep this here about the text change? If so please change the issue title of https://github.com/westnordost/StreetComplete/issues/1274 as it is currently just about something totally different.

**Comment by georg-d** [comment]
I understand the points raised by @westnordost 
1. Text suggested is IMHO fine :)  Buttons would then be `<create note><just hide for me>`? 
2. Concerning space, just an idea for other cases/dialogs: Maybe SC's GUI framework offers collapsable/expandable text like [Confluence expand macro](https://confluence.atlassian.com/doc/expand-macro-223222352.html) (example at the very top) or an i-Button that shows a baloon tip after pressing it. This allows to initially display only the question _Leave a public note or just hide for yourself?_ - saving screen space for the core content and being sufficient for experienced users - while still supporting new users with a explanation (without any need to sacrifice understandability for space reasons).

**Comment by westnordost** [comment]
Added
