### ISSUE TITLE
option to disable auto-download

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#13]
I'd like the default behavior to be that quests are downloaded only when asked for.  I realize others want different behavior, so perhaps on first launch there can be a "Download quests from current location automatically (manual download can always be requested)? Yes/No" to set the preference.

This first screen could also ask the user to authorize OSM.  That is often more convenient when installing an app than when trying to use it in the field (not intrinsically, but I often install and try new things in situations where finding my OSM password and typing is easier).

**Comment by westnordost** [comment]
1. I won't implement a first screen that asks the user for authorization. Instead, I want to delay to force the user to login as long as possible: The user should first be able to look around in the app unbothered, try it out, solve some quests etc. before being pushed to login / register.
This behavior might be unusual when you come from desktop applications and/or other OSM editors, but it is actually the design guideline for mobile apps, also because of the reason mentioned above. The architecture of the app allows this lazy login, as any quests you solve while not being logged in will be uploaded once you do. So there is really no rush - if you are in the field or don't remember your OSM password right now or don't have proper internet, it does really not matter. Eventually, the user's contributions will find their way into OSM if they really get hooked into this app.

2. The default behavior should be what the user would expect, and what the user (on a smartphone) expects is usually that things are fetched automatically for him. I.e. usually if you open your mail app, it automatically checks for new mails. So, the default behavior will stay to be like it is now.

3. But: There will be an option to turn off automatic download. This is tracked in #9
