### ISSUE TITLE
traffic_signals:sound - partially

### ISSUE THREAD

**Issue by call-me-matt** [westnordost/StreetComplete#1300]
Hi there. I propose to add a "partially" option to the traffic_signals:sound option as described in the [wiki](https://wiki.openstreetmap.org/wiki/Key:traffic_signals:sound). Otherwise users will tag the traffic lights with yes, even if only the walking signal is audible.

**Comment by rugk** [comment]
But then users need to differentiate between whether `locate` or `walk` sounds is presented? Also, how common is that actually?

**Comment by ENT8R** [comment]
> Also, how common is that actually?

It's not that common at all: https://taginfo.openstreetmap.org/keys/?key=traffic_signals%3Asound#values
Main values are obviously `yes` and `no` with both about 50% and `walk` or `locate` have only about 1% of all values of `traffic_signals:sound`

**Comment by rugk** [comment]
Well… I don't think we can use the OSM data for judging this, it is likely just not well-mapped. (and people could even do the same issue an mapping it as `yes` even if it was not relly both sounds.)

**Comment by call-me-matt** [comment]
Here it is quite common for traffic lights to have only the walking sound, that's why I was wondering about the tag.

**Comment by call-me-matt** [comment]
Northern Germany

**Comment by goldfndr** [comment]
Here in Washington state, USA, I've only heard a walk sound (which actually tends to be two different sounds, a tick tock for one road and a cuckoo for the other), not a locate sound (although pressing the call button does tend to elicit a "Wait" speech in a man's voice). I didn't know that "yes" meant "both" -- [the Key:crossing page](https://wiki.openstreetmap.org/wiki/Key:crossing) [(and other referring pages)](https://wiki.openstreetmap.org/wiki/Special:WhatLinksHere/Key:traffic_signals:sound) only mentions `yes` and `no` values. I'm a bit sad that [when it was edited to add `locate` and `walk`](https://wiki.openstreetmap.org/w/index.php?title=Key:traffic_signals:sound&diff=next&oldid=467869), `yes` was defined as meaning `both` rather than becoming ambiguous.

**Comment by westnordost** [comment]
I would consider Lulu-Ann's edit to be wiki-fiddling. Probably well meant of course, but as a general rule in OSM, one cannot simply add more values if this means the meaning of the other previously defined tags is changed.

The correct way to extend this scheme is to use subtags like `traffic_signals:sound:locate=yes/no` because whether a traffic light has sound signals at all is one information, and what type of sound signals there are is another information.
But as my previous commenters, I doubt the usefulness of this additional information because it is unclear (to me) what traffic light with sound signals for the blind would not have a walk-sound.

**Comment by call-me-matt** [comment]
@wno: Just to answer your question - even that exists: its usually the older traffic lights that come with tactile (vibrating) signals instead of a walking sound. Later they get equipped with audio signals for locating (https://www.stadt-koeln.de/artikel/03944/index.html).

**Comment by rugk** [comment]
@call-me-matt What is also interesting to me is that the beep may only actually be used, when the user presses the button at the bottom of the signal. That may be important to SC users, as they may miss the sound when not doing so and going over the traffic light when it shows "green".

**Comment by curbia** [comment]
> But then users need to differentiate between whether `locate` or `walk` sounds is presented? Also, how common is that actually?

A sound to locate the pole is the *only* form of sound at crossings here, for every place I have been to in my city. It would be nice to be able to tag as such in SCEE. I find myself having to go back over my walking routes at my computer later to change all the tags to `traffic_signals:sound=locate`

**Comment by mnalis** [comment]
> It would be nice to be able to tag as such in SCEE. I find myself having to go back over my walking routes at my computer later to change all the tags to traffic_signals:sound=locate

Note that this issue tracker is for "vanilla" StreetComplete, not for [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) - you should add feature request for SCEE [there](https://github.com/Helium314/SCEE/issues). 
Anyway, not sure if you know @curbia, if you enable expert mode in SCEE settings , you get `Show/Edit tags` option in `Other anwers`, where you can manually update the value of the `traffic_signals:sound` on the go. 
Sure, it's not as easy as direct answer, but significantly better then hoping you'll remember to correctly edit all of them when you get back home (at least for me, YMMV).
