### ISSUE TITLE
Idea: Add shortcut icons for last 3 (or more) selections for every quest type

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#131]
This would be helpful when solving for example streets, which are mostly the same type within the same area. Instead of selecting the same again and again I could use a shortcut for "Paved -> Asphalt" for the last selection.

![](https://files.natenom.com/nidx/nobackup/sharing/5e427afcb9f60f9ce5f3073ed5c15bb082f7b1b8aee9afada10deb5b229ab396.png)

The normal way needs four "klicks" and the new way only one.

**Comment by welkie** [comment]
I like this. I had to repeat the steps so many times today to do asphalt roads.

**Comment by westnordost** [comment]
★ 838, whoa! Did you actually solve all those quests while being there?
At this point, I think the planned feature to only allow answering quests if you are near will be quite unpopular.

That the selection of the surface is a bit uncomfortable right now would be less of a problem if you need to be there, because then the act of inputting the data will take much less time than actually walking there (and down the street).

**Comment by welkie** [comment]
That feature sounds pretty limiting. I don't complete quests I'm not near unless I know the answer 100%. When I installed the app I saw quests for roads that I walk on almost every day. It would really suck if I had to go walk to them just to confirm that they're asphalt.

**Comment by Natenom** [comment]
Almost all of them were solved when I was there. Only few were solved "remote" because I use the bicycle and know very excatly how the street is made. And only those roads I answer not being there.

BTW, 975 yesterday :)

I wouldn't like to be limited to my current position. Sometimes I just cycle in new areas and then remember most of the streets to answer them later.

**Comment by westnordost** [comment]
I'll definitely put something like this in there as a data quality "guarantee" and also to limit vandalism latest when I introduce a "leaderboard" where you can look at how many quests other people solved. The weakest possible implementation would be to have the user okay a confirmation dialog in the case of him not being there.

**Comment by Natenom** [comment]
Maybe you could unlock "remote" editing only for accounts older than x time and/or accounts that already made specific amount of quests in StreetComplete or in OSM in general.

**Comment by welkie** [comment]
> Maybe you could unlock "remote" editing only for accounts older than x time and/or accounts that already made specific amount of quests in StreetComplete or in OSM in general.

@Natenom I think that is a fair compromise.

**Comment by alejandroscf** [comment]
I think you deviated from the topic of this issue :P 
I think it would be helpful to have that recent used shortcuts.

**Comment by Aypac** [comment]
I agree. Also #274 might help. 

Maybe there is something "in between" for the being there issue: make it "more work" if you are not there (e.g. you have to conform a warning if you want to make a change that is farther than 100m from you current location). I guess a lot of users don't understand that it is actually better not to answer than giving a wrong answer.

**Comment by Mannshoch** [comment]
Could it maybe be an Idea to be able to setup how you are traveling and record your route?
If you are on food you could show Housenumbers and streenames, pedestrains and something similar. Drive by Bicycle or by Car you could tag road names with speed limits while drive lower than 50km/h. 

Maybe Streetcompleet could do a position recording and Ask Questions on the way you took earlier, that would also be better on ways on food, because friends of mine do not like it if I look the whole walk on my phone.

**Comment by westnordost** [comment]
This has been mitigated by a better surface selection scteen that first only shows the most common ones
