### ISSUE TITLE
maxspeed:type vs source:maxspeed

### ISSUE THREAD

**Issue by JulienPalard** [westnordost/StreetComplete#1312]
Noticed the app is adding `maxspeed:type=FR:zone30` for speed limited zones in france like those ones: ![](https://duckduckgo.com/i/05a832a6.png).

But the [OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/FR:Key:source:maxspeed) is telling me to add `source:maxspeed=FR:zone30`.

More specifically the [maxspeed:type wiki page](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type) is telling:

> While maxspeed:type=* is more used in Great Britain, the rest of the world has more tags of source:maxspeed=* in use for the same purpose (and semantics)

so it looks "against the common usage" to add some `maxspeed:type` in france (yet I did not did my own statistics to compare both usages).

**Comment by ENT8R** [comment]
StreetComplete adds `maxspeed:type` instead of `source:maxspeed` because there are so many variations of how to tag a speed limit over the world and there is no consequent tagging scheme, but StreetComplete obviously needs one to add a value...
See also https://github.com/westnordost/StreetComplete/issues/492#issuecomment-326080750 for why `maxspeed:type` is used over `source:maxspeed`

**Comment by JulienPalard** [comment]
OK thanks for the heads up :)

**Comment by JulienPalard** [comment]
Oh while I'm here, thanks all contributors of StreetComplete, I absolutly like this app \o/
