### ISSUE TITLE
Urban/rural is confusing in maxspeed quest

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1314]
It is unclear that (at least in Poland) it is asking about a legal status of road (in settlement for maxspeed purposes), not whatever it is rural.

Completely rural areas may be considered inhabited areas for this purpose.

Maybe it would be possible to have question asking "Is it a populated area for max speed purposes"?

**Comment by rugk** [comment]
Maybe "Is it (legally) a rural area?"?

**Comment by westnordost** [comment]
This is problematic because how would a surveyor know what is "legally" a rural area? The exact definitions what are rural and urban areas somewhat differ from another in different countries. This would require specialist knowledge of the surveyor, which is something we want to avoid. The alternative is that the app has this specialist knowledge and asks the correct questions based on the location.

This already happens to a degree: In the UK, something is considered within a built-up area if there are street lanterns that are at most X meters apart. In the UK, the app asks the user whether the street is lit or not.
However, to maintain the knowledge about the exact specific definitions of built-up-areas according to the highway code in the app is pretty unworkable. The definition of a built-up area in the UK deviates so much from common sense / the usual definition, that it was worth to implement an exception. But what about Poland?

**Comment by westnordost** [comment]
It is the same in Germany. To be legally built-up in respect to speed limits, it must be signposted by town entrance signs. I think showing the sign as an image is not a good idea, because they (may) differ greatly for different countries (compare Poland and Germany for starters) which would amount to **a lot** of work. Mentioning this in the text should be enough, however, as said, different countries have different definitions here. So, the text cannot simply be changed to include the note about the town entrance sign because that would make the text wrong for countries/states where built-up areas are not defined this way.
As a prominent example, I think I remember reading in the US states legislation that a built-up areas are defined more vague and according to what can be seen on the road rather than signs.

Anyway, to cut it short, this requires some research in which countries to display the town entrance sign hint and in which not.

**Comment by matkoniecz** [comment]
To get back to something fixable without huge amount of work:

maybe instead of rural/urban something like "built-up/not built-up" would be better?

**Comment by rugk** [comment]
IMHO it is not so hard for a user to determinante whether an area is built-up or not. There are signs, all people who drive cars are supposed to know this (and for them, this quest makes the most sense... We also require the user to have some basic knowledge about where street signs like this maxspeed thing are positioned and where they then apply, etc.).
So we can consider this "common knowledge", IMHO.

**Comment by rugk** [comment]
To help the user, showing one of the previously discussed images may certainly help though. Maybe only do so for countries, where you know the correct sign, and do not show it for any other countries.
You then do not need a big "legal discussion".

**Comment by matkoniecz** [comment]
> IMHO it is not so hard for a user to determinante whether an area is built-up or not. There are signs, all people who drive cars are supposed to know this

The problem is that signs are different in different regions and in some there are not signs but rather a some definition.

**Comment by westnordost** [comment]
I am still open for wording suggestions.

**Comment by matkoniecz** [comment]
built-up/rural

built-up/not built-up

built-up/outside built-up

in settlement/outside settlement

In general I want to solve problem with suggesting that rural area is never built-up.

**Comment by rugk** [comment]
inside town/outside (of) town?

**Comment by matkoniecz** [comment]
@rugk The same problem, villages also may have built-up areas and parts of town may not be a built-up area.
