### ISSUE TITLE
Roundabout marked as oneway=-1

### ISSUE THREAD

**Issue by boothym** [westnordost/StreetComplete#1320]
Saw this changeset created by the StreetComplete app which apparently used improveosm.org to highlight missing one way tags. That's fine, but the issue is that the user has added oneway=-1 to what should be tagged as junction=roundabout.

https://www.openstreetmap.org/changeset/66362617

**Comment by westnordost** [comment]
Okay, thank you for the report. 

Let's see,

So the [improveosm data](https://missingroads.skobbler.net/dumps/OneWays/20190117/) for way [216802914](https://www.openstreetmap.org/way/216802914) says that 98.2% of 169 drivers drove from node id [1123255720](https://www.openstreetmap.org/node/1123255720) to node id [2261546145](https://www.openstreetmap.org/node/2261546145).

Fair enough, that doesn't look like the improveosm data is wrong. I suspect that the logic in StreetComplete is flawed when dealing with rings. Will investigate further.

**Comment by rugk** [comment]
Well yes, obviously people in roundabouts only drive in one direction… would be kinda bad otherwise. :smiley:

**Comment by westnordost** [comment]
Okay, so the problem is in [AddOneway line 93](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/oneway/AddOneway.kt#L93)

**Comment by rugk** [comment]
I only had a quick look at the code you mentioned, but the function still only determinate the direction. For a roundabout possibly "null" would be the expected return value, but in line 93 this is already too late.

And I also guess it is hard to determinate in which directory a circle points to… just saying… :thinking: 

---

So taking a step back and thinking about the general problem (i.e. roundabouts!), I think there is much more that may be done here:
1. SC should also detect before asking a question whether the street is actually a roundabout.
2. If so, ask the user just "Is this a roundabout?" (because already asking "Is this an one-way street?" for a roundabout makes little sense), possibly with the current image of the quest anyway, so it is clear what is meant.
3. If all that is done and answered by yes, tag it properly as the OP suggested. 

And maybe (did not check if already done):
0. Exclude streets already tagged as roundabouts from the query, so such a question is not asked for an already tagged roundabout.

Note that 2. would require country metadata on in which direction roundabouts go in different counties. Although, AFAIK (or assume), this should usually be derivable from the left/righthand traffic data.

**Comment by westnordost** [comment]
Fact is, for ways that are circles, it cannot be determined from the improveOSM data in which direction the people drove. It would also be wrong to assume that it will be clockwise for left-hand-driving countries and counter-clockwise for others because not every ring is a roundabout. Without it explicitly being tagged as one, it can also not reliably determined.

So, in these cases, it is just known that this way is probably a oneway, but not into which direction. An input from the user would be required here. However, that would mean to change the wording of the question and the form itself completely. I will save myself the effort here and just exclude ways that are circles (and roundabouts) from the quest filter because
- to determine whether ways that are circles are oneways or not are less important (for routing)
- many such ways will actually be roundabouts or circulars for which the `oneway` tag is superfluous. Also, having to consider roundabouts in this quest would probably mean to redesign or at least reword the quest: The question is clear - is this a oneway or not? When a surveyor sees a roundabout, nobody would get the idea to instead look for an answer lie _"it is a roundabout"_ in the _"Other answers..."_ menu rather than just confirming the question by tapping on the "yes" button.

**Comment by boothym** [comment]
T hanks for sorting this. Suppose the only other option could be to add a note when the user comes across a circle?

**Comment by rugk** [comment]
I've already replied [here](https://github.com/westnordost/StreetComplete/commit/c714c0a2aaf26c365ebaed7cc76ffb90b2907f83#commitcomment-31980607), but to come back I here I see a use-case for a "Is this a roundabout?" question/quest.

So after all, if the implementation for changing the question here is too hard, maybe it's suited for a new quest?
