### ISSUE TITLE
Lit quest tags `lit=answer`

### ISSUE THREAD

**Issue by nmxcgeo** [westnordost/StreetComplete#1328]
Streetcomplete adds "lit"="answer" as an answer to the AddWayLit-Quest. This tag has never been seen before, all occurrences have been added by StreetComplete. 

https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete however states that:
> 🚧 Established tags only: No new or unestablished tags should be introduced through StreetComplete. Establishing tags must remain a community process and not be dictated by software implementation.

**How to Reproduce**
Have a look at https://overpass-turbo.eu/s/FKG and https://overpass-turbo.eu/s/FKH (run this through `sort -u | sed -e 's#^#https://osm.org/changeset/#'` to get a linklist).

**Versions affected**
Android version: unknown, probably all.
StreetComplete 10.0-beta1 and StreetComplete 10.0-beta2

Please consider reverting these changes completely.

Greetings Nmxosm

**Comment by westnordost** [comment]
Thank you for the report and also for the handy overpass queries to find all the mistaggings. This is definitely a bug and warrants an immediate release to beta3 today.

After fixing this bug and releasing a new version, I will leave this bug open as a reminder to fix all occurrences after all the v10 users updated to version 10.0-beta3.

**Comment by westnordost** [comment]
I now fixed the mistaggings with the help of your overpass query because all the users are now on v10.0-beta3 or later. This is the changeset: https://www.openstreetmap.org/changeset/67144459

The bug in 10.0-beta1 and 10.0-beta2 was that when the user answered that a street is indeed lit, the app would tag it as `lit=answer` instead. So, it was luckily straightforward to fix the mistaggings in the linked changeset: just replace all `lit=answer` with `lit=yes`.
