### ISSUE TITLE
Give way restrictions for bikes

### ISSUE THREAD

**Issue by Phyks** [westnordost/StreetComplete#1334]
Hi,

### General
Affected tag(s) to be modified/added: [Traffic signals](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals) (new relations created actually)
Question asked: **Is there a give way restriction at this traffic light?**

In France, it is now common to have "give way" restrictions for bikes at traffic lights. This small sign indicates that some moves can be done by bikes, even if the light is red, provided that they consider the traffic light as a "give way" sign. There is a scheme to tag this, based on relations, which is described in [the French wiki](https://wiki.openstreetmap.org/wiki/FR:Bicycle#Panonceaux_de_C.C3.A9dez-le-passage_cycliste_au_feu). These are represented by relations of `type=restriction` with at least 3 members:
* `from`, the origin of the cyclist.
* `to`, the road at the end of the move, allowed when the traffic light is red.
* `via`, the traffic light.

This tagging scheme is quite complicated and, due to the lack of easy tool to add it, often not well completed. StreetComplete could probably be a handy tool to fill in these. However, having these signs filled in OSM is important, typically for routing (especially travel time computation).

Note that this might exist in other countries as well but I'm not aware of it and did not find such info in the OSM wiki :/

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam): allowed moves differ from one crossing to another.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort): most cities are now putting these signs in place and they are put on most of the traffic signals.

### Ideas for implementation

I'm not super aware of the way StreetComplete works, so my ideas might not be a good fit, sorry :/ Please tell me if that is the case.

#### Filling in new such relations

StreetComplete could fetch the `highway=traffic_signals` around the user and display the quest on it. The wording could be "Are there give way signs for bikes at this crossing?". If there are, the user could fill multiple origin/destination moves by clicking on the different incoming/outcoming segments from the road crossing.

The move picking window could look like a table in the quest panel with two columns: origin and destination. The user could click the cells to fill in as much lines as they'd like, each line being a different authorized move.

A new from/to relation would be created for each move entered by the user.

**Metadata needed:** As far as I know, this is only valid for France.

#### Completing existing relations

Another possible task, rather than creating such relations would be to complete them. Due to the quite complex scheme used, many users only fill in the `via` member (the traffic signal) but not the moves through the `from` and `to` members.

A similar UI could be used with a task such as "Can you complete the allowed moves for this bicycle give way relation?".

I have some ideas for the UI part. However, I am not sure whether this quest would be fine for StreetComplete or whether it could be achievable with the way StreetComplete works. If you think this is fine and more info would be required on a possible UI, I can provide more details or try to provide a picture of what I have in mind.

Thanks!
Best,

**Comment by westnordost** [comment]
Hi Phyks,

Thank you for the input! Turn/give way restrictions are certainly a very useful thing to survey and map, however, unfortunately, this app is too simple to deal with this kind of stuff.
Specifically, it would need to have the ability to add a new relation to an intersection and additionally. Additionally, probably the possibility to split ways up in case the node dedicated as `via` is not actually an endpoint of a way.

> Limitations of StreetComplete
>     🌟 Only existing elements can be extended, no elements can be added or removed.
>     ✂️ The geometry of elements cannot be changed, i.e. it is not possible to split a way (currently)
>     🏷️ So, basically: Only tags can be edited
( see [Adding new quests to StreetComplete](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete) )

These limitations cannot be changed easily.

Also, unfortunately it might not be fit to make this into a quest even if the above mentioned limitation of StreetComplete was dropped one day, because there is not tag to indicate that an intersection does **not** have a turn/give way restriction. From the adding quest guidelines linked above:

> 🤔 No unanswerable quests: All generated quests need to be actually answerable (no false-positives). This means that any answer given by the user must result in something being tagged. For example, a quest that asks for the website of a place must be able to tag the element somehow if the user answers that the place has no website - otherwise, the next user will be asked the same question. Sometimes, due to the nature of how things are tagged in OSM (such as the one given in the example) it is unfortunately simply not possible to fulfill this.

Regarding the completion of existing turn type relation restrictions, this would theoretically be possible, but:
1. as mentioned at the beginning, it may be necessary to split up the `from` and `to` ways, which this app can also not do
2. the map view is not interactive for each quest that you can use it actively to mark some roads etc. Changing this so that it is interactive (and that the behavior can be defined by each individual quest) would be *a lot* of work
3. even if it is interactive, any UI that comes to my mind would be quite complicated and for this to work reliably, the UI must be dead simple and clear because users of this app are not OpenStreetMap experts and StreetComplete is not a full-blown editor
4. I can't imagine that there are really a lot of such relations where the `from` and `to` members are missing so that an implementation is worth it

You can still post your ideas about a possible UI here, if you want, but I can tell you that it is very unlikely this would be implemented in the near future, even if "🤔 No unanswerable quests" is solved somehow.

Instead, I suggest that you open a feature request at the iD editor. As far as I remember, iD already has a feature about adding a turn type restriction - with a visual UI as well. So if I remember right, maybe the French give-way-for-bikes can easily be added and even reusing the same UI.

Cheers
Tobias

**Comment by Phyks** [comment]
Hi,

Wow, thanks a lot for this very detailed answer! 

> Also, unfortunately it might not be fit to make this into a quest even if the above mentioned limitation of StreetComplete was dropped one day, because there is no tag to indicate that an intersection does not have a turn/give way restriction.

Sorry, I missed the fact that indeed, there is currently no tagging to indicate that an intersection does not have a turn/give way restriction :/ Sure, adding these relations from scratch with StreetComplete seems compromised.

> Regarding the completion of existing turn type relation restrictions, this would theoretically be possible

Just to sum up, if I'm not mistaking, this should be fine according to StreetComplete requirements (answerable quests, no false positives, etc). Except from the UI side, this requires to be able to fetch these relations (there is an Overpass query for this) and to add new members to them. The only (but still major) downside is that the existing ways should be split at the crossing, otherwise it would require splitting the ways.


> Regarding the completion of existing turn type relation restrictions, this would theoretically be possible, but:

1. Maybe the quest should be filtered further on the "incomplete relations with incoming roads split at the crossing", I should check whether this could be achievable with Overpass queries.
2. Ok, I'll drop the interactive map idea. Maybe the interactive part could be in a "schematized map" as done for cycleways quest?

Concerning the 4th point, I was originally only considering the `type=restriction; restriction:bicycle=give_way`. I did some stats in Paris, there are 584 such relations so far and 516 incompletes ones (just tagging the traffic signal, without expliciting the allowed moves). This might be an extreme case though. This "relation completion" quest could probably be extended to any restriction relation actually.


> Instead, I suggest that you open a feature request at the iD editor. As far as I remember, iD already has a feature about adding a turn type restriction - with a visual UI as well. So if I remember right, maybe the French give-way-for-bikes can easily be added and even reusing the same UI.

Thanks for the suggestion, I will do it!

Best,

**Comment by westnordost** [comment]
I think I will close this issue, as its realization (only the second point - completing incomplete restrictions) is technically not feasible for the given reasons in my initial answer. This should not be a dismissal of the overall idea, but at the moment and foreseeable future, it is too far out of StreetComplete's capabilities.
