### ISSUE TITLE
Unneeded footway quest for living_street,service with sidewalk=no?

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1336]
I have 
````
highway=living_street
sidewalk=no
````
living street are always usable for pedestrian (and have often no sidewalk) do they?

or even
````
highway=service
sidewalk=no
````

**Comment by westnordost** [comment]
Hm yeah, and pedestrian roads. I thought I did exclude living streets from the overpass query already.

**Comment by westnordost** [comment]
Hey, I did. @HolgerJeromin so did you make this example up, or did Streetcomplete v10 really tag this somewhere?

**Comment by HolgerJeromin** [comment]
I really got a quest for https://www.openstreetmap.org/way/26549937

**Comment by westnordost** [comment]
Ah okay, you got a quest asking whether it is accessible on foot, not whether it has a sidewalk. I overread that part.
The quest is shown because `sidewalk=no` is tagged, which seems already like duplicate information, at least on a living street.

I will change it so that the quest is never shown for service and living street roads, regardless if `sidewalk` is tagged as `no`.
