### ISSUE TITLE
HOT Microgrants

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#1337]
Please consider applying for a HOT Microgrant to further the development of StreetComplete to improve OSM. Below is the announcement from Humanitarian OpenStreetMap.

Hello,

A friendly reminder that the deadline to apply for a 2019 HOT Microgrant is just two weeks away! Communities are invited to apply for a Microgrant that will help them to scale their mapping activities and their local and global impact. Applications are due by February 28 at 12midnight EST. Please see the HOT blog for the application review criteria and the link to the application.

If you have any questions, please do not hesitate to contact us at microgrants@hotosm.org. A member of our team will reply within 24-48 hours.

Cheers!

Jessica

On Wed, Feb 6, 2019 at 12:54 PM Jessica Bergmann wrote:

    Hi Everyone,

    HOT is excited to announce the launch of the 2019 HOT Microgrants program! This year, we will be awarding Microgrants between $2,000-$5,000 for 8-10 communities throughout the world to reduce barriers and scale their mapping activities and impact. Applications for the 2019 Microgrants program are due by February 28 at 12midnight EST and can be found using this link.  

    We especially encourage communities from the Caribbean, Middle East, North Africa, and Asia to apply in order to continue diversifying the global mapping community. Before submitting your application, ensure that you coordinate with other mapping communities in your country/region, finding opportunities for collaboration where possible and minimizing the number of applications that propose the same mapping project. For more information about the HOT Microgrants program and to see the application review criteria, please check the HOT blog.

    Please forward this information along to any other individuals and communities you believe would make excellent candidates for this opportunity. Any questions can be sent to microgrants@hotosm.org or directly to me at this email address. Please allow 24-48 hours for a member of our team to reply.

    Best,

    Jessica

**Comment by westnordost** [comment]
Ticket 1337. ;-)

I do run this project in my free time, a grant would not increase the time I would be able to work on it since I am also full-time employed. (This is why there is also no "Donate" button here anywhere.)

However, anyone who has a concrete idea for StreetComplete and able to work on it or would like to work on an already existing ticket, is free to do so. Paid or not, I don't mind. Of course, as with any contribution, it should first discussed in a ticket whether a feature can be included in the app or not.

I am not sure if this HOT microgrants program applies to software projects as well (GSOC style) or is rather focussed on building local communities. It sounds like more the latter, but for anyone interested in applying for a microgrant to work on a (specific) thing in StreetComplete, it can't hurt to apply - or at least ask if the program does include sponsorships like that.

**Comment by matkoniecz** [comment]
This can be safely closed as (a) time for making grant requests ends today (b) according to my conversation with microgrants@hotosm.org it is not intended to support work of individual programmers but rather directly support local communities (indirect support via improving editors is not qualifying).
