### ISSUE TITLE
Allow explicit changeset commit

### ISSUE THREAD

**Issue by hholzgra** [westnordost/StreetComplete#136]
So this is actually the reverse of issue #21 somehow: 

I thought that the "Upload Answers" option would also create a new changeset afterwards, but found out the hard way that it didn't, so spanning large parts of Europe and Asia in a single changeset instead of having one local to Yakushima / Japan (where I knew road surfaces from recent days survey), and Oldinghausen / Germany where I've grown up.

(I was in Japan for vacation, and trying to kill time while waiting for a ferry, so after I solved as many local quests as I could I tried to kill more time by solving quests in a remote area that I'm pretty familiar with)

**Comment by westnordost** [comment]
I will disable solving quests that are not in your vicinity soon because the tool is intended to be used on a survey. It also sets the "source" to "survey", this would be a lie if users were able to solve quests not-on-a-survey.
Following the outcry over this limiting change, I will then probably (have to) implement a detection whether any such quest is solved in a survey or through local knowledge and put those in different changesets.

So, the feature exactly as you request it will not be implemented, but something that also solves your use case will (probably) as described above.
