### ISSUE TITLE
Dev build: Missing strings

### ISSUE THREAD

**Issue by JulienPalard** [westnordost/StreetComplete#1360]
For the home-made dev build I did for https://github.com/westnordost/StreetComplete/issues/1357 I'm having an issue, not all strings are displayed:

https://www.dropbox.com/s/jw35ar4fxe7rj8f/2019-03-25%2009.00.43.png?dl=0

I bet I'm missing a simple build step but I didn't found it in the docs.

**How to Reproduce**

I just downloaded Android Studio on Debian testing, cloned StreetComplete (caafa657), built an APK, installed it and tried it.

**Versions affected**
 StreetComplete commit caafa657, Android 8.1.0.

**Comment by westnordost** [comment]
Hmm, this is odd. I don't think you are missing a step.

The strings for French are definitely there (and if they aren't, the fallback is English).

Maybe this is a problem with the new dark mode. If you set the theme in the settings explicitly on Light (and/or switch forth and back a few times), does this change anything?

Where exactly are the strings not displaying?

**Comment by westnordost** [comment]
Second thing I'd try is to look at the layout of the screen in order to find if the text is just invisible, or obscured by another view, or the text is not even there etc.
In Android Studio, with your smartphone connected, you can get the Layout Hierarchy by clicking _Tools -> Layout Inspector_. The layout should then show in Android Studio in which you can navigate through like in a DOM (HTML).

**Comment by JulienPalard** [comment]
Thanks for the precise reponses!

So, I was hopping to debug this with your hints but the bug is no longer here and sentences are properly displayed now.

I'll follow your steps if I can reproduce it...
