### ISSUE TITLE
Meaning of generic class T in AImageListQuestAnswerFragment is unclear for me 

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1367]
In #1366 I managed to produce working (at least in my test) code, but I admit that it was bordering on cargo cult programming 

> AImageListQuestAnswerFragment<AddRailwayCrossingBarrierForm.BarrierOption,RailwayCrossingBarrierAnswer>()

part is basically copied from car wash quest without real understanding

-----

> AImageListQuestAnswerFragment<I,T> : AbstractQuestFormAnswerFragment<T>()

in `StreetComplete/app/src/main/java/de/westnordost/streetcomplete/quests/AImageListQuestAnswerFragment.kt` is using standard generic names

I think that I understand `I` (selected value), but `T` is quite mysterious. So I check how `AbstractQuestFormAnswerFragment` is defined:

> abstract class AbstractQuestFormAnswerFragment<T> : AbstractQuestAnswerFragment<T>() {

in `StreetComplete/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractQuestFormAnswerFragment.kt` is not even using `T` except in an inheritance chain from `AbstractQuestAnswerFragment`. So again, lets check how it is defined:

> /** Abstract base class for any dialog with which the user answers a specific quest(ion)  */
> abstract class AbstractQuestAnswerFragment<T> : AbstractBottomSheetFragment() {

in `StreetComplete/app/src/main/java/de/westnordost/streetcomplete/quests/AbstractQuestAnswerFragment.kt` gives information that it specifies quest type and is using it in definition of `applyAnswer` function and in `QuestType` that I follow to its definition:

> QuestType<T>

in `/home/mateusz/Documents/StreetComplete/app/src/main/java/de/westnordost/streetcomplete/data/QuestType.kt` is an interface of a quest types.

What leaves me confused why specifying `RailwayCrossingBarrierAnswer` worked at all - it is not a quest type, it is a tiny data class:

> data class RailwayCrossingBarrierAnswer(val barrierType: AddRailwayCrossingBarrierForm.BarrierOption)

-----

Overall, I am unsure how `T` generic is actually working in this inheritance chain and I am unhappy that I went with cargo cult copy pasting.

I am unsure what, if anything, should be improved - maybe meaning of `T` should be obvious.

**Comment by westnordost** [comment]
`T` is the type of the answer object (a simple model object) created by the quest form and consumed by the quest type. In MVC, this would be the model.
`I` is the type of each item (also a simple model object) in the image list. In MVC, this would be the view model.

In most instances, `T` and  `I` are the same. It is not the same f.e. for the `AddSportForm` because a single item is a String, but the answer given can be a list of sports (so a list of Strings). It is not the same for `AddCarwashType` because while the form should display the three choices (automated, self-service, service) the actual answer given are two booleans (is-self-service, is-automated).

**Comment by matkoniecz** [comment]
Thanks for the explanation, now I am no longer confused.
