### ISSUE TITLE
similar quest names

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1374]
I find the 3 following quests hard to identify through their title, (when I select those through parameter menu). Those are about accessibility with wheelchair:
1. "Is this location wheelchair accessible?" (quest_wheelchairAccess_location_title) , 
2. "Is this place wheelchair accessible?" ( quest_wheelchairAccess_outside_title ), and 
3. "Is %s wheelchair accessible?" ( quest_wheelchairAccess_name_title). 
It seems that the first 2 are specific ones (targeting transport and leisure park), would we change it?

**How to Reproduce**
na

**Versions affected**
na

**Comment by rugk** [comment]
Yes, this has technical reasons, because these are different quests that use different (overpass) queries, i.e. target different OSM tags/places etc. and may have slightly other differences (e.g. "wheelchairAccess_outside" is disabled by default – or the wiki is wrong, hmm…)
See https://wiki.openstreetmap.org/wiki/StreetComplete/Quests#wheelchair_access for the details/differences.

**So what do you propose?**

Should these be merged for displaying them to the user? (If so, we could group them per "modified tag" e.g.)

PS: You forget the toilets accessible quest. It's also a separate one…

**Comment by westnordost** [comment]
I think it is not really important that they can clearly be told apart. Someone who is interested in or not interested in wheelchair quests will usually activate/deactivate all of them.
