### ISSUE TITLE
Bug: Quests missing after screen was off

### ISSUE THREAD

**Issue by Echolon** [westnordost/StreetComplete#1378]
Hi,

I would like to ask if other had the same experience that the shown quests were not shown after the screen was off for only a short time?

I used LinageOS 7.1.4 on a Samsung S3

So, I expect the recent quests to be shown while walking out side, after switching on my screen again. I had to reload to see them again.

**Comment by westnordost** [comment]
What do you mean with "reload"?

Samsung S3 is an older device. Know that there is a known performance issue that if there are too many (already downloaded) quests to be shown on the map, it may take long for them to (re-)appear. You can mitigate this and/or test if this is really the root of the problem by disabling most/many quest types in the settings so that only a few quests are shown on the map.

**Comment by Echolon** [comment]
Ok thx, yes, probably.

I meant scan for quests

**Comment by westnordost** [comment]
Scan for quests justs attempts to download even more quests, so it would worsen the problem.
But I'd appreciate if you checked if what I suggested what could be the problem is really the problem.

**Comment by matkoniecz** [comment]
> You can mitigate this and/or test if this is really the root of the problem by disabling most/many quest types in the settings so that only a few quests are shown on the map.

This helps with this effect on my phone. I guess that obvious performance improvement (passing only quests within range for rendering) is already done or not  possible to do in a reasonable way?

**Comment by westnordost** [comment]
Yes. The performance problem stems from the fact that the layer in which the quests are displayed is actually unmodifiable. It can only be replaced completely, not more quests added as you scroll or zoom the map. So, whenever  quests from a different cell should be added to the view (or one is removed because it is solved), what actually happens internally is that the complete quest layer is removed and added again.

The solution might be to put the quests in a MBTiles sqlite database instead and somehow trigger a reload of it whenever something changes.

Am 18. April 2019 09:55:10 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>> You can mitigate this and/or test if this is really the root of the
>problem by disabling most/many quest types in the settings so that only
>a few quests are shown on the map.
>
>This helps with this effect on my phone. I guess that obvious
>performance improvement (passing only quests within range for
>rendering) is already done or not  possible to do in a reasonable way?

**Comment by Echolon** [comment]
Confirmed!

Over & out.
