### ISSUE TITLE
Opt-out: Stop app asking for location

### ISSUE THREAD

**Issue by Echolon** [westnordost/StreetComplete#1382]
Hi,

Right now the app asks me everytime when I start SC about GPS and location enabling. However, my GPS is broken (LineageOS) and thus I navigate myself all the time, which is fine for me.
But all those questions "Are you sure?" "Please enable GPS" are stopping my work flow...

Would be great to be able to opt out!

**Comment by ENT8R** [comment]
Those questions are there to assure that the user really visited the place. Disabling it for all users would be a little bit misleading, as it would maybe be a small decrease in the data quality contributed by StreetComplete. But actually, the question should only be asked 3 or 4 times after opening the app and if you are always tapping on no, the dialog should no longer appear after the first 3 or 4 questions.

**Comment by Echolon** [comment]
Yeah, but this is why I ask for opt-out. Of course this should be the default questions

**Comment by ENT8R** [comment]
I think adding a setting only for a few users whose GPS doesn't work properly is a little bit overpowered. Can't you simply remove the location permission in your phone's settings for StreetComplete, or are the dialogs still displayed then?

**Comment by lnxsr** [comment]
I'm also using StreetComplete with LineagueOS w/o GPS. I removed permission in phone settings and remembered decision on next start. Now I still need to abort on startup, but only this once.

**Comment by westnordost** [comment]
Once per startup you mean?

**Comment by lnxsr** [comment]
Correct. Before it always bothered so I stopped using the app.

**Comment by westnordost** [comment]
Okay, can reproduce. 

I will change it so that the "your location is needed to scan for quests in your vicinity" is only shown once after a user clicked once to disallow location access and then never again.

However, on solving quests, there will still be the confirmation message that is shown if the GPS is off.

**Comment by Echolon** [comment]
Hello,

but doesn't it make that worse for people like me?
Now the app is reminding me everytime I solve a quest that there is no GPS active. Please no!

**Comment by westnordost** [comment]
Worse? This is already the case.

**Comment by Echolon** [comment]
Hmm, maybe I just don't understand, just do what you think is right

**Comment by westnordost** [comment]
There are two separate things here:
1. when starting the app or pressing the GPS button, the app asks for GPS permission, then asks for GPS to be turned on (if it is off). I am going to change that the app remembers when the user once did not give permission and does not ask again on app startup
2. when solving a quest, the app checks if the user is really in the vicinity of that quest, because quests should only ever be solved on a survey - not from satellite imagery, not from "knowledge". If no GPS position is available for any reason (GPS disabled, no permission, no GPS fix, GPS shows old location), it is still possible to solve the quest, but the app will ask the user for confirmation while telling him that quests should only be solved on a survey. After the message showed 3 times, the user can check the "don't ask again for this session" button
