### ISSUE TITLE
new quest : asking for accessibility of disable parking_space

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1392]
I would like to ask if a specific parking_space=disabled is wheelchair accessible. So query with parking_space=disabled and ask if wheelchair accessible (wheelchair=yes/no/limited). It is not always the case so would be good to know precisely if those parking space are really accessible. 
I don't have statistics that would say it is not a spam... Feedbacks welcome ..
cc @smortex

>>PROPOSAL QUEST (UPDATE)

### General
Affected tag(s) to be modified/added: [wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair)
Question asked: **Is this parking space accessible to wheelchair?**
Answers :
* yes : parking place is fully accessible
* no : parking place is not accessible at all
* limited : parking place is partially accessible, one might need assistance to reach the sidewalk (there is a step less than 7cm or incline of the way is too steep)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** parking_space=disabled and !wheelchair

**Proposed GUI:** 
Yes/No/Partially selection answer option. 
Add information on the window when the user click on the "Can't say" button...?

**Comment by ENT8R** [comment]
Why didn't you fill out the quest suggestion issue template?

**Comment by ViolaineDo** [comment]
@ENT8R Sorry I wasn't sure if that ws needed at this stage...

**Comment by ENT8R** [comment]
> 🕓 Applies to a reasonable number of elements (Worth the effort)

According to [Taginfo](https://taginfo.openstreetmap.org/tags/parking_space=disabled#combinations) there are about 10.000 elements tagged with `parking_space=disabled`. 3500 of them already have a `wheelchai=*` value, so this quest would only apply to about 6500 elements, which is a pretty small amount...

**Comment by rugk** [comment]
So a better quest may be to ask for `parking_space=disabled` first (add it to parking spaces), but AFAIK this has been rejected in https://github.com/westnordost/StreetComplete/issues/1106.
Oh wait… that issue lists another tag: `capacity:disabled`.

So actually `parking_space=disabled` only is about dedicated (and separately mapped) parking spaces, as it seems. :thinking: 
Would it make sense for `capacity:disabled` >= 1, too?

**Comment by ViolaineDo** [comment]
> So actually `parking_space=disabled` only is about dedicated (and separately mapped) parking spaces, as it seems. thinking
> Would it make sense for `capacity:disabled` >= 1, too?

From my point of view, it makes sense to qualify accessibility of a whole parking where there is parking spaces for disabled, yes ;) But then the issue would be the information we give to qualify accessibility. It is not the same for a parking_space or a parking (that could be inside of a building, and then mean there is lifts etc;) So finally I think it is not ok to input data with capacity:disabled into this quest..

**Comment by westnordost** [comment]
Do you have some examples (photos) of any parking spaces reserved for disabled that are not wheelchair accessible? That sounds a bit like a contradiction.

**Comment by DeusFigendi** [comment]
> Do you have some examples (photos) of any parking spaces reserved for disabled that are not wheelchair accessible? That sounds a bit like a contradiction.

The sign for this parking space shows a wheelchair but they ain't dedicated for wheelies only but also for other handicaps, for example bad-footed folks which still walk or blind people.
So probably such parking space **could** exist.

**Comment by westnordost** [comment]
I am not convinced.

Any parking can be accessed on wheels, otherwise cars wouldn't be able to access it. 

And cases where the whole parking is surrounded by a kerb, it wouldn't matter much, because the person in a wheelchair will need help in any case - already when exiting the car. Even in a public transport bus, someone needs to at least open the ramp. Thus, the information whether there is a lowered kerb at or near the disabled parking space is pretty irrelevant.

**Comment by ViolaineDo** [comment]
Sorry I couldn't take a picture yet, so my point is that in some case people who build the disabled parking space are doing it badly, for example the width is not enough or the ground can not be accessed on wheels. It's not logical because when you build a disabled parking space, you would think one would consider it, but it is not always the case. It is usually errors where people are not competent or nature got the upper end. In some cases there is a tree nearby which roots stopped accessibility. In that case at the beginning the parking space was accessible but now it is not anymore.. Hope I am clear enough... thks for your support

**Comment by alesarrett** [comment]
> I am not convinced.
> 
> Any parking can be accessed on wheels, otherwise cars wouldn't be able to access it.
> 
> And cases where the whole parking is surrounded by a kerb, it wouldn't matter much, because the person in a wheelchair will need help in any case - already when exiting the car. Even in a public transport bus, someone needs to at least open the ramp. Thus, the information whether there is a lowered kerb at or near the disabled parking space is pretty irrelevant.

I think you are wrong in this.
Some healthy people in a wheelchair can guide a car, and are able to autonomously exit the car and use his/her wheelchair, but if they don't have around a lowered kerb, they are in trouble in accessing the places they would like to reach. And, also in cases when there are other people accompanying a person in a wheelchair, they need a lowered kerb to take them somewhere else...
So the quest makes a lot of sense, and I'm in contact with a guy using a wheelchair who is exactly willing to use StreetComplete to add accessibility information also to parking_spaces for disabled persons.  
Here two examples, one for accessible, the other for non accessible parking_space=disabled:

- accessible parking space: https://www.google.it/maps/@45.4286888,11.791639,3a,75y,81.05h,76.2t/data=!3m6!1e1!3m4!1sp18e4kV5Sfor7mPAlKdnRA!2e0!7i16384!8i8192?coh=205409&entry=ttu
- not accessible parking space: https://www.google.it/maps/@44.1465305,4.8082675,3a,66.4y,259.6h,68.17t/data=!3m6!1e1!3m4!1shSzjs6i_w6v-DhLj4_2ZMw!2e0!7i13312!8i6656?coh=205409&entry=ttu

The attention to parking spaces for disabled people is increasing, and now there are almost 200.000 elements tagged with parking_space=disabled (https://taginfo.openstreetmap.org/tags/parking_space=disabled#combinations).
I think this quest would be worth to be considered in StreetComplete. Please let me know if more information supporting this is needed or how can I help in better explain it.
Thanks

**Comment by mnalis** [comment]
>  So the quest makes a lot of sense, and I'm in contact with a guy using a wheelchair who is exactly willing to use StreetComplete to add accessibility information also to parking_spaces for disabled persons.

That is great! My suggestion for him at the moment would be to either:
- leave a note with comment and picture (by long-pressing on the map location and choosing `Create new note`
  (so then they or you or anybody else can add appropriate tags later to the map when they get home).
  Another advantage of Notes is that they  can be used not only to improve the OSM map, but also  to complain to municipality (or parking owner or whoever) to actually fix the problem and make the place wheelchair accessible!
 
- alternatively, if they are power user and know OSM tags by name, they can use [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork), enable _"expert mode"_ in settings, and then on parking quest choose `Other Answers`, and select `Show/edit tags` to add `wheelchair=limited` (or `wheelchair=no`) as well as other important tags (like [`wheelchair:description`](https://wiki.openstreetmap.org/wiki/Key%3Awheelchair%3Adescription) etc.) directly (without the need to later postprocess them)

> > are able to autonomously exit the car and use his/her wheelchair, but if they don't have around a lowered kerb, they are in trouble in accessing the places they would like to reach

Well, sure, but there are two problems with such idea:
- such quest seem ill-fitted for StreetComplete ***Quest*** (they would fit StreetComplete _Overlay_ better if there was one, or [MapComplete OnWheels theme](https://mapcomplete.org/onwheels.html) ). 

  That is because it seems to fail _"💤 No spam"_ [StreetComplete quest guideline](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md). 
  In particular, of some [196700 `parking_space=disabled`](https://taginfo.openstreetmap.org/tags/parking_space=disabled#overview), only [196](https://overpass-turbo.eu/s/1JOZ) _worldwide_ are currently marked with `wheelchair` tag different than `yes` or `designated` (e.g. `no` / `limited` / etc.). That is **less than `0.1%`** of the answers that would have such and unusual value -- which is why those are much better left to OSM Notes, then to wasting mapper time by asking them to answer a question over and over again which will have _the same answer_ more than `99.9%` of the time (most likely result of such spamming would be the user disabling such quests altogether, or even giving up on using StreetComplete or even OSM completely after seeing it as pointless).

- more generally, disabled people would probably be better served by accurately mapping the more details on the map (e.g. adding missing ways which are wheelchair friendly, etc) by e.g. [Vespucci](https://wiki.openstreetmap.org/wiki/Vespucci) mobile editor, then just by e.g. adding `wheelchair=limited` to that parking lot. 
  Because, just knowing that you _can_ (somehow) reach some parking space on wheels is much less useful then if you know _exactly_ how/where (e.g. imagine if on  big parking space there is only one way a person in wheelchair can enter/exit the parking - they could spend much time searching for it while avoiding cars, and still be unsuccessful! But if that way was explicitly marked, it would help enormously)
