### ISSUE TITLE
sharing quest settings between contributors

### ISSUE THREAD

**Issue by ViolaineDo** [westnordost/StreetComplete#1393]
**Use case**
I would like to organize mapping parties with street complete and easily share my quests settings, so that everyone can contribute to the same quests. For example I would like to organize mapping parties on wheelchair accessibility, so I won't need quests on other topic. I want that participants get the settings in a fast, easy way and with low risk of mistakes (like forgetting to tick the 15th quest on the list, when doing it manually)

**Proposed Solution**
We could add a list of presets (or categories) in the quest settings, that user can choose depending on his topic such as "wheelchair accessibility", or "bicycle mapping" or... , or/and add a qrcode system.
The qr code system would allow to get parameters from the host of the mapping party, through scanning his or her qr code. This system would be conveniant as we might not focus exclusively on wheelchair mapping but might want to add for example opening hours of amenities...

Hope that makes sense..
Here is an example of how qr code works on an other app

![Screenshot_1496350807](https://user-images.githubusercontent.com/12017078/57493830-50d4de00-7262-11e9-9534-b39b40533dd5.png)

**Comment by matkoniecz** [comment]
If this QR code actually contains admin and server passwords that are active I would advise you to change them.

**Comment by rugk** [comment]
…and possibly create an issue in whatever app that is and ask them to make sharing passwords an **opt-in** instead of an **opt-out**. :thinking:

**Comment by ViolaineDo** [comment]
> If this QR code actually contains admin and server passwords that are active I would advise you to change them.

Just took an online example ;) Still : good point ;)

**Comment by westnordost** [comment]
I also see point. 

A QR code is technically doable, however, it would require a new permission to be conveniently usable - the camera. Since organizing mapping parties for certain specific quest types are a bit of a special case, I would rather advise you to implement something like this in a fork.
Also, I believe something like this _for mapping parties_ would be rather counter-productive: If you have several people walking down the same street, you wouldn't want that they all answer the same quest type(s) because it will happen often that someone answers a quest that was already answered just a few moments or minutes ago by someone else. It would be better if the people each are answering different quest types, so they can walk together through the area.

The idea to group the quests according to interest areas is good, because the quest selection list is getting a bit long. But maybe create a separate ticket for that, so that we only have one ticket per topic.

**Comment by ViolaineDo** [comment]
Hi, thanks for the remark, a good point to keep in mind.
Though from my experience, during mapping parties, global mapping area is divided into small mapping area for that each small groups (2-3 persons) will survey. So people won't have this issue to fill in the same quests. On top of that at the start of the mapping party, I plan to advise each person of the small group to focus on a certain type of quests, in order to lower the issue you mentioned.

**Comment by westnordost** [comment]
So in this case, the mapping area is split up alongside streets? Sure, that's doable, but I think it is a bit sad to have a mapping party but then continue to walk the roads alone.
If you have small groups (2-3 persons), you will already have the problem I mentioned. (Of course, one could walk on the left side of the road, the other on the right, but that would be sad again... ;-) )

So I will rather not implement the QR code thingy, but I can give you some pointers how to do it yourself, if you like. You can then hand out your custom APK at the mapping party. Though, this will probably only be marginally less (or more) work for the participants than following the instruction to press "deselect all" in the quest selection screen and then checking every quest with the wheelchair icon while scrolling through the list.
