### ISSUE TITLE
Duplicate with building numbers

### ISSUE THREAD

**Issue by bristow** [westnordost/StreetComplete#1394]
First of all, a big thanks for your App, it' simple and funny, a lot of people loves it !

I think there is a problem with building numbers.

In Lyon, a big city in France, all numbers are in a node attached to a building. StreetComplete doesn't spot it and users of app make duplicate like that :  

![](https://pix.toile-libre.org/upload/img/1557606408.png)

This is a pity because we have to enter the number to be able to add the levels of the building :(

Thanks for all !

**Comment by ENT8R** [comment]
This is because the housenumber nodes in [this area](https://www.openstreetmap.org/#map=19/45.76956/4.85797) are not located directly on the outline of the house, so StreetComplete can't detect them. If they would be connected to the outline, or inside of the building the question would not be shown...
If you zoom in, you can see, that the node of the address is outside of the outline:
<img src="https://user-images.githubusercontent.com/25306497/57580413-8fa8a500-74a9-11e9-8d31-ad513c87064f.png" width="600px">

So... This is probably a tagging issue of the local community. But maybe StreetComplete could also exclude a quest if there is already an address node in a specific radius around the house?

**Comment by bristow** [comment]
@ENT8R you are right !!

The big import of these points is not clean, grrr.

**Comment by westnordost** [comment]
So this will be fixed if the housenumber/entrance nodes are actually mapped ad vertices on the buildings. It is a data issue. @ENT8R I'd rather keep the amount of fuzzy validation to a minimum so I'll close this.
