### ISSUE TITLE
Add interface to maproulette

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#14]
It would be interesting to be able to point StreetComplete at a maproulette challenge, and have that become a quest.  That's probably too hard, but even if there needed to be per-challenge code, being able to hook into the query would be interesting.

**Comment by westnordost** [comment]
StreetComplete is (also) inspired by MapRoulette. However, this app should enable user's who do not know anything about OSM data structures to contribute. From my experiences, MapRoulette challenges are usually more complex to solve, need a proper editor to solve, can be solved from satellite imagery and often need to "fix" something. This is definitely not possible with this app, StreetComplete is not a full-blown editor. For each quest type, I need to craft a form where the user can input his findings.

If, on the other hand, a MapRoulette challenge is indeed so easy that it could be answered by answering a simple question (let's say "find out if street is lit"), then, this challenge can just as well be a StreetComplete Quest because I need to implement the form anyway.
If you made this suggestion because in MapRoulette, users can themselves add new challenges: Yes, I have thought about this as well.
1. As said, this is not entirely possible, because each quest needs a form. However, I took care to design it in a way that it is very easy to add new quest types (in Java code), especially of course if this new quest type can reuse an existing form (i.e. a "yes"-"no"-"can't say" form). [This is the code for the opening hours quest type](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.java)
2. Notes that contain question (marks) are shown to StreetComplete users. So as an OSM user, you can phrase single notes like a question (i.e. "Is this really a one-way street? This seems to be an error.") and users will be shown this note as a quest. Later, I plan to add the possibility to add photos to a note so that you can also ask for a photo to be made at a certain spot.

**Comment by westnordost** [comment]
> being able to hook into the query would be interesting.
Well, this app doesn't need to hook into a query. It makes it's own ones to Overpass, with a simplified tag-oriented syntax. See the link in the last comment.

So as a conclusion, I do not see any part of MapRoulette that could be integrated into StreetComplete. Feel free to reopen this issue if you feel there is still a point I missed.

**Comment by gdt** [comment]
What I meant is mostly that MapRoulette is a rich source of queries that retrieve some interesting needs-attention subset of map data.   But I also don't see any easy way to link them, other than people who can write java noticing particular challenges or being inspired by them.
