### ISSUE TITLE
Adding clothes tag to `shop=clothes`

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1419]
### General
Affected tag(s) to be modified/added: [clothes](https://wiki.openstreetmap.org/wiki/Key:clothes)
Question asked: **What kind of clothes can be bought here?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

It may be necessary to improve tagging scheme itself during implementation (how one should tag shop selling solely female underwear? How one should tag shop selling both male and female underwear?)

**Element selection:** http://overpass-turbo.eu/s/JMp

**Metadata needed:** not needed

**Proposed GUI:**

**Comment by westnordost** [comment]
I don't think this is eligible for StreetComplete because
1. it is not clear what to check for a "normal" clothing store that may sell all or most of the choices shown - children, women, men, lingerie, denim etc etc. There is no way to mark a shop as a normal store and I highly doubt the usefulness to check every box for such stores. So, what is missing is to mark a clothes store as one that is not specialized (_🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)_)
2. For places where it is not immediately clear from the outside (e.g. lingerie), you'd need to go inside
3. Denim stores, Lingerie stores, baby clothes stores, costume stores, suits stores, sports stores etc etc are actually **different primary features**. They are also called differently. Nobody would refer to a costume store as a "clothing store" or would expect to be led to a costume store if he searched for it via his map app. This means that 
  a. it is relatively unlikely that a clothes store that is not already tagged with a `clothes=*` is anything else than a "normal" clothes store.
  b. To better support the `clothes=*` key the better place would be to add it as primary feature presets, so that for example if you search for a costume store in iD, you get `shop=costume + clothes=costume` right away.
