### ISSUE TITLE
Provide a view that simply lists quests sorted by distance from current position

### ISSUE THREAD

**Issue by C0RD** [westnordost/StreetComplete#142]
I like the way c:geo (A free geocaching app) displays the content. There is a view with Caches (think Quests) on the map: 
![image](https://cloud.githubusercontent.com/assets/3757667/25399626/3e9522fc-29f0-11e7-8f58-e33930e8b6d3.png) (thats what we have right now)
and there is a view with Caches just sorted by distance as a list: 
![image](https://cloud.githubusercontent.com/assets/3757667/25399662/5fd8239c-29f0-11e7-86eb-5a1e27a6ee31.png)

(Images stole^Wborrowed from http://www.cgeo.org/)

**Comment by westnordost** [comment]
Why would you prefer a list over a map? (Earnest question, please describe your use case)

**Comment by C0RD** [comment]
In fact i would like to have both. I think the screenshots above say a lot, why.

In the map you see the POIs with icons that represent some kind of quest. In the list-view you can list the nearest quests with more information about them. for example the content of a note, the question of a quest, including the distance and direction of it.

**Comment by westnordost** [comment]
Okay, the reason why I ask is because the process of how I implement features is first, I understand the user story behind any concrete request - in what way and in what context is the user using the app that this idea makes sense for him. Only after I understand this, I think about how I can facilitate this. 

I may end up at the same feature design than proposed, but I do not implement features simply because other apps do have this feature.

Specifically, I have some own ideas about how to facilitate a certain use case that _might be_ what you are looking for. But I do not know yet, that is why I asked you.

**Comment by C0RD** [comment]
I took c:geo just as an example, because it is easier to explain by an example. A list view may also be helpful to find and select quests that overlap, or don't show up in the map, It may also help to decide where to go next.

**Comment by matkoniecz** [comment]
For me it would be useful as there is currently no way to see all nearby quests.

Currently only small part is displayed, as there is massive amount of things to fix. But now app is very aggressive in blocking nearby markers - maybe it would preferable to display hidden quests as small dots or something similar? List filled with "unnamed street" would no be very useful.

**Comment by westnordost** [comment]
Hmm I see. I will tell you what I had in mind. If there are currently no markers displayed on the view, there are one or several arrows displayed at the screen border, pointing each into the direction of the closest quests (with distance) from the current location. Though, it is kinda blocked by https://github.com/tangrams/tangram-es/issues/1371 for the time being.

**Comment by gappleto97** [comment]
I think I would still prefer having a list view. It would also help with the other issue about POIs only showing up at specific zoom levels.

**Comment by Aypac** [comment]
I love @matkoniecz idea to show a small dot for "hidden" quests.

**Comment by westnordost** [comment]
I decided after all that this will not be implemented. Reason: There are not few quests where it is quite necessary to see where exactly they are located in relation to other things on the map. For example, the oneway quest, any quest that is shown for ways (surfaces, sidewalks, cycleways,... etc etc) but also for example for nodes such as park benches. Often, one needs the additional context, like at which housenumer it is located, to be able to correctly answer the quest.

**Comment by georg-d** [comment]
I repeatedly run into the same issue, mostly because some quest can't be properly answered at the moment but maybe later (e.g. a parking lorry blocks the view, or at daytime I cannot reliably answer whether something is lit, or at night time some un-lit thing is not sufficiently good to perceive). One example at 47.9853848, 7.8308004, max zoom level

![quest shown as dot, but other quests shown as pins can't be answered at the moment](https://user-images.githubusercontent.com/45993293/123521270-ec7d6e80-d6b5-11eb-92b9-daac9d9b126e.png)

**The "solutions" suggested so far (here and in related issues) are IMHO not really viable**
* **Disabling all quest types that are shown as pins and "shrink" a quest to a dot,** then aswering that quest, then enabling all the disabled quest types again. Not satisfying from a UX point of view as it's a quite cumbersome procedure - hence, many users will prefer to simply not answer the "dot quest". Moreover, it greatly increases likeliness that some quest types stay disabled _in the long term_ just by coincidence - this is against the purpose of the app.
* **Rotating the map** means I need to open & change Android settings, try & error with some rotations whether the dot hopefully turns to a pin at some point in time, and finally change the Android settings back. From UX perspective not satisfying for "just" answering a quest.
* **For each quest shown as pin, hiding it** means they don't show up any more for me, i.e. if I could answer them later, I won't  - this is against the purpose of the app.
* **Add more zoom levels** so all quests show as pins and none as dots --> not possible due to tangram / map rendering engine, see https://github.com/streetcomplete/StreetComplete/issues/2878


**Potential solutions that are IMHO more user friendly and hopefully technically feasible:**
* **Using tangram's multiple tap picking to make not only pins but also dots accessible,** i.e. first tap opens "highest" pin and further taps cycle through "lower" dots, suggested in https://github.com/streetcomplete/StreetComplete/issues/2878
* **A long tap on a pin opens a dialog allowing to send that quest to lowest level/priority,** i.e. it turns from pin to dot and a nearby dot has sufficient room to become a pin. 
* While adding a "general purpose" list view is _won't fix_ because answering quests shall only happen when seeing the quest's context on a map (see  https://github.com/streetcomplete/StreetComplete/issues/142), what about a list view that is tailored to solve this issue and other _"too few details visible despite max zoom"_ issues? i.e. **only at max zoom, a long tap opens a list view of only the quests within current map range.** Because user can only open list view from the map _and_ the list only contains what the map showed, the user obvisouly saw the quests with their context. Because of max zoom, the quests are obviously extremely nearby so we can assume they are hiding/overlapping and/or the map display is not helping much (example below), thus the user needs an alternative to the map view and opens the list view. As examples when map display is not helping much, take the very short way fragments in complex crossings where the thick rendering and/or the very limited layer information/filtering makes it really hard to recognize what way fragment the quest is about: ![way framents - connections not recognizable 2 variations](https://user-images.githubusercontent.com/45993293/123521293-146cd200-d6b6-11eb-9307-f0d294842e1e.jpg)
* **Allow to hide a quest only for a short period of time,** e.g. 5 minutes. So besides existing 2 Buttons "Nein, verstecken" and "OK" we'd have a 3rd button "Für 5 min verstecken". ![hiding a quest with new option or button](https://user-images.githubusercontent.com/45993293/123521265-e4253380-d6b5-11eb-8a1f-6f5ff478d943.png)
