### ISSUE TITLE
Bicycle Lanes in Indonesia

### ISSUE THREAD

**Issue by reinhart1010** [westnordost/StreetComplete#1421]
The government of DKI Jakarta (Indonesia) has built dedicated bicycle lanes at some secondary roads of Jakarta.

![20190605_114453](https://user-images.githubusercontent.com/17312341/59174114-4025c980-8b7a-11e9-8e86-88ab17149e39.jpg)

Exact location: Jalan Pangeran Diponegoro, Central Jakarta. https://www.openstreetmap.org/?mlat=-6.20087&mlon=106.84282#map=18/-6.20087/106.84282

In earlier versions of StreetComplete bicycle lane quest was disabled for Indonesia.

**Versions affected**
StreetComplete 12.1, Android 8.0.

**Comment by matkoniecz** [comment]
Note that enabling it would result in asking about bicycle infrastructure for most of roads across Indonesia. 

> some secondary roads of Jakarta

may to early to justify enabling it.

**Comment by westnordost** [comment]
Hi Reinhart, actually, it looks like these bicycle lanes are not dedicated bicycle lanes but advisory cycle lanes. They are too narrow for dedicated bicycle lanes and also do not have a continuous line, allowing other traffic to cross into or halt/park on the lane. The tagging for this is [`cycleway=lane + cycleway:lane=advisory`](https://wiki.openstreetmap.org/wiki/Key:cycleway:lane).

But anyway, that is beside the point. I took some random samples via google streetview and while in some places in Jakarta, there are these advisory cycle lanes, it seems to be rather an exception. So I'd rather not add Indonesia to the whitelist. Even or especially if this may be changing these days and there will be more cycleways every day, it would actually not be a good idea to let surveyors record this information because then it may be outdated pretty quickly.
