### ISSUE TITLE
House number: indicate the street.

### ISSUE THREAD

**Issue by Mbodin** [westnordost/StreetComplete#1430]
This may be a duplicate of one of the comments indicated in #213, but it seems to me different enough to report a new issue.

**Use case**
In the “House number” quest, the question is simply about the number of the building in the street. This quest however doesn’t indicate in which street one should check this number.
The issue is that sometimes, OpenStreetMap users just place a single polygon for an entire block (it may make sense when the different buildings are a lot intricated). Such a block is thus associated to several addresses in different streets. The issue is that when using StreetComplete, it is not clear in which street I should read its number… but the number I type will be associated with the street currently recorded for the building. It makes me feel a little confused when there is an ambiguity.

Here is an illustration:
```text
==== Street A ====
| _____________
S |            |
t |            |
r |            |
e |            |
e |    block   |
t |            |
  |            |
B |            |
| |____________|
|
```
If in this situation the block is reported to be in Street A, but if the StreetComplete user report its number in Street B (say 42), we could get a mismatched address like “42, Street A”, whilst its address was either “67, Street A” or “42, Street B”.

**Proposed Solution**
Instead of asking “What is the number of this building”, ask “What is the number of this building in Street A?”.

**Comment by westnordost** [comment]
Can you give the location of where this occurs so that I can have a look at the situation?

**Comment by Mbodin** [comment]
Sure: https://www.openstreetmap.org/#map=19/51.49244/-0.16718
In this case, I think that we should check the number of the building in Sloane avenue. However, there is a hotel in Lucan Place and I was in this side of the building when I saw the quest (which I did not answer).
I guess that what one really should do is to divide this building into several buildings, but this is probably too much a task for a quest.

**Comment by westnordost** [comment]
On [google maps](https://www.google.de/maps/@51.4911043,-0.1676322,187a,35y,15.88h,40.45t/data=!3m1!1e3), it really looks like this block was built as one building, some of the others around there as well. So, it is mapped correctly.
That building and buildings like these will probably have housenumbers on all surrounding roads.

The proper way to map a situation where a building has several addresses is to add the addresses to the entrances and not the building itself, example: https://www.openstreetmap.org/#map=19/53.58328/9.95059
This is nothing the surveyors can do with StreetComplete though. But as a first rough mapping, it is okay to add these multiple numbers to the building itself, this is why the following is implemented in StreetComplete:

In the _"Other answers..."_ menu, users can select _"It has multiple house numbers"_. It opens a popup that informs the user:
_"You can simply enter comma-separated house numbers or ranges. For instance 1,3 or 2-6."_

Now, this works fine when a building has several housenumbers on one street, but obviously not if it has several on multiple roads. In this case, the only way to properly record the addresses is to add addresses to the entrances. As noted, this is nothing that StreetComplete can do.

So for this case, there is no solution, it cannot be done in StreetComplete.

I'd say in this case, the surveyor would need to answer _"Can't Say"_ and leave a note. In the note, he can write down the housenumbers of the building in the text and/or make photos so that someone can supplement this information later with a proper editor.
