### ISSUE TITLE
add question for amenity=telephone like "Does this phone still exist here?"

### ISSUE THREAD

**Issue by Lukas458** [westnordost/StreetComplete#1434]
The issue:
For example in Germany, we have about 22.000 amenity=telephone(s) in the database according overpass and I believe that at least 50 percent of them have - in the reality - been removed in last years. More and more ones are getting removed and so the count of outdated data might rise. Also, nearly nobody recognizes them (even when they still exist) if they are not asked for those things because nearly nobody needs them anymore, but some phones **do** still exist (at least in Germany), and these ones may to be identified so that the other ones can get removed from the database - that's what my idea is. I just wanted to ask whether StreetComplete can help on that issue to do that, **so maybe in the form that the user gets the question "Does this phone still exist here?" when an amenity=telephone is near and he just has to answer "yes" or "no"** so not really difficult to do. But if the answer would be "no", I need an idea what to do then. I don't know whether StreetComplete will follow the purpose to delete objects from the databse... but maybe you also have ideas on that or comments so please just let me know what do you think about this topic.

**Comment by matkoniecz** [comment]
One more problem - what should be added as a tag in case where this telephone turns out to be actually existing?

> But if the answer would be "no"

StreetComplete is generally not handling deletion of items, but maybe for `amenity=telephone` mapped as nodes that are not part of ways/relations maybe it can be actually handled well? It seems to be more likely to be doable that for shops where "shop is gone" may require vastly different actions depending on the situation.

**Comment by Lukas458** [comment]
> what should be added as a tag in case where this telephone turns out to be actually existing?

okay, I see, but maybe if we don't want to delete anything we can think about using lifecycle prefixes, so making an abandoned:amenity=telephone or removed:amenity=telephone out of amenity=telephone?

**Comment by matkoniecz** [comment]
`abandoned:amenity=telephone` is incorrect for no longer existing telephone

deleting node is preferable over `removed:amenity=telephone` and may actually be doable in case of this specific POI.

And neither fits case where telephone turns out to be actually existing and working

**Comment by goldfndr** [comment]
Would `abandoned:amenity=telephone` be preferable for cases where the phone has been ripped out but the privacy booth remains?

**Comment by rugk** [comment]
BTW, next time (or right now if you want to edit your initial issue, @Lukas458, please fill out the issue template for a new quest.

**Comment by westnordost** [comment]
This falls into the category of the proposed "map maintenance" quests like...
- are these opening hours still correct?
- are these postbox collection times still correct?
- is this store still here?
- does this crossing still have no tactile paving?
- does this toilet still have no fee?
- etc etc
... that come up from time to time.

The general idea is to ask these kind of map maintenance quests in certain intervals, for example opening hours perhaps every few years, surface of unpaved road perhaps every 10 years etc.

However, the current situation is that these kind of quests are blocked (mostly) by a missing consensus and acceptance about a tag to mark that a certain tag of an element has been surveyed at date X. Something like `lastcheck:opening_hours=2019-06-21`.

To be able to mark the last survey date is necessary because in case the telephone booth is still there, other surveyors (and StreetComplete users) need to know if the existence of that telephone booth has been recently checked and doesn't need to be checked again for some time.

---

Now, having said that, this quest in particular would be blocked additionally by StreetComplete's inability to add and remove elements. This can be changed of course, but it some work. So right now, this quest is quite far off what is currently possible.

**Comment by westnordost** [comment]
Superseded by #2074
