### ISSUE TITLE
Add Mapillary SDK to capture images in app

### ISSUE THREAD

**Issue by tordans** [westnordost/StreetComplete#1461]
Mapillary recently announced a new SDK to allow image capturing from inside other apps.

- Blogpost https://blog.mapillary.com/update/2018/11/06/capture-sdk.html
- Git https://github.com/mapillary/mapillary-sdk-ios

Adding the feature to capture images of an object right out of an app would help a lot to add more visual proof for other mappers. 

Right now, whenever I go mapping I have both apps open and switch between them constantly.

I see these **use cases** where street level image capturing would benefit StreetComplete
- capture images of areas that I don't have the time to map completely
- capture images of areas that I just mapped as a proof of what I just saw
- have a quest that asks for images of places that don't have image coverage, yet. Eg "capture images of this playground so other can add the playground equipment as POIs later" (see https://github.com/westnordost/StreetComplete/issues/589)

The way I use Mapillary when walking is more as a POI photo service. So I don't take a coherent set of pictures like you would when you mount your phone/camera to a bike/car. Instead I have the app open to take 360-photo-sets or capture sets of images from POI on the go (10 pics of a junction here, 3 pics of a ad-column there, …).

---

See also https://github.com/bryceco/GoMap/issues/168 for a similar request for GoMap.

**Comment by matkoniecz** [comment]
For start:

> The Mapillary SDK for iOS lets you integrate Mapillary capture functionality into your iOS app.

This is an Android application. It's there an Android SDK?

**Comment by tordans** [comment]
From the linked blog post https://blog.mapillary.com/update/2018/11/06/capture-sdk.html

> Available platforms
>The SDK is available for both iOS and Android. They are still under development, which is why the release is a beta. We would love any feedback you might have as we keep on working on improvements. Currently, the iOS SDK is at version 0.7 and the Android SDK is a preview version.
>The iOS SDK is available on CocoaPods as well as GitHub. The Android SDK is only available as a binary for now, which you can [download from our website](http://android-releases.mapillary.io/index.html?prefix=sdk). It will be available on GitHub eventually.

--- 

Also, Simon Poole twittert about working on this https://twitter.com/vespucci_editor/status/1145621425279111168 for https://github.com/MarcusWolschon/osmeditor4android. Maybe it is also on capturing images(?).

**Comment by westnordost** [comment]
This will not be implemented in StreetComplete. Some reasons:

1. It is not that much effort to switch applications if you want to do something else
2. creating a 360° panorama or photos generally for Mapillary is something else than what StreetComplete does. It seems quite out of scope.
3. StreetComplete would need to start using the camera permission - for a feature that is not really related to the rest of the app

What may make sense at some point in the future to enable a street level imagery usage of this app, where people can use the app from home, answering the questions by browsing through Mapillary imagery. (The changeset source tag would need to be changed then, plus it should probably only work on a large screen like that of a tablet so that one has some kind of split view)

**Comment by tordans** [comment]
Thanks for the closing note @westnordost
