### ISSUE TITLE
In "Credits" in "About StreetComplete" mention also image authors

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1505]
Just mentioning them and linking to https://github.com/westnordost/StreetComplete/blob/master/AUTHORS.md would be nice.

But maybe making raw text of https://github.com/westnordost/StreetComplete/blob/master/res/authors.txt and https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/authors.txt viewable directly in app or even processing this text into something more readable within app would be a good idea?

**Comment by rugk** [comment]
Maybe just some buttons for the links to GitHub contributors etc.

So convert the plain-text into some good credit page.

**Comment by westnordost** [comment]
I don't think it is a good idea because in most cases, the authors of the resources are not actually contributors to the project. These resources are just used under a certain license. Since this is an open source project, the information about the licenses for the used resources are accessible for anyone, there is no need to show it in the app itself.

**Comment by matkoniecz** [comment]
What about just linking https://github.com/westnordost/StreetComplete/blob/master/AUTHORS.md file with something like "See [more info](https://github.com/westnordost/StreetComplete/blob/master/AUTHORS.md) about authors of assets used to make StreetComplete"?

**Comment by westnordost** [comment]
As said, the credits in the app are for people who actually contributed to StreetComplete. If at some point someone does a lot of artwork for StreetComplete, I will just put him into the list of contributors shown on that screen.
