### ISSUE TITLE
Street complete seems to show railway information in the wrong location

### ISSUE THREAD

**Issue by joostschouppe** [westnordost/StreetComplete#1527]
StreetComplete shows the main Liège railway station in a completely wrong location. Reported by a user, and visble in my Android with version 13.
For more info see https://www.openstreetmap.org/note/1891186

**Comment by westnordost** [comment]
This is how the place looks like in StreetComplete. Anything wrong with it?

https://map-data.de/#map=18/50.64333/5.5725835&style=streetcomplete-light

**Comment by joostschouppe** [comment]
Uh, this is weird.
In your link:
- it looks right in the cinnabar style
- the streetcomplete styles show "Jonfosse" from zoomlevel 19 in exactly the same place where the app shows me the wrong "Liege-Guillemins" station.
Neither Jonfosse or Liege-Guillemins have anything to do with that exact location.
What I see in the app (and is linked in the Note as well: https://imgs.be/5d5be243-1064.png) is not the same as what your link above shows me.

**Comment by ENT8R** [comment]
The problem seems to be the following:
The data which is used in the vector map has multiple sources like OpenStreetMap or [whosonfirst.org](https://whosonfirst.org/).
The label on the screenshot is from whosonfirst and the different labels in different languages are there because StreetComplete autodetects the language of the user, so a French speaking user sees the name "Gare de Liège-Guillemins", a German user is going to see the name "Bahnhof Liège-Guillemins" and if the language is unknown (or not set like in the web interface) the user sees "Jonfosse":

![liege](https://user-images.githubusercontent.com/25306497/63361895-45b94000-c371-11e9-848c-8f051b42033a.png)

The problem is that whosonfirst often supplies invalid data, see also https://github.com/ENT8R/streetcomplete-mapstyle/issues/14
Actually, @matkoniecz already opened a pull request (https://github.com/ENT8R/streetcomplete-mapstyle/pull/26) to remove whosonfirst.org as a data source, but that was in an early stage of the development of the mapstyle, so after that the style was rewritten a lot and whosonfirst.org is not banned anymore...
Maybe we should consider banning it again if the data supplid by whosonfirst is so wrong in so many cases?

**Comment by westnordost** [comment]
Right, okay!

**Comment by westnordost** [comment]
I reopened https://github.com/ENT8R/streetcomplete-mapstyle/issues/14

**Comment by matkoniecz** [comment]
Now it is fixable by updating map styles to latest commit.

**Comment by westnordost** [comment]
Thank you!
