### ISSUE TITLE
Uploading a quest and undoing it gives +2 points, instead of 0

### ISSUE THREAD

**Issue by ltog** [westnordost/StreetComplete#1537]
**How to Reproduce**
Upload a quest, then undo it. This gives the user a score of +2. But probably shouldn't increase the user's score.

**Versions affected**
StreetComplete 13.0 on Android 8.1.0 (LineageOS 15.1)

**Comment by westnordost** [comment]
Actually, it is more of an upload counter than a score counter. The answering of the quest was an upload, the undoing of it had to be uploaded again (it is a revert), so that is why there is 2 at the end. Maybe this behavior is changed later when we introduce more statistics for the user, but currently it is not really possible.
