### ISSUE TITLE
Some UI elements are not following dark mode

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1545]
At least on my phone following elements are dark text on white/gray background or small black symbol on white button

- "Scanning for new quests..." toast
- menu triggered by clicking on tree dots
- 5 buttons around the screen 
- default avatar in the note discussion

**Comment by westnordost** [comment]
> default avatar in the note discussion
> menu triggered by clicking on tree dots

Done and done.

> "Scanning for new quests..." toast

Any toast actually. The Android Toast's layout or background is not themable. This could only be solved by creating a subclass and/or Kotlin extension function that is used consistently throughout the app instead of the default Toast which sets a different layout with a custom background.
This is too much effort, in my opinion. The toast may be less visible in dark mode, but I think it is still fine, so won't fix

> 5 buttons around the screen

I think they are fine this way, won't fix. You or anyone else can experiment around with dark buttons if you like, but I won't guarantee that I merge this. IIRC @ENT8R actually already did in his initial implementation of dark mode, and it did not look that great.
