### ISSUE TITLE
Please prefetch common questions as results of quests

### ISSUE THREAD

**Issue by hmartink** [westnordost/StreetComplete#1550]
I recently worked in a bungalow park. For every building, the default question was "What kind of building is this". So I walked the bungalow park and answered for every building "bungalow" (or shed, if it was a side building and so on). When I returned to the wifi area, the results were duly uploaded and new quests appeared, namely: How many stories does the building have. So I walked the area a second time to enter the number of stories. Upon return to the wifi area, again the results were duly uploaded and a third questions, namely the roof type, appeared. So I walked the area a third time.

It would be great if common use cases could be prefetched or added to the logic of streetcomplete to avoid having to walk areas several times. Sometimes there already seems to be a logic behind, for examples after answering the street covering I often get if the street is lit, or a series of questions regarding bike lanes and pedestrian situation. So it would be great if the logic knew that (most) buildings have stories and if the roof isn't flat, that a roof type would be asked as well. This would avoid having to walk the very same area several times to answer all questions. (The alternative would be to carry some paper around and add the answers there and upon return to the wifi area add the answers from the paper).

**Comment by matkoniecz** [comment]
See discussion about this in #1510

Probably https://github.com/westnordost/StreetComplete/issues/1510#issuecomment-516743560 and https://github.com/westnordost/StreetComplete/issues/1510#issuecomment-516528413 are especially interesting.

In short: related shortcoming of StreetComplete is getting fixed by @westnordost 

Fixing this is likely to be time consuming and/or complex and/or reduce perfomance of StreetComplete - unfortunately it is not a quick fix requiring just hour or two.

**Comment by westnordost** [comment]
So, in a nutshell: Roof shape quest is only displayed once the building level quest is uploaded, building level quest is only shown when the building type quest is uploaded. There is no way around this. If you want to see the quests right away, you need to upload your answers right away, i.e. turn auto-sync on. Minus notes with attached pictures, this is really very little traffic, by the way.
