### ISSUE TITLE
No housenumber task maps to wrong OSM tag.

### ISSUE THREAD

**Issue by spindr** [westnordost/StreetComplete#1553]
See https://www.openstreetmap.org/changeset/73977621#map=18/51.51407/-2.54197

**Comment by matkoniecz** [comment]
> Not sure why noaddress is required -- National Rail seem to think it has an address?

>  it should have added "nohousenumber=yes"

**Comment by westnordost** [comment]
Why exactly is this a bug?

**Comment by spindr** [comment]
From changeset comments it appears to be that the quest is "Does this building have a housenumber?" not "Does this building have an address?".

Adding "noaddress=yes" means the building doesn't have an address.

Either change the question or change the OSM tag that get's added.

**Comment by spindr** [comment]
Here's a (copyrighted) address for the station, i.e. it has an address, but no housenumber.

**Comment by spindr** [comment]
https://www.nationalrail.co.uk/stations/BPW/details.aspx

**Comment by westnordost** [comment]
Hmm, makes sense. StreetComplete should use `nohousenumber`, even though this tag is barely used yet.

Note that the tag was just invented a few months ago. `noaddress` is in use for years already.

**Comment by westnordost** [comment]
The change would mean, though, that buildings that not only have no housenumber but also have no address would also be tagged with `nohousenumber` because naturally, the surveyor has no implement to find out if a building has no address at all or "just" no house number if there is no housenumber plate.

**Comment by tyrasd** [comment]
Unfortunately, the use of `nohousenumber=yes` is often added wrongly by streetcomplete users. Example: https://www.openstreetmap.org/way/377703085 – This building almost certainly simply has no address. However, the tag `nohousenumber` should only be used for addresses which do _exist_, but omit the housenumber part:

> For addresses which do not have a house number (for example "snc" = "senza numero civico" in Italian, "s/n" = "sin número" in Spanish and "sem número" in Portuguese) you can add `nohousenumber=yes`.

(Note: I'm pretty sure this case just does not exist for addresses in Austria.)

Another related case would be where a building/address has an address, but it is just not signposted publicly.

**Comment by HolgerJeromin** [comment]
So the issue here is that there are small hospital buildings which are the hospital itself and have a house number (and therefor should be asked by SC)
or we have a big hospital complex where not every small building has its own address.

Perhaps we should drop building=hospital from the housenumber quest because we can not distinguish both cases.

**Comment by mnalis** [comment]
> Example: https://www.openstreetmap.org/way/377703085 – This building almost certainly simply has no address

Why are you so sure? Other hospital buildings inside that hospital complex do seem to have addresses (with housenumbers)?

So I wonder is that specific case an user error (i.e. that building _does_ have an address with housenumber, but user answered wrongly), or StreetComplete lacking precision (i.e. that building does not have any address at all in reality [contrary to other hospital buildings in the complex] but the user only could tag that it has "no housenumber" or "leave a note", and chose the former as it was closest to "it has no address")?

> (Note: I'm pretty sure this case just does not exist for addresses in Austria.)

Regarding `nohousenumber=yes` not existing in Austria (IIUC?), looking at [taginfo](https://taginfo.geofabrik.de/europe:austria/keys/nohousenumber#chronology), it seems that out of 2k values, about half of the values were two big imports (or otherwise mechanical edits) adding `nohousenumber` in Austria in last year or so?

Also, running [overpass](https://overpass-turbo.eu/s/29Mq) it looks like more of half of them are on `building=yes` or objects missing `building` tag, so those at least couldn't have been tagged by StreetComplete (IOW, if `nohousenumber` tag should not exist in Austria, the problem is significantly wider than _just_ StreetComplete mistagging them)

>  or we have a big hospital complex where not every small building has its own address.

those should be skipped already:

https://github.com/streetcomplete/StreetComplete/blob/3dc1b77ed7d35c0907559207826e528945050e48/app/src/androidMain/kotlin/de/westnordost/streetcomplete/quests/address/AddHousenumber.kt#L88

But this building seems to be inside area which does ***not*** have address tagged: [way 377703086](https://www.openstreetmap.org/way/377703086)

And that seems to be because other buildings inside that hospital complex **do** have their own separate housenumber (e.g. [45758601](https://www.openstreetmap.org/way/45758601),   [5625236](https://www.openstreetmap.org/relation/5625236), [45758602](https://www.openstreetmap.org/way/45758602) etc.)

So, if anything, I would guess that [this specific hospital building 377703085](https://www.openstreetmap.org/way/377703085) should also have an regular address with housenumber (or if it does not, that it is an exception rather than a rule).

> Perhaps we should drop building=hospital from the housenumber quest because we can not distinguish both cases.

Uh... maybe we should not? I'd really prefer if we recorded addresses for hospitals, it is really useful information.  Even if rarely it might happen that some small hospital building  gets mistagged with `nohousenumber=yes` instead of `noaddress=yes`.

---

What could be done to improve situation:

- split current Other answer `It has no house number` in ***"What's the house number of this building?"*** Quest to two:
   - `It has an address without house number` ==> tags `nohousenumber=yes` and
   - `It does not have an address at all` => tags `noaddress=yes`

and/or

- add the Other answer to  ***"What street is this on?"*** Quest:
   - `It does not have an address at all` => tags `noaddress=yes` (and removes `nohousenumber` if existing)

**Comment by rusty-snake** [comment]
Somewhat related (using school as more common example):
- You have a school that is on one "Grundstück" (piece of land; property)
- Addresses in Germany are given to a Grundstück not a building, but usually you have only one building (residential, office, fire_station, ...) on one Grundstück (ignoring outbuildings).
- The school has 3 buildings; OSM: 2x building=school

Answer A:
- Some users answer with addr:housenumber for the building=school and nohousenumber for the other two buildings.

Answer B:
- Some users answer with addr:housenumber three times.

It is at least not clear to users what to answer in such cases.

(And the amenity=school area around the buildings can have an addr too).

**Comment by westnordost** [comment]
> (And the amenity=school area around the buildings can have an addr too).

In which case the quest is not asked.

> It has an address without house number ==> tags nohousenumber=yes and
> It does not have an address at all => tags noaddress=yes

The user is asked about a house number. He is on-site and doesn't see a housenumber. How should he answer the question whether "it has no address" or "it has no house number", exactly?

**Comment by matkoniecz** [comment]
> However, the tag nohousenumber should only be used for addresses which do exist, but omit the housenumber part:

https://wiki.openstreetmap.org/wiki/Key:nohousenumber also has

> For explicitly stating that no house number is assigned to a place. Show/edit corresponding data item. 

are you sure that `nohousenumber` cannot be used for buildings which have no house number and also have no other address

(BTW, comments in old issues may be missed or forgotten - it is better to open a new issue if you are sure about the problem, then it needs to be deliberately closed for it to go away)

**Comment by matkoniecz** [comment]
I opened https://wiki.openstreetmap.org/wiki/Talk:Key:nohousenumber#Is_it_fine_to_use_it_when_address_is_altogether_not_present%3F

**Comment by matkoniecz** [comment]
Maybe `housenumber:signed=no` would be better?

**Comment by matkoniecz** [comment]
Myself, I keep leaving notes "is there address for this building in official data" rather than selecting no house number answer

https://wiki.openstreetmap.org/wiki/Talk:Key:nohousenumber#Is_it_fine_to_use_it_when_address_is_altogether_not_present%3F has

>And when checking the items entered by SC, there is a 100% error rate.

(which probably applies only in some areas, but still...)

>I therefore believe that SC should never have suggested this tag, in neither of the two situations mentioned in the GitHub ticket, and should have simply added a tag describing the absence of the sign. Another source is needed to determine whether the absence of a sign means that there is no house number.

**Comment by westnordost** [comment]
(opening because there is discussion happening)

**Comment by westnordost** [comment]
`housenumber:signed=no` sounds reasonable.

Back when this was changed, `*:signed` tag wasn't established at all. But I do recognize that the wiki already [back then](https://wiki.openstreetmap.org/w/index.php?title=Key:nohousenumber&oldid=1891400) stated:

> Do not use this tag if you are unsure about the housenumber or if there is a housenumber assigned but not signposted. 

On the other hand, given that StreetComplete started using this tag to denote that there's no housenumber in September 2019, almost 6 years ago, it is clear that most probably a lot of the usage of this tag got added by StreetComplete  

<img width="1080" height="640" alt="Image" src="https://github.com/user-attachments/assets/71132b13-ea19-4937-a88a-eb5dd63b133e" />

as the tag was basically unused before, hence, SC might have mucked this up and current usage of this tag might very well somewhat be defined by how SC uses this tag.

So, I am not sure whether it wouldn't be better to align the wiki with the de-facto usage of the tag instead, e.g. "Originally intended to exclusively denote that a house has no house number (but still an address), it's usage by StreetComplete since September 2019 effectively weakened its meaning to denote that there's simply no (visible) house number, without any further implications" or similar.

**Comment by tiptoptom** [comment]
If so, I would use `addr:housenumber:signed=no`.

I would clearly prefer `addr:housenumber:signed=no`, as it fits in with the tagging in other quests (opening hours, max weight, name, etc.).

**Comment by westnordost** [comment]
There's also `noname` for roads, though, when the user answers that a road has no road name (sign). 🤔 - should we reconsider there, too?

**Comment by matkoniecz** [comment]
Maybe add option "this road definitely has no name" and "not sure, but no name is signed"?

(sometimes you can be 100% sure in villages and small towns, and `noname=yes` will be understood also by other tools)
