### ISSUE TITLE
Explain how to unglue map from location in even more prominent way

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1554]
Maybe detect repeated attempts to pan map freely and to show very, very prominent message in such case?

This issue sounds a bit silly because for long-term users it seems obvious and there is already message...

But in testing on real users it was

> problem shared by every single person was gluing map to a current location. Every single person attempted to pan map and failed to do it. Every single person failed to notice about ungluing. Every single person considered option used to unglue as hidden and not in the expected place. All were expecting that clicking on that button will locate them, not that it will trigger ungluing. Two suggested to detect attempts to pan map freely and to show message in such case.

Even work very low sample size of my test it seems to be at least a common flustrating problem, even if in reality it is lower than 100%.

Note that I was testing on people with generally low exposure to OSM-specific software.

**Comment by HolgerJeromin** [comment]
I know @westnordost has/had strong opinion about that, but I remember no other map software which prevents panning the map like SC does. 
Osmand, google maps, vespucci... lock the view to gps position when told, but unlocks the position at direct pan touch interaction. IMHO much better UX.

**Comment by matkoniecz** [comment]
Note that StreetComplete, unlike other listed map apps is supposed to be used at your current location.

But maybe warning at answering is good enough for that?

Note also that all this apps have option (not enabled by default) with center to current location.

**Comment by flera** [comment]
This issue happens to me regularly. I often forget if I enabled this option or not.

To improve, maybe we can make the elastic map around the position of the person. When you "glue" the map, you can move the map around the position, but if you stop touching the screen, the map will refocus on the phone position.

What do you think ?

**Comment by waldyrious** [comment]
> but if you stop touching the screen, the map will refocus on the phone position.

When you mentioned "elastic", I thought you were going to suggest a wobbling effect on release! 😄

**Comment by rugk** [comment]
Hmm, I like that elastic map idea. And please do use some wobbling effect, because I imagine this to be a good UX hint: It looks as if the position is "tied up", i.e. some kind of "rubber rope" is pushing you back to the current position.
That is a very clear UX hint for "You are forced to be here. You cannot/should not do this." Or at least: "You can only temporarily do this, but I will move you back."
So some animation should be used in there. Some that looks like rubber… :thinking: 

In another view, it is also actually a feature: It could be called a "_look around mode_", i.e.  a mode, where you are "attached" to your position, but can quickly look around, e.g. for seeing the end of the street (the actual underlying issue of https://github.com/westnordost/StreetComplete/issues/1576 and https://github.com/westnordost/StreetComplete/issues/1576, if I understood that correctly, e.g. /ccing @misibacsi and @misibacsi) or just for navigating where you want to go next (because you likely don't want to switch to a different app, just for having a quick overview/look around, where to go) – ah, the last thing could be a good addition/alternative to https://github.com/westnordost/StreetComplete/issues/871 so. (though I still like the idea in https://github.com/westnordost/StreetComplete/issues/871)

So maybe this can solve more issues than we think… :wink:

**Comment by waldyrious** [comment]
> of #1576 and #1576

You copied the same number twice :)

**Comment by rugk** [comment]
Damn… (at least i was consistent)

I meant https://github.com/westnordost/StreetComplete/issues/871 as the second link. (and would had to cc myself :roll_eyes:)

**Comment by xuiqzy** [comment]
Maybe an easy and good UX solution would a big circle getting smaller and circling in on the glue position button? Assuming the glue position feature is still desirable in its current form rather than allowing to move away from it.
Like a reverse of the animation of the current location "flashing" from the current position outwards in Apple Maps on iOS for example.

**Comment by maffe** [comment]
> I know @westnordost has/had strong opinion about that, but I remember no other map software which prevents panning the map like SC does.
> Osmand, google maps, vespucci... lock the view to gps position when told, but unlocks the position at direct pan touch interaction. IMHO much better UX.

I agree, but I would like to have it switch back to GPS position automatically when I no longer use the touchscreen, my position is not visible on the screen and it’s moving. That way I could easily look for new quests and continue riding my bicycle without having to toggle the GPS position switch.

**Comment by westnordost** [comment]
I removed it now for the refactor. I will eventually replace it with a pointer pin that floats at the edge of the screen and shows the direction and distance of the vote of the map to you current location, clicking on it sends you back to your location. I think mapy.cz or so does it like that

**Comment by rugk** [comment]
Great idea! 😃

**Comment by RubenKelevra** [comment]
should be fixed with v17b2 :)
