### ISSUE TITLE
"abbreviations are expanded" is fatally ambiguous

### ISSUE THREAD

**Issue by mikehgentry** [westnordost/StreetComplete#1558]
When asked what the name of a street is, it says "What is the name of this road? as written on the street sign, abbreviations are expanded:"

Unfortunately it seems to me that that could mean abbreviations *should be* expanded by the user, or abbreviations *will be* expanded automatically by the program. I would suggest changing it to either of those.

StreetComplete 13.0

**Comment by westnordost** [comment]
@mikehgentry actually it is both. The user should expand the street name but the app will expand automatically all the abbreviations it knows to help the user. If the user enters an abbreviation (name ends with a dot) that is not expanded automatically , the user will be warned about it before he can apply his answer.
Telling the user all that I just wrote would make the text too long. Yes, it is ambiguous but not in a way that should negatively affect the quality of the data entered by the user. If he interprets the sentence as  "I must expand it", the user simply only misses out on the convenience feauture. If he interprets it otherwise, he will for names the app cannot expand automatically see that the expanding does not work so he had to fill in the complete name by himself.

**Comment by rugk** [comment]
But what is the advantage of writing that sentence at all, then? Why not just remove it?
The app does it's task automatically.

**Comment by mikehgentry** [comment]
Thanks for the detailed answer. That still seems unnecessarily confusing to me, absent the explanation. How about just saying "abbreviations are available - see help", then having a menu option somewhere with a list of understood abbreviations? Or even just having something like a hyperlink "recognised abbreviations" which pops up a list?

**Comment by westnordost** [comment]
That is too much information for the user.

**Comment by westnordost** [comment]
I thought about it and I rather leave it as it is. A text change to "please expand abbreviations" would need to be translated into the 20+ languages and as said, there are no consequences for a possible misunderstanding other than that the user misses out on a convenience feature.
