### ISSUE TITLE
Private audio notes / photos attached to quest

### ISSUE THREAD

**Issue by mikehgentry** [westnordost/StreetComplete#1559]
**Use case**

I may be walking along and passing multiple quests, but unwilling or unable to stop and type in the required information at that moment. If I could more easily store notes to myself in the form of photos or audio clips, I could replay them later and complete the quests at my convenience.

**Proposed Solution**

In the quest's dialogue box, add two buttons. One records audio when held, and the other opens the camera and allows you to take a photo.

Later, once I've got home or somewhere convenient, I can press a button to replay all my quest notes. Each quest to which I have attached a note opens, the note is played / displayed, and I type in the answer. When I submit, the audio clip / photo is automatically deleted.

Perhaps audio clips / photos should be automatically deleted after some period too (a week or a month or something) if the quest is never completed, to avoid consuming too much space.

StreetComplete 13.0

**Comment by matkoniecz** [comment]
Note that you can create public text note with attached (public) photo.

**Comment by matkoniecz** [comment]
Also, for what kind of situation making notes and solving it later is better than solving it now?

In my experience for nearly all quests most of the time is to get info, not to answer questions.

Opening Hours have a long input time but in this case public note should work.

**Comment by mikehgentry** [comment]
I'm aware of the public notes, and they probably are sufficient for situations like opening times. I think the suggestion would simplify the workflow, even if they were still public notes (and they often don't need to be).

I was also thinking of situations where there are lots of simple quests near to one another - it's easier to hold a button and speak numbers than it is to type them for example, so if you're walking past many buildings without numbers, you could record them quickly.

You could possibly even have a mode where the nearest quest opens automatically (and asks the question text to speech perhaps?) You could reel through them much more quickly than opening them individually and typing.

**Comment by westnordost** [comment]
To be honest, I don't see a valid use case for this feature. 

I acknowledge that answering the quests in StreetComplete is not the fastest possible way to contribute to OpenStreetMap on a survey. If all information (of a type, i.e. surfaces, building levels, housenumbers) are missing, it is more efficient to walk down the street and [do a traditional survey, i.e. an audio or photo survey, or make notes on a printed map](https://wiki.openstreetmap.org/wiki/Mapping_techniques#Getting_the_details).
There is also at least one app that is facilitates this this, you should have a look at [OSMTracker](https://play.google.com/store/apps/details?id=net.osmtracker).

Anyway, if you want to do a focussed and faster survey, try out the mentioned techniques and the app. StreetComplete is not made for this kind of survey. Adding features to StreetComplete that facilitate this kind of survey will not be effective, because:
- > In my experience for nearly all quests most of the time is to get info, not to answer questions.
- Before you could record an audio message, you'd have to open the quest first, tapping it, then pushing the record audio button, possibly acknowledging a confirmation dialog and then exiting the quest dialog again - for each quest! And then, of course, later reopening the right quest and listening to (and making sense to) the previously recorded message. That sounds like a huge overhead.
- Same with photos, additionally it takes additional time to jump to the camera application and initialize the camera for each picture taken. 

So, I am closing this. Feel free to try out the app to which I provided the link or have a look at the other mapping techniques available.

**Comment by mikehgentry** [comment]
> Before you could record an audio message, you'd have to open the quest first, tapping it, then pushing the record audio button, possibly acknowledging a confirmation dialog and then exiting the quest dialog again - for each quest! And then, of course, later reopening the right quest and listening to (and making sense to) the previously recorded message. That sounds like a huge overhead.

The suggestion was to have a mode that eliminates a lot of that overhead though - for example by having a button that goes through all quests to which you have added a note, allowing you to type it in and automatically removing the note.

Similarly, opening the quests as you pass them is surely possible, as is recording with a single button hold (similar to how WhatsApp does it).
