### ISSUE TITLE
Star count and three-dot icon are black in day mode

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1562]
Untested in night mode

tested in https://github.com/westnordost/StreetComplete/commit/3335e5f1226785dada06989ef1e8ab7df01ab6ca

**Comment by westnordost** [comment]
Cannot reproduce on my phone

Likely caused by https://github.com/westnordost/StreetComplete/commit/aa20b5370ebe2966fe1480a2d6e700efc94f318f

Since I can not reproduce it, would you please check out the solution by explicitly defining the toolbar theme? If you define the toolbar theme explicitly, you also need to define the popupTheme.

More information here: https://stackoverflow.com/questions/26504532/appcompat-toolbar-popuptheme-not-used-in-the-shareaction-menuitem

**Comment by westnordost** [comment]
Actually, turns out that I can reproduce it after all. Will take this over
