### ISSUE TITLE
clicking on upload counter with 0 things to upload triggers upload animation

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1564]
To reproduce - disable autosync, upload all edits until 0 changes wait for upload and press upload button.

I have not tested is it triggering also actual upload.

Issue is minor but at least for me it would reduce (by a tiny bit) a trust in what app shows.

Hopefully this one is not happening just on my phone.

**Comment by westnordost** [comment]
Likely a will not fix. The upload service is started in the background. In the background, the service checks the various things to be uploaded. This takes time, and that time is shown in the UI. I wouldn't like to disable the button if the counter shows 0, because that functionality should IMO not rely on the counter showing the correct count at the moment.
