### ISSUE TITLE
Local store of photos?

### ISSUE THREAD

**Issue by rmikke** [westnordost/StreetComplete#1569]
Does StreetComplete store photos on the phone after uploading them to the server?

I have updated the [note 1921582](https://www.openstreetmap.org/note/1921582) , but the upload failed so I would like to find the photo on the phone and upload it somewhere or just use it to close the note.
**How to Reproduce**

**Versions affected**

**Comment by MegaArthur** [comment]
I'd guess it's probably stored in the alp's files, you'd need root access to get them

**Comment by hypervtechnics** [comment]
@MegaArthur Maybe he can try to make a backup of the app using `adb backup` command to get the data folder

**Comment by westnordost** [comment]
Photos are deleted after a successful upload.

The more important question is, why did the upload fail? What exactly failed?

**Comment by westnordost** [comment]
Ah, I see only the upload of the photo failed and that it failed was printed in the note. 

The reason should be found in the logs, could you post the logs for StreetComplete from the time the note was created?

**Comment by rmikke** [comment]
Where do I find the logs? I can only see cace and files/Pictures under /android/data/de.westnordost.streetcomplete. The phone is not rooted.

**Comment by westnordost** [comment]
Mhh, I am not sure but maybe you can access them via CatLog (an app).

Otherwise, you could install the Android Sdk on your computer, or at least the "adb" commandline tool, activate usb debugging on your phone (tap many times on the build number in the about phone section in the settings) and then finally read the logs via adb.

**Comment by rmikke** [comment]
CatLog requires root, I'll try adb in the evening.

**Comment by westnordost** [comment]
Actually, do you have Android version 6 or newer? If yes, then there is an easier solution:

In the "developer settings", there is an option called "Take bug report". This should include the logs:
https://developer.android.com/studio/debug/dev-options

If you do not want to share whatever is in that bug report publicly, you can send it to osm@westnordost.de

**Comment by rmikke** [comment]
Sent. Subject:
Emailing: bugreport-CatS61-OPM1.171019.011-2019-09-18-14-44-15.7z

**Comment by westnordost** [comment]
Hm, I didn't get any email. Also checked the spam folder.

**Comment by rmikke** [comment]
Well, that's strange. I've sent it from my company email and got a copy on my private email. The address matches the one you gave here. Maybe the problem is with message size (2,5MB) or some antivirus stopped the message with compressed attachment?

**Comment by rmikke** [comment]
I have shared the file via Google Drive

**Comment by westnordost** [comment]
Got it (both, one with attachment and one without ^^)

**Comment by westnordost** [comment]
Hmm, it looks like this bugreport only contains the logs from yesterday but we'd need the logs from 11th of September.

Anyway, what I can say is that the "error: upload failed" message is printed when:
1. The photo upload service returns an unexpected response
2. The photo upload service responds with an HTTP error response, i.e. _not found_ or _forbidden_
3. There was a connection problem when contacting the photo upload service, i.e. most commonly a socket timeout or no network error

Point 1 and 2 are very unlikely because the upload server is under my control, so it is unlikely that the service will suddenly respond with garbage or not be available (not found) anymore.
So what probably happened is that while trying to upload the picture, you shortly did not have network connection.

The photo upload is considered as a non-vital part of the upload process as in that a (permanent) failure here should not lead to the whole upload process being cancelled because then the user cannot upload anything at all anymore. 
This was different in the past, but there was a problem with this. Before @exploide built an own photo upload service for StreetComplete, the app used to use https://lut.im/ to upload the pictures. Then, without prior warning, the service shut down and suddenly, noone who created even just one note with one picture couldn't upload any changes anymore because the whole upload would immediately fail.

**Comment by westnordost** [comment]
For about 4% of all notes with attached pictures, the upload of the pictures fails.

**Comment by rmikke** [comment]
Would it be a problem to add an option to store photos locally even after uploading? For those 4%?

**Comment by rmikke** [comment]
> Hmm, it looks like this bugreport only contains the logs from yesterday but we'd need the logs from 11th of September.

It's BIG and contains some activity from 2019.09.12 for sure (like "this app was in front, then has gone to background"), I've tried to locate the error in this report but without success.

**Comment by matkoniecz** [comment]
> For about 4% of all notes with attached pictures, the upload of the pictures fails.

That is quite high number. Maybe it would be reasonable to retry download later and add image link as a comment (assuming that somebody, for example me, would be willing to make a PR)

**Comment by westnordost** [comment]
Well, yes. I guess it would make sense to only upload the note if the image upload (if any) succeeded. And if it did not, keep it in local storage and try again on next upload attempt.

But this requires to distinguish between two failure cases along with the one success case:
- conflict on upload of the note (comment) -> delete locally stored note and attached photos
- exception on trying to upload the photo attached to the note (comment) -> keep in local storage, so try again uploading on next upload attempt and regularly upload the next note(s) and changes

**Comment by rmikke** [comment]
Why not make it simple and just add an option to additionally store photos in selected directory, regardless of upload result? Maybe with option to automatically discard photos older than specified amount of time.

**Comment by westnordost** [comment]
Because that'd be just a workaround for a known problem. Better solve the problem then.

**Comment by westnordost** [comment]
Created a follow-up ticket
