### ISSUE TITLE
Bridge quest improvements

### ISSUE THREAD

**Issue by daveol** [westnordost/StreetComplete#1595]
Hi, while out in the field I found the bridge quest a bit lacking. It was unclear what to choose for some bridges, both because no bridge in the options matched of it was unclear what the option meant since there are no descriptions of the bridges either.

**Use case**
For example I came across this bridge:
![image](https://user-images.githubusercontent.com/1355084/66254725-b62dec00-e77a-11e9-8030-bd6358f5d295.png)
Which is not one of [bridge:structure](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) but more like [bridge:movable](https://wiki.openstreetmap.org/wiki/Key:bridge:movable)=[drawbridge](https://wiki.openstreetmap.org/wiki/Tag:bridge:movable%3Ddrawbridge). While for this bridge the quest did not pop up, I would find it unclear which of the options to choose:
![image](https://user-images.githubusercontent.com/1355084/66254833-22f5b600-e77c-11e9-9e0d-b0801eed3781.png)

**Proposed Solution**
- The options need to be described better, with text, since it's not really clear what feature of the bridge I'm looking at to compare with.
- More options that describe bridges, not only of [bridge:structure](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) but also of [bridge:movable](https://wiki.openstreetmap.org/wiki/Key:bridge:movable)

**Comment by rugk** [comment]
For reference: The original proposal had names for the briges, but [here it was removed](https://github.com/westnordost/StreetComplete/pull/709#discussion_r153203434), but not really discussed further whether names would still make sense… :thinking: 

--

As for the other thing: "bridge:movable" would maybe better be a new separate quest? (though a nice one, IMHO, because [we already have nice animations in the wiki](https://wiki.openstreetmap.org/wiki/Key:bridge:movable))
Or is it always clear that a bridge can only either be movable, or have a "structure"?

**Comment by daveol** [comment]
well the [bridge mentioned above](https://www.openstreetmap.org/way/298106003) did not show up as a quest and does not have a [bridge:structure](https://wiki.openstreetmap.org/wiki/Key:bridge:structure) property

**Comment by westnordost** [comment]
I added that the app will not ask the bridge structure for bridges that have `bridge:movable` tagged.

For the rest (movable bridges that are not tagged as such yet), I think it is feasible for the surveyor to leave a note (and attach a photo) instead then.
