### ISSUE TITLE
Ask for taking a picture from a castle

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#1601]
### General
This maps https://castle-map.infs.ch/ collect castles and ruins. They requests Photos from Users. This Photos have to be uploaded to wikidata.

**Comment by rugk** [comment]
Please do fill the "new issue" template for proposing new quests. This should have been suggested to you before/when opening a new issue.

**Comment by HolgerJeromin** [comment]
(side note: you mean wiki commons and not wikidata).
StreetComplete can not upload to Wiki servers right now. 
Another problem is, that this app is designed to be able to "complete" an area. This is not possible with this quest. 
"Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)" 

https://play.google.com/store/apps/details?id=fr.free.nrw.commons should be the target app for such things.

**Comment by ferdinand0101** [comment]
While it doesn't exactly add new Tags as far as I know we can still check in overpass for Wikidata data a look if something with a wikidata has a picture
This could then also be extended to more than Castles and be really useful

**Comment by Mannshoch** [comment]
As an Example: [https://www.openstreetmap.org/way/52671046](https://www.openstreetmap.org/way/52671046)
has a wiki data tag that leads to: [Q1012539](https://www.wikidata.org/entity/Q1012539)
and an Image Tag which leads to: [B-Huenenberg-Burgruine.jpg](https://upload.wikimedia.org/wikipedia/commons/b/b0/B-Huenenberg-Burgruine.jpg)

As a Question I would only ask for a Picture if a castle do not have an image tag. This made it possible to complete an Area.

Is there a specific wish to not challenge the Wikimedia Commons App? I would propose to do it.

**Comment by matkoniecz** [comment]
Note that StreetComplete is OpenStreetMap editor, not a Wikidata editor.

I see nothing OSM specific here.

**Comment by matkoniecz** [comment]
https://tools.wmflabs.org/fist/wdfist/ is tool that may be interesting for you

https://tools.wmflabs.org/fist/wdfist/?category=Castles&depth=9&language=en&project=wikipedia&no_images_only=1&prefilled=1 alone lists over 1000 castles with no image entry on Wikidata with highly likely matches, that can be easily handled

**Comment by Mannshoch** [comment]
> Note that StreetComplete is an OpenStreetMap editor, not a Wikidata editor.
Why not? I don't see any hindrance to not think this app in this way. And with my last propose there is OSM data which get modified and completed.

At moment, you are also possible to upload pictures if you wish to document a bug. For that westnordost use his own server.

Thanks for the link to https://tools.wmflabs.org/fist/wdfist/ But I'm not able to understand this tool in any way. Overpass with his Wizard seems easier to use.

**Comment by JeanFred** [comment]
The web-tool https://tools.wmflabs.org/wikishootme/ can work that way (although not specific to castles), as well as the [Wikimedia Commons app](https://github.com/commons-app/apps-android-commons)

**Comment by matkoniecz** [comment]
> Thanks for the link to https://tools.wmflabs.org/fist/wdfist/ But I'm not able to understand this tool in any way.

It lists Wikidata entries without images where Wikipedia pages have images and allows to add selected ones or mark available images as false positives.

https://tools.wmflabs.org/fist/wdfist/?category=Castles&depth=9&language=en&project=wikipedia&no_images_only=1&prefilled=1 links to articles from a castle category, mostly castles.

**Comment by rugk** [comment]
@Mannshoch Can you still please complete the issue template? We do have this for a reason and it may be that this issue template would have solved many questions/discussions already. Thanks. :smiley:

**Comment by ferdinand0101** [comment]
I myself just filled out the temple
While I'm not @Mannshoch this is what my current perception of the whole thing is

General
Affected tag(s) to be added:
Pictures for Wikicomons/Wikidata 

Question asked:
Can you take a picture of this castle (or other thing) ?
Example keys:

Uploading to wiki so I don't really know how

Checklist for quest suggestions (see guidelines):
 🚧 To be added tag is established and has a useful purpose

Yes a lot of programs and Apps use those images in connection to osm data (JOSM)

 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)

Yes we can look if there are pictures

 🐿️ Easily answerable by everyone from the outside but a survey is necessary

Yes

 💤 Not an overwhelming percentage of elements have the same answer (No spam)

Picture are unique

 🕓 Applies to a reasonable number of elements (Worth the effort)

The castle project needs quite a lot of images so yes

**Comment by Mannshoch** [comment]
thanks @ferdinand0101

**Comment by ferdinand0101** [comment]
okay I have looked into how to upload pictures to commons and honestly I still don't really know how but I found the documentation for their androind app
https://github.com/commons-app/apps-android-commons/wiki/External-APIs
if any of y'all wanna look into that

**Comment by westnordost** [comment]
I can see the reason behind the quest type, and it is a valid one, especially when looking at this map-mashup that shows the pictures of castles.

However, I think there should maybe rather a dedicated (wikimedia-driven/developed) app for this. Four reasons:
1. For wikimedia, we want well-made high-resolution pictures where ideally some time was invested to make good photos, from different angles etc. Not just any snapshot one can do with his phone. The camera in high-end smartphones is certainly decent, however this can not be assumed for anyone with a smartphone. 
2. For this to work, the user needs a wikimedia account. Being primarily an openstreetmap app, it will take some effort to explain this to the user. Not to mention the technical effort to implement authorization towards wikimedia
3. The app does currently not support uploading quest answers to anywhere else than the OSM API. To change this will require a larger refactor of the upload process and then effort to implement this upload to wikimedia. This alone would be a reason for me to at least "not do it for now", because it is a bit out of scope
4. While it may be possible to find castles with missing pictures via Overpass, this use case is quite limited (to castles). There are more photo-worthy objects in the world that do not have a photo yet. But of course, it would be difficult to find these automatically. Also, as far as Wikimedia goes, there is a lot more than just photos that may have to be collected on-site. A dedicated platform + app for Wikimedians/Wikipedians would solve this use case better: People could leave requests for photos or other kind of information to be acquired on-site at certain locations and other people could comment on these (A bit like OpenStreetMap notes).

In regards to point 4, maybe StreetComplete could be a client with which people can contribute to this platform, but this hypothesises that a platform like this exists in the first place.

So, this is why I will close this ticket as will not fix.

**Comment by mnalis** [comment]
Note: there exists [Commons app for Android](https://github.com/commons-app/apps-android-commons/) which contributes such imagery to [Wikimedia Commons](https://commons.wikimedia.org/ ). It works pretty nice, interested parties should go try it out! It is also [available](https://f-droid.org/en/packages/fr.free.nrw.commons/) on F-droid too.

Also, since Wikimedia Commons is big on not just good quality pictures but also metadata (caption, longer description, GPS coordinates, what does it depict [wikidata], categories etc.) it would probably make little sense to try to re-implement that whole app inside some other app like StreetComplete.
