### ISSUE TITLE
Marker re-initialization with since update

### ISSUE THREAD

**Issue by typebrook** [westnordost/StreetComplete#1606]
https://github.com/westnordost/StreetComplete/blob/d72c22303fd8edb3652c6ed68f3eb74a923ca200/app/src/main/java/de/westnordost/streetcomplete/tangram/MapFragment.java#L454

When `MainActivity` is focused, it continuously calls this method. According to the name `onRotationChanged`, it should only be triggered when map is rotating. 

Because in this method we set style for Marker, it could potentially causes APP crash when doing [`MapController.updateSceneAsync()`](https://tangrams.readthedocs.io/en/latest/API-Reference/android-sdk/0.10.0/com/mapzen/tangram/MapController.html#updateSceneAsync-java.util.List-) in MapFragement (though we don't do it now) with error message below:

```
java.lang.RuntimeException: Tried to perform an operation on an invalid id! 
This means you may have used an object that has been disposed and is no longer valid.
```
**How to Reproduce**
v14.1 and just log this method

**Versions affected**
v14.1

**Comment by westnordost** [comment]
The method is called by the compass component. It actually means, that the **smartphone** was rotated/tilted, not the map. The callback for when the map is rotated, is `onMapOrientation`.
If this is confusing, I'd suggest to refactor the class to not implement all those listener interfaces itself, but use private anonymous SAM classes / lambdas for this, i.e. in line 158:

```
compass.setListener((rotation, tilt) -> {
    //...
});
```

I am kind of hold of on any (refactor) work on `MapFragment` etc. until an upgrade of the tangrams-es dependency 0.10.x becomes necessary.

---

Anyway, the naming of the mentioned method is not the main issue you address. It is a pity that tangram-es just invalidates (=removes) all markers on each scene update.
I think the best solution here would be to never call `MapController.updateSceneAsync()` directly but instead wrap it in a function like this:
```
protected int updateSceneAsync(List<SceneUpdate> sceneUpdates) {
    // TODO: set all markers to null
    controller.updateSceneAsync(sceneUpdates);
    // TODO: reinitialize all markers, as applicable
}
```
Because `QuestsMapFragment` also uses markers, the implementation to reinitialize all the markers is not trivial. Probably it will be necessary to have a wrapper object for every marker that will not be invalidated through a `updateSceneAsync` call and is able to reinitialize its marker if asked to.

**Comment by typebrook** [comment]
Thanks for the explanation! looks like I misunderstood this method.

I think your solution is great. Just updated #1607 with 34630d2.
And it is not necessary to reinitialize all markers in this case. We already initialize those markers inside `onSceneReady()`, and it would be called each each time when scene is updated.

**Comment by westnordost** [comment]
I see, well, that's nice. Anyway, `QuestsMapFragment` assumes that `onSceneReady` is only called once when the map is initialized, this is why it adds new layers and clears the memory about for which tiles the quest pins have been pulled from the local database and inserted into the map.
Additionally, as mentioned previously, QuestsMapFragment holds markers which all are invalidated on a map update.

Suggestion:
1. Implement in `MapFragment` to distinguish in `onSceneReady` (using `sceneId`) between a scene update ready and a scene initialization ready and call two different functions, so that the code to init and reinit a scene is separated also in the subclass
2. I think we won't get around 
> Because QuestsMapFragment also uses markers, the implementation to reinitialize all the markers is not trivial. Probably it will be necessary to have a wrapper object for every marker that will not be invalidated through a updateSceneAsync call and is able to reinitialize its marker if asked to.

**Comment by typebrook** [comment]
@westnordost I have another simpler way to do this:

![Screenshot from 2019-10-25 14-28-21](https://user-images.githubusercontent.com/19887090/67548184-c7439a80-f733-11e9-9a5d-92afb48de51a.png)

I see you currently just do null check for **every** places where `Marker` is used, so why not just
replace `if(xxxMarker != null)`
with function like `if(isValid(xxxMarker))`
```java
void isValid(Marker marker){
    return marker != null && marker.getMarkerId() != 0;
}
```

**on the pro side**
- do a safer check every time a `Marker` object is used. Though besides scene update, it takes less chance to invalidate a Marker(that is: set `markerId` to 0)

**on the meh side**
- call it every time when a Marker is used. But since now we already do null check, a single regex replace command would be enough

**Comment by westnordost** [comment]
But what does it solve? The problem is that the makers have to be reinstantiated after each scene update.

**Comment by westnordost** [comment]
> AFAIK, QuestsMapFragment has no Marker object now

It does, it is the markers for splitting the way. But anyhow, I changed my mind: I think making it proper should be part of a refactor. Let's focus on getting this PR through before delving too deep into deliberations about refactoring these classes.
The markers when splitting a way are never shown at the same time as a note is left, so at least for now, we can get away with not properly reinitializing all the markers on a scene update in `QuestsMapFragment`.

**Comment by westnordost** [comment]
The new version of tangram-es does not support scene updates anymore. Every "update" is a scene reload
 I'll consider this in my refactorings ("new_tangram" branch)

**Comment by westnordost** [comment]
This will be solved in the next release
