### ISSUE TITLE
New quest: tag bus stop ID numbers

### ISSUE THREAD

**Issue by claysmalley** [westnordost/StreetComplete#1642]
### General
Affected tag(s) to be modified/added: [public_transport=platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport=platform) and [highway=bus_stop](https://wiki.openstreetmap.org/wiki/Tag:highway=bus_stop) when it is not used to mark a [public_transport=stop_position](https://wiki.openstreetmap.org/wiki/Tag:public_transport=stop_position)
Question asked: **What is the identification number of this bus stop?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ yes ] 🚧 To be added tag is established and has a useful purpose
- [ yes ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ yes ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ yes ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ yes ] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:** https://overpass-turbo.eu/s/O3o

**Proposed GUI:** Text box, defaulting to numerical input (as is the behavior for adding house numbers). Response populates `ref` tag. Possibly also a photo of a bus stop with its stop ID highlighted. Under the "Other answers" menu:
* "It has multiple stop ID numbers" (this can be the case where many operators share a bus stop)
  * Answer: "you can simply enter semicolon-separated stop ID numbers. Example: 14233;58084"

Sample bus stop, with its stop ID in the bottom-right corner. May need editing to highlight.

![Bus Stop at El Cerrito del Norte](https://user-images.githubusercontent.com/1732117/68720816-5e4a8800-0565-11ea-8710-1f338788ab5e.jpg)

**Comment by matkoniecz** [comment]
> Not an overwhelming percentage of elements have the same answer (No spam)

I think that this quest needs also list of countries where it makes sense to ask it (or list where it should not be asked).

Is it typical that bus stop in the USA generally have `ref` taggable based on a survey? Or is it limited to San Francisco? (https://commons.wikimedia.org/wiki/Category:Bus_stops_in_the_United_States may be helpful)

For example in Poland bus stops have name (sometimes with number as part of it) but not `ref` codes, so asking it there would be pointless.

> To be added tag is established and has a useful purpose

Is this tag used somewhere somehow or is there reasonable potential use? (this one would influence how high it would appear in list of available quests)

**Comment by pkoby** [comment]
I would say for some countries (e.g. US), it would probably be turned off by default, because it's certainly not a standard overall. I've lived somewhere with stop IDs, but I can't recall if they were shown on the signs or just in internal datasets for the bus company. Where I live now, we're lucky to even get a sign at all.

**Comment by goldfndr** [comment]
> Is this tag used somewhere somehow or is there reasonable potential use?

[ÖPNVKarte](https://www.xn--pnvkarte-m4a.de/) shows the bus stop ref at zooms 17 and 18. [OSM Inspector](https://tools.geofabrik.de/osmi/) in its ["Public Transport - Stops" view](https://wiki.openstreetmap.org/wiki/OSM_Inspector/Views/Public_Transport_-_Stops) shows the bus stop ref at zoom 16+.   (I don't see them in http://openptmap.org/ or [Transport Map](https://wiki.openstreetmap.org/wiki/Transport_Map) currently.)

[OsmAnd](https://wiki.openstreetmap.org/wiki/OsmAnd) definitely displays the bus stop `ref` at zoom 16 or higher, alone if `[!name]` or in parentheses if `[name]`, prioritizing over `name` display if the text won't fit due to collision, with the default "OsmAnd" map style ("Offroad" and "Topo" styles don't display it on the map but the others do).  
(OsmAnd also displays the ref for [a railway platform](https://www.openstreetmap.org/way/332989909), but that's outside the scope of this issue.)

See also [my earlier comment in #81](https://github.com/westnordost/StreetComplete/issues/81#issuecomment-552143058), but I should add that [OneBusAway](https://github.com/OneBusAway) uses GTFS feeds directly. This issue is *probably* relevant to [any location](https://transitfeeds.com/) that [has a](https://transit.land/feed-registry/) GTFS feed. While a GTFS feed will *probably* have more current and accurate data, apps offered by operators (if offered on a compatible software platform) *might* be more cumbersome to use than OSM data.

Locally, the ref appears on the sign (and, if present, on the shelter). However, I have seen some stops locally (same operator) where the signs lacked the ref; maybe they weren't yet worn out enough for replacement.

Semi-offtopic: I wonder if it would be sensible to make `noref` (and similar no\* tags) optionally be an "as of" ISO 8601 date value and not merely a `yes` value, so that `last_checked` (or equivalent) wouldn't need to be set.

**Comment by claysmalley** [comment]
> Is it typical that bus stop in the USA generally have `ref` taggable based on a survey? Or is it limited to San Francisco?

It depends heavily on the operator of the bus route. Some bus operators put their stop IDs on their bus stop signs, and some don't. It even varies within the SF Bay Area. There's really no way to know without surveying.

I suppose it could help to have another option under "Other answers":
* "It has no stop ID number"
  * "Some bus operators don't post stop ID numbers on their signs. If this is the case, you may have to skip this quest."

My wording could probably use some improvement.

**Comment by westnordost** [comment]
Since public transportation is usually not organized on a nation-wide standard, and thus, it cannot be expected that in any (region within) one country, there is a reasonable chance that one can expect to find the IDs on the sign, I see no chance for this quest to go into StreetComplete.
In any case, such a per-country-list would be necessary, same as with the postbox ref quest. (But post is organized nation-wide).

So, this is is a will-not-fix. If you come by information about that in certain countries, an ID will always be visible, it could be reopened.

Another difficulty for this quest would be that it varies where (if at all) the ID is given on the sign and if it is, how it is written there and how it looks. Also, the non-presence of an ID visible on the sign does not mean that the bus stop has no ref.

**Comment by matkoniecz** [comment]
Is it potentially something where pull request adding disabled by default quest would be OK?

**Comment by westnordost** [comment]
No, rather not. I'd not like to cross this line that quest types are included that are not fit for general use.
