### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by it4workflow** [westnordost/StreetComplete#166]
Where are the available [quests](https://github.com/westnordost/StreetComplete/tree/master/app/src/main/java/de/westnordost/streetcomplete/quests) for non-programmers documented?

**Comment by westnordost** [comment]
They are not documented.

**Comment by matkoniecz** [comment]
What would be purpose of such documentation? This program is intended to be usable without reading documentations and non-programmers will be anyway unable to code new quests.

**Comment by it4workflow** [comment]
e.g. that a non-programmer could propose new quests.

> This program is intended to be usable without reading documentations

As a matter of fact, yes, but it would be nice, if there's any overview. And what if i want to solve only selected quests (in future)

**Comment by matkoniecz** [comment]
> And what if i want to solve only selected quests (another feature request)

See Feature Request: Filter quests #35 

> e.g. that a non-programmer could propose new quests.

Working with app for such time should give enough info to do that (and without using app proposing quests is not going to be very useful)

**Comment by westnordost** [comment]
#35 will be implemented in any case sooner or later, so users of the app have an overview of what is there. Otherwise, the worst thing that can happen is that I close your request for a new quest as duplicate, but you can of course search here on github: I labeled all new-quest requests with a label "new quest".
