### ISSUE TITLE
Rendering bug when unlocking phone straight to app

### ISSUE THREAD

**Issue by thibaultmol** [westnordost/StreetComplete#1675]
I've figured out what this weird rendering bug on my end is being caused by.
 What happens is that all the quest pins on the map dissapear (sometimes only the ones in view though)

**How to Reproduce**

When you have the app open (just on the default screen with the map) and then lock your phone. Unlock it. And then the map's pins dissapear.
But it *seems* to only happens to the pins that are in the view when you lock your phone.
This is what I see when I unlock the app and zoom out: https://photos.app.goo.gl/m5D79iHNZE8MmS3o6
And when I then minimize the app and open it again (causes a new render I guess):  https://photos.app.goo.gl/4pL7VFa4jcatKxZN8
**Versions affected**

V 15.0 on Android 10 (Google Pixel 2) using the Nova launcher (if that helps)

**Comment by matkoniecz** [comment]
Oh no. It sounds like #1415/#1456 that was supposed to be fixed in https://github.com/westnordost/StreetComplete/commit/5fbff271b9cd9734aa8f5a6bb0bccea6e1f5d2a0

This bug is especially obnoxious as it is a race condition bug with visible effects only on some devices. Older variant was not appearing on devices that @westnordost has but was visible on mine.

After 5fbff271b9cd9734aa8f5a6bb0bccea6e1f5d2a0 it is appearing neither on mine or his. At least not in this easy-to reproduce form.

> When you have the app open (just on the default screen with the map) and then lock your phone. Unlock it. And then the map's pins dissapear.

Is it happening always or only sometimes? Is it happening also in case of unlocking it with a fingerprint rather than a code?

**Comment by thibaultmol** [comment]
It's surprisingly consistent actually. Every time I unlock it, it happens.
Was doing it with fingerprint, but using code (pattern lock in my case) also has the same effect

**Comment by westnordost** [comment]
This should be fixed for the next version
