### ISSUE TITLE
Exclude from lit quest sidewalks tagged as a separate ways near roads

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1678]
In some regions, for example in Poland, sidewalks are tagged as a separate `highway=footway` ways. See for example https://www.openstreetmap.org/#map=19/50.05941/19.94257

One of local mappers new to SC noticed that tagging lit status of such sidewalk is quite pointless in cases where it close to road, as data users can process data and expand lit=yes from road into nearby sidewalks

I though about excluding

- `footway=crossing` – as footway crossing part will certainly have the same lit status as the main road
- all `footway=sidewalk`
- `footway=sidewalk` with at least part of it close to a road
- short (<30m) sections of `highway=footway`/`path`/`cycleway` close to roads, to exclude way such as https://www.openstreetmap.org/way/589696051 even when not tagged with `footway tag`, without excluding long stretches of footway that cross roads

**Comment by westnordost** [comment]
Weird, I thought I already answered on this one.

Especially on main roads, there are often trees and bushes between the sidewalk and the street, so the lighting can be quite different on the sidewalk than on the road, even if the footway is tagged as a sidewalk.

To my knowledge, the best mapping practices are to only map sidewalks as separate ways if there is a physical barrier between the road and the footway (= you can not cross the street at any point), because otherwise it can lead to ridiculous directions in pedestrian routers and it is physically still part of the road and we map what we see.
But well, since it is not a hard rule, people can map what they want, but then adding another `lit=yes` where it might be inferred with relative certainty by a geospatial analysis does also not hurt.

So, I would rather not change it because it is not trivial for data consumers to infer that information from nearby roads (geospatial analysis necesssary), and the inferred information would be a fuzzy anyway.
Or, to say it in a cheeky way: If it can and should be inferred that a separately mapped sidewalk is not actually a separate way, then what is the sense of mapping it separated?

**Comment by matkoniecz** [comment]
What about the weakest part? Not asking for `footway=crossing`? "trees and bushes between the sidewalk and the street" would not apply here, but "it is not trivial for data consumers" would still apply.

**Comment by westnordost** [comment]
That's true, but the issue of it not being trivial for data consumers to infer that information remains. Though, I am not opposed to this compromise.

**Comment by westnordost** [comment]
Hm actually I'd rather not do this. As you said, my main point still applies. Also, crossings are not exactly that numerous plus sometimes simply not lit so it would not result in spam.
