### ISSUE TITLE
Disabled quests may be sometimes shown (race condition on disabling quest types during download)

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#1681]
**How to Reproduce**
Reinstall app, gave it a location permission, go to settings, disable all quests except one type, exit settings.

Now, after quests load sometimes disabled quests are shown (sadly, not always, in about 1/3 or 1/4 cases).

Closing app and opening it shows only enabled quests.

**Versions affected**
Android 6.0.1
StreetComplete 15+ (master version)

**Why I even care to report this?**

Reported as I hope that it is related to #1675

**Comment by westnordost** [comment]
Yeah, probably not related to #1675.

The setting which quests are enabled only controls which quests are downloaded. If a download already started, it doesn't stop the download and also doesn't discard the downloaded quests.

To solve this, the `QuestMapFragment` would need to check for every added quest (line 491) if its type is currently visible by consulting the `VisibleQuestTypeDao`. Only that I am not sure if this should be done at all because I am not sure if this classifies as a bug at all.

**Comment by westnordost** [comment]
Ok what I implemented now is that the download is cancelled* if the user changes anything in the quest selection screen.

* the download for the current quest type is finished, then the rest of the queue is cancelled.
