### ISSUE TITLE
Map tiles sometimes not loading

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1687]
I sometimes have problems with map tiles not loading, and it seems that it is not an issue with the tile server.
It might actually be (somewhat) intended behavior, but I'll put all here as bug report anyway... at least to get some understanding what is going on.

Sometimes map tiles are not loading when I am far away, which makes pre-loading difficult. Once I get close (and have internet connection), the tiles reliably load without any problem.
Is this some intended behavior, or are my observations just accidental and there were temporary issue with the server (and I don't remember cases where everything works).

Then once I have the tiles downloaded (i.e. in cache), I sometimes see a somewhat similar issue: even the cached tiles sometimes only load close to my location.
Some newer trains are pretty well shielded, no WiFi from outside and no GPS signals inside, so I can't avoid that my phone does not report my current location. In such cases it sometimes happens that Street Complete displays my last location, with the map tiles loaded in that area, but scrolling too far (to my "real" location) shows only an empty map, now matter what zoom level. Once I get out of the train, the phone finds a new location, and tiles in vicinity quickly load, even without internet connection (i.e. tiles were definitely in cache the whole time).
So what is the problem? I was able load the tiles initially from far away, but some 10 minutes later (same location according to my phone) the tiles are not displayed any more. Restarting the app does help rarely in such cases, but usually it does not change anything.

Sorry that I use the word "sometimes" quite often, but I haven't found any pattern when this issue occurs and when everything loads just fine...

Version: 15.0 (f-droid), LineageOS 16.0

**Comment by westnordost** [comment]
Tile loading is definitely not influenced by the current location. There is nothing like that programmed into StreetComplete and the map rendering library the app uses also does not know the users' location.

What might be triggering a behaviour that seems to favour loading the tiles around the current location is that if the location is available, the app zooms the map to that location automatically, triggering immediately to load the tiles, even if you pan away from that location immediately after.
The tiles might also be (continued to be) loaded in the background when you send the app to the background*, so at times, the tiles around your location might be in the cache already when you reenter the app.
While when you plan to another location, all tiles on the way to that location must be loaded, which is a lot more. It makes sense that the ones queried first are returned first.

* I don't know this, but it would make very much sense to not cancel all pending HTTP requests for the tiles only because the user (shortly) brings another app into foreground.

Am 29. Dezember 2019 11:11:47 MEZ schrieb Helium314 <notifications@github.com>:
>I sometimes have problems with map tiles not loading, and it seems that
>it is not an issue with the tile server.
>It might actually be (somewhat) intended behavior, but I'll put all
>here as bug report anyway... at least to get some understanding what is
>going on.
>
>Sometimes map tiles are not loading when I am far away, which makes
>pre-loading difficult. Once I get close (and have internet connection),
>the tiles reliably load without any problem.
>Is this some intended behavior, or are my observations just accidental
>and there were temporary issue with the server (and I don't remember
>cases where everything works).
>
>Then once I have the tiles downloaded (i.e. in cache), I sometimes see
>a somewhat similar issue: even the cached tiles sometimes only load
>close to my location.
>Some newer trains are pretty well shielded, no WiFi from outside and no
>GPS signals inside, so I can't avoid that my phone does not report my
>current location. In such cases it sometimes happens that Street
>Complete displays my last location, with the map tiles loaded in that
>area, but scrolling too far (to my "real" location) shows only an empty
>map, now matter what zoom level. Once I get out of the train, the phone
>finds a new location, and tiles in vicinity quickly load, even without
>internet connection (i.e. tiles were definitely in cache the whole
>time).
>So what is the problem? I was able load the tiles initially from far
>away, but some 10 minutes later (same location according to my phone)
>the tiles are not displayed any more. Restarting the app does help
>rarely in such cases, but usually it does not change anything.
>
>Sorry that I use the word "sometimes" quite often, but I haven't found
>any pattern when this issue occurs and when everything loads just
>fine...
>
>Version: 15.0 (f-droid), LineageOS 16.0

**Comment by gmischler** [comment]
On a related note (probably sidetracking this thread a bit), I have one tile that hasn't loaded for quite some time (weeks?), neither in day nor in night mode. I'm guessing something went wrong with tile generation around coordinates [48.14947/11.46154](https://www.openstreetmap.org/#map=16/48.1486/11.4615).

**Comment by Helium314** [comment]
Ok, so sometimes I have really slow loading of tiles even close to my location (S4 Mini is old & not the fastest). If whatever is causing this (my highly subjective impression is that is tends to happen when the map moves from initial to my location when there is a large distance, and also somehow quest loading seems to be involved) occurs after the first tiles are loaded, then of course loading everything on the way takes an eternity...
Next time Ihave this prolem I will try panning to the area I want, close (or force stop) and start the app again.

@gmischler 
I also have 3 of those... interestingly 2 of them are located at train stations, and I see this is the case for your's as well. 
But this is definitely a separate issue (probably with tile generation)

**Comment by Akasch** [comment]
The original issue is caused (I think) by the server: At the moment each region can only have two processes calculating tiles at the same time. So if one scroll fast over the map the tiles get generate in the ordering of the requests. If the queue is to full some of the requests are getting cancelled  because of timeouts before they are calculated. After that it gets faster again.

The issue of @gmischler is related to that, some mid zoom tiles in dense cites have so many objects on them that the calculation of all data does not finish within the timeout of 90 seconds on the server. It is on my todo list do generate a list of the tiles frequently hitting timeouts and pre calculate them at night.

**Comment by Helium314** [comment]
@Akasch 
Thanks for the info! That should explain some / many cases of what I thought was the same issue. So I assume tiles are cached once they are calculated? That would explain why some areas appear empty for quite a while.

However, the case where I definitely had the tiles pre-loaded / cached and they would not appear for quite a while should not be related to the server; in the end they all appeared at a time when I had no internet connection. I guess this is just the really slow loading that sometimes happens as mentioned above.

I'll close this issue, and maybe open again if I find some more reproducible behaviour/conditions...
