### ISSUE TITLE
roof shape quest with "recent used order" confusing

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#1692]
I am pretty sure in the past the roof shape quest had constant sort order. 
In one of the latest update it changed to "recent used order". 
The old, stable sorting was better IMO since I knew the first one was `gabled` and could select it without double checking.

**Versions affected**
Lastest play store beta

**Comment by westnordost** [comment]
The stable order was a bug, this now is the intended behaviour. It bug used to occur for *all* quests.
What is your reasoning for why for this quest, recently used roof shapes abound not be moved to the front?

Am 3. Januar 2020 08:08:25 MEZ schrieb Holger Jeromin <notifications@github.com>:
>I am pretty sure in the past the roof shape quest had constant sort
>order. 
>In one of the latest update it changed to "recent used order". 
>The old, stable sorting was better IMO since I knew the first one was
>`gabled` and could select it without double checking.
>
>**Versions affected**
>Lastest play store beta

**Comment by HolgerJeromin** [comment]
The mru order is faster if the selecting needs time. For example surface quest has a very long list with two layer menu (paved, unpaved...) or building levels have select, enter number, select, enter. 
But with this quest all (?) possible answers are shown at once. 
I knew: first is gabled. When I needed another one it was found quickly. If the next roof is the same, i remember the position (third from the first row) an am very fast.

Now this knowledge is not usable, as I have to scan many icons every time.

**Comment by pkoby** [comment]
I'd also say that in the surface quest, it's very quick to see the difference between different options. The roof shapes require a closer look to compare the icons (consider hipped vs. half-hipped, for instance). I haven't tried this new version, so I can't speak to how it works in practice, but I do agree that knowing where the icons were was pretty useful.

**Comment by matkoniecz** [comment]
>  But with this quest all (?) possible answers are shown at once.

I think that `tracktype` one is in a similar situation. I use it very rarely in my region, but I remember being confused by seemingly random order of `grade2`, `grade1`, `grade5` and so on.

**Comment by westnordost** [comment]
Okay, makes sense that the tracktype should not be mixed up. Though for the roof shapes, if you are in an area where half-hipped or hipped or whatever is really common, you would want to have them appear in the front. If the icon is not well distinguishable from others on first sight, then rather the icons should be improved. (Though, in my opinion they are already as clear as they can get. Any suggestions about making them clearer?)

Let's collect all the quests where the items should not be mixed (plus the reasons for that).

**Comment by matkoniecz** [comment]
Needles vs leaves for trees, car wash, crossing type, maybe also poles. There is enough space to display all three, so there is no benefit from switching the order and it is easier to get confused when order keeps changing.

**Comment by pkoby** [comment]
I think the icons for the roof quest are as differentiated as possible, it's just inherent that they're hard to quickly differentiate. I don't know if they could be a range of different colors? But that might suggest further meaning...

I also considered that you could add text (but there's the issue of translation), but that would take up more space in the UI.

In other words, I don't know that they can be improved for clearer differentiation—it's just how it's going to be. And yes, my region has tons of hipped and half-hipped roofs, so it would be nice to have them up top.

**Comment by HolgerJeromin** [comment]
I was not aware that we have more shapes with "show more". This is probably more important.
Feel free to close this issue.

**Comment by hmartink** [comment]
I just wanted to request that roof shapes should be ordered by recent usage. I just went through a an area with untypical roofs and (while raining) had to always tap "show more". Please keep this feature enabled, it is helpful in the field.

**Comment by gmischler** [comment]
a. If certain features are locally common, it is desireable for them to be easily accessible.
b. It is also desireable (less confusing), if the layout doesn't change around all the time.

Maybe there's a compromise to resolve this conflict of interest? In the case of eg. roof shapes, if the selected one is already in the immediately accessible top 8, there is no real point in rearranging the layout, is there? If a "new" one is called up via "show more", then some rearrangement is unavoidable, and the user will be aware to expect a change.

Luxury version? Make it possible to lock certain items in position, which would probably also require the possibility to move them to the most convenient location first. ;)

**Comment by HolgerJeromin** [comment]
> Maybe there's a compromise to resolve this conflict of interest? In the case of eg. roof shapes, if the selected one is already in the immediately accessible top 8, there is no real point in rearranging the layout, is there? If a "new" one is called up via "show more", then some rearrangement is unavoidable, and the user will be aware to expect a change.

Nice idea. Over the time the "fixed layout" would be the most used layout in this area.

> Luxury version? Make it possible to lock certain items in position, which would probably also require the possibility to move them to the most convenient location first. ;)

Hard to find an interface for this rare used feature (look at the target audience of the app).

**Comment by gmischler** [comment]
> Hard to find an interface for this rare used feature 

Android has a standard UI for for this kind of layout management, that every user is familiar with. Long-tap and then move rearranges icons. Long-tap and release without moving gives you a small menu (in our case eg. "lock position"/"release lock").
The unusual part is automatically reshuffling everything. But I think the two concepts can be easily combined.

> (look at the target audience of the app).

Since I'm part of that target audience, I'm not quite sure where you'd like me to look... ;)

**Comment by westnordost** [comment]
Okay, so I will disable the sorting by last selected for the tracktype quest, as @matkoniecz suggested. Also, for all quests that only feature selection options that fit into one line, the sorting will also not occur.

As for the other suggestion by @gmischler: The user is only supposed to give an answer at this point. Having the option to manually re-sort the possible items while the quest form is open is not what the user would expect what he could do in that form. I expect that if this would be implemented, users who accidentally discover this feature will be confused about it and don't know what it means to drag around these pictures. So, I'd rather not add this feature. It would need explanation and that explanation would need to go somewhere etc.

**Comment by RubenKelevra** [comment]
> a. If certain features are locally common, it is desireable for them to be easily accessible.
> b. It is also desireable (less confusing), if the layout doesn't change around all the time.
> 
> Maybe there's a compromise to resolve this conflict of interest? In the case of eg. roof shapes, if the selected one is already in the immediately accessible top 8, there is no real point in rearranging the layout, is there? If a "new" one is called up via "show more", then some rearrangement is unavoidable, and the user will be aware to expect a change.
> 
> Luxury version? Make it possible to lock certain items in position, which would probably also require the possibility to move them to the most convenient location first. ;)

Maybe just have a row with the most recent items with a slight color variation of the background and everything below is static?

Allows for muscle memory clicks for common stuff as well as it integrates the 'uncommon stuff in this area'.

I would plea for changing the algorithm of the 'recent' stuff towards a more static approach, like 'stuff selected most in this session' instead of switching the order every time I open the menu.

**Comment by westnordost** [comment]
I agree that the current algorithm is not really smart, it just puts the last selected item in front. But better than nothing of that sort.

It could certainly be improved. Though the problem with your suggestion is that it would mean that the app forgets this order everytime the app is launched anew. Since individual users will usually be around the same area, i.e. the normal roof shape for that area would be the same.

**Comment by RubenKelevra** [comment]
Okay how about: store the order (and the access numbers) semi-permanently in the cache. If the user gets annoyed with the ordering, we could offer a small x button on the right which just empty the area and counts from 0 again for new items clicked.

If the cache of the app gets wiped by the system or the user the area will be empty again.

All other items will be not sorted at all. 

This should solve all use cases and preferences, right? 🤔

**Comment by westnordost** [comment]
I'd prefer a method that would be smart enough that doesn't require semi-manual configuration by the user. Maybe:

Per session, count the number of times a certain option has been selected. Then, each time the dialog is opened, the first row of items are sorted by the previous selection count. Maybe with a slightly different background color as you suggest.
Then, for persisting, the collected data is reduced like this: Let's say the user selected 27x gabled, 10x hipped, 3x dome and 1xround. Only the order is saved, so gabled, hipped, dome, round. When the data is reloaded into memory (=new app start), it is interpreted like this: 4x gabled, 3x hipped, 2x dome, 1x round. So, the ordering is still the same, but will be changed easier if the user selects different roof sizes where he is now.

**Comment by RubenKelevra** [comment]
That's actually pretty clever. I think that would work very well!

**Comment by RubenKelevra** [comment]
@westnordost just want to make sure:
which feedback is still required? Or is the tag just outdated? 🤔

**Comment by smichel17** [comment]
> Maybe there's a compromise to resolve this conflict of interest?

I like the idea to put recently used choices in a separate, visually distinct section. I also have another idea, that can be implemented independently.

---

Here's the current flow, with the actions: Tap Quest // Scroll Down // Tap "Show More"

<img alt="first" height="350" src="https://user-images.githubusercontent.com/6563664/74357305-be7fde80-4d8d-11ea-9882-2343252fc62e.png"/> <img alt="scroll" height="350" src="https://user-images.githubusercontent.com/6563664/74357308-c0e23880-4d8d-11ea-946d-054160373967.png"/> <img alt="final" height="350" src="https://user-images.githubusercontent.com/6563664/74357314-c2abfc00-4d8d-11ea-965f-5160ef38ce59.png"/>

I don't see why the middle state needs to exist at all, since the act of scrolling is already an indication that I want to see more options; it should move from state 1 to state 3.

The "Show More" button is necessary for the road surface and house type quests because

- The UI changes from flat to nested
- [house type only] the entries are larger, so the recent selections don't all fit on screen.

Neither of these are true for the roof quest, so I think the extra step is not needed.

**Comment by westnordost** [comment]
Right, I guess that could be removed

**Comment by westnordost** [comment]
superceded by #1771 and other changes (removal of show more button etc)

**Comment by Lee-Carre** [comment]
> rather the icons should be improved. (Though, in my opinion they are already as clear as they can get. Any suggestions about making them clearer?)

My first thought was colour, but others have pointed out valid problems with that (and there then might be confusion that it's asking for roof:colour too). Besides, using colour would run into some accessibility issues.

Perhaps adding (graphical) emphasis where similar types differ, so that they're more visually distinct (think in terms of pattern recognition). Else, exaggerating the shape for at-a-glance clarity.

It's a tricky one.

**Comment by Lee-Carre** [comment]
More generally; perhaps a configuration variable to switch between fixed order and MRU order? Obviously defaulting to non-fixed (be that MRU, MFU, or whatever in future).

This is one of those cases, in my experience, which really is down to user preference or user disposition. With no single good answer for all.

Most-commonly-used makes sense as a default, but I can entirely relate to wanting the efficiency of a predictable order.
