### ISSUE TITLE
Doesn't respect metered WiFis

### ISSUE THREAD

**Issue by 101lols** [westnordost/StreetComplete#1699]
The app treats metered WiFis like any other WiFi connection instead of treating them as mobile data.

**How to Reproduce**
1. In settings, change **Auto-sync** to **Only on WiFi**.
1. Connect to a metered WiFi.
1. Answers will get auto synced.

 The [isActiveNetworkMetered](https://developer.android.com/reference/android/net/ConnectivityManager.html#isActiveNetworkMetered()) check is what's missing.

**Comment by westnordost** [comment]
I don't know any metered wifis. Can you give an example what a metered wifi would be, what you encountered?
I could only imagine that some public wifi would be metered because bandwith is so scarce that users should not watch videos, play games and the like. Or does any wifi created through the USB tethering / WiFi hotspot function of a smartphone get this flag? If so, why would you use StreetComplete in such a setup?

Generally the app transfers really very little data in terms of volume. Absolutely not comparable to videos and aside from loading the background map, even much less than browsing a normal website.

So even if this was changed in the app, that metered wifi are treated like a mobile connection might confuse users, depending on what classifies as a metered wifi and what not.

**Comment by HolgerJeromin** [comment]
> I don't know any metered wifis. Can you give an example what a metered wifi would be, what you encountered?

A user can mark any Wifi to be metered. 
I had an LTE router (with limited transfer volume) as an uplink of my LAN while waiting for my fibre working. 

IMO if the app has different sync strategies it should decide from nowifi/wifi but notmetereed/metered.
So 👍 for changing this.

**Comment by 101lols** [comment]
Metered WiFis are WiFi connections with data caps.
Since almost all Google apps treat metered networks as mobile data, it makes an expectation that that's the default.

And most often metered WiFis are going to be mobile hotspots (someone else's mobile data), so it makes some sense to have them treated as mobile data.
