### ISSUE TITLE
New Quest: Offerings of a supermarket (etc.)

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1711]
### General 
I couldn't find an already established tag on this topic, but it would be nice to add one.

I would use a pretty general term, like `offers:xyz=yes/no` which can apply to not only sold goods but also services.

I just like to discuss if it makes sense to write an RFC for this tag, if SC isn't going to implement this it wouldn't really make much sense to implement a new tag.

### Datasource

Instead of baking this into SC, we could update a wiki page from time to time, which holds a table for the data for possible offerings and to which tags they apply (like a shop). This could also hold the questions which the user is asked, which can be translated in the wiki as well.

This table could be placed as a subpage of `Key:offers`.

### Examples

> "Can you get fruits here?"
> "Is here a cheese counter?"
> "Is here a help desk?"
> "Does they offer gift wrapping?"
> "Is here a salad bar?"

### Proposed GUI

Since this would lead to many many questions displayed to a user, I would cut this down, that one user can just answer 2-3 questions and then the quest disappears until the area is refreshed.

Answers: yes/no/unsure

on unsure we just ignore the response and carry on.

**Comment by westnordost** [comment]
If there is no established tag for something, it is unfortunately not suitable for StreetComplete. One of the guidelines says that new tags should not be pushed through StreetComplete.

There are also other things to consider. The guidelines are here: https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

**Comment by RubenKelevra** [comment]
@westnordost I know, that's what I meant with

> I just like to discuss if it makes sense to write an RFC for this tag, if SC isn't going to implement this it wouldn't really make much sense to implement a new tag.

I would write a RFC and open a vote for a new tag on this, if there's interest in adding such a quest to SC.

But if SC won't going to implement this, it's pretty useless IMHO, since it's a thing you would like to map on site, since you can directly check this. And digging through all the possibilities manually also makes not that much sense.

**Comment by westnordost** [comment]
Ah I see. Well, apart from that the tag does not exist yet, there are several problems with it that make me lean towards not including it in StreetComplete:

- This information tends to be not accessible from the street, but there is a (soft) guideline that quests should be *🕵️ Publicly accessible*. So if this was implemented at all, it would need to be disabled by default, just like the diet quests.
- Then, supermarkets very much tend to be part of a supermarket chain. It will be somewhat dependent on to what chain a supermarket belongs if there is a cheese counter, an info desk etc. For example, Aldi will in 99% of times not have a cheese counter, everyone except for convenience stores will have fruits & vegetables, "hypermarkets" such as famila or toom will very often/always have one etc. So, to add this information to individual shops has quite a low information value because the answer will be very very often exactly what one expected it to be. (*💤 No spam* / *💵 Valuable Surveyors* guideline)
- So if such a tagging scheme is invented and approved, it is still new and the guideline that new tags should not be pushed through StreetComplete kind of still applies, at least to the amount that (because surveyor time is valuable, and limited, etc.) the surveyed information should have some *🤷 Useful purpose*. I don't really see that with this. 
- Finally, the idea about an `offers` tagging scheme is rather vague. If you intend to push it as a proposal, I'd suggest to get some input on the idea first on the tagging mailing list or during the discussion phase of a tagging proposal.

**Comment by RubenKelevra** [comment]
@westnordost well, I see that G.M. is quite heavily collecting these kind of data.

I see some use for them: You can just query the database for specific offerings, instead of guessing where something 'might' just be.

I can answer, that there's probably no cheese counters in Aldis and Lidls in my City, but I cannot answer which other supermarket might have one or not.

Especially for people not familiar with an area or a country, this *local knowledge* might not exist, that Aldi has no cheese counters.

I see that it could be quite frustrating to answer every possible combination, that's why I thought about limiting the amount of answers one user could give (in like a month) by just asking 3 random questions and hide the quest afterwards.

---

I guess I wait some days if someone else might have an opinion on that here and think about posting it afterwards on the mailing list.

**Comment by goldfndr** [comment]
[relevant discussion](http://gis.19327.n8.nabble.com/Draft-of-proposal-tag-sells-for-shops-td5869146.html)

**Comment by RubenKelevra** [comment]
@goldfndr thanks, was quite interesting... I think sells is a bad tag TBH, since it wouldn't cover services.

I think we reached a point where it doesn't make much sense to add individual tags for each service or amenities, but better use a general one with sub-tags.

The whole brand discussion exploded a bit, but I saw many good arguments for both sides. There are already brands tagged in OSM, for example for gas stations and fast-food franchises so there's not a strict guideline which forbids brands in the database.

Every time G.M. asks for information about I place I've been, I wonder why there's no way still, how to enter those informations into OSM in a well defined way.
