### ISSUE TITLE
Option to select locale

### ISSUE THREAD

**Issue by egesu** [westnordost/StreetComplete#1714]
**Use case**
I use my phone in en-GB locale. However I enter the names in tr-TR locale which is my native language. The edits I make have locale tag with en-GB value and I cannot change it.

**Proposed Solution**
Can there be an option to select my locale for my edits?

**Comment by westnordost** [comment]
The feature to add this tag to the changeset was discussed in #1674. The locale indicates the locale of the software, not that of the user.

The reason to include the tag was to be able to better track misunderstandings with the user interface in the given locale that led to a tagging error. Because of this, the `locale` tag needs to indicate the language used for the user interface.
