### ISSUE TITLE
Clarity in building type quest (house/garage)

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#1716]
### How do I tag a multi-car garage?

- "Single garage" shows a single garage door and single ridge along the top.
- "Multiple garages" shows three garage doors and three ridges along the top.

It's not clear how I should tag a 2-car garage, with two garage doors (or one very wide one) under a single roof (one ridge).

### Barn hybrids

There are a couple buildings in my area that are old barns, that are no longer on a farm (it has been converted to residential area) and are currently being used as garages or sheds. And one that I believe is a newly-constructed garage, made to look like a barn from the outside. Where is the line for whether I should mark these as a shed/garage or barn?

### Housing

- It's not clear to me exactly when the plain "House" building type should be used. It seems like a catch-all for residential buildings that don't fit any of the more specific labels, but you can already just select "Residential" without being more specific, for that case.
    - The picture looks like it is not attached to any other houses (but is close by). What distinguishes a "house" from a "detached house"?
    - Edit: I've found #25 which seems to have more information, and am reading it now. Maybe I will have wording suggestions after I finish.
- The "Row house" picture shows each of the houses being identical. Should it still be marked as a row house if the format is A-B-B-A (in my case, A's are mostly on the second story while B's are first-story). Or should it be an apartment building? (Or just "House"?)
- How should I mark a building that fits the semi-detached house description, but has 3 homes? The 3rd is larger and sits on the second floor, above the other two, which are rental units — it belongs to a friend of mine.

**Comment by matkoniecz** [comment]
What is your language in SC? Maybe problem is in the translation?

Answering questions (but is there way to improve SC to avoid this question):
> It's not clear to me exactly when the plain "House" building type should be used. It seems like a catch-all for residential buildings that don't fit any of the more specific labels, but you can already just select "Residential" without being more specific, for that case. 

`house` ( https://wiki.openstreetmap.org/wiki/Tag:building%3Dhouse ) is  for buildings constructed for a single family.

`residential` (https://wiki.openstreetmap.org/wiki/Tag:building%3Dresidential) is a general term

> The picture looks like it is not attached to any other houses (but is close by). What distinguishes a "house" from a "detached house"?

House may or may not be attached to other houses. Detached house is not.

**Comment by matkoniecz** [comment]
> There are a couple buildings in my area that are old barns, that are no longer on a farm (it has been converted to residential area) and are currently being used as garages or sheds. And one that I believe is a newly-constructed garage, made to look like a barn from the outside. Where is the line for whether I should mark these as a shed/garage or barn?

Constructed as a barn, converted: tag as a barn

Constructed as a garage, pretending to be a barn converted into garage: tag as a garage

Fortunately, for most purposes barns and garages are extremely similar (both are unlikely to have house number, utility buildings etc).

**Comment by westnordost** [comment]
Hmm, you bring up several issues at once.

# Garages

The wiki says
> A garage is a building suitable for the storage of one or possibly more motor vehicle or similar.

and for garages:

> A building that consists of a number of discrete storage spaces for different owners/tenants.

I understand it this way that "private" garages on the premises of one detached/semi-detached/home are to be tagged `garage`, others, like rented garages for building complexes / apartment complexes are to be tagged `garages`. It is certainly not very sharply defined and IMO it is also not necessary to have a crystal clear definition here.

In any case, the picture fits the description in the wiki quite well. It shows three cause having a garage for two cars / two doors doesn't necessarily mean it is automatically `garages` already. So, in my opinion, with the lack of a clearer definition in the wiki, there is nothing to be done here in StreetComplete.

# Barns 

Well, in OpenStreetMap, you ought to tag as the building what it was constructed as and only additionally tag (if it deviates) what it is currently used for. For example, a church that is now used as an office is tagged `building=church + building:use=office`. 
This tagging is a bit counter-intuitive for surveyors (like you and me) because how is the surveyor supposed to know what any building was constructed as unless is it absolutely obvious.
This is why in StreetComplete, the surveyor is just asked "what type of building" it is, with no hint towards the tagging scheme mentioned above. So when in doubt, the best thing a StreetComplete user can do is to leave a note in which he explains the situation like you did now in this ticket. But even if he just tags the ex-barn as a shed, or the ex-barn as a barn, it is still an added information so I would not say it is wrong. (Because before the building type was not defined at all)

# Houses

Yes, house is a bit a catch-all for buildings in which _a single family_ lives that don't fit into detached, semi-detached etc. Usually, you'd select this option for houses that are built in a row with no garden around like you'd see on a detached or semi-detached. Examples: 
- [Houses in old/medieval/medina neighbourhoods](https://www.goruma.de/sites/default/files/images/article/2018-04/Goslar_Neue_Strasse_1600.jpg)
- Probably [these two manor-like houses](https://www.google.de/maps/@53.5669151,9.9731365,3a,75y,140.64h,94.13t/data=!3m7!1e1!3m5!1s5RfMnIDyVXa0FrZYYB-xIQ!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3D5RfMnIDyVXa0FrZYYB-xIQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D250.67097%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656)

So this is why in the icon, you see other buildings next to the displayed house and in the icon for detached, you see some greenery in front to indicate a garden/premises.

> The "Row house" picture shows each of the houses being identical. Should it still be marked as a row house if the format is A-B-B-A (in my case, A's are mostly on the second story while B's are first-story). Or should it be an apartment building? (Or just "House"?)

If the individual units consist of each one home for a family, I'd tag it as a row house. I would say the most important factor is whether each unit has an own entrance or not (=there is a common stairway). But I don't think it is defined that clearly, in the wiki.

**Comment by matkoniecz** [comment]
And to explain a bit more: OSM tagging is growing organically, used by different people. As result it is always a bit fuzzy on boundaries. Especially in cases where difference is minor (`garage` vs `garages`).

OSM wiki definition is not 100% clear because tag was used by different people applying slightly different definitions. So there is no clearly defined meaning because there is no clear meaning of a given value.

And StreetComplete needs to deal with this fuzziness.

-------

Hopefully that explains your questions? Do you see any way to improve descriptions in StreetComplete to make it more clear?

**Comment by smichel17** [comment]
### Garages

I understand now.

> discrete storage spaces for different owners/tenants

This was the key phrase that clarified it for me.

> It shows three cause having a garage for two cars / two doors doesn't necessarily mean it is automatically garages already.

This is what I *thought*, but was not sure, because the picture for "single garage" does *not* show two cards/doors, only one. I suggest one or both of:

- Modify the picture to show a one-roof, two-door garage
- Add descriptive text to one or both
    - Single: "May have multiple doors"
    - Multiple: "Discrete spaces or owners/tenants"

Probably just adding the "single" text is enough.

(Also, I noted that there's no way to tag whether a house has an *attached* garage; there were a number of buildings that I tagged as "detached house" that have a garage attached, sometimes with a residential room over it, connecting to the house and not the garage).

**Comment by matkoniecz** [comment]
>  noted that there's no way to tag whether a house has an attached garage

Yeah, there is no special way to do that. If someone really wants to record this info: it is possible to map driveways and count how many houses have driveway attached.

Though in case of garage and house that are separate building that are joining (or closely located) I would map them as two separate buildings (reqiures Vespucci or some other editor).

**Comment by smichel17** [comment]
## Barns

I think I get it now but I'm not really sure what to do about it aside from not being afraid to use my best judgement. Maybe make it easier to "Tag with note"? But I think that's probably outside the scope of this issue.

## Houses

> House may or may not be attached to other houses. Detached house is not.

Yes, but there's already several options for houses that are attached (semi-detatched, row house, apartment building). It's unclear to me what situations are left for plain old "House", which is not a problem for *itself*, but it makes me uncertain whether I am tagging *other* buildings correctly or whether I should be tagging them as "House" instead; occasionally this leads to me skipping a building that I would have otherwise tagged.

> in the icon

Okay, I think this was a case where I read too much into the icon and this was confusing me. In it:

- There is a gap between the house in the center (which we are tagging) and the house on the left; they are clearly detached.
- The roof of the house in front overlaps the house on the right, and their baselines are not aligned.

Together, this reminded me more of a tightly-packed neighborhood of detached houses, like [this ](https://www.google.com/maps/@42.3966402,-71.126311,3a,75y,46.1h,89.64t/data=!3m6!1e1!3m4!1s_M_29Wf-8Rf3Rs7mRYkcrQ!2e0!7i16384!8i8192), while "detached house" made me think rural, like [this](https://www.google.com/maps/@42.3259347,-72.6844682,3a,75y,137.68h,85.85t/data=!3m6!1e1!3m4!1sKHCyMAr0V1rdYwZtf0Wn1w!2e0!7i13312!8i6656).

I think I would suggest a tweak to the icon, to align the right house on the same basline as the center, and don't overlap the roof. I can provide a quick pixel-art mockup if that would be helpful.

It might also be helpful to move the "House" menu item between "Semi-detached house" and "Row house", to make clear that in terms of density, it is somewhere in the middle.

**Comment by westnordost** [comment]
> I think I would suggest a tweak to the icon, to align the right house on the same basline as the center, and don't overlap the roof. I can provide a quick pixel-art mockup if that would be helpful.

Yes please, not sure if I understood correctly.

**Comment by smichel17** [comment]
Not sure exactly this, but something like it. I started with just the two suggestions I had but then it looked weird with the side house roof overhanging the main one, so I moved it over too.

![sidebyside](https://user-images.githubusercontent.com/6563664/73620662-e4281d80-4600-11ea-8161-5f335ba6249a.png)

**Comment by westnordost** [comment]
Ah ok, will do.

**Comment by smichel17** [comment]
> How should I mark a building that fits the semi-detached house description, but has 3 homes? The 3rd is larger and sits on the second floor, above the other two, which are rental units — it belongs to a friend of mine.

It seems like it could fit either "Semi-detached house" or "Apartment". It is more like a semi-detached house, in my opinion, since it has separate entrances for all 3 units (although it is possible to move between the units without going outside — one through a door in the foyer, another through the basement). But the description for semi-detached says "pair of two" explicitly.
