### ISSUE TITLE
Improve visibility of house number quest

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#1717]
This is a hopefully-more-actionable duplicate of #1369 and is related to #1121 and #1053/#767/#351.

### Context

**Motivation:** I use OSM-powered applications mainly for navigation/directions while driving. While the actual navigation works quite well, destination selection is still very rough, especially compared to proprietary alternatives. This is often due to lack of OSM data, and therefore **building numbers are one of the data points that I care about most**, just behind road names (and *ahead of lighting, etc*).

**Currently**, however, house number quests do not appear until after you've completed the house type quest, and *that* quest doesn't appear unless you've completed most of the road-related quests and/or zoomed in and refreshed at least once (?)[1]. This is important because I'm not especially interested in filling out "building type" quests[2] and I did not realize they were a pre-requisite for house number quests to appear; as a result, **I did not use streetcomplete in my hometown for around a year, because I didn't realize there were any quests left that I cared about.** Then recently I filled out a bunch of building type quests for fun on a walk and, to my surprise, house number quests appeared the next time I returned to the app.

[1]  It's not completely clear to me what the rules are for getting house type quests to appear, but it's a rather difficult thing to trigger; after clearing the quest cache, it took me maybe 10-20 minutes of intermittently refreshing to get them all to show up again (maybe rate limit related?).
[2] Also because it is a confusing quest (see #1716), so high effort + low interest = low motivation.

### Suggestion(s)

1. **Combine the house number and building type quests.** I am imagining something like:

    - Does this building have a house number? (Y/N)
        - (Y) ⇒ What is the number?
            - ⇒ Building type quest *appears* (can be completed later).
        - (N) => Building type quest *opens* (must be answered now)
           Maybe this can also be allowed to answer later, depending how OSM tags work in this case.

   In this flow, it might also be possible to filter the options in the building type quest (eg, do not show "shed" option for buildings with a house number).

   It might make sense to use both this flow and the current, type-first flow, using some type of heuristic, like building size (eg, type first for small buildings that are likely sheds).

   I expect that this won't work exactly as proposed, because I'm making the suggestion without much knowledge of how OSM tags work (as I've said in the past, I like StreetComplete because it lets me contribute without having to learn the minutia of OSM tagging).

2. **Show an indicator when completing a quest will allow others to appear.** If I knew that filling out house type would cause other quests to appear, I'd probably have done it sooner, even just out of curiosity to see what other quests it might be hiding. This also applies to my initial experience with road surface/lighting/speed limit/etc quests.

   Even better would be the ability to cycle through available quests, since different people care about different things and may not want to put in the effort for all quests… but I understand this is a difficult problem, especially since a simple UI with less important quests filtered out is a key feature.

**Comment by matkoniecz** [comment]
> and that quest doesn't appear unless you've completed most of the road-related quests and/or zoomed in and refreshed at least once (?)[1]

Just quick notes: (1) you can reorder quests (2) for technical info why refreshing is necessary: see https://github.com/westnordost/StreetComplete/issues/1119

**Comment by matkoniecz** [comment]
> I did not use streetcomplete in my hometown for around a year, because I didn't realize there were any quests left that I cared about.

Welcome back! In the last year some new quests appeared, so maybe also some other things are waiting to be solved (depends on what you consider as interesting and data in you area).

**Comment by westnordost** [comment]
This is a very good suggestion. I need to think about how this would be possible to implement.

**Comment by matkoniecz** [comment]
> I need to think about how this would be possible to implement.

Maybe as part of achievements system? After solving N questions (amybe of some type) explain that answering one SC quest may unlock some other SC quests?

**Comment by smichel17** [comment]
What about something like this, as an indicator?

![multiple](https://user-images.githubusercontent.com/6563664/73614027-6694eb00-45c9-11ea-9f56-74be6a2cd70a.png)

**Comment by peternewman** [comment]
> It doesn't show _which_ other quests are there, but this might actually be a feature, since we don't _necessarily_ know which will will come next, as in the case of this issue, where if a building is marked as a shed, the house number quest will not appear.

Pedant: surely if as you've said the other quests may not appear they should be semi-transparent or greyed our or something to indicate/suggest they might vanish.

**Comment by westnordost** [comment]
> What about something like this, as an indicator?

This is not really doable. As you said, there might or might not be a quest unlocked through this. Depending on which tags the element has and which tags the element will have after the question has been answered. Also, especially for users who do not have auto-sync on, it will create more question marks because they'd expect that after the quest is solved, another would appear behind it, as displayed on the map. Even if they are grey/half-transparent.

> Maybe as part of achievements system? After solving N questions (maybe of some type) explain that answering one SC quest may unlock some other SC quests?

@matkoniecz Yes, this is one idea! Please put these kinds of ideas on that wiki page, perhaps as a new headline (since the wiki page is only about the links so far)

**Comment by westnordost** [comment]
So, I thought more about your general idea. Basically it would be realized as a new quest:
- building type known but a housenumber -> AddHousenumber
- no building type known but a housenumber is known -> AddBuildingType
- **new**: neither building type nor housenumber is known -> AddBuildingTypeOrHousenumber

The quest would have about the same importance as the AddHousenumber quest.

This quest would do something new no other quest form has done so far, and that is to show two questions after one another. First a yes / no, then either the housenumber form or the building type form. Additionally, care must be taken that if the user answers no housenumber and then subsequently selects a building type that usually should have a housenumber, `nohousenumber=yes` is tagged on it as well so that the AddHousenumber question is not asked anymore.

So this will be quite a bit of work. 
Maybe the easier solution here would be to move the building type quest up in importance so it appears earlier. The only downside over your proposed solution is that it is not immediately apparent that there is a housenumber quest "behind" the building type quest. On the upside though, users are not forced to enter the building type quest information when they answer "no house number".
Also, if it appears earlier (meaning for many users: at all), it will also become apparent for users, like for you, that there is the housenumber quest "behind" this quest.

**Comment by westnordost** [comment]
Ok so I will just push AddHousenumber up (again)

**Comment by smichel17** [comment]
Can we filter based on the size of a building? If so, what about changing the building number query?

The current query looks something like:
```
number not present && building_type=[$valid_types]
```
I'd propose changing it to:
```
number not present && ( building_type=[$valid_types] || building_size > $small )
```
The idea being that most "no address" answers are probably sheds, so if we can filter out *most* sheds by size, we can show more address quests without showing a bunch of quests that will be answered by "no number".

**Comment by matkoniecz** [comment]
Exclude unreasonably small buildings from building quests #1439 is related

**Comment by smichel17** [comment]
I realized I had a big in my pseudo-filter that may have given the wrong impression. Fixed now.

They are related, but not the same. Maybe a better way to express what I'm looking for here is `building_size ~= "$house-sized"`. It's not about filtering out bad data, but rather selecting some buildings that are likely to be houses even though they are not yet tagged as such.

**Comment by gitka** [comment]
> * **new**: neither building type nor housenumber is known -> AddBuildingTypeOrHousenumber

Thats exactly what I'm searching for. I want to map primary housenumbers, but I didn't found the quest AddBuildingTypeOrHousenumber in my quest-list. Please give me a hint how find it in the german quest-list.

**Comment by matkoniecz** [comment]
There is no such quest. This was probably an idea to add it
