### ISSUE TITLE
Confusion with buildings with addresses on multiple roads

### ISSUE THREAD

**Issue by BudgieInWA** [westnordost/StreetComplete#1728]
I see a lot of Quests in Western Australia that are asking for the housenumber of a large building that that has multiple offices or shops accessible from multiple roads. Imagine a building that takes up the entire block, with four adjacent roads. The building has street addresses on each of the four roads. The housenumber quest does not allow me to indicate that the building has multiple streets (I'm guessing `addr:street`) or which street the building is believed to be on. In this scenario, it seems like tagging the building with a street and housenumber is not sufficient and it is [not settled](https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers) how the situation should be tagged.

The housenumber quest on buildings tagged with a street, should

- tell me which street I am submitting numbers for, and
- give me the option of answering that the building has numbers on multiple streets.

Ideally, quests would be able to add all of the addresses to the perimeter or ways or entrances or whatever, to cover the building.

If a building has neither a street nor a housenumber, it seems like the street(s) would be required first.

---

I am new to StreetComplete and OSM editing, so I am not sure how well StreetComplete supports multiple addresses per building. #213 talks about adding missing `addr:street` tags.

**Comment by westnordost** [comment]
It **is** pretty much settled. In a situation where a building has entrances on multiple streets, one should tag the address of the entrances instead of the building.

But, it is not possible to do this with StreetComplete and would be too much work to implement it. 
So in this case the user must answer "Can't say" and supply the necessary information in prose in a note, best with photos.
There is unfortunately no better way to do it.

**Comment by BudgieInWA** [comment]
Thanks for your feedback and perspective on the correct tagging, that makes sense to me. In this case, I think it turns out that the building is named, which means it does have a single address anyway (with a number of alternative entrances I guess).

I would still like for the existing street name to be displayed within the quest, because the user might unknowingly enter a house number from a different street to the tagged one, which is an error that would be easy to recognize at the time, but might be difficult to spot later. Seeing the street name would also aid in knowing where to go looking for a number.

**Comment by westnordost** [comment]
Usually, the information about the street is not known at this point. First, the housenumbers are recorded, then later the street names

**Comment by westnordost** [comment]
Of course, in a few cases it may already present, though this mapping practice (filling out the street names first and later the housenumbers) is frowned upon by some because it can be assumed that this information has been added from aerial imagery, otherwise the person who added this data would also have added the housenumbers already. In exactly the cases where it is not undoubtedly clear to which street a property belongs (from looking at the aerial view), this data has a very low quality - it's just a guess.

But anyway, if this (possibly unreliable) information would be shown, it has only the potential to mislead the users in the edge cases like those you encountered: Where a building actually has several addresses on multiple roads.

If for such a building, the street name is already recorded, this information would be wrong and thus the user would build on top of wrong information, resulting in that only one of several addresses for that building are recorded in OSM.
And for the normal cases, where one building undoubtedly belongs to one street, that information would be superfluous.

So, as a result: **When in doubt, always leave a note, best with a photo.** This way, you can be sure that you do not enter incorrect information.
