### ISSUE TITLE
GPS is kept on while app is in background

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1729]
Since the update to version 17, GPS remains on until I close the app (i.e. swipe it away in recents).
But if I close the app while it is scanning for quests, GPS stays on even after scanning has finished. The app needs to be opened and closed again to stop GPS.

Street complete 17 (fdroid)
Android 7 (AOKP, based on LineageOS 14.1)
Samsung S4 mini

**Comment by westnordost** [comment]
Ok, the problem was that the one-shot "give me the current location once" call that would result in the GPS icon on the lower right corner to stop blinking was not cancelled on pause.

While fixing this, I also removed the dependency to [LOST](https://github.com/lostzen/lost) because that library is not maintained anymore and anyway has quite a complicated API without offering any advantages over simply using the builtin components.
