### ISSUE TITLE
Responses to AddCarWashType quest should not be exclusive.

### ISSUE THREAD

**Issue by muralito** [westnordost/StreetComplete#1738]
Responses to AddCarWashType should not be exclusive.
I need to answer "Self service" and also that the operator can wash your car.

**Versions affected**
See it v17.

**Comment by Atrate** [comment]
I can make a PR if @westnordost approves

**Comment by westnordost** [comment]
If you like, I'd do it also myself before the next bugfix release. I looked into the wiki, there is now (since a few months) a documentation for `self_service=only` next to `yes` and `no`. So this could be used.

The quest should then tag `automated=*` plus `self_service=*` for the users' multi-answer.
You can do it if you like, but perhaps it is faster if I do it myself.

**Comment by Atrate** [comment]
I'll leave it to you, then
