### ISSUE TITLE
Check for and clear obsolete quests

### ISSUE THREAD

**Issue by afranke** [westnordost/StreetComplete#1750]
I loaded nearby quests and got two about opening times for a nearby shops. Upon closer inspection I noticed that one of the two shops is a new point with the new name for the old one (i.e. instead of renaming an existing shop, someone added a second shop). I went to osm.org on my desktop and fixed the situation, but now Street complete is still showing me the two quests.

I expect Street complete to find out about the removed point and make the quests accurate.

**Comment by matkoniecz** [comment]
> I expect Street complete to find out about the removed point and make the quests accurate.

It will happen once StreetComplete will scan for this quest type in this area again. 

When it will happen?

- Once quests will be old
- Or StreetComplete will run into edit conflict in this area (what indicates that also other map data is likely to be changed)
- Or you triggered this manually in settings.

------

In this situation I usually hide quests that I solved in external editor (I typically use Vespucci)

-----

Why it is not changed immediately? Because running overpass queries all the time would be costly (in various ways) for little benefit.

**Comment by afranke** [comment]
Fair enough. I should mention I did request more quests for the area and I was expecting the obsolete quest to be gone at that point, but I can see the overhead.

**Comment by westnordost** [comment]
Quests are only downloaded on a quest-by-quest basis. So, the quests of one quest type that are marked as "old" are only cleared when the that quest type is downloaded again. Depending on the position of the quest type in the download queue (the importance of the quest type), it can take some time until the app reaches this point again.
