### ISSUE TITLE
Import and display GPX track

### ISSUE THREAD

**Issue by hferee** [westnordost/StreetComplete#1757]
**Use case**
Very often, I use streetcomplete in places I don't know, while going from point A to point B (because around the places I know, there aren't so many quests left ;-)). For this reason, I often need to use a navigation app (OSMand of course) to find my way. It means that I have to go back and forth between the navigation app and SC to find my way and fill quests at the same time.

**Proposed Solution**
My suggestion is to be able to:
* use your favorite navigation app to compute a route
* export it to a standard format (say GPX or geoJSON)
* import it in SC (the last two steps can be achieved using android sharing feature), which would display it

**Implementation Details**

* tangram-es is able to display geoJSON, it seems the simplest way to go. I can provide a basic GPX to geoJSON conversion tool.
* only the latest import should be displayed (to avoid a messy map or a complex interface to handle them)
* a menu item would have to be added to import manually a gpx file, or choose not to display the last imported one.
* a size limit can be imposed if this poses rendering issues.
* bonus: the path could be oriented (with little arrows), to show which way to go.
* bonus*: the map could be oriented to follow the direction of the path (as long as the gps location is somewhere along it). This is useful for devices where the compass is too shaky (my case).

**Comment by westnordost** [comment]
Hm, this is quite a specific use case and proposed solution. The proposed solution itself is so complicated and specific, that it probably wouldn't be used much. Exporting and importing routes also has the prerequisite that your navigation app even supports exporting a computed route.

I understand the problem of switching back and forth between apps, it can be disruptive. Obviously, the best solution for this use case would be that StreetComplete is no own app at all, but comes as a plugin for your favorite navigation app. I think this has been suggested before. This would solve your use case. However, this is nothing I plan to do, mainly because it is not exactly a low hanging fruit in terms of effort - not even sure if it is possible at all.

Regarding whether I would accept a PR that implements that feature: I am not entirely sure, but the function would need to be activateable from a place in the UI where it doesn't obstruct the "normal" functions and may confuse users. To put it into the menu (upper right corner) would be too prominent in my opinion.
I plan to redesign the UI of the main screen, maybe in the future there will be a place where to unobtrusively put such an "advanced" function. For now, I'll close this ticket.

**Comment by mnalis** [comment]
- ref. https://github.com/streetcomplete/StreetComplete/discussions/5345, https://github.com/streetcomplete/StreetComplete/discussions/3898, https://github.com/streetcomplete/StreetComplete/issues/473
