### ISSUE TITLE
User confused about how to tag surface "oil-bound macadam"

### ISSUE THREAD

**Issue by AndrewKvalheim** [westnordost/StreetComplete#1762]
A StreetComplete user left a [note](https://www.openstreetmap.org/note/2114514) indicating that none of the available choices for street surface applied:

> street surface is oil-bound macadam, which is similar to asphalt but not the same, particularly when recently refreshed

Perhaps the application could offer additional guidance about how to tag this type of surface.

**Comment by westnordost** [comment]
First we need to find out how this should be tagged according to OSM wiki. (I suspect, asphalt?)

**Comment by ferdinand0101** [comment]
I just looked it up and macadam is used around 50 times on taginfo for roads

**Comment by westnordost** [comment]
So, `surface=compacted` is described as "aka water-bound macadam". 

Then there is [_tarmac_](https://en.wikipedia.org/wiki/Tarmacadam) (tar bound macadam) whose name according to the wikipedia is often used for asphalt etc. as well
> While the specific tarmac pavement is not common in some countries today, many people use the word to refer to generic paved areas at airports,[4] especially the apron near airport terminals, although these areas are often made of concrete. Similarly in the UK the word "tarmac" is much more commonly used by the public when referring to asphalt concrete. 

The reason will be that it looks similar and is also similarly smooth. So being no experts, most people  would tag tarmac as asphalt. My guess is that the vaaaast majority of tar-bound macadam surfaces are tagged as asphalt. I guess technically, it is not correct, but mappers tag what they see.

If in the future OSM contributors want to drill further down in detail regarding road surfaces, I'd say the different types of macadam (and different types of asphalt, asphalt concrete etc etc) must be subtags. But we are far from that anyway.

**So, my advice for mappers how to tag tarmac or any other variety of macadam would be:
If it looks and behaves like asphalt, it is `asphalt`. If it looks and behaves like water-bound macadam / compacted surface, it is `compacted`.**

I have no idea how the wording could be refined to make that clear though, since macadam doesn't seem to clearly fall either into `asphalt` or `compacted` category.

**Comment by westnordost** [comment]
I closed the related note, I think there is nothing to do regarding the app.

**Comment by peternewman** [comment]
I must admit in the UK I thought tarmac==asphalt and had translated the key as such. Someone had gone and defaulted it back to the tag name, as they wanted to see the raw one, but clearly there has to be a sensible limit to that with e.g. soccer/football and mail box/post box.

**Comment by smichel17** [comment]
> soccer/football

As an American who understands we're not the only country in the world, the tag ought to be football. "Soccer" is an en_US localization :P

**Comment by peternewman** [comment]
> As an American who understands we're not the only country in the world, the tag ought to be football. "Soccer" is an en_US localization :P

Although at least that is globally unambiguous, everyone knows what you mean, whereas football would potentially bring American Football type confusion into it. In the same way as the potential confusion with chips/crisps/fries, everyone knows what fries are. Or pants/trousers, no-one misunderstands trousers.
