### ISSUE TITLE
Take in consideration COVID19 tags

### ISSUE THREAD

**Issue by yopaseopor** [westnordost/StreetComplete#1774]
Hi!
As you know COVID19 is isolating our lives.
This make us act to help the community .
One project called Ça Reste Ouvert (http://caresteouvert.ft) shows us all the shops are opned during this pandemia time.
It would be interesting to can edit via StreetComplete the information with these tags

opening_hours:covid19=same
opening_hours:covid19=open
opening_hours:covid19=off
opening_hours:covid19=restricted	
opening_hours:covid19=*

description:covid19=*
delivery:covid19=yes/no
takeaway:covid19=only
note:covid19=*

**Comment by westnordost** [comment]
I am not opposed to this and would accept a PR for adding opening hours info for covid19 and as a follow-up quest, add whether a restaurant offers delivery and/or takeaway during these times. If anyone wants to do this, I will put this on the "fast lane" (would be released as v18.1, will review PR very quickly, will draw icons if necessary)

Though, I will probably not work on it myself because 
- http://caresteouvert.ft/ not only displays the data but already offers a super-easy way to enter this data, there is little need for another client to support this, in my opinion
- the lockdowns will probably stay in effect for at most a month or so. For such a short time in-effect, I'd rather spend the time on other things in this app

**Comment by westnordost** [comment]
I looked into creating a quest for this after all, but then had another look at what information is recorded through the website.
And I must say, it's just better than an implementation in StreetComplete would be. *All* relevant information is recorded in one go, super easy, no OSM login required, and it's mobile friendly.

![image](https://user-images.githubusercontent.com/4661658/78988547-86004500-7b31-11ea-980e-69bcdb6d3229.png)

Furthermore, as a convenience, when a change of opening hours is reported, the current opening hours are taken as a base. This is not possible yet in StreetComplete, as @matkoniecz PR that implements that feature https://github.com/westnordost/StreetComplete/pull/1676 is still not done.

Also, I am a bit offish toward the thought of encouraging users to go outside and solve a lot of quests during this time, since the COVID-19 quests would certainly not be the only quests users would solve then.

**Comment by westnordost** [comment]
So, having though about it, I'll not implement  this for StreetComplete. It is better to use http://caresteouvert.ft/

**Comment by goldfndr** [comment]
For anyone seeking this site, it's [in France](https://www.caresteouvert.fr/). (The FT country code [is unused](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Current_codes)).

**Comment by HolgerJeromin** [comment]
There is an android app:
https://github.com/osmontrouge/caresteouvert_android

**Comment by TheAdventurer64** [comment]
Excuse me, but the site is down.

**Comment by thibaultmol** [comment]
Unless I'm mistaken but this site only works for France (def doesn't work in Belgium for me) @westnordost

**Comment by yopaseopor** [comment]
It is working in Germany, Austria, Switzerland, Spain, Andorra and France.
You can see it at https://www.caresteouvert.fr
Also it is available in : French, English, German, Catalan, Galician,
Basque, Breton, Spanish, Italian, Dutch, Finnish, Swedish, Filipino,
Japanese and Brasilian

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by georg-d** [comment]
@westnordost The decision from April 2020 was well understandable, but the situation changed massively: The web sites https://www.caresteouvert.fr and https://www.bleibtoffen.at/ are offline, the associated app shows the same notification. At the same time, we as OSM community would need some way to map the tags related to corona easily and on the go: In Germany, we have the next lock down during November. Some restaurants are closed till 2020-11-30, some offer take away, many have not the usual but temporary opening times, and these change within few weeks (=need for re-check). Personally, I do expect another lock down after christmas & new year's holiday, because many people do usually meet indoors and for long time. Similar for easter holidays in eastern Europe. 
=> How do you consider the current situation and adding corona tags into StreetComplete?

**Comment by westnordost** [comment]
Same as before, really. If it makes sense to record this information, then through https://www.caresteouvert.fr/ . If they closed the website, they will have good reasons for it. https://www.caresteouvert.fr/ is also the only data user of this data, so it wouldn't make sense to record data that is not being displayed anywhere.

**Comment by thibaultmol** [comment]
You could make the case that we simply don't know if those tags are being
used. I wouldn't be surprised if there are municipalities that have a
website with all their businesses and shops. And use those tags to display
the opening hours for example

**Comment by HolgerJeromin** [comment]
> https://www.caresteouvert.fr/ is also the only data user of this data

Osmand shows it too: https://github.com/osmandapp/Osmand/issues/8742
But I this data is IMO too volatile to tag. 
This app can not decide how often this should be resurveyed.
We had too many very different times in the past even in germany:
* march till june
* again in july if you live in Kreis Gütersloh (I do :-) 
* kind of new "normality" till october
* partial lockdown (restaurant, but no shops) in nov
* december??

**Comment by TheAdventurer64** [comment]
I live in the US.

**Comment by georg-d** [comment]
@HolgerJeromin I do agree it's extremely difficult to add a resurvey trigger to StreetComplete, because too many regions have specific date ranges and POI owners doe change not only at start & end date of a regulation but also in the middle. At the same time, _because_ the data is so volatile, being pro-actively asked whether it's still correct would be helpful to keep it up to date. This "keeping up to date" is impossible in OsmAnd due to offline and thus slightly outdated data. A tricky combination.

@TheAdventurer64 I do not get the context / meaning of your post. What influence does the region have on tagging [Covid19 tags](https://wiki.openstreetmap.org/wiki/COVID-19_-_How_to_Map)?

**Comment by yopaseopor** [comment]
You can do that with Mapcomplete COVID19 quest 
https://pietervdvn.github.io/MapComplete/index.html?userlayout=wiki:MapComplete%2Fcovid

**Comment by Bibi56** [comment]
> he web sites https://www.caresteouvert.fr and https://www.bleibtoffen.at/ are offline, the associated app shows the same notification.

@ westnordost No, not anymore, https://www.caresteouvert.fr is back (and the app too). All countries variants may be back depending on the need (and possibly finance), the lock-down season 2 is active in France.
