### ISSUE TITLE
Allow upload of photos to Mapillary

### ISSUE THREAD

**Issue by cbeddow** [westnordost/StreetComplete#1780]
**Use case**
When a user snaps a photo when making a note, it could be useful to give the user the option to upload this photo to Mapillary so it is preserved in the long term. For example, when I take a photo of a fire hydrant and add a note about its location, I then go to iD editor and find the note, add the fire hydrant, and the photo is then discarded when I resolve the note. I may want to keep the photo available for future evidence or reference, so if it is already geocoded I could then have a quick login + upload to Mapillary option.

**Proposed Solution**
I propose having an option in the settings under `Advanced` with a toggle of `Upload note images to Mapillary` with subtext `Requires login to Mapillary` and a button to login. 

Once logged in, the user's token is saved. Then each time a note is created, when the user tap's `ok` to upload the note to OSM, it would also send the images to Mapillary's upload API.

Alternatively, there could just be a username on Mapillary called `streetcomplete` which all users of StreetComplete upload their photos to. Other apps such as Roadroid do exactly this, so the StreetComplete user remains anonymous and also has no need to log in. The token for this username can be stored in the code.

This could use the quickstart guide for Mapillary Android SDK: https://android-releases.mapillary.com/sdk/Mapillary_SDK_Quick%20start%20guide.pdf

And the full guide: https://android-releases.mapillary.io/sdk/docs/index.html

**Comment by westnordost** [comment]
You work at Mapillary, right? Is it even desired that single photos are added to Mapillary rather than a track of street side photos?

Keep in mind that StreetComplete photos are used to prove/clarify information given in a note, not to provide street side photos. If the note is no more, the context is missing. Photos taken with StreetComplete usually contain not a panorama or even the whole street side, but just a tiny detail, such as an opening hours plate, a single housenumber, a photo that only shows the feet of the photographer standing on the pavement (to show what the surface is made of) and similar shots. I fear that this would create more garbage/noise in Mapillary than it adds benefit.

Another issue here is how to treat privacy. Since notes are quite temporary and as said, should only contain certain details in the first place, I refrained from requiring the user to pixelize privacy-related areas such as faces or numberplates. It would become necessary if uploaded to Mapillary because the photo stays there forever.

**Comment by HolgerJeromin** [comment]
faces and numberplates are blured by mapillary itself.
But we should not auto upload every notes image, but opt in. 
I switched from SC to mapillary to take this image: https://www.mapillary.com/app/?lat=51.84046348786952&lng=8.476888863914374&z=17&pKey=bGJfZ3x2dsMTWkszoEXEew&focus=photo for documenting a quest.

**Comment by westnordost** [comment]
Okay, and switching to the Mapillary app is not that hard, and there is the option to "Open this location in another app".

These wild white flowers look like they are garlic mustard. Did you know, the leaves can be used as spice, for a salad, or on top of a pizza and such.

**Comment by cbeddow** [comment]
Hello! Sorry I had missed this last month. Yes overall I think this is maybe a different issue. I am thinking of a good place to store useful photos of details (rather than street scenes like Mapillary), in case the user choose not to discard it. It may be an idea I work on later this year, let's see. The European Water Project is developing a similar idea which looks to link Mapillary and OSM via single photos.
