### ISSUE TITLE
[New quest] Automatic doors key and COVID19

### ISSUE THREAD

**Issue by bekreyev** [westnordost/StreetComplete#1785]
I think during the COVID19 pandemic very interesting do not touch something by hands. For example, not open the door of a store or shopping center by the handle. Naturally, you want to go to a place where the door is automatic and you don't need to touch it.
And the OSM has a key for this - [automatic_door](https://wiki.openstreetmap.org/wiki/Proposed_features/Key:automatic_door).

I suggest adding such a quest (preferably with an image of door options) to Street Complete.

Automatic doors are doors that are operated button operated, by user detection (Camera, Infrared sensor, floor pressure detection) or that are turning all the time.

Automatic opening on user detection
**automatic_door=motion** The door opens when a sensor detects motion in front of the door.
**automatic_door=floor** The door opens to pressure on the floor in front of the door.

Button operated
**automatic_door=button**

Turning all the time
**automatic_door=continuous**

Turning all the time, Button to slow down
**automatic_door=slowdown_button**

Common combinations
entrance=*
door=*
wheelchair=*

**Comment by westnordost** [comment]
Hm, I am not really convinced that automatic door is an information worth recording.

1. It is only a proposed feature and has not been voted upon yet
2. It is not really used much yet
3. It is to be tagged on `entrance=*` nodes. So your argument that it can help to only find stores that have these automatic doors is kind of invalid cause the vaaaast majority of shops do not have an entrance node tagged on their outline. Those that do are usually big shopping centres and "hypermarkets" where the answer to the question would practically always be yes because they have automatic doors so you can enter with a shopping cart.
4. P.S: And then you touched the handles of the shopping cart. -> There could be the virus on the handles as well. So I do not think it is valid to argue for the usefulness of the tag with COVID-19.
