### ISSUE TITLE
Star counter is inconsistent

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1803]
I've opened the app after the update, and it showed like 1400 stars.

I wiped the data from the app and did a fresh login and ended up with ~3200 stars.

I wiped the data again and did a login and ended up with ~5500 stars.

I did just a logout and a login and ended up with 9200 stars.

Shouldn't it always be the same on the same account? 🤔

**Comment by westnordost** [comment]
Wat.

Yes, it should. Can you tell me your OSM user account?

**Comment by westnordost** [comment]
Ok I researched it. 9198 is actually your proper star count. Congratulations!

Each time you reinstalled the app and did a login, StreetComplete asked the backend "ok, what's my star count now?". The backend was during that time still analyzing your changeset history, so it was each answering the app what it got so far.

The logic in the app is that it will take and display the star count to the user if the last-update-date of the information from the backend is newer or equal to the local last-update-date. Since you reinstalled the app, the app had no last-update-date at all, so it displayed whatever it got from the backend even though it was old data.

**Comment by westnordost** [comment]
So it's not a bug, but obviously the behavior can be confusing. Any suggestions how else it should behave?

**Comment by westnordost** [comment]
The app could never take the backend's data as long as it is obviously incomplete. (Obviously incomplete = backend is still analyzing the history). Would that be better?

**Comment by HolgerJeromin** [comment]
Yes. Now you never now when you can trust the number or it is still rising.
Does the backend working in the background or have the app to be in foreground? Not really clear.

**Comment by westnordost** [comment]
In the background, but the app can query the current ("so far") star count anytime.

**Comment by RubenKelevra** [comment]
How about just showing a loading symbol like the typical android circle behind the number if the number isn't fully calculated?

**Comment by westnordost** [comment]
Because it makes it look like the user just has to wait on this screen and something will show up. In reality, the changeset analyzing can take a much longer time. Usually it is done after max one hour, but there are exceptions. Especially if many people query for their statistics at the same time.

**Comment by westnordost** [comment]
So I added a text in that place. If it is synchronizing (or in waiting queue for synchronizing), it will show something like "still synchronizing, return to this screen later"

**Comment by RubenKelevra** [comment]
Thanks for the clarification. This makes sense. :)
