### ISSUE TITLE
Screenshots contain a weird character

### ISSUE THREAD

**Issue by Helium314** [westnordost/StreetComplete#1809]
Android (at least some versions) put the app name in the screenshot file name.
In StreetComplete, but no other app I have some strange character between "Street" and "Complete":

`Screenshot_20200501-165242_Street�Complete`

I don't remember having something like this in previous versions of StreetCmplete, but I am really not sure about this.
It might also be some problem with my system instead of StreetComplete...

SteetComplete 19 (fdroid)
AOKP Pie (Lineage 16.0 based)
S4 Mini

**Comment by westnordost** [comment]
That's a soft hyphen. Don't know what your Android system makes out of it, but if it is above API level 18, it should actually understand it.
Maybe whatever app you are using to look at the filenames of the screenshots has some problem. In any case, that's rather either a problem of the system or the app you are using to look a the screenshots, not of StreetComplete, since it is not StreetComplete which makes or saves the screenshot.
