### ISSUE TITLE
Creating a note leaves the selected quest marker stuck onscreen

### ISSUE THREAD

**Issue by peternewman** [westnordost/StreetComplete#1820]
Creating a note leaves the selected quest marker stuck onscreen

**How to Reproduce**
Create a note, note (excuse the pun) how the blue ring remains onscreen

**Versions affected**
Android 9.0 SC v19.1

**Comment by westnordost** [comment]
Actually the normal context menu should not open when a bottom sheet is open.

**Comment by peternewman** [comment]
> Actually the normal context menu should not open when a bottom sheet is open.

Sorry, I probably didn't explain very well. After you've created a note, the ring is left present onscreen.

**Comment by westnordost** [comment]
I understood you right. I started to implement that the app behaves correctly when going directly from an open quest form to a note but stopped and chose this solution because the control over the map should belong to the bottom sheet when it is open.

Am 9. Mai 2020 10:01:52 MESZ schrieb Peter Newman <notifications@github.com>:
>> Actually the normal context menu should not open when a bottom sheet
>is open.
>
>Sorry, I probably didn't explain very well. After you've created a
>note, the ring is left present onscreen.

**Comment by peternewman** [comment]
I don't think this was when I had a quest form open, just when I pressed and held to add an independent note (e.g. of something I spotted I wanted to add to the map).

**Comment by westnordost** [comment]
Yes actually it was not properly fixed. It is now.
