### ISSUE TITLE
Ask all questions for an object, for that way user not have to selected it twice or more. 

### ISSUE THREAD

**Issue by dobriseb** [westnordost/StreetComplete#1826]
**Use case**
When I answered the question "Is it restricted who may park here?" it's regularly happened that the questions "Does it cost a fee to park here?" and "What kind of Parking is this ?" appear on the same Parking.
So what I have to do is :
1 Select a parking,
2 Choose if it's public, for customers or private
3 validate
4 select the same parking,
5 answer yes or no
6 select the same parking again
7 select the kind,
8 validate.

What I suggest is to have this way to do the same:
1 Select a parking,
2 Choose if it's public, for customers or private,
3 answer yes or at to the second question "Does it cost a fee to park here?"
4 select the kind,
5 validate.

5 actions instead off 8.

This case also happens for "What surface does this piece of road have?" which is almost always followed by "Is this section of road lit?".
And "What was this building constructed as?" followed by "How many levels does this building have?"
...

**Proposed Solution**
When a quest is selected, all questions related to the item should be displayed, with a swap mode to go to next question.
Or, when the first question is awswered display the second one...

**Comment by smichel17** [comment]
I'm pretty sure this has been suggested before, although I don't have time to search around and find the duplicates right now.

**Comment by matkoniecz** [comment]
See #1510

**Comment by westnordost** [comment]
This is intentional. It is how the app is designed. The questions are asked always as atomic as possible, so that
1. both the form can be easier and doesn't have to take into account maybe already half-filled-out-data (f.e. parking type is known, but not whether it is public, or the other way round)
2. also when not dealing with several data points at the same time, it is easier to resolve conflicts when they occur
3. The time to commit/send the answer to OSM is cut as short as possible

I know that this is not the most efficient way. Most efficient would be to present to the user all the questions related to one quest type at once, so he'd fill out a small questionaire of some sort. But the design goal of StreetComplete is not maximum efficiency. JOSM, Vespucci etc. are efficient, they present all the properties of the selected feature at once in a table and you can all change them at once.

**Comment by westnordost** [comment]
By the way, cool app you got there, have to check it out!

**Comment by dobriseb** [comment]
Thanks for these answers and the application.
May I suggest to group neighbour objects with the same quests (For examples all lines of a roundabout) ?
Or will the answer will be the same ?

**Comment by westnordost** [comment]
What do you mean with group?

**Comment by dobriseb** [comment]
![Screenshot_20200514-182829](https://user-images.githubusercontent.com/35341017/81960468-4ab1d400-9611-11ea-82ef-70fc7fb09ea6.jpg)
On the Screenshot, the 4 (may be more) icons about "What surface does this piece of road have?" concerne the same roundabout and the same answer has to be given.
In this case a groupement means have only 1 quest for all the lines that compose the roundabout.

**Comment by westnordost** [comment]
Ah, well this is not possible, for two reasons:
- There is no notion of "what belongs together" in OSM, if at all, it is something that can be determined fuzzily (i.e. "has same name?" -> probably same street)
- There is always the possibility that the property is actually different for parts of the same road

**Comment by dobriseb** [comment]
Thanks
