### ISSUE TITLE
Custom style for map

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#183]
From the screenshots of your [used lib](https://github.com/tangrams/tangram-es) I see it also supports showing the height of buildings in a 3d view, so why not use that?

**Comment by westnordost** [comment]
No reason other than time. At the moment, I am using a standard stylesheet. To create a custom stylesheet is very powerful, you can style any part of the map, even with shaders (have you seen the tron stylesheet on their website?). But it is a lot of work. Stylesheets are about 4000 lines of code.

There are some cool things that can be done when this app has its own stylesheet, 3d buildings is one of them. But at the moment, I do not want to begin this undertaking as there are more pressing things to do.
If you are interested, [you could play around](https://mapzen.com/tangram/play/), learn how to create those stylesheets and contribute this to this project.

**Comment by westnordost** [comment]
Actually, a StreetComplete related stylesheet could probably be much simpler than 4k lines of code as many things are not necessary at all
- no POIs are shown on the SC map
- no elements are shown that have no relation to the quests
- only things need to be shown that matter on the survey (on foot), i.e. colored distinctions between different roads (major, minor,...) are not necessary
- low zoom levels (i.e. zoom < 12 or similar) don't matter / can be disabled

So it might not be *that* much work.

Are you interested? (or anyone else who is reading this)

**Comment by rugk** [comment]
That's interesting. I think the Tron style is only useful for a "night/dark/black mode" of the app, as it should be light by default, but are not there some other nice templates you can use?
Of course one can also design a custom style, but actually I already liked [the left style in their screenshot](https://cdn.rawgit.com/tangrams/tangram-es/203c9d2f/images/screenshot.png) very much, so maybe you can get a style for it.

**Comment by HolgerJeromin** [comment]
It would be very helpful to have housenumbers shown. Without a good GPS it is difficult to orientate.

**Comment by rugk** [comment]
I think that's tracked in https://github.com/westnordost/StreetComplete/issues/162.

**Comment by HolgerJeromin** [comment]
Thanks!

**Comment by ENT8R** [comment]
I played a little bit around and created a custom stylesheet! You can look at it here: https://mapzen.com/tangram/view/?api=64617/1161 It looks very similar to Pokemon Go and has only about 200 lines of code. It can also be very easily extended. It would be great if you tell me what you think about it!

**Comment by matkoniecz** [comment]
I have my own style. It is unfinished - in part because I wait for mapzen deploying my changes - but it may be usable (after removing some unwanted features, like displaying bicycle parkings) and almost certainly it is a better base than 4k cinnabar mammoth.

https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/my-style.yaml

**Comment by matkoniecz** [comment]
> low zoom levels (i.e. zoom < 12 or similar) don't matter / can be disabled

I would not go so far. Sometimes GPS is unavailable or extremely stupid, so ability to move to a correct country is useful. Sometimes it is also useful to download on WiFi locations that are far, far away.

**Comment by matkoniecz** [comment]
> I played a little bit around and created a custom stylesheet!

Can you link also style itself?

**Comment by ENT8R** [comment]
Here is the link: https://gist.github.com/ENT8R/0a8c03d896eb75d4729133d300b0db41

**Comment by westnordost** [comment]
@ENT8R, I really like what you did there. You both made it look very simple and also tried to copy the playful color theme of Pokemon Go (I guess?) but also already included information that is helpful for StreetComplete users, the housenumbers - and these, quite prominently. If the actual code is as simple as the style looks, then it is a very good starting point for a custom style.

I know that at least @matkoniecz and @Teester already played around a bit but I was not aware of any outcome. Mateusz's seems to have tackled the custom style from the other end: Dumbing down the default (cinnabar) style and keep what may be useful for StreetComplete (users).

Perhaps @ENT8R could create an own repository that links directly to a tangram play page for trying it out and invite people who are interested in contributing to the style there so that not everyone does their own thing but everyone can work together. I think this is better than me governing over PRs because obviously I will not be the (main) developer of a custom SC stylesheet, at least not while it is in development.

**Comment by westnordost** [comment]
@rugk [did a similar thing when he took care of collecting the metadata for the orchard-produce quest](https://github.com/rugk/crops-parser).

**Comment by matkoniecz** [comment]
> I know that at least @matkoniecz and @Teester already played around a bit but I was not aware of any outcome

https://mapzen.com/tangram/view/?api=53844/1163#16.75/50.07262/19.93250 (slightly simplified version of https://github.com/matkoniecz/Zazolc/blob/fork/app/src/main/assets/my-style.yaml )

**Comment by ENT8R** [comment]
> Perhaps @ENT8R could create an own repository that links directly to a tangram play page

Yes I can do that! I will do that tomorrow

**Comment by matkoniecz** [comment]
> playful color theme of Pokemon Go

Maybe it is just me but this colour scheme is really straining my eyes.

@ENT8R It may be a good idea to document what is deliberately omitted. For example, maybe some things that I personally think that are missing are omitted deliberately? 

From quick look it would include: barriers (fences, hedges, railway tracks) and labels (for street names and water features), rendering rivers/stream mapped only as lines, smarter labels (displaying labels of major cities larger than ones for tiny villages).

**Comment by ENT8R** [comment]
Yes, I think we can track it in the issue tracker of the new repository.

**Comment by ENT8R** [comment]
I created a new repository at https://github.com/ENT8R/streetcomplete-mapstyle
Feel free to contribute!

**Comment by matkoniecz** [comment]
I posted some issues, after appearance of license file and sign that copying some features from my style is considered as a good idea I will make PRs.

**Comment by wambacher** [comment]
any news about official or private stylesheets? 
would like to see landuse in('residential','commercial','retail' and 'industrial') all with the same color to see the difference to e.g. farmland. At the moment all have the same color, so i can't see what's "inside" a city and what's "outside"

**Comment by ENT8R** [comment]
@wambacher we are working on it. Have you seen the repository at https://github.com/ENT8R/streetcomplete-mapstyle ? There you can see the progress and open an issue for your problem!
