### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#1831]
The old icon is old, boring and does not conform to the current app icon design guidelines anymore anyway.
Does someone have ideas or maybe even mockups for a new icon?

**Comment by smichel17** [comment]
> The old icon is old

Old doesn't mean bad!

> does not conform to the current app icon design guidelines anymore anyway.

Anything wrong besides it not being adaptive (which is a fairly easy fix)?

tbh, it feels like Google changes their design guidelines in one aspect or another every couple of months, anyway, so I wouldn't put too much stock in them anyway, unless you separately agree that it's an improvement.

> boring

Okay, that's valid, although I think the current icon is not ugly and does a good enough job at being distinctive -- we wouldn't want to lose those qualities in a new icon.

---

The only thing I can think of is to somehow incorporate the "quest pin" shape into the icon, since that's the distinctive feature of SC compared to other mapping applications. But, branding is not my forte, so take it with a grain of salt :)

**Comment by westnordost** [comment]
Yes, it not being adaptive and I am not sure but I think I read something about that there may not be transparent areas in it anymore. Sounds really stupid, maybe I misunderstood.

I was thinking of maybe using this guy here as https://www.openstreetmap.org/user/new an icon, holding a magnifying glass or something.

You know, back in 2016 when I thought up the concept of this app and when the working name of the project was still _osmagent_, I drew this in GIMP:
![Untitled](https://user-images.githubusercontent.com/4661658/82049832-5a83f380-96b7-11ea-845e-703d1856adc2.png)

**Comment by smichel17** [comment]
Super rough draft at combining those ideas

![logo_draft](https://user-images.githubusercontent.com/6563664/82051838-a10e2980-9688-11ea-82f2-a251a34bf428.png)

**Comment by westnordost** [comment]
Hmm, interesting. Is this a speechbubble, or a pin?

**Comment by smichel17** [comment]
Intended as a speech bubble. Not a proposal, just to see what it would look like.

**Comment by dAnjou** [comment]
I actually really like the current icon.

**Comment by westnordost** [comment]
Anyone who commented on this said he liked the icon, so the idea is ditched for now
