### ISSUE TITLE
[discussion] wider use of check_date

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1836]
Currently we tag what's changed in the description field of the changeset.

This gives clear information when a tag was added and that it was surveyed, but this information is only stored in the history.

Usually data consumers doesn't use the history at all, since this would inflate the amount of data necessary to store the informations.

There are many considerations to do resurveying in the future, so I think it makes sense to add the `key:check_date = date` additionally to the data added by SC.

This allows for much simpler querying in the future for outdated tags which needs to revalidated, like we do with the construction tag today.

**Comment by westnordost** [comment]
It is possible but not strictly necessary to implement [map maintenance quests]((https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete).
The construction-quests also do not always tag the check date, but only if nothing changed. I'd plan to do something similar for other maintenance-quests.

**Comment by RubenKelevra** [comment]
> It is possible but not strictly necessary to implement [map maintenance quests]((https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete).
> The construction-quests also do not always tag the check date, but only if nothing changed. I'd plan to do something similar for other maintenance-quests.

I know this proposal, I'm one of the endorsers :)

As far as I understand you're currently just looking at the last-changed timestamp on the ways for the construction quest, and don't parse the history when it was added, right?

If we have multiple map maintenance quests, one might update the timestamp and the second one would never be shown since the element was recently updated...

@ENT8R feel free to add your criticism :)

**Comment by westnordost** [comment]
> As far as I understand you're currently just looking at the last-changed timestamp on the ways for the construction quest, and don't parse the history when it was added, right?

I am currently not doing anything, just waiting on whether it will be granted or not ^^. So maybe it is a bit early to do this discussion. And generally, the decision whether to just use the bare minimum of tagging (like it is done for the construction quest) or always tag the check date, is probably something that should be up to the broader community to decide. (And how I know the more vocal people in the community, they want as few tags as possible)

Regarding the construction quest, I'd have to look at the source again, @matkoniecz implemented this quest. But as far as I remember, the quest is only displayed when both the last-change date of the element AND (if it exists) the check_date is older than X days.

This means that in the case that someone changes some tags on the construction site element in the meantime that are not related to its status as a construction site, it will inadvertently lead to that the quest is not asked again for some more time even though it was perhaps not really surveyed. That's not really an issue, in my opinion - it only means that the time the data might be outdated becomes a little longer.

**Comment by westnordost** [comment]
So if for example one would change all the links of all `website` tags of all shops to `https` links if available in a mechanical edit, all these shops would be recognized as "recently surveyed" then by the app (and other tools). Here, the assumption that if the element changed, it has probably been surveyed is not correct.

In fact, the above example is something that actually happened some time ago.
However, rather than recognizing that for this reason, the last-changed-date of an element is not a reliable datum for when an element has last been surveyed, that particular edit was heftily criticized for breaking this assumption. 

Another example: For example JOSM maintains a list of "definitely obsolete tags" that as far as I remember are _removed automatically_ when elements are touched. The question is, if these tags are soo obsolete that they may be removed automatically without the user's intervention, why are they not removed all in one go in a mechanical edit? Exactly to not break the above assumption, or in other words, to make the last-changed-date a more reliable datum.

**Comment by RubenKelevra** [comment]
Well, this assumption is completely flawed. When I fix a bus relation and have to split some ways, I don't check e.g. if the maxspeed is still correct.

The more edits happen in an area, the lower the chance that a resurvey quest would pop up, because there are constant small changes to the elements done.

While this might look fine on the first glance, it's actually the opposite: Many edits mean that there's a higher chance that something in the real world has been changed. So it would be more interesting to confirm tags which haven't been yet confirmed by people editing.

The check_date tag could be integrated into editors, that if someone edits the tag, the corresponding check_date tag will be updated as well - hiding the tag completely from the users unless they extend the view on the tag. While adding the ability to just click right on a tag and say "update check_date" to confirm that you've checked something and it haven't changed.

**Comment by westnordost** [comment]
> Well, this assumption is completely flawed.

Yes that is what I was trying to say. Still, such a decision would have to be taken together with the community and I was just giving you a preview what the popular opinion would probably look like based on past experience.

**Comment by RubenKelevra** [comment]
> > Well, this assumption is completely flawed.
> 
> Yes that is what I was trying to say. Still, such a decision would have to be taken together with the community and I was just giving you a preview what the popular opinion would probably look like based on past experience.

Well, I'm not aware that there's a need to discuss the usage of an already established tag.

It follows the rules, by being verifiable and useful.

I hate all these non-sense discussions where everyone just posts his (opposing) opinion without being constructive in any way to solve the obviously existing issue. Sure, you can invest the time to discuss it, but just because a handful of people just doesn't like a tag doesn't mean it shouldn't be used.

**Comment by westnordost** [comment]
`check_date` might be in use, but the namespace variant, `check_date:opening_hours`, `check_date:wheelchair`, `check_date:this_and_that` is not. People will be (rightly?) concerned about whether it is the right way to attach an extra tag to theoretically every other tag for information that could theoretically be derived from the history of each element:
By generating diffs and looking at the `source` tag for each change. Theoretically, because of course, there is no API for this, neither official nor unofficial (Overpass, ...), and there is no will/manpower at the core systems to implement it. But that doesn't change the fact that introducing new tags is theoretically not the best solution.

**Comment by westnordost** [comment]
Small correction: Such an API would not completely avoid the necessity of using `check_date:opening_hours` and alike unless it would be possible to "touch" a tag in a changeset without modifying it, because something can be checked without being modified.
It would only avoid the necessity to always tag the check_date for each tag when surveying, also when the opening hours (in this example) are changed.

**Comment by RubenKelevra** [comment]
Well, I'm not really a fan of `check_date:<key>=<date>`. I think check_date is logically a subkey, not the main key: `<key>:check_date=<date>`.

This will also sort better in the editors (when displayed):

```
addr:city=Remscheid
addr:housenumber=2
addr:postcode=42897
addr:street=Kronenstraße
amenity=restaurant
cuisine=pizza
name=Pizzeria Daunia
opening_hours=Mo-Tu 11:30-14:30,17:00-24:00; We off; Th-Fr 11:30-14:30,17:00-24:00; Sa-Su 11:30-23:00; PH 11:30-23:00
opening_hours:check_date=2020-01-05
phone=+49 2191 667969
```
vs
```
addr:city=Remscheid
addr:housenumber=2
addr:postcode=42897
addr:street=Kronenstraße
amenity=restaurant
check_date:opening_hours=2020-01-05
cuisine=pizza
name=Pizzeria Daunia
opening_hours=Mo-Tu 11:30-14:30,17:00-24:00; We off; Th-Fr 11:30-14:30,17:00-24:00; Sa-Su 11:30-23:00; PH 11:30-23:00
phone=+49 2191 667969
``` 

---

I agree that subtags are not that well established, but the reasoning behind that is that most users seem to add the key to determine the last time the whole object existed, like a building or an amenity.

Since we're collecting details and not new objects I think it's useful to add the date when the data was (last) collected/verified.

I don't want to add check_date to every quest we have, but `collection_times`, `opening_hours`, `oneway` and `maxspeed` makes sense to me.

We have dedicated quests for them and they do change in the real world pretty often - compared to other stuff, like building attributes or street names.

**Comment by westnordost** [comment]
> Well, I'm not really a fan of check_date:<key>=<date>.

Uhm I don't know, I'll use whatever variant is used, didn't look it up just then.

**Comment by mfbehrens99** [comment]
I prefer <key>:check_date because check date is an attribute of a key not a new key. This can also be seen with the "roof:shape" tag. Shape is not a new key but a further specification and information about the roof.

However, I am a really big fan of this feature. Street Complete is a very good and simple tool for adding new information to OSM but once the information is on the map the app is not yet able to keep information up to date. I hope this feature can be implemented on the next version of Street Complete

**Comment by RubenKelevra** [comment]
> However, I am a really big fan of this feature. Street Complete is a very good and simple tool for adding new information to OSM but once the information is on the map the app is not yet able to keep information up to date. I hope this feature can be implemented on the next version of Street Complete

The implementation of re-checking stuff is part of the [microgrant proposal](https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete), since it's a considerable amount of work to implement the re-checking. 

But just adding the `<tag>:check_date=<date>` on completion of quests isn't that difficult to add.  So it's more a matter of usability of such data - and IMHO this is given.

**Comment by westnordost** [comment]
I now posted this on the tagging mailing list: https://lists.openstreetmap.org/pipermail/tagging/2020-July/054208.html

Please feel free to join the discussion there

**Comment by westnordost** [comment]
So this can be closed now because the discussion has been done.
