### ISSUE TITLE
Sidewalk quests isn't always showing up

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1837]
I've looked into the rules of the quest and don't really see a reason why this way ([way:18459099](https://www.openstreetmap.org/way/18459099)) doesn't show up as a quest while the next segment ([way:104944961](https://www.openstreetmap.org/way/104944961)) have already shown up and was answered by me.

**Versions affected**
v20.0-beta1

**Comment by westnordost** [comment]
It does not show up because there is a footway near that strip of road.

The app is not so smart to fuzzily tell apart just some random footway in the vicinity of the street from a [separately mapped footway](https://wiki.openstreetmap.org/wiki/Sidewalks#Sidewalk_as_separate_way). If the latter exists for a road, the quest may not be asked because otherwise duplicate information would be added.

Yes, this means that with StreetComplete, it is not possible to completely map the sidewalk and cycleway infrastructure, because StreetComplete is too careful when asking for sidewalk and cycleway availability. But this is deliberate. As opposed to a validator geared at experienced users, the app shall not generate many false positives.

**Comment by RubenKelevra** [comment]
Ah! This makes sense. I thought the footways in the vicinity are only accounted for if there's a `footway=use_sidepath` tag on the road.

Thanks for the fast response!

**Comment by westnordost** [comment]
That would be nice, however only a very small percentage of roads that have separately mapped sidewalks do have this tag, so the amount of false-positives would be too high.

**Comment by westnordost** [comment]
Equally, looking only at footways with `footway=sidewalk` is unfortunately not enough, because again few sidewalks have this tag set. (And again unfortunately, it is not even possible to make a StreetComplete quest about adding this piece of information because there is no `footway=*` subtag for a "normal" footway.

**Comment by RubenKelevra** [comment]
Yeah, the structure is pretty crusty on that - it has grown and there's not a clear concept how to do this right which everyone agrees on.

Hope this improves in the future.
