### ISSUE TITLE
On first start: Map shows GPS position on world map

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1849]
I really enjoy the new intro, for new users - I think it's great.

But afterwards the user is left on the world map with a GPS dot on it. Without any instructions.

I'm not sure that's how it's supposed to be, but I would recommend to slowly zoom in over like 5 seconds to the GPS position, to allow the GPS to aquire a somewhat accurate fix and if it's finished to start downloading quests, which then start to pop up around the user.

**Screenshot**

![Screenshot_20200521-021159__01](https://user-images.githubusercontent.com/614929/82509758-18204380-9b09-11ea-89f3-6a526abb19ff.jpg)

**How to Reproduce**
First app start

**Versions affected**
v20b2

**Comment by westnordost** [comment]
The main reason why it is this way is because on gps fix, the app does not automatically follow the users location. It requires a tap on the locatiom dot to make it follow the position.

If it would, then when exiting the tutorial one likely would find the map already zoomed to the current position because the map is already active in the background while the tutorial is shown.

I remember having implemented it the way you request but remember that led to other problems.

Do you find out really that bad that the map is shown initially like this? It's hard for me to imagine that a user wouldn't know what to do then (= zoom in).

**Comment by RubenKelevra** [comment]
> Do you find out really that bad that the map is shown initially like this? It's hard for me to imagine that a user wouldn't know what to do then (= zoom in).

Yes. I was a bit confused if the app is now doing something or not. The reason for this is, that the intro shows how the map will look like with all those pins, and then you end up on a blank world map.

I think it should just run once on the first startup, as an animation after the user hit the last button. This shouldn't really break anything?

**Comment by matkoniecz** [comment]
> Do you find out really that bad that the map is shown initially like this?

Yes. Based on my user testing experiment: user will be confused by anything that can be confusing and by things that are impossible to be confusing.

Not directly applicable here, but unrelated test of unrelated thing revealed that even smallest barrier resulted in users dropping product. I admit here that I am unsure whatever it is directly applicable - maybe people who give up at this stage are extremely unlikely to be  a productive mappers?

**Comment by westnordost** [comment]
This should do it
