### ISSUE TITLE
"Preset" for speed limits, like for building levels

### ISSUE THREAD

**Issue by forteller** [westnordost/StreetComplete#1851]
Thank you for a great application! The new version is really fantastic!

**Use case**

Answering speed limit quests have quite a few steps: 
1. Open the quest
2. Press one of 2-3 options
3. Press the text field
4. Input the correct number
5. Press Ok.

Some times you have to answer the question of speed limits awefully many times in a row. This is especially true when your near a roundabout. One single roundabout can easily have 10 or more questions about speed limits, and some times there are more than one roundabout close by each other. In addition there are often many streets conected to each other with the same speed limit.

**Proposed Solution**
I propose that the speed limit quests have the same kind of "presets" as the building levels quest. After answering the building level quest once, the next time you open the same quest you're presented with a new button. This new button shows you what you answered last time, and you can press that if the new building has the same ammount of levels as the previous building.

I would think that roads nearby each other much more often has the same speed limits than buildings nearby eachother have the same number of levels. Therefor I think this solution would be reasonable, in addition to saving us questers quite a lot of time.

Thank you!

**Comment by westnordost** [comment]
Yes, could be done like you suggest, but you have much much less streets than you have buildings. In other words, the density of these quests is much lower, requiring to walk more to be able to answer it. Thus, the time necessary to enter the value is much less relevant than for buildings because most of the time is spent anyway in getting there. And in getting there, I mean to walk from one end of the whole street to the other, as is required. See also the notice that is displayed when enabling this quest type. So, adding features to speed up the input of speed limit might actually be contraproductive as in the data quality gets worse. In many cases, you wouldn't even want to input any concrete speed limit because there is no sign, so defaults apply.
