### ISSUE TITLE
Clarification on the building levels quest 

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#1889]
Do levels include bits that are not full floors, like an attic?

Context:

- For a while, I have assumed the answer is "no, only full stories count".
- However, it recently occurred to me that the roof shape quest is only asked for roof levels > 0.
- That means the app is assuming there cannot be a shape for a building with 0 roof levels -- that the roof is flat!
- If this is true that 0 levels = flat roof, then any not flat roof needs at least one level, even if it is not a full level.
- I now fear I've tagged quite a few buildings incorrectly.

**Comment by westnordost** [comment]
> For a while, I have assumed the answer is "no, only full stories count".

As far as I know, there is no consensus on it but on the other hand, this is also not discussed hotly because the roof levels is not exactly an important information. It is mostly used for 3d display with the few renderers that support it, one story or less does not matter that much.
Personally, I count a roof level as a roof level when I see a window on that storey because that means it is more than just a compartment below the roof but meant for humans to go in, bent over or not.

The lack of an "official" view/consensus on it also means that there can not be an explanatory text in StreetComplete, saying "it counts as one storey if....". It is up to the personal judgement of each individual surveyor.

> That means the app is assuming there cannot be a shape for a building with 0 roof levels -- that the roof is flat!

No, the app assumes that 
1. it might be difficult to see the roof shape that are not even one story high from below and users should only be confronted with questions they are guaranteed to be able to answer
2. the roof shape is less relevant for buildings with a relatively flat roof for 3D display
3. most buildings, [especially in regions of the earth where there are generally flat roofs because of little/infrequent rainfall](https://www.google.de/maps/@34.0614404,-4.9711758,200m/data=!3m1!1e3), that have less than one level of roof have flat roofs. Asking the roof shapes for the linked example would be spam

**Comment by smichel17** [comment]
That makes sense.

The only idea I have to address this would be a solution similar to https://github.com/westnordost/StreetComplete/issues/1717#issuecomment-581188710, by splitting "non-roof levels" and "roof levels" into two separate quests and then adding a new type of quest that asks for both roof shape and roof levels.

However, given the (not-very) importance of this tag, it is probably not worth the effort (same as the other issue). Maybe if a few other scenarios pop up where this approach would be helpful, then it will become worth it to make a generic quest type for answering two related tags at once. So I am closing this, but you can re-open if you have a better idea or decide it is worth the effort.

**Comment by smichel17** [comment]
I suppose another option would be to make the building height achievement include some information about this (or a link to your comment above :laughing:)

**Comment by smichel17** [comment]
> It is up to the personal judgement of each individual surveyor.

Just for future reference, most of the buildings I tagged like this were 1 or 2 stories with gable roofs and had no window in the roof level (but probably did have an small, unfinished attic).

**Comment by westnordost** [comment]
I meant, that if there is a window, it is a good indicator that one can enter this roof level and thus I'd count it as a roof level. If the roof looks like there should be reasonable space for someone to enter it, I'd also count it as a roof level.

**Comment by smichel17** [comment]
Hm, maybe there is room for clarification after all. I will get a picture of a building that I have tagged as 1:0 so we can more concretely evaluate whether I have been mistagging and, if so, what interface change would prevent that in the future.

**Comment by peternewman** [comment]
This is what I was pondering in #1778 (but ran out of time to write it all down, and never got round to completing it).

This seems fairly clear to me:
https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Tagging_for_building_outlines_and_parts

So a garage with a flat roof for example would be:
![Flat roof garage](https://upload.wikimedia.org/wikipedia/commons/9/9f/2012-01_Wiederitzsch_03.jpg)
```
building:levels=1
roof:levels=0
roof:shape=flat
```

A bungalow (in the UK is one storey), so this one would be:
![UK Bungalow](https://upload.wikimedia.org/wikipedia/commons/a/a2/Bungalow_United_Kingdom.jpg)
```
building:levels=1
roof:levels=0
roof:shape=gabled
```


Whereas this clearly has a loft conversion/dormer so this one would be:
![US Bungalow](https://upload.wikimedia.org/wikipedia/commons/8/88/Bangalod_Belmont-Hillsboro_naabruskonnas_Nashvilles%2C_Tennessees%2C_U.S..jpg)
```
building:levels=1
roof:levels=1
roof:shape=gabled
```


Whereas this is two floors but seemingly no room in the loft:
![Bangladesh Bungalow](https://upload.wikimedia.org/wikipedia/commons/f/fa/Guest_house_in_Sylhet_%2801%29.jpg)
```
building:levels=2
roof:levels=0
roof:shape=hipped
```

Personally I've been using the presence of a dormer or roof light to decide roof levels, and generally windows to decide building levels.

> If the roof looks like there should be reasonable space for someone to enter it, I'd also count it as a roof level.

In the UK most roofs have the ability to enter, but generally not stand up comfortably (due to height) or move around (due to rafters), but there is often a loft hatch for access and they're used for storage (e.g. suitcases or other infrequently used stuff like Christmas decorations).

The only area I'm really unclear of, is how I should be tagging somewhere with a flat roof that's used (e.g. a multi-storey car park or a roof terrace), I assume that should be `building:levels=x` (enclosed) and `roof:levels=1`?

> No, the app assumes that

This doesn't seem to quite tie up with what the code is doing:
https://github.com/westnordost/StreetComplete/blob/23882a3ef41d8c719e620201559032d42cfcc65e/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShape.kt#L10-L13
 
>     1. it might be difficult to see the roof shape that are not even one story high from below and users should only be confronted with questions they are guaranteed to be able to answer

I think I can comfortably see two or three storeys (plus roof) from the other side of the street, possibly even more. I feel I'm more guaranteed to be able to answer those questions just walking about than whether a launderette is self service or reliably answer if somewhere is wheelchair accessible without going in those places, although I appreciate the other questions are generally more useful for people than roof shape.

>     2. the roof shape is less relevant for buildings with a relatively flat roof for 3D display

Agreed, although the fact the quest is disabled for `roof:levels=0` means we can't tag them as flat.
 
>     3. most buildings, [especially in regions of the earth where there are generally flat roofs because of little/infrequent rainfall](https://www.google.de/maps/@34.0614404,-4.9711758,200m/data=!3m1!1e3), that have less than one level of roof have flat roofs. Asking the roof shapes for the linked example would be spam

While I'd agree it would be spam there, in somewhere like the UK, due to the varying historic ages of our architecture there are a large variety of roof types in use, apart from maybe dome and onion (which are mostly just on religious buildings) I'd say all of the others are quite common in different areas or during different eras.

Would it help if we could either gather a specific list of countries where `roof:levels=0` part of this quest should be enabled too (such as the UK, probably most of Western Europe off the top of my head), i.e. where flat roofs aren't the norm, or use e.g. some rain level statistics to work out areas where it should remain disabled?

**Comment by peternewman** [comment]
> I had similar problems / need for clarification regarding roof levels, but also with several other quests.
> Maybe there could be some further explanatory text behind a "more" or "details" button...
> This would help a lot, and it should be possible for at least some quests without the explanation establishing some kind of consensus.

You mean like a link to/cache of the relevant wiki page?

**Comment by smichel17** [comment]
I wrote this, then realized you were not quoting me :neutral_face:. Posting anyway because hopefully it's interesting.

> You mean like a link to/cache of the relevant wiki page?

**Context:** I started using StreetComplete (as opposed to some other way to contribute to OSM) because it did not require me to learn details of the way OSM works. As I've contributed (mostly ideas) to SC, I've explicitly tried to avoid learning those details when I can, to preserve my ability to represent the type of user I was for as long as possible. I also try to keep my feedback and suggestions in general terms and rely on those more involved with OSM to figure out the best way to translate those (even when I have incidentally picked up some OSM knowledge along the way).

How that applies here: While it's hard to avoid learning that the wiki exists :laughing:, I've read very little of it, so I'm not in the best position to evaluate the question. A link/cache might be appropriate, or it might be better to summarize it, translated into the terms StreetComplete uses (rather than talking about specific tags).

**Comment by westnordost** [comment]
Regarding rainfall, ... maybe. However, buildings in business districts will often have a flat roof as well.

Maybe the query could be loosened to only not ask for the roof shape if the user is likely to not see it from the street because the building is too high in relation to the roof levels. Maybe if >=3 levels + 0 levels in the roof

**Comment by peternewman** [comment]
> I wrote this, then realized you were not quoting me neutral_face. Posting anyway because hopefully it's interesting.

I think it is @smichel17 .
 
> How that applies here: While it's hard to avoid learning that the wiki exists :laughing:, I've read very little of it, so I'm not in the best position to evaluate the question. A link/cache might be appropriate, or it might be better to summarize it, translated into the terms StreetComplete uses (rather than talking about specific tags).

I've used SC primarily, but gone to the wiki to clarify things and used the website primarily to finish edits/fixes I couldn't complete via SC, e.g. where I'd left a note, or to add features I assumed might be missing from the map while wandering which I'd added as a note.

I think the challenge with your suggestion might be that some of the detail can be quite specific or can change. My understanding is the wiki is almost the spec for how to use OSM. Keeping that all up to date and translated into however many languages would be a lot of work, compared to linking to relevant bits of explanation.

**Comment by peternewman** [comment]
> Regarding rainfall, ... maybe. However, buildings in business districts will often have a flat roof as well.

Or some other reasonably easy to discover thing, or perhaps just a list of places where it's enabled by default and allow others to enable it elsewhere as a quest elsewhere if they'd like. Again if you take somewhere like London, it has a vast array of different building ages and hence roof styles.

> Maybe the query could be loosened to only not ask for the roof shape if the user is likely to not see it from the street because the building is too high in relation to the roof levels. Maybe if >=3 levels + 0 levels in the roof

I'll try and get a better estimate for how much roof I can see, personally I don't think it should filter out regardless of the number of roof levels, I'd like to be able to fill that in for both loft conversions and places where the loft is just storage. Otherwise per-quest options would be ideal for this. Or some second quest which is disabled everywhere as it may be spammy (similar to other disabled by default ones)?

Regarding limiting how many levels, it's also not hard to get high up in most cities and look down on buildings that are tall but shorter than yours. I think SC would still be far easier than adding that data via another means and I might walk round the floor of my office, or a hotel or department store if I'm really bored or waiting there, gathering that data via SC, but the faff of doing it via other means would likely mean I wouldn't do it. That all goes if the quest is hidden in those cases.

**Comment by michaelblyons** [comment]
😬 I started assuming I should put a default `roof:levels` of 1, because I wasn't getting the `roof:shape` without it. I agree the `roof:shape` quest should appear even with a `roof:levels=0` so other people don't do what I did.

**Comment by RubenKelevra** [comment]
In my opinion every house which has a attic should be counted as one level. Levels are the amount of floors you have. An attic has a floor, regardless how high it is.

So if there's a window in the attic, the current pictogram is pretty self-explanatory, since it shows an house with an attic with a window and a level which is also below the roof, with two windows.

The app displays that this should be counted, and it's obvious that the count should be two IMHO.

So yeah, as far as I understand you've tagged the buildings wrong. But you could just use JOSM and go through your changesets and revert them where you answered this quest.

**Comment by smichel17** [comment]
> The app displays that this should be counted, and it's obvious that the count should be two IMHO.

I agree.

> The wiki shows the same thing

I do not agree. With the wiki diagram it is clear to me that the attic should be counted as a roof level, whereas this was not clear to me from our illustration. Eyeballing the SC illustration, it is not clear to me whether there is an attic *above* the top window. Compare how much space is in between each window, and how much space is between the bottom window and the building base; in order to have equally-sized floors, the window must be near the top of the floor. So draw a floor line right above the top window, and there's actually about half a floor's worth of vertical space between there and the roof — possibly an attic!

Suggestion: Remove the top window from the illustration and draw in a triangle using a dotted line, to represent the attic.

> you could ***just*** use JOSM

This would require me [to learn](https://github.com/westnordost/StreetComplete/issues/1889#issuecomment-644778729) how to use JOSM :(

**Comment by peternewman** [comment]
> Do you mean <=3 levels?

No, the suggestion was to hide it if it's too tall to see the roof from the ground.

> In my opinion every house which has a attic should be counted as one level. Levels are the amount of floors you have. An attic has a floor, regardless how high it is.

That's impossible to answer from outside though, whether via SC or OSM. Take for example a church, it may be the height of four traditional storeys, but have a double-height main space, and a double height roof, with the only floor being on the ground. I would tag that (assuming I could only see one set of windows outside) as `building:levels:1/roof:levels:0`. In your scheme, how do you decide if it's 1 or 2 roof levels, or how do you know if it's got an attic? Or to continue the attic question, when does it become an attic? Our garage has rafters and we store stuff on them, presumably that doesn't count as there's no floor? But then our house loft is only partially floored (some is just the insulation above the ceiling of rooms), it has a hatch but not permanent ladder or access. What about a suspended ceiling below a flat roof, is that an attic?

> a level which is also below the roof, with two windows.

> The app displays that this should be counted, and it's obvious that the count should be two IMHO.

Surely if it's below the roof, it's not a roof level? So the count should be one? Although I'd say that's half in line with the roof level so perhaps a typo on your side?

There's some possible clarification here:
https://wiki.openstreetmap.org/wiki/Talk:Key:building:levels#How_to_mark_levels_that_are_partially_under_the_roof

And more uncertainty here:
https://wiki.openstreetmap.org/wiki/Talk:Key:building:levels#What_exactly_is_a_level.3F

Someone else asking the same thing on the wiki:
https://wiki.openstreetmap.org/wiki/Talk:StreetComplete/Quests#Roof_Levels_vs_Building_Levels

> Number of floors within the roof, which are not already counted in building:levels=*. 

> The wiki shows the same thing:
> 
> ![Screenshot_20200618-032207](https://user-images.githubusercontent.com/614929/84966915-05eaf280-b113-11ea-9373-0973c56eef10.jpg)

I'd suggest the wiki doesn't really properly clarify what counts as a floor either.

**Comment by michaelblyons** [comment]
> > Do you mean <=3 levels?
> 
> No, the suggestion was to hide it if it's too tall to see the roof from the ground.

My mistake. I misparsed _"to only not ask for the roof shape,"_ but I think we're on the same page now.

If you use iD, it suggests half-levels for roof and building levels. If StreetComplete did that (or even let you type them), I would have used `0.5` for crawl-space sized roofs instead of `1`. But I could also do `0` if I still got the roof shape question afterward.

**Comment by peternewman** [comment]
> If you use iD, it suggests half-levels for roof and building levels. If StreetComplete did that (or even let you type them), I would have used `0.5` for crawl-space sized roofs instead of `1`. But I could also do `0` if I still got the roof shape question afterward.

Curious, as I've not seen 0.5 levels anywhere on the wiki. Does iD just let you enter half values for all numbers?

**Comment by michaelblyons** [comment]
> Curious, as I've not seen 0.5 levels anywhere on the wiki. Does iD just let you enter half values for all numbers?

Yes, it autocompletes half-steps: 0.5, 1, 1.5, 2, 2.5, ...

**Comment by westnordost** [comment]
This discussion didn't really lead to anything. I'll close this.

**Comment by peternewman** [comment]
> This discussion didn't really lead to anything. I'll close this.

I think at a minimum there should be the ability to tag roofs where roof level = 0 (and probably it's < 3 storeys or whatever, also possibly filtered to countries which have enough rainfall to not all be flat).

**Comment by westnordost** [comment]
You can file a new issue for that, this issue has gotten too long.

**Comment by smichel17** [comment]
I have a follow-up that may make this actionable again. I was recently mapping with someone else, and having another person to bounce opinions off of was really helpful. I've concluded that there's really no sane (read: consistent) way to answer the question except to err toward:

- If it is not completely in the roof, then it is a regular level, not a level in the roof.
    - In other words, the walls must be slanted along (nearly) their entire length to count as "in the roof"
- If it does not have a window, it is not a level (or rather, cannot be reliably tagged as one).

<img src="https://user-images.githubusercontent.com/614929/84966915-05eaf280-b113-11ea-9373-0973c56eef10.jpg" alt="OSM wiki clarification image" height="200" align="right"/>

There are a very few exceptions, but basically, without going inside the house it's neigh impossible to tell whether level A exists or whether B has a tall/open ceiling, all the way up to the roof. Likewise, it's often difficult to tell how far off the floor B's windows are, making it a guessing game, whether enough of B is below the roof to call it a normal level or a roof level.

This wouldn't really be a problem, except that I noticed my judgment about how to classify vague cases changed often, and so my answers were inconsistent… which is sometimes worse than no data at all. The only way I can figure out to be consistent is to narrow my criteria so that I don't have to guess very often. This may result in lacking detail ("The top story here is actually really tall"), but it's easier to add detail later than it is to correct wrong information.

<img src="https://user-images.githubusercontent.com/6563664/116575390-1dcbff00-a8fe-11eb-8df8-6778a7cce47c.png" alt="SC building:levels form" align="right"/>

### How this relates

> The app displays that this should be counted, and it's obvious that the count should be two IMHO.

I no longer agree.

The SC form shows one of these ambiguous edge cases, where the 2nd from top story is on the edge of being in the roof vs a regular level. Here, I've extended the lines along the sides to find where the floor is implied to be for the 2nd to top story, then applied that same standard to the top story. Colors don't have any meaning, they're just to show the boundary clearly. 

I see a story that is mostly below the roof, but the tops of the walls start to be cut off by the roof. If the house were very narrow, I might be inclined to call it a roof level, but as pictured, I'd call it a regular level, *especially given my conclusion above that calling it a regular level is the only way to be consistent in the face of ambiguity.*

So, I think that the image should be adjusted, either to show the 2nd from top as a regular level or changing how far the roof comes down so that it is indisputably a roof level.

**Comment by westnordost** [comment]
Well obviously, the current graphic suggests that whenever it is ambiguous, a level should be tagged as in the roof. If the graphic was changed to show an unambiguous case, then I think this would be less help and thus result in less uniform data, because users get no hint what to answer in such ambiguous cases.

As far as landlord and tenant law is concerned, the second from top level is definitely a roof level, because you cannot put a large cabinet on the wall
