### ISSUE TITLE
Rendering bug with tilting: Icons will disappear when switching app

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#1907]
I found a weird rendering bug which seems to avoid that the icons get repainted after a switch from the app and back to the app when the map is tilted.

Also note the weirdly behaving position marker at the edge of the screen, which disappears when the quests reappear (after tilting to bird eye view again).

**Version affected**
21-beta1

**Android version**
10

**Video**
https://youtu.be/GEiHhxBUUFQ

**Comment by westnordost** [comment]
When you move the map, StreetComplete checks if the quests in the bounding box that is displayed on screen have already been loaded from the local database. If not, loads them and displays them onto the map.
If the map is extremely tilted, the bounding box cannot be calculated because it would be infinitely large (as you see the "sky"), this is why the checking for if quests should be displayed stops right there.

The quests are cleared when the map activity is stopped because while the map activity was in the background, the visible quests might have changed in the settings.

**Comment by westnordost** [comment]
I tried to limit the max tilt to a certain max to mitigate this issue, but it turns out it is nontrivial to implement this with tangram-es.

**Comment by westnordost** [comment]
So, a mitigation is too much effort for such an uncritical problem

**Comment by riQQ** [comment]
This was possibly mitigated by db365c327ce8905aa0354265b6bd9468fba07fb8.
