### ISSUE TITLE
Allow users to lock onto current location again

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#1918]
My main use scenario for this app has been as a passenger in a car. Since the UI rework, this has become incredibly inconvenient, as the app no longer seems to follow me, nor can I rotate as easily as before. Would is be possible to have something similar to the older behavior as an option? It doesn't need to be the default.

**Comment by smichel17** [comment]
You can, by tapping the location marker (or the floating pin, if your location is on-screen). FWIW I agree the new placement is non-obvious. Especially: it lacks a clear indicator for when you are currently locked on vs happen to be standing in the middle of the screen. (The location off screen pin *was* a good addition, I just don't think it works as a full replacement).

**Comment by westnordost** [comment]
You can tap on your position to follow it again 

Am 26. Juni 2020 03:02:06 MESZ schrieb Gabe Appleton <notifications@github.com>:
>My main use scenario for this app has been as a passenger in a car.
>Since the UI rework, this has become incredibly inconvenient, as the
>app no longer seems to follow me, nor can I rotate as easily as before.
>Would is be possible to have something similar to the older behavior as
>an option? It doesn't need to be the default.

**Comment by gappleto97** [comment]
Yes, but this adds an extra step to what was otherwise a perfectly good workflow. And if you accidentally drag the screen (for instance, expecting it to rotate as before) it takes itself out of follow mode. There isn't an obvious way to lock it like you could before.

**Comment by westnordost** [comment]
Yes that's true. I reckon there is no perfect solution. With the old solution ("glued position"), many people where unhappy and/or confused. And to be honest, the glued position simply didn't work that well because often you simply had to look around from your current position a bit to see the quests. Whenever I went on a survey, I switched between glued position and free position all the time: While going to the next cluster of quests, I wanted it to follow the position, but when actually coming near it, I wanted to zoom around the map to get an overview and/or to see which other quests I can solve from where I am now or moved past in the meantime (for example, after moving past a row of detached houses, I would then answer them after having moved by them at the next intersection to not trigger paranoid home owners). The position-gluing was essentially replaced by
1. nothing, because the concept itself was confusing to many
2. By a standard "it is unglued once you move the map by yourself" behavior because it somewhat coincides with (my) normal usage of the app: I want it to follow my position until I zoom around manually
3. later by the location pointer pin too: Often you don't really want to follow your position, but only know in which direction you are

There are a lot less remarks now about the current behavior. So, I acknowledge that not all are happy with the removal of the sticky position, but I'll mark this as will not fix.

I know that a few community members, would have at least the GPS button back to have a control to 1. see if the position is currently being followed and 2. to have a bigger tap-area to trigger it. The first item could obviously be solved by giving the position marker a different color when the position is being followed. If you think that helps, you could create a new feature request for that.
