### ISSUE TITLE
Opening hours quests enhancement

### ISSUE THREAD

**Issue by f6fvy** [westnordost/StreetComplete#193]
I submitted several opening hours quests in my neighborhood and faced these two situations:

- One shop was not correctly located on the map
- Another shop has changed (name and sold goods)

Would it be possible to add a note to inform about that in the reply form ?

**Comment by westnordost** [comment]
Then this form would need to be present in *every* quest because there may always be wrong data everywhere, cluttering up the user interface.

In the case of "can't answer because...." wrong data, invalid question, does not apply, wrong location etc. pp. there is the "Can't Answer" button with which you can leave a note instead.
