### ISSUE TITLE
New reward: Generate Opening Times

### ISSUE THREAD

**Issue by golden-spiral** [westnordost/StreetComplete#1933]
https://osm-de.github.io/WebToOSMOH/
Can be used to generate OSM-usable opening times from normal text (copied from web pages e.g.).

Possible "reward" for awards

**Comment by westnordost** [comment]
Hmm, that's quite nice!

Though, in StreetComplete, only things that are usable in one way or another for end users should be included. In full, only the following things should be included:
- data is fully or substantially from/for OpenStreetMap
- is open source. If it is not open source, it should at least be a free service and not appear like an advertisement for a commercial provider's services
- is interesting for end/casual users with no or limited technical understanding
- is kind of established and/or it is clear that the project will be around for a longer time
- fits into the link categories established in StreetComplete

If the WebToOSMOH works very good, even with kind of fuzzy things, the better idea would be to use this lib together with OCR from the smartphone's camera to pre-fill the opening hours by taking a snapshot of the opening hours plate. This would have to be extensively tested though, and would be able to deal with the kind of fuzzy input that can be expected from OCR input. I think that project is not in that stage (yet).

Furthermore, the project is not worked on actively since over a year ago plus I was not able to find the source code for it. ( https://gitlab.com/geometalab/web-to-osm-opening-hours/-/tree/master is pretty much empty)

**Comment by peternewman** [comment]
> Furthermore, the project is not worked on actively since over a year ago plus I was not able to find the source code for it. ( https://gitlab.com/geometalab/web-to-osm-opening-hours/-/tree/master is pretty much empty)

For info the guy that hosts it via GitHub pages therefore has a copy of the code here:
https://github.com/OSM-de/WebToOSMOH

Confusingly it seems the other code was in two different branches (presumably with alternative behaviour):
https://gitlab.com/geometalab/web-to-osm-opening-hours/-/tree/converter_A
https://gitlab.com/geometalab/web-to-osm-opening-hours/-/tree/converter_B

**Comment by mnalis** [comment]
- (related: https://github.com/streetcomplete/StreetComplete/issues/1186)
