### ISSUE TITLE
Quests counted in wrong country

### ISSUE THREAD

**Issue by ahstro** [westnordost/StreetComplete#1940]
I was browsing places from previous trips - Poland, USA, and England - and ended up mapping some places in England. For a while, they showed up as a British flag under My Profile > By Country, but now they're all logged as having happened in Poland. I don't remember if I actually mapped anything in Poland. Assuming this has to do with how StreetComplete groups edits? [This](https://www.openstreetmap.org/changeset/87591660) is most likely the offending changeset.

**How to Reproduce**

  0. Probably map in one country
  1. Map in a different country soon enough for changes to be included in the same changeset

**Versions affected**
21.0

**Comment by westnordost** [comment]
Hui, how did this changeset come together?

**Comment by ahstro** [comment]
Like I said: just scrolling the map to places I have been recently, looking for easy things like road surfaces to add from memory. Bad practice, I know, I'll be better in the future 😇, but I'm assuming still a possible bug if someone is e.g. biking across country borders. Maybe uploads to OSM should be grouped according to country or something? (I'm just guessing about the internals here)

**Comment by westnordost** [comment]
Mh, okay. Well, for the statistics, the app does not count each change but each changeset individually. It just takes the center point of the bounding box to determine the country.

So for example if you solved 1000 address quests in Paris and 1 in Krakow within one changeset, all 1001 solved quests would count as having been solved in Germany.
But since such changesets are bad practice anyway (not only in context of StreetComplete) and since it only messes up the offending user's own statistics, I don't see the necessity to increase the complexity of the implementation by determining the country of each change individually. If this is very important to you, you can create a PR here that would implement such a feature https://github.com/westnordost/sc-statistics-service

**Comment by callis** [comment]
How do You handle changeset centroids that land outside of country borders? A larger part of my changesets for example could not be associated with a country.
 https://nx4521.your-storageshare.de/s/gjFj5fAxA4pqx68

**Comment by westnordost** [comment]
They are not handled at all. Actually, they should not appear in the by-country statistics at all.
