### ISSUE TITLE
Optionally suppress quests for very short ways

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1944]
Hi there,

more and more I get road surface/road lit quests for **_very_** short ways with a length of sometimes less than 50 centimetres (building entrances or even short ways inside of building complexes). See this example:

![Screenshot_20200709-145633](https://user-images.githubusercontent.com/32601012/87042952-a43f1500-c1f4-11ea-8b20-691db1b493a1.png)

There are regions flooded with quests like the ones in the screenshot. These quests often come in clusters (many entrances to the same big building, all entrances to a series of terraced houses) and furthermore it's often private ground, although probably not tagged as such.

I'd suggest to use a minimum length for quests like these - it's kind of frustrating if you deliberately walk/cycle into an area with many road surface/lit quests just to notice that most or all of them are just these trifle cases, some of them you even cannot solve without entering private ground. Ideally this would be a switch in the settings ("Suppress very short items" or similar).

(SC 20.2 on Android 9.0)

The cycling cat

**Comment by westnordost** [comment]
Yet, very short ways may also be very important pieces of the road network. One cannot generally say that if a segment is below a certain length, it is not important. Even for way segments that are a dead end in regards of the way network, one can not generally say that: Imagine these short segments were indeed steps - this is relevant for wheelchair routers.

And since StreetComplete can not make such general assumption about the usefulness of the information based on length, this is a will not fix, even though I understand and acknowledge that the cases you show and probably most instances where extremely short ways occur, are unimportant and can be frustrating to solve.

**Comment by cyclingcat** [comment]
Granted, these snippets can be important, for routers of any kinds or as a simple source of information, especially if they are part of a road/street/way/path which has been splitted into multiple OSM ways for some reason.

On the other hand: Wouldn't it be a pity if mappers get frustrated because of this and therefore switch off the "road surface" quest completely? In particular in rural regions many road surfaces are still untagged and StreetComplete is an excellent tool to fill this gap (I don't know of any other method to tag 10 or 100 ways in a village more efficiently). Thus my proposal: Make it configurable! People with a lower frustration tolerance could simply switch off the shorter ways and concentrate on the longer ones which are still more important after all.

The cycling cat

**Comment by westnordost** [comment]
Hm, I think those getting frustrated by "too many quests" would actually quit before finding such an option. There are also other quests that are per se a bit frustrating and repetitive, such as the building type quest. I agree that this should be addressed somehow but I think the better way would be to make new users decide at the beginning what are the topics they are interested it as was proposed in another ticket.
