### ISSUE TITLE
street names in greece

### ISSUE THREAD

**Issue by beatnickgr** [westnordost/StreetComplete#1953]
The street names in greece include:
1) name:prefix
2) name
3) int_name

But the quest will add
1) name
2) name:el 
name:<lg> is for a name in DIFFERENT language https://wiki.openstreetmap.org/wiki/Names#Key_Variations
3) name:en
the latin characters are definitely not readable with English pronunciation, they are much closer to spanish, 

Here is an example
https://www.openstreetmap.org/changeset/87928121

Please make the quest asking for name and int_name exclusively.

**Comment by matkoniecz** [comment]
> name: is for a name in DIFFERENT language

No, it is for name in a specific language. It can be added also in language of name tag

**Comment by westnordost** [comment]
I will look into this.

The name-namespace is a bit of a mess in OpenStreetMap and different standards have established in different regions. So far, if in a country it can be assumed that the (street) name is given in the local language/script and in "something" in latin letters, it will be tagged as `name:en` **because this is common practice of the community in many countries**. But I agree, this is not really correct.

Actually, the most correct key for [romanized](https://en.wikipedia.org/wiki/Romanization) versions of a name (= in latin letters)  in Greek would be `name:el-Latn` (using [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924)) Though, this is seldomly used.

I will research how the name tag is used in countries where street often have 2 or more names on the street name plate.

**Comment by westnordost** [comment]
Okay, this is the outcome of the research.

I not only checked the tag counts, but also for each country listed here how the street signs actually look. Turns out, there is actually only a very small difference between street signs with romanized versions of the name and with "English" versions of the name: In one case, the street name is romanized completely, in the other, everything except the word for road is romanized and the word for road translated.

For example, let's say there is a street in Thailand called *ถนนวัด*. The romanization of that is *Thanon Wat*.
The name of the street translated to English would be *Temple Road*, but nobody does that. Either *Thanon Wat* is given on the sign, or *Wat Road*. (In the case of Thailand, it is *Thanon Wat*, with a few exceptions).

So in the table below, in the column "real situation", `en` means *Thanon Wat*, `romanized` means *Wat Road*

|                      | int_name | name:en | name:XX-Latn | Real situation |
|----------------------|----------|---------|--------------|----------------|
| United Arab Emirates | 844      | 16126   | 0            | en             |
| Armenia              | 847      | 16126   | 0            | en             |
| Bulgaria             | 39805    | 50589   | 0            | romanized      |
| Bahrain              | 483      | 2288    | 0            | en             |
| Shanghai (China)     | 3920     | 38701   | 0            | both?          |
| Bejing (China)       | 1540     | 14108   | 0            | both           |
| Egypt                | 10735    | 204536  | 0            | en             |
| Georgia              | 1682     | 37207   | 0            | en             |
| Greece               | 69608    | 67398   | 74 (el)      | romanized      |
| Israel               | 1        | 116896  | 0            | en             |
| Iran                 | 725      | 134467  | 0            | en             |
| Japan                | 2183     | 548416  | 47140 (ja)   | romanized      |
| Jordania             | 3910     | 22145   | 0            | en             |
| Cambodia             | 46       | 4003    | 0            | ?              |
| South Korea          | 1006     | 408616  | 133274 (ko)  | romanized      |
| Kuwait               | 30       | 33832   | 0            | ?              |
| Laos |   | 66 | 14000 | 0            | fr |
| Libanon              | 104      | 15809   | 0            | ?              |
| Sri Lanka            | 166      | 4648    | 0            | en             |
| North Macedonia      | 7506     | 11716   | 0            | romanized      |
| Myanmar              | 255      | 57862   | 0            | en?            |
| Oman                 | 5830     | 5844    | 0            | en             |
| Qatar                | 41       | 32666   | 0            | en             |
| Syria                | 12304    | 22371   | 0            | ? |
| Thailand             | 1791     | 114893  | 537 (th)     | romanized      |
| Taiwan               | 593      | 109739  | 0            | en             |

Looking at the usages, one can see that
* for United Arab Emirates, Armenia, Bahrain, Bejing and Shanghai, Egypt, Georgia, Israel, Iran, Jordania, Sri Lanka, Myanmar, Qatar and Taiwan, `name:en` is used by the community, which is **correct**
* for Japan, South Korea and Thailand, mostly `name:en` is used by the community even though this is **not correct**, `name:xx-Latn` would be correct
* Laos is **completely wrong**. The names on the sign are romanized to French (f.e. *Rue Wat*) but incorrectly tagged as `name:en`
* for Greece, Bulgaria and North Macedonia, also `name:en` is in common use by the community even though that is **not correct**. However, In these countries, both `int_name` and `name:en` are used in the same order of magnitude

## Result

StreetComplete does not push `name:en` for romanized names but pretty much follows current tagging practice.

However, at least the community in Greece, North Macedonia and Bulgaria are moving away from `name:en` towards `int_name`. `int_name` is better than `name:en` for romanized names but strictly speaking still not entirely correct because romanized is not necessarily "international". The community in Japan and South Korea seem to be moving towards `name:xx-Latn`, though still have a lot of re-tagging work ahead of them.

All in all, StreetComplete should not offer "English" as a choice in countries where street signs are commonly romanized without actually containing any English but instead tag the next best alternative as used by the local community. 

It is an open question whether in the curious case of Thailand and Laos, where no other option is in use, `int_name` or `name:th-Latn` should be forced onto the community. Probably not.

Another open question is how to solve this in the UI. Use "Latn" on that button? Who will understand that?

**Comment by westnordost** [comment]
Started a topic in the Thailand forum: https://forum.openstreetmap.org/viewtopic.php?pid=794811#p794811

**Comment by stephankn** [comment]
Please check the forum as linked above. In Thailand, English **is** used in name:en. Like  XX _school_, XX _administration_, XX _river_ and more.

**Comment by westnordost** [comment]
@stephankn Right, this issue is actually specifically about street names though. Are road signs also sometimes in English, like "XX road"? I have only seen "Thanon XX" so far.

**Comment by westnordost** [comment]
I also started a topic in the Greece Forum regarding their use of int_name which is kind of still not correct, even though they moved away from name:en supposedly because it is not correct:

https://forum.openstreetmap.org/viewtopic.php?pid=794922#p794922

**Comment by stephankn** [comment]
Feedback coming from map-making Thai locals is that you should use "Road", not "Thanon". But as always this is not always and fully followed. Also Transliteration of names which should use RTGS often use something else. Even on official street signs.

Examples from Google Maps, as I have too many photomapping pictures to quickly find some. I guess you should also find plenty examples on Mapillary.

Here "Road" is used in Bangkok:
https://www.google.com/maps/@13.7364283,100.5613966,3a,37.7y,29.33h,97.71t/data=!3m6!1e1!3m4!1ssDnCxsIGL2YtzvTy8deKHA!2e0!7i16384!8i8192

Pattaya has limited space on their signature street signs, so they only state name, neither Thanon, nor Road. Other street signs having more space use "Road":
https://www.google.com/maps/@12.9345706,100.892355,3a,75y,268.98h,104.05t/data=!3m6!1e1!3m4!1sn4HMUg_tWbDKOtI3CMV7GA!2e0!7i16384!8i8192

Also competitor maps like Google or Esri name it "Road".

Chiang Mai has similar issues with limited space on the signs, so they also have only the name, without Road or Thanon.
Adding to the confusion might be, that in Thai script they have "Thanon" or "Soi".

https://www.google.com/maps/@18.7914649,98.9784752,3a,63y,139.29h,89.8t/data=!3m6!1e1!3m4!1sH3E7O3kbD-rhf5ihv7aFcw!2e0!7i16384!8i8192

Soi is called like this, as it has a specific meaning. It is not translated into "Lane" or "Alley", even there are some examples around where exactly this happened. But this is an exception, similar to spelling problems on official signs.

We can keep such things in alt_name:en to care for search engines and established use of even something wrong:
https://www.google.com/maps/@18.7914498,98.9811483,3a,60y,306.83h,89.24t/data=!3m6!1e1!3m4!1s0q6rVEQmMAakwVZai59jPw!2e0!7i13312!8i6656

Where they have space on their sign and design to include more, they are using "Road"
https://www.google.com/maps/@18.7952533,98.986661,3a,39.3y,171.01h,95.12t/data=!3m9!1e1!3m7!1sDrPf9wHAxVkBN0V0MvI7vw!2e0!7i16384!8i8192!9m2!1b1!2i22

**Comment by westnordost** [comment]
Hmm, the way I came to the conclusion in the table above that in Thailand it is common to have a "Thanon Wat" and not a "Wat Road" on the street sign was by (personal experience and) looking at StreetView at random locations.

I picked some locations at random again and indeed, both "Thanon Wat" and "Wat Road" appear.

**So, then it is maybe best to leave it to the user, i.e. offer both "English" and "Thai Romanization" as additional street sign languages for the street name input form.** The user can then select which is applicable.

**Comment by westnordost** [comment]
I am a bit disappointed at you, @beatnickgr , for not taking part in working towards a solution, neither here nor in the (Greek) forum or anywhere else, even though you were the one who brought up this topic.

But regardless.

To recap, I identified the current behavior as a problem (after the research done in https://github.com/westnordost/StreetComplete/issues/1953#issuecomment-658408761) because for some countries, namely **Bulgaria, Greece, Japan, South Korea and North Macedonia**, tagging always `name:en` for the internationalized/romanized version of street names as written on the street signs goes against the recommended tagging practice in the communities of these countries.

Therefore, in order to not have StreetComplete stand in the way of recommended tagging, I saw the need to change the implementation towards supporting both `int_name` ("international") and `name:xx-Latn` ("romanization"). The extended implementation will be part of the next major release. Here is a demo how it will look in Thailand, where mostly `name:en` is used, but also `name:th-Latn` to a lesser degree: https://www.westnordost.de/misc/Thai-Street-Name-1.webm

I also selected the solution that has the least ramifications for the tagging in each of the communities, which is that for the romanization, not always `name:xx-Latn` will be used, but depending on the country instead also `int_name`, if the community there (f.e. Greece) chose to use this tag instead of the `name:xx-Latn` tag.

StreetComplete will be transparent in what it tags - when selecting "international" as the Language of the name, it will tag `int_name`, when selecting for example "ไทย (Thai), in Latin script", it will tag `name:th-Latn`.

I didn't find any information about `name:prefix` regarding Greece, so no implementation there.
