### ISSUE TITLE
Renderer: Display bridge above roads doesn't work for path before/after bridge

### ISSUE THREAD

**Issue by kudlav** [westnordost/StreetComplete#1954]
There is `highway=trunk` and bridge with `highway=footway` above (`layer=1`).
The renderer shows this footway inconsistently partly above and partly below the trunk, so it seems like missing tags but actually it is mapped correctly.

It is cause by thickness of trunk and by fact, that `highway=footway` is rendered below.

**How to Reproduce**
See: https://www.openstreetmap.org/#map=19/49.22110/16.62138&layers=N
geo:49.22103,16.62134?z=19

**Versions affected**
v21.1 (Google Play)

![Screenshot_20200713-204644_StreetComplete](https://user-images.githubusercontent.com/11516259/87343449-2ad55880-c54d-11ea-94d2-3b01e35e06c4.png)

**Comment by westnordost** [comment]
There are actually two problems here:
1. The rail should be above the motorway
2. that footway

Point 1 was a bug in the stylesheet which is fixed now. Point 2 happened because the footway is only a bridge up to that point - the motorway is drawn wider than it actually is. Is reduced the width of the motorway from 30m to 20m.
