### ISSUE TITLE
Quest: Does this crossing have a pedestrian island?

### ISSUE THREAD

**Issue by FloEdelmann** [westnordost/StreetComplete#1961]
### General

Affected tag(s) to be modified/added: [crossing:island](https://wiki.openstreetmap.org/wiki/Key:crossing:island)
Question asked: **Does this crossing have a pedestrian island?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose ([Taginfo](https://taginfo.openstreetmap.org/keys/?key=crossing%3Aisland) lists 99k items)
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam): I'm not sure about this one. I think most crossings won't have a pedestrian island, but quite a few do. That might vary by region though.
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

**Element selection:**
`nodes with crossing and crossing != "island" and !crossing:island`

**Proposed GUI:**
Simple Yes / No

### Related

* https://github.com/westnordost/StreetComplete/issues/495 (same quest suggestion, but with the older `crossing=island` tag, which doesn't prevent "no" as an answer to stop the quest from reappearing to other users)
* https://github.com/westnordost/StreetComplete/issues/1637 / https://github.com/westnordost/StreetComplete/commit/a609da8c7f0a51c24f6ca5fdd06b0b361b7cf8ec (include `crossing=island` in crossing quest, and set `crossing:island` to `yes` accordingly)

**Comment by mnalis** [comment]
Yeah, after recently enablig this, I'm not sure about "no spammyness", at least in Croatia. We do have a few islands, but they are usually on bigger streets. Currently this seems to be offered even on living and small residential streets. 

I can easily disable the quest for myself, of course, but I was thinking if it might be good idea to perhaps **limit this quest to bigger streets only** (for example, either by `highway` type and/or by number of specified lanes)?

**Comment by westnordost** [comment]
So maybe disable the quest for residential?

**Comment by andrewharvey** [comment]
> So maybe disable the quest for residential?

Please no. It's useful for residential streets too, around me some have an island and some don't.

**Comment by smichel17** [comment]
This is where something like https://github.com/streetcomplete/StreetComplete/discussions/2673 would come in handy, for determining spamminess in different areas. Some analysis of "can't say" notes opened might also be useful for evaluating "Easily answerable by everyone"

**Comment by mnalis** [comment]
@andrewharvey do such residential streets with islands have more lanes, or does it also happen when street has only 1 or 2 lanes?

**Comment by andrewharvey** [comment]
> @andrewharvey do such residential streets with islands have more lanes, or does it also happen when street has only 1 or 2 lanes?

I don't think there's much point trying to say most of the time its like X, unless it's always like X then it's still useful for StreetComplete to ask.

**Comment by mnalis** [comment]
@andrewharvey Well, I have never (not rarely, but **never**) seen **one-lane street with pedestrian island** in my life. In fact, I'm trying hard to remember two-lane residential street with pedestrian island, and coming with nothing... Sure, my experiences are limited to few countries, which is why I asked if you had such experiences, so we can have more views on the issue. 

If you have one-lane streets with pedestrian island in your area, then it might be a keeper. On the other hand, if it happens extremely rarely (or never), than perhaps it should be filtered out to reduce spamminess. 

Also, note that StreetComplete does not ALWAYS offer the quest, but only if it is not very unlikely to happen. See for example [lit quest filter](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/way_lit/AddWayLit.kt#L9) and https://github.com/streetcomplete/StreetComplete/issues/427 (just an example, many quest filter out unlikely situations)

**Comment by HolgerJeromin** [comment]
> In fact, I'm trying hard to remember two-lane residential street with pedestrian island, and coming with nothing... 

https://www.openstreetmap.org/node/8138332244
![image](https://user-images.githubusercontent.com/2410353/123805566-77e14480-d8ee-11eb-82a4-bb521811b942.png)

**Comment by peternewman** [comment]
> @andrewharvey Well, I have never (not rarely, but **never**) seen **one-lane street with pedestrian island** in my life. I can not even imagine how it would look like?

Bike lane, island, one or more road lanes.

**Comment by andrewharvey** [comment]
>  In fact, I'm trying hard to remember two-lane residential street with pedestrian island, and coming with nothing... Sure, my experiences are limited to few countries, which is why I asked if you had such experiences, so we can have more views on the issue.

https://overpass-turbo.eu/s/18XT Most of these are on residential streets, two lane. It's very common.

**Comment by andrewharvey** [comment]
> Bike lane, island, one or more road lanes.

+1

This example probably isn't an island but depending on if paint alone classes as an island it could be. 1 lane because bike lanes don't count.

https://www.mapillary.com/app/?lat=-33.841511305538&lng=151.21166330548&z=17&pKey=227729625785154&focus=photo&x=0.49061463310605896&y=0.5301689211025441&zoom=0.8103975535168195

![2021-06-30_10-03](https://user-images.githubusercontent.com/117278/123882626-84b37600-d98a-11eb-814f-d50c0792f668.png)

**Comment by mnalis** [comment]
@HolgerJeromin I would argue that last part should've been mapped either as two separate ways, or with `lanes=2`. If that last part is mapped with `lanes=1` it is clearly incorrect mapping IMHO.

@andrewharvey thanks for that picture! Yes, that is very illustrative and I can imagine it being island instead of just paint. While ideally that would be marked with `bicycle:lanes=*` and/or `cycleway=lane` as described at [wiki](https://wiki.openstreetmap.org/wiki/Lanes#Crossing_with_a_designated_lane_for_bicycles), I can certainly imagine it sometimes misses details when **only motorized part of the road is mapped** with `lanes=1` and not other road details!

So I can see your point, if such roads happen more than very rarely. Perhaps in that case `lanes=1` when answered with `crossing=island` (and without having cycleway related tags) should trigger `Does this road has a cycle lane?` type of quest on that road? Does that sound reasonable, or do you see situation where it would be wrong? (I'd open new quest if it seems ok)

**Comment by matkoniecz** [comment]
@mnalis If there are some specific improvements to be made it would be better to open a new issue for them. Long comments threads in already closed issues are (at least for me) not the best communication method, as it is possible to discuss endlessly. With multiple, amorphous, unclear or even never defined problem.

If there is some specific problem or enhancement - maybe open a new issue for that?

I get notifications about any comment made on StreetComplete issue tracker and in such cases I need to reread entire discussion to even know what is being discussed.

Maybe for others this would be preferable to discuss new related problems in the initial issue but I will likely start disabling notifications for discussions in old closed issues as it is far too time consuming to follow them.

**Comment by mnalis** [comment]
@matkoniecz I've "moved" this manually to https://github.com/streetcomplete/StreetComplete/discussions/3011 to continue discussion there (probably not the best way, but I the issue is about finding the best way)
