### ISSUE TITLE
provided surface data lost on rotation

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#197]
Basically #161 in new context

To reproduce select add surface quest, select surface, rotate

**Comment by westnordost** [comment]
What do you mean in new context?

**Comment by matkoniecz** [comment]
#161 was also about rotation of phone removing some data

**Comment by westnordost** [comment]
Can reproduce. This concerns the roof select quest as well.

**Comment by westnordost** [comment]
I decided not to fix it. It is a bit more complex and I plan to replace the grouped image select component anyway because there have been so many complaints about the usability of it.

However, the fixed it for the normal image select adapter (roof shapes) because I imagine that this component will be reused more often.
