### ISSUE TITLE
Show the house numbers in all house-related quests

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#1971]
A suggestion:

Always show the house numbers (if available) as part of the quests which relate to houses (house type, roof shape, number of stories and so on). A house number is typically very short (1-3 digits plus 0-2 extensions like letters and special characters) and gives the user more certainty that he is tagging the right building, especially in regions with many similar looking houses and/or bad sat reception.

This would also help mitigate issue #1939 (but there would be no need to remove this feature once #1939 is fixed IMHO).

The cycling cat

**Comment by matkoniecz** [comment]
I admit that it would be useful, even with housenumbers visible on the map I sometimes did cancel-look at map-restart quest.

Though it would increase workload for translators.

**Comment by cyclingcat** [comment]
At least the English word "house number" exists as a separate item in POEditor (label_housenumber). Couldn't this be reused? Alternatively, the house number in parantheses should be sufficient (or would this be too confusing for some users)?

The cycling cat

**Comment by westnordost** [comment]
In light of them missing from the map (currently), this would be an enhancement.

**Comment by westnordost** [comment]
The info could be added in the same place where the info about the level of a feature is placed and *always* for every quest if the housenumber/name/streetnumber/etc. info is available.

Then, the wordings of the quests that currently contain the housenumber in the question can be removed because that info is available just below the question.

Example: https://github.com/westnordost/StreetComplete/issues/1270#issuecomment-455805989

What do you think?

**Comment by westnordost** [comment]
![Screenshot_1595453074](https://user-images.githubusercontent.com/4661658/88230359-8fda2e00-cc72-11ea-9a92-2dfc63688bb2.png)

**Comment by matkoniecz** [comment]
I really, really like this solution.

**Comment by westnordost** [comment]
Then I shall merge it
