### ISSUE TITLE
House number and name

### ISSUE THREAD

**Issue by Cj-Malone** [westnordost/StreetComplete#1983]
Currently with the address quest you can fill out the house number, or the house name. However sometimes an house has both, this means I have to choose which to add, ether the house name and try and interpolate the number later in JOSM, or the number to make interpolating other addresses easier but loses the ability to survey the house name via StreetComplete.

**Proposed Solution**
Currently you click "Other Answers" and "No house number but a name", I think adding another option with "House number and a name" would be a nice solution. Possibly restricted to countries where it's common.

**Comment by westnordost** [comment]
Are you sure it is a `addr:housename` and not just a name?

Anyway, not sure about this. After all, one can always leave a note for such special cases.

**Comment by Cj-Malone** [comment]
Yeah, at least in England when a house has `addr:housename` it's not uncommon for it to also have a `addr:housenumber`.

**Comment by westnordost** [comment]
Okay, I checked some places on Overpass (Leeds, Manchester, Leipzig) and decided to not have this in for now, because:
1. It's rather rare, rare enough that I think that leaving a note instead in such a case will not add too much clutter. Even in England. Actually, `addr:housename` is also used in Germany.
2. If there was such an option in the other answer menu, it wouldn't be guaranteed that (all) people will find it since if they see a housenumber, they will already be able to answer the question, no need to look in the other answers menu for an answer that fits. So, an option wouldn't offer that much of an advantage other than avoid some notes.
3. If a housenumber is indeed assigned, there is no clear distinction whether a name of the building should be a `addr:housename` or `name`. For the former, the expectation is that the post will have this name in their register so that no ["address investigation"](https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FBriefermittlung_der_Deutschen_Post) has to take place. Of course we can't know that, but the expectation is that if the house has no house number assigned but a clearly visible name, the post uses this name to locate the house. For a house that already has a house number assigned, it is not that clear. For example the [Pinnacle Building](https://www.google.de/maps/@53.7978383,-1.544604,3a,75y,278.75h,111.28t/data=!3m7!1e1!3m5!1s2W1ycFUmPBDCPXbI4Admww!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3D2W1ycFUmPBDCPXbI4Admww%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D99.338394%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656) in Leeds ([overpass-turbo link](http://overpass-turbo.eu/s/Wpx)): Is it really a `addr:housename` and not rather a name? All the shops on the ground floor each also have housenumber assigned. You will probably be able to also come up with counter-examples where a house name maps 1:1 to one house number, but my point is that if a housenumber is assigned, the (house) name of the building becomes an *extra* information that is not necessary to record in the same breath to answer the question for the housenumber of a building. And that is the information the user is asked for.

**Comment by Cj-Malone** [comment]
Fixed in #3582
