### ISSUE TITLE
Follow GPS position button disappears

### ISSUE THREAD

**Issue by kudlav** [westnordost/StreetComplete#1990]
**How to Reproduce**
- open app
- there are three buttons: plus, minus, location
- when position is found, location button disappears
- when the user move with the map and app no longer follows location, the button should become visible, to be able to follow GPS again
- now you have to move position away from screen, then press the arrow at the screen edge

**Versions affected**
- App from Google Play - v21.2
- Android 10
- Samsung Galaxy A40

**Comment by cyclingcat** [comment]
See issue #1896. Unfortunately my proposal to change this behaviour has been rejected. You can tap on the small position marker in order to fix it again, however, you have to point at this marker VERY precisely in order to trigger the function. On my 4,5" display I regularly have to try this 2-5 times until it works. Meanwhile I deliberately pan the map in order to get a bigger button at one of the edges of the display. Yes, it's an ugly workaround and I will never understand why the big button in the lower right corner has to vanish. (What else to do with this now empty space?)

The cycling cat

**Comment by kudlav** [comment]
Also https://github.com/westnordost/StreetComplete/issues/1843

The problem is that it is a **toggle button** and as a user I cannot get it why it is shown for few seconds and then hidden.

**Comment by westnordost** [comment]
The reason why I decided not to show it if the own position is in view is mainly because there should be as few buttons as possible that obstruct the map view with the pins.
At least you two and @Atrate have a problem with this.

I am not sure what the process could be to decide if the most users have no problem with the button being gone and/or even like it better this way or the other way round.

Maybe like this: You create a new (non-bug) ticket in which you list the reason(s) why the button should be back (because this and hte other tickets started with the assumption that it is a bug and it's too much cruft to read through now). Then I stick the issue so everybody sees it. People can then vote on it by leaving a 👍  or 👎  and possibly a 👀 on it for "don't mind either way".

**Comment by Atrate** [comment]
@westnordost Did what you suggested in #1996

**Comment by kudlav** [comment]
Hi, just for inspiration:

I really like UI of [Windy Maps](https://play.google.com/store/apps/details?id=cz.seznam.windymaps) (or original Mapy.cz).

There is slider for zooming, and only few buttons. Location button is included and there is also location pin on the map.

![Screenshot_20200803-220935_Mapycz](https://user-images.githubusercontent.com/11516259/89223542-40332500-d5d7-11ea-9412-239d5255cb74.png)

**Comment by westnordost** [comment]
Me too, or actually mapy.cz, I think there is no difference between these two apps, is there?
