### ISSUE TITLE
New quest: Is this parking supervised?

### ISSUE THREAD

**Issue by Atrate** [westnordost/StreetComplete#2005]
### General
Affected tag(s) to be modified/added: [supervised](https://wiki.openstreetmap.org/wiki/Key:supervised)
Question asked: **Is this parking supervised?**

Possible answers:
- Yes
- No
- Differs per time of day (opens time picker)

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by matkoniecz** [comment]
>  Not an overwhelming percentage of elements have the same answer (No spam)

My main worry is that only extreme minority of parkings (at least in my region) is supervised. Is there some way to detect more likely ones?

**Comment by Atrate** [comment]
Maybe filter by size? Larger parkings seem to be more likely to be supervised

**Comment by westnordost** [comment]
There are the following issues I see with this:
1. What exactly is the useful purpose? Why would you want to specifically search for supervised parkings?
2. The vast majority of all parkings are not supervised. It would be quite a spam. Limiting to larger parkings may help, but it is still not ideal
3. **The biggest problem:** Verifiability, Answerability - What makes a parking supervised, how does it look like? I guess there don't have to be signs, but what then? Does there **have to be** a little house at the entrance where you are let in by the supervisor-person? Is it possible that you don't notice that a parking is supervised?

**Comment by peternewman** [comment]
>     1. What exactly is the useful purpose? Why would you want to specifically search for supervised parkings?

Probably because they're felt more secure.

I'd agree though, it's likely to be quite spammy in the UK, with few real instances.

**Comment by Atrate** [comment]
1. Probably for people looking to leave their car for prolonged periods of time, like weeks e.g. close to an airport or train station

**Comment by rhhsm** [comment]
Supervised (guarded) parking may not be very much in demand in Western Europe or North America, but in many countries with car theft problems (including until recently Bulgaria, where I live), knowing if a parking is guarded is highly useful. I see that there are quite a few quests that are never shown in Bulgaria, probably because it's not an issue there, so maybe this quest can be disabled for countries that don't have car theft problems?

**Comment by westnordost** [comment]
Okay, I reckon there is a useful purpose. However, this is not the biggest problem with the quest.

**Comment by westnordost** [comment]
So, problems 2 and 3 remain and I do not see how they could be fixed.

Problem 2 (spam) could be reduced by only asking for parkings with a fee.
But problem 3 remains, verifiability. Do parkings that have surveillance count as supervised? Is a parking not supervised if there is not some guy at the entrance? What about if there is not a guy at the entrance but apparently some camera at the entrance with which you have to interact because the guy is (probably) somewhere else?
I fear if this was implemented just like this, the data quality of `supervised` would be quite bad because probably many places that are supervised may not appear to be or the other way around.
