### ISSUE TITLE
New quest: is a ramp available?

### ISSUE THREAD

**Issue by rhhsm** [westnordost/StreetComplete#2036]
### General
Affected tag(s) to be modified/added: [](https://wiki.openstreetmap.org/wiki/Key:ramp)
Question asked: **Do these steps have a ramp?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [ x] 🚧 To be added tag is established and has a useful purpose
- [ x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [ x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
Great for improved mobility mapping, and should be easy to implement in addition to the handrail quest, with the options and photos in https://wiki.openstreetmap.org/wiki/Key:ramp used. I guess a wheelchair ramp is always separate, so maybe this should be an option to be selected only if the separate ramp is already mapped or a note should be left to ask for it to be mapped. I've never seen a luggage ramp, so maybe this can be omitted as an answer option if it's indeed rare.

**Comment by matkoniecz** [comment]
The tricky part is that separate wheelchair ramp acts (or at least can act) also as a bicycle / stroller / whatever ramp.

**Comment by rhhsm** [comment]
> 
> 
> The tricky part is that separate wheelchair ramp acts (or at least can act) also as a bicycle / stroller / whatever ramp.

I don't see how this is tricky; I think for the user accessibility will be obvious (a bike can use a wheelchair ramp, but a stroller can't use a bike ramp). Maybe the different answers can be described in addition to the photos:
- no: only steps, without any ramp
- bicycle: a single narrow ramp for two-wheeled vehicles
- stroller: two narrow ramps for four-wheeled vehicles
- wheelchair: a ramp, broad enough and not too steep for wheelchairs users to use by themselves. Often mapped separately from the steps.

**Comment by matkoniecz** [comment]
> I don't see how this is tricky

It is extremely hard to find steps except ones where ramp is mapped as a separate `highway=footway`.

Even if you can fetch data, run routing from start to end of steps and check whatever alternative route exists (what is already obnoxiously hard) it will still break anyway on steps with landing micromapped as `highway=footway`.

**Comment by tordans** [comment]
> It is extremely hard to find steps except ones where ramp is mapped as a separate `highway=footway`.

Ideally, those are mapped as `ramp=separate` on the stairs (https://wiki.openstreetmap.org/wiki/Key:ramp#Ramps).

I think I remember, that the sidewalk(?) quest also has a reply saying "the sidewalk is mapped separately" which the user can see on the app-map. Or at least there was a discussion about this a few weeks ago, right?

**Comment by westnordost** [comment]
Right, i also don't see a problem with this quest after reading @tordans comment, or did I not understand anything particular in your comment, @matkoniecz ?

**Comment by matkoniecz** [comment]
If excluding them is not needed/mandatiry then it is quite simple.

**Comment by rhhsm** [comment]
So in addition to the answers I suggested, there may be need for another one:
- There is a ramp, but it has already been mapped separately.

**Comment by westnordost** [comment]
I think it may be better to only support no, stroller and bicycle. Ramps for wheelchairs are usually so big that they are (or should be) drawn as a separate way.

**Comment by matkoniecz** [comment]
> only support no, stroller and bicycle

And maybe also "ramp is already displayed on the map for ones" mapped as a separate way?

**Comment by rhhsm** [comment]
Assuming a wheelchair ramp is one of the most common types of ramps, I think it should be an option to be added. Maybe users need some guidance on what makes a ramp suitable for a wheelchair?

**Comment by westnordost** [comment]
Yeah but usually such a ramp will be mapped as a separate way because it somwhat is. The length of it is a multiple of the steps itself

**Comment by rhhsm** [comment]
> 
> Yeah but usually such a ramp will be mapped as a separate way because it somwhat is. The length of it is a multiple of the steps itself
Some steps have such a gentile incline that a ramp along it would be suitable for wheelchairs. But indeed that would make it tempting to map it separately as a path. Maybe, if a user answers "wheelchair", he should be asked if it is already mapped separately, and if not, to be invited to leave a note?

**Comment by westnordost** [comment]
Hmm, do you have a picture of such steps? All the examples I've seen show a distinc separate path alongside the steps zig-zagging up

**Comment by rhhsm** [comment]
The ramp here is probably a bit too steep for a wheelchair but if they had used the full length available it would have been a good example 
https://maps.app.goo.gl/SMDn1qMpvkaBzau68

**Comment by westnordost** [comment]
Ah yeah, that's a ramp for a stroller actually

**Comment by westnordost** [comment]
So, implementation is almost done but there are a few difficulties with the tagging:

1. `ramp=separate` was not part of the original scheme but was added later after a discussion initiated by @matkoniecz, it's also not part of the JOSM preset for ramps. `ramp=separate` breaks the scheme a bit because it is very well possible that for example a bicycle ramp exists on the main steps and there is a separate way for wheelchairs zig-zagging up the hill. Also, the added value of this information is questionable because as opposed to road ways which engross to encompass all the features of the street (because they carry the street name etc), a footway/steps is generally just a footway/steps. If there are is a stairway and a way that leads up a hill next to each other, they are both equally just ways leading up the hill. So, the quest will probably not ask (ever again) for steps tagged with `ramp=separate` to avoid any problems here. (Problems would be that a surveyor might tag it as "no" but people want it to be "separate")
2. It is unclear if a stroller ramp should be tagged with `ramp:stroller=yes` alone or also with `ramp:bicycle=yes` if it is usable to push up bicycles as well. The tagging scheme seems to suggest that the tags do not define a "ramp type" but define for which things the ramp is usable, so currently I'd tag a stroller ramp with `ramp:stroller=yes + ramp:bicycle=yes + ramp:wheelchair=no` cause any stroller ramp is usable by bikes and any wheelchair ramp is usable by all three
3. It is unclear what is the relation of `ramp:stroller` to [`stroller`](wiki.openstreetmap.org/wiki/Key:stroller), `ramp:wheelchair` to [`wheelchair`](https://wiki.openstreetmap.org/wiki/Key:wheelchair) and `ramp:bicycle` to `bicycle`. **This is a problem** because if these tags are not interpreted (and modified based on the user's answer) correctly, surveys with this app can leave behind inconsistent data, for example if previously `wheelchair=yes` was tagged but the user found no wheelchair ramp. If my interpretation of the `ramp:*` keys are correct (point 2), then apparently there is virtually no difference between these tags. One states "this way can be used by..." and the other states "the ramp of this way can be used by...".

**Comment by westnordost** [comment]
So this is how it currently looks
![Screenshot_1601817224](https://user-images.githubusercontent.com/4661658/95016595-39b33f00-0654-11eb-9f48-e58618bc4011.png)

One idea however how to avoid most of the concerns above would be to throw overboard the current implementation and instead to have two quests with a simple yes/no answer:
- "Do these steps have a ramp to push up bicycles?"
- "Do these steps have a ramp to push up a stroller?"

**Comment by westnordost** [comment]
I pushed my work so far to the ramp2 branch, but this will be stalled until the concerns are cleared up. I posted a thread on the German forum as well as asked on the tagging channel on OSM slack and added some discussion points on the wiki.

**Comment by tordans** [comment]
Thanks @westnordost for this work and the analysis above! 

IMO, ideally one of the data consumers like one of the bike- and accessibility routers could shed some light about what tagging would be useful. Unfortunatelly I don't have the time ATM to research the opensource router interpretation files or reach out manually.

About the "separated":
> …So, the quest will probably not ask (ever again) for steps tagged with ramp=separate to avoid any problems here. (Problems would be that a surveyor might tag it as "no" but people want it to be "separate")

In my mind, I would not answer "no" if there is clearly a ramp, but it's next to the stairs. So in this case, I would eg. answer "wheelchair" and thus add duplicate information on the stairs that are already mapped separately. A router would have a hard time finding out, which information to follow. Which, however, would not cause real problems, since the "driver" can always not follow the router once the situation comes up. I still think that "separate" is the cleaner answer and creates better data, but I also don't see a real problem with leaving it out.

**Comment by rhhsm** [comment]
> About the "separated":
> 
> > …So, the quest will probably not ask (ever again) for steps tagged with ramp=separate to avoid any problems here. (Problems would be that a surveyor might tag it as "no" but people want it to be "separate")
> 
> In my mind, I would not answer "no" if there is clearly a ramp, but it's next to the stairs. So in this case, I would eg. answer "wheelchair" and thus add duplicate information on the stairs that are already mapped separately. 

A similar situation is when you're asked "Is this subway entrance accessible for wheelchairs?" and the entrance itself isn't (steep stairs, escalator) but there's an elevator a little further. https://goo.gl/maps/bt6iZCBVTtsaUFMc7

**Comment by westnordost** [comment]
@tordans I asked here now https://ask.openrouteservice.org/t/roles-of-ramps-in-routing/2164

**Comment by westnordost** [comment]
So for the record, concerns 2 and 3 have been dissolved: `ramp:*` specifies the type of ramp and is very different from an access restriction. The only reason why the tagging schema is a little bit odd here is to enable tagging that multiple types of ramps exist on the same steps. For example on one side a bicycle ramp and on the other, a stroller ramp. Though unlikely, I changed the UI to also support this (multiple selections possible but not particularly advertised in the UI)

**Comment by westnordost** [comment]
done
