### ISSUE TITLE
Change Map appearance If Question is not on ground floor

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#2041]
**Use case**
Some question are marked as  Level -1 or underground, the Problem is, that I sometimes not sure how the map in underground look like because other elements on ground floor or higher overlap the Question. Otherwise, I got Question inside a building about a toilet in the second level but I answered it  according to this a bit different situation in the first level because I missed to look at the level text.

**Proposed Solution**
Change the Map appearance to transparent if it is not on the same level as the question and show the question-level solid. 
Also change the level hint in the Question to a Picture that show the floor level.

**Comment by Mannshoch** [comment]
1. At moment if you are on the map every thing over the ground could be seen and is opaque, every thing underground appears below this bodies (underlay) and is shown transparent. Goal is that if you have to answer a underground question the underground appear opaque and overground Items appear transparent as overlay (or may disappear complete).

1. I mean the text e.g. "unterirdisch:"

**Comment by westnordost** [comment]
> 1

You mean the pin?

> 2

Still don't understand. You want a picture there instead? What kind of picture?

**Comment by Mannshoch** [comment]
1. No, the map. 
When I click on a question that is on level -1, you remove all elements on the map that are on a level greater than -1. 
Change the appearance of all elements on level -1 to 0% transparency. 
Now you have an underground map in front of you. This will help you to better interpret the position and situation of the question

1. If you are not able to change the map design by level, you may could add a kind of graphical level indicator.
e.g.
<img alt=""  width="300" src="https://user-images.githubusercontent.com/7795891/91183912-5753c700-e6ec-11ea-83d7-923214bdc3fd.png"> <img alt=""  width="300" src="https://user-images.githubusercontent.com/7795891/91183500-d7c5f800-e6eb-11ea-83fd-f98097b994c2.png">
or
<img alt=""  width="300" src="https://user-images.githubusercontent.com/7795891/91185901-a995e780-e6ee-11ea-86e3-7779ce109481.png">!<img alt=""  width="300" src="https://user-images.githubusercontent.com/7795891/91186196-05f90700-e6ef-11ea-828f-943459e636d7.png">

**Comment by westnordost** [comment]
> 1.

Okay, this is not possible technically, because the elements on the map do not necessarily have the same `level` tags as available in OSM.

> 2.

Interesting idea with the indicator. However, this is also not possible. A value of  `1` does not mean it is in the first storey. It could also be the ground floor. The `level` tag just indicates an ordering within the building, it is not standardized that `0` is always street level. In the US (, Russia and some other countries), you'll find many buildings who start with `level=1`, not 0. This is not a tagging mistake.
So, this is also why the app just says "on level +/-x", without further "translating" that into "EG" or anything. In other words, we can not derive from the value of the number if it is over- or underground.

**Comment by westnordost** [comment]
This is what is shown in the "on level: X" string:

```kotlin
        /* prefer addr:floor etc. over level as level is rather an index than how the floor is
           denominated in the building and thus may (sometimes) not coincide with it. E.g.
           addr:floor may be "M" while level is "2" */
        val level = tags["addr:floor"] ?: tags["level:ref"] ?: tags["level"]
```
