### ISSUE TITLE
 addr:housenumber quest is not asking for addr:street

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#205]
Addresses are complex topic but at least in Poland just addr:housenumber is not very useful without addr:street.

addr:street data may be easily collected at the same time as adding addr:housenumber without second trip once missing data is discovered.

see for example https://www.openstreetmap.org/changeset/48476823#map=19/50.07902/19.88515 where somebody else is complaining about incomplete edit made using StreetComplete

**Comment by krzyk** [comment]
Besides addr:street also addr:city and addr:postcode is required in some countries.
So it would be good to have possibility to add it (preferably with a prefilled values based on the surrounding addresses)

**Comment by westnordost** [comment]
Yes, add:street_name is a necessary compononet of the address. But while he is standing in front of a house, a surveyor cannot determine the name of the street because street sign are only at intersections. If a addr:street_name is copied from the street name anyway, it can more efficiently be done with JOSM etc anyway. As a surveyor, I would absolutely not like to be forced to enter all this address data since everything except housenumber is dead repetitive and for the most part, I simply do not kbow the current street name, postcode etc.

The same applies to postcode and city.

Am 9. Mai 2017 12:16:38 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>Besides addr:street also addr:city and addr:postcode is required in
>some countries.
>So it would be good to have possibility to add it (preferably with a
>prefilled values based on the surrounding addresses)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/205#issuecomment-300122247

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So, in short, only a house number may not be useful for data consumers, but a necessary step in completing address information that can only be collected on a survey. Survey data is the most valuable data we have.

Collecting the street part of an address is much more cumbersome on a survey and  the postcode almost impossible while that information can easily be complemented later from afar.

Am 9. Mai 2017 12:16:38 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>Besides addr:street also addr:city and addr:postcode is required in
>some countries.
>So it would be good to have possibility to add it (preferably with a
>prefilled values based on the surrounding addresses)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/205#issuecomment-300122247

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> a surveyor cannot determine the name of the street because street sign are only at intersections

In Poland it is typical that housenumber sign includes street name. Also, in cities intersection are really dense so it is trivial to add this info.

https://duckduckgo.com/?q=tabliczka+adres&t=canonical&iax=1&ia=images

![images duckduckgo com](https://cloud.githubusercontent.com/assets/899988/25849605/6dfaa100-34bf-11e7-9281-613202c703a4.jpeg)
![images duckduckgo com](https://cloud.githubusercontent.com/assets/899988/25849604/6df9db62-34bf-11e7-8d7c-9a95109f106f.png)

**Comment by matkoniecz** [comment]
In addition survey is necessary in many cases to complete addr:street as it is possible that correct addr:street is not the name of the nearest street - and for houses near intersection it fails completely. For example http://www.openstreetmap.org/?mlat=50.07773&mlon=19.87955#map=19/50.07773/19.87955

![selection_001](https://cloud.githubusercontent.com/assets/899988/25849790/271e71d4-34c0-11e7-82f5-febdbe11c22b.png)

this house has decent chance to have following addr:street values: Filtrowa, Na Błonie, Zarzecze. It is much less likely but possible to have yet another addr:street. Adding addr:street here requires either import from official data or survey.

**Comment by krzyk** [comment]
I agree with @matkoniecz that figuring out the street name for given housenumber only in JOSM is not trivial (there are multiple strange cases there, e.g. I lived on a street that was on a border between cities, and the street name was different than my address street name).

I also agree that postcode and city is easy enough to fill out in the JOSM so there is no point in adding it here.

**Comment by westnordost** [comment]
I am not convinced yet that it makes sense to determine the street name of any one address while on the survey. Do you have any examples where it would be only possible to determine from a survey or at least be easier than remotely with JOSM?

@matkoniecz example actually serves as an example why mapping which house belongs to which street does _not_ make sense. From the map, you can easily see that housenumber 36 belongs to Na Błonie by following the string of other mapped housenumbers. This is something that would be much harder to realize when you were actually in the field* as it seems the house should be in Filtrowa.

* talking internationally here, in most countries the street name is usually not on each housenumber plate

**Comment by Etua** [comment]
Still it is possible to add such possibility not as an obligation especially when combined with name suggestions as iD does for the new points right now.

**Comment by krzyk** [comment]
@westnordost A common problem is for houses that are near intersections of roads.
Here's an example: http://www.openstreetmap.org/way/431448745

This house is on the intersection, and without survey you wouldn't know which street it belongs to. And from the satellite photo you might think it is on Rezerwistów (because it has a driveway to the garage from that street), but it actually belongs to Na Czekaj street.

Another example near the previous one: http://www.openstreetmap.org/node/3302999187
This one is again near intersection and belongs to one street (and again, has driveways from both streets).

As for which housenumber plate and street name, https://www.google.pl/search?q=house+plate&safe=off&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiy_6Kx0uTTAhVMVSwKHYGjAhwQ_AUICigB&biw=1600&bih=768 suggests that both approaches are popular so it is hard to tell which one is more popular.

**Comment by matkoniecz** [comment]
> Do you have any examples where it would be only possible to determine from a survey or at least be easier than remotely with JOSM?

See https://github.com/westnordost/StreetComplete/issues/205#issuecomment-300142471

For real case see http://www.openstreetmap.org/?mlat=50.07780&mlon=19.88089#map=19/50.07780/19.88089 (I added housenumber with StreetComplete, now I need to resurvey to check whatever it is Zarzecze, Na Błonie or something else).

**Comment by matkoniecz** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/899988/25885770/a08645f2-355a-11e7-938d-77b274cf9fab.png)

What is addr:street here? It is not the nearest street, blind editing with JOSM would result in tagging addr:street=Słowicza, different from the current tag (http://www.openstreetmap.org/node/1915399183#map=19/50.08655/19.89851).

**Comment by matkoniecz** [comment]
> From the map, you can easily see that housenumber 36 belongs to Na Błonie by following the string of other mapped housenumbers. 

The problem is that this heuristic generally works but given complexity of adddr:street making "I guessed this addres data" edits is not acceptable (maybe in say USA addresses are much less likely to be highly surprising but in Poland weird and surprising address situations are normal).

**Comment by matkoniecz** [comment]
Or another surprising one 

![selection_003](https://cloud.githubusercontent.com/assets/899988/25886021/fe0b0306-355b-11e7-8aab-c18feeca8bae.png)

It has addr:street that is neither Racheli or Złoty Róg.
http://www.openstreetmap.org/way/230244928#map=17/50.08135/19.89476

http://www.openstreetmap.org/way/230244928#map=19/50.08120/19.89578

**Comment by HolgerJeromin** [comment]
I think we can summarize that there are situations where a survey is needed and some where an overview is needed.
[This house](https://www.openstreetmap.org/way/162541531) has no street name on the wall. I had to guess from the surrounding numbers that it does not belong to Narzissenweg.
![image](https://cloud.githubusercontent.com/assets/2410353/25886053/2bfc77f4-355c-11e7-9f92-46edab210e7f.png)

So a drop down with surrounding street names with the default "do not set/change" is probably the best solution.

**Comment by westnordost** [comment]
@HolgerJeromin and @matkoniecz: Wait, are you arguing for or against adding a street name field? Because all your examples work as examples for that the heuristic of following the string of housenumbers (from looking at the map) works better than trying to find it out on the survey. 😕??

The two examples from krzyk, though, are wicked, there the heuristic does not work. But again, we are not talking exclusively about Poland here, so we cannot assume that the street name is given on all the house number plates. So, even when the surveyor is looking at the street signs, he would still probably get it wrong or would not be able to answer this.

But why am I even arguing against having this input field since there are certainly cases where it makes sense to add the street name if the surveyor knows it? Because it has some downsides, obviously, so I need to balance that. Here are reasons that weigh on the other side of the said balance:

### Would make form more complex
The forms, though, should be as easy as possible. There was already some confusion regarding the building levels quest because it has two fields.

- the form must scroll to accomodate a second street name input. As soon as the form needs to scroll, it becomes much more cumbersome to quickly click through (see surface quest and the X open issues I have for that). Being able to quickly click through is a very important feature for a quest such as housenumbers is very important for usability.
- it must explain in clear words that to enter a street name is optional, further blowing up the form. Still, many users will want to fill out the street name right away if it is part of the form. I foresee that would give me a lot of complaints that entering housenumbers is too time-consuming, leading to feature requests like "auto fill in closest street name" which I naturally need to decline since this may lead to wrong data as we see through the examples here

### Optimize for the common case
In general, the quest forms should be designed in a way that it is easy to input it for the common case hile not making it impossible to input for the edge cases

- Leaving out the street name of this input altogether does no harm because it does not make impossible that a street name is added later.
- What would make it impossible or at least much more difficult (to detect), was, if a _wrong_ street name is entered. Since with a street name input, the street names would be sorted by distance, there would be the danger that the user prematurely chooses the street closest to him as experience showed to him this is correct for pretty much all of the cases. We know by the examples brought up here that sometimes, this is not correct. **Expecting the user to always be very cautious and double check an information he cannot possibly quickly check without looking at the big picture, is unrealistic, to say the least!**
- A street name input is only warranted through the few edge cases where street names can not be simply determined from looking at the map, which applies to the vast minority of house numbers. For edge cases that are _not_ covered via the "Other Answers..." button, there is always as you know the "leave note" button.
- Did you know that notes that are formulated as questions (contain a "?") are displayed to StreetComplete users as quests?

### Implementation effort
- adding the street name input (as dropdown of near streets) requires more implementation effort and more overpass queries done:
  - the implementation effort is not to be underestimated, since the app needs to store the surrounding street names for each housenumber persistently in local storage and clean this up when quests are solved. Finally, it needs to show the street names sorted by distance to the building (possibly distance between multipolygon and long linestring). Neither of that is trivial.

### Workflow
- assuming an area where previously no housenumbers were inserted, a pattern which house belongs to which street only becomes apparent _after_ the survey

My proposal for these kind of edge cases presented by @krzyk are to write a note at the position of the building after street names have been entered through JOSM, asking something like: "to which street does this house belong?".
This note will then appear in the StreetComplete application as a quest, asking the user to contribute to the note. He can then set out to clear up that one edge case.

**Comment by krzyk** [comment]
@westnordost Makes sense. But I have a follow up, wouldn't it be a good idea to add a separate quest for adding street names to addresses that already have housenumbers? This would leave only the *implementation effort* from the above list.

**Comment by HolgerJeromin** [comment]
> Did you know that notes that are formulated as questions (contain a "?") are displayed to StreetComplete users as quests?

Wow. 
We really need a documentation for the magic of the quests :-) containing a string is surprising. I thought every note was presented here 
 #194

I understand your work flow issues with adding the street name. 
Perhaps the street name is better filled in vespucci which leads me to: Using geo intends #190

**Comment by matkoniecz** [comment]
> I suggest to create a new issue for that, link that issue to this one and close this one.

OK
