### ISSUE TITLE
Give the users the possibility to mark private ground as such

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2051]
Hi there,

when I deliberately walk/ride to a road surface or handrail quest I have to hide it surprisingly often, because I'm not able to answer it without entering private ground. (Sometimes it's possible to solve the quest with a peek over the fence, but often it's not.) This is probably due to the fact that I live in a well-mapped region where road surface quests are getting more and more rare, so the percentage of missing tags on private ground is quite high here, because noone has been able to answer it so far. Leaving a note in those cases is quite boring, but wouldn't it be possible to catch this case with StreetComplete in a reasonable way?

**Suggestion:**

Add a third menu item "Private ground" (or similar) to the "More answers" menu. If a user taps on this item, add an "access=private" tag, assuming that StreetComplete will never show quests about private objects which automatically hides this quest to other users in the future.

The cycling cat

**Comment by westnordost** [comment]
In cases like these, you can and you are supposed to leave a note instead so that it can be tagged as private. I'd rather not add this to the other answers because I think a note is more valuable in this case: A way/stairs/road etc. that are private but not tagged as private are rarely alone. If you found out that a certain area is not public, a note will help to mark the whole area as private (all ways etc in the area).
Also, I'd like to pollute the other answers menu with as few items not directly related to the question itself as possible.
