### ISSUE TITLE
Stale OSM data

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#206]
I've added few streets in my neighborhood 3 days ago and the StreetComplete map doesn't reflect those.

Same for addresses, I've added them using JOSM (2 days ago), but in StreetComplete I still have quests for adding those addresses.

Is there a way to force a fetch of fresh data/clean cache? I tried setting cache to 1MB, but it doesn't help.

**Comment by matkoniecz** [comment]
In settings there option how long quests are cached. What is your setting?

Map cache size applies only to map tiles as I understand its description.

**Comment by westnordost** [comment]
No. The map shown is not based on 100% current data, I don't know how often mapzen regenerate their vector tiles.

Am 9. Mai 2017 12:12:11 MESZ schrieb "Krzysztof Krasoń" <notifications@github.com>:
>I've added few streets in my neighborhood 3 days ago and the
>StreetComplete map doesn't reflect those.
>
>Same for addresses, I've added them using JOSM (2 days ago), but in
>StreetComplete I still have quests for adding those addresses.
>
>Is there a way to force a fetch of fresh data/clean cache? I tried
>setting cache to 1MB, but it doesn't help.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/206

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
> but in StreetComplete I still have quests for adding those addresses.

I think this issue is not about the base map.

I had changed a way from building=yes to building=house. After that streetcomplete offered me a missing housenumber quest. After i found this i [corrected](https://www.openstreetmap.org/changeset/48486857) it to building=garage.
Now we have 40 hour after that fix and still i got the housenumber quest shown.

**Comment by westnordost** [comment]
Ah.

Well, this is what the "quests cache" option is for. Quests are only refreshed from server (and thus deleted if they are obsolete) earliest after the time specified there passed. After that time passed, obsolete quests are removed next time the quest type is downloaded.

For more details and why I intend to remove that option, see #141

Am 9. Mai 2017 14:10:14 MESZ schrieb Holger Jeromin <notifications@github.com>:
>> but in StreetComplete I still have quests for adding those addresses.
>
>I think this issue is not about the base map.
>
>I had changed a way from building=yes to building=house. After that
>streetcomplete offered me a missing housenumber quest. After i found
>this i [corrected](https://www.openstreetmap.org/changeset/48486857) it
>to building=garage.
>Now we have 40 hour after that fix and still i got the housenumber
>quest shown.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/206#issuecomment-300143896

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
My quest cache settings is and was 1 day (is this exactly 24h or 1 day without time?). 
Clicking "Search here for new quests" now solved my issue. The quest is gone.

**Comment by westnordost** [comment]
1 day is 24 hours.

**Comment by HolgerJeromin** [comment]
The manual "search here for quests" menu item should update all quests regardless any cache options. 
I yesterday specialized 1400 building=yes buildings to get my home town flooded with building level quests :-)
Having to waiting for a timeout is not optimal if we already have and manual "search here" trigger.

**Comment by westnordost** [comment]
I'll reopen this ticket to serve as discussion thread.

I would argue that the use case of an experienced JOSM user wanting to spawn StreetComplete quests (for himself) is quite an edge case. I do not really intend to make it very transparent for SC users when quests appear etc. because it means to concern him with how the internals of OSM (and the app) work, which he - ideally - shouldn't need to care about. This is one reason I plan to remove the "cache quests" option from the settings and instead set it to some global default.
Also, I am planning to artificially reduce the amount of quests that are shown at once on the map, so that the user is not overwhelmed with things to do but can follow a string of single quests in his vicinity. 

**Basically, it should be balanced that he will not run out of quests but at the same time is not overwhelmed by them. My solution to that would be, as mentioned, only show a few quests in his vicinity - so there is always something to do if he wants to contribute but never so much that he it feels like work. (I.e. all those street surface quests littering the map currently is not okay in my opinion)**

Now you know where I am coming from, what I would like the app to behave like and what is important to me regarding the display of quests.

For experienced JOSM users like you, there could be a "clear quests cache" option in the setting or something. As long as this option is in some "advanced" section of the options, I'd be okay with that.
What is important to me is that ingenuous non-OSM expert user does not consider a behavior as a bug or unintended behavior.

**Comment by HolgerJeromin** [comment]
Keep Right shows only x errors on the map **counted from the middle of the screen**. This is surprising, but probably a good interface here, too.
![image](https://cloud.githubusercontent.com/assets/2410353/25902500/fd84f2fa-3599-11e7-92c0-efa971ef7d23.png)

With many quests you have only a few things visible in your vicinity but scrolling can show you other stuff, too. And zooming out would not overwhelm a user with 1400 open building levels, but focus on the vicinity :-)

**Comment by westnordost** [comment]
Yeah, something like that. Though, any such behavior is currently still blocked by other things, so this will be something for the future.
