### ISSUE TITLE
System requirements?

### ISSUE THREAD

**Issue by vassilevsky** [westnordost/StreetComplete#2093]
Hello :)

I don't have an Android-powered device at the moment. I need to buy one.

What are the minimum and recommended hardware requirements to run this app?

* Operating memory size — most devices I see on the local market have 4 GB — is that enough?
* Storage size — does it cache a lot of map data? I saw an issue here that it can't use a memory card. Is this still true?
* Screen size — is a phone screen enough or is it better to get a phablet or a tablet?

Any additional info would be cool as well.

Thanks!

**Comment by matkoniecz** [comment]
> Operating memory size — most devices I see on the local market have 4 GB — is that enough?

Yes. It worked perfectly fine also on 2 GB one (Redmi 4).

> Storage size — does it cache a lot of map data?

Right now on my phone it is using 434 MB (with heavy usage in multiple locations and during road trip).

> I saw an issue here that it can't use a memory card. Is this still true?

See how the issue was resolved - by making it movable https://github.com/westnordost/StreetComplete/commit/d05ffd9c6087978c0a319b2eb328839f94f8da5f (though I keep on memory card rather downloaded maps of mapy.cz, Osmand, Magic Earth and so on - I never tested this).

> Screen size — is a phone screen enough

yes (Redmi 4 has a pretty small screen). Tablet sized screen may have some poor handling of that space instead (not sure whatever no one bother to report issues or is there no problem of any kind, but most active contributors are using small or small and normal screens, with no or minimal use of tablet-sized screens).

**Comment by smichel17** [comment]
I have a Galaxy S6 (SAMSUNG-SM-G920A). Streetcomplete runs fine on it; I think you'll only run into performance issues on very low-end devices, which it sounds like you are not looking at.

I just opened SC, panned around the map for a few minutes refreshing, opening various quests, and generally trying to get as much into ram as possible. Ended up using 250MB. Note, though, that memory usage can vary by quite a bit by device. Red Moon (a screen filter app I develop(ed)) uses 65-75MB on my phone but only 10-20MB on some older phones. I *suspect* it mostly has to do with screen size and thus, it's a fixed ~50MB extra on my device, not a multiplier.

As for storage, SC on my phone has an install size of 72MB, and is storing 5MB of data and 3MB of cache. However, I cleared the data/cache recently, I think. The app has a setting for how large its map tile cache can get. The largest value is 250MB. I don't think it will use more than ~400MB total under *any* circumstances.

Screen size is your preference. It will run on small phones just fine, but I think it's nicer on a bit larger of a screen (same for any other mapping/navigation app) -- easier to look around. I'd probably still stick with a phone though (not a tablet), since you'll be carrying it around with you while you map; SC is intended as a survey app, where you walk/bike around to answer the questions as you're actually looking at the site in question, not an app like JOSM for editing from your home.

**Comment by matkoniecz** [comment]
> The largest value is 250MB. I don't think it will use more than around 400MB total under any circumstances unless you're @matkoniecz, apparently.

434 MB is with modified version that dowloads more quests, has more quests and was heavily used in two cities and 2 towns and used during road trip. And I would expect that it will go down as quests will expire and cache will be dropped.

Or when I will reinstall it and use just in one location.

**Comment by matkoniecz** [comment]
> You should check if the phone you are going to buy will support ARCore.

Though not supporting it would disable only this new quests, everything else will continue to work.

**Comment by westnordost** [comment]
Here is the list of devices that support ARCore: https://developers.google.com/ar/discover/supported-devices

I'll close this ticket as the question has been answered.

**Comment by rugk** [comment]
BTW, for anyone having a Google-free or only microG device which is otherwise compatible, I have a big news for you:
**You can (very likely) use StreetComplete's AR mode just by installing one proprietary app.**

The reason is that the ARCore (Play Services) app is a separate app, [which I could just install from Google Play](https://play.google.com/store/apps/details?id=com.google.ar.core) (via Aurora Store or wherever you get your apps from). According [to Exodus there are also not a lot of trackers, basically just the one you get with Google Play Services lib](https://reports.exodus-privacy.eu.org/de/reports/com.google.ar.core/latest/).
Also, you can just disallow all internet connections for the respective apps. (if your custom ROM supports that)

I now also tested it with StreetComplete and it works flawless.
I have microG installed, but it did not look as if any of that was used ([as it does not support any of that](https://github.com/microg/GmsCore/issues/1672)), as such I guess you can also just install and use that on CustomROMs without any Google Play Services.

Pixel 4 with CalyxOS 3.3.0 and microG

**Comment by westnordost** [comment]
That's interesting and very cool. 

I was under the impression that ARCore app would actually check that list of supported devices I linked to earlier before even starting to do anything useful. 

Did you test whether it also works if you do not block the internet connection for the arcore app?

Yes,  this could be added to the faq, best if someone who went through the process of sideloading arcore from somewhere else for that (like you) though.

**Comment by rugk** [comment]
> I was under the impression that ARCore app would actually check that list of supported devices I linked to earlier before even starting to do anything useful.

It does, but I have a supported device. (just a CustomROM as stated in the post). I assume on not supported devices it still does not work.

> Did you test whether it also works if you do not block the internet connection for the arcore app?

Yes ikt's blocked, does not change anything. (also should not, after all, for what should it need internet access)

> Yes, this could be added to the faq, best if someone who went through the process of sideloading arcore from somewhere else for that (like you) though.

I'll do that. And it's rather more or less the official installation way other than sideloading… ARCore is delivered via Google Play… (I just use a rather… unofficial… client to access it)

**Comment by westnordost** [comment]
> also should not, after all, for what should it need internet access

For downloading the list of supported devices to return whether its installed on a supported device or not. Maybe there is a loophole: E.g. if ARCore is denied internet access on a non-supported device, it will still work. If this is the case, this is something that could be documented in the FAQ.

@matkoniecz don't you have a non-supported device? Care to try this out? Maybe we can make the measuring work on your device after all. In short, follow the sideloading ARCore instructions from @rugk, then go to settings and disallow the access internet permission for the ARCore app.

**Comment by rugk** [comment]
BTW if your system does not have a built-in way of denying internet access, you may use one of the many apps for it, [like this one](https://f-droid.org/packages/com.celzero.bravedns/) (not tested).

**Comment by rugk** [comment]
BTW, what you suggested likely won't work, because the "list of supported devices" is hardcoded [by device profile](https://developers.google.com/ar/develop/device-certification). How I know it's hardcoded? The latest [release notes on Google Play](https://play.google.com/store/apps/details?id=com.google.ar.core) mention an updated device list.

**Comment by rugk** [comment]
BTW FAQ has been added: https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#What_are_the_system_requirements_of_this_app.3F
