### ISSUE TITLE
Allow for multiple postbox collection times on the same day

### ISSUE THREAD

**Issue by kmpoppe** [westnordost/StreetComplete#2108]
**Use case**
When being tasked to add collection times for a postbox or opening hours for a business, the "standard" behaviour for the weekday picker is that weekdays, that were already selected are no longer activated.

In the case of the postbox I worked with today (https://www.openstreetmap.org/node/2388572099), I had to re-selected Mo-Fr three times to add 4 collection times during the week.

Also, in the not so progressive German business landscape there are still those, who have a lunch break - which leads to the same problem, needing to re-select the weekdays.

**Proposed Solution**
The `TimePickerDialog` (collection times) and `TimeRangePickerDialog` (opening hours) ought to display a checkbox "add more times for the same weekdays" that you can check (default: unchecked), which restarts the dialog to add another Time or TimeRange.

I haven't got enough experience with the app development yet, to propose a code change for this myself and would require input.

Kai

**Comment by westnordost** [comment]
Lunch break for collection times? Are you mixing up something?

**Comment by westnordost** [comment]
For opening hours, it is actually possible to specify multiple hours for the same weekdays since v23.0.

I have no objection against changing the collection times form in a way that when you tap the "add times button", there will be a popup menu which lets you choose to either enter new days or enter new hours, just like in the opening hours form.

If you would like to do it yourself, it is not that hard.

see `AddCollectionTimesForm` line 55 for when the button is tapped.
and see `AddOpeningHoursForm` lines 78ff for when the button is tapped for the opening hours.
In the `CollectionTimesAdapter` you'd need to add a new method for only adding new hours, not new weekdays, see the `addNewHours` method in `RegularOpeningHoursAdapter`

**Comment by kmpoppe** [comment]
> For opening hours, it is actually possible to specify multiple hours for the same weekdays since v23.0.

When doing map maintenance yesterday I didn't add times, so I didn't see that. Did I miss that point in the what's new of 23.0?

> see `AddCollectionTimesForm` line 55 for when the button is tapped.
> and see `AddOpeningHoursForm` lines 78ff for when the button is tapped for the opening hours.
> In the `CollectionTimesAdapter` you'd need to add a new method for only adding new hours, not new weekdays, see the `addNewHours` method in `RegularOpeningHoursAdapter`

Thanks for the detailed description. I'll see if I'm able to incorporate that!

K
