### ISSUE TITLE
resurvey of cycleways does not show the old value on oneways 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2120]
While the resurvey quest for cycleways work fine for non-oneways, there seem to be an issue with the loading of the old value or the rendering of it on oneways:

![Screenshot_20200929-023701](https://user-images.githubusercontent.com/614929/94499530-37d52000-01fd-11eb-8573-3bc531cbf5bb.jpg)
![Screenshot_20200929-023637](https://user-images.githubusercontent.com/614929/94499537-3ad01080-01fd-11eb-8efd-8630c3508336.jpg)

**Versions affected**
v23.0

**Comment by RubenKelevra** [comment]
Okay, this issue doesn't seem to be related to oneways, it also happens on two way roads:

![Screenshot_20200929-024749](https://user-images.githubusercontent.com/614929/94499996-5ab40400-01fe-11eb-85b6-dd50afb7a449.jpg)

**Comment by matkoniecz** [comment]
Can you link affected location? Maybe it is not tagged or is tagged in way that is impossible to interpret reliably?

EDIT:

https://www.openstreetmap.org/way/33645945/history was easy to track down, based on street names (case where `cycleway:both=no` was displayed as expected - https://user-images.githubusercontent.com/614929/94499537-3ad01080-01fd-11eb-8efd-8630c3508336.jpg )

I also tracked down https://www.openstreetmap.org/way/113373282 with `cycleway:right=lane oneway=yes` not displaying it and asking user to fill it ( https://user-images.githubusercontent.com/614929/94499530-37d52000-01fd-11eb-8573-3bc531cbf5bb.jpg )

Third one I was unable to find quickly.

**Comment by westnordost** [comment]
Yes, this is kind of deliberate. Whenever there is an **invalid or ambiguous cycleway tagging**, StreetComplete will show the cycleway as undefined rather than trying to interpret ambiguous data in one way or another.
In particular, the popular `cycleway:*=lane` without any `cycleway:*:lane=*` tagging is deemed by the app as ambiguous, because it could either be an exclusive lane (de: Fahrradstreifen) or an advisory lane (de: Schutzstreifen).

The minor inconvenience here is that the question should in such cases (where all shown sides are undefined) not suggest that the current state of the cycleway situation is shown but instead treat the situation as if it has never been tagged.

**Comment by HolgerJeromin** [comment]
Could we adjust the title / description in this case? So show/describe it as a normal survey quest.
Got it today with
https://www.openstreetmap.org/way/24149284

**Comment by peternewman** [comment]
> Could we adjust the title / description in this case? So show/describe it as a normal survey quest.

That's exactly what I proposed in #3129 @HolgerJeromin when I worked out what was going on!
