### ISSUE TITLE
Postbox collection times quest pops up despite that it's already in the database 

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2136]
I've downloaded an area manually where the app had no quests. 

I noticed that an quest for an postbox popped up, which I've already did like a year ago. 

![Screenshot_20201005-104913](https://user-images.githubusercontent.com/614929/95084938-dcd08b00-071e-11eb-9b97-efa754ccb094.jpg)

And the node's tags in Vespucci:

![Screenshot_20201005-104900](https://user-images.githubusercontent.com/614929/95085025-f2de4b80-071e-11eb-838a-ddad05969bf6.jpg)

**Versions affected**
Android 10
SC 24.0-beta1

**Comment by kmpoppe** [comment]
Hi Ruben, this is a known behaviour. It's the resurvey quest asking for the collection times, rather than showing the current listed times. This was already discuessed in #2105 and #2109 and won't be addressed as of yet.
K

**Comment by RubenKelevra** [comment]
Ah! I thought all resurvey quests would show a yes / no question first with the old data 😕

**Comment by kmpoppe** [comment]
Yes and no. Opening Times are yes/no, but this has to be done for every quest in the list - and collection times are more complicated (because you need to create the list first from what's in the node) before showing and @westnordost didn't deem it worth the effort when he made the resurvey live. Maybe someone can build this in the coming months.

**Comment by RubenKelevra** [comment]
Thanks for the detailed explanation, makes sense now :)
