### ISSUE TITLE
New quest: building entrance

### ISSUE THREAD

**Issue by tuukka** [westnordost/StreetComplete#2137]
Thank you for the great new quest on what street does the housenumber belong to! As a continuation to improving addresses, it would be great to collect the locations of the main entrances to each building.

### General
Affected tag(s) to be modified/added: [entrance](https://wiki.openstreetmap.org/wiki/Key:entrance)
Question asked: **Where is the (main) entrance(s) to building X?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation

Should be similar to splitting a linear way at a point where its properties change.

**Element selection:** This should be improved for some special cases but hopefully works as a starting point: https://overpass-turbo.eu/s/YIM

**Metadata needed:** N/A

**Proposed GUI:** Tap on the entrance location along the building outline. Two buttons: Done and Add another (entrance)

**Comment by westnordost** [comment]
This is not possible with StreetComplete, see https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#limitations-of-streetcomplete

**Comment by tuukka** [comment]
I'm sorry if there was already a discussion about this. Can you point me to it? Otherwise, I'd like to propose this as a reasonable exception to the general rules.

**Comment by westnordost** [comment]
It is a technical limitation of StreetComplete

**Comment by tuukka** [comment]
Oh, I didn't realise that. I had a quick look at the way splitting and thought it would be similar to what's already in westnordost.streetcomplete.data.osm.splitway.

**Comment by westnordost** [comment]
Well, splitway is not exactly little code. It is correct that splitway creates new elements, and of course whenever I say that something is not possible, as a developer yourself, you know it's not actually impossible but just (far too) much effort to be worth it.

**Comment by westnordost** [comment]
So, even though I see the benefit of this quest and your suggestion for an interface sounds good, this is not going to be implemented anytime soon, probably never.

Additionally to the more effortful implementation of the UI (keep in mind that the entrance position must "snap" to the building outline, so the app must know the outline of building for each add-entrances-to-building-quest during offline usage), it requires the app to "learn" saving diffs generated by the user's answer not only by tags added/deleted but also at least new elements added and also apply them correctly, plus solve automatically solvable conflicts automatically.
But that's not all, actually that is not enough for this quest: It is not only necessary that new elements can be added, it is also necessary that existant ways can be modified by adding new nodes in its midst because the entrances must be nodes on the building's outline.

This is why I said it is not possible. It is just far too much effort to add the functionality necessary to create such a quest to StreetComplete.

**Comment by tuukka** [comment]
Thank you for the feedback and I fully appreciate this is outside your roadmap. If someone else was to create a pull request though, could it be possible to merge it under some conditions, or would it just take the codebase in a wrong direction? To get a first estimate on the baggage it would add, I counted the lines of code:
`de.westnordost.streetcomplete.data.osm.splitway` 584 lines vs
`de.westnordost.streetcomplete` 36466 lines total.

**Comment by westnordost** [comment]
A PR would be fine, I already gave a rough outline what would need to be done to enable this functionality. But to anyone who wants to do this, I'd say: There are many more low-hanging fruits that are less effort to implement and will improve the app more! Just have a look at all the things tagged with "enhancement" in the issue tracker.

**Comment by smichel17** [comment]
If anyone's interested, here's a breakdown of the code base by file size:
![image](https://user-images.githubusercontent.com/6563664/95220874-7020c380-07e6-11eb-8eff-1214a3faf643.png)

And just the `data` folder:
![image](https://user-images.githubusercontent.com/6563664/95221747-4d42df00-07e7-11eb-8970-307593a591fc.png)

Not going to go any deeper than that, but `splitway` is the second largest folder under `osm`, the purple one that the line goes through (the largest is `osmquest`).

**Comment by Cj-Malone** [comment]
I sometimes think about how easy it would be to add crossings with StreetComplete. Easy for the users, not so much for the developer. So if entrances get implemented I'd vote for crossings too, but I understand it's not the direction you want to take StreetComplete.

**Comment by smichel17** [comment]
Well, that has a separate problem, which is: how would you populate quests for it? You couldn't even go the spammy way and asked for every single road, because what if it's farther down the road, out of sight? it'd be like the speed limit quest, except even harder, because that one you can walk down the road and answer when you reach the end, but crosswalks can only be mapped when you are near them. So the flow would have to be something like: open quest, walk down road marking crosswalks as you go, then submit them all to complete the quest when you get to the end. But this would mean you couldn't answer any other quests while you were in the middle of this one… not so good.

A more reasonable way would be asking for crosswalks *at intersections* specifically. But you'd need a way to make it not spammy, and I suspect many more of these are already mapped.

**Comment by Cj-Malone** [comment]
I wasn't imagining crossings as a quest, rather as a menu option when long pressing a road.

**Comment by waldyrious** [comment]
Just leaving a video reference ([original source](https://od4m.limos.fr/static/balluchon_v2-demo.mp4)) of a nice, beginner-friendly UI for adding building entrances, implemented in the [Balluchon](https://od4m.limos.fr/) web-based tool, recently [announced in weeklyOSM 616](https://weeklyosm.eu/archives/15576#wn616_software)

https://user-images.githubusercontent.com/478237/172070384-e1e26d50-e08f-4638-9a05-a34ce2fd9707.mp4

I think if StreetComplete ever had this functionality, this kind of UI would fit right in with how other similar quests have been implemented in the app :)
