### ISSUE TITLE
step_cout can't be counted correctly for splitted steps

### ISSUE THREAD

**Issue by DerDings** [westnordost/StreetComplete#2144]
Sometimes one stairway is represented by multiple osm ways. This is often the case when certain properties change along the way, e.g. the stairs are partly covered or they have changing surfaces along.

In this case, one cannot always exactly tell from the map view for which part of the steps is currently asked for. This will probably lead to people counting all steps and entering this number, even when the quest is only for a part of the steps. Later they'll be asked again for the second part and enter the whole number of steps again, assuming their first answer wasn't saved correctly or something like that. This will lead to a total number of tagged steps which is twice the real number (or even three times as much when steps are divided in three osm ways)

**Versions affected**
StreetComplete v24.0+

**Possible solution**
Query if there are other highway=steps elements around (let's say 3 meters?) the end nodes of the way which is asked for.
Then,
1. As a simple hot-fix, don't ask for those steps at all
2. Compare the way with the other steps around. If every steps-way has a level tag, check if the level of the current way is different from all other levels. If so, nonetheless ask for the step count, but include the level in the question like "How many steps are here? (level 0-1)"
If this is done, maybe even the [criterion ](https://github.com/westnordost/StreetComplete/blob/551207062006f692b358e5b20d0a37f0b898b886/app/src/main/java/de/westnordost/streetcomplete/quests/step_count/AddStepCount.kt#L13) `(!indoor or indoor = no)` could be removed, because it already makes clear which steps are actually asked for.
3. (To exclude even less ways, maybe even check for other differences. For example, compare the way with the other steps if the surface of the current way is different from the other surfaces. If so, ask for the step count, but include the surface in the question like "How many steps made of paving stones are here?" This seems a very special case, but if a way is split, it was probably done to tag some differences between both parts. So maybe checking for them is worth the effort.)

**Comment by DerDings** [comment]
related to #2145

**Comment by westnordost** [comment]
Well, if that was a problem, then the same would apply to any other quest type that is asking for a section of a way: surface, sidewalk, cycleway, parking lanes, etc etc. The number of steps is asked for the highlighted section, just like for every other quest type.

As you say yourself, if the steps are split up along the way, then it must have a good reason - part of it covered, different surfaces, different steepness etc. Also, if he is unsure until which point he is supposed to count the steps, he can always leave a note and describe the situation. I think since the user is on-site, has GPS on his phone and sees his location, plus an openstreetmap map, plus has the possibility to make a phone, these are the best preconditions for tagging/counting it correctly, can't get any better.

> "How many steps are here? (level 0-1)"

Actually, the level is displayed, when one is tagged.
