### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#2157]
[Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) – a project promoting open source contributions – is running this month.

As [they have changed the rules recenty](https://dev.to/devteam/hacktoberfest-etiquette-for-contributors-ec6) you do now have to tag your repository/repositories (=set a GItHub topic) if you want to have participated in this with the tag `hacktoberfest`.
AFAIK you can alternatively also [tag single PRs with `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#details) to mark them as a valid PR. (Otherwise all merged or positively reviewed PRs count.)

Could you do so, so one may send some PRs and participate there?
I guess for (new) contributors adding a new quest or fixing an existing one could be a quite useful task for Hacktoberfest.

**Comment by westnordost** [comment]
I am not sure if it is easy enough to contribute PRs to StreetComplete to qualify. (I understand it should be projects with an easy entry barrier.) @matkoniecz mentioned something like that the iD project would probably not be a good candidate because it's too involved, while the NSI probably is.

Sure, it is easy to contribute **something**, like suggest a new quest type, or do the research necessary to add a new quest type (like #2128) or feature, or do other research to add a new feature (like #1929), but all that wouldn not result in a PR.

**Comment by rugk** [comment]
Hmm yeah, dunno. It does not always have to be a quest though, could also be a quest fix. Even a doc fix or a simple [update of my crops data](https://github.com/rugk/crops-parser) would count. But yeah, generally it would be good if there were easy entry tasks.

**Comment by westnordost** [comment]
I don't have a problem tagging every single PR in october with hacktoberfest-accepted, but I don't think StreetComplete is eligible for an influx of random contributors (out to get some swag ;-) )

**Comment by matkoniecz** [comment]
> I don't think StreetComplete is eligible to promote it for hacktoberfest because PRs are not so easy and require some involvement.

While #4418 is not trivial at all, I think that it may be example of something fitting

**Comment by peternewman** [comment]
> I don't think StreetComplete is eligible to **promote** it for hacktoberfest because PRs are not so easy and require some involvement.

What about icons for future quests too, which would need less effort to do, but it might be hard to keep a fairly unified style that way.
