### ISSUE TITLE
Handrail wird doppelt eingetragen

### ISSUE THREAD

**Issue by OSMmapper** [westnordost/StreetComplete#2162]
Mir ist aufgefallen das bei Treppen welche bereits "handrail:right=yes" und/oder "handrail:left=yes" beinhalten,
zusätzlich jetzt noch der Tag "handrail=yes" eingefügt wird.

Denke dies ist ein Doppeleintrag ohne Mehrwert.

**How to Reproduce**
Suche eine Treppe, welche bereits "handrail:right=yes" und/oder "handrail:left=yes" beinhaltet.

**Versions affected**
StreetComplete 24.1

**Comment by westnordost** [comment]
I am going to answer in English because this is nothing specific to German or Germany.

Without additional value - maybe. But this is how the tag is defined in the wiki. `handrail` should always be set, `handrail:*=*` is described only to further define the value. We have that kind of namespaced tagging in many places in OSM. I'd additionally argue that data consumers build on, to a certain degree, that the data follows the documentation, so if data consumers check for handrails, they do not necessarily check also the `handrail:left/right` keys if handrail is not defined.

So, unlike `cycleway`, where the wiki recommends to only tag `cycleway:left/right` **instead** because it is more precise, for `handrail` it states that `handrail:left/right` defines the value more precisely.

**Comment by westnordost** [comment]
But in any case, one thing that I reckon now is that if someone resurveying the steps and not finding any handrail, the app should also delete the `handrail:*` tags, so this is the minimum that I should do about this.

Also, in regards to the argument I brought forth 2 hours ago, it would be a good idea to bring up some numbers: How much % of steps with handrail are tagged only with `handrail:*` and not with `handrail=yes`? How about the other way round?
After all what is written in the wiki is not everything and sometimes the wiki is wrong.

**Comment by westnordost** [comment]
About 9% of all ways tagged with `handrail` are also tagged with `handrail:left/right`.

About 29% of all ways tagged with `handrail:left/right` are also tagged with `handrail`.

**Comment by westnordost** [comment]
Ok since this is a not negligible amount of taggings that do not conform to the current wiki documentation, I changed it so that it doesn't ask for places with `handrail:*` anymore except in a resurvey (every 8 years)
