### ISSUE TITLE
Maintenance quest: Switch off option (opt-out)

### ISSUE THREAD

**Issue by Echolon** [westnordost/StreetComplete#2174]
Hi,

first of all: Many thanks for this great project! :heart: I love to map with SC and thereby I somehow managed to get into the top 100 world and Germany mappers (My gosh what did you do to me! :smile: )

The integration of the maintenance quests (reoccurring quests) I think that is a great idea to improve long-term quality!
However, I prefer to focus on mapping elements first that have no information yet, which is the case for most of the places I do mapping.
**Therefore I would be happy to not show reoccurring quests.** Because I am already seeing my own solved quests.

Rel: #1998  #2074

**Comment by westnordost** [comment]
That you cannot turn it off or even distinguish resurvey-quests and "normal" quests visually is deliberate.  The consideration is the following: Maintaining the data we currently have, keeping it up to date, is simply integral part of contributing to the map, there is no difference in terms of contributed value as outdated data is of as little value as missing data (or arguably is worse than missing data).
If in an area, there is not enough OSM-manpower to keep up with maintaing a certain level of detail, keeping the recorded data up to date, then it is not prudent to add even more data that eventually becomes outdated to the map - if users are not able to maintain it, the data has little value.

So I am pretty sure I will not change anything in this regard. However, that having said, there are two things you can do:

1. If you are overwhelmed by the number of resurvey and you think the assumption of StreetComplete how fast a feature might change is estimated too pessimistically in your area, then you can let them show up less often in the settings. It will ask x2 less often, so for example it will ask every 24 years instead of every 12 years for the surface of paved roads.
2. If certain quests put a lot of time-burden on you because they are re-asked very often, like the opening hours quest, you can opt-out to solving them at all (for now) by disabling them in the settings

**Comment by matkoniecz** [comment]
> Because I am already seeing my own solved quests.

Is it problem in itself? The same is happening for me and some of that data was wrong already.

**Comment by Echolon** [comment]
Yes for me it is, currently. But okay, I might have a wrong atempt to look for untagged quests only.  I will try to double the review time.

Thanks for clearing things.

**Comment by matkoniecz** [comment]
If some quests are consistently asked far too soon - it may be useful to tweak settings for them.

There is a significant local variation and @westnordost put significant effort into setting good resurvey intervals, but there is probably still room for improvement.

**Comment by Echolon** [comment]
Another question, because Im not sure how those appeared to ne recently:

Are maintenance quests tagged visibly, so I can see that this a maintenance quest before clicking on it?

**Comment by westnordost** [comment]
No, they are not.

For a few quests you'll notice it because then they are phrased differently: Namely for the opening hours quest and the cycleway quest. See here:
https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Map_Maintenance_with_StreetComplete/Report

**Comment by Echolon** [comment]
Ah okay, that was what triggered me.

Maybe that idea is another compromise one day

**Comment by RubenKelevra** [comment]
@Echolon You can at least reduce the amount of resurvey quests in the settings if you think that there are too many popping up. But to be honest I set it to 'ask more often' because it's important to have up to date informations.

**Comment by Echolon** [comment]
Everyday I map I need to think about this:

> The consideration is the following: Maintaining the data we currently have, keeping it up to date, is simply an integral part of contributing to the map, there is no difference in terms of contributed value as outdated data is of as little value as missing data (or arguably is worse than missing data).

Yes, the statement is correct and that should be how it goes.

Still I wonder if this states a very hard responsibility to the SC users and in general. We all are doing gre
