### ISSUE TITLE
Consider making step_count quest disabled for longer steps

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2184]
**Use case**
`step_count` quest is obnoxious to survey, takes a lot of time and usefulnes of data is very minor.

I think that disabling it for longer ways would be a good idea. Basing on what is listed in https://wiki.openstreetmap.org/wiki/Key:step_count it makes sense to distinguish `step_count=1` from `step_count=8` but on very long steps it is not very useful.

**Proposed Solution**
Ask `step_count` if steps are no longer than 4m. Or maybe completely disable it by default.

**Comment by rhhsm** [comment]
I don't mind the exercise :) Anyone who does can disable it in their settings or reply don't know if it's too long for their fitness. I do find that for longer steps, it's quite often necessary to split them, for instance because there's a junction with another path halfway and you would really want to count the steps before and after the junction, so it would be nice if that option is added to the quest.

**Comment by westnordost** [comment]
Everyone can disable any quest (or choose to ignore it) type if he or she finds it obnoxious. I'm with @rhhsm here. Also, currently it is not possible to split the way when asked for the step count, gotta fix that.
