### ISSUE TITLE
Show map detail at higher zoom levels

### ISSUE THREAD

**Issue by homme** [westnordost/StreetComplete#220]
I've just come across your app - it's great!  I've been testing it out and having fun with it, but came across an issue whereby when you are zoomed in (necessary to decrease the label contention and pinpoint a feature) the map features disappear.  This is shown in the screenshot below.  

An additional way of resolving this might be to implement #56 and let the satellite imagery pinpoint the feature.

![screenshot_20170511-104457](https://cloud.githubusercontent.com/assets/1055336/25940947/ac230f3c-362f-11e7-8c03-12ed75e6c9da.png)

**Comment by matkoniecz** [comment]
It seems that Internet connection was temporarily missing.

Though it would be smarter to show enlarged tiles from latest available zoom.

**Comment by homme** [comment]
Yes, you're right, it's working fine now, thanks.

**Comment by Echolon** [comment]
Hello,

I would like to reopen because of these differences.

This is the official OSM information:

<img src="https://user-images.githubusercontent.com/29168011/56322202-b4d71b80-6168-11e9-8ef0-60e9eb614523.png" width="350">

However, this is what SC shows:

<img src="https://user-images.githubusercontent.com/29168011/56322582-b6551380-6169-11e9-9077-36dc4bf5b198.jpg" width="350">

Therefore it would be great to show more details when zooming in. Unless, it often leads to unnesseary reports like "Here is a turning area". But actually it is already mapped.

Kind regards & thanks for the app!

**Comment by ENT8R** [comment]
Issues with the mapstyle should be handled in the repository of the mapstyle: https://github.com/ENT8R/streetcomplete-mapstyle
Please keep in mind that the mapstyle of StreetComplete shows no details at all to be as simple as possible and to not confuse the user. For your use case to check if some elements are already existing on the map, it would probably be the best option to try a full-featured editor like Vespucci: http://vespucci.io/
