### ISSUE TITLE
Clarify that static caravans are mobile homes in American English translation

### ISSUE THREAD

**Issue by BjornRasmussen** [westnordost/StreetComplete#2202]
Most Americans refer to static caravans as either trailers or mobile homes, but never as static caravan.  Adding an additional part to the definition in American English, like in this screenshot, would make it more clear.
![Screenshot_20201025-144844.png](https://user-images.githubusercontent.com/37753777/97116895-b88d1c00-16d6-11eb-9343-21b56cb56ec1.png)

**Comment by westnordost** [comment]
So, static caravan is a British English word?

**Comment by peternewman** [comment]
What exactly are we talking about, an overgrown portacabin? Because your picture shows a caravan that is definitely not static.

> So, static caravan is a British English word?

Yes seemingly:
https://www.lexico.com/definition/static_caravan

Although I think I'd normally use mobile home:
https://en.wikipedia.org/wiki/Mobile_home

Confusingly similar in name to, but entirely different from a motor home:
https://en.wikipedia.org/wiki/Motorhome

**Comment by westnordost** [comment]
So "mobile home" would work for both US English and GB English?

**Comment by peternewman** [comment]
Perhaps put mobile home first and static caravan second? It's not as clear cut as house or houseboat I'd say, so using a few terms is probably of benefit.

**Comment by westnordost** [comment]
I asked some Americans on slack. "Caravan" is pretty unknown there, so caravan should only be used in the en-GB translation.

**Comment by peternewman** [comment]
Okay. Well personally I'm happy with mobile home too on the British side.

With this and #2204 , do you want to make the change and push it up to POEditor so we can go and make the equivalent translation edits, or not in the case of #2204 or are you going to do both ends of it?
