### ISSUE TITLE
Replace "no name" with "no sign" for more quests

### ISSUE THREAD

**Issue by cyclingcat** [westnordost/StreetComplete#2215]
Hi,

the quest for street/road names has a similar problem as the one discussed in issue #2186 (and improved there): If this quest pops up and there is no sign with the road/street name the surveyor cannot be sure that there this (part of the) road/street has _really_ no name. Maybe there exists an official name (e. g. in official documents) but it's not signed anywhere. Or the sign is simply stolen/not readable/whatever. In these cases tagging "noname=yes" is a little premature and should be replaced with the more correct "name:signed=no".

However this situation here is a little more complex than the one of issue #2186 as this quest shows a popup with different possibilities the user is requested to choose from. As I don't know which tags the different options write into the OSM database, I've opened this issue in order to collect proposals how this can be improved.

This applies even more to bus stops where it is very unlikely that it has really no name (at least in Germany and probably in many other countries, too).

**My proposals:**

- **For the street/road name quest:** At least the text "It has no name" in the menu should be replaced with "There is no sign" (as it is the case now with quests for allotments and cemeteries and has always been for opening times). The appearing popup with the four possibilities should be examined if the wording matches the tagging exactly. At least the text "it simply has no name" should be replaced analogously and the tagging should be changed as mentioned above.

- **For the bus stop name quest:** See the solution implemented following issue #2186.

(SC 25.1)

The cycling cat

**Comment by westnordost** [comment]
Strictly speaking, you are right. That a street sign is missing is no absolute guarantee that a given street has really no name. But then, what is? Even official documents, if they exist, in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying "Beware of the Leopard", that would still be no guarantee that after all the road really has no name.

I think we can reasonably assume that a road that bears no street sign has really no name. And of course, if it has a name after all, it is no problem for anyone who would find that out to just retag it to `name=XYZ + name:signed=no`. 
`noname` is well used and understood by other QA tools on road name completeness, whilst `name:signed` is not that prevalent.

We know for example that every shop must have a name, and be it the name of the owner - the business must be registered somehow (at least in Germany). So, tagging `noname` is also factually not correct. In this case, it is better to tag `name:signed=no` but only because we can assume the above.

**Comment by westnordost** [comment]
For bus stops, name:signed=no is already tagged

On 2 November 2020 21:41:19 CET, cyclingcat <notifications@github.com> wrote:
>Granted, the chance is very high that a road without a sign _really_
>has no name. But the text "It has no name" is at least misleading IMHO,
>because the user, standing somewhere next to this road and looking for
>a sign, cannot know this and isn't able to find it out at this moment.
>The only thing he definitely knows is: "There is no sign". Perhaps
>change the wording while leaving the tagging in this case?
>
>However, the case of the **bus stop names** is just the other way
>round: If there is no visible name at a bus stop, the chance is almost
>100% that it will have nevertheless a name! (I have never seen a bus
>stop without a name, at least here in Germany! If they existed, what
>would be noted on the timetables or the displays in the buses?) Thus
>I'd consider tagging "noname=yes" in these cases as wrong. Furthermore
>it will be impossible to distinguish between bus stops that really have
>no name (very, very rare here) and bus stops where the name is for any
>reason not easily visible (in fact you can nevertheless find it out
>on-site in most cases by reading the attached timetable). So I stick to
>my opinion that these very very rare cases should be tagged with
>"name:signed=no".
>
>The cycling cat
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2215#issuecomment-720712414

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cyclingcat** [comment]
Okay. So it's just the wording left (I know, I'm sometimes a little pedantic 😂). "No sign" vs. "no name"... the former represents more what the user actually sees - and isn't this the basic rationale behind Street Complete?

The cycling cat
