### ISSUE TITLE
confusing question "Is this correct and is it not just part of a building?"

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#2221]
**Use case**

In quest on marking address on buildings, if one answers `It has no house number`, s/he is confronted with another question:
`Is this correct and is it not just part of a building?` with answers `No (leave note)` and `Yes`

It is highly confusing to me and I do not know what is meant by it, so I never answer it. 

Big part of the confusion is because it looks like to me like it asks **two** questions (`Is this correct?` and `Is it not just part of a building?`) but there is only **one** answer (and that one is brief `Yes` or `No (leave note)` which does not shed more light onto the problem).

Also using negative in question makes it harder to understand, it should probably be positive with answers inverted (for example instead of  `Is it not just part of a building?` with `yes`/`no` it would be more understandable as `Is it just a part of the building?` with `no`/`yes`)

What is exactly meant by this question, and what should one choose?

**Proposed Solution**

It would be good to describe what is meant there, with several possible examples and expected answers (and what they do to the OSM tags/Notes), so people (especially non-native english speakers) could perhaps suggest ways to ask this in more understandable way.  Thanks!

**Comment by westnordost** [comment]
Wait, is the current building type not displayed above "Is this correct?"

**Comment by RubenKelevra** [comment]
> Wait, is the current building type not displayed above "Is this correct?"

https://youtu.be/Q6MpptRjUHk

Can't confirm that with v25.0 on a random house.

Maybe there's just an issue with one specific value?

@mnalis can you give us the way-id of an object where it just shows this question, without the building type?

**Comment by mnalis** [comment]
@RubenKelevra Yes, it does show the current building type (other address quests I click on do show the type, as it does in your video). But I still don't understand the question the SC asks me? It is the wording that is confusing to me, not a program bug not displaying a picture or something...

I'll try to explain with example:

let's take for example https://www.openstreetmap.org/way/521157648 

![Screenshot_20201101_033928_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/97794004-2ca65300-1bf4-11eb-8234-a71b2dab5ddb.jpg)

If I click on it, and say it has no address, then the following question pops up:

![Screenshot_20201101_033955_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/97794043-d5ed4900-1bf4-11eb-8a63-76ed918159b3.jpg)

My problem is I do not understand the question?
It seems to me it asks "is it correct (that this building is a house)?" and **also** asks "is it not just a part of a building?"
Those are **two** questions, and I am only given **one** answer? So I am confused to which of those **two** questions do the `No, leave note` and `yes` answers correspond to? 

If it is (for example) part of the nearby house https://www.openstreetmap.org/way/521157647, then:
- the answer to first question is "YES": _yes, it is of building type=house_
- answer to second question is "NO": _it is not correct that this is not just a part of the building", which after some careful thinking translates to "(it is correct that) it is just a part of the building_

So one what should I answer in such case, "YES" or "NO"? My brain hurts trying to decipher this quest

Could you try to explain to me what exactly is being asked?

**Comment by RubenKelevra** [comment]
@mnalis 

Well it doesn't ask two questions. It just asks one:

"This is what's known right now: It's a house"

You (the user) has selected, that this object has no house number. 

The following question: "is this correct?" asks you to confirm, that the shape on the map is really outlining a house and not part of one. 

If it's just part of one, you have to open a note since tagging this isn't possible with further data being collected.

Can you create some better wording for this - while keeping it short - as an proposal? 

---

The no case should be fairly rare, since we only had a short period of time where building parts wasn't really a thing yet (not established), but it sometimes felt sensible to collect the information that a building has different parts with different properties. 

So we just made multiple building shapes and either put a node with the address into the main building or left this information out (armchair mapping).

**Comment by mnalis** [comment]
So when I press "no" to "is this correct?" question, only a new note is created. 
But what happens when I press "yes"?

Thanks @RubenKelevra! If I correctly get what you're saying, it is then equivalent of:

```
Building outlined above is tagged as: HOUSE (single-family home)

Please select correct answer:
(x) outline is just a part of bigger building (leaves Note) 
( ) outline is independent building
```

or are there some more possibilities?

**Comment by westnordost** [comment]
```
Building outlined above is tagged as: HOUSE (single-family home)

Please select correct answer:
(x) outline is just a part of bigger building (leaves Note) 
( ) outline is an independent building and really a HOUSE 
```

**Comment by mnalis** [comment]
@westnordost I see one other possibility here to add to that two options above :

`( ) outline is independent building, but not a HOUSE`

**Comment by westnordost** [comment]
Yes, this is falls also under "leave note".

The question asks "A is true and B is true?" Obviously if any of A or B is not true, the answer is no. 

On 2 November 2020 19:06:14 CET, Matija Nalis <notifications@github.com> wrote:
>@westnordost I see one other possibility here to add to that two
>options above :
>
>`( ) outline is independent building, but not a HOUSE`
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2221#issuecomment-720635484

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mnalis** [comment]
I agree it is obvious in programming languages, but I guess it depends on the natural language in question. In Croatian at least, it is extremely confusing to have a compound question (one with 3 possible answers in this case), but only 2 choices to pick from: "yes" / "no". (And so it is confusing at least for Croatians when reading English version too when phrased like this)

Also questions asked in negative form can be confusing in some languages (as in Croatian), _especially_ when they're compounded with another question (asked in positive or negative form), and when answers are not expanded to reiterate meaning, but are only short "yes"/"no".

So what I wanted to suggest, is that I think that the quest would be much clearer (and more understandable when translated to other languages) if it was in format like this:

```
Building outlined above is tagged as: HOUSE (single-family home)

Please select correct answer:
(x) outline is just a part of bigger building (leave Note) 
( ) outline is independent building, but not a HOUSE (leave Note)
( ) outline is an independent building and really a HOUSE 
```

Or, alternatively, the main "address number" quest could be modified to have additional answer (combined with removing follow-up question to `It has no house number`):
```
- It is only a part of the bigger building...
- It has multiple house numbers
- No house numbers but a name...
- It has no house number
- Can't say...
```

**Comment by schuetzm** [comment]
I'd like to add another aspect. Apart from the phrasing, it's also not clear to me what makes a building "just a part" of another building.

* If there's no gap between the buildings? But that's true for entire rows of houses in cities.
* If there's no separate entrance? But there are definitely building parts with their own entrances, so I guess the opposite is not true.
* If it's built in a different style than the main building? But that would make many small attachments/sheds separate buildings, because they are typically added later, even made from different materials...

Can we have some guidance here?

**Comment by westnordost** [comment]
@schuetzm : As far as I know, there is no clear definition in the OSM wiki. This is understandable, because the "real" way to make this distinction is to see whether the building(s) share a wall or each have their own exterior wall. But of course, this information is really inaccessible for anyone except maybe the building authority.
So, basically whether or not to classify a building as its own or just a building part is up for each contributor to decide. Two hints that may help to decide this:
1. does it share a roof? then it is very likely one building
2. same bricks, no visual vertical cut? then it is also very likely one building
3. no separate entrance? also same building

**Comment by westnordost** [comment]
@mnalis:
I wouldn't want to present three choices to the user of which two do exactly the same thing. What I can do is to change the wording so that it is easier to understand. What I can also do is to exchange "yes" and "no" with other strings, for example "HOUSE" and "NOT HOUSE" or similar.

Do you have a suggestion for an alternative wording? Here is the current full text:

> The building was tagged as:
> 
> **Apartment Buildling**
> house for multiple families, may have retail outlets on the ground floor
>
> Is this correct and is it not just part of a building?
> ------------------------------------------
> [No (Leave Note)]      [Yes]

**Comment by westnordost** [comment]
Basically, the core of the question is "Is this tagging correct?". That "and not part of a building" is mixed in is because this is a common mistake. Here for example:

[Mansteinstraße 48](https://www.openstreetmap.org/way/41296966) and [Eppendorfer Weg 152](https://www.openstreetmap.org/way/44359880) are the [same building](https://www.google.de/maps/@53.5790202,9.9653928,3a,75y,92.92h,95.36t/data=!3m6!1e1!3m4!1sP9jTotnOp--GJdz3IRu0GQ!2e0!7i13312!8i6656) but someone mapped it as two buildings. (Probably because he did not know how else to map two addresses on one building.

**Comment by schuetzm** [comment]
> That "and not part of a building" is mixed in is because this is a common mistake.

Ah, that's the idea behind it. How about using the three-way choice in [mnalis' suggestion](https://github.com/westnordost/StreetComplete/issues/2221#issuecomment-721369347), but prefill the note with "This building is incorrectly tagged as a separate house, but is really just part of another building." for the first option, or "This building is not an apartment, but a <please fill in>." for the second? Or even open the building type quest for the second option.

**Comment by westnordost** [comment]
Any suggestions for a solution without a three-way choice? As said, I don't want to implement that.

**Comment by mnalis** [comment]
@westnordost Unfortunately, I personally can't seem to figure out a way so that simple rewording solves this problem (I'd love to see if someone else can, though!) IMHO, adding additional clauses in any question increases complexity of that question - by very much in case of this subquestion. The options I see:


- the [three-way choice in subquestion](https://github.com/westnordost/StreetComplete/issues/2221#issuecomment-722528948) instead of `yes/no` which you've stated you don't want.

- removing subquestion `Is this correct and is it not just part of a building?` completely, and increasing number of answers in original question `what is the housenumber of this building?` by one (as suggested in second part of [this comment](https://github.com/westnordost/StreetComplete/issues/2221#issuecomment-721369347), which I haven't seen your  reaction on yet

- remove additional part of subquestion which makes it overly complex. So if the core of the question is "Is this tagging correct?", then ask _just for that_: `Is this tagging correct?`. (If answer to `is it part of another building?` is also important, then create a separate quest for that)

- leave quest as-is, which makes it confusing enough that even some advanced users will not understand it, so will not answer it or even worse wrongly answer it (the least desirable option in my opinion).

(As an rather anecdotal small datapoint - I've showed two other SC users (non-powerusers) the quest in 25.1, and asked what they though this subquestion meant, both in English and in my best Croatian translation - and neither could say. They successfully use SC otherwise AFAICT. Sorry I don't have better statistical sample).
  
If somebody can offer another possible solution, I'm all ears!

**Comment by HaasJona** [comment]
Actually, I don't think we really need to check the correct tagging of the house type here. I suggest to do something like this:

You selected that this [building type] has not a house number. Please specify why:

* This is just a part of a building (and it has not a proper entrance)
    * (Leave note)
* This is not a [building type]
    * (More options appear)
    * Select another building type (shows building type quest)
    * This building does not exist (Leave note)
* This building really has no house number
    * (Set nohousenumber=yes or whatever)

Also, and only slightly related, I think the case the the building is in construction should be handled, as building in construction often don't have a visible house number, but permanently tagging that it has none would be wrong. So maybe add "this building is in construction" as another option, which will set building:construction and construction to the old building value.

Or if this is all too complicated, i'd just prefer the suggestion from https://github.com/westnordost/StreetComplete/issues/2221#issuecomment-721369347 even if both answer do the same thing. But that's the clearest answer and you could extend it in case we can automatically set building:part=yes in the future or whatever.

**Comment by smichel17** [comment]
I am not totally happy with the phrasing of the first bullet point / checkbox, but what about formatting like this?

---

Building outlined above is tagged as: HOUSE (single-family home)

Please select correct answer:
- [x] Answer has one of these common problems (leave note)
    - outline is just a part of bigger building
    - outline is independent building, but not a HOUSE
- [ ] outline is an independent building and really a HOUSE

**Comment by mnalis** [comment]
@smichel17  I like that, especially as it is  relatively short wording (as short as it can be, and still be clear enough)! And _it is_ two-answer question, although not of same form type as original "yes" / "no" question, so Tobias might still dislike it.

@HaasJona  Good point about construction - that would cover another important issue with the same question (although chaining of quests one after another might be problematic from programming/usability point of view)

**Comment by westnordost** [comment]
Ok, I decided to only ask for if it is correct that it is tagged as building type Y. Because of the discussion that happened here (difficult to ask for both) and because it is maybe too much to ask the user to determine what is a building part and what is an own building at this point. If a user thinks a little annex to a house is also a house, so be it.
