### ISSUE TITLE
Quest: Discover the incline of a road via GPS (or baro if available)

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2222]
### General
Affected tag(s) to be modified/added: [incline=up / incline=down](https://wiki.openstreetmap.org/wiki/Key:incline)
Question asked: **Do you want to walk this way forth and back to discover the average incline?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
When the GPS fix is 3D with enough accuracy (or if there's a baro available) a phone could pretty accurately be used to discover the average incline of a way previously only tagged with up or down.

If only GPS is available the user should be asked to walk once in both directions, while with a baro sensor this isn't necessary.

If the user has chosen yes, one end of the way will light up and if the user reached this point he is asked to stand still for some seconds. After that the GPS accuracy is measured - if it's high enough the user will be asked to walk to the other end and this process repeats until 3 measurements are taken (two at the start point and one on the end point).

If the difference is below a threshold like 15% the average is taken and tagged as a percentage.

**Element selection:** 

Any way with up/down which is longer than say 15 meters (and is not a stairway) - since on very short distances this measuring method will lead to too much noise.

**Comment by matkoniecz** [comment]
The tricky part is that GPS based elevation (and even location) is often extremely inaccurate. I never tested barometer but accuracy would likely be even worse.

**Comment by FloEdelmann** [comment]
Why not simply make a normal quest out of this? That'd then be similar to the `AddStepsIncline` quest.

**Comment by HolgerJeromin** [comment]
I do not want to add `incline=no` at EVERY highway in my quite flat surrounding. 

https://www.geoawesomeness.com/accurate-altimeter-gps-watch/
> The general rule of the thumb is that vertical error is three times the horizontal error. If a decent signal reception is available, a modern GPS receiver should be able to give elevation data accurate to a range of 10 to 20 meters (35 to 70 feet) post correction.

With an 100 meter long osm way you do not want to analyse the incline with +/-15%  which is about the data range you want to gather.

**Comment by westnordost** [comment]
Well, it *could* be quite accurately measured with the rotation sensor. But that would require the user to shortly put his smartphone on the floor. I don't really want to require this of the users. I also suspect that people would tend to not put it on the floor but tilt their smartphone how they believe the incline is where they are and thus only recording quite inaccurate data. Also, that wouldn't really work for steps unless they have a handrail or ramp.

**Comment by RubenKelevra** [comment]
> I do not want to add `incline=no` at EVERY highway in my quite flat surrounding.

Noone suggested that you need to do this 🤔

> The tricky part is that GPS based elevation (and even location) is often extremely inaccurate.

Agreed. The absolute elevation isn't accurate, but the relative is - when comparing two points with good reception in short succession.

The gathering of 3 points will additionally eliminate any linear drift up and down. 

> I never tested barometer but accuracy would likely be even worse.

Barometer drift very very slowly, only your mapping in a thunderstorm this might be different. 

A good barometer is probably accurate to a degree that we would need to ask the user to hold the phone on the same height.

Barometers are not absolutely accurate, since the weather changes the pressure. If you have either a known pressure or a known height you can calibrate it.

> Well, it _could_ be quite accurately measured with the rotation sensor. But that would require the user to shortly put his smartphone on the floor. I don't really want to require this of the users. I also suspect that people would tend to not put it on the floor but tilt their smartphone how they believe the incline is where they are and thus only recording quite inaccurate data. Also, that wouldn't really work for steps unless they have a handrail or ramp.

That's an interesting idea, but you would multiply any error by a large number... since just a small bump in the road would change the results. 

Since there's doubt that this could be accurate I gonna test this, I got 3 devices with GPS, so I'll try if they lead to the same results on a stretch of road :)

---

A third method would be to do it visually - if we use a distinctive  point on the map for the measurements the user could point a crosshair on his camera view on it. After entering the height of the user we can calculate the angle.

This also works for steps: The user need to bring the edge of the first step with the last step on the same height by tilting his phone, when looking down the steps.

When the edges align we can use the angle directly for the steps.

**Comment by matkoniecz** [comment]
>>  I do not want to add incline=no at EVERY highway in my quite flat surrounding.

> Noone suggested that you need to do this thinking

How SC would detect where this quest is worth asking?

**Comment by RubenKelevra** [comment]
> > > I do not want to add incline=no at EVERY highway in my quite flat surrounding.
> 
> > Noone suggested that you need to do this thinking
> 
> How SC would detect where this quest is worth asking?

Well, the idea is to detect the incline on ways which are currently tagged with incline=up/down. That's what I meant with:

> Affected tag(s) to be modified/added: incline=up / incline=down

Sorry if this wasn't enough of an explanation. 

I tag ways when I know they are on a hill with the direction of their inclination. But this is hardly useful, as it is just a binary value.

Sure, there are elevation models, but this doesn't really help, they are extremely low in resolution, smoothed and thus doesn't work in canyons which appear much shallower.

Additionally a way might have some kind of embarkment, making it flatter or steeper than the surroundings.

A somewhat exact value would help to route bicyclists the most efficient route, to avoid steep grades and choose less steep ones to or circumnavigate a hill this way. 

---

Here's an example:

https://www.openstreetmap.org/way/155649367

This way has supposedly 18% incline. Not sure if there's now a sign, but when they opened there was none. Never such a steep cycleway made for fast traveling. 

Some people might want to avoid it and since that's basically on the side of an embarkment made for train tracks the embarkment actually makes it more steep.

Here's how Komoot shows a route over this paths. 

Either Komoot ignores the incline, or doesn't read it at all. The graph shows definitely not a sharp dip somewhere, so digital elevation data is used. 

![Screenshot_20201102-203421](https://user-images.githubusercontent.com/614929/97911126-13fc8100-1d4b-11eb-9315-3840e90b7a5b.jpg)

**Comment by westnordost** [comment]
Though, "Please walk down this street to record the elevation data", even it is accurate enough (@HolgerJeromin says it is not) is not really something that would fit into the StreetComplete format. This is not a question that is answered by the surveyor, it is... something else. I think requiring the user to walk up/down each road while having this one quest open (and not be allowed to solve other quests while doing that) is too much to ask of the user.

Gathering of elevation (=> incline) is data that can better be recorded automatically in the background rather than requiring an active action from a surveyor. And it is already possible to contribute this way. The "upload GPX trace" feature on osm.org. Elevation data is usually included in the GPX trace. This touches upon this point in the guidelines:

> 💵 Valuable Surveyors: Surveyor time is valuable, they shouldn't be asked to complete data that does not require a survey **and can more efficiently be done remotely**.

Remote mappers can then load the collected GPS data into JOSM and tag the ways accordingly. Using hundreds of GPS traces also smoothens out any error/inaccuracy mentioned by @HolgerJeromin. To summarize, this way of contributing this data is more efficient and more accurate.

What's still a bit missing is a tool with which one can display the aggregated GPS data in a reasonable way. JOSM currently just dumps all GPS traces as indistinguishable lines onto that display, this is not very helpful. With a more smart display (with graphs like the one you posted and stuff), the following characteristics of a road could be derived from the traces:
- speed data
- elevation data
- possible turn restrictions
- possible one-ways
- maybe more
But this is simply a missing feature in JOSM.

(Grab already creates dumps of such analyzation results of their (private GPS traces) data here https://grab.community.improve-osm.org/dumps/ , some of that data is used to create quests in STreetComplete)

**Comment by RubenKelevra** [comment]
Yeah, I get your point.

On the other hand this only applies to GPS measurements. The discussions opened some more options which maybe worth exploring. 

---

I did some testing how the different methods stack against each other. 

Google has 3D photometric images, so the incline should be pretty accurate in this case. 

While this isn't any data we could actually use, it should give us an indication how accurate different methods are. 

So I used a simple app, which combines the tilt of the phone as an overlay to the image. This obviously only works when you can aim at something, so road segments on OSM are rather bad for this. 

I've aimed between two points which are 78m apart in OSM which gave me visually a height difference of 6.6m while Google shows 7m difference. 

![Screenshot_20201108-203440](https://user-images.githubusercontent.com/614929/98482479-ff643100-2201-11eb-8f06-05910673f6b7.jpg)

This method would be also interesting for steps, since you can aim down the top of the steps to get the incline.

```
Visual 8.44%
Ground level: 7%
Google Earth: 8.97% +/- 0.6
GPS: 10.13%
```

Note: The inaccuracy on Google maps is due that the height is only available in integers.

---

Visually aiming at points would allow us to do quests, since the user just need to point the camera to a point he marked on the map, and enter his height. We could then fill in the incline to the quest and let the user confirm.

**Comment by westnordost** [comment]
Related: #2249

**Comment by RubenKelevra** [comment]
@westnordost never got a response from you on this: Do you think having users point a crosshair on the camera towards a point they marked on the map is too complicated? 🤔

I mean it appears to be the most accurate option and doesn't require the user to walk the length of the way nor to put their phones down in the dirt.

**Comment by westnordost** [comment]
If that was the only issue, maybe not. But this measure would be problematic because

- incline may change somewhat in the highlighted section. The highlighted section could be quite long after all, or not be straight (go around corners). Additionally, the highlighted section may not coincide with wherever the user points his smartphone at, e.g. be shorter.

- it is inherently imprecise, because it doesn't consider the height in which the camera is held. **a != b**. To be halfway precise, you'd have to calibrate this by entering the height in which the smartphone is held, and then always hold in in the same height.

<img width="538" height="268" alt="Image" src="https://github.com/user-attachments/assets/0d6d9329-fb6a-4caf-91a6-69695b465481" />

- needs camera permission and dealing with camera in the app

Hence, my last comment still stands. It would make more sense to record this data in a GPX trace and calculate the inclines from that. Maybe the apps with which users contribute this data to OSM already also records `ele` information? (I.e., maybe the data is already there, one just needs to write a program that distills that information from the GPX traces.)

**Comment by RubenKelevra** [comment]
I think you're overcomplicating things a bit:

1) Yeah, the incline may change, but so can the width of roads and width of paths. We already ask users to split a way if there are differences in the metric were measuring.

    And the idea is, that the user taps on a point on the map she/he can identify, not exactly the section of the way. This way it's always assured, that it's possible so see.

2) yes, we would need to ask the user for his height and then ask the user on the quest to keep the phone on "eye level". This would mitigate any issues.

    As shown above I did exactly that, I've subtracted 10 cm from my height and it's the closest measurement to laser measurement of they way and within the margin of error, due to only being integers available on Google Maps, compared to measurements on the ground and GPS measurements.

3) I mean there's already the measurement app, no? Would it be hard to add a mode with a cross hair to it, so it returns the "degrees of incline" it measured?

    SC could then take the height of the user, the GPS position and the position the user selected on the map to figure out the incline of the road.

**Comment by westnordost** [comment]
The measurement app works completely different, though.

**Comment by RubenKelevra** [comment]
> The measurement app works completely different, though.


Yeah I know it opens this 3D scanning library from Google. 

But would it be possible to call it "differently" and then open a plain camera view with a cross hair rendered in the center, and return the incline the camera measured to SC, so we can calculate the incline of the path with the distance between the GPS point, the point the user tapped on the map and the height of the user - like I did in my example?

**Comment by RubenKelevra** [comment]
@westnordost incline camera measurements are also possible via the browser.

Example: https://open-innovations.org/projects/osmedit/clinometer

So we would just need a "point on map" and "height of user" in addition. So SC could open a tiny website and give it those two values (GPS to point of map distance; height of user - 10 cm) and once the button is pressed the incline of the way is returned.
