### ISSUE TITLE
Inconsistent cycleway quest for residential highways

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#2230]
https://www.openstreetmap.org/way/385399447
```
highway=residential
lit=no
maxspeed=30
name=[set]
source:maxspeed=DE:zone30
surface=asphalt
```
shows the cycleway quest. Probably fine.

https://www.openstreetmap.org/way/387842231
```
highway=residential
lit=no
maxspeed=30
name=[set]
surface=asphalt
zone:maxspeed=DE:30
```
showed the quest on the first load (small area) and was hidden after a few seconds.

Perhaps there is a good reason for that, but this is surprising at least.

**Versions affected**
Android v10
SC 26.0 beta 3

**Comment by matkoniecz** [comment]
> Perhaps there is a good reason for that, but this is surprising at least.

Is it maybe blocked by other nearby, higher priority quest? Try moving cycleway quest to top of list in settings.

**Comment by westnordost** [comment]
When download happened for https://www.openstreetmap.org/way/387842231 , were you standing west or east of that way?

**Comment by westnordost** [comment]
Anyway, I am pretty you were standing west of it.

The mentioned way is on several tiles on zoom level 16. A tiny part of it is on tile https://tile.openstreetmap.org/16/34314/21685.png and the rest is on https://tile.openstreetmap.org/16/34315/21685.png

What happened is the following:
The app first downloaded the data for only the left tile. A quest was created for way 387842231 because no footway was within 15m of it it.
Then, the app downloaded the data for a bigger area, an area in which both mentioned tiles were included. Included in the returned data was this footway https://www.openstreetmap.org/way/660700307 . Since the way 387842231 was now within 15m of a footway, the current quest for that way was deleted because it turned out to be an element for which the cycleway quest should not be created after all.

One solution would be to not create quests for ways that intersect with the bounding box. This way, the created quests would be very stable. But on the other hand, this would mean that there will be blind spots the edges of zoom16 tiles. Additionally, most streets will be so long that they intersect with the edge(s) of a zoom16 tile one way or another. So, this solution would mean that there will be almost no quests at all.

Because of this, I decided to not fix this: After all, what the quest really wants to exclude consistently are sidewalks that run alongside the street. There are very few situations where a sidewalk running along a street would not be present in the same tile(s) as the street it belongs to. Most cases of footways that are near streets but not (always) present in all the tiles the street is will be some footway leading away from the street itself, like in this case.

**Comment by westnordost** [comment]
Hm but actually there is one thing I could do: Only exclude a way if the there is a footway of which *at least one segment* fulfills the following conditions for any segment of this way
1. is within 15m
2. angle difference of the two segments are max 45° 

So in other words, exclude all ways that have footways nearby that at least for a tiny bit (one segment) follow this street

**Comment by westnordost** [comment]
Requesting review on #2231

**Comment by westnordost** [comment]
So the idea is to filter out only those streets that have any the red footways near. The footways that are green do not lead to the exclusion of this street from the question:
![filter](https://user-images.githubusercontent.com/4661658/97878764-5a3beb00-1d1f-11eb-8234-1d67fd1cdd1b.png)

**Comment by smichel17** [comment]
Is this filter applied to all regions? I know in Germany cycleways are often a part of the sidewalk, but in the US they almost never are; whether there is a sidewalk next to the road should not impact whether this quest is asked.

**Comment by westnordost** [comment]
Yes, it is and has been applied to all regions. 
It's for footways within 15m of the center line of the road. Can you show me a road for which this filter is not eligible?

**Comment by westnordost** [comment]
Actually, the filter could be made more intelligent:
```
roadWidth= taggedRoadWidth ?: derivedRoadWidthFromLanes ?: derivedRoadWidthFromTypeOfRoad
minDistance = roadWidth + 4
```

**Comment by smichel17** [comment]
Here's one off the top of my head (though the bike lane is already tagged) https://www.openstreetmap.org/way/426585658

**Comment by westnordost** [comment]
What about it? There, the footway is tagged on a way less than 15 away from the road, so it is not asked.

**Comment by smichel17** [comment]
>  so it is not asked.

I may have misunderstood. Is "it" the cycleway quest ("Is there a cycleway here? What type?") or a different quest?

I thought you were saying that the cycleway quest would not be asked for Somerville Avenue. This would be wrong, because Somerville Ave has a cycleway on it. In most places it is a "cycle lane"; in a few places it is "explicitly shared with other traffic". In all places, the cycleway is part of the road, not the sidewalk (and in Somerville in particular, biking on the sidewalk is not allowed, although this ordinance is seldom enforced).

**Comment by westnordost** [comment]
Yes, it is the cycleway quest and the sidewalk quest.

On 2 November 2020 18:49:37 CET, smichel17 <notifications@github.com> wrote:
>>  so it is not asked.
>
>I may have misunderstood. Is "it" the cycleway quest ("Is there a
>cycleway here? What type?") or a different quest?
>
>I thought you were saying that the cycleway quest would not be asked
>for Somerville Avenue. This would be wrong, because Somerville Ave has
>a cycleway on it. In most places it is a "cycle lane"; in a few places
>it is "explicitly shared with other traffic". In all places, the
>cycleway is part of the road, not the sidewalk (and in Somerville in
>particular, biking on the sidewalk is not allowed, although this
>ordinance is seldom enforced).
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2230#issuecomment-720626344

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
And yes, the cycleway quest would not be asked for Somerville Avenue if there wasn't a cycle lane yet. The reason is that the nearby footway might be the sidewalk. If the user would answer the question and select "cycle track" as the answer option, the cycle track would be tagged on the wrong element: on the road way instead of on the sidewalk way. But if there is a separately drawn sidewalk, any cycle track if there is one should also be a separate way from the road way.
This is why the cycleway quest is not asked for elements with "just" a separate (possible) sidewalk near. I know, the surmise should be that only if nearby cycleways are near, the quest should not be asked. But for the reason stated above, a separately mapped sidewalk is already enough for that this quest should not be shown.

**Comment by smichel17** [comment]
> The reason is that the nearby footway might be the sidewalk

Yes, the footway next to Somerville Avenue is a sidewalk.

> If the user would answer the question and select "cycle track" as the answer option, the cycle track would be tagged on the wrong element: on the road way instead of on the sidewalk way.

This is where I disagree. It would be correct to tag on the road way, not the sidewalk way.

Whereas in Germany (or Hamburg, at least), cycleways are often part of the sidewalk, I don't think I have ever seen that in the US (there are a couple places where bike paths run alongside a sidewalk for 40 meters that you could argue are similar, but these are rare). Here is a view of an intersection on Somerville Ave that I think should illustrate this clearly:

https://www.google.com/maps/@42.3832797,-71.1067313,3a,75y,127.68h,62.81t/data=!3m6!1e1!3m4!1s6zSGdzMAyMxjfh4sQ2FLvg!2e0!7i16384!8i8192

**Comment by westnordost** [comment]
> This is where I disagree. It would be correct to tag on the road way, not the sidewalk way.

Yes, I said cycle **track**, not cycle lane. I am talking about cycle tracks. If the user selects cycle track, it would be tagged on the wrong element in your case.

**Comment by smichel17** [comment]
Ah, thanks for pointing that out. I had missed it -- unfamiliar terminology to me and I did not read carefully enough. So now I have the words to be more precise:

I cannot remember having ever seen a cycle track in the US. So I think it would be more useful to ask the cycleway quest on all roads. Then, either:

1. If there is a foot path nearby and the user selects track, just add a note instead.

   Or

2. Just don't show the track option in the US at all.

It would be good to have someone else who could verify that this is true across the whole US -- I have not traveled widely outside the northeast.
