### ISSUE TITLE
Consider reducing delay between start of achievement animation and showing content

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2232]
Maybe I am inpatient, but it is a bit irritating to see a contentless animation for noticeable time below achievement graphic and achievement text appears. The lightshow animation is cool, but maybe time for showing just it can be reduced?

Or maybe it is just me.

(so far I am just checking is it just me, I have not looked at how it is implemented and what would need to be changed)

**Comment by smichel17** [comment]
Settings > Developer options > Animator duration scale = 0.5x :laughing:

**Comment by cyclingcat** [comment]
Hi there,

myself, I disable any kind of animations in any systems as much as possible (Windows, Android, Firefox and more) as I hate any kinds of unnecessary distractions. Therefore my related Android settings are all set to "off". But this is just my personal preference, although my opinion is that "off" should be always the default or at least ONE single option to disable ALL of them. **(BTW: This is an accessibility topic as well, see for example the "prefers-reduced-motion" CSS media feature.)**

Concerning Street Complete I have been observing three different kinds of behaviours (many versions up to the current v25.1):

- Some animations are completely gone indeed.
- Some animations (e. g. the annoying "pumping" effect of the "Hamburger menu" and its submenus) are gone on my Android 9 phone but still visible on my old Android 5.1 phone. This is probably due to the "Remove animations" setting in the "Accessibility" menu which was introduced with Android 9 IIRC.
- Some animations (e. g. when the edit windows for quests appear) are still there, independent of the Android version.

But perhaps this is a topic for a separate ticket...

The cycling cat

**Comment by westnordost** [comment]
Ok, I decreased the delay by 900ms
