### ISSUE TITLE
New answer in maxspeed quest: bicycle_road

### ISSUE THREAD

**Issue by moebelwagen** [westnordost/StreetComplete#2238]
**Use case**

In the maxspeed quest you can choose between a speed limit sign, a zone type and a living street. The answers don't apply to a bicycle road. Technically a bicycle road could be a zone type, but the zone speed limit sign in the answer suggests that this answer is not appropriate either.

**Proposed Solution**

Bicycle road should be added as a possible answer. Since it is a zone type there could be a subquestion for a zone type, but I think it would line up better as a normal answer.

These tags could be added:
- bicycle_road=yes (if not already there)
- maxspeed=30 (at least in Germany)
- source:maxspeed=<country_tag>:bicycle_road

**Comment by westnordost** [comment]
Question is if it is worth the effort. Are (untagged) bicycle roads so widespread that it would become a real nuisance if people left a note instead? I don't think so. 

On 5 November 2020 09:31:27 CET, moebelwagen <notifications@github.com> wrote:
>
>
>**Use case**
>
>In the maxspeed quest you can choose between a speed limit sign, a zone
>type and a living street. The answers don't apply to a bicycle road.
>Technically a bicycle road could be a zone type, but the zone speed
>limit sign in the answer suggests that this answer is not appropriate
>either.
>
>**Proposed Solution**
>
>Bicycle road should be added as a possible answer. Since it is a zone
>type there could be a subquestion for a zone type, but I think it would
>line up better as a normal answer.
>
>These tags could be added:
>- bicycle_road=yes (if not already there)
>- maxspeed=30 (at least in Germany)
>- source:maxspeed=<country_tag>:bicycle_road
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2238

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by moebelwagen** [comment]
They are less widespread than the other answers, sure. You know better about the effort, so feel free to close the ticket if you think it's not worth it.

That made me think about this: if you know the answer to the question but can't select it, "something different" feels more like the right choice than "can’t say". Could apply to other questions too. But that's a completely different issue..

**Comment by FloEdelmann** [comment]
Maybe in the `AddCycleway` quest, there should also be a possibility to answer "This is a bicycle road" that adds the same tags.

**Comment by westnordost** [comment]
I thought about this, and came to the conclusion that I'll not add support for this.

What would need to be done is to research in which countries the concept of cycle streets exists and to research which tag should be used - `bicycle_road` or `cyclestreet` (they are more or less the same, but in some countries, the first is used, in other countries, the second). This is not that much effort.

Then, I'd need to include graphics of the different bicycle road signs from the different countries:

![159px-Fahrradstrasse_IMGP8343_smial_wp](https://user-images.githubusercontent.com/4661658/98443427-74087400-210b-11eb-896a-fdf1549721db.jpg)
![image](https://user-images.githubusercontent.com/4661658/98443490-e24d3680-210b-11eb-90fb-1210aab13690.png)
![image](https://user-images.githubusercontent.com/4661658/98443513-fe50d800-210b-11eb-853d-733f7ac9e473.png)
etc...

This is already quite some effort, as there seems to be no standard signage here, every country has its own sign for that.

However, what would be most effort and actually is most problematic is the following: `cyclestreet`s (Belgium, Finland, Netherlands, ...) and `bicycle_road`s (Germany) differ in one important aspect. For the latter, motorcars are actually not allowed at all on the road unless signed otherwise. 
In reality, it is signed otherwise almost everwhere (like in the photo above), one way or another. Common combinations are exceptions for residents and common are also exceptions for motorcars in general (like in the photo above). 
So, this addition to the bicycle road signage is an important part of that signage: It is very relevant if it is a bicycle road without extra signage or a bicycle roads where motorcars are allowed. To only tag something as bicycle road without in the same changeset also tag the additions is something I would consider not only as incomplete, but actually as wrong.

That means, to enable users of StreetComplete to tag this situation correctly, it must be possible to specify these extra signage as well. This makes the form really complex and since the extra signage could basically be anything, it'll never be complete but can only catch the most common cases.

So, it is better to not support it at all an let the user create a note instead, best with a picture.

**Comment by westnordost** [comment]
If someone wanted to implement this after all, here is the summary of what should be done:
- research for which countries the concept exist and put the result of this research into `res\country_metadata\isCycleStreetKnown`
- draw svg icons for the signs for the countries it is known
- either implement it only in countries where additional signage is not seen (all except Germany?) or offer (all?) the choices the extra signage could be
- implement this selectionin both or either of `AddCycleway` and/or `AddMaxSpeed` quest and quest forms.

**Comment by smichel17** [comment]
> So, it is better to not support it at all an let the user create a note instead, best with a picture.

Would it make any sense to add a (new class of) quest where the way to answer is to answer the quest by taking a picture and creating a note? And then the quest would be shown only for nodes that do not have a SC note attached.
