### ISSUE TITLE
opening hours quests not shown for nodes without name

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#224]
I just added opening hours to a pharmacy in Vespucci because it wasn't shown in StreetComplete.
(http://www.openstreetmap.org/node/342930824/history)

Tags that were present before my change (and quest was not shown):
```
amenity: pharmacy
dispensing: yes
```

I looked at the code (https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/opening_hours/AddOpeningHours.java#L34)  and if I understand correctly, opening hours quest is shown only if given place has a `name` tag. If that's correct then I think this is to restrictive (e.g. pharmacies don't always have name):

```
    @Override protected String getTagFilters()
	{
		return " nodes, ways, relations with ( shop and shop !~ no|vacant or" +
               " amenity ~ restaurant|cafe|ice_cream|fast_food|bar|pub|biergarten|food_court|cinema|nightclub|" +
                          "bank|atm|bureau_de_change|money_transfer|post_office|library|courthouse|embassy|" +
                          "car_wash|car_rental|marketplace|fuel|driving_school|" +
		                  "dentist|doctors|clinic|pharmacy|veterinary or" +
               " amenity = bicycle_parking and bicycle_parking = building or" +
               " amenity = parking and parking = multi-storey or" +
               " amenity = recycling and recycling_type = centre or" +
               " tourism ~ zoo|aquarium|theme_park|gallery|museum or" +
               " tourism = information and information = office or" +
               " leisure ~ golf_course|water_park|miniature_golf|dance|bowling_alley|horse_riding" +
						  "sports_centre|fitness_centre|amusement_arcade|adult_gaming_centre|tanning_salon )" +
               " and !opening_hours and name";
}
```

(last line: `and name`)

**Comment by westnordost** [comment]
name is necessary because the user needs to know what shop he should the opening hours to. Especially in regions with bad GPS signal and/or bad data quality (shop is 50m in wrong direction), it is a must.

Without a name, the app could ask "What are the opening hours of this pharmacy". However, that means that I need a dictionary for all primary features or at least for all shops and amenities from tag value to any language.

Because this doesn't exist yet, the "name" is required.

P.S: https://forum.openstreetmap.org/viewtopic.php?id=56889

**Comment by krzyk** [comment]
OK, but why not follow others and create dictionary of amenities/places?
This would extend the number of opening hours quests  by 20-50% depending on the country and type of the place.
