### ISSUE TITLE
Availibility of electric car charging stations when tag motorcar=no is missing.

### ISSUE THREAD

**Issue by tiptoptom** [westnordost/StreetComplete#2242]
**How to Reproduce**
The quest "How many cars can be charged at this charging station at the same time?" is asked for notes with  `amenity=charging_station bicycle=yes`

when there's no Tag `motorcar=no`

I think it would be a better way either to first ask for the vehicle type or to ask for the capacity but general for all vehicle types.  

**Versions affected**
v26.0-beta3

**Comment by westnordost** [comment]
Can you link the place where this occurs?

**Comment by tiptoptom** [comment]
The note where I noticed the problem is https://www.openstreetmap.org/node/5874099308 .

You can use this overpass request to find other notes with this problem:
```
[out:json][timeout:25];
// gather results
(
  node["amenity"="charging_station"]["bicycle"="yes"]["motorcar"!="no"]["car"!="no"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by westnordost** [comment]
There are 42700 `amenity=charging_station`.

2673 (7%) of these have `bicycle=yes`. Of these, 
- 538 (20%) have `car=no` tagged
- 410 (22%) have `car=yes` tagged
- 1722 (64%) have no `car` tagged

I am going to change it so that the capacity is asked if either of `bicycle=yes` or `bicycle=yes` is true because the `capacity` is then not unambiguous anyway and there is no solution mentioned for that in the wiki.
