### ISSUE TITLE
Quest Clarification: How to answer building type for detatched, 2-family houses?

### ISSUE THREAD

**Issue by smichel17** [westnordost/StreetComplete#2257]
[This neighborhood](https://www.openstreetmap.org/#map=18/40.74902/-73.74776) used to be mostly single-story, single-family homes. Over the years, most of the houses have been renovated into two-story houses. These renovated houses:

- Are *usually* (not always) 2-family houses. E.g. one family on each story.
- Were often renovated for the explicit purpose of adding another unit.
- Often have two separate entrances for the different units.
- Are often (guess: usually) lived in by the owner (only one unit is a rental).

I am not sure how to tag these; none of the answers seem to fit:

- **semi-detached** — this is the closest fit, but in general I think of semi-detached as sharing a *wall*, not being stratified by floor (this is also what the [wiki](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsemidetached_house) says). But perhaps this is the right tag anyway.

- **Apartment building** — Feels wrong. They are never more than 2 stories / 2 families; the owner almost always lives there; and they don't *look/feel* like apartment buildings to me, subjective as that is. The [wiki](https://wiki.openstreetmap.org/wiki/Tag:building%3Dapartments) also says something or other about tagging `building:use` if they weren't originally constructed as apartments.

- **[Detached] House** — these both specify *single-family*.

---

Separately, I had the idea that maybe one of the "more options" answers could lead to the relevant wiki pages, in case there is an edge case and the short description in SC is not enough to determine the answer.

**Comment by westnordost** [comment]
I'd tag it as semi. It doesn't really matter if the two families live on top of each other or next to each other IMO

On 9 November 2020 19:23:55 CET, smichel17 <notifications@github.com> wrote:
>[This
>neighborhood](https://www.openstreetmap.org/#map=18/40.74902/-73.74776)
>used to be mostly single-story, single-family homes. Over the years,
>most of the houses have been renovated into two-story houses. These
>renovated houses:>
>>
>- Are *usually* (not always) 2-family houses. E.g. one family on each
>story.>
>- Were often renovated for the explicit purpose of adding another
>unit.>
>- Often have two separate entrances for the different units.>
>- Are often (guess: usually) lived in by the owner (only one unit is a
>rental).>
>>
>I am not sure how to tag these; none of the answers seem to fit:>
>>
>- **semi-detached** — this is the closest fit, but in general I think
>of semi-detached as sharing a *wall*, not being stratified by floor
>(this is also what the
>[wiki](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsemidetached_house)
>says. But perhaps this is the right tag anyway.>
>>
>- **Apartment building** — Feels wrong. They are never more than 2
>stories / 2 families; the owner almost always lives there; and they
>don't *look/feel* like apartment buildings to me, subjective as that
>is. The
>[wiki](https://wiki.openstreetmap.org/wiki/Tag:building%3Dapartments)
>also says something or other about tagging `building:use` if they
>weren't originally constructed as apartments.>
>>
>- **[Detached] House** — these both specify *single-family*.>
>>
>--->
>>
>Separately, I had the idea that maybe one of the "more options" answers
>could lead to the relevant wiki pages, in case there is an edge case
>and the short description in SC is not enough to determine the answer.>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/westnordost/StreetComplete/issues/2257

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by smichel17** [comment]
Okay. Good enough for me.

**Comment by smichel17** [comment]
This is probably what I would have done if the [Tag:building=semidetached_house](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsemidetached_house) wiki page did not have the description (emphasis mine) "A house that shares a common *wall* with another on one side." I don't think I will personally do anything about this, but someone interested in improving clarity could edit that description.

**Comment by smichel17** [comment]
Follow-up question: I've since learned that this neighborhood is zoned for only single or two-family houses (ie, only detached or semi-detached). But there are a small handful of buildings that clearly (and illegally) have 3-4 units (one of them marked with {housenumber}-01, -02, and -03).

Should I mark them as semi-detached (as they were zoned & certified) or apartment (as they are being used)?

**Comment by matkoniecz** [comment]
> Should I mark them as semi-detached (as they are zoned / as the building was constructed) or apartment (as they are being used)?

Is it building constructed to house multiple apartments or a house divided into multiple apartments? (though border is very blurry here)

It does not matter how they are legally classified.

**Comment by smichel17** [comment]
Hard to tell without going inside, but closer to a house divided into 
multiple apartments, I think. I'll take some pictures soon (tomorrow, 
unless the rain which is predicted lasts all day).

**Comment by rhhsm** [comment]
I tag these as apartments, after checking their legal status on the cadastral website. I think the legal status is a more easily verifiable way to determine what kind of building it is than counting doorbells, letterboxes, etc.

**Comment by RubenKelevra** [comment]
I tag everything with more than one door bell as apartment building.

Semi-detached is only for two buildings which are build together next to each other. Not for houses with multiple families living in them.

Why we have to frantically decide between house, detached, semi-detached and apartments never made sense to me though.

I feel like this information is completely useless and most of the time tagged wrong anyway. 

I think it would make much more sense to decide between buildings which have multiple purposes, like people living in them and a shop on the ground level. 

I mean, the user has to decide at the moment which is the primary usage... is a bakery with a small apartment in the back now a commercial building, a shop or a residential building? 🤔

Is it detached since there's a bit garden around it, or is the way on one side too small to have it count as detached, and better use house instead?

Or is it an apartment building, since there's an apartment in the back - sure it's just one but it's clearly rented... 🤔

Most of the time I have no idea if the value I map makes any sense or has any use at all.

**Comment by westnordost** [comment]
You are not alone,  i really think that a "mixed use" building is missing but alas,  this is the tagging schema in osm

**Comment by smichel17** [comment]
"Tommorow"… "In 6 days"… same difference. Anyway, here's some pictures of buildings I struggled to tag:

# Detached or semi-detached?

![20201116_154254](https://user-images.githubusercontent.com/6563664/99344239-814dfd00-2887-11eb-93ee-ff0dce181de1.jpg)
![20201116_154303](https://user-images.githubusercontent.com/6563664/99344241-827f2a00-2887-11eb-8889-c43bdfb9fce5.jpg)
![20201116_154313](https://user-images.githubusercontent.com/6563664/99344245-83b05700-2887-11eb-8a3d-88d6125e67ca.jpg)

The electric/gas meters on the side suggest that this is a two family (semi-detached) house, but it *could* be a regular detached house with a side entrance. Hard to know without going inside.

# Semi-detached or apartment building?

![20201116_154503](https://user-images.githubusercontent.com/6563664/99344597-5a43fb00-2888-11eb-853b-72627cc7b20b.jpg)
![20201116_154524](https://user-images.githubusercontent.com/6563664/99344600-5b752800-2888-11eb-9e67-6c908a5a77a1.jpg)
![20201116_154536](https://user-images.githubusercontent.com/6563664/99344604-5d3eeb80-2888-11eb-8fdd-f74b66226426.jpg)

This large house could be 2 or 3 units (note: 228-03 is the building address, not the entrance address; 228-05 is next to it).

# Semi-detached or apartment building?

Should have gotten more pictures of this one, but it's around the same size as the first house. There are many others like it that I tagged as semi-detached. But this one, with the door placement near the side and separate mailboxes, feels more like an apartment. But at the same time, 100% residential and only 2 stories — not what I'd think of if you said "apartment building" to me.

![20201116_154713](https://user-images.githubusercontent.com/6563664/99344459-0e915180-2888-11eb-97ff-ff0a82edb520.jpg)

> Why we have to frantically decide between house, detached, semi-detached and apartments never made sense to me though.

Well, there are some buildings that fall clearly into one category or the other. [Clearly semi-detached](https://www.google.com/maps/@42.3268171,-72.643653,3a,75y,215.62h,96.83t/data=!3m6!1e1!3m4!1sAB9u-sZ0GKFcYySly5tZ2A!2e0!7i13312!8i6656?hl=en). I think the main reason to distinguish is the entrance type:

- Detached: All entrances lead to the same residence
- Semi-detached: multiple residences with separate entrances
- Apartment: multiple residences with a shared lobby/staircase/etc
    - But also single residences that are above a shop, sometimes

I do think maybe it would make sense to tag the *entrances* somehow rather than the whole building. But I'm not sure how these things are represented in osm.

> I tag everything with more than one door bell as apartment building.

Unfortunately this doesn't work either — my (indisputably) detached house has a doorbell on both the main and side door. :P

**Comment by rhhsm** [comment]
My philosophy is that if it's hard for you to determine how to tag something, it is hard for a user of your data too, so it probably doesn't matter too much anyway.
I also think that discussions on how to tag things should best be done at the OSM wiki, and SC should follow the consensus there instead of developing its own consensus.

**Comment by matkoniecz** [comment]
> SC should follow the consensus there instead of developing its own consensus.

I agree, but it is a good place to evaluate existing tagging and its documentation for StreetComplete-related purposes.

So inventing new tagging or changing it should not happen here, but deciding how existing tagging should be expressed in SC interface has its place here.

**Comment by westnordost** [comment]
I guess to decide into which category to fit it is up to your own consideration. To me, they look huge. If this stood in Hamburg, I'd tag it as apartments. But then again, I heard that houses in the US are often very spacey, so, no idea.

**Comment by RubenKelevra** [comment]
> My philosophy is that if it's hard for you to determine how to tag something, it is hard for a user of your data too, so it probably doesn't matter too much anyway.
> I also think that discussions on how to tag things should best be done at the OSM wiki, and SC should follow the consensus there instead of developing its own consensus.

True, but nothing holds us back to tag multiple 'purposes' of a house. There's the well established ';' sign to make a list in a tagging field.

If a building has apartments and a shop on the ground level, why not tag both?

```
building=apartments;retail
```

This makes it very clear where shop nodes might be missing, since from a building perspective there's a shop. 

And in my example one could tag `building=residential;retail` when in doubt which is the most fitting detailed tag for the residential part. 

Currently we're loosing those details by forcing to tag a building with just one type, while it's clearly has multiple purposes.

**Comment by mnalis** [comment]
@RubenKelevra I'd advise against that; although some tags do advertise and use such multiple values, `building=*` is not one of them - neither according to wiki, neither according to taginfo usage. IMHO, SC should follow general OSM consensus, not invent it's own tag values or change the way how they're used. 

For your example, I'd rather go with tagging the generic part of the building. So if it is shop on the ground floor, with apartments on the floors above, I'd tag it with `building=apartments` and then add `shop=xxxx; name=yyyy; level=0` node inside it. 

On the related note, I find accuracy of `building` tag (at least in my country where I map the most) disturbingly low (when compared to any other tag!). Lots of armchair mappers will happily mark any smaller building in residential area as `building=house`, even if it is for example small convenience shop, or a smaller `building=apartments`. So usability of those specific building tags is probably low (if they had any real use anyway)

_If we had a time machine, I'd vote to make `yes` only tag available for `building=*`, and then put groups of buildings in appropriate `landuse=*` to cover the default case, and add specific `amenity`/`shop`/etc if they are different purpose (or as extra POIs inside building, if there are multiple of them). It would probably have better precision (due to less unprecise-mappers-polluting-results) and at much less effort._

**Comment by RubenKelevra** [comment]
I'm currently armchair mapping and fixing some people's work from years ago who imported without any plan all buildings for large areas from some shady source.

At this time we had no access to Bing nor anything else... so yeah.

The official statr building database is available for OSM so I'm currently matching the buildings and fixing the broken imports etc.

That's why I think we should use multiple values - they do this too.

They have text fields which explains that it's a residential building with industrial or commercial or retail use. Or some mixture.

On the other hand they have no individual fields for different types of residential buildings.

That said, they even have building parts 😁

So if even the state database doesn't need those information, I wonder if there even exist any use-case at all.

And yes, multiple values are not that common, but I don't think they have ever been ruled out for any tag. There was some hesitation early on, that it would make parsing difficult. But that's like 10 years back. 

On the other hand all those building types were thought of, as possible values someone might want to use, not that they have to be used or that they are a very strict guidance what's allowed and what not. 

This was never the intention of the wiki.

**Comment by mnalis** [comment]
@RubenKelevra Yes, wiki is (supposed to be) descriptive and not prescriptive, that's why I also mentioned [taginfo](https://taginfo.openstreetmap.org/keys/building#overview) which shows what is *actually* being used. And it says that out of more than 423 **million** buildings, the _most common_ building tag which has multiple values is occurring about **0.005%** of the times. In my book, that is not "Common usage" by any stretch of imagination. 

I've also armchair mapped a lot, but when doing buildings from aerial/satellite photos I always map only as `building=yes`, as there is just no way to know better, and less-precise information 100% of times is IMHO much better than more-precise information which is sometimes correct but also sometimes wrong. Mapillary might allow you to be more precise, though, but it also has limits - and not even being on site will allow you to be correctly specify a precise type for all buildings.

Imports are a story for itself - while they might be useful sometimes, they often can contain obsolete and inaccurate data, and can be deterrent to mappers (see list of links at the bottom of https://wiki.openstreetmap.org/wiki/Import - some conclusions are quite interesting, especially the two articles by Matt Amos)

**Comment by RubenKelevra** [comment]
Well, since we're talking about the official database the data is pretty accurate. You have to change the building type as an owner to open a shop or use a building made for industrial use to lofts etc.

So actuality the only way to deviate from the database is to use a building illegally differently.

The database is released twice a year and each building has the date from the last change.

I'm currently replacing all values which are 'residential use and x' from this database for just `building=residential` in OSM. 

Since most buildings already exist in OSM it's not necessarily an import nor is it automated, I review for each building both data and if it's clear that the OSM data is basically just a rough shape from a satellite image or a bad import of the same database I fix the old import or enhance the shape of the satellite image. 


I was just curious if it would make sense to keep more information from this very reliable source about multi-use buildings, since we already came to the conclusion that a primary use should always be residential.

**Comment by westnordost** [comment]
Okay, it looks like this discussion strayed quite far from the original purpose, which was to ask whether such family houses that @smichel17 posted would be semi-detached, detached or apartments. The answer to that would be that it is in your own consideration, really, if there is nothing about it in the wiki. So, I am closing this.
