### ISSUE TITLE
Unable to reach the authorization server

### ISSUE THREAD

**Issue by Quix0r** [westnordost/StreetComplete#2258]
This old bug is bag since it has been switched from external browser to internal web view.

Android: 4.1 (always worked before that change!)

What I get: When I try to login and tab on the "Login" button, I get the message "Unable to reach the authorization server" with a working Internet connection (e.g. map tiles are being fetched).

**Comment by Quix0r** [comment]
And @MIcrosoft has messed up GitHub ... Version: 25.1

**Comment by mnalis** [comment]
Just a related heads-up: in less then a year (September 2021) all web sites using Let's Encrypt `https://` (including OpenStreetMap.org) [will break on Android versions < 7.1.1](https://letsencrypt.org/2020/11/06/own-two-feet.html). See the link for possible workarounds.

**Comment by westnordost** [comment]
@Quix0r and exactly this certificate problem is your problem with Android 4.2. Versions before I believe Android 4.4 wouldn't trust a Let's Encrypt certificate in a webview. It worked before for you because your external browser (Firefox, by chance?) came shipped with a set of trusted root certificates. The internal web view relies on what the Android system trusts.

If I remember correctly, there was a workaround for this - you could somehow add new root CAs to your Android system's list of trusted root CAs. So to fix this for yourself, you can try searching for the solution there.

Though, be advised that I plan to remove support for Android 4.2, 4.3 and 4.4 end of this year. So maybe it is time to buy a new (or second hand) smartphone. 4.2 was released over eight years ago.

**Comment by mnalis** [comment]
@Quix0r or maybe if are lucky you could upgrade your device ROM with https://wiki.lineageos.org/devices/ or similar

**Comment by Quix0r** [comment]
Okay thank you. :-( That's why I don't like smartphones much when it comes to apps other than SMS and calls.

**Comment by Quix0r** [comment]
Thank you for the link but I don't want to mess up a working phone with a custom ROM. I better uninstall SC and remain safe with a working phone.

**Comment by Quix0r** [comment]
But how does @Nextcloud do this? I have it running and accessing a "Let's Encrypt" secured server.

**Comment by westnordost** [comment]
It's not StreetComplete that makes the phone unsafe and it is also not a custom ROM that makes it unsafe, but the mere fact that you have such an old version is making your phone vulnerable. There are simply unfixed security issues there.

**Comment by mnalis** [comment]
@Quix0r and if you are happy with a phone which only has SMS and calls, I'd suggest not going for a smartphone in the first place (but an older brick or feature phone). 

As westnordost says: your smartphone current ROM is so old that it is vulnerable to tons of exploits. Yes, you can safeguard against most of them if you never connect your phone to the Internet (neither data nor WiFi) and uninstall all applications but SMS and Phone, but there are still exploits possible for example via vulnerable version of SMS application in your current ROM. Upgrading to the newer custom ROM would in fact probably make you *less vulnerable* than staying with obsolete and unsupported ROM from manufacturer. 

But it all depends on your risk assessment - if you don't have anything important on the phone nor you use it for anything important, and it is on prepaid or fixed plan (so attacker can't rack up your bill) than you could just continue using it while it works (and downgrade apps if they stop working after upgrades). But do note that if attackers do get control of your phone via some exploit, they can use it to make it look like you're the one doing criminal activities instead of them..
