### ISSUE TITLE
Quest for merging streets

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#2262]
### General

Sometime I'm overwhelmed by the count of Street related question. In most cases the cause of this is a street that is split into many tiny parts.
Please set a question that ask if two street are the same.
Conditions: 

1. Same Street type is set
1. Don't show this question if both street-parts have not the same tags.

### Checklist
Checklist for quest suggestions (see guidelines):
- [ ] 🚧 To be added tag is established and has a useful purpose
- [ ] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [ ] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [ ] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [X] 🕓 Applies to a reasonable number of elements (Worth the effort)

**Comment by andrewharvey** [comment]
I propose an alternative solution, instead where multiple ways form a non-branching segment, StreetComplete should present them all together as a single quest (eg. ask what the surface is once, instead of X times), but importantly have an option "differs along the way". This option is already present and will let you cut the segment, but it should also work the same for these segments streetcomplete shows as one.

These days in OSM it's quite common for a single street between intersections to be split many times due to speed limit changes, parking lane changes, turn lanes, lane counts, etc. but most of the road quests have the same answer for most of the segments (surface, lighting).

**Comment by matkoniecz** [comment]
Not sure how hard it would be to implement.

If done I would propose to merge only if sections are really tiny. 4m sections are irritating, 100m sections are fine.

**Comment by andrewharvey** [comment]
> Sometime I'm overwhelmed by the count of Street related question. In most cases the cause of this is a street that is split into many tiny parts.
> Please set a question that ask if two street are the same.

As originally described I don't see how this would really need a ground survey, we can already automatically detected non-branching ways which share the same tags, so a survey is not required to merge these. More likely there is a reason why they are not merged (like have different tags or different relation members)

**Comment by westnordost** [comment]
I fear whatever the solution (yours, or @andrewharvey ), the technical effort to do something like this would be prohibitive.
