### ISSUE TITLE
Label buildings as libraries

### ISSUE THREAD

**Issue by jakeisnt** [westnordost/StreetComplete#2265]
**Use case**
 
Libraries are important civic buildings and are often freestanding structures. It seems important to be able to label buildings with this level of specificity. 

**Proposed Solution**

Add 'library' to the list of civic buildings for the 'What kind of building is this?' quest.

**Comment by matkoniecz** [comment]
I would say that buildings constructed as libraries, especially one with clearly distinct architecture (in any way) are quite rare. I would expect that for this cases leaving note may be sufficient.

**Comment by smichel17** [comment]
Maybe different by country. All three local to me ({Northampton Forbes, Florence Lily, Williamsburg Meekins} library, MA, US) fit both criteria.

**Comment by jakeisnt** [comment]
Libraries have historically been important structures and buildings are
often built for them. I've lived in a couple of cities in the US and in
Europe, and anecdotally I've only ever been to one public library that
didn't occupy most of the building. In those locales, at least, I think
this tag would be useful.

The case for not introducing a 'library' label to me is that individual
businesses can be labeled as libraries and these can be seen to occupy the
majority of certain buildings. To this, I'd argue that libraries are often
important for architectural reasons and as community centers. Further,
there is no current quest I'm aware of that allows users to find and tag
businesses with attributes - being able to clarify the name of a business
isn't the same procedure.

**Comment by rhhsm** [comment]
Another request to add a certain building type. Maybe we should be a bit more systematic and find a method to determine which building types are worth including, and which not. Maybe the number of buildings already tagged with a certain kind can be used as a guide. Or could we vote certain types up or down?

**Comment by westnordost** [comment]
I decided to not include this. Libraries are in the civic category, you can simply answer that it is a civic building.

If I included library, I would also need to include police stations, fire stations, museums, community centers etc. as they may be some historic structures as well.

**Comment by jakeisnt** [comment]
If I see a library building, then, how should it be labeled?

**Comment by smichel17** [comment]
> If I see a library building, then, how should it be labeled?

@westnordost said, with the generic "civic building" category. I think this is another instance of https://github.com/westnordost/StreetComplete/issues/1952#issuecomment-704563446

> If I included library, I would also need to include police stations, fire stations, museums, community centers etc.

My first reaction was, "What's so bad about that?"

However, then I realized this is just the building **type** quest not building **use**. So I think my reaction comes from the feeling, "Of course those other uses should be tagged." Which is true, but isn't actually what this particular quest is about -- it's just that there is no building use quest.

Although, maybe I still support fire stations, since they uniquely must have a large enough garage to house the fire engines. The others *sometimes* have unique building types, but not always.
