### ISSUE TITLE
Cycle ways and defaults in different territories may be misleading

### ISSUE THREAD

**Issue by jamescridland** [westnordost/StreetComplete#2276]
In Queensland, Australia, it's [always legal to ride on the pavement/footpath](https://www.qld.gov.au/transport/safety/rules/wheeled-devices/bicycle#footpath) where there isn't a sign indicating otherwise.

The "is there a cycle lane on this road" quest, in Queensland, returns a screen that offers [a number of answers](https://podnews.net/uploads/cycle-lanes.jpg). In reality, in Queensland, the answer is almost always going to be "none, but cyclists are allowed on pavement", rather than "none" - assuming that there is, of course, a pavement or footpath next to the road (which is not always the case).

To confuse further, this is [not the case in New South Wales](https://www.rms.nsw.gov.au/roads/bicycles/safety-rules/road-rules-for-bicycle-riders.html), where cyclists are not allowed on pavements or footpaths, except for children.

One easy fix here: perhaps rename "none" to be "none, and cyclists are not allowed on the pavement" to make it clear.

Many StreetComplete users may not be cyclists and may not know the legal default in different territories. I worry whether OSM is being filled with incorrect data here, since it asks some knowledge of the user that they may not have. If these are configurable per territory, it might be nice if these read: if (a pavement exists) then ("none, but cyclists are allowed on pavement - %%TERRITORY%% standard")

**Comment by matkoniecz** [comment]
> The "is there a cycle lane on this road" quest, in Queensland, returns a screen that offers a number of answers. In reality, in Queensland, the answer is almost always going to be "none, but cyclists are allowed on pavement", rather than "none" - assuming that there is, of course, a pavement or footpath next to the road (which is not always the case).

Thanks for reporting problem. Do you know what is the preferred/standard tagging for such case by a local mapping community?

> One easy fix here: perhaps rename "none" to be "none, and cyclists are not allowed on the pavement" to make it clear.

Note that it may cause problems elsewhere if such change would be globally applied. 

In Poland there is a difference between "sidewalk where cyclists are not allowed in general" and "sidewalk where cyclists are not allowed at all" - there is a special rule allowing to cycle on sidewalks in case of a poor weather, unless signed with "no cyclists" traffic sign.

**Comment by westnordost** [comment]
What StreetComplete should try to do is to involve the user as little as possible in answering the legal situation and as much as possible in answering what he sees on-site.

The "explicitly on sidewalk" and the "ok to cycle on sidewalk" options exist because of these signs in Germany:
![image](https://user-images.githubusercontent.com/4661658/99186464-c02d6700-2750-11eb-9a8e-b6be3982900d.png)
This is a sidewalk but cyclists may also use it (but are "guests" there, i.e. don't have any right of way)

![image](https://user-images.githubusercontent.com/4661658/99186520-14d0e200-2751-11eb-8e79-35c9ffc37e65.png)
This is a sidewalk that is to be used explicitly by both pedestrians and cyclists

---

So in your case, the right answer would simply be "no cycleway" because the "sidewalk is allowed to be used by cyclists" option is meant to reflect the mentioned case. Maybe the wording of that option should be changed to include the information that it should be s**igned that way**. Would that help?
So far I refrained from phrasing it that way because I know many places on the countryside where there are no signs at all and there is a path next to the road way that is clearly used as a cycleway as well. I don't know the legal situation but that's the de-facto usage.

**Comment by westnordost** [comment]
Another option would be to completely remove the "ok to use sidewalk" option

**Comment by jamescridland** [comment]
You won't see any signs in Queensland, because it's always okay to cycle on the sidewalk.

You won't see any signs in NSW, because it's never okay to cycle on the sidewalk (unless you're with children).

Sidewalks are quite difficult in general here - I gather that about 75% of suburban Brisbane does not have a sidewalk on both sides of the road. I map them separately, because they're separated from the road by a grass verge, sometimes quite some distance from the road, and I'm considering wheelchairs.

All this is to suggest that the option of "OK to use sidewalk" should probably be removed everywhere. It's either default to 'on', default to 'off', or clearly signed, in different territories: the real benefit of this quest is to highlight proper cycleways, it seems, and not sidewalks which are relatively useless to cycle on anyway.

**Comment by jamescridland** [comment]
![PXL_20201116_003310885 MP](https://user-images.githubusercontent.com/231941/99201545-2f5d9680-27f7-11eb-99d4-e98ddcfa6b4d.jpg)
As one example. No sidewalk on the far left. A path on the right, which I map separately. At 1.3m wide, it's not that great to cycle on, and most people would cycle on the road. No signs.

**Comment by westnordost** [comment]
Right, it's summer over there. Looks inviting :-)

The current wording is _"none, but cyclists are allowed on sidewalk"_. I am reluctant to remove that option altogether because there is no other way to record the information mentioned above.

But on the other hand, what is tagged in that case is `sidewalk:right:bicycle=yes` and if the option is not chosen (f.e. you choose "no cycleway"), any previous `sidewalk:right:bicycle=yes` will be deleted. So in cases like yours, this has the potential to remove correct information just because the user does not now the legislation.

If I changed the wording to _"none, but cyclists are **explicitly** allowed on sidewalk"_, it still does not solve that problem because anyone living in your area would then answer "no" to this, as the allowance on the sidewalk is implicit. But this will then tag it wrongly (i.e. remove `sidewalk:right:bicycle=yes`). So I guess it is best to remove that option altogether.

**Comment by FloEdelmann** [comment]
Would that question be worth a new quest "Are cyclists allowed to use the sidewalk?", which would only be asked in regions where this is not the default?

**Comment by RubenKelevra** [comment]
> The "explicitly on sidewalk" and the "ok to cycle on sidewalk" options exist because of these signs in Germany:
> ![image](https://user-images.githubusercontent.com/4661658/99186464-c02d6700-2750-11eb-9a8e-b6be3982900d.png)
> This is a sidewalk but cyclists may also use it (but are "guests" there, i.e. don't have any right of way)
> 
> ![image](https://user-images.githubusercontent.com/4661658/99186520-14d0e200-2751-11eb-8e79-35c9ffc37e65.png)
> This is a sidewalk that is to be used explicitly by both pedestrians and cyclists (cyclists may not use the road)


May I add that there more to this in Germany... E-scooters are allowed to drive on sidewalks where bicycles are allowed, but not allowed on sidewalks where bicycles are only permitted (white sign).

Which is weird and extremely quirky IMHO but this makes the destinction between both (which are in reality pretty irrelevant) somewhat important.

When I ride an eScooter on the pavement when there's just the white sign I might get a ticket. 🙄

**Comment by westnordost** [comment]
> Would that question be worth a new quest "Are cyclists allowed to use the sidewalk?", which would only be asked in regions where this is not the default?

First of all, what should be asked is whether it is signed to be allowed or not, not wether it is allowed in general (implicitly or explicitly). But then, yeah, this would be possible. Though, the quest needs to be clear about that the signage is asked for. This may put the actual usage of the footway at odds with what is tagged cause I imagine many footways will not be signed explicitly in any way. So the elements for which the quest would be asked would need to be reduce somehow to maybe only sidewalks (footway=sidewalk / sidewalk=both/left/right/yes).

**Comment by jamescridland** [comment]
> what should be asked is whether it is signed to be allowed or not, not whether it is allowed in general

I think we should be reflecting the reality on the ground, not the availability of signage, personally.

"no there isn't a sign" doesn't mean "no, you can't cycle here". In this territory. But in yours - it does.

The first questions should be: "Is there a sidewalk on this side of the road" - a quest that already exists. Once that's answered, and we know there's a sidewalk, the question for Queensland should be:

"Is there a sign **prohibiting** cycling on the sidewalk?"
* NO - cyclists are normally allowed to use the sidewalk
* YES - cyclists are prohibited here by a sign
 
The question for New South Wales should be:

"Is there a sign **allowing** cycling on the sidewalk?"
* NO - cyclists are normally prohibited to use the sidewalk
* YES - cyclists may use the sidewalk here according to a sign

This is not easy! But we should be careful that a quest adds to OSM in a responsible way. My concern with this quest, at present, is that it may not be doing so.

**Comment by smichel17** [comment]
I think there should always be both signed options, right? Just because there is a default, does not mean that it will not be explicitly signed, too.

**Comment by jamescridland** [comment]
Sure - but it's ensuring that people who are unfamiliar with cycle laws don't mess the data up.

I think this is a unique quest for StreetComplete in that it requires not just the surveyor to look at the road, but also to know the local law. If the app can't help people with what the local law is, this quest has the capability to produce a lot of incorrect data. That's what makes me a little nervous about it.

**Comment by RubenKelevra** [comment]
Maybe we should split the quest into a physical and legal part and deactivate both by default or when the territory changed from the last one the app has run? 

This would allow us to show an info about the quest when activating, which might help the user to understand the legal situation. 

The physical part of the quest could just gather stuff like explicit stuff, like signs, road markings etc and the legal one could precise the situation for Germany mentioned by @westnordost above and capture the quirks of implicit allowed usage in different areas.
