### ISSUE TITLE
"How many lanes for cars does this road have?" is problematic with bus lanes

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#2284]
During translating  quest_lanes_title I noticed that it may be problematic for roads including bus-only lane.

https://en.wikipedia.org/wiki/Car seems to confirm that cars are not including busses

---

To clarify, I know about 

> Specify the total number of marked lanes (both sides), including lanes reserved for buses etc. Lanes occupied with parking cars don't count.

specification, but it is a bit confusing

**Comment by Atrate** [comment]
"Motorized vehicles" then maybe?

**Comment by FloEdelmann** [comment]
As suggested by @smichel17 in https://github.com/westnordost/StreetComplete/pull/2269#issuecomment-728272736:

> How many lanes does this road have? Not counting bike lanes.

This makes it clear that bus lanes should be included. Maybe parking lanes should also be explicitly excluded:

> How many lanes does this road have? Not counting bike lanes or parking lanes.

**Comment by RubenKelevra** [comment]
Maybe just use

'Count full width road lanes for e.g. cars, busses and trucks. Do not count parking lanes nor bike lanes'

**Comment by xuiqzy** [comment]
Note that in the English wiki for lanes, motorcycle lanes are specifically excluded as well in the second sentence.
In the English and German wiki, in the section on what to include, it says that it includes "General purpose traffic lanes suitable for vehicles wider than a motorbike".

**Comment by RubenKelevra** [comment]
Maybe just use this but with a bit more friendly tone 🤔

**Comment by westnordost** [comment]
I deliberately chose the term "Car" over such terms as "full width lane" or "lane for motorized vehicles" because the latter while being more correct is longer and more complicated, sounds like officialese.

I think there is no bean counter in the world who would answer who would leave a note instead and lecture something like "there are no lanes for cars at all, but there are 4 lanes for motorized vehicles in general!". 

@matkoniecz bus lanes are mentioned explicitly in the second part of the sentence

**Comment by RubenKelevra** [comment]
I shared this image in #2269 which shows a road where two vehicles can pass each other, if they are small enough, but it's not really comfortable IMHO as soon as we talk about SUVs.

![IMG_20201117_151311__01](https://user-images.githubusercontent.com/614929/99421039-3cb17880-28fe-11eb-8f64-452bbcd1a8d1.jpg)


So the answer a user gives is based on his assumption what a 'car' is.

How about changing this to 'can two trucks comfortable pass each other', this would be easily understood and narrow streets would be tagged with 1 lane instead of two, giving more emphasis the difference between roads where you have to slow down to pass each other.

**Comment by westnordost** [comment]
There are a lot of different trucks though too. This might be confusing.

**Comment by westnordost** [comment]
Moving, on,


### These are the current strings

Marked, both sides: 
>Specify the total number of marked lanes (both sides), including lanes reserved for buses etc. Lanes occupied with parking cars don't count.

Marked, specify one side only: 
>Specify the total number of marked lanes here, including lanes reserved for buses etc. Lanes occupied with parking cars don't count.

Unmarked:
> Specify the total number of lanes the road would have if lanes were marked. In other words, how many cars can comfortably pass each other?

### Suggestion for wording change

Taking into account the feedback here, here is my suggestion on how to change the wordings (emphasis only here):

Marked, both sides: 
> Specify the total number of marked lanes (both sides) **usable by car traffic. So, bike and parking lanes don't count. 
> If any lanes are reserved for busses, please leave a note instead.**

Marked, specify one side only: 
> Specify the number of marked lanes here **usable by car traffic. So, bike and parking lanes don't count. 
> If any lanes are reserved for busses, please leave a note instead.**

Unmarked:
> **Estimate how many cars can comfortably pass each other here. Narrow residential roads with parking cars often do not have enough space for more than one car to pass through simultaneously.**

### Considerations

**Bus lanes and notes**
- What should be included in `lanes=*` are the normal car lanes, but also bus (and taxi) lanes, hgv lanes etc. I looked at taginfo, `lanes:hgv` is really rare, so it suffices to only mention busses for the sake of keeping the sentence simple
- I think it is better to ask the user to leave a note if he spots a bus lane rather than answering the total number of lanes. Just specifying `lanes=*` without also tagging `lanes:bus=*` in the same changeset could be considered as incomplete tagging as the missing bus lane tag suggests that there is one more lane available for use. To directly implement that option into StreetComplete would be both effortful and I can not think of any good place in the UI to add this option, so a note will be OK I think

**bike and parking lanes**
- used the wording "usable by car **traffic**" to make clear that bike and parking lanes don't count plus also wrote it explicitly. I.e. parking lanes are usable by cars, but not by car traffic. Bike lanes are too narrow to use for car traffic, so this example should make clear that (if something like that existed??) scooter/motorbike lanes are also out.

**roads without lanes**
I fear this is a bit uncharted territory, the wiki doesn't say a lot about this and the little it says about it actually is from a discussion I started a year ago or so (`lane_markings`). Nothing much changed since then. But there seems to be a consensus of a sort that tagging decimals for `lanes`, f.e. `lanes=1.5` is not really recommended, instead it is suggested to record the width. 

However, the width alone is not useful as long as not all of parking lanes, bike lanes and any other special lanes are not also tagged, since `width` is documented to include all of this, i.e. the width is measured from "curb to curb". So, to tag `lanes` is useful after all, as an estimation how many cars can go side by side (more or less) comfortably, until all the information (width, parking lanes, cycle lanes, ...more?) is recorded and also help to decide whether it makes sense to ask people to measure the width of the road.

However, what the wiki does mention is this "Remark for data consumers":
> Many ways have not yet been tagged with the total number of lanes at all points, but only with the number of through lanes of a longer section. Therefore, data consumers can mostly treat the lanes tag as a minimum rather than an exact number.

So, it seems that one should rather round down than up, as data consumers should _treat the lanes tag rather as a minimum. than an exact number_. This is the reason why I wrote "comfortably". And since this came up so early already (@RubenKelevra ), I think it is better to explicitly state that `lanes=1` is OK for narrow residential roads, to resolve any doubts like "wouldn't this be a oneway road then?".

By the way, there will not be any parking lane quest soon because the rules for "no parking" turned out to be too complicated after a short discussion on Slack US, see [exhibit A](https://www.theaa.com/driving-advice/legal/parking-guide-yellow-lines#yellow), [exhibit B](http://guide.saferoutesinfo.org/dropoff_pickup/curb_striping_and_other_pavement_markings.cfm) and [exhibit C](https://www.mercurynews.com/2019/03/04/heres-what-colored-curbs-red-blue-green-white-and-yellow-mean-for-california-drivers/), and these are just two countries / states.

### What I'll change further apart from the wording

* When the lane count is 1, I'll render the displayed lane a little broader, so it doesn't look like a oneway but it looks like a "1.5 laned" road, also to remove doubts by users that think that answering `lanes=1` can't be right

**Comment by westnordost** [comment]
Any feedback on my suggestions?

**Comment by RubenKelevra** [comment]
Sounds reasonable, to me.

Only one small thing:

Both sides sounds a bit strange. It works perfectly for sidewalks, but directions might work better for lanes.

This would follow the tagging convention, where we tag sidewalks with right and left thus sides, but lanes with forward and backward thus directions (of traffic flow).

**Comment by matkoniecz** [comment]
I like this new wording.
