### ISSUE TITLE
Curb quest doesn't show up

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#2291]
I've searched on the map with a freshly cleared app-data to ensure no caching going on, but I could not find a single curb quest.

Am I'm missing something? I thought it should show up on pedestrian crossings?

Version 27b1

**Comment by matkoniecz** [comment]
> Am I'm missing something? I thought it should show up on pedestrian crossings?

It shows not on crossings, some additional detail is required

- Nodes with `barrier=kerb`
- Also nodes where `barrier=kerb` way intersects with way for pedestrians
- Also nodes where `footway=sidewalk` and `footway=crossing` tags make clear that asking the question is a good idea 

So either `barrier=kerb` needs to be marked or one of tagging styles for `footway=sidewalk`/`footway=crossing` needs to be used.

**Comment by RubenKelevra** [comment]
Hmmm... but all crossings I know have curbs...

So how is this supposed to work on a street with say

```
highway=residential
sidewalk=both

and a point on the way with

```
highway=crossing
crossing=uncontrolled
```

**Comment by matkoniecz** [comment]
> Or is this only supposed to work on sidewalks mapped as ways?

Yes.

**Comment by westnordost** [comment]
> I've searched on the map with a freshly cleared app-data to ensure no caching going on, but I could not find a single curb quest.

No need for that.  The cache is invalidated on each update.

**Comment by westnordost** [comment]
Here is an overview. StreetComplete asks for the blue element:

![image](https://user-images.githubusercontent.com/4661658/99389255-0ad8eb80-28d7-11eb-9eb2-93d8b029adf2.png)

**Comment by voussoir** [comment]
Hi @westnordost,

What is your opinion on this situation? SC currently does not make quests out of these.

![Untitled](https://user-images.githubusercontent.com/7299570/110687245-2709dc80-8195-11eb-8f3d-5ddbeb959c61.png)

**Comment by westnordost** [comment]
This is intended behavior. 

To put a `barrier=kerb` at the location of the blue circles is a mistake, because there is no kerb at that edge. Imagine a pedestrian router wants to lead a wheelchair user coming from the right side to the top side (so no crossing of the street required). The pedestrian router would encounter a piece of sidewalk, then a kerb, then another piece of sidewalk.

**Comment by voussoir** [comment]
Yes, I know what you mean. So I suppose the way to map it would be to add a node inside the crossing way that is very close to the edge, and mark that as the kerb node. I can do that with regular editing tools, but it's a bit of a bummer that I can't do it during a StreetComplete walk. Especially since 4-way crossings would benefit most from tactile_paving and kerb status as they are more dangerous.

I tried looking around OSM to find precedent of putting kerb nodes at my blue circle versus a node just inside the crossing way, but can't find regions with this level of detail at the moment. I do think routers should infer the the kerb is referring to the sidwalk-crossing transition and not the sidewalk-sidewalk turn. Perhaps we'll see how the map develops.

Thanks for your response.

**Comment by westnordost** [comment]
> I tried looking around OSM to find precedent of putting kerb nodes at my blue circle versus a node just inside the crossing way, but can't find regions with this level of detail at the moment. 

You will find places where it is mapped this way, but it shouldn't be. Maybe this situation should be added as a JOSM and iD warning

**Comment by andrewharvey** [comment]
That's surprising because SC is adding barrier=kerb to these nodes, eg version 2 of http://osmlab.github.io/osm-deep-history/#/node/5866630096

**Comment by matkoniecz** [comment]
> That's surprising because SC is adding barrier=kerb to these nodes, eg version 2 of http://osmlab.github.io/osm-deep-history/#/node/5866630096

I created https://github.com/streetcomplete/StreetComplete/issues/2654
