### ISSUE TITLE
Explain use of quest data in-app

### ISSUE THREAD

**Issue by NotAFile** [westnordost/StreetComplete#2295]
**Use case**

As the list of quests has grown, it has started to include an increasing number of quests where the usefulness is not immediately apparent to the average person. This can be demotivating.

This documentation is already collected through the quest proposal process, however this is not something most people will look at. It would be much better to expose it in the app.

**Proposed Solution**

The quest entry screen grows a small label below the question that indicates the high level use of the data, or what project it belongs to, for example "wheelchair navigation". Tapping this could expand further details on why the data is useful and have links to projects making use of the data.

**Comment by matkoniecz** [comment]
Or maybe show it below achievement screen. So nice links are displayed there but some message with info how quest data is used may go there.

From my TODO file

> Human stories are powerful – add personal message from real nice users (cyclestreets? osmand? osm-carto? wheelmap? hunt for some OSM use in science?)

> requires
> - (a) green light from @westnordost
> - (b) finding some users of data collected by SC, especially for less obvious cases
> - (c) asking them for agreement and writing with them some short thank you (it should be short and make clear which data is used and how, maybe also have a photo of a face of person)
> - (d) maybe include screenshot showing how this specific OSM data is used (skip projects violating OSM license by not including a proper attributions, such as MAPS.ME)


> Maybe quote domething from published scientific research (filter for some good research, not something that is bogus and just happens to use OSM )

> Maybe https://www.nature.com/articles/s41467-018-07557-4

> "OpenStreetMap (OSM) data (www.openstreetmap.org) were the main source of infrastructure information. Considering spatial accuracy, the quality of these data is comparable to commercial geodata products"

> https://www.nature.com/articles/sdata201545
> "Similarly, OpenStreetMap (OSM) vector datasets63 were regularly used to integrate the VMAP0 settlement dataset and account for land-use types, building sites, and locations of points of interest that may be strongly correlated with population presence (e.g., health clinics, schools, and police stations). Furthermore, OSM road and river data were often deemed to be more complete than the corresponding VMAP0 data and, thus, were used to increase the precision and accuracy of the gridded population outputs64."

**Comment by NotAFile** [comment]
> Or maybe show it below achievement screen

I had considered that, however that wouldn't fulfill the purpose here. The goal would be to try to prevent first time mappers from dismissing a quest out of hand. If this information is only shown after solving many quests or on a separate screen, it is already too late.

**Comment by matkoniecz** [comment]
Achievements are for categories, so they may be convinced about solving a related quest.

Quest list is very busy already, while achievement screens are a bit empty if no link is shown.

**Comment by NotAFile** [comment]
@matkoniecz ah, maybe I didn't use the correct words. I'm talking about the quest solving screen, not the settings. The solving screen is where most users will see the question for the first time, so that's where they would have to be convinced that it's not a complete waste of their time to do something weird like counting stairs.

**Comment by matkoniecz** [comment]
> @matkoniecz ah, maybe I didn't use the correct words.

No, it was me.

> I'm talking about the quest solving screen, not the settings. 

It also is a place where screen space is especially precious... Not sure is it the best place to to add even more things there.

**Comment by cyclingcat** [comment]
What about a "Did you know?" screen (at each app start, occasionally shown via the notification button or both) in order to present such kinds of information (randomly or in a "round robin"-like manner)? Many apps on several platforms show such a screen, so it's an established method to inform users about features they possibly aren't aware of. (Of course there should be a "Never show again" checkbox nearby and a possibility to reenable these hints later.)

This would also be useful for many UI-related proposals (e.g. #2292): a possibility to inform the user about more hidden UI elements such as long tapping on certain screen regions. The list could start with just a few items and enhanced later (it has to be translated though).

Examples:

"Did you know that solving quest XY is useful for ABC?"
"Did you know that long-tapping on a quest icon gives you the possibility to temporarily disable this quest type?" (would solve https://github.com/westnordost/StreetComplete/issues/2292#issuecomment-729022154)
"Did you know that long-tapping on the map is an easy way to leave a note?"
"Did you know that you can you configure the app to keep the screen on while you use it?"
"Did you know that there is a dark theme as well? Look into the settings!"
Or even: "Do you like this app and want to support the developer? Become a sponsor!"

Just an idea...

The cycling cat

**Comment by matkoniecz** [comment]
> What about a "Did you know?" screen (at each app start

Nononononnononononon. Noooooooooooooo. No. Please no.

It may be just me, but it is one of interface patterns that I simply deeply dislike.

**Comment by westnordost** [comment]
Same.

So basically the achivements are built for educating the user about how the solved quest types may be used: First in the little text that is shown and then also by the links that are being unlocked.

I am not going to build a system parallel to that with the same purpose. So, I am going to close this issue.

Your actual issue seems to be that you find you are overwhelmed by quest types that are unimportant. It is true, many **are** unimportant. I plan to do something here to make it easier for users to have only those quest types enabled that are interesting for them.

**Comment by cyclingcat** [comment]
Hence the request for a possibility to disable it immediately, so this would be a one-time action for each user who doesn't like it. (Of course this information window shouldn't be misused for trivialities or mere bullshit like in many other apps; perhaps this is the reason you dislike it :smile:)

The big advantages of this approach would be IMHO that it's not another hidden page (as it would be the case with a FAQ or the same information in a long list) and that the information is presented in smaller portions, thus not overwhelming the user with a long text he will probably forget much faster.

The cycling cat

**Comment by FloEdelmann** [comment]
What about showing the icons of all quest types that count towards a given achievement when clicking on the achievement icon in the achievement overview screen, or below the achievement graphic when you earned a new one?

**Comment by rouelibre1** [comment]
> [...] educating the user about how the solved quest types may be used [...] by the links that are being unlocked. 

It's also a really cool way to find out about the applications that are build on OSM, I really enjoyed discovering them this way. I feel it serves the goal of making the users want to use the app more, and get more involved in OSM (but maybe that's just me being too enthusiastic about the possibilities of OSM since I'm in the discovery phase).
