### ISSUE TITLE
Doesn't upload, or does?

### ISSUE THREAD

**Issue by Natureshadow** [westnordost/StreetComplete#230]
We iterated through the issue "no visual feedback on uploads whatever I do" already, but mow StreetComplete started to show new behaviour that makes we wonder whether anything happened or not.

It says ⭐18 in the navbar. When I answer a quest, it adds (+1) for a moment, then it disappears, but never switches to ⭐19.

Is it because the upload fails, or because the counter is broken, or because the counter does not count what I think it counts?

**Comment by Natureshadow** [comment]
... or the counter is no counter, after all, or...

**Comment by Hillside502** [comment]
With regards to whether or not the uploads have failed, suggest subscribing to the RSS feed of your OSM changesets at:-

https://www.openstreetmap.org/user/xxxxx/history/feed

where xxxxx is your OSM username.

**Comment by westnordost** [comment]
This can happen if the upload fails due to a conflict (someone else already answered the quest, the element does not exist anymore etc.).

That the user is not explicitly notified with "oh no there was a conflict" or something is deliberate as the user cannot do anything about that anyway and it doesn't concern him anyway, really, because the conflict has already been solved.

That the ⭐-display needs to be redesigned is another ticket I will be getting to later.

**Comment by Natureshadow** [comment]
> This can happen if the upload fails due to a conflict (someone else
> already answered the quest, the element does not exist anymore etc.).

Hmm. This happened to me on at least 20 quests in a row today. Seems a
bit unlikely.

**Comment by westnordost** [comment]
This may be a bug then. Please check your OSM history: Were the changes in question applied to the map? (If you don't recall, please check the next time this occurs to you)

**Comment by Natureshadow** [comment]
> This may be a bug then. Please check your OSM history: Were the
> changes in question applied to the map? (If you don't recall, please
> check the next time this occurs to you)

No changes were uploaded to OSM under my account during the last 21 days.

**Comment by westnordost** [comment]
Is the information that was asked for for any one of those quests now on the OSM map?
