### ISSUE TITLE
Maximum height quest, but the road is not a bridge

### ISSUE THREAD

**Issue by julietkilo** [westnordost/StreetComplete#2301]
**How to Reproduce**
Solve a lane quest on a local road of class highway=residential. After commit a new quest appear for this road. The quest asks for the maximum height under these bridge, but the road is not a bridge. It has these attributes:
highway=residential
lane_markings=no
lanes=2
lit=yes
maxspeed=30
name=Siebenbürger Straße
sidewalk=both
source:maxspeed=DE:zone30
surface=asphalt

**Versions affected**
v27.0-beta1

**Comment by FloEdelmann** [comment]
This has already been reported and fixed: #2287

**Comment by westnordost** [comment]
You should update to beta2

**Comment by mxxcon** [comment]
I'm getting this bug on v27.0 from Play Store

**Comment by westnordost** [comment]
Did you invalidate the quest cache and download again? 

On 28 November 2020 07:18:27 CET, mxxcon <notifications@github.com> wrote:
>I'm getting this bug on v27.0 from Play Store
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/2301#issuecomment-735045862

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mxxcon** [comment]
I didn't. But after a bit a realized that I think all those quests were legitimate.(that's why I deleted my message.) I just didn't expect that many road segments to intersect with overhead subway tracks and highways around my area. 😅 
At first glance it looked wrong but after inspecting it closer I understood why it was asking that quest.
