### ISSUE TITLE
StreetComplete users delete oneway:bicycle=no when answering "Add whether there are cycleways"

### ISSUE THREAD

**Issue by A67-A67** [westnordost/StreetComplete#2310]
I've seen this multiple times now and it seems to be a bug in StreetComplete with users that are unaware of what they are doing wrong. [Example changeset](https://www.openstreetmap.org/changeset/94214802).

These edits seem to be about cycle lanes, because the question is 'Add whether there are cycleways'. In this case the correct tag cycleway:both=no is added, but at the same time the bicycle exception for oneway traffic (oneway:bicycle=no) is removed erroneously. This is quite strange behaviour, as oneway restrictions have little to do with cycle lanes. 

Note that many oneway streets in the Netherlands have an exception for cyclists and especially in the historical centres, there are no cycle lanes. So the combination cycleway:both=no and oneway:bicycle=no is very common.

**Comment by matkoniecz** [comment]
It is likely combination of high complexity of real world, less than ideal interface and users not answering correctly.

Maybe some extra confirmation is needed here?

Maybe if oneway:bicycle=no is tagged already then prefill "cyclists may use road in both directions" for direction where according to existing tagging only cyclists may drive?

I tested for https://www.openstreetmap.org/way/264306015#map=19/50.07046/19.96122&layers=C found by https://overpass-turbo.eu/s/10nq

**Comment by A67-A67** [comment]
I think it's important to understand that at least Dutch users will see oneway restrictions and cycle lanes as two completely separate things. So someone who's mapping cycle lanes, wouldn't be aware that he's also mapped oneway restrictions for cyclists.

So I wouldn't remove an existing tag like oneway:bicycle=no when there was no explicit action by a user to remove it.

PS. I'm not a StreetComplete user, so I don't know exactly what a StreetComplete user sees. I just noticed incorrect edits by StreetComplete users and had to restore this important tag for bicycle routing.

**Comment by westnordost** [comment]
This is how the interface currently looks like

1. initial display
![device-2020-11-21-153229](https://user-images.githubusercontent.com/4661658/99879732-f6fef380-2c0e-11eb-9e40-73d99f109fde.png)

2. selecting what kind of cycleway there is
![device-2020-11-21-153254](https://user-images.githubusercontent.com/4661658/99879733-f8302080-2c0e-11eb-894a-c6bafb77a0df.png)

3. final view before "OK"
![device-2020-11-21-153305](https://user-images.githubusercontent.com/4661658/99879735-f9f9e400-2c0e-11eb-9f97-4904ef7ade6d.png)

**Comment by westnordost** [comment]
If anything should be done on our side, it could be one of these two possibilities:
1. When the user selects "none", do not remove any previously set `oneway:bicycle=no`. However, this might go against the user's expectation that if he deliberately selects "none" and not the item right next to it, he expects that the tag is removed
2. consider `oneway:bicycle=no`  alone (without accompanying `cycleway:*=none`) tagging as complete enough to initially pre-select the "none, but cyclists may use road in both direction" selection. (@matkoniecz suggestion)

**Comment by westnordost** [comment]
@matkoniecz would then look like this for a road that is just tagged with `oneway:bicycle=no`.

![device-2020-11-21-154920](https://user-images.githubusercontent.com/4661658/99880039-39293480-2c11-11eb-9ce9-357c89b17106.png)

Alright, I think it is a reasonable assumption to infer that there is no cycleway when `oneway:bicycle=no` is set and nothing else in terms of `cycleway`.

**Comment by matkoniecz** [comment]
> @matkoniecz suggestion would then look like this for a road that is just tagged with oneway:bicycle=no.

Maybe it would be a good idea to preset also other side with "no cycleway infrastructure"? Right now it asks "Is this still the cycleway situation here?" and there is no obvious way to select "yes, it is this way".

I know that I can tap on the other road side and select "nothing here" but someone new to SC will be confused.

**Comment by westnordost** [comment]
They might be confused, but they will not tag anything wrong. That the text "Is this still the cycleway situation here?" is shown is a different problem that cannot be solved here. It happens always when some previous tagging was discovered but nothing that was understood by StreetComplete.

**Comment by westnordost** [comment]
I noticed that some tests fail because of that change. The parser is currently very lenient when it comes down to `opposite*` values for `cycleway:left/right/both`. The wiki says that these values should be avoided.

After reading the discussion, I agree with it (that it is ambiguous), so I am changing the parser to not understand f.e. `cycleway:right=opposite_lane`, meaning that the UI will show these question marks in that case.
I think not understanding this tag is better than interpreting it in a way that may for the most part be correct but sometimes not,

**Comment by smichel17** [comment]
> The user did not see the "none, but cyclists may use road in both direction" selection, even though it is right next to the one he chose. So, this is not a bug in StreetComplete.

Was this text changed recently? Or maybe it is a localization problem? This is what I remember seeing:

![image](https://user-images.githubusercontent.com/6563664/99884939-6eda1780-2c29-11eb-8f8b-ed82a28ba758.png)

"Lane explicitly shared with other traffic" was also my understanding of that symbol. I didn't realize it ever has an effect on traffic in the other direction.

---

Separately, Google Street View captured the example @matkoniecz posted in August 2017, and if it still looks like that, the symbol is very faded:

https://www.google.pl/maps/place/Ermal/@50.0708578,19.9625283,3a,75y,134.62h,69.07t/data=!3m6!1e1!3m4!1stzjc-4IT_H-vQ9lOSrdMWQ!2e0!7i13312!8i6656!4m15!1m7!3m6!1s0x47165b2025d0bee9:0x5b83a4a06a7728ba!2sGenera%C5%82a+J%C3%B3zefa+Bema,+31-518+Krak%C3%B3w,+Poland!3b1!8m2!3d50.0714387!4d19.9623464!3m6!1s0x47165b8550355beb:0x3f8ecf30568a4c9a!8m2!3d50.0706321!4d19.9625962!14m1!1BCgIgARICCAI?hl=en

So it is possible that the person who tagged it simply did not notice the symbol.

**Comment by westnordost** [comment]
> "Lane explicitly shared with other traffic"

This is shown on non-oneways.

**Comment by matkoniecz** [comment]
> @matkoniecz suggestion would then look like this for a road that is just tagged with oneway:bicycle=no.

Is it intentional that it is not enabled for `oneway:bicycle=no` `cycleway=opposite`?

> So it is possible that the person who tagged it simply did not notice the symbol.

At least in Poland primary signage is a "bicycles are exempt" sign below sign of oneway roads (both under "this is an oneway road" and "no entrance from this side" signs)

**Comment by DerDings** [comment]
Today I stumbled upon this issue, too. Since the "no cycleway" icon has a big red X now, people (like I did) don't think there will be another "no cycleway [but...]" answer somewhere among the other options, without that big X. I think there are two main issues with this:
- The "no cycleway" option was [moved to the top](https://github.com/streetcomplete/StreetComplete/commit/42c203c45ecaad04ee965decd5cea2815567441e) because of a very similar issue, but the "none, but cyclists may use road in both directions" didn't follow along, although it is some kind of **no**, too.
- Users can't completely read what is currently tagged, even if the way is shown nearly horizontally ![photo_2021-01-10_17-25-43_2](https://user-images.githubusercontent.com/42044179/104129748-daa94880-536d-11eb-9f72-5a7130ffa3af.jpg). What's invisible here (german locale) is exactly the word "keinen" ("none"), which would have made the user (me) understand this is correctly.
Originally, it probably was intended that users read this text in the selection dialog and only see it appear in the graphic for confirmation. But when doing a resurvey, this graphic is the only place where you can see what is currently tagged. When opening the "select" dialog, which is designed to show descriptions fully readable, information about current state is not visible anymore.




I got two ideas how to make this less confusing:

- put the "none, but cyclists may use road in both directions" answer next to the "none" option
- on a resurvey, highlight what is currently tagged in the selection dialog. 
Also make sure it is not initially hidden when opening the dialog. This can be achieved 
  - by automatically scrolling down to the currently tagged item
  - by showing it as the first item in the list. If so, it should be full-width to not make all the following options swap places.

The second option would make the whole resurvey stuff more clear in my opinion.

**Comment by westnordost** [comment]
Well, the first suggestion is easily doable, so I just implemented that. The second is not that easy.
