### ISSUE TITLE
Group crossing quests into a single upload changeset

### ISSUE THREAD

**Issue by andrewharvey** [westnordost/StreetComplete#2318]
We now have a lot of crossing related quests which is great, but this leads to a lot of changesets, which makes it harder for OSMCha reviewers.

Do you think it would make sense to group all of these together into a single changeset, "Updated crossings".

- Add whether traffic signals have a button for pedestrians
- Add traffic_signals:sound tag
- Add traffic_signals:vibration tag
- Add tactile pavings on crosswalks
- Add whether pedestrian crossing has an island
- etc.

**Comment by andrewharvey** [comment]
Same for steps, group step count, handrail, direction, ramp, etc. into a single changeset.

**Comment by westnordost** [comment]
> makes it harder for OSMCha 

Well, OSMCha has some bugs that changes made with StreetComplete will not be shown correctly at all (anyway). See https://github.com/mapbox/osmcha-frontend/issues/492

Anyway, they way it is structured right now this is not possible. Every quest type is coupled to an own changeset with an individual comment and individual link to the wiki documentation. If something like grouping changesets by topic (or all in one changeset) ever was done, another solution for how the statistics are generated and displayed in the app would need to be thought of. As of now, basically the whole "profile" screen depends on the assumption that every quest uses its own changeset.

So for now, this is a will not fix.

**Comment by mmd-osm** [comment]
Another side effect that I'm experiencing more and more since 32.x has been released, is that the **same** object gets modified multiple times within a very short timeframe. As an example https://www.openstreetmap.org/way/957786191/history 

That's not exactly beautiful, but still not frequently enough that I would complain more loudly about it...

> OSMCha has some bugs that changes made with StreetComplete will not be shown correctly at all (anyway).

I'm not sure if such a broad statement is correct. However, what I can say is, if the same object has been modified multiple times within the same second across multiple changesets, that will trigger an Overpass bug, resulting in some erroneous OSMcha rendering.
