### ISSUE TITLE
Invalidate quest cache not working

### ISSUE THREAD

**Issue by MakiWolf** [westnordost/StreetComplete#2329]
**How to Reproduce**
Scan for quests on two different devices
Answer the question with one device
On the other device the question is still there, also when I Invalidate quest cache 
![image](https://user-images.githubusercontent.com/73300633/100550181-75dfd600-3278-11eb-9586-641818e896e3.png)

**Versions affected**
Version 27.0 on Android 9

**Comment by matkoniecz** [comment]
Note that if you invalidate the quest cache, all quests are marked as invalidated.

In other words it marks them as outdated and for replacement. Download of new quests happens when user is in this area or download is triggered manually.

See https://github.com/westnordost/StreetComplete/issues?q=is%3Aissue+invalidate+is%3Aclosed for some related reports.

**Comment by westnordost** [comment]
![image](https://user-images.githubusercontent.com/4661658/100551757-13d89e00-3283-11eb-8bfb-ea93bbade941.png)

**Comment by MakiWolf** [comment]
Maybe it would be great, when the app can delete all downloaded quests and newly can download them, before the app needs to be deleted and newly downloaded, to solve that.
