### ISSUE TITLE
Cycling infrastructure not enabled for Slovakia

### ISSUE THREAD

**Issue by nekromoff** [westnordost/StreetComplete#2340]
**How to Reproduce**

**Versions affected**
Latest

**Comment by westnordost** [comment]
It's not enabled because according to some research it's very unlikely to encounter any cycleways at all in Slovakia. We can change that given there is enough evidence that suggests otherwise.

**Comment by nekromoff** [comment]
Then enable it for Bratislava at least.

**Comment by westnordost** [comment]
It is only possible to enable it on a per-country basis

**Comment by westnordost** [comment]
So, as a Slovakian, would you say that it is reasonable to ask users in Slovakia for **all of Slovakia** whether each road has a cycleway or not?

**Comment by nekromoff** [comment]
No, if it's about *each* road, then it does not make sense (but that does
not make sense for general for most of the EU countries with exceptions of
the Netherlands and possibly Denmark). If it was improving already mapped
infra, then yes (same questions as for roads/ped crossings - e.g. surface,
quality, lights etc.).

BTW, Slovak works better than Slovakian.

**Comment by westnordost** [comment]
Not each road, only primary, primary_link, secondary, secondary_link, tertiary, tertiary_link, unclassified and residential with a speed above 30kmh, and also not unpaved roads.

**Comment by westnordost** [comment]
Looking at all roads in total, certainly also in Germany, only a very small fraction of roads will have any cyclways. That's still fine to ask though because there is a reasonable chance that the road may have a cycleway.
It just makes no sense to ask in countries where they don't exist at all or there are just a few "novelty" cycleways somewhere. There is a very rough rule of thumb in StreetComplete, that if the answer to a question is more than 99% the same, the question shouldn't be asked. But this is a soft rule of course, for example I guess more than 99% of all roads have an asphalt surface as well.

**Comment by nekromoff** [comment]
And yet, this is one of the most common tasks - a general question about
surface for a *road*.

Anyway, please close this issue, I just find it strange and would argue
that we exactly need more improvements in mapping cycling ifra in the
countries where such infra is generally lacking (but can be found in some
places that are possibly unmarked so far).
