### ISSUE TITLE
No undo functionality

### ISSUE THREAD

**Issue by nekromoff** [westnordost/StreetComplete#2341]
When entered something by mistake, there is no option to fix it by undoing. 

**How to Reproduce**

**Versions affected**

**Comment by westnordost** [comment]
Yes there is. Button on the lower left side.

**Comment by nekromoff** [comment]
The Undo text should be added for clear recognition.

**Comment by matkoniecz** [comment]
> The Undo text should be added for clear recognition.

In mobile interface there is not enough space to have visible text labels for all elements.

**Comment by nekromoff** [comment]
Well, that's possible, but also as a new user the arrow was not helpful for
me. #ux

**Comment by smichel17** [comment]
This used to be more obvious because the undo button was near the star count & manual upload button. We could move it somewhere in the top left again (I think I proposed this in the past, when it was first moved) and then hide it when the quest form is open. A little bit of an ugly solution, but I think it would get the job done.
