### ISSUE TITLE
Bus station quests ask for redundant properties for nodes with corresponding ways

### ISSUE THREAD

**Issue by ChemoCosmo** [westnordost/StreetComplete#2352]
The Quests for bus stop properties like _shelter_, _tactile_pavement_ or _bench_ apply to nodes that are tagged with _highway=bus_stops_ even when these nodes are part of a way that holds this properties already.

**How to Reproduce**

Street Complete asks for bench/shelter/pavement properties for bus stop nodes like [this](https://www.openstreetmap.org/node/1255610522#map=19/52.50175/13.45002&layers=N), even though these attributes have already been tagged on [the corresponding way](https://www.openstreetmap.org/way/383776475).

**Versions affected**

Android-Version 9
Street-Complete-Version 27.0

That being said: I love the new quests and how quickly the app progresses.

**Comment by ChemoCosmo** [comment]
Example of a still living quest:
![signal-2020-12-07-144815](https://user-images.githubusercontent.com/58092307/101358625-67f30c00-389b-11eb-81b1-e50403223c81.png)
at [this bus station](https://www.openstreetmap.org/way/398886932).

Unrelated: This way already has a tactive_payment property and is requested nevertheless.

**Comment by westnordost** [comment]
As far as I know, your example is actually a tagging mistake. It's mixing PTv1 and PTv2. `highway=bus_stop` should be on the same element as `public_transport=platform`, if at all.

**Comment by westnordost** [comment]
In any case, even if it was not a tagging mistake strictly speaking, there is no way for StreetComplete to find out that these two bus stops are actually the same bus stop. That's why I wrote that they should be the same element - because they are the same bus stop.

**Comment by ChemoCosmo** [comment]
Yes, that's what I thought.
But [couldn't convince other mappers.](https://www.openstreetmap.org/changeset/95336564)
Also at least all of Berlin seems to be tagged that way...

**Comment by westnordost** [comment]
I've looked at the wiki. The problem with `highway=bus_stop` is that the wiki page is changed all the time. I can not change implementation everytime when people fiddle around in the wiki and change the meaning of tags. The wiki now sounds like `highway=bus_stop` is basically the location of the bus stop pole. But that tag was never so specific. It didn't even distinguish between stop position and platform position. 
`highway=bus_stop` (etc) was not deprecated when PTv2 was created because the former is for "rough" mapping. It is/was recommended to still add `highway=bus_stop` to a PTv2 bus stop (platform) for backwards compatibility. It was never intended to be merged together in this way so that `highway=bus_stop` now fills a specific role in PTv2 (=the position of the pole)

So, I am not changing anything in the implementation here. I don't want to create a precedent that people might get the idea that changing the meaning of a tag is OK. It is not OK for exactly that reason - existing data consumers cannot be expected to change their interpretation of the tag.

**Comment by westnordost** [comment]
I've read the wiki again. It doesn't recommend the Berlin tagging specifically but also doesn't specifically discourage it or explain how `highway=bus_stop` (documented to be necessarily a node) should be tagged when the `public_transport=platform` is not mapped as a node but a way. 
So in this matter, the wiki didn't change that much over the last year and I overreacted in the last post.

However, it is still a will-not-fix, albeit for a slightly different reason: As `highway=bus_stop` is just for (backward) compatibility with data consumers that only interpret the PTv1 scheme, it is perfectly OK and correct to duplicate properties of a bus stop (shelter, garbage can, seating, ...) onto the OSM element that is tagged with `highway=bus_stop`.

**Comment by ChemoCosmo** [comment]
> he wiki now sounds like highway=bus_stop is basically the location of the bus stop pole.
As far as I can tell the node isn't even used this way in Berlin. It's just a random node at the way. At the examples I checked, the stop pole is not at the position of the node.

I agree with you that redundant properties are harmless here, because they don't change much and inconsistencies are unlikely.

**Comment by ChemoCosmo** [comment]
Apparently there is some movement in this regard.
Most likely this particular agging schema is going to be abandoned in Berlin. 👍
