### ISSUE TITLE
Some quests are always dots in map view

### ISSUE THREAD

**Issue by ludwigbald** [westnordost/StreetComplete#2359]
**How to Reproduce**

In a cluttered area, some quests are not shown as pins even when fully zoomed in, so they are also not editable.

Maybe either allow zooming in further, or just show them anyways.

**Versions affected**

Screenshot:
![Screenshot_20201209-005227.jpg](https://user-images.githubusercontent.com/34342715/101555373-d8437f80-39b8-11eb-97e6-0635fcc842f6.jpg)

**Comment by peternewman** [comment]
It's due to the priority @ludwigbald if you either answer the opening hours quest, or turn off that quest type in the settings it will show the less important quest on the other dot instead.

**Comment by matkoniecz** [comment]
>  just show them anyways

That would turn problem into "quest is displayed and not clickable", likely also clipping/overlap/flickering issues due to conflicting pins.

**Comment by westnordost** [comment]
Zooming in further is not possible.

Regarding that other suggestion, see @matkoniecz and @peternewman

**Comment by peternewman** [comment]
The only other thing @ludwigbald is that rotating the map can sometimes swap which quest is shown or show more/both, but probably not in your example as they're too close together even if they were similar priorities.

**Comment by georg-d** [comment]
I repeatedly run into the same issue, mostly because some quest can't be properly answered at the moment but maybe later (e.g. a parking lorry blocks the view, or at daytime I cannot reliably answer whether something is lit, or at night time some un-lit thing is not sufficiently good to perceive). One example at 47.9853848, 7.8308004, max zoom level

![quest shown as dot, but other quests shown as pins can't be answered at the moment](https://user-images.githubusercontent.com/45993293/123521270-ec7d6e80-d6b5-11eb-92b9-daac9d9b126e.png)

**The "solutions" suggested so far (here and in related issues) are IMHO not really viable**
* **Disabling all quest types that are shown as pins and "shrink" a quest to a dot,** then aswering that quest, then enabling all the disabled quest types again. Not satisfying from a UX point of view as it's a quite cumbersome procedure - hence, many users will prefer to simply not answer the "dot quest". Moreover, it greatly increases likeliness that some quest types stay disabled _in the long term_ just by coincidence - this is against the purpose of the app.
* **Rotating the map** means I need to open & change Android settings, try & error with some rotations whether the dot hopefully turns to a pin at some point in time, and finally change the Android settings back. From UX perspective not satisfying for "just" answering a quest.
* **For each quest shown as pin, hiding it** means they don't show up any more for me, i.e. if I could answer them later, I won't  - this is against the purpose of the app.
* **Add more zoom levels** so all quests show as pins and none as dots --> not possible due to tangram / map rendering engine, see https://github.com/streetcomplete/StreetComplete/issues/2878


**Potential solutions that are IMHO more user friendly and hopefully technically feasible:**
* **Using tangram's multiple tap picking to make not only pins but also dots accessible,** i.e. first tap opens "highest" pin and further taps cycle through "lower" dots, suggested in https://github.com/streetcomplete/StreetComplete/issues/2878
* **A long tap on a pin opens a dialog allowing to send that quest to lowest level/priority,** i.e. it turns from pin to dot and a nearby dot has sufficient room to become a pin. 
* While adding a "general purpose" list view is _won't fix_ because answering quests shall only happen when seeing the quest's context on a map (see  https://github.com/streetcomplete/StreetComplete/issues/142), what about a list view that is tailored to solve this issue and other _"too few details visible despite max zoom"_ issues? i.e. **only at max zoom, a long tap opens a list view of only the quests within current map range.** Because user can only open list view from the map _and_ the list only contains what the map showed, the user obvisouly saw the quests with their context. Because of max zoom, the quests are obviously extremely nearby so we can assume they are hiding/overlapping and/or the map display is not helping much (example below), thus the user needs an alternative to the map view and opens the list view. As examples when map display is not helping much, take the very short way fragments in complex crossings where the thick rendering and/or the very limited layer information/filtering makes it really hard to recognize what way fragment the quest is about: ![way framents - connections not recognizable 2 variations](https://user-images.githubusercontent.com/45993293/123521293-146cd200-d6b6-11eb-9307-f0d294842e1e.jpg)
* **Allow to hide a quest only for a short period of time,** e.g. 5 minutes. So besides existing 2 Buttons "Nein, verstecken" and "OK" we'd have a 3rd button "Für 5 min verstecken". ![hiding a quest with new option or button](https://user-images.githubusercontent.com/45993293/123521265-e4253380-d6b5-11eb-8a1f-6f5ff478d943.png)

**Comment by gojhub** [comment]
There is no need to change your android settings.
Just use the two-finger gestures to rotate and/or pan the map.


Am 26. Juni 2021 17:56:36 UTC schrieb Georg-D ***@***.***>:

**Comment by mnalis** [comment]
Note that rotating the map rarely helps (at least for me)... So I've been using `Can't say` / `No, just hide` and then remembering to periodically do `Settings` / `Restore hidden quests`.  Unfortunately, that disenfranchises  me from possibility to really hide quests that I can't answer (and leaving forever-open note "this can't be answered" is even worse solution).

The best and most intuitive way IMHO would be to try to get Tangrem-ES zoom issue https://github.com/tangrams/tangram-es/issues/2264 fixed - so interested parties should probably _at least_ go there and upvote that issue (currently I'm the only upvote there :disappointed: ). 

Maybe someone who develops for android can try to increase that hardcoded limit in their own copy of tangrem-es for StreetComplete and see if that crashes or of it works? If someone would build `.apk`, I'd be more than willing to try it out and report how it works for me IRL.

**Comment by westnordost** [comment]
- regarding lit quests, the root issue seems to be, that there are some quests that are not solvable (right now). So we should rather work on maing those solveable. And actually, there is already a PR for only showing lit quests during night.

> tangram's multiple tap picking

I think this is based on a misunderstanding. As far as I know, this feature does not exist in tangram-es. But in any case, even if it was not, I am not sure if it would work with features that are hidden / obscured?

> Allow to hide a quest only for a short period of time, e.g. 5 minutes

Well, you can now undo quest hidings too
