### ISSUE TITLE
Quest: tactile paving on crosswalks

### ISSUE THREAD

**Issue by PanierAvide** [westnordost/StreetComplete#238]
Less than 2% of crosswalks in OSM (`highway=crossing`) have an information about whether they have a [tactile paving](https://wiki.openstreetmap.org/wiki/Key:tactile_paving) (`tactile_paving=*`) or not (documented on [crossing=* wiki page](https://wiki.openstreetmap.org/wiki/Key:crossing)). This information is useful for blind people safety, as tactile pavings alerts them of an immediate danger. Tactile paving tag can have the following values:
- yes: this crosswalk is equipped
- no: this crosswalk isn't equipped
- contrasted: the crosswalk is equipped and the paving has an high contrast compared to the ground (white over dark asphalt)
- incorrect: crosswalk is equipped but the paving isn't legally appropriate (not at the correct distance for example)
- primitive: no proper paving but something else can be used (decoration).

As three last values needs a certain knowledge about tactile paving and law, the quest could only ask if the crosswalk has a tactile paving, with a yes/no answer.

**Comment by westnordost** [comment]
Love the idea.

It will be hard probably to find pictures that are representative. So far, I did not know that tactile pavings even existed (I thought these white riffles were just decoration or something, never thought about it). So, there are other users as well that need to see how "tactile paving" looks like to be able to give a proper answer.

I suggest an image selector that shows a list with an image on the left side and a short description right of it. (Because I think an image alone is not self-explanatory enough, but the image alone, see above, also not).
Otherwise it behaves the same as the normal image selector.

**Comment by PanierAvide** [comment]
If we only consider the yes/no answer, maybe the template can be that way:
-Title: "Is there any tactile paving at this crosswalk ?"
-Subtitle (to explain what it is): "A tactile paving is made to warn visually-impaired people of a danger"
-Photo (at left): a tactile paving at a crosswalk, potentially circled by red
-Buttons: yes/no
What do you think ?

**Comment by westnordost** [comment]
Yes/No answers are always a good idea, the easiest possible answer.

So, you disregard that there are other possible values for the tactile_paving key. This is good in my opinion, because the other values are somewhat more blurry and not answerable without training (what is incorrect tactile paving? how much contrast is 70% contrast? ). I perceive those as further refinements on "yes" that can be done later by other people.
The image should be in a size that the form doesn't need to be scrolled - i.e. it could cover the whole width (include several examples).

It makes sense to copy&paste this quest into 2 with just the Overpass query and the question being different: for public transport stops and for crosswalks.

**Comment by PanierAvide** [comment]
What do you think of these two pictures for crosswalks ?
https://wiki.openstreetmap.org/wiki/File:Tactile_paving.jpg
https://commons.wikimedia.org/wiki/File:Station_Saint-Aubin_de_l%27Express_91-06_%C3%A0_Saint-Aubin_en_Essonne_le_21_mai_2017_-_3.jpg

Makes sense to do a quest also for public transport. Pictures for this quest:
https://commons.wikimedia.org/wiki/File:ADL_807_at_Onehunga.JPG
http://www.geograph.org.uk/photo/4258938

**Comment by westnordost** [comment]
The tactile paving tiles must be the main POI in the picture, not the whole crosswalk or the whole station. It should show the user how such a tiles look, not (necessarily) how a whole crossing/station looks.
Ideally, it shows both the "bumps" (attention zone) and the "stripes" (go this way).

I only find the first picture good, though I have to say, in Germany, they look different. I.e.
![dsc_0108](https://cloud.githubusercontent.com/assets/4661658/26562375/145309dc-44c6-11e7-9fc0-3ea390983750.JPG)
(That photo is not so good though because the contrast is so low)

**Comment by PanierAvide** [comment]
It's not easy to find good tactile paving pictures with a free-license. I think I will take some near crosswalks today. I think there are no bus stops in my city with tactile paving, I will ask some people doing some accessibility mapping if they have such pictures.

**Comment by PanierAvide** [comment]
Jean-Louis Zimmermann, a great accessibility mapper, has a whole directory of pictures on Flickr (CC-By license) : https://www.flickr.com/photos/jeanlouis_zimmermann/sets/72157635218804514/with/5520460024/
He also pointed out that there are more on Flickr (but with mixed licenses) : https://www.flickr.com/search/?text=bande%20podotactile

**Comment by westnordost** [comment]
Good

**Comment by PanierAvide** [comment]
Do you think this montage can do the job for both quests ? Three different pavings, at the center of the picture.
![Tactile pavings](https://framapic.org/uqDWypConCPx/YieTBeuTFWIj.jpg)

**Comment by westnordost** [comment]
I'm viewing this right now on a smartphone, looks good except for the center pic. For that, it is not obvious that the tiles are corrugated, they just look like high contrast markings. Perhaps zoom in a bit?

Am 6. Juni 2017 13:45:49 MESZ schrieb Adrien Pavie <notifications@github.com>:
>Do you think this montage can do the job for both quests ? Three
>different pavings, at the center of the picture.
>![Tactile pavings](https://framapic.org/uqDWypConCPx/YieTBeuTFWIj.jpg)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/238#issuecomment-306461754

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment]
Thanks for merging this pull request ;-)

**Comment by matkoniecz** [comment]
See https://github.com/streetcomplete/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete

If this would qualify the best way to propose is to open a new issue via https://github.com/streetcomplete/StreetComplete/issues/new/choose
