### ISSUE TITLE
Roof shape for industrial buildings 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#240]
Perhaps even garages.

**Comment by westnordost** [comment]
I let them out deliberately because users might have problems to determine that.

You probably think of [simple warehouses](https://www.bing.com/maps?osid=06680801-fecd-4574-8b4c-8b87da49386f&cp=sxpn3mhv4cm7&lvl=17&style=o&v=2&sV=2&form=S00027),[ but what about these buildings](https://www.bing.com/maps?osid=f20ce9ca-2e57-4991-a922-82b6d90e0b66&cp=sxkvyhhv2pqh&lvl=17&style=o&v=2&sV=2&form=S00027)?

**Comment by matkoniecz** [comment]
> but what about these buildings?

In most case it seems not problematic (from aerial image, no idea whatever it would surveyable on the ground).

**Comment by matkoniecz** [comment]
The tricky buildings are ones that I would expect to require splitting before edits or would require building:area as there is no consistent roof type - but it happens also for residential buildings.

**Comment by westnordost** [comment]
Ok

**Comment by westnordost** [comment]
Ah now I remember why this is not implemented: Because StreetComplete does not ask for levels of industrial buildings (and thus roof levels). (Rightfully so, IMO)
Actually, if you define roof levels for industrial buildings, then StreetComplete will also ask for the roof shape.

**Comment by HolgerJeromin** [comment]
Hm. This is than related to (closed) #277
