### ISSUE TITLE
Quests for opening hours do not distinguish an ATM from a bank

### ISSUE THREAD

**Issue by sarimak** [westnordost/StreetComplete#246]
Quest titled What are the opening hours of "name of the bank owning the ATM"? is misleading.
1) ATM opening hours are most likely 24x7
2) how the user will know that this is not OSM data bug (wrong amenity type)

See http://www.openstreetmap.org/note/982228 for an example of confusion it causes.

**Comment by westnordost** [comment]
There is no distinction at all between different types of objects. Is Česká Spořitelna the name of that particular ATM? If it is, this should not be an issue. If it isn't, but Česká Spořitelna is just the operator, then I'd say it is correct that (you) created a note because apparently it was a mistake to tag it with name=Česká Spořitelna.

**Comment by sarimak** [comment]
"Česká Spořitelna" is a name of bank which owns the ATM (http://www.csas.cz member of Erste Group). OSM web editor shows "name = Česká Spořitelna", owner is not set, currencies are not set, opening hours are not set. However, the amenity is correctly set to "atm".

**Comment by westnordost** [comment]
Okay. My point is, that the app is not in error here. A thing has a name, so it displays the name of the thing when it references it. That is what names are for. Česká Spořitelna is the operator, not the name of that particular ATM.

**Comment by westnordost** [comment]
Notes now mention the context in which they were created (i.e. "What are the opening hours of Česká Spořitelna").

**Comment by HolgerJeromin** [comment]
BTW I know many atm which are not 24/7. Probably because the room should not be used by some homeless people .
