### ISSUE TITLE
note vs. note and fixme

### ISSUE THREAD

**Issue by it4workflow** [westnordost/StreetComplete#248]
https://forum.openstreetmap.org/viewtopic.php?pid=646547#p646547

**Comment by westnordost** [comment]
Why note and fixme?

**Comment by it4workflow** [comment]
well, [note](https://wiki.openstreetmap.org/wiki/Key:note) (...or hints for further improvement.) and [fixme](https://wiki.openstreetmap.org/wiki/Key:fixme) (to mark objects and places that need further attention.)

and as of [notes](https://wiki.openstreetmap.org/wiki/Notes):
> Don't create automated notes. Notes should be a human-to-human communication. Also avoid noting lots of data bugs which are already reported by automated Quality Assurance tools.

**Comment by westnordost** [comment]
StreetComplete does not create automated notes.

**Comment by matkoniecz** [comment]
@it4workflow it is still completely unclear what is reported here

**Comment by it4workflow** [comment]
imo, the app should use note (key) or fixme (key) instead of notes (on osm.org)

**Comment by matkoniecz** [comment]
Why?

**Comment by CloCkWeRX** [comment]
> imo, the app should use note (key) or fixme (key) instead of notes (on osm.org)
Strongly disagree.

An example workflow that actually worked out well the other day: I subscribe to all new notes via RSS in my city. Other mappers used street complete to capture opening hours, and indicated that some places were actually now vacant. We were able to collaborate and discuss; and got a better quality mapping outcome overall.

The alternative with a fixme tag would be having to use vespucci; keepright or similar to discover further mapping and it does not allow any kind of discussion about the best way to map something; apart from on the changeset.

These notes are based on users doing survey and finding they cannot describe what they want; with ways to discuss further with them. That's a far cry from "automated notes" (ie: I analyse a bunch of car trips; and create a note with likely max speed as an anonymous user)

**Comment by westnordost** [comment]
Just to add to the arguments for OSM notes (instead of fixme-tags):

- fixme descriptions must be very short - they are limited to 255 characters
- no discussion is possible, but it may be necessary if it is unclear what the person who wrote the note meant
- StreetComplete created notes are answers to specific questions. They don't need to be "This X does not exist anymore" but something much less concrete (that needs discussion). Fixmes on the other hand are mainly for instructions (i.e. "resurvey", "recheck xyz").

The OP did also not report back, so I am closing this.
