### ISSUE TITLE
Map not loading on zoom

### ISSUE THREAD

**Issue by Peremptor** [westnordost/StreetComplete#250]
Last time I opened the app, everything was fine. I have been very busy this week, so I don't know if there was an update...

Today, when I am scrolling or zooming, the map vanishes. It's really hard to answer a question when you don't know exactly, where on the street you are.

Honor 5x, Android 6, cache for maps on max 250 MB.

**Comment by zxmon21** [comment]
I confirm this. Samsung galaxy 16th, android 6.0.1

I have tried emptying the cache, but it still happens

**Comment by Sora1248** [comment]
I noticed this problem today, too. It looks like cached tiles are shown but no new tiles are loaded.

Here's a little brain dump:
- At home I downloaded the quests and looked around the map and noticed that tiles are missing in areas that I haven't visited with StreetComplete before. My Smartphone was connected with my Wifi.
- When I reached such an area the tiles were still missing (mobile internet connection)
- I once saw a tile that looked like it was for another zoom level as it was much coarser. After solving a nearby quest (zooming in & out) this tile was gone and replaced by empty space. Changing the zoom couldn't make it visible again.
- I updated the app from 0.8 to 0.10 some days ago. Today was the first time I used the app since then. I haven't noticed the problem in 0.8.
- Just as I made a quick test as I write this some missing tiles were downloaded but it stopped right away.
- According to netstat the app is collecting open TCP connections when the tiles aren't loaded (see below)

Here's a screenshot:
![screenshot_2017-05-21-16-03-01](https://cloud.githubusercontent.com/assets/19750809/26285177/f31a2376-3e4a-11e7-8c1a-387826a7fe54.png)
([Location in OSM](http://www.openstreetmap.org/#map=18/52.14814/8.56363&layers=N))  
This was also the place with the coarse tile: The roundabout was reduced to four straight lines.

netstat after moving the map around in an uncached area:
```
Proto Recv-Q Send-Q Local Address          Foreign Address        State
*snip*
tcp6       0      0 ::ffff:192.168.##.##:34109 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:51696 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:54245 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:39171 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:33323 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:33203 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:51640 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:39326 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:40413 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:37223 ::ffff:151.101.113.95:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.##.##:46011 ::ffff:151.101.113.95:443 ESTABLISHED
*snip 35 similar lines*
root@FP2:/ # 
```
(151.101.113.95 is the IP of tile.mapzen.com)

This grew over time as I tried to download more tiles.

From sniffing at the traffic I can say that Mapzen gives a reply with constant size (711 Bytes). I don't know the content as it is encrypted but this looks like some kind of error reply to me. To many connections? To many requests using this API-Key? I don't know.

Hardware & Software: Fairphone 2, Fairphone Open 17.04.0 (Android 5.1), StreetComplete 0.10. Haven't changed anything about the cache myself (it's set to 50MB).

**Comment by HolgerJeromin** [comment]
Often I get low zoom tiles, but not high zoom tiles. :-(

**Comment by westnordost** [comment]
There were several issues with the map tiles in 0.10:
- some devices/Android versions had problems with querying the map tiles via HTTPS. Now the app queries the tiles in HTTP again.
- the tiles were retrieved in a non-binary format, which required more data to be transferred -> now uses binary format again
- Mapzen might have (had) some problems delivering the tiles to so many users because they are reorganizing their infrastructure, I heard.

Please try out 0.11, there should be less problems with that.

**Comment by westnordost** [comment]
(Also, this bug is a duplicate)

**Comment by HolgerJeromin** [comment]
Works fine now. Tagging surfaces again with full speed. Hurray

**Comment by westnordost** [comment]
:-)
