### ISSUE TITLE
Highway = road refinement 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#252]
highway=road is used for unknown classification for example while tracing from airial images. 
So a quest defining the real type would be very helpful.

**Comment by westnordost** [comment]
How would you be in a better position to declare what kind of road a road of undefined type would be if you are on site? The app should not ask the user questions he will likely not be able to answer.

I argue that roads tagged as highway=road will likely not be residential roads as these will be visible from satellite (because of houses and the relatively small size of road) but instead be some unknown road leading through the countryside, where the mapper was unsure if it should be unclassified, tertiary, secondary or primary.
Would you be able to tell better if something is a primary, secondary or tertiary if you are there? I doubt it, because the classification is apparent usually only in context of the big picture and _not_ only by the size of it:
- what are the arterial roads leading into and out of a city?
- does the road connect bigger settlements / how big are the settlements it connects?
This is information you do not have on site, but it is essential to determining the classification.

I think this quest is nothing for this app. 

**However**, what this app _can_ ask is information that would help other mappers to finally determine the road type, such as the number of lanes.

**Comment by HolgerJeromin** [comment]
Who is allowed to use the road? Vehicles, bicycle, only foot. This is sometimes not decidable from airial, but when you are on site. 

Perhaps the "path" was no path at all but a dry riverbed.

**Comment by westnordost** [comment]
You mean to ask this question as a quest? For any road, or just for highway=road?

And, what to do with the answer? Always create a note with that answer, or add some tag to that road?

**Comment by HolgerJeromin** [comment]
This specific question should be asked with highway road only. 
If the answers are specific enough we could retag the way. 
But the questions have to be carefully asked. 
What is allowed here? 
Foot only: footway 
Bicycle only: cycleway 
Bicycle and foot: footway + bicycle =yes
Also cars: perhaps only create an osm note,because it is difficult to tag it right

**Comment by westnordost** [comment]
But do you think that all those "highway=road" out there are really at a considerable percentage actually not roads at all (but paths)? I kind of doubt that as well.
Also, the note would then contain i.e. the following text: "This highway=road is a road." - not _that_ helpful ;-P

**Comment by HolgerJeromin** [comment]
"You are allowed to use this road by foot, with bicycle and all double tracked vehicles." 
"You are allowed to use this road not by foot, but with bicycle and cars but not trucks "

this is helpful

**Comment by matkoniecz** [comment]
Some real examples (http://overpass-turbo.eu/s/pKZ)

- https://www.openstreetmap.org/way/302316855 - due to recent changes here aerial image is outdated and it is not 100% clear is it footway or service road
- https://www.openstreetmap.org/way/426415035 - aerial image is not helpingm it is blocked by trees or invisible
- https://www.openstreetmap.org/way/298388693from aerial it is not clear is it road or footway

5 other were fixable from aerial images.

Main problem is that there is no good way to setup questions to ensure good answer - it may be track, footway, one of several road types, road that should be mapped with private access, river, pipeline...

Maybe it would be useful for some people using this app to get "highway=road, this place needs an edit in Vespucci"? I made "show fixme=*" for myself (https://github.com/matkoniecz/StreetComplete/tree/fork/app/src/main/java/de/westnordost/streetcomplete/quests/show_fixme), but I am not sure whatever you are interested in adding quests like this (obviously it would require quest filtering as such quests would need to start disabled and appear with good explanation or remain otp-in only).

**Comment by westnordost** [comment]
So I think this is not really eligible as a quest.
