### ISSUE TITLE
Allow setting off on opening hours

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#276]
I explicit tag all off days to be absolutely clear. 
This is not really needed with Sunday, but with public holidays it is needed. 
Mo-Sa 09:00-19:00;Su, PH off

**Comment by westnordost** [comment]
The opening hours form needs to stay as simple as possible. It is complex enough already.

**Comment by HolgerJeromin** [comment]
The time input could get an third tab labeled "Off" which disables the first zwo

**Comment by westnordost** [comment]
Yeah, no. The opening hours form is complex enough as it is already.
The normal case is that a shop is closed during public holidays. If the shop is explicitly open on holidays, the user can specify that already.

**Comment by HolgerJeromin** [comment]
No. 
Many/most bakeries are open on Sunday and holidays. 
But in Verl there is a bakery which is open on Sunday and not on holidays. 
I can not tag  the difference between "holiday opening unknown" (or a user don't know that this is important) and "shop is closed on holidays"

**Comment by westnordost** [comment]
>Many/most bakeries are open on Sunday and holidays.
>But in Verl there is a bakery which is open on Sunday and not on holidays.
You can tag this in StreetComplete

**Comment by HolgerJeromin** [comment]
I can not tag 

Tu-Fr  06:00-13:00; Sa 06:00-13:00; Su 08:00-12:00;Mo,PH off

**Comment by westnordost** [comment]
Correct

Am 4. Juni 2017 00:00:05 MESZ schrieb Holger Jeromin <notifications@github.com>:
>I can not tag 
>
>Tu-Fr  06:00-13:00; Sa 06:00-13:00; Su 08:00-12:00;Mo,PH off
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/276#issuecomment-306003979

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
What you can tag is

Tu-Fr 06:00-13:00; Sa 06:00-13:00; Su,PH 08:00-12:00

**Comment by HolgerJeromin** [comment]
Which would be wrong. 
I am confused :)

**Comment by ypid** [comment]
> The normal case is that a shop is closed during public holidays.

How is this case handled by StreetComplete? "PH off" must be explicitly specified. This is not the default for opening_hours (there has been a proposal about this). This is quite common.

**Comment by westnordost** [comment]
Can you give a link to the specification where it says that leaving PH away means that PH is not specified? Usually, if you leave something out, it means that it is not open during that time so that is why I wonder. If the specification says otherwise, this may be a valid request.

**Comment by ypid** [comment]
> Usually, if you leave something out, it means that it is not open during that time so that is why I wonder.

Consider this value `Mo-Fr 08:00-16:00`. "PH" is not specified and the oh values does exactly what it says, not more and not less.

See: https://wiki.openstreetmap.org/wiki/Proposed_features/opening_hours_default_PH_off

**Comment by rugk** [comment]
Also the [opening hours evaluation tool](https://openingh.ypid.de/evaluation_tool/) complains when PH is not added:
> There was no PH (public holiday) specified. This is not very explicit. Unfortunately the tag key (e.g. "opening_hours", or "lit") is unknown to opening_hours.js. This warning only applies to the key opening_hours. If your value is for that key than read on. If not you can ignore the following. Please either append a "PH off" rule if the amenity is closed on all public holidays or use something like "Sa,Su,PH 12:00-16:00" to say that on Saturdays, Sundays and on public holidays the amenity is open 12:00-16:00. If the amenity is open everyday including public holidays then you can make this explicit by writing "Mo-Su,PH". If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.

**Comment by westnordost** [comment]
Virtually no opening hours sign says anything about opening hours on public holidays. Why? Because it is seen as self-evident that they are of course closed on public holidays _unless explicitly stated otherwise_. 

This means, that virtually no surveyor* would even get the idea to explicitly specify that it is indeed closed on public holidays. The surveyors can only be expected to transfer the data that is on the sign.

If the `opening_hours` specification is really to be understood that `PH off` must be explicitly stated, then I must say, it is simply at cross-purposes with the real world. As I said, in the real world, that shops are closed on public holidays is so self-evident shops usually do not mention it and/or is subject to country-specific legislation.

I find it otherworldly that I even have to make this point. A specification must work with the real world because it can surely not be expected that the real world will adapt to a specification.

* outside the sphere of people who concerned themselves with the OSM opening hours specification scheme

**Comment by rugk** [comment]
Maybe it is really different per country?

In any case I like the last sentences about the message in the tool there:
> If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.

So, well…, just ignore? If there is a special PH value, then users might want to add this via the comment section.

The bakeries example is, however, strange. Should also use comments there?

**Comment by ypid** [comment]
> Maybe it is really different per country?

Gotcha :)

> Virtually no opening hours sign says anything about opening hours on public holidays. Why?

This has already been discussed on the public mailing list (ref: http://thread.gmane.org/gmane.comp.gis.openstreetmap.tagging/24247) and the consensus was reached that PH (and SH) are explicit.

See also: https://wiki.openstreetmap.org/wiki/Proposed_features/opening_hours_default_PH_off

> I must say, it is simply at cross-purposes with the real world.

I know, in OSM we map what we see. But at the end of the day we want to do something useful with this data. Getting PH (not to mention SH) definitions is difficult enough. Figuring out what types of amenities are closed by default on PH for every country is impractical.

**Comment by westnordost** [comment]
Of course it is different for each country. Data consumers can simply find out in which country an element is and apply the country's default. The metadata to find out what amenities are closed on PH are a work that has to be _done_ once and then this intelligence can be applied worldwide.

My argument that surveyors will not even consider adding an explicit `PH off` still is valid. As it stands, StreetComplete _could_ gather the aforementioned intelligence itself and then automatically add `PH off` as the default for those amenity+country combinations where this is the case.
But I will not do this, because it does not belong into a data producer application, for the same reason as stated [here](https://github.com/westnordost/StreetComplete/issues/353#issuecomment-312218116).

**Comment by ypid** [comment]
> The metadata to find out what amenities are closed on PH are a work that has to be done `once` and then this intelligence can be applied worldwide.

`Once` for every combination of country/region and type of object. In theory you are right and I can see your point. I just think this will be very difficult and probably also every error prone in practice as has been discussed. This part of reality can not be covered by a couple of rules because reality is not necessarily rule based either. But I have not problem with being disabused if somebody comes up with a working solution and a proposal for how opening_hours could move to it :-)

**Comment by rugk** [comment]
Okay, great, but let's not start a discussion about OSM or this special tag. As it stands, it obviously has been discussed before and StreetComplete is just a client-side application, which cannot change these rules anyway…

So to get back to this issue: What was it about actually? Adding "PH settings" or so as an option…
It seems it has been decided not to do so, as it's not simple and comments can be used.
So I think this issue can be closed, as nothing needs to be discussed here anymore. Further discussion leads to no new results here and might be directed to appropriate places (I appreciate a link).

**Comment by westnordost** [comment]
Yeah, ok.

**Comment by xuiqzy** [comment]
Maybe StreetComplete could be explicit in not recording PH opening hours and adding a PH with a comment  in the meaning of "unknown" or "not specifically known to be open, probably regional default"? (as it would be open on PH according to the specification)
This way the most detailed information would be recorded/available, if the way things are tagged or evaluated changes in the future, for QA tools, etc.

**Comment by HolgerJeromin** [comment]
> PH with a comment in the meaning of "unknown" 

This will/should be done by a data consumer.

> This way the most detailed information would be recorded/available, if the way things are tagged or evaluated changes in the future, for QA tools, etc.

qa tools are able to detect missing PH definition right now

**Comment by xuiqzy** [comment]
Some data consumers might assume that something is open on PH, because that is the case if nothing else is specified, according to the specification! I'm sure there are opening_hours where it's correct that they are open on PH but it's not explicitly stated.
By marking it as unknown, it would be clear that the opening on PH is not known rather than known to be open, so qa tools can concentrate efforts on places where it can be sure it is unknown rather than not so pretty/explicit, but correct tagging.

**Comment by HolgerJeromin** [comment]
> Some data consumers might assume that something is open on PH,
> because that is the case if nothing else is specified, according to the specification! 

Nope. There was a [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/opening_hours_default_PH_off) to define a default but it was rejected as a default can not be assumed in all parts of the world.

**Comment by xuiqzy** [comment]
I don't know if we're understanding each other correctly...
The proposal proposes a default off, because currently the specification makes no difference for PH if it is not specified, meaning open on PH the same as on other days, only depending on the day.
In the proposal it says: "Definition: | Changes the opening_hours=* syntax from explicit PH off to implicit PH off." That is because currently PH off has to be specified explicitly, otherwise it means: if it is a PH or not doesn't make a difference for the opening status.
If I misunderstood the specification, could you tell me where it says it is unknown for all holidays not specified, as that's what I think you're suggesting?
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

**Comment by goldfndr** [comment]
The complication with having PH default to off is trying to turn it back on again.

Let's take the example of New Year's Day, which is going to be on a different day from year to year. If a retail establishment doesn't observe the holiday but has different opening hours on weekdays (e.g. Mo-Fr 08:00-19:00) vs weekends (e.g. Sa 09:00-18:00; Su 10:00-17:00), how would that be encoded?
