### ISSUE TITLE
add quest to make surface=paved/unpaved more detailed

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#279]
Currently surface quest for detailed surface info, but there is no quest to make general surface values more clear.

And there is significant difference between surface=cobblestone and surface=asphalt, surface=grass_paver or surface=compacted (especially for cases like people on wheelchairs or cyclists).

I propose to add similar quests, asked for surface=paved and surface=unpaved and asking to make these data more detailed - it will allow both to make existing data more detailed and stop discouraging answering general answer.

For example I just cycled several streets, all paved. I would solve these quests as I am now waiting in queue - but as I am not remembering which part was surface=paving_stones and answering surface=paved would hide theses quests I decided to not do anything.

----

query: exclude ways with `cycleway:surface`, `surface:cycleway`, `footway:surface`, `surface:footway`, `segregated=yes`

**Comment by CloCkWeRX** [comment]
Maybe a quest for https://wiki.openstreetmap.org/wiki/Key:smoothness on surface=unpaved might better target the "how well can I travel on this with a bike/wheelchair/etc"

**Comment by matkoniecz** [comment]
> quest for https://wiki.openstreetmap.org/wiki/Key:smoothness on surface=unpaved might better target

smoothness is useful (for example - horrible asphalt) but in general it is very subjective. On the other hand difference between surface=grass_paver and surface=compacted is clear unambiguous and useful.

**Comment by matkoniecz** [comment]
smoothness key is tricky and a separate issue so any discussion should happen in a separate issu/ticket/feature request.

**Comment by matkoniecz** [comment]
Response to @westnordost in #322 (here, as it is relevant to this proposal)
  
> But what to do in the case the user can (rightfully) really not say what kind of public building it is? (ie its some weird mixture?) This is the same reason why surface=unpaved etc exists.

I never encountered case where it was impossible to use something more detailed that surface=unpaved. Sometimes road splitting was necessary and some generalization may be necessary, but so far I never encountered situation where it is impossible.

for example for http://www.openstreetmap.org/way/297445670#map=18/49.41306/21.98244 I ended using surface=compacted though I was tempted to use something like surface=asphalt;earth;sand;gravel;grass or surface=very_old_asphalt_mostly_completely_crushed_with_grass_and_earth_peaking_through_with_some_potholes_filled_with_earth.

**Comment by westnordost** [comment]
I do not agree.

The case you mention is **exactly** the case I have in mind when I think about when surface=paved (or unpaved, ground) is the right thing to choose. If it is very old crumbling asphalt, compacted is also wrong because it is simply not a compacted road. It may not be asphalt anymore either, so this is where the "generic" categories come in. It is easier to say "well it is more or less not paved generally" than "well it is more or less a gravel road".

I see the point of this quest: There are many many tags with surface=paved of which most will probably be asphalt etc., so it is good to offer users to answer it in more detail.
But how to do this? There are simply _also_ those cases where the surface cannot be determined any more detailed. Those that have been added in the past and those that are added even now with StreetComplete.

**Apart from the "asking again once" part of this, which is just a nuisance, the bigger issue here is that it should be a valid answer to say "yes, it cannot be determined in more detail than simply 'paved'" and this answer should be persistent, as in that StreetComplete does not ask the next guy the same question. See https://github.com/westnordost/StreetComplete/issues/322#issuecomment-308395719 .** 

There are different ways to do that, my suggestion is to require the user to add a short comment that should describe the surface of the road and add this comment in **surface:note**. The "detail surface quest" is then not shown for any roads that have this tag.

**Comment by matkoniecz** [comment]
Note that in this case generic surface=paved would not be correct. It was not merely "very old asphalt with cracks". The asphalt was so degraded that it was not even obvious that road used to be asphalt road in the past. It was closer to surface=unpaved than surface=paved.

Asphalt was completely crushed (except very small patches), mixed with gravel substructure and sand/gravel/earth.

I am pretty convinced that it was fitting 

> A mixture of larger (e.g., gravel) and smaller (e.g., sand) parts, compacted (e.g., with a roller), so the surface is more stable than loose gravel.

definition.

**Comment by matkoniecz** [comment]
> There are different ways to do that, my suggestion is to require the user to add a short comment that should describe the surface of the road and add this comment in surface:note. The "detail surface quest" is then not shown for any roads that have this tag.

That would be a good solution.

**Comment by areynoua** [comment]
For my use of the app, I would like to be able to activate and deactivate a "surface" quest for roads labeled with a general value (paved, unpaved, earth...). It should be a quest disabled by default, but that you could activate when you know it's useful (a quick look at overpassturbo shows me that it would be convenient around my house).

**Comment by matkoniecz** [comment]
One more question-before-implementation to @westnordost : would it be OK to ask about all kinds of `surface=paved/unpaved`? With roads, paths and all other objects within one quest?
 
Or would it be required to limit it to the same features as road quest and path quest and keep it split into two quests?

Or limit it to highway=* but have questions for roads and paths, footways, cycleways in one quest without splitting it into two quests? I think this one is my favorite.

------

@areynoua

> earth

This is not a general value, it is a synonym of `surface=dirt`

**Comment by westnordost** [comment]
No, it should be two quests because the user might want to select only the category of quests that he is interested in. Perhaps he is only interested in streets. I'd say the information on roads is also more important than on paths and often easier to answer.

**Comment by xuiqzy** [comment]
It would also be nice to keep the information that the surface cannot be determined in more detail machine-readable as all the `note:*=*` keys are not and should not be machine readable by design.

Something roughly like `surface:detail_available=no` in addition to the actual description of the situation in the `surface:note` key would achieve that in a similar fashion to the machine readable `opening_hours:signed=no` for example.
