### ISSUE TITLE
Align building level quest to tagging 

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#280]
The quest asks for full building levels including roof levels. 
I am tagging building details since years, but after using this app a lot I got confused if the osm tag building:levels includes roof or not.

**Comment by matkoniecz** [comment]
> building:levels

From my understanding of quest picture - building:levels count roof if there is an attic there. It is quite obvious for flat roofs and for buildings with windows in the roofs, but is not really clear in many cases (is there attic level, nearly nonaccessible area below roof or is the final level higher?)

But anyway building:levels is used solely for 3D rendering so its value is quite low and accuracy not critical.

**Comment by HolgerJeromin** [comment]
@matkoniecz 
The app tags 
`building:levels=<answer building level>` minus `<answer roof levels>`
`roof:levels=<answer roof levels>`

So **data wise** everything is correct, but you **train the brains** of the mappers to a wrong tagging schema.

**Comment by matkoniecz** [comment]
Yeah, now I see the problem (http://wiki.openstreetmap.org/wiki/Key:building:levels).

PR would be quite simple, just modify explanation picture and remove substraction.

It would help that use also other editors and hurt current StreeComplete users, but overall I think that it should be done.

**Comment by westnordost** [comment]
Then I'd make the quest into two:
AddBuildingLevels
AddRoofLevels

**Comment by HolgerJeromin** [comment]
Thanks.

**Comment by matkoniecz** [comment]
Why split quest in two? It would add more clicking for little benefit.

**Comment by jancborchardt** [comment]
Yeah, UX-wise splitting them would be an extra step and lead to confusion again ("do I count the roof level?").

The image simply needs to be adjusted, top field having the roof levels, bottom the others.

**Comment by HolgerJeromin** [comment]
Perhaps after an update we need an warning dialog, that the quest has changed. Not for new users only for users who has used the app before the update.

**Comment by rugk** [comment]
This is an interesting issue. Because the app's behaviour has changed to make the behaviour more intuitive for non-mappers, people not/rarely knowing OSM, it is now confusing for the pro-mappers, the ones mapping in OSM for years. Oh, that's a bad trade-off…

Initially, I, as a relatively new mapper, was also confused (https://github.com/westnordost/StreetComplete/issues/66), so the [image has been added](https://github.com/westnordost/StreetComplete/issues/41#issuecomment-292731285). I think the image is very clear, logical and easy for beginners. That's how it is supposed to be…

That it uses a different logic than what all other mappers have done for years is somehow problematic now. And indeed, if you consider that this app may/should also attract new mappers/OSM users, then it is not good…

So a new image is really a good idea to solve this. Still funny, how confusing such a simple quest can be… (for multiple parties)

**Comment by westnordost** [comment]
I don't mind if this is changed. But I reserve the right for myself to still split up the quest into two later on.

**Comment by rugk** [comment]
Later,… if there are good arguments for it. When this quest is changed again after someone else opens an issue… :wink: 
Currently I like that it is in one picture.

**Comment by grrgui** [comment]
Useful enhancement, it will clear after that.
I like also it in one picture.

**Comment by HolgerJeromin** [comment]
Thanks a lot.
