### ISSUE TITLE
Can't add address-range house numbers

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#295]
Similar to #266 and #281

For commercial buildings, or apartment blocks; addresses are sometimes a range. Some systems model this as 'street number low', 'street number high'; or its noted as "11-31 Example Street".

For some of these buildings, they are better split into a terraced model (densely packed standalone apartments); but others really are just one big address.

Right now, the housenumber quest input doesn't allow "-" input; so you have to fall back to an osm note - ie http://www.openstreetmap.org/note/1017460

**Comment by westnordost** [comment]
It does, just press the ABC button to get the normal keyboard.

**Comment by CloCkWeRX** [comment]
Could have sworn it refused the input the other day when mapping; despite showing the keyboard, but yes I agree it works now.

**Comment by westnordost** [comment]
There is a "-" in the number input, you probably pressed this. This is pretty much an Android issue. I am telling the system "now only input numbers!" and Android shows a keyboard with numbers and minus, comma and dot of which the non-numbers obviously do not work because the input only accepts numbers.
