### ISSUE TITLE
Flush quest cache button

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#300]
Often when I use this, its because I made edits to my hometown where I don't remember all the details offhand. This becomes a problem because I have to wait more than a day before it becomes available on this app.

As an example, I would reasonably remember the name of a restaurant to add, but its unlikely that I would remember the hours without writing it down, so its more convenient to use StreetComplete the next time I'm near there.

There are two solutions I would propose.

1. A much shorter option for the quest cache. Since you have it go from a week to a day, it would make sense to go from a day to an hour.

2. Give a "flush cache" button to push for these sorts of situations

**Comment by rugk** [comment]
Sorry, but I don't like understand your example. So you go to this restaurant, answer the quest. ro no… ah… so the restaurant is not mapped and also not included in StreetComplete?
In this case, I would just create a note on the map (probably with another app) adding all details there, maybe take a photo, maybe with Mapillary, so it is automatically geotagged and uploaded and can be used to verify the information by anyone.

So in any case you add the restaurant and now your problem is that the cache only expires after 24h and quests for this restaurant only appear afterwards, right?
Then I just don't understand one thing: You have to add the restaurant with another app or the OSM web editor (iD) anyway. There you can also just add all potential quests, which may later appear? (e.g. opening hours)

Additionally a similar button as "flush cache" is already available: Just tap on "Look for quests here". This should update all quests. What would be the difference/advantage to/of a "flush cache" button?

**Comment by westnordost** [comment]
> Additionally a similar button as "flush cache" is already available: Just tap on "Look for quests here". This should update all quests. What would be the difference/advantage to/of a "flush cache" button?

By the way, this does not work. The "look for quests here" button respects the "quest cache" delay.

I mentioned earlier that it would be okay for me to have a flush cache button in an "advanced" section of the settings dialog. For me however, this has no priority and thus should be done by somebody who cares about it.

**Comment by gappleto97** [comment]
The example is poorly worded, sorry.

The idea is that I might map something without remembering its hours of operation. When I then go to that store, it would be nice if I didn't need to wait a full day to fill them in.

**Comment by rugk** [comment]
> should be done by somebody who cares about it.

So tag this issue with "help wanted", maybe?
But at least you should fix that button; why am I hitting it constantly if it does not work? :smile:
(Or, at least, remove that button…)

**Comment by westnordost** [comment]
Anything that is tagged with anything is help wanted.

**Comment by rugk** [comment]
Ah, eh, really? Interesting policy you have there. (So untagged issues are ones you do yourself?) You maybe should just mention it somewhere, so contributors know this…

Usually the "help wanted" tag can be used in the search of GitHub and you can thus point potential contributors to issues they could be working at.

**Comment by westnordost** [comment]
Untagged issues are usually issues I am not convinced they should be done.

Hmm ok. I will look through the issue tracker and tag things that I do not plan to implement myself but others are invited to do so some time.
