### ISSUE TITLE
replacement for amenity=public_building

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#322]
This nonspecific tag would benefit from replacing it with more precise one

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building mentions

- office=government for government offices
- amenity=townhall
- amenity=library
- amenity=police
- amenity=hospital
- amenity=school
- leisure=sports_centre
- amenity=community_centre

It seems that also following may be useful:
- office=yes

**Comment by westnordost** [comment]
But what to do in the case the user can (rightfully) really not say what kind of public building it is? (ie its some weird mixture?)

This is the same reason why surface=unpaved etc exists.

Am 13. Juni 2017 06:27:47 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>This nonspecific tag would benefit from replacing it with more precise
>one
>
>https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_building
>mentions
>
>- office=government for government offices
>-     amenity=townhall
>-     amenity=library
>-     amenity=police
>-     amenity=hospital
>-     amenity=school
>-     leisure=sports_centre
>-     amenity=community_centre
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/322

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
> can (rightfully) really not say what kind of public building it is

I would expect it to be so rare that it would fall under "can't say, hide quest". I can implement it in my personal fork and test it.

**Comment by westnordost** [comment]
Hmm, you didn't get my point: The app will then ask every user that comes by this place, and if every user answers with can't say, the quest will never be solved. It is true that the quest will not be shown as long as there is a note, but as soon as it is closed, tge quest will appear again.

This is a bit the behavior as the qa tools that show not only clear errors but also warnings that may or may not be errors.

There may be a generic solution to this, applicable also to a possible "what kind of paved?"-quest. If the building can really not be determined more detailed, then require the user to write a short comment what it is then. The tagging could be i.e.

building=public_building
public_building:note=shared village meeting hall, kindergarten and coffeehouse

Am 14. Juni 2017 11:38:44 MESZ schrieb Mateusz Konieczny <notifications@github.com>:
>> can (rightfully) really not say what kind of public building it is
>
>I would expect it to be so rare that it would fall under "can't say,
>hide quest". I can implement it in my personal fork and test it.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/322#issuecomment-308379310

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
In that case coffeehouse, kindergarten should be tagged separately.

Note that it is about amenity=public_building, not building=public_building.

**Comment by matkoniecz** [comment]
To be clear, building=public_building is perfectly fine and requires no compline.

**Comment by derfasthirnlosenick** [comment]
Seems similar to #112 and #314 - we (as of now) have no standard way of showing that someone went and verified the info that is stored on osm. This means we either 
a) use some method to store the info on osm (lastcheck or similar tag, touching the node, ...). Might ruffle some feathers.
b) unchanged/verified info is just stored locally - every other user will still see the quest. Might create some double-work.

b) might be a good way to test whether the value-add from such verification is worth the possible disruption caused. This would need 3/4 things:
1. Implementation of the quests of interest
2. An "Einzelkämpfer“ setting/build that triggers these quests - in order to avoid annoying/overwhelming normal users
3. A way to generate a report on the verification (e.g. for type A quests, the user had X times no change, Y times change to parameter A, ...) - this would enable a more informed discussion.
(4. In case data (date/time, result) is stored on the "no change" quests, this info could potentially be written into OSM once a concrete decision is taken - I'd be quite cautious with this one though as that could screw up things.)

I guess as long as nothing is written on osm, there is no harm done to the greater OSM community.

**Comment by rugk** [comment]
@derfasthirnlosenick I think for the current stage it is not worth to discuss it. (Or either, in a separate issue.) The current policy is [(nearly) no false-positives](https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete#user-content-no-false-positives).

In any case looking at this quest suggestion, I think it is not that bad. First of all `amenity=public_building` is a discouraged tag, so (hopefully) there should not be that many buildings tagged with it. So basically this quest would be about cleaning up a type of discouraged tags by making them more specific.

So, now second question: Can the user usually reasonably decide what type of building this is?
Seeing the list of possible buildings, I clearly think, yes. The reason is that mos of these types of buildings have a plate/text somewhere stating what it is (library or so).
Only `townhall`, `community_centre` and `sports_centre` could get difficult, but in this case I just hope that not so many townhalls exist in one place (:wink:) and other wrongly tagged `public_building`s are rare.

**Comment by matkoniecz** [comment]
After real world fixing of this problem - in most cases it is fixable without resurvey, in remaining one note may be opened.

I decided against implementing it even for my fork.
