### ISSUE TITLE
Quest for parking type (underground, multi storage and surface)

### ISSUE THREAD

**Issue by HolgerJeromin** [westnordost/StreetComplete#331]
- underground
- multi-storage (plus add building?): image from [mapillary](https://www.mapillary.com/app/?pKey=Ev8dnRA1Q4qjSOtCnDA_Ng)
- surface: image from [mapillary](https://www.mapillary.com/app/?pKey=bHTfAWGLa0aPUIvqJw5DGw)

separated from #100

**Comment by rugk** [comment]
@ENT8R here we see how awesome it is of you to always forget to add "Fixes #issuenumber" to your PRs. This issue was fixed 2 months after it has been created and it took once again a month to notice that it is still open and anyone forgot to close it.

See https://help.github.com/articles/closing-issues-via-commit-messages/ for how to do it properly.

And, of course, please close this issue. It is fixed.

**Comment by HolgerJeromin** [comment]
@rugk your are right. But please stay polite.
