### ISSUE TITLE
Building type quest - allow to access full list by scrolling, not by clicking "show more"

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#3387]
**Use case**
On mobile it is more natural to scroll list than to click on button.

**Proposed Solution**

Current: list with top answers and blue "show more" button. Pressing button replaces top values with a full list.

Proposed: list with top values and  full list below - accessible by scrolling, not by pressing button.

Seems clearly better to me (multiple people in testing tried to scroll and completely failed to notice big blue button). But I want to check before implementing anything.

**Comment by smichel17** [comment]
I am conflicted.

On one hand, I agree that having to scroll *and* tap a button is annoying, and that scrolling is the natural motion.

On the other, the categories interface is equally cumbersome, and having 6 recent entries allows me to avoid using it most of the time (and #3373 will reduce that further). I'm not sure I want to reduce the number of recent entries or make the category view even more clogged and awkward; I think you'd need to do one of those, unless you're proposing to have two "sticky" scroll positions (expanded recents & category view with no recents) which… that might work. I'm open to at least trying it.

**Comment by matkoniecz** [comment]
> I'm not sure I want to reduce the number of recent entries 

I am not proposing this

> make the category view even more clogged and awkward

not his

>  I think you'd need to do one of those

Why? I want to have one menu, with top answers on top and categories below them in one conrtinuous list

**Comment by smichel17** [comment]
- Open a category
- Scroll down
- Scroll back up with a "fling" motion so there is momentum

Current behavior: stops at the top of the category list, where you can see the open category (to collapse it again).
New behavior: scrolls all the way to the top of the top items. Now you have to scroll back down to get to the categories.

I am open to the possibility that it won't be that bad, or that we can put two "scroll momentum stopping" points (like what we currently have, that stops the scrolling at the top of the category list, instead of moving the form down lower).

**Comment by mnalis** [comment]
@smichel17 Perhaps convert `Recents` to just another category, which is placed at the top of the list, and expanded by default?

Then clicking on the `building type` quest could open the list of categories directly, and get rid of annoying `show more` button, while converting whole `scroll` / `find show more button` / `tap show more button` / `scroll`  to just `scroll` and thus fixing this issue, while still having `recents` as easily accessible as they where before.

**Comment by alex-m-ffm** [comment]
Maybe the top values could also reflect the most common types already in the database in the current surroundings, rather than just the recent selections of the user? Of course this might require additional database queries...
In the first days I was too lazy to explore the "Show more" button and might have misclassified some non-residential buildings as multi-family homes, since the default top 6 are all residential types. Perhaps other newcomers fall into the same trap.

**Comment by smichel17** [comment]
I re-used the "other" image + string for a proof of concept of @mnalis' [idea](https://github.com/streetcomplete/StreetComplete/issues/3387#issuecomment-946252307). It turned out to be much easier than I expected.

<img width="350" alt="Form expanded" src="https://user-images.githubusercontent.com/6563664/147251575-236eb30a-5c36-404d-bdb0-f0635770c5f4.png" /> <img width="350" alt="Form as it woudl be when it first opens" src="https://user-images.githubusercontent.com/6563664/147251597-2e99b176-449a-4252-9754-7e920d2b0cd9.png" />

Now that I implemented it, I think my fear in https://github.com/streetcomplete/StreetComplete/issues/3387#issuecomment-944894497 is probably overblown. After all, in the first screenshot above, you can still see the categories. And it's still way less work than clicking the "show more" button was before. On the other hand, with the solution of making "recent items" a category, then we always have a useless item taking up the top slot when the form is first opened, like in the second screenshot.

So I think I will probably go with the original idea, and just stick the recent items on top of the list. Needs a few tweaks so it looks right and to clearly mark it as "Recent/Suggested", but otherwise seems good to me.

<img width="350" alt="Form expanded, with recent items not in a category" src="https://user-images.githubusercontent.com/6563664/147258744-5b1356f3-74ea-46e3-9a26-a90fd8b70132.png" />

**Comment by matkoniecz** [comment]
@smichel17 Do you still have this code by any chance? Can you push it to github? (appears to be not present on https://github.com/smichel17/StreetComplete/branches/all )

(just in case that you can locate it easily and it works with latest SC)

**Comment by matkoniecz** [comment]
It appears to be on https://github.com/smichel17/StreetComplete/commit/1a25091c6c8339eb2d67ce5c0d98eb487762a04f

**Comment by smichel17** [comment]
Yes, that's it

**Comment by smichel17** [comment]
Right now, this is pretty low priority for me personally, so I don't know [if/when] I will finish it. I'll unassign myself to reflect that; if someone else would like to implement this, feel free.

[if/when]: I seem chronically incapable of not getting involved in whichever tools I use, organizations I'm part of, etc— and then my current involvements fill up my time so I can't continue with my previous ones. So if you see activity on my OSM profile, you can also expect to see me around here shortly :)
