### ISSUE TITLE
StreetComplete asks for data on cycleways under construction

### ISSUE THREAD

**Issue by matthiasfeist** [westnordost/StreetComplete#3434]
**How to Reproduce**
StreetComplete asks for the type of Cycleway here: https://www.openstreetmap.org/way/414672271 but not if it's completed... 
I think it should not be asked as the path is still under construction.

![Screenshot_20211023-150100_StreetComplete](https://user-images.githubusercontent.com/1589740/138557524-e20cdc9c-9afb-417e-8c28-28a9146b8e20.png)

**Versions affected**
Android: 11
StreetComplete: v36.1

**Comment by matkoniecz** [comment]
I am unassigning myself as 

- my PR was useful but handling this requires something different
- if a nearby active construction should stop quests then it should be considered more generally and be applied to many other quests

**Comment by smichel17** [comment]
> if a nearby active construction should stop quests then it should be considered more generally and be applied to many other quests

This is a good point. It would also be more efficient to implement if there just needs to be one pass to create bounds for areas under construction, which can then be queried, vs having to check for each element.

**Comment by peternewman** [comment]
> Though it can be easily argued that the same should be done also with `lane` `surface` `lit`

From a quick look aren't these covered already as we won't show the quest for `highway=construction`?

> `sidewalk`  quests

This has the same complexity as cycleway, as the sidewalk/cycleway may be separately mapped from the road being constructed.

> expanded to include also nearby nonparallel lines and `landuse=construction` areas. So I worry a bit about slippery slope here

Is it now worth adding the relatively simple parallel line cases for sidewalk/cycleway **resurvey** as they're a quick win?

> > if a nearby active construction should stop quests then it should be considered more generally and be applied to many other quests
> 
> This is a good point: It would be more efficient to implement if there just needs to be one pass to create bounds for areas under construction, which can then be queried, vs having to check for each element.

I agree though, it would be beneficial to cover the broader case at some point to stop people being asked about the state of traffic lights or benches in squares that are being resurfaced, or shops in buildings which are being rebuilt, otherwise they risk inputting incorrect or temporary data.

I was actually going to open a discussion about the reverse of this too (maybe I still should to flesh out the details), which I think could use the same logic as this, or similar, when an area has been reconstructed, it would be great to be able to resurvey everything within that area regardless of when it was last checked, as e.g. the paving surface or lighting or traffic lights may have changed. It could use the same construction area and the completion date and resurvey if older than the completion date of the construction.

Should we re-title this issue, it's certainly only now about resurvey with the existing fix that's gone in, plus the wider construction stuff we're talking about.

**Comment by matkoniecz** [comment]
> From a quick look aren't these covered already as we won't show the quest for highway=construction?

The same as cycleway quest.

And - the same as in case reported here - there could be a nearby `highway=construction` `footway=sidewalk` or surface changed termporarily due to nearby construction etc.
