### ISSUE TITLE
Toilet/diaper

### ISSUE THREAD

**Issue by amilopowers** [westnordost/StreetComplete#344]
I would love to see if the app asks if an amenity has restrooms (toilet=yes/no) and if there is a diaper table.

https://wiki.openstreetmap.org/wiki/Key:diaper

I don't know how to code ao I can't do it myself.

**Comment by westnordost** [comment]
For what amenities do you think this quest should be displayed? Keep in mind that the quests are displayed globally and then always for every amenity of the type you specify.

**Comment by HolgerJeromin** [comment]
This could be only for micro mapped amenities with toilet=yes/no.
That was suggested by amilopowers.

**Comment by amilopowers** [comment]
I think it should be asked for every node with a "toilet=yes" tag.

And for amenities/shops like:
amenity=restaurant/cafe/pub...
shop=mall

**Comment by rugk** [comment]
> And for amenities/shops like:
>amenity=restaurant/cafe/pub...
>shop=mall

I think it depends on the country whether such amenities usually have a toilet or maybe are even required to have one. (such as restaurants in Germany)

**Comment by HolgerJeromin** [comment]
I have never found a place with diaper:fee=yes in the last five years. I would have used the next meadow instead.

**Comment by amilopowers** [comment]
I think interesting is if there is one at all and if it is accessible by both men and women. So diaper:unisex=yes/no.

**Comment by rugk** [comment]
Okay, you've convinced me. :+1:

**Comment by krzyk** [comment]
@amilopowers I think this one can be closed, it was implemented in #381

**Comment by rugk** [comment]
@krzyk BTW: Next time you can use "Fixes #issue" to (automatically) [let issues close](https://help.github.com/articles/closing-issues-via-commit-messages/) when a PR is merged.

**Comment by krzyk** [comment]
@rugk I don't like doing that, because the creator of the issue should close it, not the implementer. e.g. because it could be implemented not the way the "creator of the issue" wanted.

**Comment by rugk** [comment]
Actually the idea is it to close when the PR is merged, i.e. when the maintainer approves it. And as you see here, the issue creator maybe forgets the issue at all and does not close it. (So what's the point, when you even have to suggest to close the issue?)
When the issue creator does not like the solution, they will open a new issue, anyway…

**Comment by krzyk** [comment]
Because reporter might not monitor this repo for changes, when I inform him he can look at it and accepts the change. This way it makes the process more clean.

Here's how I see it (based on experience from other opensource projects):
1. Reporter creates issue
2. Implementer implements it
3. Reviewer/maintainer reviews if it follows standards, and looks good
4. Reporter sees the changes and accepts them or not, if not, implementer creates another PR for the same issue.

Sometimes only reporter knows how to recreate the issue (e.g. OAuth problem).
`fixes` syntax is good when you are the only person working on the repo and created the issue.

**Comment by rugk** [comment]
> when I inform him he can look at it and accepts the change.

You saw how it worked you: You informed, nobody answered, maintainer had to close the issue.

For everything else, you can always reopen an issue… (I am not sure right now if the issue creator can do this, if the issue was closed by a PR…)

In any case, I think what really matters is how the maintainer here would it like to be. So @westnordost do you want to close issues manually after a PR is merged or automatically?

**Comment by westnordost** [comment]
I don't care

On 18 August 2017 13:58:31 CEST, rugk <notifications@github.com> wrote:
>> when I inform him he can look at it and accepts the change.
>
>You saw how it worked you: You informed, nobody answered, maintainer
>had to close the issue.
>
>For everything else, you can always reopen an issue… (I am not sure
>right now if the issue creator can do this, if the issue was closed by
>a PR…)
>
>In any case, I think what really matters is how the maintainer here
>would it like to be. So @westnordost do you want to close issues
>manually after a PR is merged or automatically?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/344#issuecomment-323334837

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by amilopowers** [comment]
Thanks for adding that quest! I saw one on an "amenity=toilet".

Question: On which tags does it appear?

**Comment by rugk** [comment]
See https://wiki.openstreetmap.org/wiki/StreetComplete/Quests

Basically on all public amenity=toilet and some other restaurants and shops which have a toilet.

**Comment by amilopowers** [comment]
Thank you, I didn't know that website!

**Comment by bkil** [comment]
There is an ongoing proposal to enhance tagging of baby changing tables. Please share with whoever may be concerned and feel free to comment:
https://wiki.openstreetmap.org/wiki/Proposed_features/baby_changing_tables
#1380
