### ISSUE TITLE
Feature Request: Filter quests

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#35]
It has been requested by several people to have the option to filter (out) certain quest types.

I would supply this as an option in the settings, listing all quests with a checkmark in front, whether to download and show them or not.

**Comment by gdt** [comment]
I think a simple list with on/off by type would be a great enhancement.  Around me, almost no buildings have levels information, leading to vast numbers of levels quests.  I don't know of any important use for that info, so I'm totally uninterested in it.   Opening hours, on the other hand, shows up in osmand searches, and there aren't so many  that doing them all in my town is crazy.  But everybody will feel different.

**Comment by ax3l** [comment]
If would be great if we can not only filter what is in the "available-quests list" but also move the ordering of quests to set our own priorities when to show what (currently the defaults are hard-coded).

Of course, a "reset to defaults" button might be useful to reorder and re-enable/re-disable the default quests.

**Comment by westnordost** [comment]
Makes sense, yes

**Comment by anarcat** [comment]
for me, it's not a filter as much as prioritization that i need. i'd be happy to walk or bike a mile or two to get some critical information that's missing from the map (say a park name or bike lanes). i don't care so much about the closing hours of the bar next door. :)

**Comment by matkoniecz** [comment]
App may also try to learn from user actions - maybe it can work by counting how many issues for each type are hidden without fixing and how many are fixed? And show ones that given user fixes rather than dismisses?

One failure mode for that is somebody that prefers one type over another depending on location/day/season and overall would prefer to receive mix of different issues rather than monoculture...

**Comment by waldyrious** [comment]
> App may also try to learn from user actions - maybe it can work by counting how many issues for each type are hidden without fixing and how many are fixed?

IMHO, we should not make this too complicated 😄 it seems sensible to start with a basic on/off implementation as suggested by @gdt above; which could then be enhanced with reordering, as @ax3l mention, and only then improved with smart heuristics as you describe (which, at least for me, should never change settings automatically, but at most present a dialog to the user offering to disable a specific kind of quest they've been dismissing a lot).

**Comment by westnordost** [comment]
The problem with "monoculture" is that this app relies on Overpass queries and wants/needs to be very cautious not to overload the server with queries. For the necessary runtime of a query, the size (if 1km² or 10km²) is much less decisive than the number of queries. That is why queries are usually made in relatively large areas but relatively few queries are made (by quest auto downloader), 3 per trigger.
This is why you see this "monoculture" in the app.
The quest auto downloader will only pull more quests, if most downloaded quests in the vicinity are solved (or hidden).

**Comment by Sukender** [comment]
Sorry to just "bump" that issue, but I must say the whole app is unfortunately boring to use in my area **ONLY** because I have plenty of "speed limits" quest prompting first. As a consequence, I have to select the quest, to remove it an see another one (5 clicks instead of 1 + loading times).

So having the ability to sort quests and/or filter them would be really nice. I suppose that a list with draggers to order it the way we want should be enough.

**Comment by westnordost** [comment]
It's planned for the next release (3.0)

**Comment by mdtrooper** [comment]
Sorry...but... How do you want the filter? As icon :mag: in toolbar or in the settings.

I have a lot streets that the pin or icon quest of "speed limit" over the icon of kind of street. And I can not fill the quest of "kind of street" and I don't know the speed limit.

And maybe I can help to develop the filter...if the gods give me a bit of free time.

**Comment by westnordost** [comment]
There will be another menu in the settings which displays a list of all quest types and where you can permanently enable or disable quest types.

I am implementing it in a way so that it will be relatively easy to also add the possibility for users to reorder the quest types (= the order on which they are downloaded and which is shown on top and which is shown below other quests on the map). But I think I will leave that (for now), because I cannot think of a use case where being able as a user to reorder the quests would make an awful lot of sense.

**Comment by waldyrious** [comment]
> I cannot think of a use case where being able as a user to reorder the quests would make an awful lot of sense.

Here's my use case for that, in case it helps: as I used the app, I ended up hiding lots of quests in my neighborhood/city, in order to surface those that I was able to complete more quickly or by glancing around (e.g. on a car ride, or when walking for a purpose other than surveying). For example, I hid street name quests to show road paving type, etc. to show up.

Now, after completing most such tasks in the locations I'm usually at, I'd be happy to tackle the harder quests when I can find the time to go surveying -- but without the reordering feature, I'd have to regularly be tweaking which quests to make visible or not. It would work, but it wouldn't be very convenient.

**Comment by matkoniecz** [comment]
>  I cannot think of a use case where being able as a user to reorder the quests would make an awful lot of sense.

In my fork I changed priority of many quests:

Bicycle parking had higher priority as I am interested in mapping bicycle infrastructure

Opening hours is lower as this data is really quickly outdating, boring and time consuming to collect.

Surface is higher as it is easy to collect and save after cycling given route (especially in situation of "it is asphalt everywhere".

Missing names is lower as in my city only extreme corner cases are remaining.

Wheelchair access is higher as it is relatively easy to collect and works as checking whatever poi still exists.

**Comment by westnordost** [comment]
Okay, sounds all reasonable.

**Comment by waldyrious** [comment]
:tada: :grin:
