### ISSUE TITLE
More detailed speed limit quest?

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#353]
There are speed limits that apply only for
  * Trucks.
  * different time frames.
  * one direction, not both.
  * probably more...

If this would not be implemented what should one answer in such a quest?

**Comment by westnordost** [comment]
The quest has been on master less than 12 hours and already the first feature request :-S 

As for everything, the fallback answer is "leave note".

Yes, all three are valid. However, following things should be considered:
- edge cases should not clutter up the main view
- consider whether these edge cases occur often enough that it is worth the effort to implement them
- Different time frames: Parts of opening hours UI could be reused
- One direction: parts of to be implemented cycleway quest could be reused (probably)

You could have a look at taginfo for how much % of speed limits these edge cases apply, then we can discuss based on this data whether it is worth implementing it.

On 27 June 2017 11:06:06 CEST, Natenom <notifications@github.com> wrote:
>There are speed limits that apply only for
>  * Trucks.
>  * different time frames.
>  * one direction, not both.
>  * probably more...
>
>If this would not be implemented what should one answer in such a
>quest?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/353

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Of tagged roads with maxspeed:
% | type
-- | ----
1.3% | for different vehicle types (trucks, buses, ....)
1% | at different times
0.5% | for different directions
0.5% | no official but practical speed limits

**Comment by Natenom** [comment]
So no reason to implement :)

Could you instead please add another answer like "There is no speed limit sign for this street", because there are some quests here where this applies.

**Comment by westnordost** [comment]
Hu, there is!

**Comment by westnordost** [comment]
It's even quite elaborate.

**Comment by Natenom** [comment]
Jupp, just saw it. Sorry. Wanted to remove that here before you read it. Too late :)

**Comment by krzyk** [comment]
Conditional maxspeed is a country wide default in Poland for urban roads: 50 km/h between 05-23 and 60km/h between 23-05). So for Poland we map implicit maxspeed with:
```
maxspeed=50
maxspeed:conditional=60 @ (23:00-05:00)
source:maxspeed=PL:urban
```

Maybe it would be good to implement some default values per country for implicit maxspeeds (this would be easier than adding handling of full conditional rules).

**Comment by westnordost** [comment]
StreetComplete only sets `source:maxspeed=PL:urban` for the case of being in Poland and saying "there is no sign" in an urban street because the rest can be inferred from that information.

**Comment by krzyk** [comment]
Yes, it can be inferred. But it will require additional work (adding manually or using some automation) to add the conditional maxspeed, to have the full info in OSM.

I'm just adding that here so if there will be more detailed maxspeed quest, you can take that into consideration.
There are few countries that have conditional maxspeed - besides Poland I see that Lithuania, Latvia and Estonia have those on motorways during summer/winter, France has it during rain. Maybe there are others. (source: https://en.wikipedia.org/wiki/Speed_limits_by_country)

**Comment by matkoniecz** [comment]
> StreetComplete only sets source:maxspeed=PL:urban for the case of being in Poland and saying "there is no sign" in an urban street because the rest can be inferred from that information.

Normal tagging in Poland is to set maxspeed and maxspeed:conditional - because this way maxspeed data will be usable by standard data consumers. Human that would tag only source:maxspeed would be considered as one making mistakes.

Would you accept PR fixing this problem and setting also maxspeed and maxspeed:conditional as it is normal in Poland for source:maxspeed=PL:urban roads?

**Comment by westnordost** [comment]
No. This kind of intelligence belongs into data consumers. What if the default speed limits change? Then all explicitly added speed limits are suddenly wrong.

This is why the competing tags maxspeed:type (GB) and maxspeed:zone (DE) were invented, in certain areas it is even accepted to put i.e. RO:urban directly into the maxspeed tag (RU, RO). Any of the above is better than the current source:maxspeed scheme, unfortunately they didn't become accepted beyond their certain areas.

Data consumers need to be able to deal with this anyway.

I hope at some point in the future, the community will come together and agree on ONE correct way to tag and change all the taggings automatically into the globally accepted one. I favour the RO/RU theme, as the old argument that maxspeed should always be a number doesn't hold true anymore anyway.

---

SC should only add the information that the user surveyed, not infer other data based on this observation. Because:
- if the inferred data is wrong, it will add wrong data without the user's knowledge or consent to OSM. I.e. for speed limits, the default speed limits can be quite complex and depend on a number of things. In short: this behavior would come close to an automatic edit
- if an information can be inferred always from another value, then this information is duplicate and thus is superfluous
- In case of speed limits, it is usually added to make life easier for data consumers so that they do not have to have the intelligence that you'd like to have in SC. But what is this? This is actually pretty much "tagging for the renderer", or in that case, tagging for certain data consumers.

On 30 June 2017 09:39:11 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>> StreetComplete only sets source:maxspeed=PL:urban for the case of
>being in Poland and saying "there is no sign" in an urban street
>because the rest can be inferred from that information.
>
>Normal tagging in Poland is to set maxspeed and maxspeed:conditional -
>because this way maxspeed data will be usable by standard data
>consumers. Human that would tag only source:maxspeed would be
>considered as one making mistakes.
>
>Would you accept PR fixing this problem and setting also maxspeed and
>maxspeed:conditional as it is normal in Poland for
>source:maxspeed=PL:urban roads?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/353#issuecomment-312198266

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by matkoniecz** [comment]
I think that SC should follow consensus on tagging issues if one exists.

**Comment by westnordost** [comment]
A consensus would be nice. I have spent quite some time researching in wikis and discussions. Not one exists, but almost half a dozen competing ones.
And even if there were a consensus that an explicit limit must also be added, this app wouldn't add it automatically because of the stated reasons and also wouldn't ask the user because it can't be expected that he knows.

The consensii that apply universally are
- Don't tag for renderer 
- no explicitly approved auto edits 

On 30 June 2017 12:58:14 CEST, Mateusz Konieczny <notifications@github.com> wrote:
>I think that SC should follow consensus on tagging issues if one
>exists.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/353#issuecomment-312238960

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
So, closing this.

Perhaps for the 1.3% of speed signs that have different limits for different vehicle types (trucks, buses, ....) the quest can be extended later. (Seperate issue - create one when you plan to work on it)

**Comment by matkoniecz** [comment]
> A consensus would be nice. I have spent quite some time researching in wikis and discussions. Not one exists, but almost half a dozen competing ones.

Have you checked existing validators? For example JOSM validator complains about missing maxspeed ("source:maxspeed without ^maxspeed:? (1)").
