### ISSUE TITLE
Farmland/produces quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#363]
A quest about `landuse:farmland` could be useful. Including setting the [crop](https://wiki.openstreetmap.org/wiki/Key:crop) and what it [produces](https://wiki.openstreetmap.org/wiki/Key:produce). The produces thing could also be expanded to aquaculture and forest.

In any case images should be included for all townies, so they select the right thing… :wink: 

Also when vineyard is selected it should convert the landuse field instead (`landuse=vineyard`, see wiki). And a "more options" selection containing "this is not a real field" changing the landuse to `meadow` could also be useful.

A problem could be that more than one fruit/crop is produced, so first of all selecting multiple values must be necessary. Apart from that, maybe you need to ask this question multiple times (winter, summer, spring, etc.) to find out, what is always produced. Don't know how to do this though…

**Comment by chrisdebian** [comment]
This sounds like a good idea, especially converting the tag,  which would make the map data even better. Good idea.

Chris.

**Comment by rugk** [comment]
Yeah, it was also only one example. `landuse=greenhouse_horticulture` would be the same. Maybe the `trees` thing would be more difficult to handle, or maybe not…

**Comment by matkoniecz** [comment]
> Because of the target group, only those quests are shown which are answerable very clearly by asking one simple question and only those quests are created which contain very few false positives.

https://github.com/westnordost/StreetComplete/blob/master/README.md

I think it rules out ones like this that require obscure local knowledge or questions repeated over months/years.

**Comment by rugk** [comment]
Hmm, it's difficult. However, it is very easily answerable for the current time and at least vineyards won't change to cornfields the next year, so it depends a bit.

**Comment by westnordost** [comment]
No.

1. Farmland is planted with different crops throughout one year
2. Farmland usage may vary between fallow, different crops and meadow
3. Unless you are a farmer or a botanist, users will not recognize which crops exactly these are

What **is** possible is to ask users for the produce of farmland with perennial plants, a.k.a **plantations**: apples, pears, bananas, rubber, coconuts, cocoa, coffee, grapes etc.
But, please open a new issue for that and add some details for implementation. This also requires a country-specific list of common produce types, [like it is done for the sports quest](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/popularSports.yml) because otherwise there are too many choices.

**Comment by rugk** [comment]
> Unless you are a farmer or a botanist, users will not recognize which crops exactly these are

Ehh, I think they do. The wiki is quite general and user likely get the difference between asparagus, rice and a vineyard.

**Comment by rugk** [comment]
Split into:
* https://github.com/westnordost/StreetComplete/issues/367 - general questions about landuse/produces
* https://github.com/westnordost/StreetComplete/issues/368 - orchard/trees
