### ISSUE TITLE
Create Wiki How-To for Writing of New Quests.

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#365]
Hi, Tobias/ all,

As you've said, it looks like many people are interested in your great application, and we are not short of ideas for quests. Would it be possible to ask for help, for someone to write a short Wiki How-To, explaining how to best provide data for new Quests. The idea is that all anyone would need to do, would be to follow the guide, and provide as much useful information, as possible, so that whoever writes queries, in the future, has to do the minimal amount of work, in order for the whole world to benefit, from someone's useful idea. The great thing about StreetComplete, is that it is mildly addictive. I showed my partner, and she instantly started adding missing data....brilliant!

Thanks,

Chris
chris_debian
2E0FRU

**Comment by matkoniecz** [comment]
Who would be target of that wiki page? Programmer making PRs?

**Comment by chrisdebian** [comment]
Users who want to make the application even better, and where possible, do some of the background research, to save your time. Experience has taught me that as projects get more and more popular, you will not be able to manage the workload, if you do it all yourself, as much as you may want to.

**Comment by westnordost** [comment]
I wrote something. Where should it ideally go?  Wiki page on Github? Openstreetmap wiki?

**Comment by westnordost** [comment]
Do you have an idea for a new quest? Read this!

1. Decide whether the idea works out with StreetComplete

Consider the limitations of StreetComplete:
- Only existing elements can be extended, no elements can be added or removed.
- The geometry of elements cannot be changed, i.e. it is not possible to split a way (currently)
- So basically: Only tags can be edited 

No false-positives: Consider that every instance of this quest must actually be solvable by users. Sounds obvious, but the implications are that
- the question asked must be valid for any element for which the question is asked. I.e. asking for the address of every building does not make sense because not all buildings have house numbers and those that do sometimes have the housenumber tagged as a separate node.
- any reasonable answer the user gives must lead to the quest not being generated for other users anymore. For example, how to tag that a shop has inded no website (for a hypothetical quest that asks for that)? There is no accepted tag for that, at least currently. If the user's answer leads to nothing being tagged, it means that technically the quest cannot be solved - the next user will be asked the same question. 

Sometimes, due to the nature of how things are tagged in OSM, it is unfortunately simply not possible to fulfill this. 
 
Finally, think about the users:
- No knowledge about OpenStreetMap or any other background knowledge must be necessary
- Users are out and about and impatient. Input must be able to be straightforward, clear and quick
- The information the users are supposed to collect must be actually easily accessible to the users
- Don't bore the users. A quest which is to be answered in most cases with the same (yes-no) answer is not a good quest. I.e. asking for any road which vehicles are allowed on it, is silly.

2. Think and write down how to generate the quests

Quests are usually generated by searching for certain OSM key-value combinations (via Overpass). I.e. for the "What sport is played on this pitch" quest, quests are generated for nodes and ways that have the tag `leisure=pitch` but not the tag key `sport`.
You need to think about the condition for which key-value combinations on which elements the quest should be generated. The rules should be as exclusive as possible to generate as few false-positives as possible. I.e. instead of asking for the surface of any way tagged with `highway=*`, the surface should instead only be asked for an inclusive list of roads.

Also, for very detailed information that can be assumed to always have the same ("undefined") answer in many countries, it might be a good idea to limit quests to an inclusive list of certain countries.

Depending on the quest, this requires some research but is necessary preparational work that can be done without any programming knowledge (but with knowledge of OSM).

3. Design the form

As mentioned, the user interface must leave no space for misunderstandings, it must be concise and quick and easy to use. Also sounds obvious, but you will quickly find out that a balance must be found between covering all the edge cases and designing the form to be as straightforward and clutterless as possible.

- Design the main form clutter-free so that it is straightforward for the majority of use cases.
- Make it not impossible to answer the edge cases (but don't clutter up the main form with that). A good pattern is to "ban" answering edge cases into the "Other answers..." menu. I.e. look at the opening hours quest.
- Don't rely on the "leave a note" fallback too much. It is not intended and does not work as a regular answer but is designed to cover the case that the question was invalid itself because it was based on wrong data like i.e. the place does not exist anymore.
- The information the user should fill in should be as atomic as possible. Users are impatient. I.e. do not let them fill out a whole address with street name etc. when just the house number is fine too.
- "A picture is worth a thousand words": Often the term for certain things may not be enough to convey the meaning of certain predefined answers. Do you know what a wheelbender is? You will know if you see the photo. 

Considerations about the edge cases to consider, how the design could look like and finding good representative photos or icons that match in style is also part of the preparational work that can be done without programming knowledge.

**Comment by matkoniecz** [comment]
> Where should it ideally go? Wiki page on Github? Openstreetmap wiki?

Would you prefer it as "official statement" or "something that can be edited by anybody"? In the second case OSM wiki is good, in the first case I would link this comment from OSM wiki (or post it on Wiki page on Github and link it from OSM wiki).

**Comment by westnordost** [comment]
I put the article into the github wiki

**Comment by matkoniecz** [comment]
CONTRIBUTING file (or CONTRIBUTING.md if you're using Markdown) from root of the repository is linked during creating a new issues.

Maybe create it and link there this article? It increases chance that somebody creating issue for new quests will see it.

See https://github.com/blog/1184-contributing-guidelines

**Comment by chrisdebian** [comment]
Tobias/ Matkoniecz,

This is excellent. I'll have a look today, and offer any thoughts, for your consideration. Great work!

Chris
