### ISSUE TITLE
Confusing images for surface quality quest (concrete)

### ISSUE THREAD

**Issue by mnalis** [westnordost/StreetComplete#3781]
**Use case**

When answering `surface quality` (smoothness) quest, when surface is `concrete`, I've got displayed following pictures for answers:

![s_Screenshot_20220218_161032_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/154773003-0ad95d08-7217-445c-ab07-f89daadb99c6.jpg) ![s_Screenshot_20220218_161000_de westnordost streetcomplete](https://user-images.githubusercontent.com/156656/154772998-f58eea8a-75a8-4b3b-a824-f90130e1ef80.jpg) 

the first three (circled in green) are confusing time and again to me, as the pictures are of something I would more likely identify as `surface=paving_stones` instead; so this results in me selecting `surface is different` answer, only to be shown that surface is indeed already correctly mapped  as `concrete`. 

This is confusing and gets frustrated after first few times, and especially as last pictures which might tell the difference are only shown on bottom (when I have already gone and automatically answered `surface is different`)

(I know the pictures for real `paving_stones` are different in this quest, it is just that those lines make me identify the `concrete` surface as paving stones too)

**Proposed Solution**

- I think replacement pictures for `concrete` (or bigger crop of existing ones, showing more context, if that is an option - as there is no sense of scale currently which feeds the confusion) would be great - even if it is harder to see the  exact difference of quality of concrete, I think it would be less frustrating, as pictures themselves wouldn't be confusing.

- Alternatively (or better, in addition) we could show surface name in **bold** at the beginning (in the quest title itself, or in description); e.g. instead of asking _"Select one:"_, we could ask _"Select quality of this **concrete** way:"_  / _"Select quality of this **asphalt** way:"_ etc.

**Comment by westnordost** [comment]
The pictures shown for paving stones are completely different. Yes, picture #3 could be interpreted to be paving stones if you ignored the manhole cover in the back (would be pretty big paving stones don't you think?).

Anyway, I don't want to change anything here because if picture #3 was shown from further away, the (rough) structure and the size of the gaps would looks too smooth / small.

If this frustrates you every time, at some point you will remember that these are the pictures shown for concrete and it will not be a problem anymore.

**Comment by matkoniecz** [comment]
Though if you somehow can solve conflict between showing important part (edges of plates) and showing them as very large plates, feel free to open a pull request.

(you can also provide openly licensed images and mockup demonstrating improvement for images shown at this size in app)

**Comment by mnalis** [comment]
(I'll try if I stumble upon good example @matkoniecz, but I do guess it is improbable to be able to do that - that's why I indicated that in my opinion loss of precision would be acceptable compromise in order to get the bigger picture / more context - which (so far) seems to be opinion _not_ shared with devels  :smiling_face_with_tear:)

However, I did not get any comment from anyone on the alternative I've proposed: to **_show the current surface in the quest description_** (or title) directly? 

I realize that it requires another string to translate, but are there other issues with that idea? As it would both alleviate the problem with recognizing what the images shown **and** also allow users extra information to verify if surface is mapped incorrectly (which happens quite often for me), I think it would be quite useful.

I'm willing to try doing a PR for example that asks in manner like `quest_openingHours_name_title=What are the opening hours of %s?` e.g. _"What is the surface quality of this path here (asphalt)?"_, or some other way, if @westnordost would consider that acceptable?

**Comment by westnordost** [comment]
No, because 

> If this frustrates you every time, at some point you will remember that these are the pictures shown for concrete and it will not be a problem anymore.

I.e. if the user mistakes the pictures shown for another surface, he'll press the answer you pressed and eventually he'll recognize the pictures and know for which surface these are.

**Comment by pkoby** [comment]
I thought I would comment here rather than open a new issue, just to give my two cents.

One use case where I have noticed it would be useful to have the surface type in the question (e.g. "What's the surface quality of _Example Alley_ here (asphalt)?") is when surveying in bright conditions. I cannot easily tell the difference between the concrete and asphalt smooth images, and those are the only ones that pop up for me on my shorter screen. Having a text representation of the surface would be a second option for verification to make sure that it's correctly tagged.

**Comment by mnalis** [comment]
And in v42, it might even look nicer, as new questions looks like:
```
What's the surface quality here?
Sidewalk
```

which could easily be changed to more informative:
```
What's the surface quality here?
Sidewalk (asphalt)
```
