### ISSUE TITLE
Use traffic sign overlay from Mapillary to detect 'one-way' streets, turn restrictions, etc

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#379]
Similar to #370 

http://blog.mapillary.com/update/2015/06/02/id-signs.html covers the feature

![image](https://user-images.githubusercontent.com/365751/27847758-db4472f4-617e-11e7-9960-f3fbbe60e7a5.png)

https://www.mapillary.com/developer/api-documentation/#map-objects
s is the API I think. Checking how its used in the ID editor might be worthwhile as well.

Unfortunately these aren't tied to specific ways or nodes by id; so doing some "nearest way" calculations may be required.

Possible quests:
 * Add the turn restriction between these two streets (present user with the closest streets to choose from, similar to the ID turn restriction UI)
 * Is this street one way? What direction? (A one way sign was detected within X metres)
 * What is the speed limit for this residential road? (this may be more complicated, requiring splitting of ways or similar for different speed limits though)
 * Is there a heavy goods vehicle restriction on this road? Yes/No

https://www.mapillary.com/developer/api-documentation/#traffic-sign shows the detected signs

**Comment by eneerhut** [comment]
Awesome @CloCkWeRX. This is something we're investigating at the moment. Agree that map matching may be necessary. E.g. Mapillary has detected a 100km/h sign and it corresponds to xxx road. xxx road does not have speed limit information. Create task.

Investigating different areas for collaboration at the moment such as Osmose and ImproveOSM. Stay tuned!

**Comment by westnordost** [comment]
As far as I can see, Mapillary only detects the signs. If the signs are already visible through photos, it does not make sense to send StreetComplete surveyors there because all information necessary to add to the database that i.e. the maxspeed limit on a stretch of road is X or that a road is indeed oneway is already there and thus, the information can be added via iD or JOSM from the home computer.

The ImproveOSM data is different in the aspect that no actual sign has been spotted but only by analysing the GPS traces it is inferred that _probably_, a street is a oneway street. To confirm or deny that "probably", a survey makes sense.

**Comment by westnordost** [comment]
Anyway, the new traffic sign feature from mapillary is really neat. Though, I would suggest to only show those signs which either contradict OSM data or where OSM data is not available yet (i.e. speed limit).
