### ISSUE TITLE
Quests for paths

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#385]
Would be nice with quests about smoothness and trail_visibility for paths. Maybe sac_scale as well.

**Comment by rindlerblabla** [comment]
#38 #279 also mention smoothness.

**Comment by matkoniecz** [comment]
How you propose to detect whatever asking for sac_scale make sense? Asking about sac_scale for every footway in the city would be obnoxious.

**Comment by matkoniecz** [comment]
Maybe ask only on paths in relation http://wiki.openstreetmap.org/wiki/Tag:route%3Dhiking - but that requires making overpass query and testing is it reducing useless question ratio to acceptable levels.

**Comment by rindlerblabla** [comment]
Yes, sac_scale might not be the priority, but if it would be possible for hiking route relations it would be nice. Don't know anything about technical difficulties, I just know what I like to tag, hehe.

**Comment by rugk** [comment]
So maybe change the title to "Quest for hiking paths"?

**Comment by rindlerblabla** [comment]
Yes, but the idea of quests for smoothness and trail_visability is valid for all highway=path, I think.

**Comment by matkoniecz** [comment]
I would skip it for paved highway=path/footway and for ones with unknown surface.

**Comment by westnordost** [comment]
Please one issue for one data point to add. I'll close this one so that you can each start a fresh one. Please also read https://github.com/westnordost/StreetComplete/wiki/Adding-new-Quests-to-StreetComplete (the guide is new, if anything is missing or not clear, tell me) before doing that. 

Generally I think it should be possible with overpass to retrieve only ways that are part of a relation that have certain tags.
