### ISSUE TITLE
Quest. Trail_visibility for paths

### ISSUE THREAD

**Issue by rindlerblabla** [westnordost/StreetComplete#388]
See #385. 

Suggestion to ask for trail_visibility for highway=path/bridleway and maybe even track(?). My suggestion is like comments in the other thread purposed to exclude paths that are paved. Also to exclude footways since my experience is that they in general have good/excellent visibility. 

Ending up in paths with bad visibility is a problem when using routing in e.g. Osmand, why I think not only relations should be included.

See http://wiki.openstreetmap.org/wiki/Key:trail_visibility

**Comment by matkoniecz** [comment]
> Quest. TrailT 

It is not clear what is suggested here.

**Comment by matkoniecz** [comment]
I am confused by OSM wiki page - see https://wiki.openstreetmap.org/wiki/Talk:Key:trail_visibility#highly_confusing_tag

**Comment by rindlerblabla** [comment]
Good to figure that out first. About trail_visibility for tracks as I mentioned above, it's better to use  tracktype, which according to #38 already is on the list, so exclude that one as well.

**Comment by rindlerblabla** [comment]
Have now read the wiki myself and for me it's pretty obvious that it's ment for tagging paths not routes. The difficulty maybe is to find good images. Maybe it could be possible to have image for trail_visibility excellent

**Comment by matkoniecz** [comment]
@rindlerblabla Can you answer at https://wiki.openstreetmap.org/wiki/Talk:Key:trail_visibility#highly_confusing_tag or find somebody who would be able to answer?

**Comment by rindlerblabla** [comment]
Didn't know how to answer the will but it says "Part of a classification scheme for hiking trails, but can be used for any type of paths." "This key describes attributes regarding trail visibility (not route visibility) and orientation." I understand what you mean with the values in the table that it's confusing though.

**Comment by westnordost** [comment]
I'd close this then. It may be reopened if the definitions on the wiki are clearer. Though, currently they are both highly subjective, plus, I am not sure if this quest should be shown for any path, everywhere.

**Comment by rindlerblabla** [comment]
And even the photos on the wiki is a bit unclear. Think it's easy to say if the visibility is excellent or if it's bad/horrible but the values in between is just a mess.

**Comment by rhhsm** [comment]
I've been considering for a long time to revive this proposal, but I agree the wiki entry for the key is too confusing. That's why I opened this discussion about it here https://community.openstreetmap.org/t/tag-trail-visibility-proposed-improvements-for-this-descriptive-tag/97865 It was a very lengthy and confusing discussion without clear conclusions, unfortunately, so I postponed suggesting it here.
As for the selection on which ways (paths, footways and maybe bridleways, I think) to ask it, in addition to ways that are part of a hiking relation, it could be asked for ways that are within a national park, nature reserve, etc. It should not be asked for ways that are paved or are broad (tracks, roads) because these can be assumed to have no visibility problem.
