### ISSUE TITLE
Add Type of Ferry quest

### ISSUE THREAD

**Issue by daniel-j-h** [westnordost/StreetComplete#39]
The app should probably filter the number of markers it shows in the map view and prioritize quests for which the added value is high or the frequency in osm is low. Conceptually similar to [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf).

---

To be more specific here: consider the case of ferries. Ferries are tagged `route=ferry` and a `duration` tag describes how long the route takes. Without a `duration` tag you can only guess the duration.

The ferry tag is rare and the duration tags adds high value - a marker for a missing ferry duration tag should probably be prioritized among many opening hour, building level and roof shape markers.

http://wiki.openstreetmap.org/wiki/Tag:route%3Dferry

**Comment by daniel-j-h** [comment]
Related: filtering quests https://github.com/westnordost/StreetComplete/issues/35

**Comment by westnordost** [comment]
Easy to detect, but does it make sense for StreetComplete in particular? The ferry from Kiel to Göteburg takes about 12 hours, I think. **Somewhere**, on the middle of this long ferry route (in the middle), there is **one** quest marker in the middle of the sea which you will only see at that exact location because you do only see quests starting at a certain zoom level.

This is a technical limitation that will not be lifted soon.

So the chance is high that you will simply miss it. Also, there is usually no internet and no mobile phone coverage on seas, so unless you downloaded these pieces of ocean before manually, the chance is very high that you will not see it. Not to mention even get the idea that there could be any quests there at all.

And even if you are so lucky to see it - you won't be able to answer it at that time, because you can only answer it after you arrived. This is not the concept of StreetComplete, the quests should be answerable on-the-spot or with minimal walking around (i.e. for a "maxspeed" quest).
But let's say you solve the quest after arriving at the port, then, this info is still only one "experience". For longer distances, the actual duration varies. Also, what's completely out of the picture here is how many times a day the ferry will even go - the waiting time, so to say.

So for long ferry trips, it makes more sense to have this quest on a map for armchair mappers, i.e. on Osmose because to look up the duration (online) on the shipping companies schedule, in the travel guide etc. is definitely the better way.

For short trips, i.e. a trip over the Nord-Ostsee-Kanal at Rendsburg, "duration" is definitely not enough to make the routing engine give a better estimate, because there are also waiting times (the ferry will only go if there are X cars on the deck) and these are actually the deciding factor. So for short ferry routes, it might make sense to ask a user for that, but only if there were a tag where the user could specify the max/the mean waiting time. But the value is not as high as you might think because I'd say that ferries that go over short distances (=over a river) more or less go all by the same speed.

If this ticket is about adding the ferry quest, I will  not close it though, because there are other tags that definitely make sense to ask (is it for cars?).

**Comment by daniel-j-h** [comment]
Agree with your take on ferries :+1:.

It was mostly an example to show the importance / frequency ratio idea behind tags. The same holds e.g. when showing the opening hour and a theoretical bridge max height quest: you probably want to weight the bridge max height higher since its frequency is low but the impact could be high.

**Comment by westnordost** [comment]
Max height for a bridge? Do you mean max weight?

Am 30. März 2017 09:15:40 MESZ schrieb "Daniel J. H." <notifications@github.com>:
>Agree with your take on ferries :+1:.
>
>It was mostly an example to show the importance / frequency ratio idea
>behind tags. The same holds e.g. when showing the opening hour and a
>theoretical bridge max height quest: you probably want to weight the
>bridge max height higher since its frequency is low but the impact
>could be high.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/39#issuecomment-290323391

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by daniel-j-h** [comment]
Sorry I meant tunnels and their max vehicle height constraint.

**Comment by westnordost** [comment]
(This ticket is about adding ferry type quest now)

**Comment by rugk** [comment]
> (This ticket is about adding ferry type quest now)

Really good idea. And @westnordost, there are also smaller ferry routes, often on rivers or so. There such a quest makes some sense.

Bridge max height is tracked in https://github.com/westnordost/StreetComplete/issues/399.

**Comment by rugk** [comment]
BTW the duration is also "highly recommended" according to the wiki as routing engines seem to estimate that thing mostly wrongly.

**Comment by goldfndr** [comment]
#733 has solved the quest marker technical limitation.

**Comment by matkoniecz** [comment]
So this is about adding tags mentioned in the first part of https://wiki.openstreetmap.org/wiki/Tag:route%3Dferry#Tags_to_use_in_combination ? (`motor_vehicle`, `hgv`, `motorcycle`, `foot`, `bicycle` tags)

**Comment by westnordost** [comment]
Yes, though, each should be a yes/no question. I figure that everything except motorcar and foot may be not always answerable. (the surveyor doesn't know)

**Comment by matkoniecz** [comment]
Would you prefer each as a separate quest (maybe even split intop more than one PR) or as a one big quest with toggleable answers?

**Comment by matkoniecz** [comment]
Ask ferry personnel? Though that may be expecting to much and not sure whatever implementing it is worth it given that it would be disabled by default.

**Comment by rugk** [comment]
I guess he/she will usually see some signs stating that. At least for bicycles it should be mentioned. Because actually, the operators of a ferry likely have to make that clear, also with other infos as the service times, etc.

**Comment by matkoniecz** [comment]
There are still `hgv`, `motorcycle`, `bicycle` tags. It may require asking ferry personnel so would be disabled by default.

Would you want such quests? (it should be really easy to implement them, and I will add `bicycle` one in my private version, so I may as well make PR adding it here)

**Comment by westnordost** [comment]
Is the question directed at me or the author of the ticket?

**Comment by matkoniecz** [comment]
@westnordost To you.

**Comment by westnordost** [comment]
Hmm, maybe `hgv` is quite important, for routing and stuff. The others, maybe not for now. May be too much. Never heard of a ferry that will accept cars but not motorcycles, respectively pedestrians but not cars.

(I am remembered of this right now, 4th picture: https://westnordost.de/blog/india/35/about-forgotten-temples  - a pedestrian ferry that takes on motorcycles. Does not seem to exist anymore, or was never mapped: https://www.openstreetmap.org/#map=17/15.34517/76.48819 )

**Comment by HolgerJeromin** [comment]
> respectively pedestrians but not cars

I am pretty sure I ride one of those in the past.

**Comment by westnordost** [comment]
Err right, that part of the sentence didn't make sense. I meant "pedestrians but not bicycles"

**Comment by HolgerJeromin** [comment]
https://www.luehesand.de/f%C3%A4hrplan/

> Es können keine Fahrräder mit auf die Insel genommen werden.

**Comment by mcliquid** [comment]
> Hmm, maybe `hgv` is quite important, for routing and stuff.

@westnordost Before I open a completely new issue based on the question in [#821](https://github.com/Helium314/SCEE/issues/821#issuecomment-3876723621), would the `hgv` ferry quest based on the `AddFerryAccessBicycle` quest be a StreetComplete topic or rather SCEE?
