### ISSUE TITLE
Disable shoulder quest in the UK

### ISSUE THREAD

**Issue by trigpoint** [westnordost/StreetComplete#3975]
In the UK shoulders only exist on motorways and other limited access expressways.

The quest is asking if the exist on rural trunk / primary / secondary and tertiary roads where the answer is always going to be no and has the potential to be very spammy.

Typical rural roads are enclosed by hedges / walls or fences, there is no space for shoulders.

There is often a verge, this would be a useful quest as it is useful information for walkers.

I believe that this quest should be disabled in the UK.

A fairly typical secondary road where this quest is being asked but makes no sense

https://www.mapillary.com/app/?pKey=1350682775316706

**Comment by westnordost** [comment]
E.g. this should satisfy the criteria for a (soft) shoulder: https://www.google.de/maps/@54.4403204,-2.5326497,3a,75y,264.83h,68.05t/data=!3m6!1e1!3m4!1sXR1eI20qq6Ls182lRWat5A!2e0!7i16384!8i8192 - i.e. broad enough for any vehicle to stop beside the roadway.

**Comment by trigpoint** [comment]
> E.g. this should satisfy the criteria for a (soft) shoulder: https://www.google.de/maps/@54.4403204,-2.5326497,3a,75y,264.83h,68.05t/data=!3m6!1e1!3m4!1sXR1eI20qq6Ls182lRWat5A!2e0!7i16384!8i8192 - i.e. broad enough for any vehicle to stop safely beside the roadway.

That is an over manicured verge. Unless there has been a long dry spell, stopping a vehicle on a soft surface would be fool hardy

**Comment by westnordost** [comment]
So is the description of the `shoulder` key on the wiki in need of improvement in your opinion, then? Currently, the wiki page does not mention anything about that a shoulder with a grass surface is not fit as a shoulder because it is too soft.

Also, is there any objective clear definition what would distinguish a (soft) shoulder from a verge? And how to tag a verge? If there is, the shoulder quest could be made into a three-choice quest:
- Yes a shoulder (= broad enough for any vehicle to stop safely on firm surface)
- Just a verge (= not broad enough or not suitable to stop for other reasons)
- Nothing at all

**Comment by SomeoneElseOSM** [comment]
>Currently, the wiki page does not mention anything about that a shoulder with a grass surface is not fit as a shoulder because it is too soft.

The actual problem with the wiki definition is the part you added on 8th January this year:

https://wiki.openstreetmap.org/w/index.php?title=Key:shoulder&diff=prev&oldid=2242200

The previous version https://wiki.openstreetmap.org/w/index.php?title=Key:shoulder&oldid=2091155 reads OK to me (based on the British English definition**, which is what OSM mostly uses).

As an example of something that I would consider a shoulder by this definition, see https://www.google.de/maps/@55.1971484,-7.0141348,3a,75y,56.74h,74.7t/data=!3m6!1e1!3m4!1skeS-WotsQv_4r-Aw_xwLLw!2e0!7i16384!8i8192 (Co donegal, Ireland) or https://www.google.de/maps/@51.9825668,-2.4069653,3a,75y,59.96h,80.17t/data=!3m7!1e1!3m5!1sYysp01Qg4uCN9JEkH9qSBQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DYysp01Qg4uCN9JEkH9qSBQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D301.69537%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192 (M50, England).

Some more that I wouldn't: https://www.google.de/maps/@53.1741372,-1.324842,3a,75y,22.27h,72.49t/data=!3m7!1e1!3m5!1smE7-kFr_JBW9AZk7TWQsPg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DmE7-kFr_JBW9AZk7TWQsPg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D301.76175%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192 (M1, England) and https://www.google.de/maps/@52.8845726,-1.728158,3a,75y,115.91h,84.57t/data=!3m7!1e1!3m5!1s4z1iiqaa09ds-1eNYId62A!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3D4z1iiqaa09ds-1eNYId62A%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D88.08387%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192 (A50, England).

That last one is legal (if not exactly advised) to walk and cycle on, wth the verge being useful for the former and the gap between the painted edge of the carriageway and the verge useful for the latter.

** around the world the definition varies; as the recent discussion in "OSM World" on Discord showed (in some parts of the US, a shoulder seems to be "anything to one side of the road where you are less likely to be run over walking", including verges etc., in other parts not).

**Comment by westnordost** [comment]
The previous version just contained a less precise definition. It's no wonder that the meaning of the `shoulder=*` tag will be interpreted differently by different users if a clear definition is missing. The result usually of an imprecise tag definition is that the de-facto usage of a tag becomes subjective and/or very liberal (i.e. what passes as a shoulder in this case).

The edit was made to document more precisely how the tag is **de-facto** used after some random research. The source is mentioned in the change comment, direct link: https://github.com/streetcomplete/StreetComplete/issues/3613#issuecomment-1007439695

> based on the British English definition**, which is what OSM mostly uses
> [...]
> ** around the world the definition varies; as the recent discussion in "OSM World" on Discord showed (in some parts of the US, a shoulder seems to be "anything to one side of the road where you are less likely to be run over walking", including verges etc., in other parts not).

Well, we surely don't want to have a tag whose meaning drastically and fuzzily changes depending on the country you are in. Hence, the definition must be delivered up-front in the wiki. Now, `shoulder=*` has been in use for many years, so we can't just make up an ideal definition now.

Thus, see my last post.

**Comment by 10992-osm** [comment]
Just my thoughts on the assorted examples:

- https://www.mapillary.com/app/?pKey=1350682775316706: a verge rather than a shoulder: long grass, and a sign in the middle of it.
- https://www.google.de/maps/@54.4403204,-2.5326497,3a,75y,264.83h,68.05t/data=!3m6!1e1!3m4!1sXR1eI20qq6Ls182lRWat5A!2e0!7i16384!8i8192: I think that's a verge: a) it's grassy, but also, there's a kerb, so you'd have to drive up over that onto the grass
- https://www.google.de/maps/@55.1971484,-7.0141348,3a,75y,42.26h,80.66t/data=!3m6!1e1!3m4!1skeS-WotsQv_4r-Aw_xwLLw!2e0!7i16384!8i8192: I'd agree that that's a shoulder
- https://www.google.de/maps/@51.9825668,-2.4069653,3a,75y,59.96h,80.17t/data=!3m7!1e1!3m5!1sYysp01Qg4uCN9JEkH9qSBQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DYysp01Qg4uCN9JEkH9qSBQ%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D301.69537%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192: again, I'd agree that's a shoulder
- https://www.google.de/maps/@53.1741372,-1.324842,3a,75y,342.61h,60.26t/data=!3m7!1e1!3m5!1smE7-kFr_JBW9AZk7TWQsPg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DmE7-kFr_JBW9AZk7TWQsPg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D301.76175%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192: that's fairly obviously not, it's not wide enough, and there's a crash barrier preventing you from getting too far off the road
- https://www.google.de/maps/@52.8845726,-1.728158,3a,80.7y,127.85h,66.59t/data=!3m7!1e1!3m5!1s4z1iiqaa09ds-1eNYId62A!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3D4z1iiqaa09ds-1eNYId62A%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D88.08387%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192: I think it's hard to say: there doesn't appear to be a kerb, the asphalt section isn't wide enough, and there are signs on it, so I suppose it might not be.

[According to the RAC](https://www.rac.co.uk/drive/advice/driving-advice/what-is-the-hard-shoulder/):
> The ‘shoulder’ of a road is the land to the edge of the road. On most roads without pavements, the shoulder is a strip of grass or a hedgerow. This is known as a ‘soft shoulder’.
On a motorway, this strip of land is hardstanding, hence the name ‘hard shoulder.’ In the UK, the hard shoulder has a standard width of 3.3m and is separated from the motorway’s driving lanes by a solid white line.

According to that definition, every single road has a shoulder, as every single road must have some land on either side (perhaps excluding coastal roads or causeways).

[According to Wikipedia](https://en.wikipedia.org/wiki/Shoulder_(road)#United_Kingdom), in the UK:
>Full width hard shoulders are usually provided only on [motorways](https://en.wikipedia.org/wiki/Motorway) and are usually 3.3 metres (11 ft) wide, but there are exceptions. Some motorways do not have hard shoulders at all (for example the [A57(M)](https://en.wikipedia.org/wiki/A57(M)_motorway) and many [smart motorways](https://en.wikipedia.org/wiki/Smart_motorway) where the hard shoulder has been converted into a running lane) and there are a small number of [dual carriageway](https://en.wikipedia.org/wiki/Dual_carriageway) A-roads which do possess hard shoulders (for example, parts of the [A1](https://en.wikipedia.org/wiki/A1_road_(Great_Britain)), [A2](https://en.wikipedia.org/wiki/A2_road_(England)) and [A27](https://en.wikipedia.org/wiki/A27_road)). Hard shoulders are always marked with a reflectorized solid white line which is 20 centimetres (7.9 in) wide and is provided with a [rumble strip](https://en.wikipedia.org/wiki/Rumble_strip). A line of red [cats' eyes](https://en.wikipedia.org/wiki/Cat%27s_eye_(road)) is also used, and is placed to the side of the line.
On many modern non-motorway roads, a hard strip is provided. These are usually 1 metre (3 ft 3 in) wide, and are bounded by thinner solid white lines, and often without a rumble strip.
