### ISSUE TITLE
Support alternative map renderers

### ISSUE THREAD

**Issue by daniel-j-h** [westnordost/StreetComplete#40]
I can see all kinds of rendering artefacts with connected ways, which are probably due to issues in the upstream Tangram render. Do you plan on supporting alternative renderers?

Specifically I would love if you could support Mapbox GL as a native renderer (disclaimer: I work for Mapbox but not on the renderer and my involvement with your app is purely private).

https://www.mapbox.com/android-sdk/

What's your take on this?

If this is out of scope feel free to close this issue - no hard feelings ;)

---

Here are some issues I found after a couple minutes of playing around with the map view

![sc-2](https://cloud.githubusercontent.com/assets/527241/24375839/1b0d05c4-133a-11e7-82e8-b6f5ea189c3d.png)
![sc-1](https://cloud.githubusercontent.com/assets/527241/24375841/1b2d6cb0-133a-11e7-92a0-2e9a54e02f81.png)
![sc-0](https://cloud.githubusercontent.com/assets/527241/24375840/1b28fae0-133a-11e7-8c96-d4c1ee8387c9.png)

**Comment by westnordost** [comment]
Yeah, Tangram-ES is very bleeding edge, there are still many issues with this rendering library.

However, I set for Tangram-ES instead of MapBox early in development [because of this](https://www.mapbox.com/tos/#[TuMSTSwp]). I have no control over what and when the map renderer calls home, which is adverse to my goal to make this app very light on data usage and able to work offline.
To change this now will be a little more effort and since the reason why I didn't choose MapBox is still there as before, I won't switch.

**Comment by daniel-j-h** [comment]
Ah I see your point. Do you see the possibility to add it as a second renderer, though? Not sure if it can be easily abstracted over, I don't have much experience with Android development.

Re. data usage and offline - as far as I know the sdk works fine in offline mode / with offline maps and does not send any telemetry there, and also uses a passive location provider to only piggyback on events.

**Comment by westnordost** [comment]
Not really, enabling and maintaining two renderers is not worth the effort and maintenance work, really.

What might be eligible in the future to split the app into a core component and a map component, the core component could then be used to create StreetComplete plugins for other navigation apps. Just a thought.
