### ISSUE TITLE
Add a "About this quest" button and link to openstreetmap wiki

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#406]
of the used key/tag.

**Comment by westnordost** [comment]
No, doesn't fit into the UX of the app.

**Comment by mnalis** [comment]
Note: this wiki link has since been implemented via the Undo button, see [SC FAQ: How does StreetComplete select the data to be modified, and what exactly does it tag?](https://wiki.openstreetmap.org/wiki/StreetComplete/FAQ#How_does_StreetComplete_select_the_data_to_be_modified,_and_what_exactly_does_it_tag?) for details.
