### ISSUE TITLE
Clarify Phrasing for Building Levels Quest

### ISSUE THREAD

**Issue by jasonharrison** [westnordost/StreetComplete#41]
For the 'how many levels does this building have' quest, perhaps the prompts could be changed to:

Total levels (inclusive roof) => **Total levels (including the roof)** 

Of these, levels in the roof* => **Of these,  how many levels are the roof?**

\* I am not completely sure what is being asked in the second prompt.

**Comment by Monduiz** [comment]
I have posted this in a closed ticket so I will copy it here as it is relevant. 

It can be confusing when adding roofs and basement. The notion of roofs structure is for dedicated mappers. What is important for the general public is building:levels=*. An app like this will appeal to a broader range of users and I would say that its best to keep it simple for them: focusing on the number of floors above ground while avoiding getting the roof into the question.

House -> How many floors above ground? -> 2
bungalow -> How many floors above ground -> 1

A building like the one I am working in would be building:levels=13

For most users, I believe it is easier to understand: number of floors above ground than number of floors inclusive roof.

Great work by the way, the UI is amazing!

**Comment by westnordost** [comment]
For 0.5, you can leave the roof field empty.

However, there is a good reason why the quest also asks for the roof levels and that is because having defined no roof levels at all is being used synonym for "roof:levels=0". So, the app (and other data consumers) have no way to differ between "there is no roof" and "a roof has not been specified yet". So, I put these two values into one quest because the app will never ask you again about it and it will be very hard later to find if there is data missing or if there is no roof.

**Comment by Monduiz** [comment]
I am not sure why the roof needs to be there, but maybe I am missing something. When mapping in OSM, you usually just enter the number of floors above ground. Roof information is something I would leave for a more focused and detailed intervention (iD editor or JOSM).  Why is roof:levels being set to zero when entering the number of floors? If no roof information is entered, the tag should not be present in the "way", right?

tags are added to objects as information is available.

**Comment by johnwhelan** [comment]
The problem is in Ottawa it is very rare to see a level within a roof.  Less than 1% of buildings have them.  So yes from a completeness point of view it is nice to have every option available but from a practical point of view with inexperienced mappers it adds unnecessary complexity and is potentially a source of errors as people misunderstand the questions as at least two people so far have done.

**Comment by Locke** [comment]
> The problem is in Ottawa it is very rare to see a level within a roof. Less than 1% of buildings have them. 

In Germany we have a lot of houses like these: https://commons.wikimedia.org/wiki/File:Hausen-adz-dorfstr-web.jpg

The first and second one would be building:levels=1 and the third one buildings:levels=2. That doesn't reflect their total levels (actually there all about the same size), so it would be wrong to ignore roof:levels. The problem lies in the definition of building:levels to be the levels without the levels in the roof, but as that's how it is defined it would also be wrong to include the upper levels in building:levels.

**Comment by johnwhelan** [comment]
The new wording works well.

Thanks John

**Comment by westnordost** [comment]
Hm? I didn't change anything yet, I think.

**Comment by johnwhelan** [comment]
Oops I skimmed over the (inclusive roof) so strip that out and then if the second line becomes 
how many are in the roof?



Total Levels

how many are in the roof?

and I think that works nicely.

The stumbling block is "inclusive roof" to me its two storeys for the house then does it have a roof if so add one.

John

**Comment by westnordost** [comment]
I added an illustration now
![device-2017-04-08-190057](https://cloud.githubusercontent.com/assets/4661658/24830842/e246512a-1c8d-11e7-8bfa-db47945d59e8.png)
