### ISSUE TITLE
New feature: Stick to GPS

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#429]
Currently when using SC I need to:

1. Press "Follow GPS"
2. Press quest, solve it
3. Press again "Follow GPS"
4. Go to step 1.

The "Sticky" mode would automatically always follow the GPS position after solving a quest.

**Comment by westnordost** [comment]
Hm yes, the current "follow GPS" mode is quite un-sticky, but not sure if your suggestion would be the behavior the user expects.
Let's say the user has GPS on generally but supplements data he remembers from a short walk. Then, he wouldn't want the view to zoom back to his current position every time after he finished solving a quest since he turned "follow GPS" off.

**Comment by Natenom** [comment]
As an option?

For example long pressing the gps button, so for advanced users only?

**Comment by westnordost** [comment]
No, not as an option.

**Comment by westnordost** [comment]
"Follow me" GPS mode is now truly sticky. User needs to click on the location button to escape.

But in that mode, he can still rotate, tilt and zoom the map.

Except if he is in compass mode, then he can only zoom it.
