### ISSUE TITLE
lit=limited for street lighting?

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#430]

**Comment by westnordost** [comment]
What's that?

**Comment by krzyk** [comment]
It was requested also by @ninjamask in https://github.com/westnordost/StreetComplete/issues/84#issuecomment-318269018 and https://github.com/westnordost/StreetComplete/issues/84#issuecomment-318876768 (it exists in [German wiki page for lit key](https://wiki.openstreetmap.org/wiki/DE:Key:lit)).

**Comment by krzyk** [comment]
Would adding `limited` in "Other answers" be enough for this to be useful? Or `hours_off` are needed to make it usable from consumer of `lit` data?

**Comment by Natenom** [comment]
@krzyk Thats what I thought of but forgot to mention it. Adding it to other answers is good. At least you then know that it could happen that lights go off in the middle of the night as I once experienced ... not funny when you are in a village you don't know. Typically at 02:00 AM.

**Comment by westnordost** [comment]
Hm. Wiki pages in other languages should be translations, not add their own stuff. `lit=limited` is used by about 0.1% of all lit ways. This is _really_ insignificant.

**If** anyone is going to extend the quest to include this tag, then:
- only show it in Germany
- name the answer accordingly: "Lantern has a red ring" -> Confirmation dialog, ideally showing a picture (like for the living street confirmation dialog) and explain what this means

**Comment by ninjamask** [comment]
https://de.wikipedia.org/wiki/Laternenring
You can show this quest also for Austria.

**Comment by matkoniecz** [comment]
Maybe it would be better to avoid promoting tags that are not properly documented?

**Comment by rugk** [comment]
Yes, please show [this pic](https://de.wikipedia.org/wiki/Datei:Laternenring.svg) in the answer.

**Comment by 9662** [comment]
> `lit=limited` is used by about 0.1% of all lit ways. This is _really_ insignificant.

That reflects the state of the map, not how many places actually turn off the lights at night.

> **If** anyone is going to extend the quest to include this tag, then:
> 
>     * only show it in Germany and Austria

Nein. Towns and villages in France are also keen on switching the lights off past a certain hour. The current “is lit” quest is useless there.

**Comment by westnordost** [comment]
Are the street lights that are switched off during certain hours marked in any way?

The problem with "limited" is (additionally) that then the question needs to be rephrased from asking for the physical presence of street lamps to be something like "Are there street lamps and are they always on during the night?"

Not only can the latter property always change per city council decision (or otherwise), it also becomes almost impossible to survey unless you know about those red rings: First of all it could only be done at night, and noone is going to sit all night next to street lamps for verification. And the red rings are certainly not an international convention.

**Comment by rugk** [comment]
> Are the street lights that are switched off during certain hours marked in any way?

Two to four comments above yours: https://de.wikipedia.org/wiki/Laternenring (Or was this question only about the situation in France?)

At least in Germany (or, possibly, _only_ in Germany or possibly in DACH area, i.e. Germany, Austria and Switzerland, but I don't know that).

> "Are there street lamps and are they always on during the night?"

Actually that may already be needed, because you have one "other answer" for "automatic lights", i.e. they are also not always on during the night.

> unless you know about those red rings

I think at SC we know how to solve that problem: Obviously, we have to require the user to look for them and have a UI that explains this thing and let's them enter it.
IMHO; if the lamps do not have this thing, the user should add a note or so, i.e. nobody can expect them to know that. That's also why this should not be enabled in countries where these red rings do not exist.

----

However, I see another problem with this quest: At least I often do this quest when traveling at higher speeds than by foot and thus won't look too detailed at the street lamps, but rather just confirm they are there:
As such, they possibly won't even notice that small red ring and just answer "yes" instead of checking the other answers.
However, this issue is already present with the "automatic lights" option, obviously, as this is also not noticeable at the time of day.
Thinking about it, should I open a new issue about that, or is there just nothing we can do about it?

**Comment by 9662** [comment]
> Are the street lights that are switched off during certain hours marked in any way?

![](http://www.sieda.fr/images/missions/eclairage-public/panneau-extinction-1.jpg)

![](http://eclairagepublic.eu/site/wp-content/uploads/2017/04/DSC_8812-B-744x1116.jpg)

![](https://cdn-s-www.leprogres.fr/images/2586CCEE-C633-4227-8287-ED35D159FDCA/LPR_v1_02/des-panneaux-annoncent-le-choix-des-communes-photo-d-archives-remy-perrin-1486672826.jpg)

**Comment by gdt** [comment]
In Massachusetts, US, there is no notion of red rings on streetlights.   Typically streetlights are  always on, and parking lot lights increasingly not, both due to increased light pollution rules, and because LED lights start instantly and therefore being on motion detectors is feasible.

But I agree that absent a country-specific labeling rule, someone using SC can't tell from looking.

**Comment by westnordost** [comment]
@9662 okay, just as I thought, that's not workable from the perspective of verifiability. It is not a property of the lantern(s) themselves (a red ring would be) but of a countywide policy.

I suggest to tag lit streets in these towns simply as "yes" and then maybe add everywhere "lit:conditional=no@(0:00-6:00)" or something. Though, this is going to become messy if the city council decides on different times.

It cannot be conveyed to and not expected of a surveyor that he should go to the city/county limits to check if lights in this city are turned off generally at certain times and then answer "limited" for each and every street lantern.

**Comment by westnordost** [comment]
After reviewing this again, I decided that this should not be implemented in StreetComplete, also not as a PR. The reason is basically that `lit=limited` is a problematic / poorly chosen tag: That a street is not lit during the whole night is a *property of* a lit street and should not form an own category on the same level as `yes` or `no`.

This is problematic because it cannot be assumed that everyone who maps if a street is lit or not (if he or she sees street lights) knows about those red rings (or other markers used in other legislations to mean the same thing) and also knows about that he is supposed to tag them as `limited` instead of `yes`. In other words, it means that many places that are tagged with `lit=yes` now are actually not on during the whole night. In this ticket, from the other examples posted here, we also learned that `lit=limited` is not sufficient anyway to map the situation when light is on an when it is off: In other places, street lights are turned on and off at certain (sometimes signposted) hours.
