### ISSUE TITLE
Use around to find out probably lit ways

### ISSUE THREAD

**Issue by krzyk** [westnordost/StreetComplete#431]
Two ideas that are based on `around`:

1.
If there is a road with `lit=yes`, then it highly probable that roads `around` it might have it also. Overpass query that does this:
```
way[highway][lit=yes]({{bbox}});
way(around:100)["highway"~"primary|secondary|tertiary|unclassified|residential|living_street|service|pedestrian"]({{bbox}});
(._;>;);
out;
```

This would allow to extend the lightning for roads that don't have sidewalks, but are in enough developed parts that have lights at streets.

2. If there is a separate footway/cycleway near given road, it gives high probability that there the road is lit.
```
way["highway"~"footway|cycleway"]({{bbox}});
way(around:100)["highway"~"primary|secondary|tertiary|unclassified|residential|living_street|service|pedestrian"]({{bbox}});
(._;>;);
out;
```

**Comment by westnordost** [comment]
The first idea is intriguing, but does unfortunately not work as you might expect it to, as quests are only downloaded once and kept in cache for some time. The resulting user experience would be quite annoying because to users it looks like every now and then over the course of months, some street light quests are popping up. This is not good.

The second idea might work better, the query should be refined though to include the logic that is in the query right now (paths). Please see the cycleway quest - there is a similar query.

**Comment by krzyk** [comment]
Regarding 1. Isn't that the same for all other quests? E.g. someone adds a sidewalk (in some editor like JOSM/iD) and suddenly users of StreetComplete will see new light quest starting popup.
Or someone adds type of buildings to a district and out of nowhere there are dozens of new house level quests. Similar thing is with quest priority, when you solve some quests with higher priority you will suddently get a lot of lower priority quests.

I'm not sure how this is different from light quest "creeping" mode. As I understand quests are downloaded once every `t`, after `t` passes new quests are downloaded and during this download new quests might appear in area that you previously cleared (because "something" happened, either other OSM contributor did something, or you did, or lower priority quests became available).

**Comment by westnordost** [comment]
>1.

True. Ideally, quest types are ordered in a way that those who require other things to be gathered first have a lower priority. I.e. housenumber quest should have lower priority as building type quest. If the quests are prioritized in this way, the mentioned behavior becomes less notable for users because the auto downloader will only download new quest types once most quests in the vicinity are solved.
