### ISSUE TITLE
O

### ISSUE THREAD

**Issue by chrisdebian** [westnordost/StreetComplete#433]
Hi, all.

I have started to read about different Quality Assurance tools for OSM, here:

http://wiki.openstreetmap.org/wiki/Quality_assurance

Whilst reading, I noticed that one common problem seems to be one way streets that don't go anywhere, meaning they are 'dead ends'. I believe these should be tagged as two way streets. Could this be helped with a quest?

The QA page has many good ideas, to consider.

Thanks,

Chris

**Comment by westnordost** [comment]
Generally, yes, data from QA tools can be used if this data is accessible via an API. If you have a suggestion which data exactly may be used, you can open a ticket for that. [As already mentioned](https://github.com/westnordost/StreetComplete/issues/370#issuecomment-313862880), simply stating the fact that there are quality assurance tools for OSM and that they may have data out of which quests could be created is not specific enough to be of any help for this project.

**Comment by rugk** [comment]
First, next time please use a proper title. Secondly is not this issue rather specific about a "New quest: One-way streets with one end"

As a data source, I think, you could use Overpass as usual, can't you? Then look for streets with one end (i.e. without a junction or so at this end).
Obviously such one-way streets are unlikely to exist as you cannot (legally) drive back when entering them. The point is only, why ask the user if it is so unrealistic? If there is a chance that the user can say "But it is tagged correctly, i.e. it is such a strange street", then this would make sense, but otherwise not…

**Comment by rugk** [comment]
@westnordost Any chance you can use this issue to track a quest suggestion for one-way quests? I also saw you already have an icon for it.
