### ISSUE TITLE
Feature Request: Follow ways for Surface Quest

### ISSUE THREAD

**Issue by mrenvoize** [westnordost/StreetComplete#434]
Often ways are split up into adjoining sections which means you have multiple surface quests adjacent to each other. It would be great if the app could traverse adjacent ways displaying the next logical surface quest on the adjoining way?

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by forteller** [comment]
Yes, please! For some reason the roads in my area are often split into a ton of tiny pieces. And each direction on the same road is asked about separately too. The whole road is the same material! Especially the bigger roads this should be a given.

Thanks!

**Comment by westnordost** [comment]
Sorry, won't implement.

**Comment by mrenvoize** [comment]
Somehow I missed the change to wontfix a few days ago.  Could u get some clarification on why it's a no fix.. To hard, bad idea or another reason perhaps..  Knowing that may encourage or discourage one form having a go at adding such a feature themselves.

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by westnordost** [comment]
Well, I won't accept any PR for that either, so it is irrelevant. Reason:
* surfaces may be different along a stretch of road and user is supposed to check the location himself, so he needs to be there. There is no point in "speeding up" surface quest answering or somehow allowing mass-taggings
* difficult to implement: the app works with single elements, not sets of elements

**Comment by mrenvoize** [comment]
Thanks for that follow-up explanation, it's greatly appreciated.  I may not totally agree with all of it, but I do appreciate your points.

Many thanks

**Comment by forteller** [comment]
I understand why you can't so this, westnordost. I thought of another possibility to make this task less boring and time consuming:

For me at least every time I do this quest I have to 1) click on it 2) click 'paved' 3) scroll down 4) click 'asphalt' 5) click 'ok'. When there's four or five of these quests in one single roundabout and four more in each street leading out of the roundabout it gets quite tedious and demotivating for using the app at all after some time. And I'm sure others feel the same way, meaning we might lose a lot of contributers because of this.

So my two alternative suggestions I hope you will consider:

1a) Would it be possible for the app to learn which 1-2 alternative(s) I use the most and give me a one click option to select that alternative? Let's say I've finished 20 surface quests and in 18 of them I've chosen asphalt. Then the next time I open a quest like this asphalt could be already selected for me. So that the process would look like this: 1) click on quest 2) click 'ok' (or select some other surface . That would help a lot!

1b) Maybe more logical: Preselect the previous surface. You wouldn't have to learn or figure out what I select most often, just preselect the same surface as I selected last time. Most likely the roads close to each other have the same surface.

2) Alternatively: Maybe it would be possible to say to the app: All the surface quests visible on my screen right now, select this surface for all of them. This might be more difficult to implement.

And, as always: Thank you for your fantastic work on this great app! I used it quite a lot yesterday and then went home and recommended it to my Twitter followers :)
