### ISSUE TITLE
Feature: Mark a Object as deleted

### ISSUE THREAD

**Issue by cyper85** [westnordost/StreetComplete#459]
Sometimes I have a quest (opening_hours for shops or capacity for bicycle_parking) for an object that doesn't exists anymore.

I think it's not a good Idea to delete it directly, but maybe you can add a Button, that create a note and remove the quest for this object from your database?

**Comment by westnordost** [comment]
In this case, answer with "Can't answer" -> you will be prompted to leave a note and describe why it can't be answered. That the quest is invalid because the object does not exist anymore is a typical use case for this and works very similar to what you describe: Other quests for an object are not shown when there is a note for that object.

P.S: There is no database. The app works directly with openstreetmap overpass queries.
