### ISSUE TITLE
Ability to create private note and/or osm note

### ISSUE THREAD

**Issue by Natenom** [westnordost/StreetComplete#47]
For example today I saw that there was nothing while the map showed me a street. Would be nice if I could create a note for myself and/or for osm in such a case.

**Comment by westnordost** [comment]
You mean there was a road on the map, even though in reality there was none?

Instead of answering a quest, you can create a note instead for each quest.

**Comment by Natenom** [comment]
1. Yepp. Found another non existing street today.
2. Adding a note instead of answering the quest is ok.
But I would also like an option to create a (private) note anywhere on the map in a case where I would like to add something missing to OSM.

**Comment by westnordost** [comment]
This sounds like a reasonable option for experienced OSM users.

**Comment by claudiush** [comment]
This is becoming more and more important for me as well as I observed in my usage. Two scenarios I see:

1. While solving unrelated StreetComplete quests I discover something else that needs updating (closed street/shop, construction landuse)
1.  While solving StreetComplete quests I discover that the object needs a different aspect updating.

For the second scenario I had multiple cases of the following:

- While performing the "bus stop shelter?" quest I found 4 stops that don't exist at all any longer.

- While performing the "opening hours" quest I found multiple shops that changed name and type in London.
I think the _"Cannot answer" -> "Add Note"_ flow is too well hidden here. Maybe expose this already one option higher and have the button say _"Cannot answer / add note"_ ?
And for the more power advanced user a long press on the map to create a note would make StreetComplete make an even better basic survey tool.

**Comment by matkoniecz** [comment]
> While performing the "bus stop shelter?" quest I found 4 stops that don't exist at all any longer.

For objects where quest object that was supposed to be made more detailed is gone (like bus stop in your case) solution is simple - use "can't say" and open note with "bus stop is gone".

Or, what is for me preferable - use Vespucci to edit on spot.

For objects where both quest can be done and note created and cases where just note should be mode - yes, that would be very useful (missing streets, missing building, demolished buildings, moved bus stops etc)

**Comment by CloCkWeRX** [comment]
Shifted from #281

Mockup
 * Select 'new note' control, which shows a crosshair or similar to precisely locate it
 * Key in details
 * Save/publish

![image](https://cloud.githubusercontent.com/assets/365751/26766908/32901c56-49d9-11e7-84c1-d1aaea47b832.png)

![image](https://cloud.githubusercontent.com/assets/365751/26766962/ee34cede-49d9-11e7-8fd4-60a27aa849c0.png)

It would possibly solve the 'I made a mistake' case; as well as "I'm looking at something, but not being prompted to add it"

Obviously warrants better icon than "New Note"

**Comment by ENT8R** [comment]
I thought about implementing this feature in the next time. But before I will do this I have some questions:
- Is it right that this feature should be only for experienced users (so you have to enable an "expert mode" in the settings)?
- Is it better to have a button somewhere in the menu which opens something like a crosshair to locate the position of the note or just long-press on the location where the note should be?

**Comment by westnordost** [comment]
**In reality, there are two features here. We need to distinguish these in the discussion.**
1. Ability to leave a note anywhere
2. Ability to have private notes (and export these to GPX)

Why having (1) makes sense is apparent. That would, in my opinion, not be an expert feature.

For (2), the target group of this feature, would be experienced users who want to solve their own notes later when they are back at home with JOSM, iD etc. So, the ability to create private notes should not be visible by default, because the default user will not know what to do with private notes. For starters, I guess a single option in the settings should enable/disable this feature. Later on, when there are possibly more expert features, it could be put into a whole sub-settings which as a whole is activatable with one click.

I'd imagine that there would be an additional button or checkbox on all note-creation dialogs that lets the user choose whether to create a public note or a private note.

The private notes should be exportable as a GPX file, so that they can be easily put into JOSM. I think the easiest way, which also does not require any additional permissions, is to send it via email. 

Anyhow, (1) is I guess the more obvious thing in terms of usefulness. It is also easier to implement, as the whole local database stuff for creating notes already exists.

In terms of UX, I do not like the long-press. I used OruxMaps a long time for OSM survey, and I hated that. Instead, a separate button with the ability to move the marker (by moving the map) I find better.
But well, perhaps that is a matter of taste. I would say this is open for discussion. The problem with the button, by the way, is, that it will not fit onto the screen on landscape mode for smaller smartphones.

**Comment by ENT8R** [comment]
> The problem with the button, by the way, is, that it will not fit onto the screen on landscape mode for smaller smartphones.

Why don't put the button into the menu at the upper right corner?

**Comment by ENT8R** [comment]
> I think the easiest way, which also does not require any additional permissions, is to send it via email.

You mean that the application should open the default email program with the file as an attachment and the user just has to enter the recipient and press send?

**Comment by ENT8R** [comment]
And for the private notes:
Should the private notes be displayed on the map like any other note too?

**Comment by westnordost** [comment]
> Why don't put the button into the menu at the upper right corner?

Because that'd be one click more, wouldn't it?

> Email

Yes.

> Private notes in general

I think the implementation of private notes should be done separately (later), actually. Regarding the specific question: Well, if they are displayed, they should look distinguishable from the other markers because they are a very different thing. I.e. just dots, or a different shape of marker etc.

**Comment by ENT8R** [comment]
> Because that'd be one click more, wouldn't it?

Yes, it would be, but I think this is not so bad...

**Comment by rugk** [comment]
> I think the implementation of private notes should be done separately (later), actually. 

👍 , also "sending/sharing/exporting notes". The main feature would just be to create public notes.

> In terms of UX, I do not like the long-press.

Just my point: I think that would be a nice thing for the UX. 1. Because "creating notes" is always an "expert feature", as the "usual user" should use StreetComplete just to complete quests and not do such a stuff. 2. One you know how to do it (either you discover it or read it somewhere – so maybe put a tip somewhere!) it is quite easy to use, you do not need 2 clicks or so and it (as an expert feature) wastes no space in the UI.
BTW users using OsmAnd may also be familiar with long-tapping on things, so you can expect that user discover this.

**Comment by ENT8R** [comment]
Currently it looks like this:
<img src="https://user-images.githubusercontent.com/25306497/33233485-d6db795c-d216-11e7-8f44-d62ff51fee0c.png" width="300px"> <img src="https://user-images.githubusercontent.com/25306497/33233486-d6fdaa9a-d216-11e7-97a0-2d83e457bd43.png" width="300px">

**Comment by rugk** [comment]
Hmm… but that required two taps. 😞

**Comment by ENT8R** [comment]
I can change this if this is really wanted... Just want to make sure that I don't implement something which is considered bad...
