### ISSUE TITLE
advisory speed limits

### ISSUE THREAD

**Issue by elgaard** [westnordost/StreetComplete#470]
I would like a way to set maxspeed:advisory. There are a lot of 30 and 40 km/h advisory zones in Denmark.
I realize that it not easy to decide where it is missing. But when setting a speed limit, it could be possible to mark it as advisory (the blue zone sign, instead of the red one).

The maxspeed tag would then still be missing. In most cases here it would be dk:urban=50, but it I think there could be cases of maxspeed=40, maxspeed:advisory=30
So there should still be a quest for maxspeed if maxspeed:advisory is set.

A lot of roads are incorrectly tagged with maxspeed set to the advisory limit. Having SC users choose between blue and red signs would help a lot.

**Comment by chrisdebian** [comment]
That sounds like a good way to improve things, and I guess it would be easy
for most people to tell the difference between a red and blue sign.

Chris.

**Comment by westnordost** [comment]
I'd say it could be implemented as a "Other answers..." option "There is an advisory speed limit". 
When selected, the sign displayed in the form turns blue and instead of maxspeed, maxspeed:advisory is tagged. Since I do not think an advisory speed limit sign is ever accompanied by a normal speed limit sign, I think the quest should not ask the user about this and thus not tag source:maxspeed. The quest then does not turn up for streets which have a maxspeed:advisory set as well.

This needs some research though in which countries the concept of advisory speed limit exist and how they look. (I.e. speed limit signs in the US and Canada look very different than in other parts of the world, the concept of living streets mostly only exists in Europe, Russia, Southern Africa and Australia)

**Comment by Binnette** [comment]
It seems that a lot of coutries are concerned : [WP:Advisory speed limit](https://en.wikipedia.org/wiki/Advisory_speed_limit)

Map of OSM nodes/ways with maxspeed:advisory : [maxspeed:advisory#map](https://taginfo.openstreetmap.org/keys/maxspeed:advisory#map)

In france we have this kind of sign : [WP:vitesse conseillée](https://fr.wikipedia.org/wiki/Panneau_routier_d%27indication_de_vitesse_conseill%C3%A9e_en_France)

**Comment by westnordost** [comment]
> The signage for advisory speed limits is not defined by the Vienna Convention on Road Signs and Signals, and is therefore not standardised internationally.

Uhm, this sounds like a lot of work. So, whoever reads this and wants to help: 

From the source posted by @Binnette and other sources, identify clusters of similar-looking advisory speed limit signs for each country and create a simple list of country iso code -> typical/rough appearance. 

I did a similar thing for living streets:
1. [The list](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/livingStreetSign.yml)
2. The pictures: [European style](https://github.com/westnordost/StreetComplete/blob/master/res/living_street.svg), [Australian/New Zealand style](https://github.com/westnordost/StreetComplete/blob/master/res/living_street_australia.svg), [Russian style](https://github.com/westnordost/StreetComplete/blob/master/res/living_street_russian.svg)
![Russian style](https://raw.githubusercontent.com/westnordost/StreetComplete/master/res/living_street_russian.svg)

**Comment by rugk** [comment]
I'll do.

**Comment by westnordost** [comment]
Cool!

But, one thing after another? I'd like to finish up the orchard branch first. That the per-area-data is used is not necessary for the initial version, the data can be always updated later. But the pictures is (the last thing that is still) missing.

**Comment by rugk** [comment]
No multitasking. :wink:  Also just looking for data here, PR for data and images will come…

**Comment by westnordost** [comment]
Added (for v2)
