### ISSUE TITLE
Add housenumber quest should be disabled for the Netherlands

### ISSUE THREAD

**Issue by akudzo** [westnordost/StreetComplete#476]
In the Netherlands, address and building data is imported from official government sources. Addresses should be tagged as nodes, and should not be part of the building. Updates are provided based on the official government data as well. Users are strongly discouraged to manually add address nodes.
Therefore StreetComplete should not offer the add-housenumber quest in the Netherlands. Would it be possible to disable this quest in the Netherlands?
The update procedure is available [here](https://wiki.openstreetmap.org/wiki/NL:BAG#Updaten), unfortunately it's only available in Dutch.

**Comment by westnordost** [comment]
Technically it is absolutely doable, no problem.
Though, since this would be the first quest with a black list of countries, this requires a bit of work to make this halfway performant. In other words, it will not find its way in the v1 release. Just so you know.
Do you have a link to the wiki somewhere where this is being officially stated (or another source)? (After all, if it is strongly discouraged, then it should be also in the wiki)

Probably then this quest should be disabled for Norway as well, I think they do it the same. (Or was it Sweden?) Though, a request to blacklist that country vanished after I explained the following:

One thing you should note: StreetComplete only displays quests for buildings that likely have housenumbers (residential,house,apartments,commercial,...), so not for building=yes. **Additionally**, if there is a node with a housenumber inside or on the edge of a building, then, no quest is displayed. So, if the imported housenumber data is precise, then no quests should be shown in the Netherlands. If it is not precise (i.e. the housenumber node is beside the building), then, IMO, this warrants fixing the imported data.

So, what do you say?

**Comment by rindlerblabla** [comment]
#229 is the other issue (concerning Norway).

**Comment by akudzo** [comment]
You can find the import decision [here](http://wiki.openstreetmap.org/wiki/BAGimport#Import_decisions_for_BAG). Unfortunately the wiki doesn't reflect the current situation very well. The main reason for importing addresses as nodes is because the addresses in the dataset are within 5 meters of the entrance. 
The current practice for adding addresses is asking for an import [here](https://forum.openstreetmap.org/viewtopic.php?id=52973). This way, the building outline and postal code can be added or updated as well. 
Because of your filter for specific types of buildings without an address, this quest is rarely displayed in the Netherlands. Therefore it isn't such a big issue at the moment. However, to keep the data up-to-date, complete and consistent with other available address data, we ask editors to request an import instead of adding address data manually.

**Comment by westnordost** [comment]
OK, I will work on excluding Netherlands (and Norway).

**Comment by matkoniecz** [comment]
> and Norway

Why Norway? #229 has no link to anything that would document manual address mapping as a poor idea.

**Comment by matkoniecz** [comment]
@akudzo Can you document ban on manual address mapping on wiki? Probably https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources is a good place

**Comment by westnordost** [comment]
#535

**Comment by westnordost** [comment]
https://forum.openstreetmap.org/viewtopic.php?pid=671650#p671650

**Comment by westnordost** [comment]
So I disabled the quest for Netherlands, Norway, Denmark and Czech Republic.

I am currently waiting for final confirmation regarding Czech Republic and also for Slovakia. Then this ticket can be closed.
