### ISSUE TITLE
New quest: tracktype for smaller tracks/ways

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#487]
In https://github.com/westnordost/StreetComplete/issues/38 @westnordost said:
> At least […]track type[…][ is on my list.]

:+1: for [tracktype](https://wiki.openstreetmap.org/wiki/Key:tracktype). It is as far as I see only useful for smaller tracks or paths, so reasonable as it is not asked for bigger streets or footpaths or so.
Mostly useful in forests when wandering.

I thought it is a good idea to open a new issue for that thing, as https://github.com/westnordost/StreetComplete/issues/38 is more or less a "meta issue".

**Comment by rugk** [comment]
BTW: Also pay attention to a special [type of a way](https://wiki.openstreetmap.org/wiki/DE:Key:tracktype#Besonderheiten) (concrete lanes, see [picture](https://wiki.openstreetmap.org/wiki/File:Concrete_lanes.png)), which seems to be only used/famous in Germany, as it is not shown in the English wiki.

**Comment by westnordost** [comment]
Perhaps @Natenom might be interested in searching for good photos for this?

**Comment by Natenom** [comment]
There are tracks of all grades available here. I will do different photos.

**Comment by Natenom** [comment]
I searched in my photo collection and found some images that may suit according the the linked wiki page about track types.

Uploaded them to a static generated gallery and will update this gallery when created new photos. Have also full resolutions versions of the images locally.

Most of them until now would be grade1, the last one could be grade2 or 3.

Do you want vertical or horizontal photos? @westnordost

If those images are not what you need at all please tell me exactly what you need :)

See the gallery at https://files.natenom.com/nidx/nobackup/tracks/

**Comment by westnordost** [comment]
The photos will probably be cropped to be square. Guidelines for best photo selection:
* final resolution (after cropping) should be at least 384x384 or larger (see below)
* track should be straight
* track should be as generic as possible: usable internationally, usable both for forest-tracks and farmland-tracks, not too specific about the surface
* ideally, the surroundings of each photo look similar, only the track type differs
* usually I prefer pictures taken while it is cloudy because direct sun creates too much contrast

I am not sure about the final layout yet. Perhaps it is too much text (in [German](https://wiki.openstreetmap.org/wiki/DE:Key:tracktype) for the typical tiled image select with three items per row. Perhaps there should be only two items per row and each image 50% broader.

**Comment by rugk** [comment]
Maybe add that photo guidelines to the wiki here?
Also could you maybe open the wiki for everyone to edit (it's in the repo settings)? Then I could add that too.

**Comment by Natenom** [comment]
So instead of creating more own photographs I tried to find some.

I used the same website which one of the used images is from

So here is the list:

Grade1:
* https://pixabay.com/en/away-road-landscape-target-just-1422212/
* https://pixabay.com/en/sky-road-landscape-mountain-grass-2236892/

Grade2:
* https://pixabay.com/en/away-lane-nature-landscape-way-1378960/
* https://pixabay.com/en/lane-away-landscape-nature-456715/
* https://pixabay.com/en/heydt-saarbruecken-hiking-trail-839456/
* https://pixabay.com/en/away-lane-trail-landscape-way-2661557/

Grade3 and higher (from this grade it is very difficult for me to decide whether it is 3, 4 or 5)
* https://pixabay.com/en/field-away-nature-meadow-lane-406183/
* https://pixabay.com/en/away-lane-trail-landscape-way-2661557/
* https://pixabay.com/en/rac%C5%82awice-poland-landscape-1487430/
* https://pixabay.com/en/path-dusty-road-dust-travel-1700531/
* https://pixabay.com/en/way-field-the-path-fields-village-2527899/
* https://pixabay.com/en/away-lane-trail-fence-infinite-2486366/
* https://pixabay.com/en/mountains-landscape-trail-way-885342/
* https://pixabay.com/en/building-way-bicycles-tree-sky-1694698/

**Comment by westnordost** [comment]
Hm, well. I think the photos from the wiki are in general good to represent their track type. Only, these do not have a good resolution. Some more guidelines to sort out pics that do not fit well:

- the photos should not have any filters applied (in particular depth of field blur, high dynamic range and/or other artistic filters)
- the photos should all show the same perspective, as said earlier: _"ideally, the surroundings of each photo look similar, only the track type differs"_. 

In general, I don't want to confuse you too much. The most important thing is that the photos visually fit to each other. If you made own photos, then they already do, as they come from the same camera etc.

**Comment by matkoniecz** [comment]
Some potentially useful images are also now in https://github.com/westnordost/StreetComplete/compare/master...ENT8R:tracktype

**Comment by ENT8R** [comment]
Oh... I created this quest some time ago for testing [my tool](https://github.com/ENT8R/StreetCompleteQuestCreator). If it is wanted I can search the sources of the images and create a PR for that.

**Comment by rugk** [comment]
Please do. Why did not you already create an upstream PR for that? This issue here, likely, already existed, did not it?

**Comment by ENT8R** [comment]
Yes, it already existed but I thought this maybe needs some adjustments... I will make a PR.

**Comment by matkoniecz** [comment]
@ENT8R For grade5 image I would expect something more overgrown, something like https://commons.wikimedia.org/wiki/File:Overgrown_Road_-_geograph.org.uk_-_206865.jpg or https://commons.wikimedia.org/wiki/File:Zandpad_aan_buitenkant_van_het_gebied._Locatie,_Stuttebosch_in_de_lendevallei._Provincie_Friesland_01.jpg or maybe https://commons.wikimedia.org/wiki/File:Zandpad_aan_buitenkant_van_het_gebied._Locatie,_Stuttebosch_in_de_lendevallei._Provincie_Friesland_01.jpg

**Comment by goldfndr** [comment]
@matkoniecz those last two are the same, did you intend a different one?

**Comment by matkoniecz** [comment]
I don't remember now - maybe I lost one, maybe not. I will edit post to remove duplicate.
