### ISSUE TITLE
Road names

### ISSUE THREAD

**Issue by robybully** [westnordost/StreetComplete#5]
Consider only to ask for names of highway=residential.
On other streets like highway=unclassified this could lead to bad inputs from unqualified users. "Has no name" may be too often the best answer in this cases.

**Comment by westnordost** [comment]
I only ask for names of roads that **neither** have a `name `**nor** have a `ref`. Wouldn't unclassified, tertiary, secondary and primary roads have a `ref` instead of a name?

**Comment by robybully** [comment]
All this roads can have a name of course. 
Mostly living_streets, residentials, bicycle_roads and pedestrians have names. All other may lead to confusion and bad answers.

If you ask for "name" for a primary road, then outside of a city the "name" may be the wrong attribute ans a "ref" may be best.

Why I opened this issue? Because when I open StreetComplete I see a lot of street name questions around my town. Most of this ways are lower than tertiary (width with 1,5 lanes) and have neither a ref nor a name. So 99% of the questions can be answered with "Has no name".

**Comment by gdt** [comment]
There is the name/ref confusion.  But in the US highway=unclassified almost always have names.   It's really highway=service that do not have names.  (I realize other countries may be different.)

**Comment by westnordost** [comment]
Hmm, I am reluctant to remove "primary|secondary|tertiary|unclassified|road" from the recipe. It seems odd to ask for all the residential roads, but leave out the most important road.

But I totally get your point.

On the countryside, most roads will have no name but a ref(, perhaps except unclassified). However, there is no simple way to find out if an area is in the countryside or in the city. 

If you say that in your country, many unclassified roads do not have a name, perhaps I could implement country-filters for quests. So that in your country, the quest does not ask for names of unclassified roads.

There is a rudimentary country-detection in place already. Depending on in which country you are, the "Add Road Name" form automatically expands abbreviations while you type. I.e. if you are in Turkey and type "Turanlı Sk", it expands it to "Turanlı Sokak". :-) (Sorry to brag, I am just so proud of this feature,... it works in every country!)

 So, may I ask where you are from?

**Comment by gdt** [comment]
In thinking about this, I think the core issue is that depending on locale (and perhaps not just country, but more), certain kinds of roads will tend not to have names, and certain kinds will.  So I wonder if you can for each road category, ask if at least 80% of the category has some feature, and then enable the quest.

**Comment by AndrewBuck** [comment]
There is also the [noname key](http://wiki.openstreetmap.org/wiki/Key:noname) which is something that could be useful as an option.  I haven't been able to see what the form looks like when you click a road since the app crashes when I do that (I have an old tablet so it may just be out of date libraries or something).  If a road really doesn't have a name though, you could have a button to allow the user to state this explicitely as well as to add possibly other tags as well for why it might not.

So for example in your query listed above you search for service roads that don't have service=alley on them.  However many of the service roads really should have this tag, it is just missing from the database.  So if the user clicks the noname button for one of those they get a 'reason' window that pops up that has options like 'simply has no name' or 'is an alleyway' or 'is a dirveway', etc.  The reasons would have to be somewhat context specific, so you don't show the 'is an alleyway' reason if the road is something other than service, etc.  Depending on what reason was chosen the app will add appropriate tags like noname=yes and/or other tags that indicate more specific information.

**Comment by westnordost** [comment]
Could you open another bug for the crash? The app should run on Android 4.2 or higher, if not, it is a bug. These [crashes] are exactly the thing I want to find in the early betatest.

Regarding noname: Yes, you can answer that the road has no name, there will be a confirmation dialog, warning that any street in which there are houses normally have a name.
I plan to add answers like "it is not a proper street" -> because: "its a service road", "its a link between roads", ... later.

**Comment by westnordost** [comment]
I actually added it now already. This is all I can do for now regarding covering more cases in "Add road name" quests, the thing suggested by @robobully would take more intelligent behavior of the app to solve, this is not on the roadmap yet.

**Comment by althio** [comment]
I think the road name quest needs a warning/better text about the confusion name/ref.
Or maybe it could provide a choice to fill in name or ref or both.

**Comment by westnordost** [comment]
The problem with ref: Streets will probably only have a (visible) ref outside of the city. The app has no way of finding if you are in a city or not.

**Comment by althio** [comment]
My suggestions would be:
1. other wording: when asking for name only
>What is the name of this road?
as written on the street sign, abbreviations are expanded:

could be replaced by
> What is the **real name** (_not a reference_) of this road?
name as written on signs, abbreviations will be expanded:

2. and/or ask always for name & ref together

3. and/or try a proxy for rural/urban with tags (road type + maxspeed...), for instance, rough idea:
 - ask name, not ref,  if maxspeed < 40
 - ask name and ref if 40 < maxspeed < 60 or maxspeed unset
 - ask ref, not name, if maxpeed > 60
