### ISSUE TITLE
source:maxspeed=sign

### ISSUE THREAD

**Issue by hsimpson00** [westnordost/StreetComplete#515]
Hi,

the app puts a source:maxspeed=sign automatically, when you answer the maxspeed-question with a concrete maxspeed.

This leads to the situation, that many users may answer this question for example for roads inside a town, whith the korrwet maxspeed of 50km/h (in germany), because they don't understand, that this question only asks for explicit maxspeed-signs.

So there will be many roads with an incorrect source:maxspeed=sign!

To avoid this problem, you could set up a multi-level question:
1.: Is there an explicit sign for the maxspeed on this road or ist this road part of an explicit maxspeed-zone?
If answered with yes: Use the same overlay to ask for the maxspeed that you use right now
If answered with no:
2.: Is the road in a urban or a rural zone? (You can also ask for other zones like the "Verkehrsberuhigter Bereich" in Germany)(maybe it's better to ask this question via pictures)
Optional: 3. What is the implicite maxspeed of this road? (I would aks this question, but there are mappers who don't like this)

Please change this soon, so there won't be too many wrong source:maxspeed

Regards

**Comment by rugk** [comment]
You can already select "Other answer" -> "There is no sign" and after confirmation StreetComplete will then ask – if necessary –, whether this is rural or not.
IMHO this is quite straightforward and I did it correctly from the beginning (without knowing how it works). So for me it was intuitive, especially as the image you see is **actually** a street sign as you might see it on the street. So that should be an indicator for you to tap on "Other answers".

However, I have one tip: Currently the question is "What is the speed limit on this street?" – It should maybe better ask "What street limit sign is there limiting the speed on this street?". That is a bit long, however.

Also "Verkehrsberuhigter Bereich" (en: [living street](https://en.wikipedia.org/wiki/Living_street#Around_the_world)) is already implemented. In the "other answers" section, too.

**Comment by rugk** [comment]
BTW this was also already discussed when adding the quest in https://github.com/westnordost/StreetComplete/issues/457.

**Comment by hsimpson00** [comment]
The point is, that you are first asked "What is the maxspeed of this road?" If there is a correct answer (for example 50 on urban roads), it doesn't seem to be wrong to answer with 50. And if you do so, the case is closed and there are no more questions.

When I tried this, I saw the option "no sign", but I didn't choose this, because I was able to answer the question without this option. And I wasn't even shure about the meaning of "no sign".

So if this is the way how to add a correct urban- or rural-limit (which are very common), maybe you shouldnt hide it behind a "more options" menu? Or maybe ask afterwards, where you got the information of the maxspeed (possible answers: "There is a sign" or "General maxspeed on urban/rural roads")?

However, for me it wasn't intuitive :)

Regards

**Comment by rugk** [comment]
"no sign" means you do not see any sign. What exactly is not clear about that?

As it has been discussed before quests should only ask one question, so I assume @westnordost will reject such a change.
So what do you think about my minor change adn leaving the quest as it it currently?
> Currently the question is "What is the speed limit on this street?" – It should maybe better ask "What street limit sign is there limiting the speed on this street?". That is a bit long, however.

**Comment by hsimpson00** [comment]
There is a huge difference between there is no sign and i cannot see any sign...

I think your change would make it more clear what is exactly asked.

Regards

**Comment by westnordost** [comment]
Ok, so the wording should be clearer. The quest should explicitly ask for the **sign**.

**Comment by westnordost** [comment]
Hey, wait a moment, the wording **_is_** clear! It says _"What is the speed limit **sign** for this street?"_

Only in German, the sign is not explicitly mentioned _"Was ist die Höchstgeschwindigkeit für diese Straße?"_.

I slightly improved the wording in POEditor.

**Comment by rugk** [comment]
However, we have to think about the length of that question. Especially when also implementing https://github.com/westnordost/StreetComplete/issues/518, the question could become really long.
I mean in English you have contact clauses and so one and you may be able to describe it with few words, but think about German or so… 😑 ("Welches Geschwindigkeitslimit steht auf dem Schild der Straße Beispielstraße XY?")

**Comment by rugk** [comment]
Ha, bad translator…

**Comment by hsimpson00** [comment]
Haha very nice :)
Maybe "Gibt es an dieser Straße ein Schild für die Geschwindigkeit?"

**Comment by rugk** [comment]
@HolgerJeromin You can join the translation team at [POEditor](https://poeditor.com/join/project/IE4GC127Ki), so there you can discuss such things or change the strings. 👍

**Comment by HolgerJeromin** [comment]
@rugk It took me a while to detect, that you wanted to ping @hsimpson00 and not me :-)

Thanks for changing the wording. I entered some default 50 km/h in Germany without knowing there exists a further other solution in other.

**Comment by rugk** [comment]
Uuups, … no idea where I got the alias. :smiley:

**Comment by gileri** [comment]
With the current wording/UI many quest answers are incorrect in France, as often maxspeed is implicit and do not require maxspeed signs. However, as the UI is biased towards sign-based speed limits, both new and seasoned users are using the default choice without checking the "other options".

At least half of [those ways](http://overpass-turbo.eu/s/z70) shouldn't have maxspeed_type=sign, as 50 kph/kmh is the default speed limit in urban areas, so those ways don't have a sign.

I believe displaying both implicit and explicit maxspeeds choices equally would reduce errors, while not impeding input. Here is an [UI mockup](https://i.imgur.com/asQFkgp.png).

**Comment by westnordost** [comment]
Maybe it is a translation issue. The quest clearly asks for a sign.

You UI mockup is interesting. However, for the two center options, no speed limit should actually be entered, so this is a bit confusing. There have been some iterations already on how to place the answer options (specifically for when there is no sign), so I'd only consider to topple that over again if a new proposed solution would be significantly better. With your suggestion, I fear I do not see that, because while it may solve the low visibility of the "no sign" answer, it creates other UI problems (as mentioned).

**Comment by gileri** [comment]
Some people like you know the quest and what is meant in term resulting tags, and would not make such mistakes, but as evidenced by the Overpass query I sent above, this is not the case for a lot of contributions. So I think we can agree that something need to be done to address this issue.

In french and english at least, the problem does not stem from a bad translation and the "sign UI" and title of the quest both suggest that the speed limit must come from a sign.
However as I said, the quest allow both implicit and explicit maxspeeds, while defaulting to sign-based, and discourage implicit speed limits mapping through 4 additonal user actions including 1 confirmation popup.

The current UI has the same "problem" as my mockup, you are invited to input the numeric speed limit value before choosing "Other answers". As often in France, implicit speed limits are mapped with both maxspeed=* and (maxspeed:source=* or maxspeed_type=*), so I would have expected to be required to enter the numeric value.

If entering the numeric value and selecting "implicit speed limit" is an issue, then disabling and blanking the numeric input [like this](https://imgur.com/a/k735a9G) could work I think.

**Comment by westnordost** [comment]
But what if the user entered a value there before? I'd rather not have the sign appear then at all, but as I said, this may confuse users. By the way, if he user selects "it is a living street" or "it is a zone", the image on the left could be replaced to show how the sign looks like, that would be quite nice.

Another more generic solution I have been thinking about for some time would be to fully use the space in the bottom bar, i.e. have "no sign" appear between "OK" and "Other answers...".

I'll reopen this because as you say, it is an issue, independent of whether we can agree on a solution or not.

**Comment by gileri** [comment]
How would [that](https://imgur.com/a/e4Ayltd) do ?

**Comment by westnordost** [comment]
Right, that makes sense. However, regarding implicit speed limits, I fear it is more complicated than that, depending on the country one is in

**Comment by westnordost** [comment]
@gileri Could you please create a new ticket and add those mockups of yours there as images? We can then think about how solve the thing about how to deal with the "implicit" case.
This ticket got a bit long and was initially about something slightly different.

**Comment by gileri** [comment]
I think the first post and its answer are spot on the issue I'm mentionning and trying to address.

But sure I can open another issue if that helps.
