### ISSUE TITLE
How accessible is this app?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#520]
In StreetComplete there are many quests about accessibility (wheelchair, blind people), but how accessible is the app actually?

I don't know much about it so I am just linking to the [Android site](https://developer.android.com/guide/topics/ui/accessibility/index.html), but I assume screen readers and such things are possible. There are common concepts for the web, whcih I'll just assume here too.

The most obvious example I see are the quest icons: Do they have an alternative text describing the image? If not, then I can provide them, because I actually already write them for [the wiki](https://github.com/westnordost/StreetComplete/issues/477).

**Comment by westnordost** [comment]
They can't have an alternative text because they are part of the map view. The map view is a black box, in that matter. So, don't bother. A version of this app for blind people **does not make sense**, because you need eyes to do a survey.

**Comment by rugk** [comment]
I am very sure blind people are very likely to not like that statement that the app does not make sense for them. Sure, maybe they cannot answer some quests, but others, especially the ones that affect themselves, can maybe answered better by them than by anyone else. Of course, I am talking about the tactile quests here…

Also accessibility is not only about blind people. Quoting Android docs:
> Common disabilities that affect a person's use of an Android device include blindness or low vision, color blindness, deafness or impaired hearing, and restricted motor skills. When you develop apps with accessibility in mind, you make the user experience better not only for users with these disabilities, but also for all of your other users. 

But to keep the discussion short: My main idea was the alternative text, you said it is not possible, so I also see no reason to keep it open anymore, unless someone else finds a problem with the app in this way. 😃

**Comment by chrisdebian** [comment]
rugk,

I don't know how this would be technically implemented, but I strongly
support your thought.

For example, W3C standards say that web pages should have alternative text
to pictures, which can be read by screen readers. With a small number of
people activily coding for StreetComplete, I know that these extra bits of
functionality may not seem to be a priority; but I worry that excluding
groups of visually impaired people (for example), isn't a great thing to
do. I know that not replying to your suggestion, would make me guilty of
being part of this discrimination, even though I don't know how to fix the
problem.

Essentially, it would be great to have this functionality on the 'to do'
list.

Thanks,

Chris
chris_debian
2E0FRU

**Comment by rugk** [comment]
I completely agree, but I also agree with the _technical_ reasons @westnordost provided, explaining why alt-texts are not possible currently. I would love to see a PR here, but even better than a PR would be users, which are actually affected by this and which can tell how they (can) move the app and what needs to be improved. Because we can only tackle this problem as "outsiders", so some feedback there would be nice.
Without that doing any TODO items gets more difficult.

----

However, to get back to some actual actions here. As I explained above, I understand this issue cannot be solved yet, so I opened an issue on tangram – the map render used – about that feature: https://github.com/tangrams/tangram-es/issues/1627

**Comment by chrisdebian** [comment]
Agreed :-)

**Comment by rugk** [comment]
By the iOS codebase migration (see https://github.com/streetcomplete/StreetComplete/issues/5616 and https://github.com/streetcomplete/StreetComplete/issues/5421), BTW; maybe the app could or will automatically get more accessible BTW. At least Kotline Multiplatorm [has a page for that, already](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-accessibility.html#customize-synchronization-of-the-accessibility-tree) and I know iOS devices are quite popular for blind or visually impaired people. Well… let's see. (Just came upon this idea [because another Protoype fund project currently offers free a10y reviews](https://github.com/KreerC/a11ybuddy)).

**Comment by rugk** [comment]
Maybe you are right and you make good points, but one thing: accessibility is not only about *blind* people, but also about:
* temporary/situational problems, like e.g. being blinded by sunlight and you cannot read the map
* in general also seeing impaired people, this does not have to mean you see nothing at all, but maybe that tiny little informational text is unreadable that advises you on some important aspect for solving a quest 
* generally other impairments like hearing problems or so 

Some concrete usual improvements that can be checked here:
* making sure the app works properly of font sizes are increased
* making sure it works if you have a high contrast mode or generally a hight-contrast map (design) could benefit
  * this can mean improving the default contrast, but also… 
  * and/or having a special high-contrast map that mostly uses black and white (maybe enabled when the os asks for high contrast) 
* texts should be clear and understandable, again a thing many people will benefit from
* … 

See https://web.dev/learn/accessibility/why

This issue was just meant as a starting point to get the attention and do some advocacy. Obviously this can (and should) be integrated into the development in general. I am by no means an expert in that field, so I am sure much more can be done.
and if the UI is redone I guess this is a good point to keep that in mind.

Also, I think it would be very beneficial to people who can make use of such a quest, to also know aor even collect the data themselves. As said, maybe not all quests or so, but well… this can be customized.

**Comment by westnordost** [comment]
When big fonts lead to glitches in displaying the UI, this is something we should look at and fix.

**Comment by matkoniecz** [comment]
Similarly if things break in high contrast mode maybe it is fixable but would require specific report (including info how to get that high contrast)

**Comment by mnalis** [comment]
> in general also seeing impaired people, this does not have to mean you see nothing at all, but maybe that tiny little informational text is unreadable that advises you on some important aspect for solving a quest

True. Are you aware of Android built-in accessibility features addressing those (without needing specific app support)? One is (for small visual impairments) just enlarging fonts. For larger visual impairments, there is magnifier tool (which allows arbitrary zoom on any parts of the screen, activated by gesture or physical keys). Both seem to work well in SC (but see below).

> generally other impairments like hearing problems, impairments for text understanding (language or complex it etc.) or so

I don't think people with hearing problems will have issues with using StreetComplete (I've _always_ used without it producing any sounds -- except that [one time](https://github.com/streetcomplete/StreetComplete/issues/2966#issuecomment-862744441)!)

As for the simple and clear language, we already strive hard to do it that way (and we do I pretty good job generally, I think!). But if you spot unclear language somewhere, please do open an issue!

There are fine motor control issues, but I don't think that those can be easily solved with current concept of icons on a map (icons could only made very slightly larger without making map display mostly unusable); and we already try to make all  buttons big enough for "fat fingers"

> Some concrete usual improvements that can be checked here:

And that is great @rugk; as things that ***"can be checked"*** can be done by anyone (including you or me) without burdening main developers (who have full hands of stuff we can't do), and if an actionable issue is detected,  it can be reported as a new (actionable) issue, explaining exactly what the issue is, and proposing solution(s) how we think it may be solved.

> - making sure the app works properly of font sizes are increased

I've checked this one, and it seems to work mostly fine, with one bug I've just reported:  https://github.com/streetcomplete/StreetComplete/issues/5881 !

> - making sure it works if you have a high contrast mode or generally a hight-contrast map

It seems that android-wide contrast does not affect SC map. [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) however has special high-contrast theme, so you may want to try out how it works; so perhaps it could be included in SC if it turns out to be good at solving accessibility issues!  

> I am by no means an expert in that field, so I am sure much more can be done.

Wait, is that a typo (i.e. _"you are ***not*** sure much more can be done"_) or some sort of willingly acknowledging [Dunning-Kruger effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect)? :smiley: 

> The most obvious example I see are the quest icons: Do they have an alternative text describing the image? 

As for the original issue from 2017.; that seems to have solved itself - any icon on the map provides a question (and longer explanation if provided) just by clicking it; but also there is a list of all quest with their icons in Quest presets under settings...

> This issue was also just meant as a starting point to get the attention and do some advocacy

If you are interested in putting in time to work on this, good strategy might be to approach some of the groups with specific disabilities who might be able to use most of the app (e.g. so visually impaired yes, but fully blind probably not) and asking if they'd like to help evaluate possible issues with app (with very short introduction what SC app does and how OSM data it updates might help them). if you catch their interest; they'd likely be very adept at finding accessibility issues, and also likely have better hints at possible solutions than we have; and even if they don't have a suggestion for a fix, when issue is identified, one could ask on https://ux.stackexchange.com/ or similar places for directions how to solve it.

**Comment by rugk** [comment]
> some of the groups with specific disabilities who might be able to use most of the app 

As indicated, we could get a free a10s review by https://github.com/KreerC/a11ybuddy?tab=readme-ov-file#free-consulting-offer
I just don't feel like I am allowed to (file a) request (it) and I am not even sure if it is wanted. But maybe I'll ping @KreerC and they read it and can provide more information.

As for this "typo", well lol:
> I am by no means an expert in that field, so I am sure much more can be done.

 I rather mean "I guess I may overlook many stuff that can be done/which should be accounted for" rather than "I know for sure there is stuff to do" haha…

And yes, going forward by reporting small issues would certainly be the way to go! Also note my listing was more general examples to explain the concept (and what may need to be checked), not that I claim SC has a flaw there.
