### ISSUE TITLE
NL - Don't ask for bus stop info on ways

### ISSUE THREAD

**Issue by 501Ghost** [westnordost/StreetComplete#5257]
In NL all bus stops exist as nodes. These nodes are used in the PT relations. Not too long ago some people also wanted to map the designated stop areas, which are often raised and clearly visible. This has duplicated a lot of information.

See for example https://www.openstreetmap.org/way/826227302 and https://www.openstreetmap.org/node/7389978917.

I'm confused each time I see quests for bus stops that I know are already fully tagged. Making mappers do all the work twice is a waste of time, so I'm asking for bus stop ways to be ignored in SC quests.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element - the problem is with mapping the same object twice

**Comment by Helium314** [comment]
But then for mapping it as one thing, the tagging would need to contain something like `highway=bus_stop;platform`.
Further, `highway=bus_stop` is to be used on nodes only according to wiki, so when mapping the plaform in detail there is not much choice but to have a way for the platform and a node for the stop.

**Comment by westnordost** [comment]
There is no such thing as `highway=platform`, you mean `public_transport=platform`, right?

Anyway, since a `public_transport=platform` **can** be way and an area, and is supposed to replace (/mean the same as) `highway=bus_stop`, it sounds to me that this is rather a documentation issue for `highway=bus_stop`.

In any case, if the public transport platform is duplicated - as a `highway=bus_stop` node and a `public_transport=platform` way, then of course any information tagged on public transport platform is duplicated, too.

**Comment by 501Ghost** [comment]
I agree that mapping / tagging choices and documentation are to blame, but I think this discussion is not where we change those things.

The goal here as I see it is to stop showing mappers the same quest twice for the same bus stop. Slowing down further duplication of tags is an additional benefit. 

Bus routes in NL are all mapped in a standardised way with the nodes, so we won't miss out on relevant quests if we ignore the ways.

**Comment by westnordost** [comment]
I understand your point of view.

However, I made it a rule for this app to not have the app change how things are tagged based on whatever the local tagging preferences are. It is really a can of worms to enter into this game for which we simply do not have the manpower to maintain it. 
After all, we want to be consistent in the decisions we make, so if we add it for one place, people will have the expectation that the app should adapt to other local tagging preferences, too. This is the reason why the app always uses `maxspeed:type` for implicit speed limits and not `source:maxspeed`, even though the latter is more popular, at least in Germany.

Furthermore, and this is more important, OpenStreetMap is a global project. If a tagging scheme is consistent in one country or area but different in the rest of the world, this really does not help. Because then **every single data consumer** would need to add this exception for that one country (and know in which country a geo-position is) to correctly interpret the data. This is not really acceptable in a global project. (In this case, somehow de-duplicate and merge bus stop platforms.)

So anyway, you do you, i.e. if the Dutch community decided that this duplication is okay in the Netherlands, that's fine, I guess. But it is an stays a duplication of which you can't expect that every data consumer will handle this in a reasonable way.

And since the only effect of not handling it in a reasonable way in StreetComplete is that the users are asked twice about the bus stop platform properties, i.e. convenience rather than adding erroneous data, I'll leave the behavior as it is.

**Comment by matkoniecz** [comment]
For reference, my city had the same problem. I opened some notes complaining about duplication and a helpful mapper fixed this duplication (in this case supposed areas were dubious at best, so they were converted to nodes - but moving `highway=bus_stop` to areas would also work)

**Comment by mnalis** [comment]
Also (at the risk of stating the possibly obvious to some), if the mapper finds certain quest useless (or simply not worth the bother, or not enjoyable use of their  time in any way) in their country, they can easily disable it in `Settings` / `Quest selection and display order` and it will not be asked again (unless re-enabled).

And if they often map in different countries for which they would like different group of quests to be active, they could also create additional `presets` for easy changing between such groups of active quests.

I do that all the time (for example, most of the time I do not care about building-levels, roofs and similar quests, so I simply choose preset which ignores them and gives me the quests I find are an useful use of my time). The point is to have fun mapping, so by all means do disable the quest you don't think are adding to that goal! :heart:

**Comment by 501Ghost** [comment]
> if the mapper finds certain quest useless (or simply not worth the bother, or not enjoyable use of their time in any way) in their country, they can easily disable it

The point I tried to make is that a quest which would normally be perfectly OK gets asked twice for each bus stop, and there is no way for mappers to disable the duplicate questions.

**Comment by matkoniecz** [comment]
General policy is to accept that StreetComplete will work poorly if OSM data is broken.

Trying to support broken OSM data is complex and wasted time: OSM data should stop being broken anyway.

Either this areas are real and then `highway=bus_stop` should be moved to areas (yes, wiki disreccommends nodes: because it claims that bus platforms are vague and not real)

Or this areas are vague and mapping specific borders is dubious, and they should be deleted with tags moved to nodes.

**Comment by mnalis** [comment]
> The point I tried to make is that a quest which would normally be perfectly OK gets asked twice for each bus stop, and there is no way for mappers to disable the duplicate questions.

I got that @501Ghost, but see `matkoniecz` and `westnordost` answers above about that. I'm only trying to offer some workaround for you. Because the data is duplicated in OSM, that seems to be the source of the duplicate quests issue in  StreetComplete. 
Once _the cause_ of that OSM duplication problem is solved (in any way Dutch community prefers), so will the _symptoms_ (SC asking duplicate quests) go away automatically.  Unfortunately, allowing for such OSM duplication, but tailoring StreetComplete quest behaviour to be different for each country specifically is too big of an effort to maintain. 

---

If you'd rather not disable those quest completely, nor tackle fixing of the OSM underlying duplication of elements for all of the Netherlands,  you can try fork of StreetComplete called [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) ("SC Expert Edition") , which allows you as a user to customize on which elements each of the quests will match.

e.g. you may want to remove `, ways` from this default expression for `What's the name of this stop?` in screenshot below if you don't want the quest to trigger on ways/areas but only on nodes:
![small_Screenshot_20230923_171655_de westnordost streetcomplete expert](https://github.com/streetcomplete/StreetComplete/assets/156656/7ea5f57c-f181-4898-9ac1-99afaca995a9)

You can repeat it for all quests that you would like to behave differently. Would that accomplish what you want?
