### ISSUE TITLE
Your app does changesets over multiple continents

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#529]
See http://resultmaps.neis-one.org/osm-changesets?comment=streetcomplete#3/44.53/-14.06. 

In case the result differs when you view it (it only takes the last 30days into account), here is a screenshot:
![changesets](https://user-images.githubusercontent.com/11966684/29582955-dbee8cbe-877e-11e7-8efd-bc637c9fee64.png)

In any case there seem to be some changesets spanning from US<->EU travelers. I think this is not really expected… That may be individual cases, but can't you "force close" them when the distance between the single changes becomes too much?
(Note that I personally would not care, it just surprised me too see that in this tool.)

**Comment by westnordost** [comment]
Yes, as any editor will do if the user inputs data over multiple continents.

**Comment by westnordost** [comment]
Due to how this app signs off changesets, these changes must happen each within max about an hour. I.e. the user that did this violet changeset must have answered quests in US and then within one hour answered things in Europe.

He must also have clicked away the warning "Did you really check on-site?".
