### ISSUE TITLE
Quest: oneway:bicycle

### ISSUE THREAD

**Issue by areynoua** [westnordost/StreetComplete#533]
Many one ways are not one ways for bicycle.

> Instead of, or in addition to, using `cycleway=opposite`, you can use `oneway:bicycle=*` to identify roads where the `oneway` rules for cyclists differ from the general `oneway` restriction. If tagging an object where bicycles are the only permitted vehicles, a simple `oneway=*` is also commonly used.
http://wiki.openstreetmap.org/wiki/Bicycle#Bicycle_Restrictions

**Comment by matkoniecz** [comment]
It is really, really bad idea. And it is from person who mapped significant part of bicycle contraflow in my city.

Except extreme and unfortunately rare cases typically only small parts of one-way roads are not one-way for bicycles (certainly true at least in Poland, probably in most of countries).

So ratio of useful quests to all issued will be poor.

In addition adding oneway:bicycle=yes on oneway=yes ways is not considered as a valid tagging.

Also, in my experience this type of edit usually requires splitting ways, so is not doable with StreetComplete anyway.

**Comment by areynoua** [comment]
Oh… ok : (

Here in Brussels most of the one-ways roads are not one way for bicycles, but very few are tagged as this.

**Comment by westnordost** [comment]
Actually, the rate in Hamburg is quite high. So, it is safe to say that it varies significantly per region.

So, in any case, it should be clear that this quest cannot be applied world wide (if it should be made at all) because in some regions it may be relatively meaningful to ask, in others not. 
In a worldwide comparison, the extent of official regulation on streets in Europe and other Western countries is quite unique from my experience. I'd say that in most regions in this world, such a signage does not exist - which does not mean that cyclists and other small vehicles will not go through a oneway street from the other end and it is generally accepted and expected that they do.

**Comment by westnordost** [comment]
It could be made this way: Someone analyses the `cycleway=opposite / oneway:bicycle` usage worldwide and finds out which countries are relatively likely to have this and then limit this quest to that country(/ies) with a possibility to extend to more countries later.

**Comment by matkoniecz** [comment]
Main problem here is that it is impossible to mark lack of contraflow

To quote part of OP

> you can use oneway:bicycle=* to identify roads where the oneway rules for cyclists differ from the general oneway restriction. 

Note word "differ". adding oneway:bicycle=yes on oneway=yes ways is not considered as a valid tagging

**Comment by westnordost** [comment]
Why not? Where does it say that?

**Comment by westnordost** [comment]
It's certainly not that beautiful because it looks like duplicate information and is prone to be deleted by people cleaning up superfluous tags, but I don't see how it would be wrong.

**Comment by westnordost** [comment]
@areynoua : If you are interested in this quest, you could perhaps address this problem in the tagging mailing list. Perhaps someone has an idea how to best approach this. To summarize, the problem is that there seems to be no accepted way to differ between _"it is a oneway for everyone, including bicycles"_ and _"it is a oneway, but it is unknown if it is also a oneway for bicycles"_. Only if a distinction can be made, a quest like this can be implemented.

**Comment by matkoniecz** [comment]
> Why not? Where does it say that?

I copied it from OP. It seems to be taken from https://wiki.openstreetmap.org/wiki/Bicycle

**Comment by areynoua** [comment]
https://lists.openstreetmap.org/pipermail/tagging/2017-August/033136.html

**Comment by rugk** [comment]
Also covered by https://github.com/westnordost/StreetComplete/pull/671, as far as I see, is not it?

**Comment by westnordost** [comment]
Hmm, yes

**Comment by matkoniecz** [comment]
I think that it is still blocked by country-based filters - in countries where oneway:bicycle=no is common it makes sense to ask about cycleway infrastructure also for roads with low max speed.
