### ISSUE TITLE
Quest to check if recycling container is still present

### ISSUE THREAD

**Issue by johnjohndoe** [westnordost/StreetComplete#534]
I noticed that a lot of recycling containers, mostly clothes, are **removed** or **replaced** by others. It would be great to have a quest so users can verify if the container is **still there**.

**Comment by westnordost** [comment]
I agree. This would be nice for a couple of things. There are many things (in this world) which are mapped but often have only a limited likely "half-life" until they should be checked again.

There is an issue for that already, see #314.

**Comment by johnjohndoe** [comment]
I am aware of the `lastchecked` tag. But is there a quest which allows to delete containers which have been removed?

**Comment by westnordost** [comment]
No. But your suggestion goes into a whole new category of quests - "re-check if data is valid" quests. These are (technically) not possible at all and #314 contains discussion about what would be the first steps there.

The point is, it's not only about containers. It is about construction sites, about (short-lived) shops, about bicycle way smoothness, about wheelchair accessibility, ... about _everything_, because _everything_ needs to be rechecked and perhaps deleted if it doesn't exist anymore. (Only, certain elements are usually longer-lived than others, i.e. a road as-such is longer-lived than a recycling container).

**Comment by rugk** [comment]
As for containers: if you answer the container quest, you can just choose "cannot answer' and add a note about this.
