### ISSUE TITLE
Whitelist / Blacklist countries for quests

### ISSUE THREAD

**Issue by westnordost** [westnordost/StreetComplete#535]
Some quests are only valid or it only makes sense to ask in certain countries. Examples:
- To ask whether a restaurant offers vegan food only makes sense where veganism is a thing and cannot assume that every other place will have vegan things (India,..)
- To ask for tactile pavings only makes sense in countries where they are halfway common or are usually rolled out in newly refurbished crossroads / bus stops. Same for wheelchair access.

Additionally, some quests are specifically not valid in certain countries. For example, in the Netherlands (and Norway), housenumbers are imported from an official government source. Adding own housenumbers is not necessary.

It must be implemented that each quest can have a white- and/or blacklist of countries where it should be shown.

**Comment by Etua** [comment]
@westnordost I suggest creating a seperate branch for that use. It could be used both for existing and currently prepared quests like #527 It would be prepared by commits/PRs and pushed to master when ready.

**Comment by forteller** [comment]
> For example, in the Netherlands (and Norway), housenumbers are imported from an official government source. Adding own housenumbers is not necessary.

I actually came here to open a new Issue to say exactly this (about Norway) when I saw this Issue! I just learned this from someone on OSM telling me that I was messing things up by fulfilling the housenumber quests :)

So thank you for already working on this!

Not sure I agree on what you say on vegan food, though. Veganism is spreading and it's in the countries with the least vegan options where it's the most important to map the options that exist. If you can just go out and find many vegan places to eat with no problems, then you don't need to look it up. But if you need to plan ahead because there are so few places with vegan food, that's when you need the info on a map.

**Comment by Mannshoch** [comment]
I would not as blacklist things that are only not common, If you would do something, than set-up a lower Priority, so they only appear if all other Questions in this area are answered.

**Comment by forteller** [comment]
That doesn't make sense for house numbers in Norway. Those quests should never be done.

**Comment by Mannshoch** [comment]
@forteller I agree with that. This condition was not meant

**Comment by majkaz** [comment]
The house numbers quest shouldn't come for Czech republic either (import as well)

**Comment by westnordost** [comment]
@majkaz Please provide a link to where this is documented.
Also, the quest is only shown for buildings which are missing a housenumber - so, where the data source from which it was imported seems to be incomplete.

In general, I will soon implement that blacklist for quests, this is why I need to know definitely where the app should *never* should ask for housenumbers. The existance of a source from which housenumber data is imported does not necessarily mean that housenumbers should never be supplemented by user survey. ( That is why I ask for explicit documentation)

**Comment by majkaz** [comment]
The problem is that the tags are NOT on the building, but on a separate address point. 
Short summary of the import documentation is at http://wiki.openstreetmap.org/wiki/Address_import_from_RUIAN , unfortunatelly, the detailed description is in Czech only. The same problem is with Czech editing standards.

**Comment by westnordost** [comment]
> The problem is that the tags are NOT on the building polygon, but on a separate address node.

This is not a problem. This app only asks for housenumbers for buildings that do neither contain a housenumber node and are not itself contained in a larger area that has a housenumber (school etc.)
If it was a one-time import, it is no problem anyway.
With official documentation, I meant that i.e. in the Address-article, it is stated somewhere that adding housenumbers by hand should _not_ be done.

**Comment by majkaz** [comment]
Just tried the app again - the housenumber quest simply makes no sense in Czech republic. The housenumbers (complete address info) are imported as soon as they are assigned officially, the delay MIGHT be a few days.  Every question from Streetcomplete will come back wrong / as spam - either "building has no number" or there will come wrong answer just to avoid searching in the "other" part.

Sorry, but show me single possible positive result of a quest which can only introduce mistakes.

**Comment by westnordost** [comment]
Okay, so the import you mentioned was not a one-time import but is done regularly?

In any case, this should definitely be explained in the wiki here https://wiki.openstreetmap.org/wiki/Addresses#Country_specific_rules_and_sources
