### ISSUE TITLE
Is cycling allowed on this pedestrian way? (`bicycle=*` on `highway=pedestrian`)

### ISSUE THREAD

**Issue by mcliquid** [westnordost/StreetComplete#5515]
### General
Affected tag(s) to be modified/added: [bicycle=*](https://wiki.openstreetmap.org/wiki/Key:bicycle) on [highway=pedestrian](https://wiki.openstreetmap.org/wiki/Tag:highway=pedestrian)
Question asked: **Is cycling allowed on this pedestrian way?**

At least in my area, there are many pedestrian zones where cycling is permitted or prohibited by sign. Very often, however, this information is missing from the data or is only incompletely filled in. I would like to supplement this information with this quest.

Some example images:
[bicycle=yes](https://contentlounge-s3.bf-contentlounge-production.aws.bfops.io/styles/manual_crop/s3/2023-03/imago_78161282-v1.jpg)
[bicycle=no](https://asc-images.forward-publishing.io/2021/5/6/d7e12595-04cf-478b-92e6-7d4a8e190f86.jpeg?w=1024&auto=format) (Cyclists are prohibited in DE / AT without an additional sign.)
[bicycle=dismount](https://martin-ueding.de/posts/fahrradfreie-fussgangerzone-in-konigswinter/2023-05-05_19-09-20.jpg)

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/streetcomplete/StreetComplete/blob/master/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by any pedestrian from the outside but a survey is necessary
- [x] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
The quest could be triggered whenever a user surveys a pedestrian way tagged as `highway=pedestrian` without any `bicycle`-Tag.
```
ways with
  highway=pedestrian
and !bicycle
```

**Metadata needed:** 
Country-specific metadata may be needed to determine if cycling is allowed / disallowed by law on pedestrian ways in certain regions.

**Proposed UI:**
- **Question:** Is cycling allowed on this pedestrian way?  
  - Yes  
  - No  
  - Designated
  - Dismount  

According to [taginfo](https://taginfo.openstreetmap.org/tags/highway%3Dpedestrian#combinations), these four answer options are the most common.
Option 1: Show all four possible answers
Option 2: Only display Yes and No and use the notes for the others

In some cases there are time restrictions; a note would also have to be created for this.

**Comment by esilja** [comment]
bicycle=dismount and bicycle=no mean the same in the existing data, I think. It wouldn't make sense to distinguish them in StreetComplete only.

**Comment by matkoniecz** [comment]
Have you seen #4760 https://github.com/streetcomplete/StreetComplete/issues/4714 https://github.com/streetcomplete/StreetComplete/issues/4669 and likely other

https://github.com/streetcomplete/StreetComplete/blob/5e0244e6aa4de3da77069af4ffc57a1b17c81e5d/app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/SeparateCyclewayForm.kt#L33-L55 is still applying, though some people (as seen in this issues) tried to convince @westnordost to change that. Not checked whether this issue contains new arguments.

**Comment by tordans** [comment]
> Longer explanation: It's not about what should be considered legitimate but what can be considered verifiable on the ground. SC only shows as option what is verifiable on the ground.
> Distinction between bicycle=yes and no is only guaranteed to be verifiable if there is a sign. But there is no way to tag whether there is a sign or not.
> https://github.com/streetcomplete/StreetComplete/issues/4760#issuecomment-1396937023

How about `traffic_sign=DE:242.1,1022-10`? 
https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:242.1

This would require to have the `traffic_sign` "companion tag" specified for each country where this is being asked, of course. But I would love to see SC go into this direction anyways, as we need more explicit traffic sign tags in OSM.

(I startet a project at https://trafficsigns.osm-verkehrswende.org/?signs=DE%3A242.1%7CDE%3A1022-10 about this, but did not communicate it yet because I don't consider it ready enough to be used or commented on…)

**Comment by westnordost** [comment]
Rather, `bicyle:signed=yes`

**Comment by westnordost** [comment]
Nice tool, by the way. Though, isn't there a tool specifically for Germany already?

**Comment by tordans** [comment]
> Rather, `bicyle:signed=yes`

Why would you prefer this new tag over the established `traffic_sign`? For projects like radverkehrsatlas.de having more explicit traffic signs data is super helpful and it does convey a lot more information than a simple `yes`. 

It does also make it more complex, of course, for cases like …
- one need the sign value per quest per country
- one need to handle cases where the sign is not exactly the same like when it is [242,1020-12](https://osmtools.de/traffic_signs/?signs=242,1020-12) instead of [242,1020-10](https://osmtools.de/traffic_signs/?signs=242,1022-10) and so on

---

> Nice tool, by the way. Though, isn't there a tool specifically for Germany already?

Yes, there is osmtools.de/traffic_signs but that has not been maintained for ages and the author seems to be inactive. I also hope to one day expand it in a library that can be included in iD, SC, … to translate traffic signs bidirectionally. And to open it up to other languages.

**Comment by westnordost** [comment]
That is the reason.
