### ISSUE TITLE
Use proper compass icon 

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#560]
Before the 2.0 release, could we still get a proper compass icon?

See https://github.com/westnordost/StreetComplete/pull/436#issuecomment-321512624

I could not resist to open a new issue for that, I still fear it may go undetected as it is not in the [2.0 milestone](https://github.com/westnordost/StreetComplete/milestone/1), which soon seems to be finished. Also your "TODO" list should be completely on GitHub issues as that is transparent coding as expected from FLOSS software.

**Comment by westnordost** [comment]
"Proper"? It is proper!

(And also, to be precise, it is not an icon, but a 3D-model)

**Comment by matkoniecz** [comment]
> Also your "TODO" list should be completely on GitHub issues as that is transparent coding as expected from FLOSS software.

Please, avoid making suggestions that sound like demands. It is really cool that @westnordost makes this great app, it would be a good idea to avoid discouraging him.

**Comment by rugk** [comment]
Yeah, just giving tips.

As for "proper", I've elaborated on that, so there are different issues:
1. "Could we also rotate the "N" – so make the N belong to the arrow?"
2. The current icon is a red triangle with a letter. That's not a compass. Maybe use [this one](https://openclipart.org/detail/191872/compass-arrow) or a simple one I also saw in other applications showing the south triangle too. ([this style](https://openclipart.org/detail/87583/compass-symbol), only colored)

And, to also include the issues @ENT8R discovered: 
3. The red triangle overlays the quest.
4. "map [should] reset[…] to the default orientation if the north-indicator is clicked"

If anything is already done (particularly for the last one I am not sure), no problem, just comment. That's what we have an issue tracker for, to see what issues there are/were and when/if/how they are closed.

(I admit, I should have opened the issue instantly when finding the problems, commenting in an already-merged pull request was not a good idea.)

**Comment by westnordost** [comment]
By the way, in my definition, FOSS just means that it is **free** and **open source**, nothing more. 
Everything else is additional. It is enabled by the software being free but it is not a necessary part of it.

Specifically, I do not react well to people that come to me with the expectation that I have to comply to some "FOSS guides", just because this software happens to be open source. It should be clear that these guides were written as **tips** _for_ the developers and not as rules of conduct to be brought up _against the_ developers.

I am usually a little frank but I think any good developer will prefer honest feedback over compliments (_"Nedd gmotzt isch globt gnuag"_). Also, I am not as transparent as some people might wish. If that scares away some people, that's unfortunate, but I am primarily a programmer, not a community manager. Making people feel welcome is to be honest really not my main objective. My passion is coding and living it is what ultimately drives this project.

That being said, I didn't take amiss your words, all fine, chill. I just felt that right now is a good moment to publicly state what is my stance on this, so everybody is in the clear.

**Comment by westnordost** [comment]
>"Could we also rotate the "N" – so make the N belong to the arrow?"

No, that was deliberate. I want the N always to be readable right-side-up.

> The current icon is a red triangle with a letter. 

It is called a compass needle. The rest of the compass, including "South"-part of the needle is abstracted away. This should go well with the arrowhead metaphor for direction that many map and navigation apps use. In short, I will not change anything there.

> 3. The red triangle overlays the quest.

This has long been fixed.

>  4. "map [should] reset[…] to the default orientation if the north-indicator is clicked"

This has long been implemented already.

**Comment by rugk** [comment]
So let's have a look at other compasses. (all from the apps here)

Mapillary:
![mapillary](https://user-images.githubusercontent.com/11966684/29794175-2755c240-8c47-11e7-94ba-7b7ae3b9fd21.png)
Maps.me:
![mapsme](https://user-images.githubusercontent.com/11966684/29794186-31a59f90-8c47-11e7-80fa-b7109dc84b24.png)
OsmAnd:
![osmand](https://user-images.githubusercontent.com/11966684/29794188-363789c4-8c47-11e7-99dd-d4751364ab79.png)

Now compare it with StreetComplete:
![StreetComplete](https://user-images.githubusercontent.com/11966684/29793931-28c7f2b6-8c46-11e7-971e-eb23b4509cfa.png)

Don't you think, this looks strange? From the screenshot the "N" is also partially overlayed, and if the `N` is really fixed at it's position, then it also behaves strange compared to other "usual" compasses you know from other apps. (see above)

The "compass needle" also does not look like a needle, but rather than an arrow. If you compare the pictures above, I hope, you see what I mean. E.g. the one ending is carved in whereas a needle would not have this.
And IMHO the OsmAnd version is okay, but the others showing the south needle too are more familiar to me and look nicer.

That said, I have not tried out the app in practice yet as no version is released yet and I do not want to self-compile it. So you can leave this issue as it is and I will likely comment on it again when I get my hands on it in practice.

**Comment by matkoniecz** [comment]
> Don't you think, this looks strange?

No, for me it was perfectly recognizable as symbol of compass.

**Comment by westnordost** [comment]
You can report that the arrow is shifted to the top if you experience it (and specify what android version you are using etc.) as a bug.
