### ISSUE TITLE
undo gives points rather than removing them - balancing gamification problem

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#566]
as result one may easily farm points by cycle of doing and reverting group of quests

**Comment by westnordost** [comment]
Yes, I mentioned this earlier. This is a technical limitation.

**Comment by westnordost** [comment]
I will elaborate a little:  

* Technically, two cases are distinguished which are transparent to the user: _undo_ and _revert_. An undo can be made if the change has not been uploaded to OSM yet (i.e. when autosync mode is off). No changes made are simply deleted and the quest returned to its original state, no problem there. _Revert_ is the complex part.
* Reverting of quests works by reversing the change made of a quest, storing this revert-quest into a separate DB table locally (so that users cannot undo their undos) and then uploading these revert-quests in technically the exact same way as normal quests (including all the conflict handling etc).
* as the revert-quests are uploaded as normal quest-answers, a revert adds to the ⭐️ quest counter instead of subtracting from it. I could have implemented it another way to count the stars correctly, but then the revert-quests wouldn't be uploaded in the same changeset. I think it is more important to upload it in the same changeset than to have the ⭐️ quest counter being absolutely accurate.

**Comment by westnordost** [comment]
Perhaps it is possible to subtract the count later when I implement the leaderboards. I will keep this in mind when implementing it. The (python) script that mines through the user's changesets to create the stats should be able to detect if any one element appears twice or more often in a single changeset -> That would mean that the user reverted that quest.

**Comment by matkoniecz** [comment]
> if any one element appears twice or more often in a single changeset

Note that edge case described in #567 breaks this assumption and revert may be in a separate changeset.
