### ISSUE TITLE
undo changesets are poorly described

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#567]
Changeset undoing "Add crossing type" quest is named "Add crossing type" rather than something like "Undo my own edit".

Also "StreetComplete:quest_type" is dubious.

http://www.openstreetmap.org/changeset/51523561#map=19/50.08017/19.89030 is an example

This may be triggered by undoing things from a closed changeset.

**Comment by westnordost** [comment]
How many minutes after introducing the change did you revert it?

**Comment by matkoniecz** [comment]
After more than one hour (I waited till changeset was closed).

I was deliberately trying weird things to check whatever undo works correctly, but I had situations where I reverted my (last) StreetComplete edit after more than one hour.

**Comment by westnordost** [comment]
Hm, okay. Well, the app tries to put the revert into the same changeset as the initial answer, but if that changeset is closed already, a new changeset must be created of course.

The behavior as it is now has some caveats, like this one, but any other option is more problematic:
1. Putting reverts into an own other changeset tears apart the context in which changes have been added/reverted. I.e. the "adding something" changeset would still show the wrongly added things and the "oops, reverted that" would be in a completely different changeset. 
2. Additionally, it makes it impossible to associate a revert with any one quest type, which is a prerequisite of possibly decrementing the quest counter for a revert. Except if for any revert of each different quest type, a changeset is created, but this is out of question, this would really spam the changelog.

Usually, a revert is done like an undo - do something, oops, wrong, undo, do again. The thing you did is in my opinion really an edge case. It is very rare that a surveyor needs to revert something an hour later. It is good to know that it basically works.

I could of course change the maximum allowed delay between solving a quest to being able to reverting it from 24 hours to about half an hour (the time SC leaves a changeset open), but that does not guarantee that the described thing does not happen because the user may choose to upload the change much later when auto-sync is off.

**Comment by matkoniecz** [comment]
> The thing you did is in my opinion really an edge case.

I agree and in this case nothing truly horrible happens. WONTFIX is perfectly fine in case that fixing it would be really complex or break some assumptions that simplify things.
