### ISSUE TITLE
Missing error panel after selecting a map pin

### ISSUE THREAD

**Issue by stephan75** [westnordost/StreetComplete#6]
Sorry for typos and brievety:

On moto g with Android 5: after clicking on an error map pin only the red circle is displayed around position ... But no error description.

But when turning device from portrait mode to landscape mode, error description is then shown!

Anyone can reproduce?

**Comment by westnordost** [comment]
Yes, I can. 

This is actually due to the performance issue. The description does not open because in the background, the job is still busy retrieving all those pins from the local DB to display on the map. It is a queue, so when you want to display the details, it has to retrieve the pin from DB and it adds this to the end of the queue.

The "workarund" currently is to just wait until the background job is done. Best way to tell when it is done: When the description opens after you clicked, since this the the very last thing the job will do then.

**Comment by westnordost** [comment]
Fixed/workaround now in https://github.com/westnordost/StreetComplete/commit/888f74843cf7b5fc6ef0932a1e628b246409fc7e

**Comment by stephan75** [comment]
This error still or again comes up in fresh 0.5 app version!

Re-open issue?

**Comment by westnordost** [comment]
Oh no! The exact same problem?

Is the map still slow as well?

Was it fixed intermediately in version 0.4?

Do you use any "battery saving mode"?

**Comment by stephan75** [comment]
I will try to install the 0.4 or 0.3 apk file manually and do some testing ... needs some time.

**Comment by westnordost** [comment]
Ah, don't bother too much about that, I thought you maybe remember. The other questions will help me more to find the bug.

**Comment by stephan75** [comment]
I tried both, 0.3 and 0.4 apk ... same issue.

No battery save mode, no map panning slow down , and I assume that no other result after minutes.

And after changing screen orientations from landscape to portrait, each time that nagging reminder comes up to turn on GPS when I have it off.

**Comment by westnordost** [comment]
> each time that nagging reminder comes up to turn on GPS when I have it off.
Oh, please create a separate issue for that.

**Comment by stephan75** [comment]
I think I found the culprit:

The error depends on the developer settings of the android device, turn graphic animations on or off there.

I had them off, thus no error panel.

When enabling animations, everything works right.

But why does streetcomplete depends on those settings?

**Comment by westnordost** [comment]
Apparently it does. For the slide up of the panel. Thank you for the info :-)
