### ISSUE TITLE
I don't see a map

### ISSUE THREAD

**Issue by sycoso** [westnordost/StreetComplete#60]
I don't see a map. All I can see is a white background, my position, and quest markers.
Reinstalling didn't fix the issue.

I have a Fairphone 2 with Android 5.1 (not stock)

**Comment by westnordost** [comment]
Does the [Eraser Map](https://play.google.com/store/apps/details?id=com.mapzen.erasermap) work for you?

**Comment by sycoso** [comment]
It also only shows a white background and my location

**Comment by westnordost** [comment]
Hmm okay, then I have to forward you to the rendering library: https://github.com/tangrams/tangram-es/issues

Would you please create a bug report there? The problem seems to be that your phone is unable to get the vector and/or display tiles from mapzen's tile server. I think the people over there might have some ideas how to get onto the problem.
