### ISSUE TITLE
Use correct version suffixes for pre-releases

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#622]
You published v2.0 and 2.1 as a pre-release. That will cause you trouble. E.g. which version will you release as a stable? 2.0 (so going backwards with the release numbers? -> that could break F-Droid) or 2.2 (skipping 2.1 as a stable?) or what?
Marking a version as a pre-release on GitHub is not enough (also not enough for F-Droid, which wrongly offers 2.0 and 2.1 as stable releases to F-Droid users).

I'd strongly suggest you to abide to [semantic versioning](http://semver.org/), i.e. here is an example of version numbers:
* 1.0 = stable version
* 2.0-alpha1 = Alpha release of v2.0
* 2.0-alpha2 = 2nd alpha release of v2.0
* 2.0-beta1 = Beta release of v2.0
* […]
* 2.0-rc1 = first release candidate of v2.0
* 2.0-rc2 = second release candidate of v2.0
* 2.0 = final stable release of of v2.0

So you see you can iterate with pre-release versions as you want and in the end release the final version. Of course, you do not need to use all these stages. You can also just release one beta version and directly release the final version afterwards. That's fine, but the point is: If you use a pre-release version, use a pre-release version number (respectively suffix).

**Comment by westnordost** [comment]
Again, with the "semantic versioning"... A stable is stable when it is stable. Meaning, any version I release may be promoted to a non-pre-release version if I declare it stable enough.

The release process is as follows:
* I increase the major version for a release that contains new features, quests, etc.
* I increase the minor version for any subsequent bugfix update of that major version
* any new major version (x.0) will start being a "pre-release". As soon as I deem a version stable enough, I mark it as a "release". 
  1. For Google Play releases, only the stable versions show up. Except for users that opted in to be betatesters
  2. On F-Droid releases, this has no effect, as there is no notion of beta/stable channel

If you prove to me that F-Droid would not show and offer to update versions that are suffixed with something (like -beta1, -rc1 etc.), then I may consider to change my versioning scheme. Otherwise, I leave it as it is.

**Comment by rugk** [comment]
>On F-Droid releases, this has no effect, as there is no notion of beta/stable channel

There is. In the settings users can show/hide pre-release version. But apparently F-Droid does not look for the GitHub 

Note that semantic versioning defines how one can tag pre-releases:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. 

It is a "may", but I'd strongly recommend it. (even if F-Droid does not care for it) As otherwise you just cannot differentiate between stable and pre-release versions.

**Comment by rugk** [comment]
In any case I've asked how to correctly release pre-release versions:
https://forum.f-droid.org/t/how-to-mark-releases-as-pre-releases/1246

**Comment by westnordost** [comment]
Ok, nudge me here when you got a concluding reply

**Comment by rugk** [comment]
From https://f-droid.org/docs/Build_Metadata_Reference/ in the part about Updates -> Tags:
> It shouldn’t be used if the developers like to tag unstable versions or are known to forget to tag releases. [But: …] Optionally append a regex pattern at the end - separated with a space - to only check the tags matching said pattern. Useful when apps tag non-release versions such as X.X-alpha, so you can filter them out with something like .*[0-9]$ which requires tag names to end with a digit.

So it seems you can configure it to work correctly…

**Comment by rugk** [comment]
BTW, you can unassign me. I got a concluding reply.

**Comment by westnordost** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2823
