### ISSUE TITLE
Does not recognize housenumber nodes on outline of building

### ISSUE THREAD

**Issue by iwohltmann** [westnordost/StreetComplete#626]
It seems that StreetComplete does not recognize housenumbers given as nodes on the outline of a building. I just removed more than 100 double housenumbers. The reason for the double tagging seems to be that the app did not realize that the housenumbers were already there and generated quests for many already tagged buildings. I think this is very unfortunate, since someone put a lot of work into something here for nothing.

Location where I noticed this is around streets "Am Brunnen" and "Drevesstraße" in Potsdam, Germany

**Comment by westnordost** [comment]
There is a lot of "seems" in this bug report. Can you actually reproduce this somewhere?

I can tell you that it is implemented that housenumber nodes placed on a building outline are excluded and this behavior has been tested before. Of course, it is never possible to completely eliminate the possibility of a bug.
Nevertheless, I want to ask you to actually show me a place where a housenumber quest pops up where it should not so that I can reproduce it.

**Note**: Nodes that are even the slightest distance misplaced to the outside of a building still count as outside of a building for the app.

**Comment by iwohltmann** [comment]
Hello,
after updating the quests this morning (in my german version "Hier nach Aufgaben suchen"), the quests for housenumbers for the buildings in question disappeared and everything looks fine now. Is it possible that there was a change in behaviour regarding that recently? I also have to admit that I did not check which editor the user who doubled the housenumbers used. It turned out it was JOSM and that he did not use Streetcomplete. Sorry for the false alarm.

**Comment by westnordost** [comment]
Ok.
No, nothing was changed in that aspect. The last change that was done on the housenumber quest was that buildings within areas that already have a house number are not included anymore.
