### ISSUE TITLE
limit unglue notification

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#627]
Hint introduced by https://github.com/westnordost/StreetComplete/commit/361fee94d4d7042b2b3f1b5d8093da91b719e9c5 is shown over and over again

Maybe after displaying it for example 2 times it should not appear anymore? Or at least appear rarely?

**Comment by westnordost** [comment]
I am open for suggestions.

**Comment by matkoniecz** [comment]
For experienced users this notification is not necessary (but given that I maintain my own fork I am an extreme outlier, the same applies for nearly everybody active on the issue tracker), so I think that this addition makes sense.

Showing it only once would be not enough - people on first contact with a software sometimes dismiss explanation and later would like to see it again.

Showing it once and adding "show again are already displayed hints" setting is a solution that I like but I know that one of design decisions is to avoid settings.

Maybe showing it three times and reset this counter if app was unused for longer than 20 days (inspired by how Firefox behaves)?

I would recommend just "show it three times and never again" if counting inactivity time is an overkill (though I think that it would be again useful once other hints are introduced).

**Comment by antonv6** [comment]
Maybe not strictly related to this issue, but what's the idea behind tapping a button being the only way to unglue the map?

If users were allowed to just drag the map to unglue it, there wouldn't be any need to show this notification at all, _and_ it also would make UI feel more familiar. Many, many apps that have a map just allow users to drag it around by default, and then have a button to show or follow their location. Such a button doesn't need any notifications, sometimes doesn't even have a tooltip, because it's instantly discovered when people want to see their location, and the other two buttons are just + and -.

**Comment by westnordost** [comment]
1. It was a feature request not to turn off follow-me-mode when answering a quest and to make follow-me-mode more sticky in general (#429). Answering a quest involves clicking on the marker, which the map registers already as a swipe and thus turning off the follow-me-mode. While this particular behavior may or may not be considered as a bug of tangram-es, in any case, just swiping the map by one pixel would already turn off the follow-me-mode, which made that mode too volatile. To disable the mode with a "strong swipe" would also have been conceptually possible, only not technically (I think). However, there is a second reason:
2. Following the position is supposed to be the default, because the user should be discouraged to answer quests that are not at his location. The non-follow-mode is just there to "look around".

**Comment by matkoniecz** [comment]
>  The non-follow-mode is just there to "look around".

And for situations when GPS is showing wrong position

**Comment by matkoniecz** [comment]
It was reverted in https://github.com/westnordost/StreetComplete/commit/c69046a05362599480cce395dff76ed2d199863a

Is it because "show info X times then stop doing this" is a bad idea? Or is it a bad idea just in this case because interface is too tricky and without this message many users are confused?

**Comment by westnordost** [comment]
I don't know if it is generally a bad idea. I only know that I got a several people complaining about that they can't move the map even after I added the hint.
