### ISSUE TITLE
Verification of the OSM-Account

### ISSUE THREAD

**Issue by Schatzforscher** [westnordost/StreetComplete#646]
I could not verify my username and password of OSM with streetcompleet. Every time it connect to OSMAnd and not to a verification site. In the Apps Menue it is not able to chancge the standard prorgramm.

**Comment by versat** [comment]
I've tried to reproduce it.
I have also installed OsmAnd on my phone.
For testing i have said that the link should always be opened with OsmAnd.
What helped to fix it:
Go into the Settings/Einstellungen -> Apps -> click the cog/Zahnrad at the top.
Then go into "Links zum Öffnen" (i don't know how it is called in english) and scroll down to OsmAnd.
Click at OsmAnd and in the window showing the OsmAnd settings click on "Standard-Einstellungen zurücksetzen" ("Reset to default settings" or so in english).
At least this works on my Sony Xperia XZ with Android 7.1.1.

**Comment by westnordost** [comment]
Yes, the issue is the combination of that
1. you open the authentication on www.openstreetmap.org not in the browser but in OsmAnd
2. OsmAnd even offers itself to open that website in place of a browser
3. Android is not making it clear to the user that it is opening a link to a website in another app (as per prior set preference by the user)
4. Google blocks authorization through OAuth when done within an app instead of
