### ISSUE TITLE
Support for Czech/Slovak addressing system

### ISSUE THREAD

**Issue by andrewshadura** [westnordost/StreetComplete#688]
*(copying and pasting from a [mailing list discussion](https://groups.google.com/d/msgid/osm_sk/8bdf928c-c1e7-43ea-8fe7-952b0e2d6d53%40googlegroups.com))*

I would be great if you could add support for the Czech/Slovak house number scheme to
StreetComplete, for the moment enabling it in Slovakia only (since the Czech community is currently against enabling this)? <sup>[0]</sup>

Unfortunately, there isn't any good documentation in English, but you myself and others can help you with this. Basically, there's one number (*conscription number*) which is normally unique to the place or its district, depending on the city, and another number (*street number*) is the regular street number; neither is normally rendered. Unless street numbers aren't used (which mostly what happens in villages), `addr:housenumber` is better be set to the street number, for rendering purposes. In villages it's quite often that houses don't get any street numbers, so when conscription number only is used, it is copied to `addr:housenumber`.

The street signs in Slovakia normally look like this:

![2017-11-14_12-36-52](https://user-images.githubusercontent.com/309253/32777975-94b7c814-c938-11e7-86b8-87e651ae348e.png)

The black sign is the conscription number, the red one is a street number.

In some cases, the conscription number is prepended by a red Roman numeral denoting the city district:

![2017-11-14_12-38-36](https://user-images.githubusercontent.com/309253/32778074-d4375ac2-c938-11e7-817a-71dd9710ca94.png)

I would expect from StreetComplete to display two house number boxes separated by a slash:

`[     ]/[   ]`

with the first of them corresponding to the conscription number, and the second being the street number. For Slovakia, it's be also cool if they could be coloured differently, in the same way the real street signs are coloured (conscription numbers are black on white, street numbers are red on white).

In Czech republic, unfortunately, there isn't a country-wide standard for the house number signs, so this colour scheme may not work.

Alternatively, StreetComplete might display the same UI as elsewhere, but recognise house numbers with a slash in Slovakia and fill `addr:conscriptionnumber`/`addr:streetnumber` fields accordingly when saving changes.

[0]: https://wiki.openstreetmap.org/wiki/Key:addr:streetnumber

**Comment by westnordost** [comment]
After reading the [wikipedia article](https://en.wikipedia.org/wiki/House_numbering#Czech_Republic_and_Slovakia), (which is not too complete for Slovakia) I have some questions:

- when the conscription number like I.383 is prepended by a Roman numeral for the district, would `addr:conscriptionnumber` also be set to `I.383` (or 383)?
- are the conscription number and street number (aka orientation number) sometimes also on the same sign? (I have seen signs for Czech Republic where this was the case.) If yes, is the conscription number always the first number in the `[ ]/[ ]` pair?
- which color are the registration numbers (aka provisional numbers) in Slovakia (if they exist)? Are they also sometimes prepended with an E, sometimes with a 0? If yes, should this information be transcribed as-is into `addr:provisionalnumber`? A place that has a provisional number does not have any "normal" house number, right?
- Is there **always** a conscription number? I.e. I understand that especially in villages, roads have no names and that is why the houses will often have no streetnumber. But can houses have a streetnumber but no conscriptionnumber? (If no, this makes streetnumber an optional field in the form and conscriptionnumber a required field)
- Can a house have two streetnumbers (and associated streets) if it is situated at an intersection? I have read that this can be the case in Czech Republic. If yes, how should this be tagged?
- Should the `addr:housenumber` always be set (automatically) together with the Slovakia-specific tags, taking the value from streetnumber (if available), conscription number (if available) or otherwise provisional number? (And if yes, why? After all, it can be inferred automatically, so this adds data duplication)

**Comment by andrewshadura** [comment]
> when the conscription number like `I.383` is prepended by a Roman numeral for the district, would `addr:conscriptionnumber` also be set to `I.383` (or 383)?

Possibly. Both variants exist in the wild. As I understand it, adding the  `I.` prefix is considered more *correct*, but it's often skipped (I often skip it myself). It also can be derived from other tags (as usually there's a 1:1 mapping between the number and the city district name). I don't have a strong opinion on this.

> are the conscription number and street number (aka orientation number) sometimes also on the same sign? (I have seen signs for Czech Republic where this was the case.) If yes, is the conscription number always the first number in the `[ ]/[ ]` pair?

Not if the standard plates are used. Yes, if the house owner uses custom number plates. The conscription number is supposed to come first (it is *mostly* first in the address lines except AFAIK once city in Czech Republic), but sometimes people mess it up and write it in the reverse order.

> which color are the registration numbers (aka provisional numbers) in Slovakia (if they exist)? Are they also sometimes prepended with an E, sometimes with a 0? If yes, should this information be transcribed as-is into `addr:provisionalnumber` (or the E/0 be stripped)? A place that has a provisional number does not have any "normal" house number, right?

Officially they have been abolished. In practice, they can be found on older buildings like garages or huts; they're usually white on a dark blue background. I think I haven't seen E or 0 prefixes in Slovakia.

I think provisional numbers should not normally be offered as an option. It makes sense to offer them as a last chance option when the user says *oh, there's a number, but it's weird and looks nothing like this*

> Is there **always** a conscription number? I.e. I understand that especially in villages, roads have no names and that is why the houses will often have no streetnumber.

I *think* there always must be a conscription number. It's basically a sequential number given to this building when the building is registered with the place administration.

> But can houses have a streetnumber but no conscriptionnumber? (If no, this makes streetnumber an optional field in the form and conscriptionnumber a required field)

I don't think so. It may not be discoverable (e.g. the house owner decided to not display it), but in that case it should be considered not yet known.

> Can a house have two streetnumbers (and associated streets) if it is situated at an intersection? I have read that this can be the case in Czech Republic. If yes, how should this be tagged?

Not normally, but happens sometimes:

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Czech_and_Slovak_house_numbering_scheme.jpg/300px-Czech_and_Slovak_house_numbering_scheme.jpg)](https://commons.wikimedia.org/wiki/File:Czech_and_Slovak_house_numbering_scheme.jpg#Summary)

I have no opinion on how to tag that. Probably looking this house up in OSM may give an answer :)

> Should the `addr:housenumber` always be set (automatically) together with the Slovakia-specific tags, taking the value from streetnumber (if available), conscription number (if available) or otherwise provisional number? (And if yes, why? After all, it can be inferred automatically, so this adds data duplication)

Yes, I think so. It is used by the renderers, unlike the other two tags, which are used by Nominatim only.

**Comment by andrewshadura** [comment]
> Not normally, but happens sometimes:
> 
> [![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Czech_and_Slovak_house_numbering_scheme.jpg/300px-Czech_and_Slovak_house_numbering_scheme.jpg)](https://commons.wikimedia.org/wiki/File:Czech_and_Slovak_house_numbering_scheme.jpg#Summary)

Actually, thinking about this again, I suppose the author of the picture is mistaken. Probably the sign is put at one of two adjacent buildings, and for some reason they decided to put the signs together, but they actually belong to different buildings. They often do this in Bratislava, putting five red signs at the corner of a building, when in reality they belong to five entrances of the building.

**Comment by westnordost** [comment]
![device-2017-11-15-190816](https://user-images.githubusercontent.com/4661658/32852497-60a813fc-ca38-11e7-8180-d4e5826a7fde.png)

**Comment by westnordost** [comment]
I left the provisional house numbers ("registration numbers") out now because
- it looks like they are only more or less still used in Czech Republic, but for this country, the quest is disabled (no photos on wikipedia, by local knowledge from @andrewshadura and by looking at taginfo)
- there is no standard how the registration plaques look like: Sometimes they are green, sometimes yellow, sometimes another color. Sometimes they are prepended by E..., sometimes by 0...; Since the app is not for experts, it is not possible to get across to users when something is a conscription number and when something is a registration number easily. 
- As with any other edge case, if a housenumber looks odd, the user can always leave a note instead

**Comment by westnordost** [comment]
**Implementation details:**
- Quests are only shown for buildings that have none of housenumber, conscription number, house name, street number defined.
- For Slovakia, always the dialog is shown as shown above. (But the user can still select that the building has a house name instead)
- Conscription number is required, street number is optional. An error message will pop up if the user tries to input only a street number, telling him that the conscription number is required.
- Clicking the 123/abc button changes the keyboard for the input field the user is in currently.
- Input is validated and the user is warned, if the input looks fishy: For conscription numbers, it must be a number with up to 6 digits. For street numbers, it is the same validation as for other housenumbers.
- Finally, also the normal housenumber input does not change its size anymore, instead, the text is scaled down.

**Comment by westnordost** [comment]
The feature will be live in a few hours because incidentally, I will create a new major release today. On Google Play, it will be beta for now.

Spread the news, I saw on the Google Play Console that only 20 people from Slovakia use the app! :-)
Also, there is no translation for Slovak yet in the app, I guess everyone is using English or Czech? Anyway, [anyone who is interested can help with the translation here](https://poeditor.com/join/project/IE4GC127Ki).

**Comment by andrewshadura** [comment]
I just wonder how do you handle the situation when for some reason the conscription number isn't visible? E.g. usually there's just one conscription number sign for the whole building, but entrances have their own individual street number signs. With custom signs, house owners sometimes choose not to display the conscription sign at all — will StreetComplete allow me to proceed with just the street number and warn me it's not complete, or will it block me and not let me save at least what I've got?

**Comment by westnordost** [comment]
StreetComplete asks for the number of the whole building, not every single entrance. So if he finds only one conscription sign (i.e 1234) but several orientation numbers (1, 2, 3, 4), he will have to input 1-4 for the orientation number.

This is really the same situation as for normal housenumbers.

If the multiple entrances are already mapped on the building, then it is very likely that these entrances already have housenumbers, in which case the quest is not shown.
In the case they are not mapped, then giving the correct number(s) for the building will be a good first step with the option to make it more detailed (putting the numbers on the entrances) later.

On 16 November 2017 08:36:23 CET, Andrew Shadura <notifications@github.com> wrote:
>I just wonder how do you handle the situation when for some reason the
>conscription number isn't visible? E.g. usually there's just one
>conscription number sign for the whole building, but entrances have
>their own individual street number signs. With custom signs, house
>owners sometimes choose not to display the conscription sign at all —
>will StreetComplete allow me to proceed with just the street number and
>warn me it's not complete, or will it block me and not let me save at
>least what I've got?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/688#issuecomment-344840036

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
