### ISSUE TITLE
Avoid asking about both cycle lanes on one way street

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#689]
Some major roads are modelled as 2x parallel physically seperated, one way roads.

Example: Grand Junction Rd, Rosewater, South Australia
http://www.openstreetmap.org/way/10418145

With these, a cycle lane is only put in the direction of said road, so asking about "both" sides of the road doesnt make sense.

**Comment by westnordost** [comment]
But it does make sense for normal oneway roads because there may be a contra-flow bicycle lane.

How to distinguish between these?

**Comment by CloCkWeRX** [comment]
I was thinking about that, the best filter criteria I could come up with is either its a trunk/primary/motorway + oneway, or has lanes=2/similar + oneway.

**Comment by westnordost** [comment]
Hm, but especially for those big roads (where the cars will go fast), it is a valuable information whether there is a cycleway or not.

**Comment by CloCkWeRX** [comment]
I was thinking more the validation requirements got relaxed: where lanes>1 + oneway, && you-only-filled-out-one-cycleway, !show "you left the form blank"

**Comment by westnordost** [comment]
That wouldn't be self-explanatory to the user at all.

**Comment by westnordost** [comment]
One heuristic could be that if the street is mapped as `tertiary`, `secondary `or `primary `and `oneway=yes` and `oneway:bicycle` is not `no`, then, change the form to only show one side of the street (the direction that goes with the flow).

**Comment by westnordost** [comment]
So, I came up with three ideas, ordered by my preference. All are not optimal. (Examples assuming right-hand traffic:)

### 1. Right side on full width
In the above mentioned case, only display the right side in full width. The left side cannot be specified. Add an other-answer option "Cycleway in contra-flow" which restores the normal layout that shows both the left and right side.
**Con:** If there indeed is a contra-flow cycleway, it is not evident to the user that such a other-answer option exists because because that other-answer is only shown in this case, not always.

### 2. Left side pre-filled
In the above mentioned case, pre-fill the left side with "no cycleway", but if not changed by the user, nothing is tagged for the left side.
**Con:** The user might be confused why `cycleway:left` is not being tagged then. This is not explained. Also, the user might misinterpret the street mentioned in the quest as "the whole street" (+ the other side of the dual carriageway) which will lead to wrong tagging.

### 3. Left side "hidden"
In the above mentioned case, leave the left side blank (white). The left side can be specified as usual by clicking on the white area but is not required.
**Con**: This looks a bit like a bug. It is not apparent to the user that the white side means that one does not need but can optionally specify something. Also, the user might misinterpret the street mentioned in the quest as "the whole street" (+ the other side of the dual carriageway) which will lead to wrong tagging.

**Comment by westnordost** [comment]
So I chose option 1. Was quite some work, I hope this solves it now. 😅 

![device-2017-11-18-223442](https://user-images.githubusercontent.com/4661658/32985034-661fa0b8-ccb1-11e7-9faf-c6ce7fb032a0.gif)

**Comment by rugk** [comment]
From your gif: Maybe the label "Other answers…" does not fit here very well, because this question has no buttons saying yes or no or so and "other answers" does not close the answer – you still have to click on "OK".
Maybe label the button "Add…" or something generic like "More…" in that case.

**Comment by westnordost** [comment]
You have a point, @rugk . Perhaps instead of that "Other answer" option, there should be a button in the lower left corner with which one can add the other side.
How should it be named? "Also define other side" - would be too long I suppose? "Also other side"? "And other side"?

**Comment by westnordost** [comment]
By the way, @antonv6 , here you see in action that strings can change even after beta release through feedback/bugs about the new features. Yesterday, I updated POEditor with the new term ("Also cycleway on other side") but now it looks like that was too hasty and every translator who invested time in translating that, wasted his time.

**Comment by westnordost** [comment]
So, I will leave it as it is now. You have a point of course, but the button would be too prominent and I think thus would invite wrong tagging. About 10% of primary/secondary/tertiary streets are oneway. I don't know how many of these 10% are then actually _not_ dual carriageways but "real" oneway streets, for which it would make sense to show the other side, but it must be a very small percentage - making this specific scenario rare enough that I think it is okay to "hide" it in the "Other answer..." menu.
