### ISSUE TITLE
zoom-buttons for one-hand use

### ISSUE THREAD

**Issue by zossebart** [westnordost/StreetComplete#7]
I played around with the beta a little bit and had problems using the app one-handed because zooming seems only be possible using pinch-to-zoom.

Would it be possible to add zoom control buttons (+/-)? Maybe this could be made optional via the settings menu.

**Comment by westnordost** [comment]
Well, usually you shouldn't need to pan and zoom around since the quests can usually only be answered if you stand right next to it (i.e. opening hours). The view should automatically zoom to your position.

Actually, I am thinking about _forcing_ GPS always on and no control whatsoever for the user to pan and scroll. Reasons:
- I intend to add more gamey-things later, with highscores and such. I don't want to invite users who cheat themselves up the ranks by inserting garbage for the quests but still commit them
- almost same: this limits "easy" vandalism to the immediate location the user is. The only location any well-meaning user may reasonably contribute anyway
- as said, there is no necessity to pan and zoom: download-quests-for-offline-usage could be selected in a separate dialog; if there is no quest in sight, I intend to add arrows that stick to the screen border pointing into the direction of the next quests (with distance). Every unnecessary control is a superfluous control

I am only thinking about this, but it's not from the table.

I am leaving all this "freedom" in for now because obviously in the first time, only OSM enthusiasts will use the app and the "download for offline" functionality uses the currently displayed are on the map as selection.
Since it is a no-brainer, I will add double-tap to zoom for now.

If this functionality (+/-) is important for you, would you elaborate why zooming while only having one hand free is important for your use case?

**Comment by zossebart** [comment]
Ahh ok, I see your points. Maybe I'm too much of an OSM enthusiast ;-)
You are right, in regard of the gaming aspects it's not necessary to zoom and pan. 
But even under these aspects, it might be useful to only get an overview of an area before actually going there to "play". Maybe there could be a "look around" mode, which allows zooming and panning, but no editing (maybe show the symbols greyed out?)?

Why it would be important to me: maybe it's just me, but I almost never use my phone two-handed. My other hand is oftentimes holding something else (bag, bike handlebar, wife's hand ;-) ). And because I don't own one of these "monster phones", I can actually use it one-handed quite comfortably. So oftentimes I quickly get the phone out of my pocket, unlock, do something (for example writng a note), lock and put it back into my pocket, all with one hand.

**Comment by westnordost** [comment]
Hm yes, this'd be a good compromise. So then I will
- add an option to show -/+ buttons for better one-hand control
- disable answering of quests further away from the user than X meters
- have the view by default "snap" to the user location but make it possible to look around as well (so more or less like it is now)

However, this is quite low priority right now, so I will leave this open for now.

**Comment by westnordost** [comment]
All implemented now except the "disable answering of quests" limitation. I'll do that later as this kind of limitation is I think not necessary with a small userbase of OSM enthusiasts.
