### ISSUE TITLE
Latest version on F-droid?

### ISSUE THREAD

**Issue by forteller** [westnordost/StreetComplete#707]
It seems like version 2.4 has been available in Play Store since Nov 11th, but it's still not in F-droid. I don't know if the fault is on this side or F-droids side, but I'd appreciate it if it became available soon! Thanks! :)

**Comment by westnordost** [comment]
#695 : There was a build problem between 2.4 and 3.0. It has been fixed for 3.1. 

Hmm, but according to https://f-droid.org/wiki/page/de.westnordost.streetcomplete#3.1 it still fails, though I do not see any error message in the log.

**Comment by rugk** [comment]
Wanna ask the F-Droid devs?

**Comment by westnordost** [comment]
Would you be so kind? You already have a connection ;-)

**Comment by rugk** [comment]
I also just ask them in the forum or so… 😄 

But here you go: https://forum.f-droid.org/t/streetcomplete-is-outdated/1636

Maybe also a good idea to ask @Bubu.

**Comment by Bubu** [comment]
I have no idea what's up with the log. But apparently the whole build infrastructure is hanging right now, so we will only know if the build worked or not when the server starts publishing builds again... :-/

**Comment by westnordost** [comment]
Cool, thanks for the feedback, @Bubu 

Then I can close this as the issue seems to be somewhere else.

**Comment by IzzySoft** [comment]
@westnordost As issues on F-Droid are now solved, maybe it's time I take your app off my repo to avoid confusion (for folks using my repo, it would otherwise mean to closely check the source and not pick the wrong one; they better go with the "official repo" then). When need arises, let me know and I re-list it (I'm just "archiving" the metadata, so adding it back is a snip with the fingers).

Just thought it fair to let you know :wink:
