### ISSUE TITLE
All time i have null island location

### ISSUE THREAD

**Issue by siampour** [westnordost/StreetComplete#710]
Hi
in Android 7 on mi5s device with location permission i have wrong location in null island all time

**Comment by westnordost** [comment]
What is null island?

On 27 November 2017 07:25:17 CET, siampour <notifications@github.com> wrote:
>Hi
>in Android 7 on mi5s device with location permission i have wrong
>location in null island all time
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/710

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by HolgerJeromin** [comment]
Coordinate 0,0

**Comment by westnordost** [comment]
@siampour, what happens when you press on the GPS button on the lower right corner? For the location to work, you need
1. grant permission
2. turn on location
3. actually get a location (from GPS/Wifi/...)

Also, do you get a location in other apps? You are the first one to report this problem. Consider consulting also mi5s guides on that topic, it seems to be that there are some problems with this.

**Comment by siampour** [comment]
When i press the GPS button map located to the null island in 0,0 coordinate with gran permission
in other apps like osmand  i have the correct location 
https://preview.ibb.co/ix7ycm/Screenshot_2017_11_28_11_12_52_979_de_westnordost_streetcomplete_debug.png

**Comment by rugk** [comment]
LOL, it is even la labeled? 😆

**Comment by westnordost** [comment]
@siampour Okay, so both permission is granted and location is enabled.

For location updates, the [LOST library](https://github.com/mapzen/lost) is used, which uses the usual Android system GPS providers to find the location. 

However, to me, since for all the other users the location updates are working just fine, the most obvious cause of your problem seems to be that there is a problem generally with GPS on Mi5s. Not that it is not working at all, but that it seems to have problems finding a first fix.

And indeed, [searching for it on Google, you find a lot of other people who have problems with their GPS on this device](https://www.google.de/search?q=mi5s+gps). I think you are well advised if you read through these posts there to try to find a solution, perhaps update your OS, download GPS analyzer tools etc.
As far as I see it, there is nothing this project or LOST can do to solve this problem for you.

**Comment by siampour** [comment]
Read this 
https://stackoverflow.com/questions/7644063/getting-0-0-for-latitude-and-longitude-while-showing-current-location-in-map/8157308#8157308

> 1)Open Google Maps app and click button on map to get current location.
> 2)When you allow Google map permission, then only other apps permission will work. (and I feel this is big bug)
> 3)Now go to your app and try to get current location and it will work.

its a bug in android but some other apps prevent from that

**Comment by westnordost** [comment]
So, the cited "solution" is working for you?

**Comment by siampour** [comment]
not working

**Comment by westnordost** [comment]
Well, then you'll have to look for a solution with mi5s, nothing either LOST or this app can do about.
