### ISSUE TITLE
Privacy Statement: Location Implications

### ISSUE THREAD

**Issue by ax3l** [westnordost/StreetComplete#72]
Thread split from #63 (sry for going OT there):

> What do you think about additionally adding [in the privacy statement] a small note / paragraph in "Location" that due to the contributions in OSM the actual positions you likely visited are very easily identifiable, even correlated with time. People should be aware of that.

**Comment by westnordost** [comment]
Hmm, there is this sentence right before the location paragraph:

> Editing the OpenStreetMap anonymously is not possible, so any changes you make are made with your OSM user account, which also means that your changes to the map are visible publicly on the openstreetmap website.

Don't you think this is enough?

**Comment by ax3l** [comment]
You could also write there more explicitly :

"... which also means that your changes to the map (including implicitly your location and when you mapped) are visible publicly on the openstreetmap website."

I just think people should be aware that accounts can be connected and eg their home is easily derivible from their edits.

**Comment by gdt** [comment]
I suspect I'm one of the more extreme people in terms of being privacy-conscious.  I think the wording is good as is, but might add "and attributable to you" to make that obvious without too many additional words.  In general I think privacy statements should be clear about what happens, and not be so concerned about consequences.

It would be good if it's clear that quests are uploaded immediately on completion.  That's reasonable given the app design, but it's different from how josm/vespucci work.

Perhaps because I'm already an OSM editor, it's obvious that my quest solution changesets are associated with my OSM credentials.   If I'm someplace that I don't want to admit being, I don't run StreetComplete  or Vespucci.   My privacy concerns have been more along the lines of what information is transmitted simply by opening up the app, in terms of tile and overpass queries, with questions about if they are associated with username, and if they are rounded sufficiently to avoid giving fine-grained location to the server.    I might also wonder about being able to do quests and delay uploading -- generally, the fact that I was someplace yesterday I consider much less sensitive than where I am right now.

**Comment by westnordost** [comment]
I changed the last sentence before the Location paragraph to:

"Editing the OpenStreetMap anonymously is not possible, so any changes you make are made with your OSM user account. This means, that the date, content and implicitly the location of your changes are visible publicly on the openstreetmap website and are attributable to your account."

**Comment by ax3l** [comment]
> "and attributable to you" ... without too many additional words

perfect, I agree fully.

> It would be good if it's clear that quests are uploaded immediately on completion

unfortunately, that needs/is about to change anyway, since that is not the way OSM edits are supposed to work: #21

**Comment by westnordost** [comment]
Right. I will leave the formulation the same though, because "location" can also mean an area.
