### ISSUE TITLE
Empty opening_hours

### ISSUE THREAD

**Issue by robybully** [westnordost/StreetComplete#721]
StreetComplete adds empty strings ("") as opening_hours to database.

Example: 
https://www.openstreetmap.org/changeset/54502958
https://www.openstreetmap.org/changeset/54517668

I don't know if it is user related, but it should be avoided. 
This may apply also for other key and values.

**Comment by westnordost** [comment]
This happens if the user answers that there are no regular opening hours - the user is then presented an input field where he has to input an opening hours description (such as "by appointment") - and the user simply leaves the form empty.
I agree that this is not acceptable and the app should not let the user do that.

Perhaps the user should be contacted why he did that - if it was deliberate or not. It might be that the user was missing an answer option in the app and that is why he did that.

**Comment by rugk** [comment]
> Perhaps the user should be contacted why he did that - if it was deliberate or not. It might be that the user was missing an answer option in the app and that is why he did that.

Great idea! @robybully can you do so?

**Comment by robybully** [comment]
Yes, I will ask him.

**Comment by robybully** [comment]
I phoned with the user, he confirms that he answers the quest with "this object has no opening_hours". This results in an empty string "" in the opening_hours value.
See changeset https://openstreetmap.org/changeset/54726026 we used for a test.

**Comment by westnordost** [comment]
By the way, the real problem here is what to do if the shop has no opening hours posted at all, not even "per appointment". In Thailand and Myanmar, only the fancy places will have anything posted.

I guess most of these places will still have informal opening hours but some really have nothing regular. I don't know how this could be tagged.
Perhaps the error message when trying to specify no description for "no regular opening hours" should include that when nothing is posted, the shop owner should be asked about the OH.

**Comment by westnordost** [comment]
So it now opens an error dialog, which also closes the previous input dialog, describing that the user needs to describe what is on the sign or if there is no sign, ask for the opening hours inside. 

Not too user friendly (both requiring the user to do that and to close the input dialog), but I do not see any other possibility to do that.
