### ISSUE TITLE
Add cobblestone:flattened to the default paved surface types

### ISSUE THREAD

**Issue by afmenez** [westnordost/StreetComplete#728]
The "cobblestone:flattened" is the most common surface type where I live, and I believe it should be one of the main paved surface types.  Probably replacing "wood".

**Comment by westnordost** [comment]
Do you have a picture? For me, flattened cobblestone is the same as sett because what makes sett stand apart from cobblestone is that it is quarried for roadbuilding to have a flat surface. The shape of each stone, be it quadratic, rectangular or round does not really matter.

Am 18. Dezember 2017 19:57:17 GMT+07:00 schrieb Alexandre Folle de Menezes <notifications@github.com>:
>The "cobblestone:flattened" is the most common surface type where I
>live, and I believe it should be one of the main paved surface types. 
>Probably replacing "wood".
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/728

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by afmenez** [comment]
To me sett is always rectangular, and that's the definition on [Wikipedia](https://en.wikipedia.org/wiki/Sett_%28paving%29): "broadly rectangular quarried stone used for paving roads".

**Comment by afmenez** [comment]
Let me explain my motivation: if you are driving, there is indeed no difference between sett and cobblestone:flattened.  But if you are on a bicycle, the ride is very different.  I would even say that when routing for bicycles, the algorithm could include sett but avoid cobblestone:flattened.

**Comment by westnordost** [comment]
Hmm but do you have a pic of what exactly of a pavement you mean? (That in your neighbourhood)

**Comment by matkoniecz** [comment]
What is the difference between cobblestone:flattened and cobblestone? Where it is documented?

For example osm wiki currectly gives https://wiki.openstreetmap.org/wiki/File:Granite_Setts.jpg as example of surface=cobblestone at https://wiki.openstreetmap.org/wiki/Key:surface

**Comment by afmenez** [comment]
The wiki is wrong.
-Cobblestone: irregular shaped stones and irregular sizes, the ride is very rough;
-Cobblestone:flattened: only one of the sides is flat, the pavement is smooth when new but the stones tend to move with time;
-Sett: all sides of each stone are flat, and they all have similar size. The pavement is stable and the ride is smooth;

**Comment by matkoniecz** [comment]
Is this tagging method documented anywhere on the OSM wiki?

**Comment by afmenez** [comment]
Nope, I believe it needs fixing.
I just had a discussion on the Brazilian OSM group, and this is how we map here.

**Comment by santamariense** [comment]
I agree with @afmenez. Without no differenciation, the app ends by adding wrong surface tag.

**Comment by ftrebien** [comment]
From the OSM wiki (which might need corrections):

- sett: formed from _stones_ quarried or worked to a _regular_ shape
- cobblestone: _colloquial_ meaning here, and therefore _includes_ the type of stones that would more precisely be called "setts"
- cobblestone:flattened: _neither a correct name_, like sett (cobblestone is by definition not shaped into any form), _nor a colloquially used name_, like cobblestone

From which I conclude:

- sett is not necessarily rectangular, though it is usually so (it might be hexagonal, for example)
- cobblestone includes other types of stones, such as irregular stones
- cobblestone:flattened should be avoided due to its imprecise definition; it is also [very rare](https://taginfo.openstreetmap.org/keys/surface#values)

**Comment by rugk** [comment]
Ah so simply? Sett - has some (strict) form and is "deliberately" formed.
And cobblestone seem to be the one you find in small towns or so where they have these things formed in any way, how it was shaped/collected or however such things are produced…

**Comment by althio** [comment]
I almost agree with @ftrebien here.
In fact I agree more with your [tagging list message](https://lists.openstreetmap.org/pipermail/tagging/2018-January/034821.html).

> To make differences more evident, I believe we could define in the wiki:
> - pebblestone: loose small rounded natural stones
> - cobblestone: jointed large rounded natural stones [1]
> - sett: large natural stones cut to a flat top, usually jointed and
forming a regular pattern [2]
> - paving_stones: smooth tightly-fitting natural stones or artificial
blocks, usually forming a regular pattern [3]
>
> This would change the wiki in the following ways:
> - cobblestone: no longer a superset of sett
> - sett: no longer required to be always regular

**Comment by westnordost** [comment]
@althio This is how interpret the current wiki (anyway). @ftrebien also posted this in the forum, let's limit the amount of communication channel and not also talk about that here.

Only this:

> cobblestone: no longer a superset of sett

I can only repeat [what I said in a discussion in the German forum about sett/cobblestone last year](https://translate.google.de/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fforum.openstreetmap.org%2Fviewtopic.php%3Fid%3D58116&edit-text=&act=url): Existing tags cannot be redefined. If they were, it would immediately make all existing tagging wrong.
That is why I proposed to instead define a new tag, i.e. `natural_cobblestone`, that would fit that  more tight definition (but got no feedback for that) while `cobblestone` is defined as it was before (could be sett, could be undressed stones).

(Please read the whole linked thread)

**Comment by althio** [comment]
@westnordost 
> @ftrebien also posted this in the forum, let's limit the amount of communication channel and not also talk about that here.

I don't know which forum you are talking about.
@ftrebien posted on the tagging list, I gave notice, quote and link here, I responded there.

> what I said in a discussion in the German forum [...]
> (Please read the whole linked thread)

No thank you. 🙄 
Please use the tagging mailing list if you have something to contribute or to discuss globally about tagging, not the German forum.

**Comment by westnordost** [comment]
> I don't know which forum you are talking about.

https://forum.openstreetmap.org/viewtopic.php?id=61042

**Comment by ftrebien** [comment]
@westnordost Since 3rd May 2015, the [German wiki](https://wiki.openstreetmap.org/wiki/Template:De:Map_Features:surface) refers to sett as "flatter than surface=cobblestones" ("ebener als surface=cobblestones") and to cobblestones as "uncut natural stone; the surface is rounded, with no prescribed shape; thereby surfaces are uneven" ("unbehauenem Naturstein. Die Oberfläche ist gerundet, es gibt keine vorgegebene Form. Damit sind Flächen uneben"). The current images for cobblestones and setts have remained the same on the German wiki since then too. So I believe the new definition should not affect German mappers so negatively. Most edits in Germany in the last 30 months have probably followed the German wiki text, which agrees closely with the proposed new definitions. But @althio is right, this must be discussed in the tagging list.

**Comment by westnordost** [comment]
I've followed the recent [forum discussion](https://forum.openstreetmap.org/viewtopic.php?id=61042), I would say it came to a conclusion at least so far as this ticket can be closed.

(In a nutshell, "flattened cobblestone" would still count as cobblestone, "Portuguese cobblestone", as sett)

**Comment by ftrebien** [comment]
@westnordost I agree that cobblestone:flattened should be discouraged because of current and past definitions of both cobblestone:flattened and cobblestone.
