### ISSUE TITLE
Wheelchair accessibility on public toilets

### ISSUE THREAD

**Issue by PanierAvide** [westnordost/StreetComplete#737]
### General
Affected key(s) (or tags) to be modified: [wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair)
Question asked: **Are thèse toilets accessible in wheelchair?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)

### Ideas for implementation
As there is already a quest for wheelchairs in businesses, should the implémentation extend this quest or be a separate one ?

**Element selection:** 

**Metadata needed:** 

**Proposed GUI:**

**Comment by westnordost** [comment]
I think for a toilet it is not enough that there are no stairs to be ♿-accessible, there must be some sort of special room for that.
So the explanatory text must be different. Otherwise, perhaps rather the public transport wheelchair quest could be extended (because it is a public facility, not a business).
I have no strong opinion on whether to have it as an own quest or include it in another.

Am 27. Dezember 2017 14:22:13 GMT+07:00 schrieb Adrien Pavie <notifications@github.com>:
>### General
>Affected key(s) (or tags) to be modified:
>[wheelchair](https://wiki.openstreetmap.org/wiki/Key:wheelchair)
>Question asked: **Are thèse toilets accessible in wheelchair?**
>
>### Checklist
>Checklist for quest suggestions (see guidelines):
>- [x] 🚧 To be added tag is established and has a useful purpose
>- [x] 🤔 Any answer the user can give must have an equivalent tagging
>(Quest should not reappear to other users when solved by one)
>- [x] 🐿️ Easily answerable by everyone from the outside but a survey
>is necessary 
>- [x] 💤 Not an overwhelming percentage of elements have the same
>answer (No spam)
>- [x] 🕓 Applies to a reasonable number of elements (Worth the effort)
>
>### Ideas for implementation
>As there is already a quest for wheelchairs in businesses, should the
>implémentation extend this quest or be a separate one ?
>
>
>**Element selection:** 
>
>
>**Metadata needed:** 
>
>
>**Proposed GUI:** 
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/737

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PanierAvide** [comment]
Yes wheelchair accessible toilets requires no stairs, large door, and adapted height for handwashing. Maybe a separate quest makes more sense for clearer explanation. If you agree with that I will work on a pull-request to implement this in the next days :-)

**Comment by westnordost** [comment]
👍

**Comment by rugk** [comment]
However, compared to other facilities it is often easy to get out (from the outside) if such a toilet is accessible.
Because usually, such toilets ate specially labeled, there are special signs and so on.
And is they are not, it is very likely they are *not* wheelchair accessible.
IMHO the quest should make it clear. Maybe even ask whether a toilet is specifically labeled or just make a button "there is a sign".

**Comment by PanierAvide** [comment]
So the quest could be asked that way :
Is it possible to use these toilets with a wheelchair (if so, this symbol will be visible) ?
![Icon](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Wheelchair_Accessible_-_The_Noun_Project.svg/240px-Wheelchair_Accessible_-_The_Noun_Project.svg.png)
* Yes
* No
* I'm not sure
