### ISSUE TITLE
Better GPS Fix

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#743]
At moment i have to pick a random destination in Osmand so this ap runs in background. Otherwise I'm not able to get a GPS Fix.

Fairphone 2
Android 6.0.1

**Comment by esilja** [comment]
I also experience this problem. Nexus 5x, Android 8.1.0.

**Comment by westnordost** [comment]
I really have no idea, it works for me.

This app is using an external library to get location updates, called LOST (from mapzen), but that library just uses the Android system calls.

Most apps, perhaps also Osmand, use the Google Location Services instead of the normal system calls. It seems to be faster acquiring a first Gps fix for sone reason, but it's closed source.

Please open a ticket in the LOST issue tracker instead.


Am 1. Januar 2018 16:49:39 OEZ schrieb esilja <notifications@github.com>:
>I also experience this problem. Nexus 5x, Android 8.1.0.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/743#issuecomment-354657068

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
> Please open a ticket in the LOST issue tracker instead.

**Comment by Mannshoch** [comment]
I don't know what's different between Osmand and StreetComplete but Osmand it self need another App to to get fast GPS Fix here is the Problem, that Osmand is not able to use GSM locations to get the GPS Fix.

https://github.com/osmandapp/Osmand/issues/3833
