### ISSUE TITLE
swap "actually used" and "some QA tools complain" priority

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#758]
I think that data that is really used is better to collect that one where some random QA tool complain.

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/QuestModule.java#L63

This change is motivated mostly by fact that in many place maxspeed and surface quest is much more useful than bikeway quest.

First two always provide useful information, bikeway quest is typically repetitive, "nothing on left lane, nothing on right lane, OK"

In terms of user experience and data collected it would be preferable to degrade AddCycleway quest below AddRoadSurface, AddMaxSpeed, AddOpeningHours.

**Comment by westnordost** [comment]
I have no strong opinion on that. You can create a PR for that and I'll merge it.

**Comment by matkoniecz** [comment]
I made and submitted PR. I went a bit further and moved entire "QA complains" below "data is used".

Still, only bikeway quest got degraded to a lower priority.

**Comment by matkoniecz** [comment]
As side effect number of people complaining about cycleway:both=no appearing everywhere should be now lower.

**Comment by rugk** [comment]
Another good side effect I see (which should always also be considered when setting quest proprieties): For the user it is way easier to answer a simple quest such as the street surface one. The bicycle quest is much harder and you could actually have problems to (fastly) see the "correct" answer. So this then also blocks the ability to answer the other quests, which you could answer. (but, I know, there are other issues for that)

On the other hand street surface quests are common, so in order not to make oit boring for the user the cycleway quest could also have a higher priority, because only then the user might see it and get that there is such an "existing" quest. 😉 
So as you see, that is quite hard to decide...
