### ISSUE TITLE
gate creating note for cycleway quest behind "select 'no' answer for both sides if no bicycle infrastructure is present"

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#768]
Multiple people created notes in bikeway quest rather than selecting "no" for both sides.

Maybe it would be a good idea to have "note, you can select that there is no bicycle infrastructure by selecting "no" for both sides" dialog before allowing user to create a note? Similar to how one gets warning before selecting "no name" for street name quest?

Some recently encountered examples:

https://www.openstreetmap.org/note/1267398

https://www.openstreetmap.org/note/1262510

https://www.openstreetmap.org/note/1245283 (probably)

https://www.openstreetmap.org/note/1250200

Most of notes from this quest that I was able to understand are of this type (see https://ent8r.github.io/NotesReview/expert/?query=StreetComplete&limit=3000&start=true ).

**Comment by smichel17** [comment]
At least in English, I think the problem is a phrasing mismatch between the question (Is there a cycleway in this street?) and answers [Okay | Can't Say].

I think it would make more sense to use the following structure:

Is there a cycleway in this street? [Yes | No | Can't Say]

Yes -> Open the current dialog to select the type of cycleway, with prompt, "What kind of cycleway does this street have? <picker> [Okay | Cancel]"

No -> Same as if I had selected no cycleway on both sides of the street and pressed okay.

Can't say -> Same as current.

---

This would also make it significantly faster to mark no cycleway, which would be really nice in places like the US where they are not (yet) very common and so I'm hitting "None" a lot.

**Comment by westnordost** [comment]
@smichel17 The current dialog is a little bit more complex. I.e. you have to select both sides. To have all this UI in just a dialog seems too volatile to me. Also, that "dialog" would then open another dialog on top of it to allow for cycleway type selection. This kind dialog-stacking is a form of UX I want to avoid where possible.

**Comment by westnordost** [comment]
One could add an "other answer" option named "No bicycle infrastructure whatsoever" or alike perhaps.

**Comment by westnordost** [comment]
"No bicycle infrastructure" even shorter :-)

**Comment by matkoniecz** [comment]
Probably some people will be confused by bicycle infrastructure like parkings or bicycle rental stations but I have no idea how to avoid this issue.

**Comment by rugk** [comment]
"No way for bicycles" (just somehow avoid the term "infrastructure")

**Comment by matkoniecz** [comment]
> "No way for bicycles"

This may get confusing with shared lanes (bus + bicycles lane, contraflow without dedicated lane, bicycles allowed on footway...)

**Comment by smichel17** [comment]
@westnordost The way I envision it working does not have the problems you brought up, I think. I will make a mockup to clarify.

**Comment by smichel17** [comment]
![cycleway](https://user-images.githubusercontent.com/6563664/34917880-d8046cb8-f943-11e7-9b13-d3a56a5f3388.jpg)

**Comment by westnordost** [comment]
Ah! Well, this is interesting. Hmm... but it would not be that simple to implement.

**Comment by smichel17** [comment]
Don't we already have a slide-up animation? In that case the center part should just be a matter of having a hidden view. The hard part, I think, would be changing the bottom labels without opening a new dialog, as I assume that's currently handled by android.

**Comment by westnordost** [comment]
Hm, not at all simple. I think I prefer the "other answer" option, looking at the effort to tear that all up and refactor to enable this.

Also, I said that earlier, I think: I do not want to make it (much) easier to answer "no, no cycleway" than specifying the cycleway. Otherwise, it may encourage users to sweep through whole areas of towns without even doing a survey.
See for example here: https://www.reddit.com/r/Android/comments/6dqdl6/streetcomplete_the_easiest_way_to_contribute_to/di5l5ba/

**Comment by westnordost** [comment]
I decided to, after all, not implement this, but instead only change the wording of the question slightly: _"Is there a cycleway here? **What type?**"_ so that the answer format ("OK" instead of "Yes/No") is not at odds with the question.

The _"No bicycle infrastructure"_ answer could lead to wrong taggings in the case where instead of "no cycleway", "cycles go implicitly/explicitly on sidewalk"
