### ISSUE TITLE
Avoid asking for street names on minor connectors

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#77]
I often see a road connecting to a larger road in a T junction, with 10m of dual carriageway as one is expected to keep right around an island, or sometimes one of the ways is 2-way and one of them 1-way.   Sometimes one of these 10m segments doesn't have  a name.  Arguably the main road has the name and whether what is effectively a slip road has a name or not is perhaps an interesting tagging discussion, but adds little value to the map.   A road with real extent that isn't named is a much bigger thing.

It would be nice to split the naming quests into really missing names and sort-of-slip-road pedantry, so that I could disable the latter.  Unfortunately I don't have a great idea for how to separate this programmatically.   I would suggest ways that are < 20m, with each end connected to a named way, and those ways connected to each other with total distance < 3x the unnamed one.

**Comment by westnordost** [comment]
You can choose from "Other answers..." -> "It just connects two roads".

I'd argue that those carriageways are wrongly tagged as primary, secondary, tertiary. The quest offers you to re-tag it as primary_link, secondary_link or tertiary_link. Those link roads have no name.

For unknown reasons, there is no unclassified_link (defined in the wiki), so, I don't know how to deal with that.

The point is, the app cannot easily determine what is a connecting road with no name and what is a small section of road (i.e. split because of turn lanes, bus routes, turn restriction etc etc) with no name, so it is asking a human.

**Comment by gdt** [comment]
These aren't really link roads.   It's just that a road, sometimes tertiary, sometimes unclassified, sometimes residential,  has  a split around an island.  There's no strong sense of which one is real and which one is link.     Here's an example: https://osm.org/go/ZfI0SKhr_--?m=

I'm not really arguing that they shouldn't have a name.  My point is instead that the fact that they are unnamed is fairly unimportant, and in general I'm finding a lot of unimportant quest clutter where I would prefer to see the ones that I think matter more.   But I agree that it's very hard to figure this out programmatically.

**Comment by westnordost** [comment]
Hmm, I will close this one now as it is not really solveable.
