### ISSUE TITLE
What is the Different between following answers for streets with cycling?

### ISSUE THREAD

**Issue by Mannshoch** [westnordost/StreetComplete#786]
I'm not sure what the Answer "kein" (none) means. If cycling is forbidden then the answer may should say forbidden. If it's not forbidden then the Answer is similar to the other one.
![img_20180111_202119](https://user-images.githubusercontent.com/7795891/35221625-23472868-ff7b-11e7-9843-5a797b9b3e99.jpg)

**Comment by rugk** [comment]
Cycling does not have to be forbitten, you can also just have no lane, i,.e. you share the road with cars and so on.

As the right image shows, for that shared lane, there must be **explicit markings** on the road.

**Comment by Mannshoch** [comment]
Then I would prefer, "No markings available" (Keine Markierungen vorhanden) as text.

**Comment by westnordost** [comment]
Other opinions? (You can also add thumbs down/thumbs up)

**Comment by lokaman** [comment]
I like the term "no markings available" since it describes the purpose best. There are some types of cycle "infrastructure" which have some type of marking (like the share lane logo, or the "Schutzstreifen" in Germany) but are not useful at all - they are supposed to encourage people to cycle on a "normal" road. Often they're on one side of the road, encouraging people not to "take the lane".

Questions which arise - since "markings" are also present on other types of cycle infrastructure - can it cause false tagging?

Another Question is how to tag the "Schutzstreifen" - together with the shared lane? Would be right, but not specific (one tag missing?). Or give to two options - which may will be barely used - would consider "Schutzstreifen" as german-only, and shared lane markings as a UK / US cycle "infrastructure". May open a issue to this topic, when I have more time.

**Comment by westnordost** [comment]
How to tag "Schutzstreifen" is a hotly discussed topic in the German forums, there are different opinions.
Personally, I would tag such a thing as a regular **bicycle lane** if both the lane is broad enough for cyclists and the rest of the road is broad enough for cars not to have to sometimes drive on that lane and tag it as **shared lane** otherwise.

**Comment by rugk** [comment]
> shared lane markings as a UK / US cycle "infrastructure"

No, AFAIK it is also visible/possible in Germany. Rare, I'd say, but possible.

**Comment by westnordost** [comment]
I have seen those markings just in the parallel street from where I live.

**Comment by lokaman** [comment]
@westnordost and this is the problem - there are some times markings indicating some type of "we want you to know you can cycle here" (shared lane logo with the "double roof", most "Schutzstreifen" I know). And there are markings indicating a totally different type of infrastructure - the type you described is probably a "bicycle street" ("Fahrradstraße") if it has a sign (https://upload.wikimedia.org/wikipedia/commons/b/bf/Zeichen_244_-_Beginn_der_Fahrradstra%C3%9Fe,_StVO_1997.svg in GER).

There may be no strict legal rules on markings - at least this should be researched. 

Somehow we need to fix the problem that there are crazy forms of cycle infrastructure which look different in different countries.

Will look into this in a few weeks.

**Comment by westnordost** [comment]
No, it's not, it is a normal street.

**Comment by westnordost** [comment]
I will close this and adapt the translation for German. In English, it is _"lane shared **explicitly** with other traffic"_, in German, it does not say "explicitly", but it should.
