### ISSUE TITLE
Cycleway quest: Add "opther answer" for forbitten cycling

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#787]
https://github.com/westnordost/StreetComplete/issues/786 inspired me for that. Currently you can only specify that no lane is there, but you e.g. may know that cycling is forbitten, and, as such, you could instruct the app to mark it as forbitten for bicycles.

**Comment by westnordost** [comment]
I thought about this today, and actually I will close this, because:

1. I fear that if I implemented this option, then there is still room for misunderstanding _"Cyclists forbidden here":
People might think that this refers to the street - i.e. in Germany, cyclists are forbidden on the road if there is a signed cycleway, or even the other way round, that it may refer to that cyclists are forbidden on the area that makes up the sidewalk+cycleway usually because there is no cycleway. And then, in countries with less explicit rules posted everywhere, people might get the idea to tag something as "forbidden" if the road is obviously not suitable for bicycles( / no bicycles can be seen) because it might be "informally" forbidden. Believe me, I have seen a lot of roads that had taggings like` horse=no, bicycle=no, foot=no, ...`. This dives into the whole topic of that the surveyor is supposed to have intrinsic knowledge about (unposted) rules in a country, even though for this quest, he is just asked to indicate the physical availability of bicycle infrastructure. (TBH the current quest already dives a bit into the topic in "explicitly shared sidewalk" vs. "implicitly shared sidewalk", but nothing I can do about there.)
2. It's somewhat rare that roads are **explicitly** signed as not allowing bicycles
3. And, as usual, the user has always the possibility to leave a note and describe the situation.
