### ISSUE TITLE
Let us customize the notes quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#789]
Currently the notes quest is always pinned to the top, cannot be disabled and one cannot change the order of it.

I sea no reason to treat this quest in a special way, so why do you do so?

Just let us move it, too.

**Comment by westnordost** [comment]
Because an existing note blocks all quests below it.

A note is there to indicate a problem with the data there, especially in the context of notes that have been created with StreetComplete, as it creates the quest-related notes exactly on that element.
A note says "hey, something is wrong with this element", so no quests for this should be created.

I.e. someone answered "Actually, this shop does not exist anymore, there is now a Cafè called Amaretto", then, of course, the app cannot not use the current data as it is in the OSM database as a base for creating a quest, because one thing or another might be incorrect now.

This treatment of notes is hardwired into StreetComplete, and it will not change.

**Comment by rugk** [comment]
Thanks for that answer… I'll add that to the FAQ, I think it fits there.
