### ISSUE TITLE
Complex Buildings with Relation

### ISSUE THREAD

**Issue by ax3l** [westnordost/StreetComplete#79]
I found this funny looking collection of quests yesterday on Dresden's [Hofkirche](http://www.openstreetmap.org/way/14879154) and think that might be not intended.

![hofkirche](https://cloud.githubusercontent.com/assets/1353258/24586194/3349e69c-179b-11e7-901b-ee319fc35adb.png)

Maybe relations of complex builds need to be taken into account?

**Comment by westnordost** [comment]
Oh my god

**Comment by westnordost** [comment]
These quests show because the height of the sections of the church are defined with the undocumented tag `building:height` (instead of `height`), which SC doesn't recognize.

Okay, so I will not show the quest if this tag is defined, and, you know what, I will just disable the quest for all `building:part`s for now.
Later, I will implement that quests for `building:part`s are only shown for building parts within residential, commercial etc. buildings - if at all.

**Comment by ax3l** [comment]
Great! I will at the same time fix this building itself to use the correct `height` tag via OSM iD.

**Comment by westnordost** [comment]
Well, it's used almost 50000 times.

**Comment by ax3l** [comment]
Globally you mean, on all OSM buildings.
I was just referring to that church with its few dozen sub-entries.
