### ISSUE TITLE
Add setting for disabling some kinds of quests

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#8]
I see a vast number of opening hours quests.  That's fine for many, I suspect, but I'm not that interested in opening hours, and often it's awkward.   So I'd like to be able to download and see other types.  I suggest a setting with checkboxes for the various kinds of quests.

**Comment by westnordost** [comment]
Okay, actually there are only two normal quests types right now - "Add road name" and "Add opening hours". Since in the usual well-surveyed city, there are just about no roads without names left, all you see everywhere are these opening hours.

So, just be patient. Over the time, new and other quest types will follow.

Then, later, when there are a couple dozen quest types, we can discuss about better filtering or ordering the quest types. Now, with just very few around, this does not make so much sense.

Don't get me wrong, I too see much room for improvement with the current implementation but right now, this is not a topic for me.
