### ISSUE TITLE
maxspeed=<countrycode>:<zone type> in US

### ISSUE THREAD

**Issue by cliffordsnow** [westnordost/StreetComplete#813]
I noticed a new user adding maxspeed=US:urban. I've lived in many cities across the US, and have never seen a consistent maxspeed for anything, from residential to motorways (Interstate highways) 

Can that feature be turned off for countries without established speed limits?

The changeset, https://openstreetmap.org/changeset/55834170 was by a new users that has probably never seen how streets are tagged.

**Comment by westnordost** [comment]
The user added [`maxspeed:type`](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type), not `maxspeed`.

**Comment by matkoniecz** [comment]
> was by a new users that has probably never seen how streets are tagged.

In StreetComplete user is not selecting tag, app is doing this (user is answering questions that should be easy to answer using common sense and general knowledge, without knowledge about OSM tagging)

> have never seen a consistent maxspeed for anything

So tagging using by SC is not conflicting with local consensus, because it does not exists?

> without established speed limits

Are you claiming that USA has no concept of speed limits? AFAIK it is not true.

**Comment by cliffordsnow** [comment]
Yes - user is just answering questions and the app created the appropriate
tags. If I were to see the option for entering speed limit that says
US:urban or something similar I would not accept it because it's not
defined.

The US does have established speed limits as you stated, just but not
documented on the wiki. (https://wiki.openstreetmap.org/wiki/Speed_limits)
For the case I referenced, maxspeed:type=US:urban is not a valid value. It
should be a number. The only exception is the variable speed limit ways,
which is tagged maxspeed:variable=*

To document speed limits in the US would require looking at every state,
county and city.

**Comment by westnordost** [comment]
How is the fact that the value of implicit speed limits are not documented in the wiki relevant here?

Am 29. Januar 2018 00:11:21 MEZ schrieb Clifford Snow <notifications@github.com>:
>Yes - user is just answering questions and the app created the
>appropriate
>tags. If I were to see the option for entering speed limit that says
>US:urban or something similar I would not accept it because it's not
>defined.
>
>The US does have established speed limits as you stated, just but not
>documented on the wiki.
>(https://wiki.openstreetmap.org/wiki/Speed_limits)
>For the case I referenced, maxspeed:type=US:urban is not a valid value.
>It
>should be a number. The only exception is the variable speed limit
>ways,
>which is tagged maxspeed:variable=*
>
>To document speed limits in the US would require looking at every
>state,
>county and city.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/813#issuecomment-361105293

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Do you mean it should be i.e. maxspeed:type=US-NY:urban?

Am 29. Januar 2018 00:11:21 MEZ schrieb Clifford Snow <notifications@github.com>:
>Yes - user is just answering questions and the app created the
>appropriate
>tags. If I were to see the option for entering speed limit that says
>US:urban or something similar I would not accept it because it's not
>defined.
>
>The US does have established speed limits as you stated, just but not
>documented on the wiki.
>(https://wiki.openstreetmap.org/wiki/Speed_limits)
>For the case I referenced, maxspeed:type=US:urban is not a valid value.
>It
>should be a number. The only exception is the variable speed limit
>ways,
>which is tagged maxspeed:variable=*
>
>To document speed limits in the US would require looking at every
>state,
>county and city.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/813#issuecomment-361105293

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Carnildo** [comment]
The US does not have nationwide implicit speed limits.  Some states have implicit statewide speed limits, but those aren't often well-known, and the groupings vary from state to state, and sometimes within a state.

For example, California's implicit groups are "non-highway streets in residential and business districts, school zones, and senior zones", "undivided two-lane highways", and "all other highways".  Non-highway roads outside of urban areas don't appear to have an implicit speed limit other than "reasonable and prudent".

In comparison, Washington's implicit groups are "state highways", "county roads", and "city and town streets".  This covers everything, but literally the only place I've seen these speed limits mentioned is in the relevant section of the state law.  If you were to ask the average person what the speed limit is on a road without a speed limit sign, they couldn't tell you.

As a further complication, the city of Spokane, within Washington, has its own implicit groups: "arterials" and "all other roads".  Other cities may have their own implicit speed limits, but I'm not familiar with them.

A simple "maxspeed:type=US:urban" isn't meaningful.  You'd need tags such as "maxspeed:type="US-WA:county", "maxspeed:type=US-WA-Spokane:arterial", and "maxspeed:type=US-CA:undivided-highway".  And given that many of these implicit speed limits are not well-known, you're better off requiring that any speed limit in the United States be entered as a number.

**Comment by westnordost** [comment]
Ok, I understand. 

Though, if the implicit speed limit is not well known, how would a surveyor then be able to answer this with an explicit value?

Am 29. Januar 2018 09:57:43 MEZ schrieb Carnildo <notifications@github.com>:
>The US does not have nationwide implicit speed limits.  Some states
>have implicit statewide speed limits, but those aren't often
>well-known, and the groupings vary from state to state, and sometimes
>within a state.
>
>For example, California's implicit groups are "non-highway streets in
>residential and business districts, school zones, and senior zones",
>"undivided two-lane highways", and "all other highways".  Non-highway
>roads outside of urban areas don't appear to have an implicit speed
>limit other than "reasonable and prudent".
>
>In comparison, Washington's implicit groups are "state highways",
>"county roads", and "city and town streets".  This covers everything,
>but literally the only place I've seen these speed limits mentioned is
>in the relevant section of the state law.  If you were to ask the
>average person what the speed limit is on a road without a speed limit
>sign, they couldn't tell you.
>
>As a further complication, the city of Spokane, within Washington, has
>its own implicit groups: "arterials" and "all other roads".  Other
>cities may have their own implicit speed limits, but I'm not familiar
>with them.
>
>A simple "maxspeed:type=US:urban" isn't meaningful.  You'd need tags
>such as "maxspeed:type="US-WA:county",
>"maxspeed:type=US-WA-Spokane:arterial", and
>"maxspeed:type=US-CA:undivided-highway".  And given that many of these
>implicit speed limits are not well-known, you're better off requiring
>that any speed limit in the United States be entered as a number.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/813#issuecomment-361179340

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by cliffordsnow** [comment]
When I use the app if I know the speed limit I add it. For instance, in my
town, residential streets are mostly 25mph. In the county, unclassified are
35mph. Based on where I'm at, I know the speed limit. Other counties and
cities use other defaults. Unless I know what they are I don't add the
speed limit.

**Comment by westnordost** [comment]
It is good that you know this, but I fear that StreetComplete must do more here because it can not assume that every surveyor, like you, knows about the regulations what limits apply when and can be trusted to input the correct values without err.

As @Carnildo mentions, if it is irrelevant (in certain states) in the US whether a road is urban or rural for which implicit applies, StreetComplete should not record this. 
I already implemented a special rule for the United Kingdom, where this is also irrelevant if it is in or out of town but only whether it is a "dual carriageway" or a "single carriageway". So, in the UK, the app asks for that, not for urban vs. rural.

This kind of special rules need to be implemented for the US as well, ASAP, as for every week where StreetComplete asks for urban vs. rural in places where it is irrelevant is adding useless information.

Since no documentation exists yet in the OpenStreetMap wiki, we need to do the research here by ourselves. Let's use this issue for that. Perhaps, if we are fast (and perhaps you want to help) and the information is well available (in wikipedia?), an implementation can go into the next minor release.
If not, then I'd consider turning off the complete quest for the US in the next minor release, until we have the necessary information.

**Comment by matkoniecz** [comment]
https://en.m.wikipedia.org/wiki/Speed_limits_in_the_United_States_by_jurisdiction

**Comment by westnordost** [comment]
I am working through this source right now!

**Comment by westnordost** [comment]
Also using http://www.safemotorist.com/Alabama/Roads/speed.aspx (and other pages on same website as source):

Leaving out school zones, if mentioned, because school zones are posted. Perhaps an answer option like "there is no sign, but there is a school zone" or something could be added.

Also, for some states, there are explicit speed limits for alleys (usually 15 mph). This is interesting, as is it a good use case for the `service=alley` tagging (I guess) but irrelevant for this app, because it does not ask for speed limits on `service` roads.

From the wikipedia article and the other source, it is not always clear if the described limits are limits that are actually posted, or that the drivers are supposed to know (for the more complicated cases).

It would be good if someone else would go over each item in the list and also review if the research is correct. It would be good if several people would confirm or refute my findings.

.h2 A-F

| State | Ask for... | Comment |
| ----- | ---------- | ----- |
| Alabama (US-AL) | urban / rural |  |
| Alaska (US-AK) | residential district / business district / somewhere else | |
| American Samoa (AS) | urban / rural | (aka built-up areas / open road) |
| Arizona (US-AZ) | urban / rural | |
| Arkansas (US-AR) | urban / rural | sounds like question should even be asked for `highway=trunk` and `motorway`, but it may be that what is meant is that for every freeway within city limits, there will be signs |
| California (US-CA) | "business or residential district" / open road | California's "Basic Speed Law" seems to be reluctant to cough up some concrete max speed limits, but it comes down to that. Not sure if a distinction can be made between "built-up area" in general and "business or residential district" (think through streets in built-up areas, see Connecticut). If not, it would be simply "urban / rural" again. |
| Colorado (US-CO) | residential district / business districts / narrow, winding mountain roads / open mountain roads / rural roads | _"Home-rule cities can also adopt a blanket speed limit for the whole town, such as 25 mph, and it will be that unless otherwise posted."_ So, something like a slow-zone for the whole town, hmm. Also, not sure what "open mountain highways" are supposed to be and if there are really no limits posted in these cases. |
| Connecticut (US-CT) | urban / rural -> if urban, "residential streets and central business districts" / arterial roadway | sounds like question urban/rural should even be asked for freeways, but it may be that what is meant is that for every freeway within city limits, there will be signs. But perhaps for the arterials as well? |
| Delaware (US-DE) | urban / rural | |
| Florida (US-FL) | urban / rural | |

**Comment by westnordost** [comment]
It's by the way such a shitty tagging scheme that one has do dwelve into each legislation of each country just to _correctly_ tag "there is no speed limit sign", it's madness. There really should just be `maxspeed=implicit` or` maxspeed:type=implicit` or something like this... :-(

**Comment by matkoniecz** [comment]
Well, with maxspeed=implicit one would anyway need to survey to check is it urban/rural/"residential streets and central business districts" - and that depends on location...

But maxspeed:implicit=yes or something like that would probably make sense.

**Comment by westnordost** [comment]
I'll definitely not be able to research, review and implement all this for the next bugfix update. So I am disabling this quest for US for now.

**Comment by westnordost** [comment]
I now gave up going through that wikipedia article and that other source. This is all too ambigous and incomplete. This really requires to look into the actual law.

**Comment by westnordost** [comment]
I found a better source. An official government source: https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/summary_state_speed_laws_12th_edition_811769.pdf

Based on that source, I started putting the legislation into a YAML-based configuration file to showcase a possible format in which the implicit speed limits could be defined. See below.

```
US-AL:
  - maxspeed:type=US-AL:urban: 30 mph
  - surface=$UNPAVED: 35 mph
  - maxspeed:type=US-AL:rural: 45 mph
  - [highway=motorway, maxspeed:type=US-AL:interstate]: 70 mph
  - lanes>=4: 65 mph
  - 55 mph
US-AK:
  - highway=service: 15 mph
  - maxspeed:type=US-AK:business: 20 mph
  - maxspeed:type=US-AK:residential: 25 mph
  - 55 mph
US-AZ:
  - maxspeed:type=US-AZ:urban: 25 mph
  - [highway=motorway, maxspeed:type=US-AL:interstate]: 75 mph
  - 65 mph
US-AR:
  - maxspeed:type=US-AR:urban: 30 mph
  - 60 mph
```

However, I now recognize, that there are some open questions that need to be determined by the US community, I neither can nor want to simply define something here and it somewhat goes beyond the scope of this project to come up with something from scratch.
So, the following points should be put into consideration when developing a (`maxspeed:type`-based) scheme for defining implicit speed limits:
1. Some states define a max speed for alleys, but do not define what exactly constitutes an alley, can it be roughly assumed to be the same as `highway=service` (+`service=alley`)?
2. States usually set a specific statuary speed limit for interstate highways, but it is not clear if all roads tagged as `highway=motorway` are actually interstates. And also, the other way round, if all interstates are tagged as `highway=motorway`. If not, a tag like `maxspeed:type=US-XX:interstate` would be necessary.
3. Based on my first research, many states define a different statuary speed limit for freeways in urban areas and a different one for freeways in rural areas. If this is true, and freeways are to be translated as `highway=motorway` and/or `trunk`, then this might need another `maxspeed:type` tag to differenciate.
3. Some states define explicitly a speed limit for school zones. It is the question if this needs another `maxspeed:type` tag then.
4. Some states define separate max speeds for 1. business districts, 2. residential districts, a few even for 3. suburban districts and 4. "arterial roadways". So there must be (for these states) some `maxspeed:type` definitions then.
5. Some states define different speed limits based on if the highway is divided or not (single or dual carriageway). The question is, if that information should be regarded as inferrable from` oneway=yes`. If not, then again it must be tagged with some tag for `maxspeed:type` (like in Great Britain with `nsl_dual` and `nsl_single`).
6. Some states define different speed limits based on the number of lanes - usually for 4 or more. This seems straightforward to infer from the `lanes` key, but perhaps not if one thinks about dual carriageway highways, which are mapped as two separate ways in OSM.

In any case, the re-enablement of maxspeed quests for the United States is blocked until either the US community came together and developed a set of rules on that or a tag like `maxspeed:implicit=yes` would be accepted.

**Comment by matkoniecz** [comment]
> If not, a tag like maxspeed:type=US-XX:interstate

Or maybe tag Interstate status (of not equivalent to highway=motorway), work something like motorway=yes.

**Comment by cliffordsnow** [comment]
I've posted this ticket on the [US Slack](Sign up at https://osmus-slack.herokuapp.com/) community. 

For my state, Washington, the NHTSA has too many qualifiers that allow local government to change the maxspeed based on local conditions. For example, I take a scenic route on a state highway. It should be a 60MPH section, but because of the curves and limited shoulders, it's limited to 40MPH.

@matkoniecz highway=motorway isn't limited to just interstates in a small number of states.

**Comment by westnordost** [comment]
@cliffordsnow Yeah, but there are signs, right?

**Comment by cliffordsnow** [comment]
Yes - always signs - some well hidden just to increase city coffer through speeding tickets.

**Comment by Carnildo** [comment]
"highway=motorway" in the US is used for Interstate highways and for any other road built to Interstate standards.  You don't need to worry about implicit speed limits for them: part of that standard is speed limit signs at every entrance, every change of speed limit (eg. going from rural to urban), and at intervals if it's been too long since the last sign.

**Comment by gappleto97** [comment]
As a temporary thing, you could simply have it not ask further information if there is no sign. Treat it as a "Just dont show it again" button until this gets sorted out.

**Comment by gappleto97** [comment]
Can you please just disable the type portion for the US? I dont get why that part is necessary at all if we can provide the explicit number.

**Comment by matkoniecz** [comment]
> if we can provide the explicit number

What about roads where you can't?

**Comment by gappleto97** [comment]
For roads where there isn't an explicit number (so the user clicks "no sign"), you would treat it as a "hide for now" command. You don't want to eliminate the quest entirely because most of the untagged roads are still going to get useful data. You also don't want to mark it as a type because it's unclear. So the pragmatic solution is to prompt the user again when that portion of the quest is workable in the US.

**Comment by westnordost** [comment]
Sorry, I do not want to do this. That would mean that the quest would pop up for any other surveyor again and again (and also if you clear the app's data), until someone just inputs "some" (i.e. 25 mph) data to silence the quest being displayed again and again. It's against the quest guidelines, so to say, and there are good reasons for these guidelines. 

It is in the interest of everybody to properly define the data needed for determining the implicit speed limits for the US, why not get down to it? It seems perhaps like a huge chunk of work, but I never said that the whole US needs to be defined. The quest can bit by bit be enabled by more and more states within the US. I already linked the best possible source for this information, it should be just up to the US community however to define how exactly the tags should look like, not up to me.

**Comment by 1ec5** [comment]
It sounds like either `maxspeed:type` or `zone:maxspeed` would be a good way to tag the sort of “citywide unless otherwise posted” speed limit signs that are often displayed at the entrances to small towns. In many states, each village, town, city, and (in some cases) neighborhood can have its own implicit speed limits set by local ordinance (e.g., `US:OH:HAM:Loveland:residential`).

[<img src="https://user-images.githubusercontent.com/1231218/38267685-0cd6bc54-3731-11e8-8c5f-9e432ea00268.png" width="200" alt="medford">](https://twitter.com/medfordpolice/status/915968792458616832)

https://mutcd.fhwa.dot.gov/htm/2009/part2/part2b.htm#section2B13_para08
https://www.aaroads.com/forum/index.php?topic=12925.msg314075#msg314075

Just to give a sense of scale, at least [325 jurisdictions in Ohio](http://odotextrpt.dot.state.oh.us/traffic/) have received permission from the state to set a default speed limit lower than the statewide default. (In that state, local authorities don’t need permission to raise the default speed limit above the statewide default, so there’s an unknown number of those rules.) This is just one state – we could be talking about thousands of values, compared to the 311 or so `maxspeed:type` values or 711 colon-delimited `source:maxspeed` values that currently exist worldwide in OSM.

While a comprehensive database of these speed limits would eventually be useful, it would be such a massive undertaking that data consumers are unlikely to be able to use `maxspeed:type` in the U.S. for the foreseeable future. After all, a decade on, there still aren’t any major consumers of road route relations at the state level, let alone the county or municipal level.

Given the impracticality of `maxspeed:type` tagging in the U.S., some sort of `implicit` tag as you proposed in https://github.com/westnordost/StreetComplete/issues/813#issuecomment-362929963 sounds reasonable to me. It would be a placeholder for something more specific in the future, unblocking the addition of a large amount of immediately useful data to the project (posted speed limits). If you still think this is worth doing, perhaps an informal request for comments on the talk-us list would be a good start?

**Comment by westnordost** [comment]
Absolutely.
Though, maybe not `maxspeed:type=implicit`, because obviously, this is already taken/defined. But could be `implicit_maxspeed=yes`, or maybe even `maxspeed=implicit` or whatnot.

After discussion in the talk-us mailinglist, I think though that it is necessary to pitch it on a worldwide scale (talk-mailinglist, forums).

**Comment by 1ec5** [comment]
As part of revamping the [Ohio map features guide](https://wiki.openstreetmap.org/wiki/Ohio/Map_features) on the OSM Wiki, I compiled [this flowchart](https://commons.wikimedia.org/wiki/File:Speed_limits_in_Ohio.svg) for determining the implicit, unless-otherwise-posted speed limit of a road in that state. (These are just the main points; the actual legal situation is much more complex.) Having done this exercise, now I completely understand why you stopped short of Ohio in https://github.com/westnordost/StreetComplete/issues/813#issuecomment-362929963. 😉

[<img src="https://upload.wikimedia.org/wikipedia/commons/6/6b/Speed_limits_in_Ohio.svg" width="300">](https://commons.wikimedia.org/wiki/File:Speed_limits_in_Ohio.svg)

**Comment by westnordost** [comment]
Next exercise: put it into context of OSM. After all, the road classification (expressway, freeway,...) is already there, so the flowchart becomes a bit simpler

Am 30. April 2018 08:33:27 MESZ schrieb "Minh Nguyễn" <notifications@github.com>:
>As part of revamping the [Ohio map features
>guide](https://wiki.openstreetmap.org/wiki/Ohio/Map_features) on the
>OSM Wiki, I compiled [this
>flowchart](https://commons.wikimedia.org/wiki/File:Speed_limits_in_Ohio.svg)
>for determining the implicit, unless-otherwise-posted speed limit of a
>road in that state. (These are just the main points; the actual legal
>situation is much more complex.) Having done this exercise, now I
>completely understand why you stopped short of Ohio in
>https://github.com/westnordost/StreetComplete/issues/813#issuecomment-362929963.
>😉
>
>[<img
>src="https://upload.wikimedia.org/wikipedia/commons/6/6b/Speed_limits_in_Ohio.svg"
>width="300">](https://commons.wikimedia.org/wiki/File:Speed_limits_in_Ohio.svg)

**Comment by westnordost** [comment]
By the way, I started this: https://wiki.openstreetmap.org/wiki/Default_speed_limits

**Comment by ianthetechie** [comment]
@westnordost thanks for your work on that Wiki page! That may be the most comprehensive endeavor of the sort that I've seen.

Out of curiosity, have you proposed (or are you aware of any other discussions re:) getting this into OSM directly somehow (as part of admin tags, perhaps)?

**Comment by westnordost** [comment]
No, not yet. Other than time, two reasons:
- the mapping of road type -> OSM tags (and what kind of OSM tags may be missing yet) is not complete yet
- I wanted to have a parser that parses this wiki page into a JSON and will warn about any such missing mappings and other syntax errors in the wiki page; possibly a reference implementation in Javascript to interpret that JSON to showcase it

To be able to say "look, it works already, just use this data and this library" is going to make it easier to argue for getting rid of the `source:maxspeed` and `maxspeed:type` tagging and replacing it with a more reasonable tagging. (E.g. `urban=yes` instead of `source:maxspeed=DE:urban` etc)

Are you by chance, interested in writing such a parser? ;-)

**Comment by ianthetechie** [comment]
Wow, thanks for the quick reply!

All points make sense, and I couldn't agree more on wanting to present a full solution.

As a matter of fact, I had that exact thought (writing a parser) when I saw that the intent was to be machine readable. I guess you already answered my potential follow-up query as to whether or not one exists. Yes, I am interested in working on this.

For a bit more context, I arrived here via a comment you made on https://github.com/valhalla/valhalla/issues/1069 as I contribute to valhalla occasionally, host some instances, and can't resist a good data improvement challenge. (To answer the question you posed there, defaults are hard-coded based on the road tags. TL;DR here: https://valhalla.readthedocs.io/en/latest/speeds/). I considered building a Spatialite DB from the wiki page. Valhalla takes a similar approach for TZ data already, but it would still be great if the data could be tagged at the admin level in OSM.

**Comment by westnordost** [comment]
So, the research is complete, here https://wiki.openstreetmap.org/wiki/Default_speed_limits
@ianthetechie and me wrote a parser for this data here (newest in PR): https://github.com/stadiamaps/osm-default-speeds/pull/8 
And there is the countryboundaries library to distinguish in which country any one road is.

However, what I had to realize during the research (first link), that the situation is so complex that the current `maxspeed:type=<country_code>:<zone_type>` is not really sufficient, in parts incorrect and in any case, I or someone else would have to invent a lot of tags zone types over the world. As an author of an editor, I will refrain from this because new tags should not be pushed by an editor.

I did not see any one else taking any initiative in consolidating the broken maxspeed tagging, so I don't see how the maxspeed quest could be enabled in the US.

**Comment by BalooUriza** [comment]
Given the roughly 7000 possible implicit speed limits in Oklahoma, I think the best way it could be handled for Oklahoma is to ask what the speed limit is, and of the answer is "there is no sign" just set it to maxspeed:type=implicit.  Anything with maxspeed:type=implicit could then ask if the implicit speed limit is known, and what that value is.

Probably wouldn't be a bad idea to have a resurvey task ask about once a hear "is the speed limit still __?" and if the answer is no, then ask what the new speed limit is.  This could be once a week for things that are tagged construction=minor, and one more time (along with maxheight, maxweight, since these often change after construction) as a confirmation task after construction is complete.

**Comment by westnordost** [comment]
I'd prefer `maxspeed:signed=no` to denote that a stretch is not because it does not conflict with the maxspeed:type scheme. However, `maxspeed:signed` is not really used (that much) yet, so prior discussion on tagging mailing list or another community channel is imperative.

**Comment by 1ec5** [comment]
`maxspeed:signed=no` was discussed quite extensively on the tagging mailing list [earlier this month](https://lists.openstreetmap.org/pipermail/tagging/2021-January/thread.html#57929).

**Comment by BalooUriza** [comment]
> `maxspeed:signed=no` was discussed quite extensively on the tagging mailing list [earlier this month](https://lists.openstreetmap.org/pipermail/tagging/2021-January/thread.html#57929).

Oh, thanks for bringing that up.  I do like that one better.

**Comment by westnordost** [comment]
Was there any clear outcome out of this discussion though?

**Comment by matkoniecz** [comment]
Main outcome for me is that I need to describe better why it would be useful. 

Right now I have already multiple proposals active and waiting for vote where people were less confused (https://wiki.openstreetmap.org/wiki/Proposed_features/healthcare%3Dsample_collection https://wiki.openstreetmap.org/wiki/Proposed_features/remove_link_to_Wikidata_from_infoboxes are two in the queue).

And I plan to have no more than one active vote at once - so in near future I will e not working on it.

**Comment by tordans** [comment]
@westnordost does your recent work on the topic of maxspeed (https://www.openstreetmap.org/user/westnordost/diary/399412) change the outcome of your findings in https://github.com/streetcomplete/StreetComplete/issues/813#issuecomment-688252355?

**Comment by westnordost** [comment]
no

**Comment by michaelblyons** [comment]
Lurkers may want to take a look at #6758
