### ISSUE TITLE
adding missing construction key for highway=construction

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#819]
### General
Affected key(s) (or tags) to be modified: [construction](https://wiki.openstreetmap.org/wiki/Key:construction)
Question asked: **What kind of way exists here or is under construction?**

### Checklist
Checklist for quest suggestions (see guidelines):
- [x] 🚧 To be added tag is established and has a useful purpose (is prominently used in some major renderings), would enable #685 for answered elements
- [x] 🤔 Any answer the user can give must have an equivalent tagging (Quest should not reappear to other users when solved by one)
- [x] 🐿️ Easily answerable by everyone from the outside but a survey is necessary 
- [x] 💤 Not an overwhelming percentage of elements have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of elements (Worth the effort) 30k of 120k highway=construction are missing construction key, would enable #685

**Element selection:**   http://overpass-turbo.eu/s/vEB

**Metadata needed:** 
No

**Proposed GUI:** 

list of image + text for 

----

version a:

- road (would apply highway=construction, construction=road leaving exact classification for more advanced users)
- footway
- cycleway

Would not provide full data.

version b:

- motorway
- motorway_link
- trunk
- trunk_link
- primary
- primary_link
- secondary
- secondary_link
- tertiary
- tertiary_link
- unclassified
- residential
- service
- living_street
- pedestrian
- footway
- cycleway

Difference between say primary and secondary is not obvious and may be confusing.

**Comment by westnordost** [comment]
> Version b

He would also not be able to answer this, probably, because this can better be answered by someone with an overview.

All in all, I do not think that this makes a good quest. Version a)'s helpfulness is very limited, and it is very likely that the person who added `highway=construction` will set the correct value after construction is finished, or, another mapper will do it. This is information that is usually apparent from satellite, and if not, someone can create a note.
