### ISSUE TITLE
Beer Quests

### ISSUE THREAD

**Issue by ax3l** [westnordost/StreetComplete#82]
[OpenBeerMap](https://openbeermap.github.io) ([GitHub](https://github.com/OpenBeerMap)) is probably the most sophisticated and progressive way to make use of the OpenStreetMap database project. The only problem that it faces since years: bad data coverage.

So what needs to be done? `amenity`'s like `bar`, `biergarten`, `pub`, `restaurant` and every micro-`brewery` need `brewery=Beer1;Beer2;Beer3` attributes! Let's make this a quest in StreetComplete!

### Are you kidding me?

No, seriously. Those tags are standardized and are *important* information for civilization!
  http://wiki.openstreetmap.org/wiki/Key:brewery

(note: OpenBeerMap considers only *draft* beer for the list; everyone can serve bottled beer)

### But there are SO MANY sorts of beer in the world!

Yes, but don't hesitate, openbeerdb has us covered:
  https://openbeerdb.com

### Ok, but who would do such quests

Come on, who *would not*?!

**Comment by westnordost** [comment]
Oh, come on

**Comment by ax3l** [comment]
There would be *so many people* eager to go on surveys for it!

**Comment by ax3l** [comment]
Good thing is, you can reuse #74 input and rules for Happy Hours:
  http://wiki.openstreetmap.org/wiki/Key:happy_hours

**Comment by n01r** [comment]
A great service to the general public and all of humankind! :+1:

**Comment by escoand** [comment]
The more they survey, the worse is getting the accuracy...
Sure there is some kind of usage but maybe there are more important tags missing.

**Comment by anttitelio** [comment]
OpenBeerMap and contributing to it would be great additions to a dedicated beer app, like Pint Please!

**Comment by rugk** [comment]
As for https://openbeerdb.com is this data available per-country, i.e. can one filter/sort the data per country? I mean the popularity of the beer sorts is certainly very different per country…

**Comment by rugk** [comment]
This could be made as a disabled-by-default quest (ref https://github.com/westnordost/StreetComplete/issues/558).

**Comment by westnordost** [comment]
I'll close this as not to be implemented because:
- not every restaurant, bar, pub etc. will advertise this on the outside. I know, the typical "pub around the corner" at least in UK, Germany etc probably will, but other kind of restaurants and pub not. Also, the beer brand they advertise will (often) not be the only one they offer. Just recording what can be seen outside thus leads to incomplete information but users will be included to only record that information
- there is no way to tag if the place does not offer any beer or at least does not advertise it. But it is required that something can be tagged
- in reality, what drinks are offered (can) fluctuate somewhat, sometimes they have certain beer, sometimes not, sometimes they try out other or new brands etc. It is so volatile that I don't think it is worth recording it (in OSM). To be honest, I don't really think this kind of information belongs in OSM, what's next, we also record the contents of the menu?
- one is supposed to state all the beer brands in a semicolon separated list. But what if it offers more beers than would fit in the field? (max 255 characters)
- the `brewery` tag is not that often used and half of its usages is to mark a place as that they brew their own beer, not what kind of beers they sell anyway

**Comment by ax3l** [comment]
When I last talked to a bar owner in Germany, most restaurants and bars negotiate and contract with a provider or even brewery for their regular beverages, especially for beer brands on tap (kegs). Therefore, their beer tap selections change quite seldom, at best once a year.

But I guess the best rationale would be given by the people that maintain OpenBeerMap.

**Comment by derfasthirnlosenick** [comment]
It *might* be relevant in places where the brewery is often the landlord (Munich for example) and mandates whic hbeer can and cannot be sold. But I agree that the probability of mis-tagging (e.g. going by the umbrella outside) is likely to outweigh any benefits this might  information might have.

**Comment by mnalis** [comment]
(for those being subscribed, this Quest has _actually_ been [implemented](https://github.com/Helium314/SCEE/issues/472) for years now in [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"expert edition"_ fork)
