### ISSUE TITLE
Quest: support trees

### ISSUE THREAD

**Issue by PanderMusubi** [westnordost/StreetComplete#83]
Please add support for individual trees, see https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree

Make sure only to offer one-of-many choices such as `leaf_type`, `genus`, `species` and/or (when applicable for the species) `sex`. Note that for these four values, many can be derived when the most specific was chosen in the app. Best to consult the decision tree with a tree expert / botanist.

Other values such as `taxon`, `name`, `circumference`, `height`, `diameter_crown` and `start_date` are to be derived (taxon) or difficult to impossible to simply observe by looking and should not be offered.

**Comment by picsi** [comment]
A common tag is also ``species:foo`` where "foo" is a two-digit language code. This is used for common names. I think it would be useful to have this as more regular people (non-wizards) know the common names rather than the scientific names.

So maybe let's have a 'be sure of what you're doing' before the user inputs a scientific name in the ``species`` field, or worse: the user adds a comon name into the ``species`` field.

**Comment by PanderMusubi** [comment]
Let them pass a simple English or localises test first.

**Comment by Jotam** [comment]
Mmh, maybe not the most urgent quest to implement.

**Comment by PanderMusubi** [comment]
Agreed, nevertheless a valuable one. Perhaps only start on this when offering a compulsory user test to check if they know what they are doing is easily available in street complete.

**Comment by matkoniecz** [comment]
I used to have `leaf_cycle` and `leaf_type` quests in my fork but I removed them because

- individual trees are impossible to precisely locate during survey and I was never sure whatever I am answering correctly. Maybe it would be improved by map showing locations of trees - but it is rejected by guidelines for SC map style
- quests turned out to be extremely boring, even for somebody who really loves nature
- I had constant feeling that solving this quests is a complete waste of time

Overall, I would not recommend adding this quest.

**Comment by rugk** [comment]
Hmm… do they map forests as single trees where you use StreetComplete? :laughing: :wink: 
Because otherwise you may only find these in parks or some single ones at streets or so. I think they are both always the same (when in a row or so) and less often different when standing near each other,
And in parks one may not have too many trees at once to answer. I think there can hardly be a quest, which is even more boring than the street surface one in cities… :wink: That's why I just move it down from the priority.
So I still consider this not soo bad, maybe limit it to tree rows or so… (then you only answer once for a row, similar to how you do it for a street)

Maybe also consider https://github.com/westnordost/StreetComplete/issues/366 the follow-up of this issue and maybe generally the better idea. As the implementation should be the same for both quests, however, one may e.g. just include the _tree rows_ in the other quest there.

**Comment by matkoniecz** [comment]
Yes, in my city some parks have individual trees mapped. Maybe in places with only major trees mapped it would be less flustering.

**Comment by PanderMusubi** [comment]
Some cities in the Netherlands have exported their tree databases under an open license and these have been imported into OSM. So some cities have tens of thousands of individual trees.

Here is an example. ![example](https://in04.hostcontrol.com/resources/dad6034ccf77b2/c25d29bee5.PNG) F4 uses `leaf_type` to render the correct shape of tree.

It is certainly not to be used for forests, only for individual trees which are missing these details. See, as @rugk also mentions, https://github.com/westnordost/StreetComplete/issues/366 for more fine-tuned approach.

**Comment by rugk** [comment]
Hmm, ok. Now we have one argument in favor of this quest (F4) and one against it (the database import)…

However, once trees are mapped, they are mapped… 😐

**Comment by PanderMusubi** [comment]
If a tree is mapped, it can still be missing:
1. `leaf type`
2. `leaf cycle`
3. an optional node relation for a man-made nest with:
    - `man_made=nesting_site`
    - `support=tree`
    - `material=plastic`, `material=metal` or `material=wood`
    - `taxon:order=Chiroptera` (for bats) or `taxon:class=Aves` (for bats)
    - (Omit `species`, `genus` and `capacity` as this is hard to observe or determine. Perhaps also store somehow that there is no man-made nest?)

Especially the man-made nesting site is very interesting addition to be made by StreetComplete users as they are usually not part of the open tree database from local governments. Note that natural nesting sites are not to be mapped.

[!example](https://wiki.openstreetmap.org/w/images/7/7e/Nest-for-bats.jpg)

See also https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Nesting_Site#Nest_for_bats_on_a_tree and https://wiki.openstreetmap.org/wiki/File:Nest-for-bats.jpg

**Comment by rugk** [comment]
Uh, that is getting very much…

Please note StreetComplete quests should not spam users. And I am very sure most trees do not have such a nesting site.

Also I do not see a concrete use case, just because it is not mapped in government databases.

And generally, I'd say this is a new quest type, so next time, just directly open a new issue. (and fill out/check the issue template)

**Comment by PanderMusubi** [comment]
Agreed, so only `leaf type` and `leaf cycle` then.

**Comment by PanderMusubi** [comment]
To keep it practical, query only `leaf_type`. In OSM `natural=tree` occurs 10,211,795 times. Of which 7,538,527 trees are missing `leaf_type` and 12,236 trees have `leaf_type=mixed`, which is not allowed for a tree.

If `natural=tree` has is missing `leaf_type` or has `leaf_type=mixed`, offer the user only `leaf_type=broadleaved` or `leaf_type=needleleaved` to choose from.

**Comment by goldfndr** [comment]
The query should perhaps also include leaf_type values that aren't 'broadleaved|needleleaved|leafless' for `natural=tree`, to fix up the mistagged trees. (It seems like leafless should maybe be spineleaved, given the accompanying images.)

**Comment by PanderMusubi** [comment]
Agree with @matkoniecz because this could overwrite (unwillingly,unknowingly) new tags which are in the making or starting to be used. I doubt it will apply here, but better to be strict.

By the way, leafless applies to huge cacti which are added as a tree or dead trees (which should be tagged as a pole or something else, as the original tree did have a leaf type). so I would recommend to stay away from leafless too.

**Comment by westnordost** [comment]
Based on @matkoniecz experiences with a prototype version of the quest, and the fact that he already implemented quests for leaf-cycle for (small) forest patches, I will close this ticket as will not fix.

To summarize:
- type of single trees are rather unimportant, mostly only useful for 3D rendering
- highly repetitive (waste of time)
- tree type (coniferous or broadleaved) can often be determined easily from good areial imagery
- **Most importantly:** 
> individual trees are impossible to precisely locate during survey and I was never sure whatever I am answering correctly.

So, the latter is a real problem that can and will lead to wrong data entered by the users.

**Comment by TraWELTina** [comment]
I know, this quest was closed, but I would ask to reopen it:

- the tree type has valuable application for research (e.g. used for the monitoring of insects which are specific to certain trees)
- if determining the "right" tree is hard, can one probably add a filter, to not include trees that are standing too close?
- tree rows can be probably mapped together as they are mostly the same tree type (so that its not too repetitive)
- botanists/experts could provide the decision images

I would ask to reopen because of a current research issue where this kind of information would be really helpfull (so really NOT useless)

**Comment by matkoniecz** [comment]
Tree rows are supported already in the leaf your quest.

Even if single tree is mapped then multiple trees may be in a given place.

**Comment by TraWELTina** [comment]
> Tree rows are supported already in the leaf type quest.
Yes, the suggestion was to also include genus or species

**Comment by mnalis** [comment]
> allow tagging species or genus by mapper without botanical experience, without making code as complex as all other quests taken together
> But I am sceptical about species or even genus tagging with SC, it sounds extremely complex or requiring user to have some botanical experience.

I agree, specialized [MapComplete](https://mapcomplete.osm.be/) map for such quests requiring special knowledge might be much better match than StreetComplete.

**Comment by rugk** [comment]
A specialized app would be a lot of code duplication/maintenance effort. Then, rather a plugin system for SC adding more quests would be appropiate. This was raised a long time ago in https://github.com/streetcomplete/StreetComplete/issues/98 in some way, though it focused on a JSON format, while I would nowadays prefer just native code/apps that you can download.

If you want to re-raise it, maybe collect a list of quests (issues here) that would be suitable, find out whether the interface SC nowadays uses for quests is appropriate/can somehow theoretically be extended and then document that in a new issue.

**Comment by PanderMusubi** [comment]
Perhaps in the future, StreetComplete can have special modules that are unlocked for contributors which have a high quality track record and then did some 'entrance quests' for which we know the answers, in order to do more advances quests, such as tree circumference.

**Comment by matkoniecz** [comment]
> A specialized app would be a lot of code duplication/maintenance effort.

Not really. You can maintain version with own quests fairly easily (I know because I am doing this).

**Comment by andrewharvey** [comment]
> Not really. You can maintain version with own quests fairly easily (I know because I am doing this).

It becomes difficult for mappers when you have a number of different SC forks installed though, and I still think the effort to maintain and do releases is significant.

I would love to be able to have a tree quest as originally described here, and do understand why it might not be enabled by default, but I still think it's better have an an experimental trees quest included in SC rather than in a SC for trees fork.

**Comment by mnalis** [comment]
@andrewharvey perhaps those different quests could be kept in _one_ experimental fork? see @Helium314 et al. suggestion at https://github.com/streetcomplete/StreetComplete/discussions/3003#discussioncomment-1028770

**Comment by mnalis** [comment]
These days, I'd recommend to people interested in this subject to try out [Every Door](https://wiki.openstreetmap.org/wiki/Every_Door). 

As is StreetComplete, EveryDoor is also simple to use app, but seems much better match for this use case (as opposed to SC Quests), and already implements this feature, e.g.

![small_Screenshot_20230512_195032_info zverev ilya every_door](https://github.com/streetcomplete/StreetComplete/assets/156656/4db9b8b3-8a6a-4f79-a7fe-2394e2dac8cf)

**Comment by mnalis** [comment]
Just FYI for those following this issue: nowadays, `Things overlay` can be used to add trees as POIs in StreetComplete (and there is a quest for leaf type too). 

For those wanting more details [SCEE](https://wiki.openstreetmap.org/wiki/SCEE) (StreetComplete _"Expert Edition"_ fork) also has an advanced quest for species/genus taxon of the tree.
