### ISSUE TITLE
In "What is the structure of this bridge" quest photos are without labels

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#842]
Happens on Android 6.0.1.

**Comment by westnordost** [comment]
Yes, there are no labels.

**Comment by westnordost** [comment]
Users should decide on the structure based on the shape, not based on the description plate in front of each bridge that describes how the type of bridge structure is called - because this plate is usually absent ;-)

**Comment by matkoniecz** [comment]
I think that it would be better with labels. In some cases photos are not self-explanatory and I would prefer to check whatever I am understanding correctly what should be selected as an answer.

I would not look for description of bridge, I would check what given bridge type means.

**Comment by matkoniecz** [comment]
Also, at least for me it would be interesting to know how bridge types are named if I am classifying them.

**Comment by westnordost** [comment]
Then perhaps we need better photos? Which bridge photo is not self-explanatory? (And why do you think that giving the name (i.e. "arch bridge", "suspension bridge", ...) would help the surveyor decide?

**Comment by rugk** [comment]
Indeed, the argument for what to select when manually mapping later is indeed valid, considering this app may be for OSM newbies and they later want to map on OSM.org or so.

Also, of course, the names **are useful**. Look at the [German translations](https://wiki.openstreetmap.org/wiki/DE:Key:bridge:structure):
* Bogenbrücke
* Balkenbrücke
* Seilbrücke

…would e.g. even help without any picture. So just give the user any help they need.

**Comment by westnordost** [comment]
Would you argue the same with roof shapes?

**Comment by matkoniecz** [comment]
> Would you argue the same with roof shapes?

No - roofs are less varied in structure than bridges, picture are clearly indicating what is the important feature of a given case and in addition I am less interested in roof shapes.

For concrete usecases: 

- floating bridge was not obvious for me before checking source code of the quest. With label it would be self-explanatory.

- I am not sure which answer, if any, applies to smaller bridges like https://www.google.com/maps/@50.0597404,19.9006872,3a,28.3y,352.53h,88.98t/data=!3m6!1e1!3m4!1szNBayaDCD2n45SSRXUp9pA!2e0!7i13312!8i6656

Probably the first one but at least I would prefer to check whatever bridge type description matches what I see.

**Comment by lokaman** [comment]
Roof shapes are easy to tag based on the simple pictures in the quest. You don't need the names since they don't provide any additional information to the user. The german roof shape names are not commonly known (despite the "Giebel" maybe).

The pictures of the bridges are good.

I don't see any need to add something.

Is there a picture which is confusing?

**Comment by westnordost** [comment]
> I am not sure which answer, if any, applies to smaller bridges

Yeah me neither. "Beam" probably? 
![Beam bridge](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_beam.jpg)

Look, if that is the problem, then labelling the above bridge with "bream bridge" is not going to help much. What would help however, and I already did that for arch bridges, is to add another picture of a visually different bridge such as the one you posted and let it tag the same.

I.e. both these pictures are tagged as arch bridges:
![Arch bridge](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_arch.jpg) ![Arch bridge](https://raw.githubusercontent.com/westnordost/StreetComplete/master/app/src/main/res/drawable-mdpi/bridge_structure_tied_arch.jpg)

**Comment by rugk** [comment]
> is to add another picture of a visually different bridge such as the one you posted and let it tag the same.

I like that UX trick, but would still argue for including the name. As it has been stated by others, the names are much more "valueable" than the roof ones. As for bridges, you generally know what is meant.

**Comment by westnordost** [comment]
So, I am not convinced that the names of the particular structures would be useful, so it is a will-not-fix. We will see what other feedback comes in over the time for the bridge structure quest.

**Comment by 1ec5** [comment]
This came up in a recent thread [in OSMUS Slack](https://osmus.slack.com/archives/CRCUH32G5/p1761585861556549). It isn’t clear that the defining characteristic of each option is in red. For those of us who are used to bridges being painted various shades of red, it just looks like decoration. 🌉

For my part, I could see the names being useful for bridge shapes that don’t exactly match the diagrams. For example, the current [Jeremiah Morrow Bridge](https://en.wikipedia.org/wiki/Jeremiah_Morrow_Bridge) looks a lot like [this option](https://github.com/streetcomplete/StreetComplete/blob/ce9e35ece49a4fae70415254ab632e2af0c5d815/res/graphics/bridge%20structure/arch.svg), but it’s actually a box girder bridge, not an arch bridge. (It replaced a truss arch bridge, which would be tagged `arch` rather than `truss`.) Just a small context clue as to what these diagrams are supposed to depict could keep the user from making a mistake on the off-chance they’re vaguely familiar with the terms.

**Comment by mnalis** [comment]
> For my part, I could see the names being useful for bridge shapes that don’t exactly match the diagrams. For example, the current [Jeremiah Morrow Bridge](https://en.wikipedia.org/wiki/Jeremiah_Morrow_Bridge) looks a lot like [this option](https://github.com/streetcomplete/StreetComplete/blob/ce9e35ece49a4fae70415254ab632e2af0c5d815/res/graphics/bridge%20structure/arch.svg), but it’s actually a box girder bridge, not an arch bridge

Hmmm, yeah, maybe, but to be truthful, I'd still probably answer that Jeremiah Morrow Bridge wrongly even if image had a label. As an additional hurdle with my translator cap on, I really have no idea how I'd translate those bridge type names in Croatian to be intelligible to anyone (except perhaps few civil engineers specialized in bridge building)

---

If the pictures are unclear, perhaps an `(i)nfo` button somehow explaining to look at red parts as important ones in making a decision would be more helpful then labels of specific bridge types, especially for general public?
