### ISSUE TITLE
View/Update/Add POI-Mode

### ISSUE THREAD

**Issue by RubenKelevra** [westnordost/StreetComplete#844]
SC is already a very neat editor for small property on-the-fly edits for surveys but the new ability to add notes everywhere (currently added to the latest beta) I doubt is a good idea... the numbers of notes will likely going to explode if we don't add a small view and edit feature for POIs because one cannot distinguish between already present informations and maybe nice-to-have Infos in the current map view.

Many times I saw ppl creating notes about changed shops etc which then needs to be edited by another user adding a huge amount of overhead for simple stuff like changing the type of shop, name, opening hours and telephone number.

Adding an additional POI layer with ability to show informations about items with a long press would help us alot updating POI-informations on the fly while on survey.

I suppose this isn't a small task but I think it would be worth a discussion.

**Comment by matkoniecz** [comment]
> the numbers of notes will likely going to explode

I would not expect this, but we may wait and see what happens.

> adding a huge amount of overhead

In my experience it is not huge overhead, but maybe you edit in region that has more outdated data in OSM that is detected during StrreetComplete surveys.

In general this proposal seems out of scope for this project, see README

> Because of the target group, only those quests are shown which are answerable very clearly by asking one simple question and only those quests are created which contain very few false positives.

And for full OSM editor I suggest using Vespucci, I typically use it together with StreetComplete.

**Comment by ENT8R** [comment]
Maybe you want to have something like #471?

**Comment by rugk** [comment]
@ENT8R Indeed, that's what he wants, AFAIK. Plus, of course, a display of these tags, but this is a quite obvious requirement for that issue.

> if we don't add a small view and edit feature for POIs because one cannot distinguish between already present informations and maybe nice-to-have Infos in the current map view.

Indeed, that's a good point. I also saw me making notes (at least for the "regular quests", i.e. with pre-v4.0 versions) for things that later turned out to be mapped, already. 
Of course that may be things that need to be excluded in the Overpass query for the quest in StreetComplete itself, but I think there are always things, where such things cannot be done or maybe are too rare or whatever.

> Adding an additional POI layer with ability to show informations about items with a long press would help us alot updating POI-informations on the fly while on survey.

Yeah, I've already proposed a long-tap for the manual notes creation stuff. So I do not know how many manual notes will be created later and I doubt (or, hope) it won't be too much senseless ones, but if it really turns out to be too much, it could be an idea to change it and at least only make it possible (i.e. harder) for users to create such a note by using a long-tap.
So we have yet another argument for such a more "hidden" way of creating such notes.

**Comment by westnordost** [comment]
Having a POI layer is out of the scope of this app. The reason why the current map is kept very simple and explicitly does *not* include all those informations that you might i.e. find on the Mapnik map is that users don't get the idea to deduct from the fact that something is not displayed on the map, it might be missing. That is why it displays almost nothing.

The very idea of StreetComplete is, that you do not need to find the "holes" by looking through the map but the app does that for you. Of course this does not work for everything, i.e. the app will (probably) never ask you "There should be a shop here, right? What shop is it?" but there are other apps that display a very complete map which also allow you to leave notes, even add new elements - namely Maps.Me and probably Osmand too.

**Comment by ENT8R** [comment]
> the numbers of notes will likely going to explode

I just browsed notes created by SC users using NotesReview and found this area:
https://www.openstreetmap.org/#map=16/-27.9888/153.0007&layers=N
where a user with only 8 edits created so many notes with information which is not helpful at all... e.g. the names of shops which already existed in OSM but the user didn't see them on the map and created a note (especially https://www.openstreetmap.org/note/1294513)
Maybe a small hint while creating a new note like "Do only add a note here if you are 100% sure that the information is not already included in OSM" is useful

**Comment by ENT8R** [comment]
I just found out that there was a mapping party: https://www.openstreetmap.org/user/David%20Dean/diary/43224 with users using SC to create notes...

**Comment by westnordost** [comment]
Give someone a hammer...

**Comment by westnordost** [comment]
So perhaps the app should be more explicit in the wording that this should be used only to report issues?
The current text is _You can leave a note to let other mappers know about an issue here._

**Comment by westnordost** [comment]
Perhaps one could add a feature where one can leave a note only to oneself plus an export-to-GPX function or something like that.

**Comment by rugk** [comment]
> So perhaps the app should be more explicit in the wording that this should be used only to report issues?

Maybe just use the same mechanism as when you try to solve quests farer away. Display a message with a "Do not show again" checkbox before the user can enter a note.
This message should then explicitly state that not all things from OSM are shown on the map and one should re-check that before opening a note…

**Comment by RubenKelevra** [comment]
Thanks for the productive discussion, yeah, I know my request was way out of the current implementation. But hey, I thought it would be worth a discussion. I even think it would be better to add this than an expert mode, like, add simple blue or green points for POIs and just the ability to see what's actually already there would be more helpful than the ability to edit those points. You can still make a quick note on this and someone rechecks if an edit makes sense here.

**Comment by Helium314** [comment]
I recently had the same idea, and noticed that simply showing POIs is actually easy to do, even for someone who has no experience with software development, git and kotlin (i.e. me):
![poi](https://user-images.githubusercontent.com/43007630/90817127-a46f1c00-e32d-11ea-8dac-07407a29b198.jpg)
Currently it can display: bicycle parking, waste bin, bench, telephone, recycling, business, with name being displayed when tapping the dot.
Adding and deleting is not possible, images for other quests are re-used, and the list of businesses used for the orange POIs likely needs some tweaking to avoid possible duplicates when adding stuff through notes.

After testing for two days I found it pretty useful, and did not find any problems... it could be extended some more, but is good enough for personal use.
I thought some of you might be interested, that's why I write here and put it on github: https://github.com/Helium314/StreetComplete/tree/show-poi

**Comment by NotSoImportant** [comment]
> I thought some of you might be interested, that's why I write here and put it on github: https://github.com/Helium314/StreetComplete/tree/show-poi

This sounds really interesting. I found myself multiple times opening OsmAnd to check if an item exists, but then for quicker collection opening SC, creating a foto note. 

Ideally
- I could check existance in SC
- add a new poi
- add a foto note with details (adress, phone, opening hours,... for updating later) 

Maybe there should be a toggle between the regular "suggestion mode" and this "edit mode". 

Does it work with the latest SC version (there was this change in downloading all quests at once last year)? How do you retrieve the pois? Via the same time consuming overpass query than the old implementation?

**Comment by Helium314** [comment]
> Does it work with the latest SC version (there was this change in downloading all quests at once last year)? How do you retrieve the pois? Via the same time consuming overpass query than the old implementation?

The outdated version linked above does not work with the new way of downloading, but I have an updated version. I can update the version on github.

Downloading all quests was a very helpful update; previously sometimes POIs in downloaded areas where not shown (probably due to some limitation in the number of elements downloaded or returned by overpass).

But:
* you should check or adjust which elements are displayed (and which are not!) to avoid adding notes for existant but not displayed POIs
* be careful near the edges of downloaded areas, often some POIs are shown and some are not. These edges are easy to miss when zoomed in, and they are not sharp (POIs mapped as areas can be shown outside the downloaded area)
* if you are in a badly mapped/outdated area, the amount of notes will lead to people complaining (which is why I rarely add POIs any more...)
* one reason of why I added this was to check existance, which can now be done much better in SC (mostly without necessity of leaving notes)

**Comment by Helium314** [comment]
Sorry it took me so long @NotSoImportant
updated version is available: https://github.com/Helium314/StreetComplete/tree/show_poi_2

**Comment by mnalis** [comment]
@Helium314 it would be nice if you could make `APK` on Release page, so people without full android development environment might try it out and give comments.

**Comment by Helium314** [comment]
Here you go: https://github.com/Helium314/StreetComplete/releases/tag/v31.1_poi
