### ISSUE TITLE
Consider adding "usually" to fee quest question

### ISSUE THREAD

**Issue by matkoniecz** [westnordost/StreetComplete#848]
Currently it is not clear what should be answered for parking that have fee or are free depending on

- time (time of year/day of week/hour)
- status of user (worker, customer, resident, random person)
- how long car is staying (up to X minutes/hours is free)
- other factors

I checked wiki ( https://wiki.openstreetmap.org/wiki/Key:fee ) and now I know that it should be whatever "fee is usually charged", but if I were a user without OSM knowledge I would end creating flood of notes explaining that given place is sometimes paid and sometimes free.

**Comment by westnordost** [comment]
"Usually" will not be helpful because it is also somewhat ill-defined.

Did you just come up with these possible conditionals or are you describing this from your own experience? A parking lot that is free for residents and there is a fee for other people seems curious.

**Comment by matkoniecz** [comment]
> are you describing this from your own experience

Yes. For example municipal parkings in city center of Kraków are paid or not depending on day of week and hour.

![550fc990f3704_o](https://user-images.githubusercontent.com/899988/36038593-65ef8234-0dc0-11e8-9f47-a8b127923b97.jpg)


>  A parking lot that is free for residents and there is a fee for other people seems curious

It appears sometimes in places with many tourists where fees from residents are waived and others (tourists) are paying, though it is less common than other cases.

**Comment by westnordost** [comment]
Hmm, is there a tagging scheme to pay respect to this kind of conditional fees?

Am 9. Februar 2018 17:41:38 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>> are you describing this from your own experience
>
>Yes. For example municipal parkings in city center of Kraków are paid
>or not depending on day of week and hour.
>
>![550fc990f3704_o](https://user-images.githubusercontent.com/899988/36038593-65ef8234-0dc0-11e8-9f47-a8b127923b97.jpg)
>
>
>>  A parking lot that is free for residents and there is a fee for
>other people seems curious
>
>It appears sometimes in places with many tourists where fees from
>residents are waived and others (tourists) are paying, though it is
>less common than other cases.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/848#issuecomment-364487600

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by rugk** [comment]
Even if not, you could still add a "Other answer" item and e.g. tag it as "yes" anyway, so that users get accustomed to the special answer, so if a tagging scheme one days comes up, you can change it.
Similarly to how you sometimes add additional pictures for the same element for some quests. I like that UX trick… 😄

**Comment by matkoniecz** [comment]
> is there a tagging scheme to pay respect to this kind of conditional fees

There is fee:conditional ( https://taginfo.openstreetmap.org/keys/fee%3Aconditional#values ) using https://wiki.openstreetmap.org/wiki/Conditional_restrictions , but it is not  popular with 240 uses worldwide.

Anyway, adding fee=yes in that situation is better that not adding fee=yes tag or creating a note.

**Comment by westnordost** [comment]
> "Other answer" item and e.g. tag it as "yes" anyway, so that users get accustomed to the special answer, so if a tagging scheme one days comes up, you can change it

This is manoeuvring the `fee=yes` tag into a dead end, and ultimately burning the tag this way. If `fee=yes` can also mean "usually yes", "sometimes yes, depends on ...", it will be impossible to distinguish those parking lots that just plainly require a fee from parking lots where whether they require a fee or not, depends on certain factors. 
In other words, if we tag everything as `yes`, then it will be impossible to create a quest later on in which the user should define on what the conditional fee depends because the overpass query would need to look for parking lots tagged with `fee=yes` and ask for whether the fee depends on things, but if it just a fee unconditionally, the quest has nothing to tag!

You get my point, right?

So, even if there is no proper tagging scheme that covers all the possible conditionals now, we must still keep this option open by tagging accordingly.

To tag `fee=conditional` or similar would be a solution because then in `fee:conditional` it can later be defined more in detail (or as an extension to this quest).

**Comment by DeusFigendi** [comment]
> A parking lot that is free for residents and there is a fee for other people seems curious.

Indeed I know places where this is the case, **but** residents usually know they can park there for free and for everyone else it's just "yes". Similar for "workers". Employees also know they don't have to pay :D

But it might be interesting for  parking lots where you usually have to pay a fee but you don't have to if you are a customer.

> To tag fee=conditional or similar would be a solution because then in fee:conditional it can later be defined more in detail (or as an extension to this quest).

"conditional" seems as good as "usually" it's just any value that isn't "yes" XD.
I like the idea to include this into the quest so one answer could be "usually" or "under conditions" or "maybe" or something and this opens a new choice for `fee:conditional=` (similar to the new surface-quest).
