### ISSUE TITLE
3.7 binary in repo fails to install if 3.6 is already installed

### ISSUE THREAD

**Issue by BrettDikeman** [westnordost/StreetComplete#863]
Please fix the 3.7 APK - upgrading from 3.6 fails on Marshmallow.

**Comment by rugk** [comment]
I assume you've downloaded StreetComplete from F-Droid. If so, you cannot upgrade it with the APK provided here. F-Droid uses a different (i.e. their own) signature for the APK, while the one hosted on GitHub uses the one by @westnordost (and the same as on Google Play, I assume).

The only way to install the version would be to uninstall the previous one and reinstall the new one. That signature thing is a feature of Android. There is nothing StreetComplete can do about that.

Just wait for the F-Droid release.
So I think this issue can be closed.

**Comment by BrettDikeman** [comment]
Correct, you can close this.

For the future, would you hold off on remotely killing old versions of your app until there's a version verified to be available in distribution channels? Maybe even give people a day or so to get the update via normal update channels?

**Comment by rugk** [comment]
The reason was that the old versions caused bad mappings and each new upload would maybe have introduced/mistagged data or so. See https://github.com/westnordost/StreetComplete/issues/852 for details, if you have not already read that.
One may argue whether one or two days matter, but IMHO that fast reaction is understandable. Especially as it is not that you cannot use the app anymore, but just that you cannot upload data until the next uopdate (you can still collect data though).
