### ISSUE TITLE
Create taginfo.json for taginfo site

### ISSUE THREAD

**Issue by goldfndr** [westnordost/StreetComplete#864]
The taginfo site features [a list of projects](https://taginfo.openstreetmap.org/projects) and the keys/tags that they use. When looking at a key's or tag's page in taginfo, one can switch to the *Projects* tab and see what projects use that key or tag and how.

Currently, StreetComplete is not represented in the taginfo projects. To add representation, there needs to be [a JSON file listing attributes of the project and the keys/tags it supports](https://wiki.openstreetmap.org/wiki/Taginfo/Projects).

I've created [a preliminary taginfo.json](https://gist.github.com/goldfndr/7f66afc5b4628fcdd7e2bf3099053914) for StreetComplete. It's current as of the 4.0 beta, assuming that [the OSM wiki's table](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) is complete (I went in order from top to bottom). Things that are needed:

- [x] Buy-in
- [x] A contact name and email (I suppose that since it's taginfo-specific, it doesn't need to be @westnordost ).

Something that would be useful is a 16x16 icon for StreetComplete; there are better artists than me here.

You'll see that I didn't include all of the `name:__` languages from the Road Name quest. If someone can provide me with space-separated list of the ones StreetComplete outputs to (based on the country data), I'd be happy to get the full list in. You'll also see that I shortcutted on the `religion` key.

I created the tags array using a spreadsheet. Data columns are Key, Value, nwar, description. Then in a fifth column, I have a complicated formula that converts the four columns into proper JSON, using the nwar column to look up the expansion (combinations I found are na ar n w nar wa). I created the data by looking at the source code of each quest. All typos and other mistakes are my own. For many of them, the query has a not (!) operator in front (e.g. Speed Limit quest has `!maxspeed` and `vehicle !~ private|no` in the query). I ignored the ! operator for those, rather than excluding them (or trying to figure out what the nonexcluded values were).

(Edit: closed parenthesis in last paragraph)
(Edit: it doesn't include #862's changes.)

**Comment by rugk** [comment]
> assuming that the OSM wiki's table is complete 

Yeah, I try to keep it complete. You can always cross-check with the app in the options (where you can enable/disable/sort quests), to see whether quests are missing.

> Something that would be useful is a 16x16 icon for StreetComplete; there are better artists than me here.

Just use the official one. As [there is an SVG](https://github.com/westnordost/StreetComplete/blob/master/res/appicon_flat.svg), you can scale it to the size, you need.

> If someone can provide me with space-separated list of the ones StreetComplete outputs to (based on the country data), I'd be happy to get the full list in.

I assume [that's it](https://github.com/westnordost/StreetComplete/blob/master/res/country_metadata/additionalStreetsignLanguages.yml). (It's linked in the wiki… 😄 )

**Comment by matkoniecz** [comment]
> You'll also see that I shortcutted on the religion key.

https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/religion/AddReligionToPlaceOfWorshipForm.java has full list and it is

christian, muslim, buddhist, hindu, jewish, chinese_folk, bahai, sikh, toist, jain, shinto, caodaism

**Comment by matkoniecz** [comment]
> Buy-in

Such resource may be also maintained as a separate project, without any effort required from @westnordost

**Comment by westnordost** [comment]
That's a nice idea!

I see pulling the JSON into this repository as a commitment to always keep it absolutely up-to-date and thus also require contributors who want to create new quest types to this project to also always update it alongside it, so I am not sure about that, as I want to keep it as simple as possible to do that.

But as @matkoniecz mentioned, it could be also maintained in a separate repository. Not necessarily something you have to do, but would be cool of course :-)

> I created the tags array using a spreadsheet

Perhaps you should put this spreadsheet (and the converter) into that repository. Editing that JSON looks a bit like a pain because of all that duplication. @rugk (maintainer of the list in the wiki) and other people from this project, including me of course, can then create PRs to that repository (or you give us write-access) to update it here and there. 

> provide me with space-separated list of the ones StreetComplete outputs to
Heh. Any? :-)
Well, at the moment (sorted alphabetically:)
```aa,adx,af,ak,am,any,ar,as,ay,az,bci,be,bem,ber,bg,bi,bm,bn,bo,br,brx,bs,bzj,ca,ceb,ch,chk,crs,cs,cy,da,de,den,dgr,dk,doi,dv,dyu,dz,ee,el,emk,en,es,et,eu,fa,fan,ff,fi,fil,fj,fo,fon,fr,ga,gd,gil,gl,grt,gu,gug,gv,gyn,ha,heb,hi,hif,hil,ho,hr,ht,hu,hy,id,ilo,is,it,iu,ja,jam,jv,ka,kea,kha,kk,kl,km,kn,ko,kok,kri,ks,ky,lb,ln,lo,lt,lua,lus,lv,mad,mai,mfe,mg,mh,min,mk,mkw,ml,mn,mni,mnk,mos,mr,ms,mt,my,myn,na,nb,nd,ne,niu,nl,nn,no,nso,ny,oc,om,or,pa,pap,pau,pih,pl,pon,pov,ps,pt,qu,rar,rm,rn,ro,ru,rw,sg,si,sid,sk,sl,sm,sn,snk,so,sq,sr,ss,st,su,sus,sv,sw,swb,ta,te,tet,tg,th,ti,tk,tkl,tn,to,tpi,tr,trp,ts,tvl,ug,uk,ur,uz,vi,wal,wlc,wni,wo,xh,za,zdj,zh,zu
```

**Comment by westnordost** [comment]
16x16 Icon is here: http://westnordost.de/streetcomplete/icon_16x16.png
Email would be osm at my domain.

**Comment by rugk** [comment]
He said "space-separated"… 😉 😆 

Regarding the maintainability, I also see the duplicated efforts here. IMHO the ones, who can do it best may be the ones sending PRs in. So maybe you can expand your guide (and maybe add a Pull Request template and "Contributing.md" [GitHub now notices people when that file changed], because not everybody reads the wiki, so noticing them directly when they create the PR may be the best.

So they then know that, when the PR is merged, may do two more things: adjust the wiki, and the JSON
Or we make one "generatable" out of the others… but that is hard.

**Comment by goldfndr** [comment]
@matkoniecz: Thank you for the religion list. You did miss one though: multifaith.

@westnordost: Thank you for being cool with the idea and for providing a list of language IDs. I thought that the inclusion of "any" might've been a mistake, but I see that it *is* included in the country data.

All: I've gone ahead with the suggestions and created [my own repository](https://github.com/goldfndr/StreetCompleteJSON). Please take a look at the JSON, and if you can spot any mistakes, let me know (issue or pull). If 48 hours go by without incident, I'll go ahead with submitting a pull request for the taginfo site.

You'll notice that I've added image URLs and initially have them pointing to the OSM wiki's SVGs. I'll probably download them later (next week?) in 16x16 format and host them on the GitHub repository, to save bandwidth on the OSM wiki site (not that I expect a big drain initially).

**Comment by westnordost** [comment]
> You'll notice that I've added image URLs and initially have them pointing to the OSM wiki's SVGs. I'll probably download them later (next week?) in 16x16 format and host them on the GitHub repository, to save bandwidth on the OSM wiki site (not that I expect a big drain initially).

Perhaps you can link the automatically created thumbnails from the wiki. (Can one influence for which sizes thumbnails are generated for a given SVG in MediaWiki?)

**Comment by rugk** [comment]
Hmm just change the URL: 
* 16x16:L https://wiki.openstreetmap.org/w/images/thumb/1/1c/StreetComplete_quest_baby.svg/16px-StreetComplete_quest_baby.svg.png
* 32x32: https://wiki.openstreetmap.org/w/images/thumb/1/1c/StreetComplete_quest_baby.svg/32px-StreetComplete_quest_baby.svg.png
* 1x1: https://wiki.openstreetmap.org/w/images/thumb/1/1c/StreetComplete_quest_baby.svg/1px-StreetComplete_quest_baby.svg.png

(also discovered that feature right now 😆)

**Comment by westnordost** [comment]
I am going to close this issue. The JSON for taginfo is being taken care of in this repository:
https://github.com/goldfndr/StreetCompleteJSON

**Comment by goldfndr** [comment]
It's live now. https://taginfo.openstreetmap.org/projects/streetcomplete#tags

I don't know how often the project JSONs are refreshd. I'm guessing daily.

**Comment by westnordost** [comment]
I wonder, is it possible to supply multiline descriptions? I.e. to have instead of this
![before](https://user-images.githubusercontent.com/4661658/36476672-d4eab400-16fe-11e8-8087-99568c0ba190.png)
... something like this ...
![after](https://user-images.githubusercontent.com/4661658/36476681-db811926-16fe-11e8-8408-f5a41d591593.png)

**Comment by HolgerJeromin** [comment]
cc @joto

**Comment by goldfndr** [comment]
That's something that would need to be changed in the taginfo site, not in the JSON. The JSON only specifies an icon and text for a key or tag, I don't know if HTML in the text is supported (parsed as-is vs escaped). Also, having so many rows in the JSON could interfere with paging (i.e. same number of rows on each page, especially on mobile).

**Comment by joto** [comment]
The taginfo JSON format is rather simple. This was on purpose. I'd rather create something that sort-of works, then wait for a perfect solution. Each project has different requirements so it isn't easy to see what changes might make sense for the JSON format. But I am open to suggestions here.

One thing which might or might not make sense for you is having multiple JSON files for each of the Quests instead of having only a single StreetComplete JSON file with everything.

For simplicity, HTML is not allowed in the descriptions.

Project files are usually read daily by taginfo.
