### ISSUE TITLE
Thank you, @westnordost

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#866]
### StreetComplete is so much more than a simple Android app for contributing to OSM

Dear Tobias (@westnordost),
so I want to say thanks for your awesome FLOSS project, StreetComplete. I also like OpenClonk, but to be honest I just like/use StreetComplete much more. 😀 And it is really a great thing, what you've built there.
So being a contributor, issue spotter (😉), or, at the very least, StreetComplete user for some time already, I also know some frustrating times, where I just thought "But why does @westnordost do so??".
But it began very nicely when I discovered that project in [March 2017](https://github.com/westnordost/StreetComplete/issues/53) judging from my first issue. And what was is? A crash report. Well… yeah. Even on Cyanogenmod (seems too far ago…). Fortunately the app's "souls" (my award typos🙄) were fast to fix and I continued to report all sort of issues.
And, I have to admit, I sometimes proposed [very silly](https://github.com/westnordost/StreetComplete/issues/525) quests, altghough [one was even accepted](https://github.com/westnordost/StreetComplete/issues/484) (😜). You made it crystal clear that this wastes your time (you expressed it in a friendler way though) and you were completly right with that. So the community needed to find a solution. We could [ignore quests](https://github.com/westnordost/StreetComplete/issues/525#issuecomment-325120503) or, better, [propose them in a better way](https://github.com/westnordost/StreetComplete/issues/550) with a clear wiki guide and an issue template. IMHO the quality of quest suggestions really raised afterwards (even as more contributors came in) and it also helped me to rethink some of my own quests again.

Since the beginning I've opened more than 100 issues or PRs, invested really too much time (😉) into collecting data for an [orchard quest](https://github.com/westnordost/StreetComplete/issues/368) – which I still have not seen in practise being asked (or maybe I am just always at the wrong position) and [created a wiki page of all quests](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests).
But you did the whole development work there, making StreetComplete a really intuitive app, combined with a coding style, which really cannot be done any better. And that's not just something I say, but something I've seen. Especially the good UX is impressing. I saw and now also always understand that you often needed to reject features, which sound great fat the first glance, but just were not good for the project. At this is great! It's great you keep the original goal in mind, keep the quality high and always think of the (worldwide!) user.
Another thing for any FLOSS project is the community. And I think this also accelerated quickly. Now you always have one or two pull requests open, you've got big features [implemented out of nowhere](https://github.com/westnordost/StreetComplete/pull/655) and many helper websites (yeah, looking at you @ENT8R). So I think you saw that being a maintainer of a more or less big FLOSS project, also always means caring and "maintaining" your community. And well… it seems to have worked quite well. 😊 
You could (thanks to your community again) even handle the one big issue in 2018 so far, the Mapzen shutdown, so I think that shows a big success.

So this is the first year I can say thanks to you at the #IloveFS day and it was not really not hard this year for me to decide that your project is going to be my year's number one at #ILoveFS's day.
Your project is a really nice one, and it is far more than a simple Android app. It's a project contributing back to OpenStreetMap (not only with data, but also with tagging changes and so on), it's a vibrant community for such a new project of that size, it's likely also a great way to learn Java/Android coding, but ultimately it's a big change in contributing to OSM for maybe thousands(?) of users or so. It really changed how I contribute to OSM, and made it a really a easy thing I do not want to miss. I think others see it in a similar way.
So keep up the good work and enjoy it!

Best regards,
rugk

----

(also posted on [thankyouopensource.com](https://www.thankyouopensource.com/letter/271/StreetComplete-is-so-much-more-than-a-simply-Android-app-for-contributing-to-OSM/))

**Comment by exploide** [comment]
> I have to admit, I sometimes proposed very silly quests, altghough one was even accepted

Yeah, and now I have to deal with this... 😉 😂 
![bench](https://user-images.githubusercontent.com/5670236/36251416-6ec7d0a2-1241-11e8-8caf-86bc72677f31.jpg)

No, @rugk is completely right. Thank you and all the contributors for this awesome app. It really helps bridging the gap between the typically tech-affine OSM enthusiast and the average users w/o deep OSM knowledge. 👍

**Comment by CloCkWeRX** [comment]
>  orchard quest
Ah that ones working just fine. Any time I get on my bike near https://www.openstreetmap.org/#map=13/-34.9389/138.7424&layers=N its apples, allll the way down.

**Comment by rugk** [comment]
As for the orchard quest, yeah, I also suspect it's just my usual mapping locations (ehm… cities), which just do not include fields or so.

**Comment by exploide** [comment]
Now that we celebrated the existence of this project, lets do some statistics to see how this app evolved over the last year. 😋 

Probably not the most beautiful graphs you've ever seen, matplotlib can be annoying sometimes, but just in case some of you are interested, here are some monthly stats for StreetComplete (similar to what is done yearly on the OSM stats wiki page).

![changesets](https://user-images.githubusercontent.com/5670236/36268066-de3a05f2-1275-11e8-8ea2-1355ef6903e0.png)
![edits](https://user-images.githubusercontent.com/5670236/36268078-e4cf8356-1275-11e8-93b4-b28968766581.png)
![users](https://user-images.githubusercontent.com/5670236/36268140-12874bd0-1276-11e8-917c-6b18adcf4a76.png)

My interpretation:
First of all, we see the "hype" starting in February/March. The subsequent drop occurs earlier for the changeset count than for the other graphs. This is due to #21 which was resolved in April. Why the later drop for users and edit occurs... Don't know, maybe the "hype" was over. However, the app continued to be popular. I could imagine that the number also decreases in Autumn/Winter due to the bad weather conditions. But this is only a guess. Now for 2018 a new upswing is recognizable 😉

**Comment by ENT8R** [comment]
I can also just add my gratitude and the best wishes for the future!

---

I found the app in the app store last summer during a very long train ride and I was fascinated from the very first moment 😄 It is so easy to contribute useful data to OSM using your application!
As this is my first open source project I'm contributing to, I also want to say thank you to the nice community here on Github 🎉 Keep up the good work!
From the contributors side I can also say that the code quality is really awesome and @westnordost did a really good job there!
I think that this app will have a great future and always new users. The last months, I solved some notes created by StreetComplete using [NotesReview](https://ent8r.github.io/NotesReview/) and I can say that this app is used by a broad range of users:
- Users who may have never heard of OSM but are contributing to it now
- Users who created an account a few years ago and maybe never made an edit but found now back to OSM thanks to this app
- Users who are experienced and just enjoy the simplicity of mapping 😉 

---

**Thank you!**

**Comment by rugk** [comment]
Oh, these graphs are great! Would there be any way to have these automatically generated or so, so that they can be put into the OSM wiki page for StreetComplete). (So have an own stats page.)

As for the "hype" in March, I have an explanation: [StreetComplete has been released in F-Droid](https://gitlab.com/fdroid/fdroiddata/merge_requests/2121) there. AFAIK this is also how I found the project (it very strongly correlates to my first issue, see OP).

> I found the app in the app store last summer 

F-Droid or Google Play?

**Comment by ENT8R** [comment]
> F-Droid or Google Play?

Google Play (searched for OSM editor)

**Comment by exploide** [comment]
> As for the "hype" in March, I have an explanation: StreetComplete has been released in F-Droid there. AFAIK this is also how I found the project

This is also my believing. I stumbled upon StreetComplete because it was shown on the startup activity of F-Droid those days, because it was new or recently updated.

> Oh, these graphs are great! Would there be any way to have these automatically generated or so, so that they can be put into the OSM wiki page for StreetComplete). (So have an own stats page.)

Thanks :) Guess that depends on what you mean with automatically. Plotting this is already mostly automatic but doing this regularly in an automated manner would require a server and maybe wiki access if that was what you have in mind.

Manually, one needs to download the "Latest Weekly Changesets" from http://planet.openstreetmap.org/, then extract the necessary data with the tools that are also used for the OSM wiki stats page (https://github.com/Zverik/editor-stats) probably broken down to months. And the resulting `.lst` files get processed by a Python script I wrote which produced these graphs. I can share this if someone believes it will be useful.

But still depending on what you want to automate, some obstacles might occur. For example if you want to extent the plot monthly, it either develops an impractically width or the spacings will collapse, which renders the whole thing ugly. This would happen to the x-axis labels first, afterwards to the y-point labels.

**Comment by rugk** [comment]
> I can share this if someone believes it will be useful.

Sure, just dump it into a repo. 😄 

How is it done in the OSM wiki for the general OSM data? Is not that also automated.
If not, it does not have to be automated. Maybe one can just put that manually on the wiki page and update it from time to time.

**Comment by exploide** [comment]
Ok, I will have a look on that later, apply a bit of polish and publish it 😋 

The [stats page](https://wiki.openstreetmap.org/wiki/Editor_usage_stats) says it is done manually while the plots and tables are automatically generated.

**Comment by rugk** [comment]
Ah, great. Good to see StreetComplete there, too. The 4th largest editor now in 2017, already. (a steep increase considering others are there for much longer time)

**Comment by exploide** [comment]
Ok, I tried to make this independent of the editor and some other constraints, so it may be helpful for other editors, too. Along with a reasonable documentation in the README, it is available here: https://github.com/exploide/osm-tool-stats

I hope it may be useful. As stated there in the last sentence: It may be necessary to tune the plotting a little bit. Maybe further functionality will be added later. Pull Requests are welcome.

😄

**Comment by westnordost** [comment]
Hui, thank you, @rugk! I did not immediately answer, because I was a bit overwhelmed by this and did not know what to say. Perhaps I can contribute by giving my perspective on it:

I never planned for the app to become that popular. Actually, I would have already been happy if apart from me, a few hundreds of other people would use it as well - one fringe tool amongst many. Instead, there are now over 6000 users from Google Play alone.
This popularity comes with a great deal of responsibility. The more users there are - and rely on the automatisms that the app employs - the more impact a systematic error in the app will have on the OpenStreetMap data. Be it a simple ambiguity in formulation, or an actual bug.

It also means that I feel that most of the time I can put on the project actually goes into things that are connected to maintaining it as a live product. Answering on feedback, requests and bug tickets, communicating with the (rest of) the OSM community, managing translators and their translations, giving feedback to and merging PRs. This is not a role I was expecting.
As a programmer who just wants to code, this is not work that is particularly engaging for me. But it is a work that is anything but thankless. I think I have never before in my life received so much appreciation for something I have done before - I am somewhat overwhelmed by it, to be honest. :-)

And as you (@rugk) mentioned, it is only due to public interest that the closing of Mapzen was overcome so seamlessly, thanks to the other souls that are enthused by the concept of the app and take on developing it further besides me, most of all @ENT8R and @matkoniecz.

By the way, regarding the stats that @exploide posted, bear in mind that the app is a surveyor tool. So, once a user cleared his area of the quests, they are not coming back. So that means that to keep a steady amount of edits, new users must join or quests be added (or both) constantly. Unlike satellite-imagery-based tools like JOSM and iD, where users once enthused about OpenStreetMap will just continue to map other areas if their first area of interest is complete, this is going to happen much less for StreetComplete (and probably Vespucci).
So, this is one argument to somehow advertise for OSM within the app to get more people interested to go deeper into the mapping activity by learning JOSM or iD, joining the forum or mailing lists, reading and extending the wiki etc.
But with any feature, I lack the time to develop these things as fast as I would like to.

**Comment by matkoniecz** [comment]
> this is not work that is particularly engaging for me

If you have any idea for delegating work do not hesitate to ask (for example - you may want to allow somebody trustworthy to triage bugs).

Though as it may help with bug handing it would add additional complexity (for example - what kind of issues this person should close? Obvious duplicates? Ideas going against design goals? Really poor quest ideas?).

**Comment by westnordost** [comment]
@rugk (in particular) is already a big help there, as often he is the first to answer to a request or bug report to point out issues with it (duplication, asking for missing information, not eligible as quest etc). This usually leads to that the reporters close their own ticket if it really is invalid - which is the best approach anyway. More polite than closing it oneself.

Am 16. Februar 2018 17:49:12 MEZ schrieb Mateusz Konieczny <notifications@github.com>:
>> this is not work that is particularly engaging for me
>
>If you have any idea for delegating work do not hesitate to ask (for
>example - you may want to allow somebody trustworthy to triage bugs).
>
>Though as it may help with bug handing it would add additional
>complexity (for example - what kind of issues this person should close?
>Obvious duplicates? Ideas going against design goals? Really poor quest
>ideas?).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/866#issuecomment-366291370

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by JeanFred** [comment]
I would like to chime in here as well to express my gratitude for this app. I am not an expert mapper by any stretch, having only started editing OpenStreetmap a couple of years ago, and although I do use ID (and even tried my hand at JOSM), StreetComplete is my favourite surveying tool, which I use pretty much everywhere I go.
(Funnily enough, my phone broke down around last November and since then I have been using a temporary crappy phone, which has only enough disk space for a couple of apps − StreetComplete is one of them :)

I am very interested in following where this app is going, and as such read pretty much every discussion on every issue (just don’t have anything to say). One thing that struck me very early on, is how you, @westnordost, have such a solid vision for StreetComplete, and how you (always tactfully!) push back on feature/quest  requests that would not fit into SC’s workflow. I think SC is such a healthy free-software project thanks to that as well. :)

Keep up the good work everyone − it is much appreciated :) I hope to contribute more meaningfully one day to SC’s development.
(Actually, for some reason I have long been mapping bench backrests ; and I had started implementing a quest for that a long time ago − never submitted it as I thought it would be too silly ^_^).

**Comment by rugk** [comment]
> Actually, for some reason I have long been mapping bench backrests

😄 

> and I had started implementing a quest for that a long time ago − never submitted it as I thought it would be too silly ^_^

Great to see I am not the only one, who thinks such a, somewhat, silly quest makes sense.
And BTW, when there is an issue and it is tagged with "new quest", I'd see that it is accepted for implementation, so you can feel free to submit a PR then. (There can happen nothing worse than that it's declined, so just do. I am sure a not-accepted contribution is still better than no contribution.)

**Comment by westnordost** [comment]
@JeanFred Nice to hear that! :-) Due to some changes, the v4.0 version will be even 2MB smaller than v3.0 ;-)

**Comment by matkoniecz** [comment]
@westnordost In addition I really admire you that by combination of bugfixing, handling PRs and rejecting ideas incompatible with your vision you manage to keep count of open issues below 100.

**Comment by westnordost** [comment]
It's because I have to keep that number below 100 to keep my head from exploding. ;-)

**Comment by rugk** [comment]
Well… let's see how long that works. :smile:

**Comment by rugk** [comment]
For those following this issue, @westnordost shared some Google Play stats: https://github.com/westnordost/StreetComplete/issues/894, BTW.

**Comment by smichel17** [comment]
My turn — Thank You, @westnordost!

StreetComplete helps me stay motivated to get out of my house for some excercise and fresh air (I work from home). It also enables me to contribute to OpenStreetMap, a project I think is important but isn't exactly my calling in life. Before, the learning curve and time investment always put me off of contributing; right now I'm sitting on :star:1297!

On the tech side, I've also been impressed with both the quality of the code base — it's on my short list of apps to consult for "What's the right way to do X?" — and your stewardship of the community. In particular, you've done a great job of rejecting out-of-scope ideas *gracefully*, often along with a well-reasoned explanation for why we that feature doesn't belong in StreetComplete.

I wish I'd gotten back into mapping a few months earlier this year, when I was still in Hamburg; I would have offered to go get a coffee or something. Maybe next time I'm in the area…

> > I have to keep that number below 100 to keep my head from exploding. ;-)
>
> Well… let's see how long that works. :smile:

Two years later — 107!

(out of 1367 total, 8 of them [mine](https://github.com/westnordost/StreetComplete/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Asmichel17))

**Comment by westnordost** [comment]
Hey, thank you @smichel17 , I very much appreciate this feedback :-)

I quit my job a few months back to (among others) work on a few things I wanted to have in the app from the start - the next few updates will be very interesting I think. 
After that, the app will go more or less into maintenance mode (bugfixes, merging PRs, ... but no new features from my side) - as you noticed, I am quite particular about what I think is in and what is out of scope of the app.

You lived in Hamburg? Ha, I thought you were American.

> quality of the code base

This flatters me, because it is very important to me. 
Apropos, there are a few things that I do not use in the code, but would so if I started a new project:
- use LiveData and probably ViewModels, maybe Room or GreenDao
- use Gson or similar instead of Kryo for serialization (better forward compatibility of serialized data)
- probably Navigation (from Android Jetpack)

**Comment by smichel17** [comment]
> You lived in Hamburg? Ha, I thought you were American.

I am, but my girlfriend is studying in Hamburg, so I have visited a few times.

**Comment by smichel17** [comment]
> So, once a user cleared his area of the quests, they are not coming back.

This may take some time :joy: 

![image](https://user-images.githubusercontent.com/6563664/78509213-8fb53180-775a-11ea-98a6-891105a235bf.png)

**Comment by smichel17** [comment]
> In particular, you've done a great job of rejecting out-of-scope ideas *gracefully*

…and at being as even-handed with ideas even when they are presented as poorly as mine in https://github.com/streetcomplete/StreetComplete/issues/3034#issuecomment-879481130. I failed to thank @westnordost for his hard, unpaid work on a feature I'm looking forward to; instead I suggested taking a different approach, which would mean throwing it away — probably more time than I've spent on StreetComplete PRs in total. I didn't respond to the request for implementation feedback and my response could easily have derailed the thread into *another* [long](https://github.com/streetcomplete/StreetComplete/issues/1654) [design](https://github.com/streetcomplete/StreetComplete/issues/2565) [discussion](https://github.com/streetcomplete/StreetComplete/discussions/2457).

It takes ***serious humility*** to turn around and consider the suggestion with an open mind. I'm speechless. Thank you.
