### ISSUE TITLE
using StreetComplete map style in my app

### ISSUE THREAD

**Issue by rwrx** [westnordost/StreetComplete#867]
Hi, StreetComplete is great app. I also like it's map style. Could I use it in my app GPX Viewer PRO - https://play.google.com/store/apps/details?id=com.vecturagames.android.app.gpxviewer.pro ? There is also free version - GPX Viewer, but only GPX Viewer PRO is using Tangram-ES but only for offline maps. Unfortunately I have not enough of time for learning and creating my own map style. 

Also if I may ask you, how long it took for you to learn how to create map style for Tangram-ES to some degree?

Thank you and keep up a good work :).

**Comment by rugk** [comment]
Yet again, mapstyle issues should be reported at https://github.com/ENT8R/streetcomplete-mapstyle.

But the short answer is: Yes, if your whole app(!) is also licensed under the GPLv3 or a compatible license. The reason is that the mapstyle is under [the same license](https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/LICENSE) as StreetComplete.

If you don't know about the GPL, [here is a short _overview_](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) and otherwise I can just recommend the Wikipedia article.

**Comment by ENT8R** [comment]
That's all right what @rugk said.
I just wanted to add that it is actually pretty easy to learn how to write a mapstyle as the documentation is very detailed. I think I created something useful within two or three days...

**Comment by matkoniecz** [comment]
https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/LICENSE has decent summery autogenerated by Github at top.

**Comment by rwrx** [comment]
Thank you a lot for the information. Also I am sorry, I didn't researched that this style has it's own repository. Unfortunately my app is closed source, but anyways thank you for information. I should also learn how to create map style :).

**Comment by rugk** [comment]
…or you open-source your app. 😃
