### ISSUE TITLE
Show un-searched area with some kind of shading

### ISSUE THREAD

**Issue by gdt** [westnordost/StreetComplete#9]
In JOSM, areas without data are crosshatched.   Some visual clue that quests haven't been downloaded within the cache period would be really nice.

PS: the fact that I'm making issues like this is a clue that I have not found anything seriously wrong!

**Comment by westnordost** [comment]
To have areas cross-hatched that haven't been scanned yet goes contrary to the concept of the app:
- The scanning process should be "transparent" to the user in the sense that he should not even get the idea to worry about whether or not an area without quests has been scanned or not. If there are any quests, they should simply be there as if they are a fixed and integral part of the map
- Except for pre-scanning an area for later offline-availability, the app never automatically downloads **all** quest types but only the next important ones. This is mainly because of server quota constraints but also to limit the mobile data usage.

I understand that this is a loss of control, when you come from "proper" editors like JOSM. My goal is, that it does not feel like a loss of control because the app is smart enough, and is trusted to be smart enough, to manage this automatically.
It is valuable to me that you come with this kind of request. I want to ask you, where does this wish come from, what are you missing? Why do you think you need to control the app there (because apparently it does not do automatically what you would like to see)

**Comment by westnordost** [comment]
Ah I see. I will implement such an option. So I keep this issue open until I did so.

Am 24. Dezember 2016 02:45:29 MEZ, schrieb Greg Troxel <notifications@github.com>:
>I have only done pre-scanning for offline usage.  It was not clear that
>it would autodownload at all.  While I see your point about automatic,
>it seems there should be a "download area around current location
>automatically" option, and it can default to checked.
>
>It was in downloading areas ahead of time that I wanted to know what
>was actually blank vs not downloaded.  I was not actually downloading
>for offline use as I have plenty of data, but just exploring.   I have
>yet to have spare time to wander after having found the spare time to
>build and try it :-)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/westnordost/StreetComplete/issues/9#issuecomment-269063306

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by westnordost** [comment]
Hmm, while thinking of how to implement it / how to phrase the option, I am having second thoughts. What use case should this option cover? If someone has a contract that does not grant him much data, he will have mobile data off anyway.
If the use case is only to communicate to the user that by default, quests are downloaded and uploaded automatically, then this would make more sense:
- remove "Upload Answers" and "Scan for Quests here" itmes from the menu
- replace this with an item like "Download for Offline" which presents the user a dialog where he can select which area should be prepared for offline-usage and after he selected the area, **both** quests **and** map data is downloaded so that he can fully use the app in that area while being offline.

**Comment by gdt** [comment]
What I did was to pan around to various places (10s of km away), and select download, which I understand from reading the code downloads all information in z12 tiles that overlap the screen (which is fine and very sensible once I read about it).    It was while doing this pan around that i was unclear whether there were no quests or the data had not been downloaded.  This was particularly unclear as I zoomed out beyond the point at which quests were displayed.   My point was not really to preload for offline use, but to understand quest density and types in various places.  So my motivation was about having a more accurate representation of data, separating "it is known that there are no quests in this area" from "we don't have the data to tell us if there are or aren't quests in this area".

I can understand that you want to make things automatic.  But I don't understand why you want to hide from the user the fact that things that should sometimes be automatically downloaded either have or have not actually been downloaded.   DImming the map to 75% or some light crosshatching in z12 tiles that aren't fresh in the local db seems easy enough and as they change to bright/clear and quests appear people will understand quickly.   This shouldn't happen much as the app really needs to be used as a pedestrian, or maybe a bicyclist that stops.

From a server utilization POV, I suspect it's best not to  auto-download quests when people are just panning around to explore.    As for fully offline usage, I see your point about also downloading tiles (usage policy issues?), but I also wonder about mapsforge.  satstat uses that to show maps offline.  They aren't as pretty but suffice for orientation, and e.g. all of Massachusetts (5M people, 2M buildings) is only 150 MB.

**Comment by westnordost** [comment]
I am not sure if I can answer this to your satisfaction, beyond that [earlier comment](https://github.com/westnordost/StreetComplete/issues/9#issuecomment-269028296) I cannot add much. I think I will let sink what you described to me first for some time. I understand where you are coming from, and I can relate to that, with JOSM, I need and want control. Even when looking at notes, markers on osmose and MapDust, when mapping with HOT, I want to pan the map, look around, **completely** solve all issues / map all boxes.
StreetComplete is a "map completion" tool that may be compared with the above ones but still does not offer this kind of overview. I understand this does not feel good.

As said, I will let sink your critique, but just a few sentences regarding this: The difference to these tools is, that the quests on the StreetComplete map (far away from you) do only become relevant when you are near, because they can only be solved on-site. What (also) does not feel good, is to see an ocean of unsolved issues around you, it can be demotivating - like "I will never be able to solve them all". There are so many different Pokemon out there, it will not be possible to "catch them all", still, players are not demotivated, on the contrary, they get served as many Pokemon as they want to take, one by one. I want to find a balance here - if the user wants to solve many quests, there should always be some, but they should not overwhelm him.

**Comment by westnordost** [comment]
> downloading tiles (usage policy issues?), but I also wonder about mapsforge. satstat uses that to show maps offline. They aren't as pretty but suffice for orientation, and e.g. all of Massachusetts (5M people, 2M buildings) is only 150 MB.

With the map rendering library I use, it is currently not possible to display offline tiles. But it is in development. When they are done, it should be possible to display the map using data in mapsforge format.

**Comment by corsac-s** [comment]
Jumping in on this issue, I think this feature request also helps seeing this application and OSM as an exploration game, a bit like strut app (http://strutapp.com/) whose only “goal” is to uncover map tiles. It unfortunately doesn't exist on Android but I tried it a bit on iOS and I loved it :)

**Comment by westnordost** [comment]
So, I can pretty much certainly say that I will not implement this. Other than what has already been said here, the more important point is that I do not see a way how it is technically possible with the map rendering library this project is using.

**Comment by riQQ** [comment]
This was actually implemented with #4986 (see also #4970).
