### ISSUE TITLE
Add warning when manually adding notes

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#905]
Followup of https://github.com/westnordost/StreetComplete/issues/844 (respectively of https://github.com/westnordost/StreetComplete/issues/844#issuecomment-364666534, which I consider a good idea).

The problem was, in short: Users may add notes for things they don't see on the map, because StreetComplete displays few things.

I would suggest a warning, at least, to make users aware that this is counterproductive:
> Maybe just use the same mechanism as when you try to solve quests farer away. Display a message with a "Do not show again" checkbox before the user can enter a note.
This message should then explicitly state that not all things from OSM are shown on the map and one should re-check that before opening a note…

(already got two upvotes, so think this is a good idea)

**Comment by westnordost** [comment]
Well, what kind of warning? What'd be the text?

**Comment by rugk** [comment]
Text could be:
> You are about to add a note to OpenStreetMap.
> Please consider that StreetComplete does not display everything, which is added in OpenStreetMap. Before writing about something, you see is missing, please consult another OpenStreetMap app to check whether it is already displayed.

> Also, how big of a problem is this?

Good question. We'll likely see…

/cc @RubenKelevra

**Comment by ENT8R** [comment]
I think that this is pretty good! I encountered some users who were surprised that SC creates a new note if they can't answer the question... Perhaps the wording there should be clearer too...

Regarding your text: I think there should not be a comma before "which" and before "you see is missing"...

**Comment by rugk** [comment]
Actually I only thought of this text when manually adding a note, not when canceling a quest ("cannot answer").

**Comment by ENT8R** [comment]
Maybe we don't need an extra alert dialog there, but there were some users surprised that they left a new note if they clicked on "Can't Answer". Actually, the wording is pretty clear to me, so I have no suggestion on how to to it better...

**Comment by rugk** [comment]
Yet again: I am not talking about the "Can't answer" dialog. That may be a different issue… I am talking about manually leaving a note with the bottom left button in the 4.0 version.

**Comment by rugk** [comment]
Was that enough feedback?

**Comment by matkoniecz** [comment]
@rugk Can you give examples of notes that should be discouraged by this warning?

**Comment by rugk** [comment]
Ask @RubenKelevra, who originally had the origin idea.

**Comment by matkoniecz** [comment]
@RubenKelevra Can you give examples of notes created using StreetComplete that should be discouraged by this warning? I think that it is problem big enough to justify time to create and maintain something that will be just irritating for 99% of users (and probably be ignored anyway be people creating notes like that).

**Comment by RubenKelevra** [comment]
Well, users usually want to add missing features to the map, so if you see something and you don't find this feature rendered they might add a note like "here's a shop called Rumpelkiste". Which might already mapped, but is not rendered in SC.

**Comment by matkoniecz** [comment]
> they might add a note like "here's a shop called Rumpelkiste"

But is it really happening? I think that adding highly obnoxious warning, just because MAY add useless note is a poor idea. 

Given that no POIs are rendered I expect that only extreme minority would make this kind of mistake and that anyway vast majority of such notes would be added by people who spotted something new in their neighborhood (so such note would be anyway useful).

Such warnings should be added only if where it is really useful, not just because it in theory maybe may be useful.

**Comment by goldfndr** [comment]
At least a couple of notes have been created due to ENTR8/streetcomplete-mapstyle#55. Like [1345405](https://www.openstreetmap.org/note/1345405) and [1345413](https://www.openstreetmap.org/note/1345413) (both by the same person). The notes created this way are only detectable by searching for lut.im (if they have a photo) because StreetComplete is not mentioned.

**Comment by matkoniecz** [comment]
In that case warning also would not be useful, as roads are generally displayed...

**Comment by RubenKelevra** [comment]
@matkoniecz yes, this is really happening.

A different example:

https://github.com/westnordost/StreetComplete/issues/844#issuecomment-364649539

Maybe we should display it on the first creation of a note freely on the map, and a "dismiss for this session" button. But it's really important to add this information.

SC have a huge potential to be the first editor by newbies. I've showed it to 3 people and they started mapping with them, by solving tasks, because they love the idea of having a free world map like Wikipedia.

So we have to make some compromises here and there in SC to accommodate the uses by users who haven't ever seen OSM raw data or know what a simplified rendering is. All they probably know is Google Maps, which shows POI, our rendering not. 😉

**Comment by westnordost** [comment]
It'd also be possible to have a checkbox within this warning dialog to _never_ show this message again. And, it would also be possible to i.e. only show this checkbox on the Xth time the dialog was shown.

**Comment by RubenKelevra** [comment]
I like this second approach, maybe 10 times is a good start? So in 10 sessions the dialog need to be closed before the user is able to hide it permanently. In this case we're sure, he probably read it more than one time.

**Comment by RubenKelevra** [comment]
Another thing is, notes just created don't appear on the map. And refreshing don't load a demo note I've just created either. There seems to be a somewhat substantial database delay, so writing them to the local cache after creation would be nice. :)

**Comment by rugk** [comment]
> Another thing is, notes just created don't appear on the map. And refreshing don't load a demo note I've just created either. 

This is issue https://github.com/westnordost/StreetComplete/issues/962. Please comment/vote/discuss that feature there.

**Comment by westnordost** [comment]
StreetComplete is mentioned in notes since v5.0. So, have StreetComplete-initiated user notes become a problem?

**Comment by matkoniecz** [comment]
not in my area, I have spotted no issues when I sometimes checked recently added notes worldwide

**Comment by ENT8R** [comment]
I also resolved some worldwide notes and only one or two users said in a note that a feature would be missing even though it was simply not displayed on the map of StreetComplete. So I would say that this is not that kind of a big issue...

**Comment by westnordost** [comment]
Ok I'll close it then
