### ISSUE TITLE
Custom Tabs for OSM Auth?

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#906]
What about using Custom Tabs for OAuth? They don't open in a new "strict" window, but are still a kind of external browser.

Chrome/ium and Firefox on Android (since v57) support them.

https://developer.chrome.com/multidevice/android/customtabs

~~Maybe it would also help https://github.com/westnordost/StreetComplete/issues/413. (the ones affected by LineageOS' default browser Gelly, which does not work for OAuth with OSM)~~ (Probably would not help.)

**Comment by ENT8R** [comment]
But what if the user only wants to use Gelly and has no other browser installed?

**Comment by rugk** [comment]
When the user only has Gelly we cannot help anyway. And I also now see that it does not help in such a case, even if there would be another browser installed, because Custom Tabs always use the default browser. (AFAIK, at least)

So okay, maybe not a fix for that Gelly issue, but generally a nice thing. Looks integrated, is faster and fulfills the requirement of an external browser for OAuth. (And does not use the ugly WebKit)

**Comment by westnordost** [comment]
No, I do not want to include another dependency (from Google) for that. I already looked into the customtabs stuff and I find it incomprehensible why they need to introduce a library for coloring the address bar and the like instead of just offering standardized intent parameters to achieve the same (probably that is what they do under the hood?). This is unnecessary complexity.
