### ISSUE TITLE
Quest: Amenity=cafe/pub/bar/restaurant/fast_food without website

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#92]
Websites often feature info like opening hours, contact, etc.
They are often on menus, shopfronts, and more (at least in Australia).

Overpass query:
http://overpass-turbo.eu/s/o3f (Well, the start of it at least)

**Comment by westnordost** [comment]
I'm sorry, I will definitely not implement this. Perhaps in conjunction with general contact data (phone number, website etc), but also that probably not.
The reason is that the StreetComplete app should offer as few as possible "false positive" quests, meaning as few as possible quests that you cannot answer because the assumption the quest is based on is incorrect. 
The incorrect assumption here is that the vast majority of these amenities will have a website.

**Comment by CloCkWeRX** [comment]
Could quests be given geographical bounds perhaps or some other criteria that increases likelyhood?

I'd suggest that in most cities with high smartphone uptake, there'd be a 70% or higher rate of a cafe/pub/bar/restaurant/fast_food having a website or web presence (though distressingly, a lot of the time that's a facebook page; sigh).
I'd suggest a web presence is very likely with large brand/chains of fast food.

I agree that a rural area with no connectivity it would be less likely for a local bar to have a website.

Alternatively; only prompting for this if internet_access=wifi is available would push it into the "very likely to have a web presence" category?
Or delivery=yes (thus more likely to have an online menu)?

**Comment by rugk** [comment]
Suggesting something similar in https://github.com/westnordost/StreetComplete/issues/454…

**Comment by HolgerJeromin** [comment]
Tagging website is done by me in 95% all cases later. I google for the name and the city name and after checking i got the right website i tag it. Much faster and less error prone (as i copy and paste the working URL).

**Comment by rugk** [comment]
This quest may now be possible to implement, because https://github.com/westnordost/StreetComplete/issues/558 (or, rather, https://github.com/westnordost/StreetComplete/pull/672) is resolved.

We now handle **indoor quests** by disabling them by default and allowing users to enable them in the settings.

(@westnordost reopen…?)

**Comment by matkoniecz** [comment]
> (@westnordost reopen…?)

already clearly rejected for a different reason:

>  I'm sorry, I will definitely not implement this. Perhaps in conjunction with general contact data (phone number, website etc), but also that probably not.
> The reason is that the StreetComplete app should offer as few as possible "false positive" quests, meaning as few as possible quests that you cannot answer because the assumption the quest is based on is incorrect.
> The incorrect assumption here is that the vast majority of these amenities will have a website.
