### ISSUE TITLE
Refactoring: Split out quests (queries) and common quest UI forms

### ISSUE THREAD

**Issue by CloCkWeRX** [westnordost/StreetComplete#93]
A lot of quests will likely fall into a number of different ways to answer them:
 * String input (single answer)
 * Integer input  (single answer)
 * Picture selection  (single answer)

with others remaining more complex and deserving dedicated UI.

For example:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/road_name/AddRoadName.java

and
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/place_name/AddPlaceName.java

both have similar string input results, lookups, etc.

Once you have 3-4 of a particular kind, it would be good to refactor those to a "String question input" or similar component; *and pull the question text, overpass query, and other UI labels out to a JSON or YAML file*.

By splitting up the quest and the UI, it'd be a lot easier for people to go from quest template (#86) to pull request.

I'm not suggesting make *everything* like this, but for common answer types it could rapidly expand the number of askable questions.

It may introduce difficulty with i18n, and there's a risk of inner platform effect kicking in; but done carefully it could be useful.

Psuedocode 'name' quest:

```
{
  "title": "Restaurant missing name",
  "title:en" "Restaurant missing name",
  "question": "What is the local language name for this restaurant?",
  "question:en": "What is the local language name for this restaurant?",
  "quest.type": "string.single_answer",
  "answer.quests.name.noname": true,
  "answer.quests.canttell": true,
  "answer.quests.add_note": true,
  "answer.osm_tag": "name",
  "overpass.query": "(amenity = restaurant) and !name and noname != yes",
  "commit_message:en": "Added name to Restaurant"
}
```

and the quest handling code would start to look like
```
# Load all quests:
Dir("./quests/string/single_answer/*.json).each do |file|
  quests << new StringSingleAnswerQuest(JSON.parse(file))
end

public class StringSingleAnswerQuest extends OverpassQuestType {
   public StringSingleAnswerQuest(JSON configuration) {
     // ...
     this.setOpenstreetmapTag(configuration.openstreetmapTag);
     this.setTagFilter(configuration.overpassQuery);
   }

   @Override public Integer applyAnswerTo(Bundle answer, StringMapChangesBuilder changes) {
      String inputAnswer = answer.getString(StringSingleAnswerForm.ANSWER);
      if(inputAnswer != null) changes.add(this.getOpenstreetmapTag(), inputAnswer);
      return this.getCommitMessage();
   }
}
```

For debugging, 'open this query in overpass turbo' would be a useful control to add to these generic forms.

**Comment by westnordost** [comment]
Hmm, thank you for your input.

Every form for each quest is (planned to be) so customized for that quest, that I do not see that it would make sense to put any information out of the Java code. In my opinion, that will rather limit future contributions to fit into this JSON defined frame instead of enabling the contributors to create an input form customized and optimized for adding the information necessary in the maximum comfortable way.

A theoretic quest that would only consist of one normal edit text would also in Java just consist of a few lines of code. Of course there is place in the project for reusable components and there are already some, like i.e. the grouped imaged selector, but they can be used just as easy in Java.

Point is, if someone were to contribute quests (finding quests, user interface, ...) to this project, he wouldn't come too far without Java anyway. Quests that require no special UI and are easy to find using the query are something I can also write up in a few minutes myself.
Don't think there are so few quests right now because it's hard to add them, there are so few quests around because this is the beta phase and there are currently more pressing things to do. Also, certain quests will have certain prerequisites that are not implemented yet, for example the "housenumber" quest is not representable solely through an overpass query but an algorithm (in Java) needs to further search through the downloaded data before creating the quests.
