### ISSUE TITLE
Show manually created notes (with bottom left button) on map

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#962]
SC v4 does not show the manually created notes on the map, after creation. I think it should (just as a notes quest – the `?` icon) directly after creation, because of the following reasons:
* show visual feedback to the user (so they know it worked)
* allow users to "adjust" (add comments) to a thing, if they see something new, made a mistake, need to correct something, etc.
* maybe in the future (as not implemented right now, AFAIK) allow them to close note (same reason as point 2)
* prevent them from making such a note again at the same position, when they go there later and forgot about the note

**Comment by westnordost** [comment]
Well they don't see the solved quest neither.

**Comment by rugk** [comment]
Yeah, but quests are a different thing. These do not need correction, these will not be recognized again by the user, these are just gone and they are even a different "flow" in the UI (the manual notes thing is an extra button).

I'd also have another argument from an UI perspective. Currently when the user creates such a note:
* in an "exiting" animation (:wink:) a quest-like-icon pops up from the top
* the user positions the thing
* the user writes a note and clicks on OK

Current result: The marker disappears. (user reaction: :open_mouth:)
Should be: The marker is finally set as the whole animation/stuff before implies.

Because the note thing is – more or less – adding a "quest", not solving it. So it is kinda the "reverse action".

> (Or is it "either", by the way?)

https://dict.leo.org/forum/viewGeneraldiscussion.php?idThread=627264&idForum=4&lang=de&lp=ende

**Comment by TO-92** [comment]
>  (user reaction: :open_mouth:)

Yep, that happened to me, too. I find it really confusing that you cannot see your own notes. It might even lead users to think "oh, that did not work" or "I could swear I left a note here last week, but maybe that's just my imagination" and then add the same note multiple times.

(As an aside talking about duplicates, I also think the button to leave a note should only be shown when the user has enabled the option to display all notes on the map. Otherwise they might leave a note for something that someone else has already commented on.)

**Comment by rugk** [comment]
And BTW, when it is implemented all own notes may be shown with the "!" icon (even when opened in another tool), so users do not get confused.

**Comment by RubenKelevra** [comment]
The notes just displayed like all other notes would be nice. Everything above is a bit overkill I guess. :)

**Comment by exploide** [comment]
On the other hand, SC does not show notes where you participated. So this would be kind of inconsistent.

**Comment by rugk** [comment]
But AFAIK it shows notes, which you have _created_.

**Comment by rugk** [comment]
That is an option in the setting, but AFAIK SC also does not refresh the stuff so fast, so you won't see the notes you just added via StreetComplete.

So let's focus on this issue and I think, it does need special handling in the code anyway. This issue is "Show manually created notes in StreetComplete on the map after creation.". That's it. Not more, not less.

**Comment by blipp** [comment]
By “manually created notes”, do you also mean notes created by answering “Can't say”to a question? Because then I consider myself affected by this issue:

Some time ago I created some notes via “Can't say” on some road surface questions. Now I gained additional knowledge (ENT8R answered to one of my notes) and could answer the questions and mark the notes as done. But StreetComplete doesn't show neither the questions nor the notes. Which at the time I originally answered the questions was completely reasonable and expected, because back then these questions were done from my point of view. Now however, I would like to see them again.

I have “Show all notes” activated. I think I activated it right away when I installed StreetComplete.

You can see the notes I created here https://www.openstreetmap.org/user/bblipp/notes.
Interestingly, _one_ of the _questions_ I added a note for was shown again. I answered it and marked the note done on the OpenStreetMap website. It was this one https://www.openstreetmap.org/note/1282132.

Maybe StreetComplete could provide a list of notes created, with the option to re-answer them, or add more comments.

**Comment by rugk** [comment]
> By “manually created notes”, do you also mean notes created by answering “Can't say”to a question? 

No, I don't.

So to clarify yet again:
* **Can't say** notes are created when the user just cannot answer a question. These may *not* need to be shown on the map. And if you want so, please ope a new issue.
* The notes created by the bottom left button are the ones I call **manually created notes** as the user actively has to click that button and write a note.

IMHO these note types are quite different. While the first one should not be problematic to just hide – because the quest is not shown again and the user cannot answer/add the same note again.
Also, said said, the animation for the "manually created note" also implies a note is set to a place you choose. And when you press "OK", it is just hidden. There is no information about whether that actually worked or if there was some error.

BTW:
> I have “Show all notes” activated. I think I activated it right away when I installed StreetComplete.

Then all your notes should be shown. Maybe it takes some days, as they are likely cached.

**Comment by westnordost** [comment]
Implemented some feedback on creating a note.
(I do not plan to implement showing the created note to users.)

**Comment by rugk** [comment]
BTW what I've also experienced in the past is, that I've created a note and then looked around and found some other detail I wanted to add. However, I had to spam OSM with notes on the same place, as I just could not add/comment the details to the existing note, I've just created. Obviously this was not a good situation for anyone (neither OSM nor me, i.e. UX).
