### ISSUE TITLE
Retain zoom level after finishing a quest

### ISSUE THREAD

**Issue by TomJansen** [westnordost/StreetComplete#965]
I like to zoom out a bit and see more of the map when doing quests. But now, after I click on and finish a quest, the app zooms in again (to the default zoom level). It would be better if the app jumped back to the zoom level it was in before.

**Comment by westnordost** [comment]
It zooms in to the quest so that you can see where it is exactly and the dimensions of it.

**Comment by rugk** [comment]
That's not the issue. The issue is this (arbitrary numbers):
0. App started with zoom level 12.
1. User zoomed around to level 8.
2. Clicks on quest -> zooms in, as expected, to level 15, e.g.
3. User solved quest

What happens: App zooms to level 12.
What should happen: App zooms to previously remember zoom level, i.e. level 8.

**Comment by TomJansen** [comment]
yes, what @rugk said is what I meant

**Comment by westnordost** [comment]
The described behavior is already present, with the limitation that it will not zoom back out to more than 17.5.
This is deliberate, because when a user zooms to look at a certain quest, he is likely to want to look around in the vicinity rather than be catapulted back onto metropolitan-area-zoom-level. So, I will not change this for now.

**Comment by cyclingcat** [comment]
I want to support this suggestion! I often use SC while riding one of my bikes, so I zoom out a little bit in order to find interesting places with many quests. I leave the map zoomed out for a better overview and it's a little annoying having to restore "my" zoom level after each and every quest manually.

So I would vote +1 for this suggestion, a least as an option in the settings (perhaps leaving the current behaviour as default).

The cycling cat

**Comment by rugk** [comment]
> So I would vote +1 for this suggestion, 

BTW you can (alos) just upvote the top-most "comment" (i.e. the actual issue) at the top. There is a :+1: for this exact thing.

**Comment by westnordost** [comment]
Okay since so many people voted for it, let's try it out.

The app will now always zoom back to the previous zoom, regardless of what level it was.

**Comment by pkoby** [comment]
This works great when it does work. However, I'm finding that when I have geolocation on (so it sticks to my position) it does not return to the original zoom. I guess this might be because it recenters on my position, which probably uses a different bit of code to keep the zoom at 17.5.

**Comment by rugk** [comment]
@pkoby If you can reproduce this and give an exact example where it fails (or video or so), better open a new issue.
