### ISSUE TITLE
Mild rendering error

### ISSUE THREAD

**Issue by gappleto97** [westnordost/StreetComplete#969]
When I go to specific zoom levels on circular pools they begin to morph into star shapes. Pretty sure that this isn't on you, but I dont know how to determine if this is an upstream issue or not. Or who upstream is, for that matter.

![example](https://i.imgur.com/kpBTMAG.png)

_Sent from my Pixel 2 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by matkoniecz** [comment]
See https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md

> Map style used by StreetComplete is developed as a separate project and related issues should be reported there.

That links to https://github.com/ENT8R/streetcomplete-mapstyle

**Comment by matkoniecz** [comment]
It is also reported and closed as https://github.com/ENT8R/streetcomplete-mapstyle/issues/46 - so either it was fixed and not released yet or this problem is back.

Anyway this issue should be closed and if fix for https://github.com/ENT8R/streetcomplete-mapstyle/issues/46 is already included - it should be reported on https://github.com/ENT8R/streetcomplete-mapstyle/issues

**Comment by ENT8R** [comment]
Right. @westnordost said in https://github.com/ENT8R/streetcomplete-mapstyle/issues/46#issuecomment-364710299

> I think the pool problem will not be fixable.
