### ISSUE TITLE
Parking fee is not directly asked after solving parking access quest

### ISSUE THREAD

**Issue by rugk** [westnordost/StreetComplete#976]
STR:
1. Solve parking type, and, afterwards, parking access quest.

What should happen:
Parking fee quest should popup automatically.

What happens:
The auto-quest-opening only works for other quests (e.g. parking access), but not for the parking fee quest.

SC 4
LineageOS 14.1

**Comment by matkoniecz** [comment]
What was the answer in access quest? Parking fee is not asked for private parkings ( https://github.com/westnordost/StreetComplete/blob/7c593607bbf1797ca05ac62a288d54ad86492e92/app/src/main/java/de/westnordost/streetcomplete/quests/parking_fee/AddParkingFee.java )

**Comment by rugk** [comment]
> What was the answer in access quest?

Ah, yes, forgot to mention. Of course, it was public.

> Also, maybe fee was specified already

No, actually the icon did appear on the map, but the quest did not auto-open. I could reproduce this in several cases.

**Comment by westnordost** [comment]
From the description, looks like a bug. Though, a low-priority one because the auto-opening of the next-quest is somewhat of a stepmother-feature right now. I.e. I am not sure if we want to keep it in the future.

**Comment by westnordost** [comment]
Does this still appear for v5.0-beta1?

**Comment by rugk** [comment]
Could not test the beta, because the stable has the same name – and even though they have different signatures (which is good, I don't want to upgrade my stable version) – Android seems to decline to install that version.

**Comment by exploide** [comment]
AFAIK it's about the Java package name. `de.westnordost.streetcomplete` must be unique on a device.

**Comment by exploide** [comment]
Luckily I found my old phone with Android 5.1.1, which I could use to test SC 5.0-beta1.

The bug is not fixed. I tested with approx. 30 parking areas (of course w/o uploading). I realized the following:

- auto opening of street quests (surface, maxspeed, bicycle) works as expected
- auto opening from parking type to parking fee works
- auto opening from parking type to parking access works
- auto opening from parking access to parking fee does not work
- auto opening from parking access to parking type does not work (before I changed priorities) (so it seems it's the access quest that contains the problem?!)
- opposed to stable SC on my primary phone, with beta the not automatically opened quests do not appear on the map at all. This looks like an additional bug, since with all the 30 parking areas I tested, once I answered one quest or the auto-opened chain of 2 quests, the remaining did not appear.

I did not fully understand what was happening with the last point. Maybe the old Android or any side effect?! Would be great to see if someone else can reproduce.

**Comment by westnordost** [comment]
Ok, found the problem. It is not a bug. Perhaps a missing feature, but I don't think I can do anything about it:

1. New quests are only unlocked **after upload** of the solved quest, not before. This is because the new quest can only be unlocked on the basis of the element changed after the quest has been solved. These changes however are only applied to the element just before upload - for easy conflict resolution, StreetComplete does not keep the complete changed element in local storage until upload but only the (tag) changes made to it (`StringMapChanges.java`). This is especially important when there are several quests that make changes on the same element.
2. The parking fee quest requires parking lots to have `access=yes` in order to be shown.
3. The next quest is only shown directly on solving the previous quest if it is present already (has been downloaded before) or has been directly unlocked because the solved quest had been uploaded directly on solving it.

Thus, the parking fee quest is not shown because since the access was not set, it wasn't downloaded before and it also wasn't unlocked yet since the solved parking access quest was not uploaded yet.

I already thought about loosening the restriction of point 1 there, but this would lead to too many difficulties. Because, what this means is to have changes for quests that build on top of each other in local storage. In other words, the changes of quest B are only valid if the changes of quest A have been applied (before). But what if there is a conflict on applying the changes of quest A? - the changes of quest B will then be possibly wrong.
